### PR TITLE
Convert errors tracer into a separate package

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Convert errors tracer into a separate package

## Motivation and Context
Part of simplification as part of https://github.com/minio/minio/projects/13

## How Has This Been Tested?
Manually using `go test`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
```
krishna@escape:~/gocode/src/github.com/minio/minio$ cat pkg/test/main.go
package test

import (
	"fmt"

	"github.com/minio/minio/pkg/errors"
)

func Test() error {
	return errors.TraceError(fmt.Errorf("some error"))
}
krishna@escape:~/gocode/src/github.com/minio/minio$ git diff 
diff --git a/cmd/server-main.go b/cmd/server-main.go
index 158e1d09..10f07b02 100644
--- a/cmd/server-main.go
+++ b/cmd/server-main.go
@@ -17,6 +17,7 @@
 package cmd
 
 import (
+       "fmt"
        "net/http"
        "os"
        "os/signal"
@@ -27,6 +28,7 @@ import (
        "github.com/minio/dsync"
        "github.com/minio/minio/pkg/errors"
        miniohttp "github.com/minio/minio/pkg/http"
+       "github.com/minio/minio/pkg/test"
 )
 
 var serverFlags = []cli.Flag{
@@ -153,8 +155,10 @@ func serverMain(ctx *cli.Context) {
        // Init the error tracing module.
        errors.InitError("github.com/minio/minio/cmd.")
 
+       err := test.Test()
+       fmt.Println(err.(*errors.Error).Trace())
+
        // Check and load SSL certificates.
-       var err error
        globalPublicCerts, globalRootCAs, globalTLSCertificate, globalIsSSL, err = getSSLConfig()
        fatalIf(err, "Invalid SSL certificate file")
 
krishna@escape:~/gocode/src/github.com/minio/minio$ 
```

this prints:
```
krishna@escape:~$ minio server export
[/home/krishna/gocode/src/github.com/minio/minio/pkg/test/main.go:10:github.com/minio/minio/pkg/test.Test server-main.go:158:serverMain /home/krishna/gocode/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:github.com/minio/minio/vendor/github.com/minio/cli.HandleAction /home/krishna/gocode/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:github.com/minio/minio/vendor/github.com/minio/cli.Command.Run /home/krishna/gocode/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run main.go:145:Main /home/krishna/gocode/src/github.com/minio/minio/main.go:68:main.main]


```

Expected output is:
```
pkg/test/main.go:10:Test() server-main.go:140:serverMain()
```

**Comment by harshavardhana** [comment]
All requirements addressed take a look again @krishnasrinivas @krisis

**Review by krisis — DISMISSED** [review]

**Review by krisis — DISMISSED** [review]

**Comment by krishnasrinivas** [comment]
@harshavardhana still gives:
```
krishna@escape:~/gocode/src/github.com/minio/minio$ ./minio server ~/export
[/home/krishna/gocode/src/github.com/minio/minio/pkg/test/main.go:10:Test() /home/krishna/gocode/src/github.com/minio/minio/cmd/server-main.go:157:serverMain() /home/krishna/gocode/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:HandleAction() /home/krishna/gocode/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:Command.Run() /home/krishna/gocode/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:(*App).Run() /home/krishna/gocode/src/github.com/minio/minio/cmd/main.go:145:Main() /home/krishna/gocode/src/github.com/minio/minio/main.go:68:main()]
```

**Comment by harshavardhana** [comment]
That is unexpected may be something I am missing on my end. Let me check again.

**Comment by harshavardhana** [comment]
> krishna@escape:~/gocode/src/github.com/minio/minio$ ./minio server ~/export
> [/home/krishna/gocode/src/github.com/minio/minio/pkg/test/main.go:10:Test() /home/krishna/gocode/src/github.com/minio/minio/cmd/server-main.go:157:serverMain() /home/krishna/gocode/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:HandleAction() /home/krishna/gocode/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:Command.Run() /home/krishna/gocode/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:(*App).Run() /home/krishna/gocode/src/github.com/minio/minio/cmd/main.go:145:Main() /home/krishna/gocode/src/github.com/minio/minio/main.go:68:main()]

I think i know what is happening here you are perhaps doing `go build` or `go install` without providing the right values for GOPATH. Let me see if i can somehow support this as well.

**Comment by harshavardhana** [comment]
> I think i know what is happening here you are perhaps doing go build or go install without providing the right values for GOPATH. Let me see if i can somehow support this as well.

i.e if you did `make install` or simply `make` it would work fine.

**Comment by harshavardhana** [comment]
Now tested with new change with or without using `make` both work fine.

```
$ go build
$ ./minio server ~/test
[pkg/test/main.go:10:Test() cmd/server-main.go:158:serverMain() vendor/github.com/minio/cli/app.go:499:HandleAction() vendor/github.com/minio/cli/command.go:214:Command.Run() vendor/github.com/minio/cli/app.go:260:(*App).Run() cmd/main.go:145:Main() main.go:68:main()]
```

```
$ make
$ ./minio server ~/test
[pkg/test/main.go:10:Test() cmd/server-main.go:158:serverMain() vendor/github.com/minio/cli/app.go:499:HandleAction() vendor/github.com/minio/cli/command.go:214:Command.Run() vendor/github.com/minio/cli/app.go:260:(*App).Run() cmd/main.go:145:Main() main.go:68:main()]
```

**Comment by harshavardhana** [comment]
you might have to review again @krishnasrinivas @krisis ?

**Review by krishnasrinivas — APPROVED** [review]

**Review by krisis — APPROVED** [review]

**Comment by harshavardhana** [comment]
This PR is part of the converting gateway into packages POD. Merging this in.

**Pull request merged**
