### PR TITLE
Improved error message for user and access key conflict

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
The server responds with `400 - Invalid Request` when the username is same as the access key while adding the user.

## Motivation and Context
Provide a verbose and meaningful error message for the username and access key conflict

## Regression
No

## How Has This Been Tested?
With steps provided in minio/mc#2670

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_exclamation_mark: [more...](#9470ee82-ef5c-4dbb-80d2-eb78dd19a7b1) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#a669b391-e3d6-472b-8674-42eb61c04dde) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#900115c9-56af-4ff4-9299-5d08bbd97e75) |
| mint-compression-fs.sh | :heavy_exclamation_mark: [more...](#d4d4a969-4172-4b69-8074-901990891e25) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#413fc3b9-b422-483b-97b5-ae77a0cd0051) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#c0e4d911-be2b-4ce5-94d7-abf249b27e15) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#1d61a24c-d003-4b82-b1b2-e75260c15eb1) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#5c26e656-cb59-4cde-afc0-2734c914ae2a) |
<a name="c0e4d911-be2b-4ce5-94d7-abf249b27e15"></a>
### 7190-d74b23f/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a669b391-e3d6-472b-8674-42eb61c04dde"></a>
### 7190-d74b23f/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="9470ee82-ef5c-4dbb-80d2-eb78dd19a7b1"></a>
### 7190-d74b23f/mint-compression-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="5c26e656-cb59-4cde-afc0-2734c914ae2a"></a>
### 7190-d74b23f/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="413fc3b9-b422-483b-97b5-ae77a0cd0051"></a>
### 7190-d74b23f/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="900115c9-56af-4ff4-9299-5d08bbd97e75"></a>
### 7190-d74b23f/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="d4d4a969-4172-4b69-8074-901990891e25"></a>
### 7190-d74b23f/mint-compression-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="1d61a24c-d003-4b82-b1b2-e75260c15eb1"></a>
### 7190-d74b23f/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```

**Review by harshavardhana — APPROVED** [review]
LGTM tested

**Review by poornas — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :x: [more...](#b5babfc4-a6cd-48fb-9a56-f7ec02163eef) |
| mint-dist-xl.sh | :x: [more...](#794b635a-18ab-4f31-95b2-350ba0dd5113) |
<a name="794b635a-18ab-4f31-95b2-350ba0dd5113"></a>
### 7190-02615bd/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32292
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6a9c38c34e64:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 43 seconds
(4/13) Running aws-sdk-ruby tests ... done in 4 seconds
(5/13) Running awscli tests ... done in 1 minutes and 53 seconds
(6/13) Running mc tests ... done in 37 seconds
(7/13) Running minio-dotnet tests ... done in 3 minutes and 8 seconds
(8/13) Running minio-go tests ... done in 1 minutes and 4 seconds
(9/13) Running minio-java tests ... FAILED in 27 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream body, long size, String contentType)",
  "args": "contentType: application/javascript",
  "duration": 19615,
  "status": "FAIL",
  "error": "java.net.SocketException: Connection reset >>> [java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115), java.net.SocketOutputStream.write(SocketOutputStream.java:155), okio.Okio$1.write(Okio.java:78), okio.AsyncTimeout$1.write(AsyncTimeout.java:179), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171), okio.RealBufferedSink.write(RealBufferedSink.java:41), okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171), okio.RealBufferedSink.write(RealBufferedSink.java:109), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:74), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185), okhttp3.RealCall.execute(RealCall.java:69), io.minio.MinioClient.executeReq(MinioClient.java:1097), io.minio.MinioClient.execute(MinioClient.java:1056), io.minio.MinioClient.executePut(MinioClient.java:1399), io.minio.MinioClient.executePut(MinioClient.java:1421), io.minio.MinioClient.putObject(MinioClient.java:3986), io.minio.MinioClient.putObject(MinioClient.java:4078), io.minio.MinioClient.putObject(MinioClient.java:3952), FunctionalTest.testPutObjectUnknownStreamSize(FunctionalTest.java:556), FunctionalTest.putObject_test8(FunctionalTest.java:582), FunctionalTest.runTests(FunctionalTest.java:2998), FunctionalTest.main(FunctionalTest.java:3154)]"
}

Executed 8 out of 13 tests successfully.
```
<a name="b5babfc4-a6cd-48fb-9a56-f7ec02163eef"></a>
### 7190-02615bd/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32728
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 46b72cbedafd:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 1 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 42 seconds
(4/13) Running aws-sdk-ruby tests ... done in 4 seconds
(5/13) Running awscli tests ... done in 1 minutes and 55 seconds
(6/13) Running mc tests ... done in 35 seconds
(7/13) Running minio-dotnet tests ... done in 3 minutes and 14 seconds
(8/13) Running minio-go tests ... done in 53 seconds
(9/13) Running minio-java tests ... FAILED in 25 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream body, long size, String contentType)",
  "args": "contentType: application/javascript",
  "duration": 19372,
  "status": "FAIL",
  "error": "java.net.SocketException: Connection reset >>> [java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115), java.net.SocketOutputStream.write(SocketOutputStream.java:155), okio.Okio$1.write(Okio.java:78), okio.AsyncTimeout$1.write(AsyncTimeout.java:179), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171), okio.RealBufferedSink.write(RealBufferedSink.java:41), okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171), okio.RealBufferedSink.write(RealBufferedSink.java:109), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:74), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185), okhttp3.RealCall.execute(RealCall.java:69), io.minio.MinioClient.executeReq(MinioClient.java:1097), io.minio.MinioClient.execute(MinioClient.java:1056), io.minio.MinioClient.executePut(MinioClient.java:1399), io.minio.MinioClient.executePut(MinioClient.java:1421), io.minio.MinioClient.putObject(MinioClient.java:3986), io.minio.MinioClient.putObject(MinioClient.java:4078), io.minio.MinioClient.putObject(MinioClient.java:3952), FunctionalTest.testPutObjectUnknownStreamSize(FunctionalTest.java:556), FunctionalTest.putObject_test8(FunctionalTest.java:582), FunctionalTest.runTests(FunctionalTest.java:2998), FunctionalTest.main(FunctionalTest.java:3154)]"
}

Executed 8 out of 13 tests successfully.
```

**Pull request merged**
