### PR TITLE
Consider partNumber in GET/HEAD requests

### LINKED ISSUE #9914: GET/HEAD of object with partNumber returns entire object content/length
Peforming a HeadObject or GetObject request against a MinIO server with a specific partNumber specified in the query parameters currently returns the Content-Length (and in the case of GetObject, the content) of the entire object rather than the Content-Length (and content) of the specific part.

This deviates from the behaviour of AWS S3 and the S3 documentation:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html:

> partNumber: Part number of the object being read. This is a positive integer between 1 and 10,000. Effectively performs a 'ranged' HEAD request for the part specified. Useful querying about the size of the part and the number of parts in this object.

 https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html

> partNumber: Part number of the object being read. This is a positive integer between 1 and 10,000. Effectively performs a 'ranged' GET request for the part specified. Useful for downloading just a part of an object.

## Expected Behavior

For example, given an object created with four parts:

`$ cat /tmp/minio/.minio.sys/buckets/test-bucket/multipart/fs.json | jq
{
  "version": "1.0.2",
  "checksum": {
    "algorithm": "",
    "blocksize": 0,
    "hashes": null
  },
  "meta": {
    "X-Minio-Internal-actual-size": "15728641",
    "content-type": "application/octet-stream",
    "etag": "0aa6cdf3a0b42b1eb084600f2b26d5c0-4"
  },
  "parts": [
    {
      "number": 1,
      "size": 5242880,
      "actualSize": 5242880
    },
    {
      "number": 2,
      "size": 5242880,
      "actualSize": 5242880
    },
    {
      "number": 3,
      "size": 5242880,
      "actualSize": 5242880
    },
    {
      "number": 4,
      "size": 1,
      "actualSize": 1
    }
  ]
}`

Performing a head-object request against a specific part should return the ContentLength of the specific part:

`$ aws --profile minio --endpoint-url http://localhost:9000 s3api head-object --bucket test-bucket --key multipart --part-number 1 
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 25 Jun 2020 00:22:22 GMT",
    "ContentLength": 5242880,
    "ETag": "\"0aa6cdf3a0b42b1eb084600f2b26d5c0-4\"",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "PartsCount": 4
}

$ aws --profile minio --endpoint-url http://localhost:9000 s3api head-object --bucket test-bucket --key multipart --part-number 4
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 25 Jun 2020 00:22:22 GMT",
    "ContentLength": 1,
    "ETag": "\"0aa6cdf3a0b42b1eb084600f2b26d5c0-4\"",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "PartsCount": 4
}`

Similarly, performing a get-object request against a specific part should return just the content of that part.

## Current Behavior

Performing a head-object request against a specific part returns the ContentLength of the entire object:

`$ aws --profile minio --endpoint-url http://localhost:9000 s3api head-object --bucket test-bucket --key multipart --part-number 1 
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 25 Jun 2020 00:22:22 GMT",
    "ContentLength": 15728641,
    "ETag": "\"0aa6cdf3a0b42b1eb084600f2b26d5c0-4\"",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "PartsCount": 4
}

$ aws --profile minio --endpoint-url http://localhost:9000 s3api head-object --bucket test-bucket --key multipart --part-number 4
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 25 Jun 2020 00:22:22 GMT",
    "ContentLength": 15728641,
    "ETag": "\"0aa6cdf3a0b42b1eb084600f2b26d5c0-4\"",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "PartsCount": 4
}`

Similarly, performing a get-object request against a specific part returns the entire contents of the object, not just the part.

## Steps to Reproduce

1. Create an object using the multipart APIs that consists of more than 1 part
2. Perform a HEAD or GET request for a specific part with ?partNumber=N or (with the aws CLI) --part-number N

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
The current code doesn't not process partNumber correctly. It is returning 
the wrong content-length and the wrong data. This PR fixes the behavior
though there is no good documentation about partNumber.

## Motivation and Context
Fix https://github.com/minio/minio/issues/9914

## How to test this PR?
```java
package com.mycompany.app;

import com.amazonaws.services.s3.transfer.Download;
import com.amazonaws.services.s3.transfer.MultipleFileDownload;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.ClientConfiguration;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;

import java.io.File;


public class App {

    public static void main(String[] args) {
        final String USAGE = "\n" +
                "Usage:\n" +
                "    App <s3_path> <local_paths>\n\n";

        if (args.length != 2) {
            System.out.println(USAGE);
            System.exit(1);
        }

        String[] s3_path = args[0].split("/", 2);
        String bucket_name = s3_path[0];
        String key_name = s3_path[1];
        String local_path = args[1];

        System.out.println("Downloading to file: " + bucket_name, key_name);

        AWSCredentials credentials = new BasicAWSCredentials("minio", "minio123");
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");

        AmazonS3 s3Client = AmazonS3ClientBuilder
          .standard()
          .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:9000", Regions.US_EAST_1.name()))
          .withPathStyleAccessEnabled(true)
          .withClientConfiguration(clientConfiguration)
          .withCredentials(new AWSStaticCredentialsProvider(credentials))
          .build();


        File f = new File(file_path);
        TransferManager xfer_mgr = TransferManagerBuilder.standard().withS3Client(s3Client).build();
        try {
            Download xfer = xfer_mgr.download(bucket_name, key_name, f);
            xfer.waitForCompletion();
            xfer_mgr.shutdownNow();
        } catch (Exception e) {
            System.err.println(e.String());
            System.exit(1);
        }

    }
}
```
Download a multipart object using AWS SDK java Transfer manager and check the integrity 
of the downloaded file

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]
Awesome tested & LGTM

**Comment by harshavardhana** [comment]
@vadmeste do you think we should add a mint test for this with aws-sdk-java?

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#afa540e7-ac76-459c-9b9e-2ba9993befbe) |
<a name="afa540e7-ac76-459c-9b9e-2ba9993befbe"></a>
### 10618-c97f810/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31911
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 82b61f8f3aa4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 26 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 3 minutes and 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 4 minutes and 10 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 38 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 43 seconds
{
  "args": {
    "bucketName": "minio-go-test-cqeqwr4m5a2tgeqz",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1019,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 11 minutes and 2 seconds
(10/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 44 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 20 seconds
(12/15) Running s3select tests ... done in 39 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10618-c97f810

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
