### PR TITLE
kafka: _MINIO_KAFKA_DEBUG to enable sarama debug messages

### PR DESCRIPTION
**Pull request by vadmeste**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — COMMENTED** [review]
Would it be crazy to hook it up to the tracer as it's own type?

Not sure if there is a big cost by having it enabled, but just skipping if nothing is listening?

**Comment by vadmeste** [comment]
> Would it be crazy to hook it up to the tracer as it's own type?

I would prefer a new API for verbose debug messages in general

**Review by poornas — APPROVED** [review]

**Review by klauspost — APPROVED** [review]

**Comment by klauspost** [comment]
@vadmeste Yeah. My main issue is that

A) This requires a restart to enable/disable.
B) Collecting logs may be "challenging" for some users.
C) Logging doesn't really have any type filtering, so we cannot implement something that is (close to) zero cost when not enabled.

Since traces fixes these that was my goto-thought - though it doesn't really match the "text logging" schema. Let's add this and consider our options.

**Comment by harshavardhana** [comment]
> @vadmeste Yeah. My main issue is that
> 
> A) This requires a restart to enable/disable. B) Collecting logs may be "challenging" for some users. C) Logging doesn't really have any type filtering, so we cannot implement something that is (close to) zero cost when not enabled.
> 
> Since traces fixes these that was my goto-thought - though it doesn't really match the "text logging" schema. Let's add this and consider our options.

This env is mostly never going to be used, but it is needed in very rare situations when you are dealing with saas kaka offering as we recently found during debugging.

**Pull request merged**
