### PR TITLE
honor maxWait heal config when maxIO hits

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
honor maxWait heal config when maxIO hits

## Motivation and Context
maxWait was not honored properly

## How to test this PR?
Check healing speed with only maxWait changes, the
healing speed doesn't change. With this PR it shall
be honored appropriately.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#312fe3b3-d03e-4d5c-8fa4-9f5ee6401341) |
| mint-zoned.sh | :x: [more...](#6dcdfa84-6d9a-4536-9d7c-87c8d1ca8c71) |
<a name="312fe3b3-d03e-4d5c-8fa4-9f5ee6401341"></a>
### 11338-02a28a6/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31661
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2c60c2ea6637:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 7 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 3 minutes and 2 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 55 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 45 seconds
(10/15) Running minio-java tests ... FAILED in 9 minutes and 5 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 176,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:a1058c11-101e-0067-17ef-f15e49000000\nTime:2021-01-24T01:26:22.8102163Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'KQ8pYy6yhyi87IXLLoBqoAV8eGwnuD/86MnVbcoXncw=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:f2ddaced-c5eb-4c83-54e7-98b7d60380b0\nx-ms-date:Sun, 24 Jan 2021 01:26:22 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-1kn6t8b/minio-java-test-9i4ttq\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-1kn6t8b/minio-java-test-9i4ttq?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-01-24T00:51:54Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [f2ddaced-c5eb-4c83-54e7-98b7d60380b0]\n   X-Ms-Date: [Sun, 24 Jan 2021 01:26:22 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Sun, 24 Jan 2021 01:26:22 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [a1058c11-101e-0067-17ef-f15e49000000]\n\n\n, bucketName = minio-java-test-1kn6t8b, objectName = minio-java-test-9i4ttq, resource = /minio-java-test-1kn6t8b/minio-java-test-9i4ttq, requestId = 165D06AD37B02CF3, hostId = 434bcf95-014e-42f7-a623-53c71ddf1f32)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31661/minio-java-test-1kn6t8b/minio-java-test-9i4ttq, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev6.minio.io:31661\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210124T012622Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210124/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 165D06AD37B02CF3\nX-Xss-Protection: 1; mode=block\nDate: Sun, 24 Jan 2021 01:26:22 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 50 seconds
(11/15) Running minio-py tests ... done in 18 minutes and 37 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 22 seconds
(13/15) Running s3select tests ... done in 58 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="6dcdfa84-6d9a-4536-9d7c-87c8d1ca8c71"></a>
### 11338-02a28a6/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30894
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8f401c15c622:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 13 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 5 seconds
(8/15) Running minio-dotnet tests ... done in 58 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 4 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 26 seconds
(11/15) Running minio-js tests ... done in 1 minutes and 2 seconds
(12/15) Running minio-py tests ... done in 3 minutes and 16 seconds
(13/15) Running s3cmd tests ... FAILED in 21 seconds
{
  "name": "s3cmd",
  "duration": "10458",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 10 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 11338-39791d0/gopath/src/github.com/minio
+ git -C 11338-39791d0/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 11338-39791d0/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 11338-39791d0/gopath/src/github.com/minio/minio fetch --quiet minio pull/11338/head:pr11338
+ git -C 11338-39791d0/gopath/src/github.com/minio/minio checkout --quiet pr11338
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/11338-39791d0/gopath
+ make -C 11338-39791d0/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/colinmarc/hdfs/v2 v2.1.1
go: downloading github.com/minio/minio-go/v7 v7.0.7-0.20210105224719-8dddba43079f
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading google.golang.org/api v0.5.0
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/shirou/gopsutil v3.20.11+incompatible
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.5.0
go: downloading github.com/tinylib/msgp v1.1.3
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading github.com/klauspost/compress v1.11.7
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/prometheus/procfs v0.2.0
go: downloading github.com/gorilla/handlers v1.5.1
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/felixge/httpsnoop v1.0.1
go: downloading golang.org/x/net v0.0.0-20201216054612-986b41b23924
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/google/uuid v1.1.2
go: downloading go.etcd.io/etcd v0.0.0-20201125193152-8a03d2e9614b
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading golang.org/x/sys v0.0.0-20201119102817-f84b799fce68
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading golang.org/x/text v0.3.3
go: downloading google.golang.org/grpc v1.26.0
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/minio/simdjson-go v0.2.0
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading golang.org/x/crypto v0.0.0-20201124201722-c8d3bf9c5392
go: downloading github.com/pierrec/lz4 v2.5.2+incompatible
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/lib/pq v1.8.0
go: downloading github.com/prometheus/common v0.14.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/nats-io/stan.go v0.7.0
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/fatih/structs v1.1.0
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/jcmturner/gofork v1.0.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/gomodule/redigo v1.8.3
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading google.golang.org/protobuf v1.23.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20200313005456-10cdbea86bc0
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/klauspost/cpuid/v2 v2.0.3
go: downloading github.com/streadway/amqp v1.0.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading go.opencensus.io v0.22.5
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/klauspost/reedsolomon v1.9.9
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/olivere/elastic/v7 v7.0.22
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/dswarbrick/smart v0.0.0-20190505152634-909a45200d6d
go: downloading github.com/willf/bitset v1.1.11
go: downloading github.com/mailru/easyjson v0.7.6
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/minio/sio v0.2.1
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading go.uber.org/zap v1.13.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/nats-io/nkeys v0.2.0
go: downloading github.com/minio/md5-simd v1.1.0
go: downloading github.com/nats-io/jwt v1.1.0
go: downloading github.com/tidwall/gjson v1.6.7
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/tidwall/pretty v1.0.2
go: downloading go.uber.org/atomic v1.5.0
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading github.com/tidwall/match v1.0.3
go: downloading github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: downloading go.uber.org/multierr v1.3.0
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/nats-io/nuid v1.0.1
# github.com/minio/minio/cmd
cmd/background-heal-ops.go:80:14: maxWait - waitTick evaluated but not used
make: *** [build] Error 2

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#c4e0dfb0-c10a-4f62-a259-e75ac5869811) |
<a name="c4e0dfb0-c10a-4f62-a259-e75ac5869811"></a>
### 11338-a56d3e7/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32488
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 67f32f7fd15c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 7 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 4 minutes and 4 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 43 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 50 seconds
(10/15) Running minio-java tests ... FAILED in 9 minutes and 6 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 171,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:f78f43a0-501e-00ca-2a22-f27e23000000\nTime:2021-01-24T07:30:17.0661192Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'Ips+cmKgXIUYUFaOYCSt/gB704oP3/AAX8xGNVf/O+o=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:e49b17d3-7f4b-47b5-5cbb-c10e502fe444\nx-ms-date:Sun, 24 Jan 2021 07:30:17 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-344r06i/minio-java-test-ulcodb\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-344r06i/minio-java-test-ulcodb?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-01-24T06:55:37Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [e49b17d3-7f4b-47b5-5cbb-c10e502fe444]\n   X-Ms-Date: [Sun, 24 Jan 2021 07:30:17 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Sun, 24 Jan 2021 07:30:16 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [f78f43a0-501e-00ca-2a22-f27e23000000]\n\n\n, bucketName = minio-java-test-344r06i, objectName = minio-java-test-ulcodb, resource = /minio-java-test-344r06i/minio-java-test-ulcodb, requestId = 165D1A88E6A53129, hostId = ddb048b9-e5bd-498c-9e48-45e97c00b269)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32488/minio-java-test-344r06i/minio-java-test-ulcodb, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev6.minio.io:32488\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210124T073016Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210124/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 165D1A88E6A53129\nX-Xss-Protection: 1; mode=block\nDate: Sun, 24 Jan 2021 07:30:17 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 49 seconds
(11/15) Running minio-py tests ... FAILED in 18 minutes and 25 seconds
{
  "name": "minio-py:test_select_object_content",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-2837f0d1-3069-4c06-8f74-62b987d499f4",
    "object_name": "test.csv"
  },
  "message": "InternalError: file not found",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 285, in test_select_object_content\n    for data_bytes in data.stream(10*KB):\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select.py\", line 444, in stream\n    if self._read() <= 0:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select.py\", line 406, in _read\n    headers.get(\":error-code\"), headers.get(\":error-message\"),\nminio.error.MinioException: InternalError: file not found\n",
  "duration": 990
}
(11/15) Running s3cmd tests ... done in 2 minutes and 34 seconds
(12/15) Running s3select tests ... done in 1 minutes and 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by klauspost — APPROVED** [review]
LGTM

**Pull request merged**
