### PR TITLE
Peer/rpc should never honor RPC calls without object-layer

### LINKED ISSUE #6484: Request go routine can crash in notification subsystem code
## Expected Behavior
No go routine crash in the log

## Current Behavior
```

http: panic serving 10.98.94.201:50898: runtime error: invalid memory address or nil pointer dereference
goroutine 100829 [running]:
net/http.(*conn).serve.func1(0xc420595cc0)
        /opt/go/src/net/http/server.go:1726 +0xd0
panic(0x12788a0, 0x202b760)
        /opt/go/src/runtime/panic.go:502 +0x229
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:771 +0x93
panic(0x12788a0, 0x202b760)
        /opt/go/src/runtime/panic.go:502 +0x229
github.com/minio/minio/cmd.(*NotificationSys).send(0x0, 0xc42082d8f6, 0x3, 0xc42082d4d8, 0x3, 0xc42082d850, 0x8, 0x0, 0x0, 0xc420681a60, ...)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/notification.go:420 +0x3a
github.com/minio/minio/cmd.(*peerRPCReceiver).SendEvent(0x2065bc8, 0xc4207f61c0, 0xc42082d94e, 0x0, 0x0)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/peer-rpc-server.go:145 +0x10a
reflect.Value.call(0xc4203f0f00, 0xc4201864c0, 0x13, 0x145a060, 0x4, 0xc42089cf70, 0x3, 0x3, 0x119a6c0, 0x0, ...)
        /opt/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc4203f0f00, 0xc4201864c0, 0x13, 0xc42089cf70, 0x3, 0x3, 0xc420a03540, 0x1, 0x1)
        /opt/go/src/reflect/value.go:308 +0xa4
github.com/minio/minio/cmd/rpc.(*Server).call(0xc4203eb020, 0xc42082d0b0, 0xe, 0xc4208f7500, 0x643, 0x643, 0xc42072a2a0, 0xc420521180, 0x6b22b8)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/rpc/server.go:204 +0x755
github.com/minio/minio/cmd/rpc.(*Server).ServeHTTP(0xc4203eb020, 0x158b640, 0xc4205e4580, 0xc420330200)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/rpc/server.go:245 +0x1c2
github.com/minio/minio/cmd/rpc.(*Server).ServeHTTP-fm(0x158b640, 0xc4205e4580, 0xc420330200)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-rpc-server.go:86 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420369860, 0x158b640, 0xc4205e4580, 0xc420330200)
        /opt/go/src/net/http/server.go:1947 +0x44
github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420184be0, 0x158b640, 0xc4205e4580, 0xc420330200)
        /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107 +0xdc
github.com/minio/minio/cmd.requestIDHeaderHandler.ServeHTTP(0x1580e40, 0xc420184be0, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:742 +0x9e
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1582fa0, 0xc420473b20, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:757 +0xdc
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc4201820c0, 0x1583020, 0xc420473b30, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:628 +0x88
github.com/minio/minio/cmd.rateLimit.ServeHTTP(0xc420461630, 0x1582e20, 0xc4201820e0, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:722 +0x123
github.com/minio/minio/cmd.pathValidityHandler.ServeHTTP(0x1582f40, 0xc420182100, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:615 +0x1b8
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1582f20, 0xc420473b50, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:554 +0xba
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1582ec0, 0xc420473b60, 0x50004000000, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:71 +0xde
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1582fc0, 0xc420182120, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:96 +0xa7
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1582f80, 0xc420473b70, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x8a
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1582e80, 0xc420473b80, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:248 +0x92
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1582f60, 0xc420473b90, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:306 +0x78
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1582f00, 0xc420473ba0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:275 +0x73
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1582e40, 0xc420473bb0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:376 +0x1af
github.com/minio/minio/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc4201821e0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /opt/go/src/net/http/server.go:1947 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1583fa0, 0xc4201821e0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:505 +0xd2
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1583000, 0xc420473c20, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:287 +0x157
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1582e00, 0xc420473c30, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:139 +0xa7
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1582fe0, 0xc420473c40, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:774 +0x8d
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/server.go:115 +0xe7
net/http.HandlerFunc.ServeHTTP(0xc4202196a0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /opt/go/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc420104b40, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /opt/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420595cc0, 0x1592580, 0xc420410ec0)
        /opt/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /opt/go/src/net/http/server.go:2795 +0x27b
```

## Possible Solution
Do not know yet

## Steps to Reproduce (for bugs)
We need to ask @curantes for a reliable way to reproduce

## Context
@curantes reported this bug

## Regression
Do not know

## Your Environment
RELEASE.2018-09-01T00-38-25Z

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Peer/rpc should never honor RPC calls without object-layer

## Motivation and Context
Fixes #6484

## Regression
Not sure

## How Has This Been Tested?
- Couldn't reproduce it
- Theoretical fix with an actual possibility fixed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by balamurugana — APPROVED** [review]

**Review by nitisht — APPROVED** [review]

**Comment by nitisht** [comment]
blocked till mint results are published

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#9529c6fc-3151-42bc-95e3-3b35b57136cf) |
| mint-fs.sh | :x: [more...](#ea576d09-6e3b-4f52-9d4c-89b1606df49f) |
<a name="ea576d09-6e3b-4f52-9d4c-89b1606df49f"></a>
### 6486-c2a3823/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31042
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dc5d5f9e2691:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 57 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 4 seconds
(4/13) Running aws-sdk-php tests ... done in 42 seconds
(5/13) Running aws-sdk-ruby tests ... done in 4 seconds
(6/13) Running mc tests ... done in 20 seconds
(7/13) Running minio-dotnet tests ... FAILED in 47 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.Fail failed. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Minio.Functional.Tests.FunctionalTest.<>c.<ListIncompleteUpload_Test2>b__85_1(Exception ex) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2124
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:line 76
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Invoke() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Throw.cs:line 42
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 83
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 127
   at System.Reactive.Linq.QueryLanguage.<>c__DisplayClass330_0`1.<Create>b__0(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Creation.cs:line 46
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObservable.cs:line 37
   at System.Reactive.ObservableBase`1.ScheduledSubscribe(IScheduler _, AutoDetachObserver`1 autoDetachObserver) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 82
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 126
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 94
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 51
   at Minio.Functional.Tests.FunctionalTest.ListIncompleteUpload_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2122
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 241

Executed 6 out of 13 tests successfully.
```
<a name="9529c6fc-3151-42bc-95e3-3b35b57136cf"></a>
### 6486-c2a3823/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31797
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d45ad76a2466:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 2 minutes and 37 seconds
(2/13) Running aws-sdk-go tests ... done in 2 seconds
(3/13) Running aws-sdk-java tests ... done in 1 seconds
(4/13) Running aws-sdk-php tests ... done in 30 seconds
(5/13) Running aws-sdk-ruby tests ... done in 29 seconds
(6/13) Running mc tests ... done in 5 minutes and 13 seconds
(7/13) Running minio-dotnet tests ... FAILED in 4 minutes and 52 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=We encountered an internal error, please try again.)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=We encountered an internal error, please try again.) ---> Minio.Exceptions.MinioException: Minio API responded with message=We encountered an internal error, please try again.
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 362
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 504
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 350
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 483
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 229
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 740
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1724
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 218

Executed 6 out of 13 tests successfully.
```

**Comment by nitisht** [comment]
@harshavardhana any ideas on why `mint-fs.sh` is failing?

**Comment by harshavardhana** [comment]
No idea most probably after recent dotnet release but I am sure it will run fine, if run second time.

**Comment by nitisht** [comment]
okay, merging this then - as the changes are clearly not relevant to FS mode.

**Pull request merged**
