### PR TITLE
Azure Gateway: Create empty BlockBlob when creating multipart upload

### PR DESCRIPTION
**Pull request by pauln**
I thought that this had already been merged as part of #5198, as @krishnasrinivas [merged it into `krishnasrinivas:azure-listparts`](https://github.com/krishnasrinivas/minio/pull/14), which was the subject of #5198 - but it seems that it was removed from that branch before the PR was merged.  See discussion in #5169.  If there's any chance that a new release could be published after this PR is merged, I would be very appreciative.

## Description
This allows requests such as GetInfo and ListObjectParts to succeed before the first block has been uploaded - thus matching S3 more closely, as S3 does not return a 404 in this situation (as Minio Azure Gateway currently does).

## Motivation and Context
As discussed in #5169, this is required for [tus/tusd](https://github.com/tus/tusd) to be able to use Minio Azure Gateway.

## How Has This Been Tested?
Tested as part of testing #5198.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
Not sure how it got missed out, but looks like that fix is not correct. Because it is creating a 0 byte file in the main name space.

A better fix is:
```
+++ b/cmd/gateway-azure.go
@@ -746,6 +746,11 @@ func (a *azureObjects) ListObjectParts(bucket, object, uploadID string, partNumb
 
        objBlob := a.client.GetContainerReference(bucket).GetBlobReference(object)
        resp, err := objBlob.GetBlockList(storage.BlockListTypeUncommitted, nil)
+       azureErr, ok := err.(storage.AzureStorageServiceError)
+       if ok && azureErr.StatusCode == http.StatusNotFound {
+               // If no parts are uploaded yet then we return empty list.
+               return result, nil
+       }
        if err != nil {
                return result, azureToObjectError(errors.TraceError(err), bucket, object)
        }
diff --git a/cmd/server-main.go b/cmd/server-main.go
```

**Comment by pauln** [comment]
> looks like that fix is not correct. Because it is creating a 0 byte file in the main name space

It's creating an empty BlockBlob, into which the blocks can subsequently be uploaded (and then concatenated).  As it currently stands (without this patch), the BlockBlob is only created when the first chunk is uploaded

> A better fix is:

I did think about implementing it that way when the issue came up, but:

- It would mean implementing the workaround in multiple methods - at least `GetInfo` as well as `ListObjectParts` - rather than simply creating the empty BlockBlob, which is what I'd expect `NewMultipartUpload` to be doing anyway
- It would result in the aforementioned methods then failing to return an error if called on a file/upload which genuinely doesn't exist (which it probably shouldn't)

**Comment by krishnasrinivas** [comment]
@pauln no, empty BlockBlob would not be desirable.

what I mean is, if you call newmultipartupload and not upload any parts, you will create a 0 byte file:
```
krishna@escape:~$ miniodebug multipart new --bucket test --object testobject
{
  "Bucket": "test",
  "Key": "testobject",
  "UploadID": "54c35031301ff13a"
}
krishna@escape:~$ mc ls myazure/test
[2017-11-22 18:45:57 PST]     0B testobject
krishna@escape:~$ 
```

> It would result in the aforementioned methods then failing to return an error if called on a file/upload which genuinely doesn't exist (which it probably shouldn't)

No actually, we have a check that will fail:
```
        if err = a.checkUploadIDExists(bucket, object, uploadID); err != nil {                          
                return result, err                                                                      
        }                                                                                               
```

**Comment by pauln** [comment]
It still seems strange to me that `NewMultipartUpload` doesn't actually create the BlockBlob - but having dug a bit deeper, the `a.checkUploadIDExists` check does indeed seem to cover the case where the multipart upload doesn't exist at all as it's checking for the existence of the metadata object rather than the actual object.

I've tested your suggestion on top of master, and `tusd` seems to be happy with it.  Would you like me to update this PR to use your patch instead, or would you prefer that I close this PR and leave it to you to handle getting your patch in?

**Comment by krishnasrinivas** [comment]
> Would you like me to update this PR to use your patch instead

Yes please, you can send the PR.

**Comment by pauln** [comment]
Since your fix is a completely different approach to dealing with the original issue, I've opened a fresh PR for it (#5230) and am now closing this one.

**Pull request closed without merging**
