### PR TITLE
cli: Make sure to add --help flag for subcommands.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
cli: Make sure to add --help flag for subcommands.

## Motivation and Context
--help is now back and prints properly with command help template.

## How Has This Been Tested?
Manually `minio server --help` 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by balamurugana — CHANGES_REQUESTED** [review]
This is not the right fix
```bash
$ minio --help
NAME:
  Minio - Cloud Storage Server.

DESCRIPTION:
  Minio is an Amazon S3 compatible object storage server. Use it to store photos, videos, VMs, containers, log files, or any blob of data as objects.

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   Start object storage server.
  version  Print version.
  update   Check for a new software update.
  help, h  Shows a list of commands or help for one command
  
FLAGS:
  --config-dir value, -C value  Path to configuration directory. (default: "/home/bala/.minio")
  --quiet                       Disable startup information.
  --help, -h                    Show help.
  --version, -v                 Print the version.
  
VERSION:
  2017-02-19T10:00:56Z

$ minio --version
Minio version 2017-02-19T10:00:56Z

$ minio version
Version: 2017-02-19T10:00:56Z
Release-Tag: DEVELOPMENT.2017-02-19T10-00-56Z
Commit-ID: 4690c42a3942c58ee26098f08a23e7e53c2c56b8

$ minio version --version
Incorrect Usage: flag provided but not defined: -version

NAME:
   minio version - Print version.

USAGE:
   minio version

VERSION:
  2017-02-19T10:00:56Z

$ minio help
NAME:
  Minio - Cloud Storage Server.

DESCRIPTION:
  Minio is an Amazon S3 compatible object storage server. Use it to store photos, videos, VMs, containers, log files, or any blob of data as objects.

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   Start object storage server.
  version  Print version.
  update   Check for a new software update.
  help, h  Shows a list of commands or help for one command
  
FLAGS:
  --config-dir value, -C value  Path to configuration directory. (default: "/home/bala/.minio")
  --quiet                       Disable startup information.
  --help, -h                    Show help.
  --version, -v                 Print the version.
  
VERSION:
  2017-02-19T10:00:56Z

$ minio h
NAME:
  Minio - Cloud Storage Server.

DESCRIPTION:
  Minio is an Amazon S3 compatible object storage server. Use it to store photos, videos, VMs, containers, log files, or any blob of data as objects.

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   Start object storage server.
  version  Print version.
  update   Check for a new software update.
  help, h  Shows a list of commands or help for one command
  
FLAGS:
  --config-dir value, -C value  Path to configuration directory. (default: "/home/bala/.minio")
  --quiet                       Disable startup information.
  --help, -h                    Show help.
  --version, -v                 Print the version.
  
VERSION:
  2017-02-19T10:00:56Z

```

**Comment by harshavardhana** [comment]
@balamurugana I am not sure i understand . Can you clearly write in words what you posted doesn't help me here?

**Comment by balamurugana** [comment]
> @balamurugana I am not sure i understand . Can you clearly write in words what you posted doesn't help me here?

Look at each command execution and its output.

New option `--version` is not useful
```
$ minio --version
Minio version 2017-02-19T10:00:56Z

$ minio version
Version: 2017-02-19T10:00:56Z
Release-Tag: DEVELOPMENT.2017-02-19T10-00-56Z
Commit-ID: 4690c42a3942c58ee26098f08a23e7e53c2c56b8

$ minio version --version
Incorrect Usage: flag provided but not defined: -version

NAME:
   minio version - Print version.

USAGE:
   minio version

VERSION:
  2017-02-19T10:00:56Z
```

Look at below `help` command which is not useful
```
$ minio help
NAME:
  Minio - Cloud Storage Server.

DESCRIPTION:
  Minio is an Amazon S3 compatible object storage server. Use it to store photos, videos, VMs, containers, log files, or any blob of data as objects.

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   Start object storage server.
  version  Print version.
  update   Check for a new software update.
  help, h  Shows a list of commands or help for one command
  
FLAGS:
  --config-dir value, -C value  Path to configuration directory. (default: "/home/bala/.minio")
  --quiet                       Disable startup information.
  --help, -h                    Show help.
  --version, -v                 Print the version.
  
VERSION:
  2017-02-19T10:00:56Z

$ minio h
NAME:
  Minio - Cloud Storage Server.

DESCRIPTION:
  Minio is an Amazon S3 compatible object storage server. Use it to store photos, videos, VMs, containers, log files, or any blob of data as objects.

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   Start object storage server.
  version  Print version.
  update   Check for a new software update.
  help, h  Shows a list of commands or help for one command
  
FLAGS:
  --config-dir value, -C value  Path to configuration directory. (default: "/home/bala/.minio")
  --quiet                       Disable startup information.
  --help, -h                    Show help.
  --version, -v                 Print the version.
  
VERSION:
  2017-02-19T10:00:56Z
```

**Comment by harshavardhana** [comment]
> Look at each command execution and its output.

@balamurugana this is provided by default and no way to turn it off the `help` subcommand.  What is the fixed in this PR is that to provide missing '--help' which went missing in the previous change.  `--version` can be disabled using HideVersion.

Let me send an updated PR removing `--version`.

**Comment by harshavardhana** [comment]
PR is updated take a look once again. @balamurugana

**Comment by balamurugana** [comment]
@harshavardhana I can't understand why we need to use new cli package.
However this is UI change, it should be reviewed by @abperiasamy

**Comment by harshavardhana** [comment]
> However this is UI change, it should be reviewed by @abperiasamy

He will review @balamurugana first give me your reviews. We need to use because it has some fixes as i explained earlier - that is not the issue here.

**Comment by harshavardhana** [comment]
> @harshavardhana I can't understand why we need to use new cli package.

Also FYI it is not a new cli package it is the same package with some updates which have changed functionality which we didn't anticipate - which is also explained by me earlier to you. So rather than circling back to the same thing again and again lets proceed further.

**Comment by harshavardhana** [comment]
The sub-command `help, h` and `--version` flags are gone now.

**Review by balamurugana — APPROVED** [review]
Now main command and subcommands look same as previous.

**Pull request merged**
