### PR TITLE
Fix deadlock in in-place CopyObject decryption/encryption

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Fix deadlock in in-place CopyObject decryption/encryption

## Motivation and Context
In-place decryption/encryption already holds write
locks on them, attempting to acquire a read lock 
would fail.

## How Has This Been Tested?
Manually using `minio-go` tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#c2b7e319-a7dd-4c82-949c-a67f26ae86d7) |
<a name="c2b7e319-a7dd-4c82-949c-a67f26ae86d7"></a>
### 5637-3d56781/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30199
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 497de4bb62f6:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 48 seconds
(3/12) Running aws-sdk-ruby tests ... done in 7 seconds
(4/12) Running awscli tests ... done in 4 minutes and 47 seconds
(5/12) Running mc tests ... done in 1 minutes and 45 seconds
(6/12) Running minio-dotnet tests ... done in 1 minutes and 1 seconds
(7/12) Running minio-go tests ... done in 4 seconds
(8/12) Running minio-java tests ... FAILED in 37 seconds
{
  "name": "minio-java",
  "function": "presignedPostPolicy(PostPolicy policy)",
  "duration": 11943,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: timeout >>> [okio.Okio$4.newTimeoutException(Okio.java:227), okio.AsyncTimeout.exit(AsyncTimeout.java:284), okio.AsyncTimeout$2.read(AsyncTimeout.java:240), okio.RealBufferedSource.indexOf(RealBufferedSource.java:344), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210), okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185), okhttp3.RealCall.execute(RealCall.java:69), FunctionalTest.presignedPostPolicy_test(FunctionalTest.java:1775), FunctionalTest.runQuickTests(FunctionalTest.java:2785), FunctionalTest.main(FunctionalTest.java:2833)]"
}

Executed 7 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#31d625d1-0d6f-49f6-8966-02f1525d4ba7) |
<a name="31d625d1-0d6f-49f6-8966-02f1525d4ba7"></a>
### 5637-b376e6e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32646
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 3fa2cc694808:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 0 seconds
(2/12) Running aws-sdk-php tests ... done in 6 minutes and 25 seconds
(3/12) Running aws-sdk-ruby tests ... done in 57 seconds
(4/12) Running awscli tests ... FAILED in 2 minutes and 47 seconds
{
  "name": "awscli",
  "duration": 6069,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 3 out of 12 tests successfully.
```

**Review by aead — APPROVED** [review]

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by poornas** [comment]
@harshavardhana , can we add a minio-go functional test for this?

**Comment by harshavardhana** [comment]
> @harshavardhana , can we add a minio-go functional test for this?

We already have it @poornas

**Review by poornas — APPROVED** [review]

**Pull request merged**
