### PR TITLE
S3Select: Handle array selection in from clause

### PR DESCRIPTION
**Pull request by donatello**
## Description

Bug fix for #9064 

## How to test this PR?

Just try with the reproducer

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by donatello** [comment]
@klauspost I get an simdjson error on master currently - this PR appears to fix #9064 , but I needed to first turn off the simdjson support.

```
$ mc sql --query "select * from s3object[*].elements[*] s where s.element_type = '__elem__merfu'" myminio/sqlselectapi/issue_9064.json
mc: <ERROR> Unable to run sql InternalError:"Encountered an error parsing the JSON file: parsing input: Bad parsing while executing stage 2. Check the file and try again."
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#a8337a10-5bd2-4673-b8d6-19d094fa6efb) |
| mint-gateway-azure.sh | :x: [more...](#5f75ee35-4d27-4f45-9c23-4607b783f812) |
| mint-gateway-nas.sh | :x: [more...](#c4a024be-dd5f-48bf-8a24-ba2ee7deb6e7) |
<a name="a8337a10-5bd2-4673-b8d6-19d094fa6efb"></a>
### 9076-e02b6f0/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30400
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 276f0406abc8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-lwxlqoc4z4rpl1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120316,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30400/aws-sdk-go-test-lwxlqoc4z4rpl1: dial tcp 72.28.97.55:30400: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5f75ee35-4d27-4f45-9c23-4607b783f812"></a>
### 9076-e02b6f0/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32648
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 25f1e56b19f3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 22 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... FAILED in 3 minutes and 8 seconds
{
  "name": "awscli",
  "duration": 1537,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 14 tests successfully.
```
<a name="c4a024be-dd5f-48bf-8a24-ba2ee7deb6e7"></a>
### 9076-e02b6f0/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31064
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b58f23843608:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ysuq6avlesjm23",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120290,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31064/aws-sdk-go-test-ysuq6avlesjm23: dial tcp 72.28.97.55:31064: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#5619bd6e-7f90-46df-b2b5-c74c06185464) |
| mint-gateway-azure.sh | :x: [more...](#bd810a63-d432-4c75-b429-ca0e07254eab) |
<a name="bd810a63-d432-4c75-b429-ca0e07254eab"></a>
### 9076-5158c91/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32049
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 47e0d0be4750:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 17 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... FAILED in 11 seconds
{
  "name": "awscli",
  "duration": 1528,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 14 tests successfully.
```
<a name="5619bd6e-7f90-46df-b2b5-c74c06185464"></a>
### 9076-5158c91/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31858
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 962c1c3feb48:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 13 minutes and 20 seconds
(10/14) Running minio-java tests ... done in 3 minutes and 32 seconds
(11/14) Running minio-js tests ... FAILED in 19 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, metaData)",
  "args": "bucketName:minio-js-test-332a7305-3700-452a-b18a-4422668ef634, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 1430,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)"
}

Executed 10 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by klauspost** [comment]
@donatello You must specify 'DOCUMENT' mode to test the supplied data. By default it uses 'LINES' which is for NDJSON.

You can test with the sample in the issue.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-worm.sh | :x: [more...](#047cbfad-8d3a-417e-9346-bde2d9065d5f) |
| mint-gateway-azure.sh | :x: [more...](#df673890-8d69-4d2e-b51e-558ae56b0f28) |
<a name="047cbfad-8d3a-417e-9346-bde2d9065d5f"></a>
### 9076-c4c3d6e/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32646
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3940f6df066d:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-yde0cevkxfgaxtolfv7f6b44wrjvni3j1l9fx556rkjp10km3edm80h",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120384,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32646/bucket-yde0cevkxfgaxtolfv7f6b44wrjvni3j1l9fx556rkjp10km3edm80h: dial tcp 72.28.97.55:32646: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="df673890-8d69-4d2e-b51e-558ae56b0f28"></a>
### 9076-c4c3d6e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32269
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cb82f2bb48fe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 38 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... FAILED in 55 seconds
{
  "name": "awscli",
  "duration": 1527,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by donatello** [comment]
@klauspost Added* the reproducer as a test, and updated the output to match that of S3.

This now appears to work.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#9971d063-d993-482a-9158-0ce02360a8b3) |
<a name="9971d063-d993-482a-9158-0ce02360a8b3"></a>
### 9076-b68b4aa/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32597
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6314aa8a60e5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 6 minutes and 4 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 29 seconds
{
  "name": "awscli",
  "duration": 1530,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
Very nice!

**Review by ebozduman — APPROVED** [review]
I've tested the fix in my environment, using the same json file provided in the Issue #9064. 

Expected result is displayed as shown below:

```
$ mc sql -e="select * from s3object[*].elements[*] s where s.element_type = '__elem__merfu'" --json-input type="document" myminio/test/test9076.json
{"element_type":"__elem__merfu","element_id":"d868aefe-ef9a-4be2-b9b2-c9fd89cc43eb","attributes":{"__attr__image_dpi":300,"__attr__image_size":[2550,3299],"__attr__image_index":2,"__attr__image_format":"JPEG","__attr__file_extension":"jpg","__attr__data":null}}
```


With @andreimerfu's python script in Issue #9064:

```
$ python3.7 piton.py 
{"element_type":"__elem__merfu","element_id":"d868aefe-ef9a-4be2-b9b2-c9fd89cc43eb","attributes":{"__attr__image_dpi":300,"__attr__image_size":[2550,3299],"__attr__image_index":2,"__attr__image_format":"JPEG","__attr__file_extension":"jpg","__attr__data":null}}

Stats details bytesScanned: 
932
Stats details bytesProcessed: 
932
```

**Pull request merged**
