### PR TITLE
Register postgre driver in pkg/event/target

### LINKED ISSUE #6688: Unable to activate postgresql
## Expected Behavior
Postgresql should work normally when activated

## Current Behavior
```
API: SYSTEM()
Time: 15:28:43 CET 10/23/2018
Error: sql: unknown driver "postgres" (forgotten import?)
       1: cmd/logger/logger.go:295:logger.LogIf()
       2: cmd/config-current.go:712:cmd.getNotificationTargets()
       3: cmd/notification.go:462:cmd.NewNotificationSys()
       4: cmd/server-main.go:376:cmd.serverMain()
```

## Possible Solution
Revert postgresql import

## Steps to Reproduce (for bugs)
1. Start Minio in new FS mode
minio server /tmp/fs/
2. Get config json with mc
mc admin config get myminio >/tmp/config.json
3. Enable postgre sql
```
    "postgresql": {
      "1": {
        "enable": true,
        "format": "",
        "connectionString": "",
        "table": "mytable",
        "host": "127.0.0.1",
        "port": "5432",
        "user": "",
        "password": "",
        "database": "testdb"
      }
    },
```

mc admin config set myminio </tmp/config.json
```
mc: <ERROR> Cannot set server configuration file. postgreSQL(1): sql: unknown driver "postgres" (forgotten import?)
```

## Context
Bug reported from one user in the community

## Regression
Yes  https://github.com/minio/minio/commit/5c1376516867aeca06f114868e329e1d710f7148

## Your Environment
All

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Commit 5c1376516867aeca06f114868e329e1d710f7148 removed postgre registration triggerd
by the automatic gofmt command but it was the only where pg is registered. This commit
fixes behavior and adds unit tests to check whether postgre & sql are registered or not.

## Motivation and Context
Fixes #6688 

## Regression
Yes, introduced by 5c1376516867aeca06f114868e329e1d710f7148

## How Has This Been Tested?
1. Start Minio in new FS mode
`minio server /tmp/fs/`

2. Get config json with mc
`mc admin config get myminio >/tmp/config.json`

3. Enable postgre sql
```
    "postgresql": {
      "1": {
        "enable": true,
        "format": "",
        "connectionString": "",
        "table": "mytable",
        "host": "127.0.0.1",
        "port": "5432",
        "user": "",
        "password": "",
        "database": "testdb"
      }
    },
```
4. 
```
$ mc admin config set myminio </tmp/config.json
mc: <ERROR> Cannot set server configuration file. postgreSQL(1): sql: unknown driver "postgres" (forgotten import?)
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 6689-9ff6a1f/gopath/src/github.com/minio
+ git clone --quiet https://github.com/minio/minio.git 6689-9ff6a1f/gopath/src/github.com/minio/minio
++ cd 6689-9ff6a1f/gopath/src/github.com/minio/minio
++ git remote add minio https://github.com/minio/minio.git
++ cd 6689-9ff6a1f/gopath/src/github.com/minio/minio
++ git fetch --quiet minio pull/6689/head:pr6689
++ cd 6689-9ff6a1f/gopath/src/github.com/minio/minio
++ git checkout --quiet pr6689
++ minikube ip
+ minikube_ip=192.168.39.64
++ mkdir -p certs
++ cd certs
++ ./cert -host 192.168.39.64
2018/10/23 11:17:56 wrote public.crt
2018/10/23 11:17:56 wrote private.key
+ GOPATH=/mnt/nvme0n1p1/mint-auto/mint-auto/6689-9ff6a1f/gopath
+ make -C 6689-9ff6a1f/gopath/src/github.com/minio/minio --quiet
pkg/event/target/postgresql.go:65:2: cannot find package "github.com/lib/pq" in any of:
	/mnt/nvme0n1p1/mint-auto/mint-auto/6689-9ff6a1f/gopath/src/github.com/minio/minio/vendor/github.com/lib/pq (vendor tree)
	/mnt/nvme0n1p1/mint-auto/.gimme/versions/go1.10.4.linux.amd64/src/github.com/lib/pq (from $GOROOT)
	/mnt/nvme0n1p1/mint-auto/mint-auto/6689-9ff6a1f/gopath/src/github.com/lib/pq (from $GOPATH)
make: *** [build] Error 1

```

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 6689-af3bbf1/gopath/src/github.com/minio
+ git clone --quiet https://github.com/minio/minio.git 6689-af3bbf1/gopath/src/github.com/minio/minio
++ cd 6689-af3bbf1/gopath/src/github.com/minio/minio
++ git remote add minio https://github.com/minio/minio.git
++ cd 6689-af3bbf1/gopath/src/github.com/minio/minio
++ git fetch --quiet minio pull/6689/head:pr6689
++ cd 6689-af3bbf1/gopath/src/github.com/minio/minio
++ git checkout --quiet pr6689
++ minikube ip
+ minikube_ip=192.168.39.64
++ mkdir -p certs
++ cd certs
++ ./cert -host 192.168.39.64
2018/10/23 11:33:59 wrote public.crt
2018/10/23 11:33:59 wrote private.key
+ GOPATH=/mnt/nvme0n1p1/mint-auto/mint-auto/6689-af3bbf1/gopath
+ make -C 6689-af3bbf1/gopath/src/github.com/minio/minio --quiet
vendor/github.com/lib/pq/buf.go:7:2: cannot find package "github.com/lib/pq/oid" in any of:
	/mnt/nvme0n1p1/mint-auto/mint-auto/6689-af3bbf1/gopath/src/github.com/minio/minio/vendor/github.com/lib/pq/oid (vendor tree)
	/mnt/nvme0n1p1/mint-auto/.gimme/versions/go1.10.4.linux.amd64/src/github.com/lib/pq/oid (from $GOROOT)
	/mnt/nvme0n1p1/mint-auto/mint-auto/6689-af3bbf1/gopath/src/github.com/lib/pq/oid (from $GOPATH)
make: *** [build] Error 1

```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by kannappanr — APPROVED** [review]

**Review by donatello — APPROVED** [review]

**Pull request merged**
