### PR TITLE
handle post policy only it is set.

### PR DESCRIPTION
**Pull request by balamurugana**
Previously policy in post form is assumed to be set always.  This is
fixed by doing the check when policy is set.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
is this how S3 API behaves? @balamurugana

**Comment by balamurugana** [comment]
> is this how S3 API behaves? @balamurugana

This is what https://github.com/minio/minio/issues/6844 claims.

**Comment by harshavardhana** [comment]
@balamurugana can you resolve the conflicts. The PR LGTM - I tested the original scenario posted by the user. It looks like we have to relax the strict requirement in our implementation.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by harshavardhana — APPROVED** [review]
LGTM tested with the reproducer steps in original issue

**Review by poornas — APPROVED** [review]
LGTM

**Pull request merged**
