### PR TITLE
add a NoAuth mode that accepts all authentications

### PR DESCRIPTION
**Pull request by kahing**

### CODE REVIEW

**Comment by harshavardhana** [comment]
if you wish to test signature V4 with minio, we are working on the webUI to make it easier to generate access keys.  

For the time being following approach will do 

Start 'minio controller'

```
$ minio controller
```

```
$ go run get-accesskeys-minio.go
```

https://gist.github.com/harshavardhana/747655c2c3a6e6dbdd22

**Comment by harshavardhana** [comment]
Add the values generated to `users.json` created at `${HOME}/.minio/users.json` 

``` json
{
  "AC5NH40NQLTL4D2W92PM": {
    "Name": "kahing",
    "AccessKey": "AC5NH40NQLTL4D2W92PM",
    "SecretKey": "H+AVh8q5G7hEH2r3WxFP135+Q19Aw8yXWel8IGh/HrEjZyTNx/n4Xw=="
  }
}
```

I know all of this is a hassle right now, but until the WebUI gets ready it is really not worth the effort using signature v4. One can just do anonymous requests

**Comment by harshavardhana** [comment]
Better yet , following command will work too. 

``` sh
$ curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "Auth.Get", "params": []}' -H 'content-type: application/json' http://127.0.0.1:9001/rpc
```

**Comment by harshavardhana** [comment]
#844 with this fix, following command will work and you don't have to create a users.json manually, which makes it easier for one to test out signature v4. 

```
$ curl -X POST -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "id": "test", "method": "Auth.Generate", "params": [{"user": "kahing"}] }' http://localhost:9001/rpc
```

JSON RPC reply

``` json
{"result":{"name":"kahing","accessKeyId":"861AIPLTVHOM47TSXH86","secretAccessKey":"6u5VIOVTXTWS52UBlfJ4dvR/ZmRmJFPoVr+Y9XZd"},"error":null,"id":"test"}
```

Use this key to add to your mc configuration

```
$ mc config host add localhost:9000 861AIPLTVHOM47TSXH86 6u5VIOVTXTWS52UBlfJ4dvR/ZmRmJFPoVr+Y9XZd
```

Start minio server

```
$ minio server
```

and you have your own s3 with signature v4.

**Comment by kahing** [comment]
My fault for not providing more context. I am trying to use minio with a project that's done with amazon sdk, which doesn't seem to have a way to not send the `Authorization` header. I am also using minio in a non-conventional way. I am launching it directly from go code inside go test:

```
    addr := "127.0.0.1:9000"
    authConf := &auth.Config{ NoAuth: true }
    auth.SetAuthConfigPath(filepath.Join(t.MkDir(), "users.json"))
    perr := auth.SaveConfig(authConf)
    t.Assert(perr, IsNil)

    go server.Start(api.Config{ Address: addr })
```

The end goal is a local object store that I can use within go test. How do you suggest this use case be handled?

**Comment by kahing** [comment]
Alternatively I tried this:

``` go
    accessKeyID, perr := auth.GenerateAccessKeyID()
    t.Assert(perr, IsNil)
    secretAccessKey, perr := auth.GenerateSecretAccessKey()
    t.Assert(perr, IsNil)

    accessKey = string(accessKeyID)
    secretKey = string(secretAccessKey)

    authConf := &auth.Config{}
    authConf.Users = make(map[string]*auth.User)
    authConf.Users[string(accessKeyID)] = &auth.User{
        Name:            "testuser",
        AccessKeyID:     accessKey,
        SecretAccessKey: secretKey,
    }
    auth.SetAuthConfigPath(filepath.Join(t.MkDir(), "users.json"))
    perr = auth.SaveConfig(authConf)
    t.Assert(perr, IsNil)

    go server.Start(api.Config{ Address: addr })
```

and then

``` go
    s.s3 = s3.New(&aws.Config{
        Credentials: credentials.NewStaticCredentials(accessKeyID, secretAccessKey, ""),
        Region: aws.String("us-west-2"),
        Endpoint: aws.String(addr),
        DisableSSL: aws.Bool(true),
        S3ForcePathStyle: aws.Bool(true),
        MaxRetries: aws.Int(0),
        LogLevel: aws.LogLevel(aws.LogDebug | aws.LogDebugWithHTTPBody),
    })
```

I get `SignatureDoesNotMatch` as a result

**Comment by harshavardhana** [comment]
> Credentials: credentials.NewStaticCredentials(accessKeyID, secretAccessKey, ""),

This should work. 

```
s3.New(&aws.Config{Credentials: credentials.AnonymousCredentials})
```

**Comment by harshavardhana** [comment]
> Region: aws.String("us-west-2"),

Also of course "us-west-2" region will not work with "Minio" since our region is "milkyway" :-) - you will get a signature mismatch.

**Comment by kahing** [comment]
Ah ha! I didn't find documentation for anonymous credential. Setting the region to "milkyway" with the generated credential also works. Thanks!

**Comment by harshavardhana** [comment]
> Ah ha! I didn't find documentation for anonymous credential. Setting the region to "milkyway" with the generated credential also works. Thanks!

It is not documented, looked through the source code :-)

**Comment by kahing** [comment]
That said, maybe incorrect region should return different error...

**Comment by harshavardhana** [comment]
> That said, maybe incorrect region should return different error...

Of course - the signature handler code is not doing much to do that, it replies back SignatureMismatch for all errors related to signature.  In time we will get to that..

**Pull request closed without merging**
