### PR TITLE
Quickly build dev docker images using 'make docker'

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Quickly build dev docker images using 'make docker'

## Motivation and Context
This PR simplifies the process of developer build of local
docker containers using `make docker`.

You need to provide a TAG i.e

```
TAG=y4m4/minio:exp make docker
```

## Regression
No

## How Has This Been Tested?
Just apply the PR locally and do `TAG=y4m4/minio:fix make docker` , NOTE: specifying tag is important. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#3fe392ae-38a2-464f-b7b1-5b4cb683b32c) |
| mint-dist-xl.sh | :x: [more...](#23879136-4378-4cef-9ca2-ff3634b5f1cd) |
<a name="3fe392ae-38a2-464f-b7b1-5b4cb683b32c"></a>
### 6505-da2faa4/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30900
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b29ec230a96e:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 2 minutes and 44 seconds
(2/13) Running aws-sdk-go tests ... done in 1 seconds
(3/13) Running aws-sdk-java tests ... done in 7 seconds
(4/13) Running aws-sdk-php tests ... done in 46 seconds
(5/13) Running aws-sdk-ruby tests ... done in 31 seconds
(6/13) Running mc tests ... done in 6 minutes and 16 seconds
(7/13) Running minio-dotnet tests ... FAILED in 5 minutes and 3 seconds
{
  "name": "minio-dotnet: CopyObject_Test5",
  "function": "Task<CopyObjectResult> CopyObjectAsync(string bucketName, string objectName, string destBucketName, string destObjectName = null, CopyConditions copyConditions = null, CancellationToken cancellationToken = default(CancellationToken))",
  "args": {
    "bucketName": "miniodotnet7gg7h41c2p2zvkm",
    "objectName": "miniodotnetgkmflz4364",
    "destBucketName": "miniodotneted68t7btlld6bfh",
    "destObjectName": "miniodotnetvbwj0drn1v",
    "data": "6MB",
    "size": "6MB"
  },
  "duration": 4984,
  "status": "FAIL",
  "alert": "",
  "message": "Minio API responded with message=A header you provided implies functionality that is not implemented",
  "error": "A header you provided implies functionality that is not implemented: Minio.Exceptions.MinioException: Minio API responded with message=A header you provided implies functionality that is not implemented\n   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 362\n   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 504\n   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 350\n   at Minio.MinioClient.CopyObjectRequestAsync(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions, Dictionary`2 customHeaders, String resource, CancellationToken cancellationToken, Type type) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 986\n   at Minio.MinioClient.MultipartCopyUploadAsync(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions, Int64 copySize, Dictionary`2 metadata, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 1045\n   at Minio.MinioClient.CopyObjectAsync(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions, Dictionary`2 metadata, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 939\n   at Minio.Functional.Tests.FunctionalTest.CopyObject_Test5(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1059"
}

Executed 6 out of 13 tests successfully.
```
<a name="23879136-4378-4cef-9ca2-ff3634b5f1cd"></a>
### 6505-da2faa4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30369
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 742d9ae098b8:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 1 minutes and 3 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 2 seconds
(4/13) Running aws-sdk-php tests ... done in 43 seconds
(5/13) Running aws-sdk-ruby tests ... done in 6 seconds
(6/13) Running mc tests ... done in 28 seconds
(7/13) Running minio-dotnet tests ... FAILED in 2 minutes and 20 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) ---> Minio.Exceptions.MinioException: Minio API responded with message=Multiple disks failures, unable to write data.
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 362
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 504
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 350
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 483
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 229
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 740
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1724
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 218

Executed 6 out of 13 tests successfully.
```

**Review by poornas — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
@krishnasrinivas can you review?

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
