### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xrfinbupt**
add description about ip

## Description

add description about ip

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d68ada3e-be47-4918-8490-d781d45212a7) |
| mint-large-bucket.sh | :x: [more...](#5b5eda57-3b7a-46ba-8616-191b13ec6973) |
| mint-compression-dist-xl.sh | :x: [more...](#f00296c1-08f0-4b07-8c4a-0a830fbead5c) |
| mint-dist-xl.sh | :x: [more...](#a3f22777-4cf1-4714-b312-dace1866ca18) |
<a name="a3f22777-4cf1-4714-b312-dace1866ca18"></a>
### 7557-7406c54/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31745
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c39954bcb552:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-kj2lze20vxcwes",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 298,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.51:31745/aws-sdk-go-test-kj2lze20vxcwes: dial tcp 72.28.97.51:31745: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d68ada3e-be47-4918-8490-d781d45212a7"></a>
### 7557-7406c54/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30726
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 28fb38a12b75:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-bntplp5vyq9hnb",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 367,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:30726/aws-sdk-go-test-bntplp5vyq9hnb: dial tcp 72.28.97.54:30726: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5b5eda57-3b7a-46ba-8616-191b13ec6973"></a>
### 7557-7406c54/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30806
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 19cfd30de6ce:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vsz1sangwupvqu",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 325,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.51:30806/aws-sdk-go-test-vsz1sangwupvqu: dial tcp 72.28.97.51:30806: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f00296c1-08f0-4b07-8c4a-0a830fbead5c"></a>
### 7557-7406c54/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32622
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9733628b651b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5mpb6cbhl6sspf",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 307,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:32622/aws-sdk-go-test-5mpb6cbhl6sspf: dial tcp 72.28.97.59:32622: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by eco-minio — COMMENTED** [review]
@xrfinbupt Not sure what this adds?  The command already states that it is the server (i.e., minio **server** http://<ip_address>)

**Comment by xrfinbupt** [comment]
> @xrfinbupt Not sure what this adds? The command already states that it is the server (i.e., minio **server** http://<ip_address>)

i don't get it,this place http://192.168.1.1{1...8}/export1 does not seem to understand a bit, since the minio service port is 9000, then here is the use of port 80?
the document explain with below(from **minio server --help**) maybe better, thank u
other:
I just think this place needs to be perfected. This pr may not be perfect.

EXAMPLES:
  1. Start minio server on "/home/shared" directory.
     $ minio server /home/shared

  2. Start minio server bound to a specific ADDRESS:PORT.
     $ minio server --address 192.168.1.101:9000 /home/shared

  3. Start minio server and enable virtual-host-style requests.
     $ export MINIO_DOMAIN=mydomain.com
     $ minio server --address mydomain.com:9000 /mnt/export

  4. Start erasure coded minio server on a node with 64 drives.
     $ minio server /mnt/export{1...64}

  5. Start distributed minio server on an 32 node setup with 32 drives each. Run following command on all the 32 nodes.
     $ export MINIO_ACCESS_KEY=minio
     $ export MINIO_SECRET_KEY=miniostorage
     $ minio server http://node{1...32}.example.com/mnt/export/{1...32}

**Comment by harshavardhana** [comment]
This PR is not correct, or at least it's not explaining what it is trying to do.

Please join us on https://slack.min.io to discuss, we should close this PR until then.

**Pull request closed without merging**
