### PR TITLE
Do not send envVars in ServerInfo()

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Sending envVars along with access and secret
exposes the entire minio server's sensitive
information. This will be an unexpected
situation for all users.

If at all we need to look for things like if
credentials are set through env, we should
only have access to only this information
not the entire set of system envs.

## Motivation and Context
Security and avoid sending sensitive information

## How Has This Been Tested?
Manually. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by vadmeste** [comment]
I tested this PR, I was expecting to see 'xxx' in access/secret keys fields in Settings dialog but I am still seeing the actual access/secret keys. Isn't this the expected behavior? at least this is what I understood from the code.

I did never test any PR related to the browser since moving the latter under `minio/minio`

So this is what I did:
1. Downloaded the PR, 
2. `cd browser/; yarn; yarn dev`
3. `minio server /tmp/fs` in another terminal
4. Opening http://localhost:8080

Am I missing something ?

**Comment by harshavardhana** [comment]
> I did never test any PR related to the browser since moving the latter under minio/minio
> 
> So this is what I did:
> 
> Downloaded the PR,
> cd browser/; yarn; yarn dev
> minio server /tmp/fs in another terminal
> Opening http://localhost:8080

You have to set the access and secret through env @vadmeste for it to be disabled.

**Comment by harshavardhana** [comment]
> You have to set the access and secret through env @vadmeste for it to be disabled.

Also the data-structure has changed..did you build `minio server` again?

**Review by vadmeste — APPROVED** [review]
LGTM and tested.

**Review by fwessels — APPROVED** [review]
Tested and OK

**Pull request merged**
