### PR TITLE
Exitcode '1' when update is available

### LINKED ISSUE #5347: Changed behaviour of 'minio update --quiet' breaks usage for monitoring solutions
## Expected Behavior
Before PR https://github.com/minio/minio/pull/4961 we were able to check for minio updates with our monitoring calling 'minio update --quiet' and expecting exitcode '1' when a new version is available.

## Current Behavior
Now exitcode '0' is returned without the distinction if running the most recent version or an update is available.

## Possible Solution
Reimplementation of the old behaviour, introduction of an additional exitcode for 'update has been applied'.

## Steps to Reproduce (for bugs)
1. On the command line call 'minio update --quiet' with RELEASE.2017-12-28T01-21-00Z of minio installed. 
2. Call echo $?
3. Exit code wil be '0'

## Context
We are using a command line check with our monitoring to see, if a new version of minio is available. As we are testing software updates on staging environments before releasing it on our production systems and use automated deployment for our infrastructures, updating minio right away when calling 'minio update' is not an option for us.

## Your Environment
* Version used (`minio version`): RELEASE.2017-12-28T01-21-00Z

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Fix update command with exitcode '1' when update is available
--quiet should simply update the binary without any prompt.

## Motivation and Context
Fixes #5347

## How Has This Been Tested?
go test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5354/gopath/src/github.com/minio
+ git -C 5354/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5354/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5354/gopath/src/github.com/minio/minio fetch --quiet minio pull/5354/head:pr5354
+ git -C 5354/gopath/src/github.com/minio/minio checkout --quiet pr5354
+ GOPATH=/home/bala/mintauto/5354/gopath
+ make -C 5354/gopath/src/github.com/minio/minio --quiet

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5354/gopath/src/github.com/minio
+ git -C 5354/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
fatal: destination path 'minio' already exists and is not an empty directory.

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5354/gopath/src/github.com/minio
+ git -C 5354/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
fatal: destination path 'minio' already exists and is not an empty directory.

```

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by nitisht — APPROVED** [review]
LGTM

**Comment by nitisht** [comment]
Codecov is stuck here as well. Ignoring it as change is adding exit code.

**Pull request merged**
