### PR TITLE
allow cross platform builds for non amd64 architectures

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
allow cross-platform builds for non-amd64 architectures

## Motivation and Context
PR #8401 simdjson supports only amd64, allow fallback.

## How to test this PR?
Just do `make crosscompile`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression yes introduced in simdjson support PR
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#8d1e4a3d-b52f-42a3-a169-63166df7675e) |
| mint-large-bucket.sh | :x: [more...](#eabffc7f-6e6a-4d6b-bbe3-8de283cad790) |
| mint-fs.sh | :x: [more...](#6d001d82-9c8e-4de4-94a4-91481b0ea65c) |
| mint-dist-xl.sh | :x: [more...](#321b5117-927a-4d26-9d2e-a0f35e36642f) |
| mint-gateway-azure.sh | :x: [more...](#60715604-845a-4bf0-9055-fac24806749f) |
<a name="8d1e4a3d-b52f-42a3-a169-63166df7675e"></a>
### 9002-821e6b8/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31243
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8dbd91b2395e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-pv05sxsgwwp2a4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120320,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31243/aws-sdk-go-test-pv05sxsgwwp2a4: dial tcp 72.28.97.55:31243: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="6d001d82-9c8e-4de4-94a4-91481b0ea65c"></a>
### 9002-821e6b8/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30590
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 57a23d71b89e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-eoalleu6pqnhsh",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120279,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30590/aws-sdk-go-test-eoalleu6pqnhsh: dial tcp 72.28.97.55:30590: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="60715604-845a-4bf0-9055-fac24806749f"></a>
### 9002-821e6b8/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31863
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 87c04d47e2e8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 14 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 17 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(9/14) Running minio-go tests ... done in 19 minutes and 55 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 16 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11628,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-20feivm, objectName=minio-java-test-f1j19t, resource=/minio-java-test-20feivm/minio-java-test-f1j19t, requestId=15F3A57CF41826D1, hostId=58449de5-4e17-4d69-9ce2-38d6b2070334)\nrequest={method=PUT, url=http://72.28.97.51:31863/minio-java-test-20feivm/minio-java-test-f1j19t?uploadId=4932cc23adac5932&partNumber=1, headers=x-amz-copy-source-if-match: 332584ad774f20eaefd4960361541f72-2\nx-amz-copy-source: minio-java-test-20feivm/minio-java-test-2po650u\nAccept-Encoding: identity\nHost: 72.28.97.51:31863\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200215T180410Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200215/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-15T17-00-48Z\nVary: Origin\nX-Amz-Request-Id: 15F3A57CF41826D1\nX-Xss-Protection: 1; mode=block\nDate: Sat, 15 Feb 2020 18:04:10 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="321b5117-927a-4d26-9d2e-a0f35e36642f"></a>
### 9002-821e6b8/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31316
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b64151682713:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fupr0ecutzsz0v",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365351,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F3A36EDD1D28CA, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="eabffc7f-6e6a-4d6b-bbe3-8de283cad790"></a>
### 9002-821e6b8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32254
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fd2a187ef9db:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-u1byodrouykpla",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 288,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.52:32254/aws-sdk-go-test-u1byodrouykpla: dial tcp 72.28.97.52:32254: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#efa3da15-765a-4da1-8f91-ffa8e4d20beb) |
| mint-large-bucket.sh | :x: [more...](#e3e023ba-600a-44a4-8593-a701c599d993) |
| mint-dist-xl.sh | :x: [more...](#1a6c1740-0302-40bf-b838-e97173d9bc1a) |
| mint-gateway-azure.sh | :x: [more...](#62c7d525-bfc2-4ce8-a8f7-561a498b9328) |
<a name="efa3da15-765a-4da1-8f91-ffa8e4d20beb"></a>
### 9002-b15dad8/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31625
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 10697a386ffe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-o6wjrsty0su0kd",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120334,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31625/aws-sdk-go-test-o6wjrsty0su0kd: dial tcp 72.28.97.55:31625: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="62c7d525-bfc2-4ce8-a8f7-561a498b9328"></a>
### 9002-b15dad8/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31536
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cbbfe74c0ca9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 17 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 3 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 38 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/14) Running minio-go tests ... done in 22 minutes and 8 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 18 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 10608,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3hpgdbs, objectName=minio-java-test-ci1d1n, resource=/minio-java-test-3hpgdbs/minio-java-test-ci1d1n, requestId=15F3A9214B0D1706, hostId=39e99aec-96c4-4775-8d8e-4bfafd01a624)\nrequest={method=PUT, url=http://72.28.97.56:31536/minio-java-test-3hpgdbs/minio-java-test-ci1d1n?uploadId=3175bd2a5c2fbd8f&partNumber=1, headers=x-amz-copy-source-if-match: ac0eac2d457ccf6dd5eefecc09135f2b-2\nx-amz-copy-source: minio-java-test-3hpgdbs/minio-java-test-2es0r8d\nAccept-Encoding: identity\nHost: 72.28.97.56:31536\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200215T191054Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200215/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-15T18-04-42Z\nVary: Origin\nX-Amz-Request-Id: 15F3A9214B0D1706\nX-Xss-Protection: 1; mode=block\nDate: Sat, 15 Feb 2020 19:10:54 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="1a6c1740-0302-40bf-b838-e97173d9bc1a"></a>
### 9002-b15dad8/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30289
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a846f2993b3e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-tf6o36etgxg9g2",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365624,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F3A6E93F482EC8, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="e3e023ba-600a-44a4-8593-a701c599d993"></a>
### 9002-b15dad8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32170
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3ae6a1b853cb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-xiynufhfon06c1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365010,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F3A6E9219CC4A0, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by klauspost** [comment]
IMO this should be fixed upstream in the simdjson package instead @fwessels

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#db2d42a0-928c-4288-b309-8e56e308bd5d) |
| mint-gateway-azure.sh | :x: [more...](#0a3691aa-ecc8-4c0c-a634-239b07d46af4) |
<a name="db2d42a0-928c-4288-b309-8e56e308bd5d"></a>
### 9002-badb8ce/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32531
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6296e858d008:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 48 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... FAILED in 13 minutes and 19 seconds
{
  "args": {},
  "duration": 86647,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="0a3691aa-ecc8-4c0c-a634-239b07d46af4"></a>
### 9002-badb8ce/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30349
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1b3657ca6773:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 22 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 54 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 5 minutes and 46 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(9/14) Running minio-go tests ... done in 21 minutes and 14 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 14 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 10819,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3sd0elg, objectName=minio-java-test-ps8cq9, resource=/minio-java-test-3sd0elg/minio-java-test-ps8cq9, requestId=15F3B01B69014AC2, hostId=3ce6dada-6408-483a-8ccc-60365be7f42f)\nrequest={method=PUT, url=http://72.28.97.61:30349/minio-java-test-3sd0elg/minio-java-test-ps8cq9?uploadId=00924729c21c3241&partNumber=1, headers=x-amz-copy-source-if-match: 53b43520e5cf90d8d12ca17e9e20ffe4-2\nx-amz-copy-source: minio-java-test-3sd0elg/minio-java-test-3rv27nr\nAccept-Encoding: identity\nHost: 72.28.97.61:30349\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200215T211834Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200215/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-15T20-14-57Z\nVary: Origin\nX-Amz-Request-Id: 15F3B01B69014AC2\nX-Xss-Protection: 1; mode=block\nDate: Sat, 15 Feb 2020 21:18:46 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by jessestuart** [comment]
Just saw this after filing #9003. 

@klauspost Yeah, in principle I'd agree this is more an issue with the upstream `simdjson-go`... but still, the introduction of the dependency was itself a breaking change.

**Comment by harshavardhana** [comment]
@klauspost that is doable as well, i thought intention of simdjson-go was to be only amd64

**Pull request closed without merging**
