### PR TITLE
chinese translate

### PR DESCRIPTION
**Pull request by astaxie**
It's still in process. When it ready I will let you know
- [x] docs:add readme_zh.md
- [ ] add docs/cn

### CODE REVIEW

**Comment by harshavardhana** [comment]
Thanks @astaxie

**Comment by astaxie** [comment]
@hackintoshrao Where is the mardown file about this link https://docs.minio.io/docs/how-to-install-golang. As I want to move to https://docs.minio.io/docs/zh-CN/how-to-install-golang, but I can't find the file in doc folder.

**Comment by harshavardhana** [comment]
@astaxie it is at https://github.com/minio/cookbook

**Comment by astaxie** [comment]
@harshavardhana The README is ready to merge. I will create another PR to https://github.com/minio/cookbook for other docs translate

**Comment by harshavardhana** [comment]
> @harshavardhana The README is ready to merge. I will create another PR to https://github.com/minio/cookbook for other docs translate

Thank you! @astaxie

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
