### PR TITLE
Update UI assets

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Update UI assets

## Motivation and Context
Update with latest updates in package.json

## Regression
No

## How Has This Been Tested?
Usual UI testing

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#380de06d-0379-4720-a76c-e15ae93f5ccd) |
| mint-large-bucket.sh | :x: [more...](#af1a5a2c-f287-4573-bacd-28b87b083cd3) |
| mint-dist-xl.sh | :x: [more...](#bafd5938-92d3-4422-ae51-c28f3c48daa9) |
<a name="bafd5938-92d3-4422-ae51-c28f3c48daa9"></a>
### 7764-bce9b20/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30232
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2cd2c49b1c01:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 42 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 50 seconds
(10/14) Running minio-java tests ... FAILED in 39 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName)",
  "duration": 764,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-4qdhr6, objectName=minio-java-test-2agbh16, resource=/minio-java-test-4qdhr6/minio-java-test-2agbh16, requestId=15A691666E32A2D2, hostId=18d2e391-8087-4b6c-a3ba-333d8ff6e848)\nrequest={method=DELETE, url=http://72.28.97.54:30232/minio-java-test-4qdhr6/minio-java-test-2agbh16?uploadId=f550f1fa-5fbc-4f2d-b975-aec3307abd19, headers=Host: 72.28.97.54:30232\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190609T152950Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190609/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-09T15-11-32Z\nVary: Origin\nX-Amz-Request-Id: 15A691666E32A2D2\nX-Minio-Deployment-Id: 18d2e391-8087-4b6c-a3ba-333d8ff6e848\nX-Xss-Protection: 1; mode=block\nDate: Sun, 09 Jun 2019 15:29:50 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test1(FunctionalTest.java:1601), FunctionalTest.runTests(FunctionalTest.java:2988), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="af1a5a2c-f287-4573-bacd-28b87b083cd3"></a>
### 7764-bce9b20/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31254
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d54fbf05a8da:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 34 seconds
{
  "name": "mc",
  "duration": "121131",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-5604 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-14351  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-14351/datafile-1-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-14351/datafile-10-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-14351/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-14351/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-14351/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-14351/datafile-129-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-14351/datafile-1.03-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-14351/datafile-1-b`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-14351/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-14351/datafile-100-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-14351/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-14351/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-14351/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-14351/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-14351/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 545.36 MiB, Speed: 4.50 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="380de06d-0379-4720-a76c-e15ae93f5ccd"></a>
### 7764-bce9b20/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31759
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fff8336af6f2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ekmd46nzujll3e",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360015,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A6916D66513B17, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by kanagarajkm — CHANGES_REQUESTED** [review]
Since we use `yarn` primarily we don't need to add package-lock.json, instead, yarn.lock should be updated.

**Comment by harshavardhana** [comment]
I think we should deprecate `yarn` and instead move to npm due to all the improvements npm is now much better and well supported by GitHub's automated system as well.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#43de7f99-dc31-4738-bf7f-9d394b6f56cd) |
| mint-dist-xl.sh | :x: [more...](#6ce40546-7eb0-43e4-bb76-0322582f95ee) |
<a name="6ce40546-7eb0-43e4-bb76-0322582f95ee"></a>
### 7764-4d79580/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30370
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dc146e5398bc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 37 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 44 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 19 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 811,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3g9ku4u, objectName=minio-java-test-2ivt4k, resource=/minio-java-test-3g9ku4u/minio-java-test-2ivt4k, requestId=15A6ADD764D461C2, hostId=78e76450-fd2c-4643-a4cb-3c0e2a152af5)\nrequest={method=DELETE, url=http://72.28.97.52:30370/minio-java-test-3g9ku4u/minio-java-test-2ivt4k?uploadId=c9df08d4-6dcf-4352-9d33-586017c4bbbe, headers=Host: 72.28.97.52:30370\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190610T001101Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190610/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-09T23-51-57Z\nVary: Origin\nX-Amz-Request-Id: 15A6ADD764D461C2\nX-Minio-Deployment-Id: 78e76450-fd2c-4643-a4cb-3c0e2a152af5\nX-Xss-Protection: 1; mode=block\nDate: Mon, 10 Jun 2019 00:11:02 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="43de7f99-dc31-4738-bf7f-9d394b6f56cd"></a>
### 7764-4d79580/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32716
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c5a9ac776aac:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 16 seconds
{
  "name": "mc",
  "duration": "106565",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28247 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-22843  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-22843/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-22843/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-22843/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-22843/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-22843/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-22843/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-22843/datafile-10-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-22843/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-22843/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-22843/datafile-5-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-22843/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-22843/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-22843/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-22843/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-22843/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 528.25 MiB, Speed: 4.96 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ee791b82-1248-4f1b-82e8-9fdcfc2f0095) |
| mint-dist-xl.sh | :x: [more...](#7fcfa996-bcb4-4f03-87c2-04dd8f1cc63d) |
<a name="ee791b82-1248-4f1b-82e8-9fdcfc2f0095"></a>
### 7764-ffebc9f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30598
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a85b0fb3a6c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 15 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 37 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 14 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 361,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3taf5fo, objectName=minio-java-test-3336mbe, resource=/minio-java-test-3taf5fo/minio-java-test-3336mbe, requestId=15A6AF868B15F735, hostId=57984afb-230a-42a5-a49f-e210bbc04c18)\nrequest={method=DELETE, url=http://72.28.97.54:30598/minio-java-test-3taf5fo/minio-java-test-3336mbe?uploadId=c49d58cc-6bd8-4a78-aaaf-cf8621e5aa01, headers=Host: 72.28.97.54:30598\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190610T004153Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190610/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-10T00-20-30Z\nVary: Origin\nX-Amz-Request-Id: 15A6AF868B15F735\nX-Minio-Deployment-Id: 57984afb-230a-42a5-a49f-e210bbc04c18\nX-Xss-Protection: 1; mode=block\nDate: Mon, 10 Jun 2019 00:41:53 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="7fcfa996-bcb4-4f03-87c2-04dd8f1cc63d"></a>
### 7764-ffebc9f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32735
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 61b7ba105ce6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 3 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 30 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 293,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-264deip, objectName=minio-java-test-3on0bbp, resource=/minio-java-test-264deip/minio-java-test-3on0bbp, requestId=15A6AF74764DC901, hostId=ec99fd52-c7b2-4cc3-bb06-ab32ec052697)\nrequest={method=DELETE, url=http://72.28.97.54:32735/minio-java-test-264deip/minio-java-test-3on0bbp?uploadId=1f1d8159-0826-4328-a35a-cb95a8c98d12, headers=Host: 72.28.97.54:32735\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190610T004035Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190610/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-10T00-20-30Z\nVary: Origin\nX-Amz-Request-Id: 15A6AF74764DC901\nX-Minio-Deployment-Id: ec99fd52-c7b2-4cc3-bb06-ab32ec052697\nX-Xss-Protection: 1; mode=block\nDate: Mon, 10 Jun 2019 00:40:35 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Review by kanagarajkm — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
