### PR TITLE
Update elasticsearch library to work with ES 7.x

### PR DESCRIPTION
**Pull request by donatello**
## Description

- In namespace mode, we now use a hash of the object name as the id. This is due to
restrictions in length of the id (512 bytes in ES) and because we need to remove
URL characaters like `/` from the object name for use as an id.

## Motivation and Context

This change allows using MinIO with Elasticsearch version 7.x which is the latest major release series.

## How to test this PR?

Setup an elasticsearch cluster and configure MinIO bucket notifications. https://docs.minio.io/docs/minio-bucket-notification-guide.html#Elasticsearch

With docker:
```
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" --name elasticsearch docker.elastic.co/elasticsearch/elasticsearch:7.12.0
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

We are no longer supporting ES releases older than 7.x.

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#df5f3248-85b8-46a9-b8ed-259df05c0442) |
<a name="df5f3248-85b8-46a9-b8ed-259df05c0442"></a>
### 11636-37a5dbe/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32672
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d248c15a5d37:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2848,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:32672 s3api copy-object --bucket awscli-mint-test-bucket-28632 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-28632/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 57 seconds
(7/15) Running minio-dotnet tests ... done in 44 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 38 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-40bly9wwaj1q2nbt",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-40bly9wwaj1q2nbt",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 4061,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 39 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 432,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-137o93g, objectName = minio-java-test-1g0c498-copy, resource = /minio-java-test-137o93g/minio-java-test-1g0c498-copy, requestId = 166715BE5328B6EA, hostId = 910d6ae2-10c9-4bd3-b30e-ababc43d8e87)\nrequest={method=PUT, url=http://minio-dev8.minio.io:32672/minio-java-test-137o93g/minio-java-test-1g0c498-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-23nqvqh/minio-java-test-1g0c498\nHost: minio-dev8.minio.io:32672\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210225T195458Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210225/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Thu, 25 Feb 2021 19:54:58 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166715BE5328B6EA\nX-Xss-Protection: 1; mode=block\nDate: Thu, 25 Feb 2021 19:54:58 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 54 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 10 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3019",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-24457/s3cmd-test-object-14341 e649986c-5349-4b11-b436-66c0279bccc1\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id e649986c-5349-4b11-b436-66c0279bccc1 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#6665bc4a-1560-4a23-8982-b937005beaad) |
<a name="6665bc4a-1560-4a23-8982-b937005beaad"></a>
### 11636-cc4c126/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30733
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5c9b438c8b95:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2671,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30733 s3api copy-object --bucket awscli-mint-test-bucket-15471 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-15471/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 51 seconds
(7/15) Running minio-dotnet tests ... done in 39 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 52 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-5d55aaa0we0tc21z",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-5d55aaa0we0tc21z",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 5195,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 42 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 307,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2bm3nqj, objectName = minio-java-test-18gvfl1-copy, resource = /minio-java-test-2bm3nqj/minio-java-test-18gvfl1-copy, requestId = 16682EE8D6DC8A6F, hostId = f6a3decf-33fa-4750-aec1-c721fbd0c4d1)\nrequest={method=PUT, url=http://minio-c3.minio.io:30733/minio-java-test-2bm3nqj/minio-java-test-18gvfl1-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2h9mtve/minio-java-test-18gvfl1\nHost: minio-c3.minio.io:30733\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210301T094722Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210301/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Mon, 01 Mar 2021 09:47:23 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16682EE8D6DC8A6F\nX-Xss-Protection: 1; mode=block\nDate: Mon, 01 Mar 2021 09:47:23 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 55 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 0 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3080",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-29285/s3cmd-test-object-30742 11622e53-85ea-4493-a1ce-3a4d6818f9e3\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 11622e53-85ea-4493-a1ce-3a4d6818f9e3 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Does this break existing deploymentS? @donatello

**Comment by donatello** [comment]
> Does this break existing deploymentS? @donatello 

We previously only supported 5.x elastic search but that version was EoLed in 2019 - https://www.elastic.co/support/eol

I'm not sure if 6.x worked with minio but it was also EoLed in 2020. 7.x is supported but doesn't quite work with minio based on the  bug report we got.

Will need to check if it actually breaks 5.x and 6.x. will update once I do.

**Comment by harshavardhana** [comment]
> > Does this break existing deploymentS? @donatello
> 
> We previously only supported 5.x elastic search but that version was EoLed in 2019 - https://www.elastic.co/support/eol
> 
> I'm not sure if 6.x worked with minio but it was also EoLed in 2020. 7.x is supported but doesn't quite work with minio based on the bug report we got.
> 
> Will need to check if it actually breaks 5.x and 6.x. will update once I do.

We should check existing customers on this @donatello not sure who might be using ES - AFAIK no one has yet complained about the library not working so not sure how it is working for them either if ES7 is the standard now.

**Comment by harshavardhana** [comment]
@donatello is this something that we can bring in as a new target such as `notify_elasticv7` - I am just a little wary of deprecating the current implementation right away, we may start throwing warnings and eventually remove it. 

Or should we just keep the current implementation as is and take `notify_elastic version=v7` ? this way we can turn this compatibility mode on?

**Comment by donatello** [comment]
> Or should we just keep the current implementation as is and take `notify_elastic version=v7` ? this way we can turn this compatibility mode on?

I like this option better. We can start showing deprecation warnings for version < v7 at server startup, and maybe 6 months down the line remove the older implementation. This also gives a path for future upgrades. Maybe later version=v8 could be added, and then we can deprecate v7. Let me know and I can update this PR.

**Comment by harshavardhana** [comment]
> > Or should we just keep the current implementation as is and take `notify_elastic version=v7` ? this way we can turn this compatibility mode on?
> 
> I like this option better. We can start showing deprecation warnings for version < v7 at server startup, and maybe 6 months down the line remove the older implementation. This also gives a path for future upgrades. Maybe later version=v8 could be added, and then we can deprecate v7. Let me know and I can update this PR.

Yes makes sense let's do that..

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#d2e8386d-7ed3-4c82-bfc7-fb171d9aeb80) |
<a name="d2e8386d-7ed3-4c82-bfc7-fb171d9aeb80"></a>
### 11636-da4f1ea/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31491
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ecb05cddeb1a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2518,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31491 s3api copy-object --bucket awscli-mint-test-bucket-10513 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-10513/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 46 seconds
(7/15) Running minio-dotnet tests ... done in 33 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 12 seconds
{
  "args": {},
  "duration": 764,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 56 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 231,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-10mj9sg, objectName = minio-java-test-305usib-copy, resource = /minio-java-test-10mj9sg/minio-java-test-305usib-copy, requestId = 16754035EFD857C4, hostId = 31700668-7952-4a26-b501-74a4ef471ca9)\nrequest={method=PUT, url=http://minio-c3.minio.io:31491/minio-java-test-10mj9sg/minio-java-test-305usib-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-1gqc622/minio-java-test-305usib\nHost: minio-c3.minio.io:31491\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210412T233041Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210412/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Mon, 12 Apr 2021 23:30:41 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16754035EFD857C4\nX-Xss-Protection: 1; mode=block\nDate: Mon, 12 Apr 2021 23:30:41 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 56 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 4 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3005",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-11539/s3cmd-test-object-28262 4e115948-2696-4114-a0ba-d3f1aa6401ae\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 4e115948-2696-4114-a0ba-d3f1aa6401ae put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — CHANGES_REQUESTED** [review]
are you planning to add the config option? @donatello

**Comment by donatello** [comment]
> are you planning to add the config option? @donatello 

Yes, will keep 5.x support but planning to do by directly querying the server for it's version and then printing the compatibility message - we could avoid adding the config option this way.

**Comment by harshavardhana** [comment]
> Yes, will keep 5.x support but planning to do by directly querying the server for it's version and then printing the compatibility message - we could avoid adding the config option this way.

Oh okay cool - if that is possible @donatello

**Comment by donatello** [comment]
Closing in favor of #12053

**Pull request closed without merging**
