### PR TITLE
select: Check if CSV is valid utf8

### LINKED ISSUE #10970: If CompressionType is not set, SelectObjectContent API return junk instead of InvalidTextEncoding error
## Expected Behavior
Should return `InvalidTextEncoding` error.

## Current Behavior
Returns junk.

## Steps to Reproduce (for bugs)

	public static String getCSVZipObjectHeader(String bucketName, String objectName,
		      MinioClient minioClient) throws Exception{
		try {
			String sqlExpression = "select * from S3Object limit 1";
			InputSerialization is = new InputSerialization(null, false, null, null, FileHeaderInfo.NONE, null, null, null);
			OutputSerialization os = new OutputSerialization(null, null, null, QuoteFields.ASNEEDED, null);
			SelectResponseStream stream =
			    minioClient.selectObjectContent(
			        SelectObjectContentArgs.builder()
			            .bucket(bucketName)
			            .object(objectName)
			            .sqlExpression(sqlExpression)
			            .inputSerialization(is)
			            .outputSerialization(os)
			            .requestProgress(true)
			            .build());

			byte[] buf = new byte[2048];
			int bytesRead = stream.read(buf, 0, buf.length);
			String header =  (new String(buf, 0, bytesRead, StandardCharsets.UTF_8)).trim();
			stream.close();
			log.info(header);
			return header;
		}catch(Exception e) {
			log.error("Error retrieving header from S3 Object. {}", e.getMessage());
			throw e;
		}
	}

## Context
Extracting the header from a compressed CSV file

## Your Environment

* Version used (`minio --version`):  
minio version RELEASE.2020-08-18T19-41-00Z
* Server setup and configuration: 
Distributed MinIO 4 Servers 

* Operating System and version (`uname -a`):
Linux itom-di-minio-0 3.10.0-862.14.4.el7.x86_64 minio/minio#1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Check if first block of CSV data is valid utf8.

Fixes #10970

## How to test this PR?

Test with binary files, etc.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by vadmeste** [comment]
Something like this seems to be enough:
```
diff --git a/pkg/csvparser/reader.go b/pkg/csvparser/reader.go
index c5d75c128..9bbc554a1 100644
--- a/pkg/csvparser/reader.go
+++ b/pkg/csvparser/reader.go
@@ -254,6 +254,9 @@ func (r *Reader) readLine() ([]byte, error) {
                line[n-2] = '\n'
                line = line[:n-1]
        }
+       if !utf8.Valid(line) {
+               return nil, errors.New("invalid utf8 character")
+       }
        return line, err
 }
```

It doesn't seem to make any difference in benchmark numbers:
```
name                old time/op    new time/op    delta
ReadLargeFields-24    6.59µs ± 0%    6.88µs ± 0%   ~     (p=1.000 n=1+1)

name                old alloc/op   new alloc/op   delta
ReadLargeFields-24    3.94kB ± 0%    3.94kB ± 0%   ~     (all equal)

name                old allocs/op  new allocs/op  delta
ReadLargeFields-24      24.0 ± 0%      24.0 ± 0%   ~     (all equal)
```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#0760629e-9bd3-4d01-89c0-4604d06afb92) |
<a name="0760629e-9bd3-4d01-89c0-4604d06afb92"></a>
### 10991-360af6a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32535
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9bce032d04fa:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 18 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 2 minutes and 57 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 43 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 40 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 28 seconds
(10/15) Running minio-java tests ... done in 10 minutes and 42 seconds
(11/15) Running minio-js tests ... done in 2 minutes and 38 seconds
(12/15) Running minio-py tests ... done in 18 minutes and 56 seconds
(13/15) Running s3cmd tests ... FAILED in 1 minutes and 19 seconds
{
  "name": "s3cmd",
  "duration": "16727",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  following lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nInvoked as: /usr/local/bin/s3cmd --config /tmp/.s3cmd-978/s3cfg get s3://s3cmd-test-bucket-24608/s3cmd-test-object-8113 s3cmd-test-object-8113.downloaded\nProblem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer\nS3cmd:   2.1.0\npython:   3.6.9 (default, Jul 17 2020, 12:50:27) \n[GCC 8.4.0]\nenvironment LANG=C.UTF-8\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 3121, in <module>\n    rc = main()\n  File \"/usr/local/bin/s3cmd\", line 3030, in main\n    rc = cmd_func(args)\n  File \"/usr/local/bin/s3cmd\", line 604, in cmd_object_get\n    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)\n  File \"/usr/local/lib/python3.6/dist-packages/S3/S3.py\", line 726, in object_get\n    response = self.recv_file(request, stream, labels, start_position)\n  File \"/usr/local/lib/python3.6/dist-packages/S3/S3.py\", line 1733, in recv_file\n    data = http_response.read(this_chunk)\n  File \"/usr/lib/python3.6/http/client.py\", line 459, in read\n    n = self.readinto(b)\n  File \"/usr/lib/python3.6/http/client.py\", line 503, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  above lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
}
(13/15) Running s3select tests ... done in 59 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
> Something like this seems to be enough:
> 
> ```
> diff --git a/pkg/csvparser/reader.go b/pkg/csvparser/reader.go
> index c5d75c128..9bbc554a1 100644
> --- a/pkg/csvparser/reader.go
> +++ b/pkg/csvparser/reader.go
> @@ -254,6 +254,9 @@ func (r *Reader) readLine() ([]byte, error) {
>                 line[n-2] = '\n'
>                 line = line[:n-1]
>         }
> +       if !utf8.Valid(line) {
> +               return nil, errors.New("invalid utf8 character")
> +       }
>         return line, err
>  }
> ```
> 
> It doesn't seem to make any difference in benchmark numbers:
> 
> ```
> name                old time/op    new time/op    delta
> ReadLargeFields-24    6.59µs ± 0%    6.88µs ± 0%   ~     (p=1.000 n=1+1)
> 
> name                old alloc/op   new alloc/op   delta
> ReadLargeFields-24    3.94kB ± 0%    3.94kB ± 0%   ~     (all equal)
> 
> name                old allocs/op  new allocs/op  delta
> ReadLargeFields-24      24.0 ± 0%      24.0 ± 0%   ~     (all equal)
> ```

@klauspost were you able to take a look? - looks like @vadmeste approach is much simpler and only requires one change.

**Comment by klauspost** [comment]
@vadmeste @harshavardhana It is a >4 % slowdown which will be paid by the entire file. That is why I only do it for the first block.

You need more than n=1 for it to show the difference. Use `benchcmp`.

**Comment by harshavardhana** [comment]
> @vadmeste @harshavardhana It is a >4 % slowdown which will be paid by the entire file. That is why I only do it for the first block.
> 
> You need more than n=1 for it to show the difference. Use `benchcmp`.

Ah I see @vadmeste PTAL

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by vadmeste** [comment]
> It is a >4 % slowdown which will be paid by the entire file.

yes, I thought it is not a big deal if we want to be complying to S3 behavior here, S3 detects if there is non utf8 sequence even if the file is large. Approving anyway for now.

**Pull request merged**
