### PR TITLE
Add loong64 support

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
## Description
Add support for loong64.
At present, the support of loong64 has been added in the golang source code.

## Motivation and Context
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.

Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html

## How to test this PR?
./buildscripts/checkdeps.sh
./buildscripts/cross-compile.sh

When performing cross-compilation, rely on 2 PRs:
https://github.com/minio/madmin-go/pull/163
https://github.com/shirou/gopsutil/pull/1228

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#7ab36d11-67f4-4fd5-b00a-e4673273fd4f) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#cdbb4c53-da53-497e-a8e9-024c1b2ff3eb) |
<a name="cdbb4c53-da53-497e-a8e9-024c1b2ff3eb"></a>
### 16283-608200b/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:30590
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 6cc5dd8aa754:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-rlcnky6yifp0un",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364746,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1732C19D1C964FD1, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/14) Running aws-sdk-java tests ... done in 1 seconds
(2/14) Running aws-sdk-php tests ... done in 42 seconds
(3/14) Running aws-sdk-ruby tests ... done in 7 seconds
(4/14) Running awscli tests ... done in 58 seconds
(5/14) Running healthcheck tests ... done in 1 seconds
(6/14) Running mc tests ... done in 15 seconds
(7/14) Running minio-go tests ... done in 49 seconds
(8/14) Running minio-java tests ... done in 29 seconds
(9/14) Running minio-js tests ... done in 50 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 41 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
<a name="7ab36d11-67f4-4fd5-b00a-e4673273fd4f"></a>
### 16283-608200b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.5:31638
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp a0be8ef8232a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-duecs634abigo2",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364409,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1732C19D0BF43AAD, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/14) Running aws-sdk-java tests ... done in 1 seconds
(2/14) Running aws-sdk-php tests ... done in 42 seconds
(3/14) Running aws-sdk-ruby tests ... done in 7 seconds
(4/14) Running awscli tests ... done in 59 seconds
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... done in 16 seconds
(7/14) Running minio-go tests ... done in 51 seconds
(8/14) Running minio-java tests ... done in 31 seconds
(9/14) Running minio-js tests ... done in 51 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 46 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#075cd8bd-db26-4d91-9b6a-db8ed6c004b9) |
<a name="075cd8bd-db26-4d91-9b6a-db8ed6c004b9"></a>
### 16283-37f6d4b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:31755
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 3fcbe49eeb9a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 48 seconds
(9/14) Running minio-java tests ... FAILED in 30 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 360,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"InternalError\",\"Message\":\"We encountered an internal error, please try again. (Server not initialized, please try again)\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"1735464E9ADB3061\",\"HostId\":\"6601110c-2a02-4ad1-b5b4-4d5e79ef627e\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:206), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 50 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 46 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by klauspost** [comment]
Failure:

```
-->   linux/loong64:github.com/minio/minio
# github.com/minio/madmin-go/v2/kernel
Error: ../../../go/pkg/mod/github.com/minio/madmin-go/v2@v2.0.3/kernel/kernel.go:76:32: undefined: utsnameStr
# github.com/shirou/gopsutil/v3/host
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.22.9/host/host_linux.go:98:22: undefined: sizeOfUtmp
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.22.9/host/host_linux.go:103:14: undefined: sizeOfUtmp
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.22.9/host/host_linux.go:105:9: undefined: utmp
make: *** [Makefile:28: crosscompile] Error 2
Error: Process completed with exit code 2.
```

**Comment by zhaixiaojuan** [comment]
I analyzed these two errors:

(1)
> 
> ```
> -->   linux/loong64:github.com/minio/minio
> # github.com/minio/madmin-go/v2/kernel
> Error: ../../../go/pkg/mod/github.com/minio/madmin-go/v2@v2.0.3/kernel/kernel.go:76:32: undefined: utsnameStr
> ```
This bug requires adding loongarch64 support in madmin-go, I have submitted a PR: https://github.com/minio/madmin-go/pull/163

(2)
>
> ```
> # github.com/shirou/gopsutil/v3/host
> Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.22.9/host/host_linux.go:98:22: undefined: sizeOfUtmp
> Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.22.9/host/host_linux.go:103:14: undefined: sizeOfUtmp
> Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.22.9/host/host_linux.go:105:9: undefined: utmp
> make: *** [Makefile:28: crosscompile] Error 2
> Error: Process completed with exit code 2.
> ```
I checked the gopsutil project, and someone has submitted a related PR: https://github.com/shirou/gopsutil/pull/1228

**Comment by klauspost** [comment]
We have approved/merged the madmin change. The gopsutil will have to be fixed, though.

**Comment by harshavardhana** [comment]
Please resubmit when gopsutil support is released.

**Pull request closed without merging**
