### PR TITLE
Fixed docker-compose file for Minio on Docker Swarm.

### PR DESCRIPTION
**Pull request by fungiboletus**
Hei.

[If you follow the documentation ](https://docs.minio.io/docs/deploy-minio-on-docker-swarm), you end up with the issue #4761 

Therefore, I updated the version in the docker-compose file.

### CODE REVIEW

**Comment by vadmeste** [comment]
Thanks for this PR @yellowiscool

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by nitisht** [comment]
@yellowiscool Thank you for the PR, but `latest` tag is not the recommended approach as it has its own set of [problems](http://container-solutions.com/docker-latest-confusion/)

So, we tag releases and use them accordingly in docs. We intend to keep the docs updated with each release, however there was a delay this time, I have now updated the docs.

**Comment by nitisht** [comment]
@yellowiscool as the doc is now updated, feel free to close this PR.

**Comment by fungiboletus** [comment]
@nitisht Ok thanks for the link about the `latest` problems.

**Pull request closed without merging**
