### PR TITLE
Disable network share test, appveyor bug.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Disable network share test, appveyor bug.

## Motivation and Context
Unknowingly appveyor tests are failing. 

## How Has This Been Tested?
Manually. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by balamurugana — CHANGES_REQUESTED** [review]
I see below error.
```
--- FAIL: TestNetworkSymbolicLink (2.16s)
	stat_windows_test.go:141: CreateFile \\localhost\GoSymbolicLinkTestShare\: The network path was not found.
FAIL
FAIL	github.com/minio/minio/pkg/x/os	4.520s
```

I think we should fix this than ignoring.

**Comment by harshavardhana** [comment]
> I think we should fix this than ignoring.

I prefer merging this and opening a bug to address this problem with appveyor, since without this PR it blocks all other PRs. Once we have figured out the cause with appveyor why this suddenly started happening we can turn the test back on.

**Comment by harshavardhana** [comment]
> I prefer merging this and opening a bug to address this problem with appveyor, since without this PR it blocks all other PRs. Once we have figured out the cause with appveyor why this suddenly started happening we can turn the test back on.

Appveyor meaning i am talking to Appveyor support folks to figure out what really just happened on their end. It is perhaps something they did on their end to disable network share creation. @balamurugana

**Comment by harshavardhana** [comment]
https://github.com/appveyor/ci/issues/1579 is the issue tracking @balamurugana looks like the new windows images they deployed has a regression which is failing across some projects which use network share tests.

**Review by poornas — APPROVED** [review]
LGTM

**Review by deekoder — APPROVED** [review]
Since this is an Appveyor bug, I approve disabling this test till its fixed on their end.

**Pull request merged**
