### PR TITLE
Update screenshots. Use png instead of jpgs.

### LINKED ISSUE #5746: Update minio browser screenshots on docs.minio.io
Docs are still showing older UX screenshots. Update them.

### PR DESCRIPTION
**Pull request by deekoder**
## Description
Fixes #5746 

## Motivation and Context
Update older screenshots with newer.

## How Has This Been Tested?
Manually on localhost

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by deekoder** [comment]
i have pinged @belvid  on the res changes of the screenshot.

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by harshavardhana — DISMISSED** [review]

**Comment by deekoder** [comment]
updated screenshots again. PTAL.

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by nitisht — COMMENTED** [review]
Seems an extra file `/minio-browser-gateway.png` is added, but not referred from code. Is that intentional?

**Comment by deekoder** [comment]
@nitisht yes. We are replacing minio-browser.jpg with minio-browser.png (png is better). We are then simply doing inplace replace of the minio-browser-gateway.png. Since the filenames are the same you dont see any file name changes in the md files. Wheras for the minio-browser.jpg we are forced to make changes since it will be minio-browser.png.  HTH.

**Review by nitisht — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
