### PR TITLE
perform zero-zopy discards

### PR DESCRIPTION
**Pull request by wlan0**
Following up on this PR: https://github.com/minio/minio/pull/7214

As mentioned by @donatello: 

> Discard actually implements ReadFrom and this would be used by io.Copy - internally it allocates from a sync.Pool an 8kb buffer, which can't really be avoided.

This change removes the 8k buffer allocation while draining http streams with `Content-Length` set. In the most likely case, where we drain already-drained http bodies, we will allocate no buffer.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Can you check why Travis is failing ?

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by donatello — CHANGES_REQUESTED** [review]
There is no actual buffer copying saving here because the copying happens in the Read call before the Write method is called. Potentially we may save an allocation when the src is already read but if that's that important it is better to rewrite this without all the io.Copy complexity and explicitly using the LimitedReader optimization.

**Comment by wlan0** [comment]
> There is no actual buffer copying saving here because the copying happens in the Read call before the Write method is called. Potentially we may save an allocation when the src is already read but if that's that important it is better to rewrite this without all the io.Copy complexity and explicitly using the LimitedReader optimization.

What makes you think we're not using the LimitReader optimization? The part you seem to be missing is that, even with the LimitReader optimization, the io.Discard ends up using a buffer. This removes that problem. 

Even if you had read it all before discarding, this buffer would get allocated.

**Comment by harshavardhana** [comment]
Here are the numbers which are helpful 

```
~  go test -bench .
goos: linux
goarch: amd64
pkg: github.com/minio/drain
BenchmarkPR7217-4       	 5000000	       404 ns/op	5069.02 MB/s	    2080 B/op	       2 allocs/op
BenchmarkCopy-4         	20000000	       100 ns/op	20290.76 MB/s	      32 B/op	       1 allocs/op
BenchmarkCopyBuffer-4   	20000000	       100 ns/op	20445.78 MB/s	      32 B/op	       1 allocs/op
BenchmarkOptimal-4      	30000000	        43.6 ns/op	46952.75 MB/s	      32 B/op	       1 allocs/op
PASS
ok  	github.com/minio/drain	41.830s
```

```go
package drain

import (
	"io"
	"io/ioutil"
)

// ZeroCopyDiscard is a /dev/null equivalent write stream that does not allocate a buffer
var ZeroCopyDiscard = zeroCopyDiscard(0)

func ReaderPR7217(respBody io.Reader) {
	io.Copy(ZeroCopyDiscard, respBody)
}

type zeroCopyDiscard int

func (z zeroCopyDiscard) Write(b []byte) (int, error) {
	return len(b), nil
}

var buf = make([]byte, 512)

func ReaderOptimal(reader io.Reader) {
	for {
		if _, err := reader.Read(buf); err != nil {
			return
		}
	}
}

func ReaderCopy(reader io.Reader) {
	io.Copy(ioutil.Discard, reader)
}

func ReaderCopyBuf(reader io.Reader) {
	io.CopyBuffer(ioutil.Discard, reader, buf)
}
```

```go
package drain

import (
	"bytes"
	"io"
	"testing"
)

func benchmark(b *testing.B, size int64, drainer func(io.Reader)) {
	r := bytes.NewReader(bytes.Repeat([]byte("a"), int(size)))
	b.ResetTimer()
	b.SetBytes(size)
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		drainer(io.LimitReader(r, size))
	}
}

func BenchmarkPR7217(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderPR7217)
	}
}

func BenchmarkCopy(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderCopy)
	}
}

func BenchmarkCopyBuffer(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderCopyBuf)
	}
}

func BenchmarkOptimal(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderOptimal)
	}
}
```

**Comment by harshavardhana** [comment]
One more implementation with bufPool involved.

```
~ go test -bench .
goos: linux
goarch: amd64
pkg: github.com/minio/drain
BenchmarkPR7217-4             	 5000000	       442 ns/op	4631.37 MB/s	    2080 B/op	       2 allocs/op
BenchmarkCopyBufferPool-4     	10000000	       171 ns/op	11953.56 MB/s	      32 B/op	       1 allocs/op
BenchmarkOptimalPool-4        	20000000	       120 ns/op	17009.00 MB/s	      32 B/op	       1 allocs/op
BenchmarkCopy-4               	10000000	       107 ns/op	18963.22 MB/s	      32 B/op	       1 allocs/op
BenchmarkCopyBufferStatic-4   	20000000	       101 ns/op	20115.80 MB/s	      32 B/op	       1 allocs/op
BenchmarkOptimalStatic-4      	30000000	        44.2 ns/op	46282.87 MB/s	      32 B/op	       1 allocs/op
PASS
ok  	github.com/minio/drain	61.960s
```

```go
package drain

import (
	"io"
	"io/ioutil"
	"sync"
)

// ZeroCopyDiscard is a /dev/null equivalent write stream that does not allocate a buffer
var ZeroCopyDiscard = zeroCopyDiscard(0)

func ReaderPR7217(respBody io.Reader) {
	io.Copy(ZeroCopyDiscard, respBody)
}

type zeroCopyDiscard int

func (z zeroCopyDiscard) Write(b []byte) (int, error) {
	return len(b), nil
}

var b512pool = sync.Pool{
	New: func() interface{} {
		buf := make([]byte, 512)
		return &buf
	},
}

var buf = make([]byte, 512)

func ReaderOptimalPool(reader io.Reader) {
	bufp := b512pool.Get().(*[]byte)
	defer b512pool.Put(bufp)

	for {
		if _, err := reader.Read(*bufp); err != nil {
			return
		}
	}
}

func ReaderOptimalStatic(reader io.Reader) {
	for {
		if _, err := reader.Read(buf); err != nil {
			return
		}
	}
}

func ReaderCopy(reader io.Reader) {
	io.Copy(ioutil.Discard, reader)
}

func ReaderCopyBufStatic(reader io.Reader) {
	io.CopyBuffer(ioutil.Discard, reader, buf)
}

func ReaderCopyBufPool(reader io.Reader) {
	bufp := b512pool.Get().(*[]byte)
	defer b512pool.Put(bufp)
	io.CopyBuffer(ioutil.Discard, reader, *bufp)
}
```

```go
package drain

import (
	"bytes"
	"io"
	"testing"
)

func benchmark(b *testing.B, size int64, drainer func(io.Reader)) {
	r := bytes.NewReader(bytes.Repeat([]byte("a"), int(size)))
	b.ResetTimer()
	b.SetBytes(size)
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		drainer(io.LimitReader(r, size))
	}
}

func BenchmarkPR7217(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderPR7217)
	}
}

func BenchmarkCopyBufferPool(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderCopyBufPool)
	}
}

func BenchmarkOptimalPool(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderOptimalPool)
	}
}

func BenchmarkCopy(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderCopy)
	}
}

func BenchmarkCopyBufferStatic(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderCopyBufStatic)
	}
}

func BenchmarkOptimalStatic(b *testing.B) {
	for _, i := range []int64{
		10,
		50,
		100,
		512,
		1024,
		2048,
	} {
		benchmark(b, i, ReaderOptimalStatic)
	}
}
```

**Comment by harshavardhana** [comment]
I guess let's leave the way things are with `io.Copy(ioutil.Discard, respBody)` - I don't think we need this PR.

**Comment by wlan0** [comment]
I'm fine with closing the PR. The benchmark numbers are as expected. The optimization was supposed to help when most of the streams are already closed, as it is with our usage of drain body.

**Pull request closed without merging**
