### PR TITLE
xl: Fix locking in xl HealObject

### PR DESCRIPTION
**Pull request by vadmeste**
## Description

Move locking to the correct location, before loading
object data.

## Motivation and Context
Fix issues found when doing something else

## How to test this PR?
This is an issue with locking, which is hard to reproduce.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by harshavardhana** [comment]
The second one is not a bug @vadmeste we don't need write locks because read locks are sufficient to write to parts which are not on disk and also allow read locks to read the data as well.

So the second issue is not useful so you need to add the read lock before reading xl.json

**Review by harshavardhana — DISMISSED** [review]

**Comment by vadmeste** [comment]
> The second one is not a bug @vadmeste we don't need write locks because read locks are sufficient to write to parts which are not on disk and also allow read locks to read the data as well.
> 
> So the second issue is not useful so you need to add the read lock before reading xl.json

Fixed and added a comment

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#04605903-a7ea-4fcd-b50a-01244eff6ed6) |
| mint-compression-dist-xl.sh | :x: [more...](#65c4c781-e691-4563-933a-9d16d2ee40a4) |
| mint-dist-xl.sh | :x: [more...](#e2995b22-ac1a-4ab2-b887-64c7c1d65149) |
<a name="e2995b22-ac1a-4ab2-b887-64c7c1d65149"></a>
### 8455-6158f3c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31770
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ebfb16f29746:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 41 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 29 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 5 seconds
(11/14) Running minio-js tests ... done in 56 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 42 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 108,
  "args": {
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-28T23-30-59Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15D1F53B5BD9F41E\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 29 Oct 2019 00:03:00 GMT\"]}}",
    "bucket_name": "minio-py-test-30924c3a-fdd0-454f-acc8-fa1b30fc6f68",
    "response.status": 403,
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>244aa6f7-7d49-4f7e-8c63-5eb232c9b010</Key><BucketName>minio-py-test-30924c3a-fdd0-454f-acc8-fa1b30fc6f68</BucketName><Resource>/minio-py-test-30924c3a-fdd0-454f-acc8-fa1b30fc6f68/244aa6f7-7d49-4f7e-8c63-5eb232c9b010</Resource><RequestId>15D1F53B5BD9F41E</RequestId><HostId>ca9b68b3-adb8-42ac-8f03-a908a921db23</HostId></Error>",
    "object_name": "244aa6f7-7d49-4f7e-8c63-5eb232c9b010",
    "presigned_get_object_url": "http://72.28.97.52:31770/minio-py-test-30924c3a-fdd0-454f-acc8-fa1b30fc6f68/244aa6f7-7d49-4f7e-8c63-5eb232c9b010?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191029%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191029T000247Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=ecc77f79bd7ae1d50dac5384566949817b931cb7d1339feaf74e4da7b34bc828",
    "response.reason": "Forbidden"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="04605903-a7ea-4fcd-b50a-01244eff6ed6"></a>
### 8455-6158f3c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31166
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d794358a29f6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 18 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 40 seconds
{
  "args": {},
  "duration": 110677,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="65c4c781-e691-4563-933a-9d16d2ee40a4"></a>
### 8455-6158f3c/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30057
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bb003f19c788:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 51 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 12 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 56 seconds
(11/14) Running minio-js tests ... done in 53 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 58 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "args": {
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-28T23-30-59Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15D1F5334E94830B\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 29 Oct 2019 00:02:25 GMT\"]}}",
    "object_name": "5a2e577d-fa6f-441d-bbb6-17efed6ef75d",
    "bucket_name": "minio-py-test-3594f3d3-f297-44aa-b3aa-ca867776e44a",
    "response.reason": "Forbidden",
    "presigned_get_object_url": "http://72.28.97.58:30057/minio-py-test-3594f3d3-f297-44aa-b3aa-ca867776e44a/5a2e577d-fa6f-441d-bbb6-17efed6ef75d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191029%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191029T000213Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=d3dac661fce4f2f98200033454af047751cd68b48b7ee69e4efc76b918992993",
    "response.status": 403,
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>5a2e577d-fa6f-441d-bbb6-17efed6ef75d</Key><BucketName>minio-py-test-3594f3d3-f297-44aa-b3aa-ca867776e44a</BucketName><Resource>/minio-py-test-3594f3d3-f297-44aa-b3aa-ca867776e44a/5a2e577d-fa6f-441d-bbb6-17efed6ef75d</Resource><RequestId>15D1F5334E94830B</RequestId><HostId>48810804-59b5-4fb4-bc26-74e0cc2893c2</HostId></Error>"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "duration": 602,
  "status": "FAIL",
  "message": "AccessDenied: message: Access Denied"
}

Executed 11 out of 14 tests successfully.
```
Error: No such image: minio/minio:8455-6158f3c

**Review by harshavardhana — APPROVED** [review]

**Comment by vadmeste** [comment]
ping @donatello

**Review by donatello — APPROVED** [review]

**Pull request merged**
