### PR TITLE
Implement basic S3 notifications through queues

### PR DESCRIPTION
**Pull request by yrashk**
Supports multiple queues and three basic queue types:
1. NilQueue -- messages don't get sent anywhere
2. LogQueue -- messages get logged
3. AmqpQueue -- messages are sent to an AMQP queue

### CODE REVIEW

**Comment by yrashk** [comment]
For reference: http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html

**Comment by abperiasamy** [comment]
Awesome contribution @yrashk. We were about to start working on it.

**Comment by yrashk** [comment]
@abperiasamy thanks; anything I can do to ease the merging? (besides rebasing)

**Comment by yrashk** [comment]
Rebased.

**Comment by harshavardhana** [comment]
> @abperiasamy thanks; anything I can do to ease the merging? (besides rebasing)

@yrashk i am testing this locally right now and will merge soon.  You can leave rebasing for us thanks for your contribution.  

There are some changes in the area where new patches are modifying it, will make sure to merge fix those conflicts and merge.

**Comment by harshavardhana** [comment]
After discussing this internally, we have some design changes on how this needs to be addressed @yrashk are you on https://gitter.im we can talk about this in detail ?

**Comment by yrashk** [comment]
Yeah I'm on gitter.

**Comment by harshavardhana** [comment]
> Yeah I'm on gitter.

@yrashk - reached out to you let me know when you are available.

**Comment by harshavardhana** [comment]
Closing this as merged functionality on master.

**Pull request closed without merging**
