### PR TITLE
Remove "-1" appended at the end of ETag on OSS gateway

### LINKED ISSUE #9229: Minio gateway oss compat
Minio gateway for OSS doesn't support the **--compat** option or it doesn't take any effect. As a result aws sdk v2 throws the exception:
```
java.lang.IllegalArgumentException: Invalid base 16 character: '-'

	at software.amazon.awssdk.utils.internal.Base16Codec.pos(Base16Codec.java:80)
	at software.amazon.awssdk.utils.internal.Base16Codec.decode(Base16Codec.java:66)
	at software.amazon.awssdk.utils.internal.Base16Lower.decode(Base16Lower.java:65)
	at software.amazon.awssdk.services.s3.checksums.ChecksumsEnabledValidator.validatePutObjectChecksum(ChecksumsEnabledValidator.java:144)
```

The reason is redundant "-1" suffix in the Etag value. For example:
Aws sdk expects `Etag: 1D4690BA4BC0FC9D867E990630876A34`
But gets `Etag: 1D4690BA4BC0FC9D867E990630876A34-1`

I found issues:
https://github.com/minio/minio/issues/7642
https://github.com/minio/minio/issues/7756
and tried to enable compat mode but it didn't work out.
What are plans for **compat** option for OSS gateway? It would be great if it is supported.

## Steps to reproduce:

1. Start gateway `MINIO_ACCESS_KEY=*** MINIO_SECRET_KEY=*** minio --compat gateway oss https://oss-cn-hongkong.aliyuncs.com --address 127.0.0.1:9090`
2. Run Java sample
```
        final S3Client s3Client = S3Client.builder()
                .endpointOverride(ossEndpoint)
                .region(Region.of(region))
                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(accessKey, secretKey)))
                .build();
        final PutObjectRequest putRequest = PutObjectRequest.builder().bucket(bucket).key(key).build();
        RequestBody body = RequestBody.fromString("");
        s3Client.putObject(putRequest, body);
```

## Environment
MacOS Catalina
minio version RELEASE.2020-03-25T07-03-04Z
aws sdk 2.11.4

### PR DESCRIPTION
**Pull request by ebozduman**
## Description
Fixes #9229
MinIO appends a redundant "-1" suffix to Etag.
This causes exception `java.lang.IllegalArgumentException: Invalid base 16 character: '-'`, when a put is done with MinIO as a `gateway oss`.

## Motivation and Context
We need to prevent the exception.

## How to test this PR?
Start MinIO as a gateway to Alibaba Cloud Object Storage Service (OSS) and run a `java` script that tries to put a file.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#fa4d1556-4cc8-4522-93f8-0eccb4ae7cff) |
<a name="fa4d1556-4cc8-4522-93f8-0eccb4ae7cff"></a>
### 9243-4bc2c27/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32313
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5da75046cc0c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 10 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 9 minutes and 12 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 2 minutes and 35 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 41 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 45 seconds
(9/15) Running minio-go tests ... done in 22 minutes and 14 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 24 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11183,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-1l6btbc, objectName=minio-java-test-1hc4kqg, resource=/minio-java-test-1l6btbc/minio-java-test-1hc4kqg, requestId=160192059933343B, hostId=effc5d1c-523b-4410-8f2f-01b49dfe0053)\nrequest={method=PUT, url=http://minio-c3.minio.io:32313/minio-java-test-1l6btbc/minio-java-test-1hc4kqg?uploadId=6f8d38dc787d5c13&partNumber=1, headers=x-amz-copy-source-if-match: c67429520c3ee4ae74a484e5b18c0b27-2\nx-amz-copy-source: minio-java-test-1l6btbc/minio-java-test-3aupcgl\nAccept-Encoding: identity\nHost: minio-c3.minio.io:32313\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200401T024456Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200401/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160192059933343B\nX-Xss-Protection: 1; mode=block\nDate: Wed, 01 Apr 2020 02:44:56 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
I hope my title edit is accurate. If so, no problem.

**Comment by Praveenrajmani** [comment]
@ebozduman Other tools like s3cmd verifies this ETag for checksum verification. By suffixing this with `-`, we denote that ETag is not a checksum.

So, this change would perpetually fail those requests which validates the checksum with the ETag been responded.. Is that OK?

**Comment by harshavardhana** [comment]
> So, this change would perpetually fail those requests which validates the checksum with the ETag been responded.. Is that OK?

We need to preserve ETag if possible as sent by OSS @Praveenrajmani for the most part OSS is S3 compatible.

**Review by Praveenrajmani — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#c157a3b9-5881-4d9d-9ea7-faa6a6ed2c7e) |
<a name="c157a3b9-5881-4d9d-9ea7-faa6a6ed2c7e"></a>
### 9243-54bdbdd/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30018
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 49f4f6a88463:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 8 minutes and 58 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 3 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 6 minutes and 37 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 47 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 13 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 3 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName)",
  "duration": 4479,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name=StorageClass, data=false, type=void, required=true) on field 'storageClass' private java.lang.String io.minio.messages.Item.storageClass in class io.minio.messages.Item at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioClient.listObjectsV2(MinioClient.java:3018), io.minio.MinioClient.access$100(MinioClient.java:152), io.minio.MinioClient$2$1.populate(MinioClient.java:2879), io.minio.MinioClient$2$1.hasNext(MinioClient.java:2910), FunctionalTest.listObject_test1(FunctionalTest.java:1436), FunctionalTest.runTests(FunctionalTest.java:3817), FunctionalTest.main(FunctionalTest.java:3963)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
