### PR TITLE
Preserve ETag case for S3 compatibility

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Preserve ETag case for S3 compatibility

## Motivation and Context
Most hadoop distributions hortonworks, cloudera all
depend on aws-sdk-java 1.7.x to 1.10.x - the releases
which have bugs related case sensitive check for
ETag header. Go changes the case of the headers set
to be canonical but only preserves them when set
through a direct map.

This fixes most compatibility issues we have had
in the past supporting older hadoop distributions.

## Regression
No

## How Has This Been Tested?
Using hortonworks HDP 2.6.5 with hadoop 2.7.3 and aws-sdk-java 1.10.6

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by poornas — CHANGES_REQUESTED** [review]
For consistency, can you also make this change in checkCopyObjectPreconditions and checkPreconditions

**Comment by harshavardhana** [comment]
> For consistency, can you also make this change in checkCopyObjectPreconditions and checkPreconditions

Done @poornas

**Review by donatello — DISMISSED** [review]

**Review by poornas — DISMISSED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d6ce4d04-402d-4b76-86eb-3a7bb4686959) |
| mint-large-bucket.sh | :x: [more...](#75315833-6db8-412f-836e-db9211285e45) |
| mint-compression-dist-xl.sh | :x: [more...](#371f2bbc-2b32-4acb-8e31-19ee830274d4) |
<a name="d6ce4d04-402d-4b76-86eb-3a7bb4686959"></a>
### 7498-e1cc870/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30445
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b575f3082454:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vyv025hevz4r60",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120328,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30445/aws-sdk-go-test-vyv025hevz4r60: dial tcp 72.28.97.60:30445: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="75315833-6db8-412f-836e-db9211285e45"></a>
### 7498-e1cc870/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32095
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e1a4c20fd389:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 6 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 2 seconds
(4/14) Running aws-sdk-ruby tests ... done in 19 seconds
(5/14) Running awscli tests ... done in 1 minutes and 32 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/14) Running minio-go tests ... done in 4 minutes and 3 seconds
(10/14) Running minio-java tests ... done in 9 minutes and 17 seconds
(11/14) Running minio-js tests ... done in 1 minutes and 8 seconds
(12/14) Running minio-py tests ... FAILED in 10 minutes and 39 seconds
{
  "duration": 1280,
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "bucket_name": "minio-py-test-e3549ea3-0353-47cd-be00-7a5ac0b02e55",
    "object_name": "79378f4c-c5e9-48f3-8835-0b09463db745"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="371f2bbc-2b32-4acb-8e31-19ee830274d4"></a>
### 7498-e1cc870/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30732
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bfb63ba28d45:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-cgtga4vbah2fgd",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360034,
  "error": "XMinioWriteQuorum: Multiple disks failures, unable to write data.\n\tstatus code: 503, request id: 15939C235DED4B79, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by kannappanr** [comment]
@harshavardhana Please fix unit tests. Travis is failing.

**Comment by harshavardhana** [comment]
> @harshavardhana Please fix unit tests. Travis is failing.

Done @kannappanr

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-worm.sh | :x: [more...](#28ddfce9-34ea-4333-b834-1b7995667040) |
<a name="28ddfce9-34ea-4333-b834-1b7995667040"></a>
### 7498-e99f708/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31169
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 78f334379d26:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-boyo0qk5y5li81dhazdiqe16krc9mtni4xrtyspdtsq66c2fvcjva27",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 3053,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31169/bucket-boyo0qk5y5li81dhazdiqe16krc9mtni4xrtyspdtsq66c2fvcjva27: dial tcp 72.28.97.57:31169: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```

**Comment by kannappanr** [comment]
ping @poornas @donatello

**Review by donatello — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#b3d9bc49-bd9b-4f9c-ac1f-00d97266df43) |
<a name="b3d9bc49-bd9b-4f9c-ac1f-00d97266df43"></a>
### 7498-3ca3d53/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30188
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5d43c1fd412c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-etffzkcl6gy4do",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3056,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30188/aws-sdk-go-test-etffzkcl6gy4do: dial tcp 72.28.97.57:30188: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by poornas — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :x: [more...](#7e5c9322-683f-42a1-8a3e-92a4f8fb65e9) |
<a name="7e5c9322-683f-42a1-8a3e-92a4f8fb65e9"></a>
### 7498-8d38a5a/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30391
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4546afa2325f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dklsd5t3qym1mz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3065,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30391/aws-sdk-go-test-dklsd5t3qym1mz: dial tcp 72.28.97.57:30391: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :x: [more...](#8d82356d-47f6-44ac-a1d0-ed896bdeccef) |
| mint-gateway-nas.sh | :x: [more...](#25b187a0-db26-4e01-b5ce-723587244986) |
<a name="8d82356d-47f6-44ac-a1d0-ed896bdeccef"></a>
### 7498-f79072f/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31090
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6180b73d3233:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-gvkrovcvrewgpfz2h82p4t8a1qvubccbesde8v01widcfz74mj823vr",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 3068,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31090/bucket-gvkrovcvrewgpfz2h82p4t8a1qvubccbesde8v01widcfz74mj823vr: dial tcp 72.28.97.57:31090: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="25b187a0-db26-4e01-b5ce-723587244986"></a>
### 7498-f79072f/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32503
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp af229612f000:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ck6n3vgomiuyff",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2722,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32503/aws-sdk-go-test-ck6n3vgomiuyff: dial tcp 72.28.97.57:32503: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Pull request merged**
