### PR TITLE
fix: support pre-sign signature for STS tokens

### LINKED ISSUE #8391: STS AssumeRole - Getting SignatureDoesNotMatch with Presigned PutObject Request
I'm pretty sure this is a Minio issue as I have tested the same code against S3 and it works. I've eliminated all other possibilities.

I have a set of temporary credentials, meaning I'm using a Session Token returned from the AssumeRole API. I have tested these credentials using the AWS CLI and a simple PutObject. That request succeeds. When using AWS iOS SDK the same request, with the same credentials fails. I have tried on multiple versions of iOS SDK from the latest, to some pretty old ones all with the exact same result. With http tracing turned on on Minio, the only difference between the two requests is that the working request includes the authentication headers, while the presigned requests submits them as URL Query Parameters. Example requests below:

Working
```
[REQUEST s3.PutObject] 23:53:59.968
PUT /bucket/file.jpg
Host: HOSTNAME.com
Content-Type: text/plain
Expect: 100-continue
X-Amz-Date: 20191011T235359Z
X-Amz-Security-Token: SESSION_TOKEN
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=ACCESS_KEY/20191011/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=7e73f94d9cf741652a0bd5cfa8589fc80393752cdaa4b18f436ca7c14a73391f
Content-Length: 0
User-Agent: aws-cli/1.16.113 Python/3.7.3 Linux/4.19.0-6-amd64 botocore/1.12.103
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
<BODY>
[RESPONSE] [23:53:59.982] [ Duration 14.218ms  🠉 134 B  🠋 261 B ]
200 OK
X-Amz-Request-Id: 15CCBCDFEBFD0A85
X-Xss-Protection: 1; mode=block
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
ETag: "bd6c49dfcd4b947adf8e974af9b7d89c-1"
Server: MinIO/RELEASE.2019-09-25T18-25-51Z
Vary: Origin
<BODY>
```

Not working

```
PUT /bucket/file.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ACCESS_KEY%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T234948Z&X-Amz-Expires=2999&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Security-Token=SESSION_TOKEN&X-Amz-Signature=cd26642f11b8b3c5a8f4786df40ffdf967835d1287ccf7e7d4b19a51c11fa014
Host: HOSTNAME
Accept-Language: en-us
Content-Length: 3592778
User-Agent: aws-sdk-iOS/2.10.3 iOS/12.4.2 en_US transfer-utility
Accept: */*
Accept-Encoding: br, gzip, deflate
Connection: keep-alive
Content-Type: image/jpeg
<BODY>
[RESPONSE] [23:49:50.254] [ Duration 737.341ms  🠉 123 B  🠋 722 B ]
403 Forbidden
X-Xss-Protection: 1; mode=block
Accept-Ranges: bytes
Content-Length: 465
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2019-09-25T18-25-51Z
Vary: Origin
X-Amz-Request-Id: 15CCBCA59BE7554D
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>1/80/1-146-80_2019-10-11_22-20-24.jpg</Key><BucketName>lets.minio</BucketName><Resource>/lets.minio/1/80/1-146-80_2019-10-11_22-20-24.jpg</Resource><RequestId>15CCBCA59BE7554D</RequestId><HostId>65039a11-b6d1-4577-b1fd-60251134a48c</HostId></Error>
```

## Expected Behavior

Presigned PutObject requests using temporary credentials from AssumRole API should succeed

## Current Behavior

When making a PUT request like
```PUT /bucket/image.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ZU1YPXXYOENJ1K1EJYR6%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T234948Z&X-Amz-Expires=2999&X-Amz-SignedHeaders=content-type%3Bhost%3Bx-amz-server-side-encryption&X-Amz-Security-Token=TOKEN&X-Amz-Signature=cd26642f11b8b3c5a8f4786df40ffdf967835d1287ccf7e7d4b19a51c11fa014```
the request fails with ```SignatureDoesNotMatch```
## Steps to Reproduce (for bugs)

1. Currently using AWSTransferUtility in iOS SDK which generates presigned PutObject requests. To reproduce, generate a presigned PutObject requests using STS temporary credentials. AWS Docs: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html

## Context

I am trying to use AWS SDK's to allow untrusted clients temporary access to access files at specific prefixes in a bucket. 

## Your Environment

* Version used (`minio version`): 2019-09-25T18:25:51Z
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: EC2 
* Operating System and version (`uname -a`): 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: support pre-sign signature for STS tokens

## Motivation and Context
Fixes #8391

## How to test this PR?
You need to generate `assume-role` creds using aws cli and then use them to generate
presigned URLs

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#64cdffbb-424b-4431-969f-7bca40a675d5) |
| mint-large-bucket.sh | :x: [more...](#f1886680-3cf8-4b29-a521-08a7180560ab) |
<a name="64cdffbb-424b-4431-969f-7bca40a675d5"></a>
### 8826-95ac8b7/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30763
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 06bc5446147b:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 9 seconds
{
  "name": "awscli",
  "duration": 7323,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="f1886680-3cf8-4b29-a521-08a7180560ab"></a>
### 8826-95ac8b7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32616
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9be79c7e1b41:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 16 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 57 seconds
(5/13) Running minio-go tests ... FAILED in 2 minutes and 52 seconds
{
  "args": {},
  "duration": 72401,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by vadmeste** [comment]
@harshavardhana I am not sure what I am missing here but the following test does not work (signature mismatch error)

```sh
#!/bin/bash


sts=$(aws --endpoint-url http://localhost:9000 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything)

export AWS_ACCESS_KEY_ID=$(echo "$sts" | jq -r .Credentials.AccessKeyId)
export AWS_SECRET_ACCESS_KEY=$(echo "$sts" | jq -r .Credentials.SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo "$sts" | jq -r .Credentials.SessionToken)

echo "Credentials:  >> $AWS_ACCESS_KEY_ID << >> $AWS_SECRET_ACCESS_KEY >> << $AWS_SESSION_TOKEN >>"

presigned_url="$(aws s3 presign s3://testbucket/upload/file | sed 's#https://testbucket.s3.amazonaws.com#http://localhost:9000#')"

echo "Presigned URL: >> $presigned_url <<"

curl -X GET "$presigned_url"

```

**Comment by harshavardhana** [comment]
> ```shell
> presigned_url="$(aws s3 presign s3://testbucket/upload/file | sed 's#https://testbucket.s3.amazonaws.com#http://localhost:9000#')"
> ```

The issue is here @vadmeste you need to use the `--endpoint-url` which is missing - doing a sed won't help since Host header will be different

**Comment by harshavardhana** [comment]
Works fine now 

```
~ /tmp/assume-role.sh 
Credentials:  >> SLQ9OCQ3CAWEMDBLV2WI << >> oSRZx+1fD+TgQxQXq4NYX1yQguXX1h+mBbNYFLgE >> << eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJTTFE5T0NRM0NBV0VNREJMVjJXSSIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoicmVhZHdyaXRlIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVUzUnRkREVpTENKRlptWmxZM1FpT2lKQmJHeHZkeUlzSWtGamRHbHZiaUk2SW5Nek9pb2lMQ0pTWlhOdmRYSmpaU0k2SW1GeWJqcGhkM002Y3pNNk9qb3FJbjFkZlE9PSJ9.TVXWh0kSVzncEUnc-x0W1fThGZe2Aw9zKBN5wn4uMfNXPCdUx4xENpw9nI0XIck86n5VVOoum_Vz2U7jjAjaWg >>
Presigned URL: >> http://localhost:9000/testbucket/upload/file?AWSAccessKeyId=foobar&Expires=1579300795&Signature=2fVBgRYWj5tu7yuAWzC3LHB4PTw%3D <<
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:9000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /testbucket/upload/file?AWSAccessKeyId=foobar&Expires=1579300795&Signature=2fVBgRYWj5tu7yuAWzC3LHB4PTw%3D HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Accept-Ranges: bytes
< Content-Length: 347
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO/DEVELOPMENT.2020-01-17T21-35-49Z
< Vary: Origin
< X-Amz-Bucket-Region: us-east-1
< X-Amz-Request-Id: 15EACA6E87D1C575
< X-Xss-Protection: 1; mode=block
< Date: Fri, 17 Jan 2020 21:39:55 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>upload/file</Key><BucketName>testbucket</BucketName><Resource>/testbucket/upload/file</Resource><Region>us-east-1</Region><RequestId>15EACA6E87D1C575</RequestId><HostId>9b7bfaac-dacc-4bf4-90fa-a13607351872</HostId></Error>
```

```sh
#!/bin/bash


sts=$(aws --profile foobar --endpoint-url http://localhost:9000 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything)

export AWS_ACCESS_KEY_ID=$(echo "$sts" | jq -r .Credentials.AccessKeyId)
export AWS_SECRET_ACCESS_KEY=$(echo "$sts" | jq -r .Credentials.SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo "$sts" | jq -r .Credentials.SessionToken)

echo "Credentials:  >> $AWS_ACCESS_KEY_ID << >> $AWS_SECRET_ACCESS_KEY >> << $AWS_SESSION_TOKEN >>"

presigned_url="$(aws --profile foobar --endpoint-url http://localhost:9000 s3 presign s3://testbucket/upload/file)"

echo "Presigned URL: >> $presigned_url <<"

curl -v -X GET "$presigned_url"
```

**Comment by harshavardhana** [comment]
Works also with signature v4

```
~ /tmp/assume-role.sh 
Credentials:  >> GOB9JXU3N3HANO8PSXGN << >> B+yjubQiYz7pYB5Y4lUqxjMzcUtj+RySpDbTgMaW >> << eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJHT0I5SlhVM04zSEFOTzhQU1hHTiIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoicmVhZHdyaXRlIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVUzUnRkREVpTENKRlptWmxZM1FpT2lKQmJHeHZkeUlzSWtGamRHbHZiaUk2SW5Nek9pb2lMQ0pTWlhOdmRYSmpaU0k2SW1GeWJqcGhkM002Y3pNNk9qb3FJbjFkZlE9PSJ9.29lIkEAt5gYLfoB864GV1rll6a2ShHUO_38lDirxf1_SMZUpywZJp2NlAbyS6dCJwF37eAHKyAhJ62Me1l7y4w >>
Presigned URL: >> http://localhost:9000/testbucket/upload/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Credential=foobar%2F20200117%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20200117T215233Z&X-Amz-Signature=7f1bcacc89080473f102916da3e20010601bb248a90267ccd09c5ce1750bde7f <<
*   Trying 127.0.0.1:9000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /testbucket/upload/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Credential=foobar%2F20200117%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20200117T215233Z&X-Amz-Signature=7f1bcacc89080473f102916da3e20010601bb248a90267ccd09c5ce1750bde7f HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Accept-Ranges: bytes
< Content-Length: 347
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO/DEVELOPMENT.2020-01-17T21-35-49Z
< Vary: Origin
< X-Amz-Bucket-Region: us-east-1
< X-Amz-Request-Id: 15EACB1EFA467E0C
< X-Xss-Protection: 1; mode=block
< Date: Fri, 17 Jan 2020 21:52:33 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>upload/file</Key><BucketName>testbucket</BucketName><Resource>/testbucket/upload/file</Resource><Region>us-east-1</Region><RequestId>15EACB1EFA467E0C</RequestId><HostId>9b7bfaac-dacc-4bf4-90fa-a13607351872</HostId></Error>
```

NOTE: region has to be set for pre-sign to be signature-v4

```
cat ~/.aws/config 
[default]
region = eu-central-1 
s3 =
    signature_version = s3v4
[profile foobar]
region = us-east-1
s3 =
    signature_version = s3v4
```

```
~ cat ~/.aws/credentials 
[default]
aws_access_key_id=minio
aws_secret_access_key=minio123

[foobar]
aws_access_key_id = foobar
aws_secret_access_key = foo12345
```

**Comment by harshavardhana** [comment]
Works also with signature v4

```
~ /tmp/assume-role.sh 
Credentials:  >> N2U7IQ6D269PBS4NNFOR << >> WZdbL4UTPc7NIX8+weRbBmR0lXmuJd5kpsL5RuV9 >> << eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJOMlU3SVE2RDI2OVBCUzROTkZPUiIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoicmVhZHdyaXRlIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVUzUnRkREVpTENKRlptWmxZM1FpT2lKQmJHeHZkeUlzSWtGamRHbHZiaUk2SW5Nek9pb2lMQ0pTWlhOdmRYSmpaU0k2SW1GeWJqcGhkM002Y3pNNk9qb3FJbjFkZlE9PSJ9.epp3H4miZwhPqU7EyMIOintV82pNkIT4tUacHrpv0S1yXiLOtwCygnUk4p2EUfgLnfcwbVEfOC8Kxi3P_zVUJA >>
Presigned URL: >> http://localhost:9000/testbucket/upload/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Date=20200117T215438Z&X-Amz-SignedHeaders=host&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJOMlU3SVE2RDI2OVBCUzROTkZPUiIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoicmVhZHdyaXRlIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVUzUnRkREVpTENKRlptWmxZM1FpT2lKQmJHeHZkeUlzSWtGamRHbHZiaUk2SW5Nek9pb2lMQ0pTWlhOdmRYSmpaU0k2SW1GeWJqcGhkM002Y3pNNk9qb3FJbjFkZlE9PSJ9.epp3H4miZwhPqU7EyMIOintV82pNkIT4tUacHrpv0S1yXiLOtwCygnUk4p2EUfgLnfcwbVEfOC8Kxi3P_zVUJA&X-Amz-Credential=N2U7IQ6D269PBS4NNFOR%2F20200117%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=15eb3dabfb0258c25874d64cfd0bd4d7a0e429f98ef4ab9e566b4d22e51e22fc <<
*   Trying 127.0.0.1:9000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /testbucket/upload/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Date=20200117T215438Z&X-Amz-SignedHeaders=host&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJOMlU3SVE2RDI2OVBCUzROTkZPUiIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoicmVhZHdyaXRlIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVUzUnRkREVpTENKRlptWmxZM1FpT2lKQmJHeHZkeUlzSWtGamRHbHZiaUk2SW5Nek9pb2lMQ0pTWlhOdmRYSmpaU0k2SW1GeWJqcGhkM002Y3pNNk9qb3FJbjFkZlE9PSJ9.epp3H4miZwhPqU7EyMIOintV82pNkIT4tUacHrpv0S1yXiLOtwCygnUk4p2EUfgLnfcwbVEfOC8Kxi3P_zVUJA&X-Amz-Credential=N2U7IQ6D269PBS4NNFOR%2F20200117%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=15eb3dabfb0258c25874d64cfd0bd4d7a0e429f98ef4ab9e566b4d22e51e22fc HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Accept-Ranges: bytes
< Content-Length: 347
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO/DEVELOPMENT.2020-01-17T21-35-49Z
< Vary: Origin
< X-Amz-Bucket-Region: us-east-1
< X-Amz-Request-Id: 15EACB3C25377E7D
< X-Xss-Protection: 1; mode=block
< Date: Fri, 17 Jan 2020 21:54:38 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>upload/file</Key><BucketName>testbucket</BucketName><Resource>/testbucket/upload/file</Resource><Region>us-east-1</Region><RequestId>15EACB3C25377E7D</RequestId><HostId>9b7bfaac-dacc-4bf4-90fa-a13607351872</HostId></Error>
```

```sh
#!/bin/bash

sts=$(aws --profile foobar --endpoint-url http://localhost:9000 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything)

export AWS_ACCESS_KEY_ID=$(echo "$sts" | jq -r .Credentials.AccessKeyId)
export AWS_SECRET_ACCESS_KEY=$(echo "$sts" | jq -r .Credentials.SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo "$sts" | jq -r .Credentials.SessionToken)
export AWS_DEFAULT_REGION="us-east-1"

echo "Credentials:  >> $AWS_ACCESS_KEY_ID << >> $AWS_SECRET_ACCESS_KEY >> << $AWS_SESSION_TOKEN >>"

presigned_url="$(aws --endpoint-url http://localhost:9000 s3 presign s3://testbucket/upload/file)"

echo "Presigned URL: >> $presigned_url <<"

curl -v "$presigned_url"
```

**Review by vadmeste — APPROVED** [review]
LGTM & tested with signature v4

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
