### PR TITLE
Remove duration field from lock instrumentation

### PR DESCRIPTION
**Pull request by krisis**
## Description

Duration for which a lock was held can be computed from the `Since`
field of `OpsLockState`. It is the difference between current time and
time at which the namespace lock was held. This change avoids
superfluous instrumentation.

## Motivation and Context

See #4110 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by vadmeste** [comment]
@krisis umm, are we sure? doesn't that require from the client to have the correct time to correctly compute the duration ?

**Comment by donatello** [comment]
Tests need fix.

**Comment by krisis** [comment]
@vadmeste 
>@krisis umm, are we sure? doesn't that require from the client to have the correct time to correctly compute the duration ?

Interesting point you raise. If we can't expect clients to be in (time) sync with Minio server, then we will need both the time when the lock was held (as per Minio server) and duration. 

@harshavardhana @krishnasrinivas Is it correct to expect Minio server and clients like `mc` to have their time in sync?

**Comment by harshavardhana** [comment]
> @harshavardhana @krishnasrinivas Is it correct to expect Minio server and clients like mc to have their time in sync?

They can be different timezones but they should be in UTC sync - 15mins is the window allowed for time skew between `mc` and `minio`

**Comment by vadmeste** [comment]
Or we do the reverse, we un-export Since field and keep Duration

**Comment by krisis** [comment]
@vadmeste, Like we discussed, `Since` and `Duration` fields are both equivalent, given that the server and clients can't be farther than 15 minutes, I have decided to retain `Since` and remove `Duration` as it is in this PR. Could you provide further review comments if any?

**Review by vadmeste — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
