### PR TITLE
codebase imports an old repository github.com/coreos/etcd

### LINKED ISSUE #7304: codebase imports an old repository github.com/coreos/etcd
## Expected Behavior
* `import _ "github.com/minio/minio"`
* `import _ "go.etcd.io/etcd"`
* `go test ./...`

## Current Behavior
Running go tests outputs the following:
```
$ go test ./...                                                                                                                                                                
2019/02/27 14:02:13 proto: duplicate proto type registered: authpb.User
2019/02/27 14:02:13 proto: duplicate proto type registered: authpb.Permission
2019/02/27 14:02:13 proto: duplicate proto type registered: authpb.Role
panic: proto: duplicate enum registered: authpb.Permission_Type

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
        /home/vagrant/go/pkg/mod/github.com/golang/protobuf@v1.2.0/proto/properties.go:458
go.etcd.io/etcd/auth/authpb.init.0()
        /home/vagrant/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20180904210406-1df1ddff4361/auth/authpb/auth.pb.go:103 +0x1d7
FAIL    stash.detss.corpintra.net/dhc/t1        0.009s
```

## Possible Solution
Migrate etcd dependency from `github.com/coreos/etcd` to `go.etcd.io/etcd`.
This is what the etcd team has done due to repository migration: https://github.com/etcd-io/etcd/issues/9965

## Steps to Reproduce (for bugs)
use [gist](https://gist.github.com/chrischdi/b632cfae6bb3dac06790ae50f933101b)
`go test ./...`

## Context
We fixed it by on the following fork: If it is ok I would create a PR for it:
https://github.com/c445/minio/tree/revendor-etcd

## Your Environment
```
$ uname -a
Linux archlinux 4.20.12-arch1-1-ARCH #1 SMP PREEMPT Sat Feb 23 15:11:34 UTC 2019 x86_64 GNU/Linux
$ go version
go version go1.11.5 linux/amd64
```

### PR DESCRIPTION
**Pull request by chrischdi**
This PR replaces `github.com/coreos/etcd` by `go.etcd.io/etcd`.

## Description
Changed the imports by executing the following bash script:
```
#!/bin/bash
set -euo pipefail
 # This gives us some convenience functions, like log.
target_repo="go.etcd.io/etcd"
src_repo="github.com/coreos/etcd"

# log prints its arguments to stderr
function log() {
                echo "$@" >&2
        }


function migrate_files () {
     for file in $@; do
        echo sed -i -e "s@$src_repo@$target_repo@g" "$file"
        sed -i -e "s@$src_repo@$target_repo@g" "$file"
    done
}
log "[migrate] all .go files"
go_sources=`find . -iname '*.go' -not -path "./vendor/*" -exec grep -l "$src_repo" {} \;`
migrate_files $go_sources
gofmt -w pkg cmd
```
Afterwards I added the new and removed the old import via:
```
go get go.etcd.io/etcd
# use compatible version
pushd $GOPATH/go.etcd.io/etcd
git checkout 6143c135b
popd
for PKG in $(cat vendor/vendor.json| grep github.com/coreos/etcd | awk '{print $2}' | sed 's/,$//' | sed 's#github.com/coreos/etcd#go.etcd.io/etcd#g' ); do env PKG=$PKG make pkg-add; done
for PKG in $(cat vendor/vendor.json| grep github.com/coreos/etcd | awk '{print $2}' | sed 's/,$//'); do env PKG=$PKG make pkg-remove; done
```

## Motivation and Context
Fixes #7304

## How Has This Been Tested?
I did run a `make check` see [gist](https://gist.github.com/chrischdi/270aac1da59b98cb08f87d2f07cdd7f0)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :x: [more...](#b4204c18-2da3-446a-8770-27a442016265) |
| mint-worm.sh | :x: [more...](#f684d239-704d-4ffa-8e3a-0bfd9ec1770c) |
<a name="f684d239-704d-4ffa-8e3a-0bfd9ec1770c"></a>
### 7336-9cff6ff/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30164
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a9273b68b23f:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-0w16azmo7b9fm94g8x8tci7gds7b04py4fmj29lcra4xi323l43u4ke",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120241,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30164/bucket-0w16azmo7b9fm94g8x8tci7gds7b04py4fmj29lcra4xi323l43u4ke: dial tcp 72.28.97.60:30164: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="b4204c18-2da3-446a-8770-27a442016265"></a>
### 7336-9cff6ff/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31474
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b51be5ecfeef:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2nbc0drif43zdy",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 337,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31474/aws-sdk-go-test-2nbc0drif43zdy: dial tcp 72.28.97.55:31474: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
@chrisdi we are moving to non vendor model from go1.12 - we may not need to do this for now.

**Comment by chrischdi** [comment]
@harshavardhana then please consider the first commit for moving to the more current repository of etcd :-)

**Comment by harshavardhana** [comment]
We already have a PR which moves the vendor #7302

**Comment by chrischdi** [comment]
Then I will close this PR and will start watching the other issue if this is ok for you :-)

**Comment by chrischdi** [comment]
And maybe rebase/refactor & reopen this PR later on, because it looks like the issue will still persist for us because there still would get github.com/coreos/etcd get imported

**Comment by harshavardhana** [comment]
The go.mod can change to different repo in #7302

**Pull request closed without merging**
