### PR TITLE
save correct bucketInfo on it's indexes

### PR DESCRIPTION
**Pull request by jiuker**
## Description

bucketInfos[0] have data ready.
We should do like 
https://github.com/minio/minio/blob/8bfe972bab02982e77cd277049414f5cc8fb5a46/cmd/peer-s3-client.go#L92-L110

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by jiuker** [comment]
@harshavardhana 
https://github.com/jiuker/minio/blob/8bfe972bab02982e77cd277049414f5cc8fb5a46/cmd/erasure-server-pool.go#L1618-L1624

**Review by harshavardhana — CHANGES_REQUESTED** [review]
A safer way to do this is 

```diff
git diff
diff --git a/cmd/peer-s3-client.go b/cmd/peer-s3-client.go
index 62393594d..46664ab1d 100644
--- a/cmd/peer-s3-client.go
+++ b/cmd/peer-s3-client.go
@@ -144,9 +144,6 @@ func (sys *S3PeerSys) GetBucketInfo(ctx context.Context, bucket string, opts Buc
                return BucketInfo{}, err
        }
 
-       errs := []error{nil}
-       bucketInfos[0] = bucketInfo
-
        for idx, client := range sys.peerClients {
                idx := idx
                client := client
@@ -163,7 +160,9 @@ func (sys *S3PeerSys) GetBucketInfo(ctx context.Context, bucket string, opts Buc
                }, idx)
        }
 
-       errs = append(errs, g.Wait()...)
+       errs := g.Wait()
+       errs = append(errs, nil)
+       bucketInfos = append(bucketInfos, bucketInfo)
 
        quorum := (len(sys.allPeerClients) / 2)
        if err = reduceReadQuorumErrs(ctx, errs, bucketOpIgnoredErrs, quorum); err != nil {
```

**Comment by jiuker** [comment]
@harshavardhana 
`bucketInfos := make([]BucketInfo, len(sys.peerClients)+1)`
`bucketInfos = append(bucketInfos, bucketInfo)`
Here is an empty data at ` len(sys.peerClients)`?

**Comment by harshavardhana** [comment]
@jiuker we are only adding the local peer at the end. There is no order requirement here.

**Comment by harshavardhana** [comment]
Actually your PR is fine as well.

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :x: [more...](#e890776e-9b14-47f8-96fa-3dfa159b990e) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#7f6a1e64-fbeb-4a2c-996f-bd6f8f6dd698) |
| mint-pools.sh | :x: [more...](#1ae26364-ba82-4d5d-9627-14bac9f0b78e) |
<a name="1ae26364-ba82-4d5d-9627-14bac9f0b78e"></a>
### 16685-70b561a/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:30510
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 62bb054b9a31:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 9 seconds
(5/14) Running awscli tests ... done in 1 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-go tests ... done in 57 seconds
(9/14) Running minio-java tests ... done in 37 seconds
(10/14) Running minio-js tests ... FAILED in 2 minutes and 3 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, metaData)",
  "args": "bucketName:minio-js-test-4f3a50cc-7f1e-423f-aa12-ebb6cb664ad4, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 113559,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 2 minutes and 17 seconds
(11/14) Running s3cmd tests ... done in 18 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 33 seconds

Executed 13 out of 14 tests successfully.
```
<a name="7f6a1e64-fbeb-4a2c-996f-bd6f8f6dd698"></a>
### 16685-70b561a/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:30492
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp b30964ce7482:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 9 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 48 seconds
(9/14) Running minio-java tests ... done in 30 seconds
(10/14) Running minio-js tests ... FAILED in 2 minutes and 22 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 14,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(10/14) Running minio-py tests ... done in 2 minutes and 5 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 30 seconds

Executed 13 out of 14 tests successfully.
```
<a name="e890776e-9b14-47f8-96fa-3dfa159b990e"></a>
### 16685-70b561a/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.5:31712
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp ca14d04d6604:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 minutes and 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 33 seconds
(9/14) Running minio-java tests ... done in 17 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 23 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 63905,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 31 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 56 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
