### PR TITLE
Fix entries not cleared on resolve

### PR DESCRIPTION
**Pull request by klauspost**
## Description

This can cause old entries to be included (albeit unlikely) in resolution.

## How to test this PR?

Conflict resolution can cause an old entry to be most popular.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — CHANGES_REQUESTED** [review]
@klauspost is there a test case for this to test?

**Comment by klauspost** [comment]
@harshavardhana I can add some test cases for the rewrite. This is a clear mistake.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
> @harshavardhana I can add some test cases for the rewrite. This is a clear mistake.

No I am wondering when does it happen in what situation, so that we know this is affecting someone.

**Comment by klauspost** [comment]
@harshavardhana It very well could be happening and breaking when there are disk inconsistencies.

This is a high priority fix.

**Pull request merged**
