### PR TITLE
config: Remove level field in console/file loggers

### LINKED ISSUE #3927: config: deprecate logger log levels
- remove 'log-level' for loggers.
- rename `fileName` for file logger as `filename`.

migrate the config to version 16.

## Expected Behavior
Currently log-levels are kind of pretty much useless because we do not have any extensive logging. 

## Current Behavior
log-levels are supported and parsed which do not provide much value to the end user and ends up confusing them.

## Possible Solution
Fix `config.json` 

## Steps to Reproduce (for bugs)
Open `config.json`

## Context
Cleanup and simplification.

## Your Environment
Latest minio release and master branch.

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Also rename fileName field in file logger to filename

## Motivation and Context
Fixes https://github.com/minio/minio/issues/3927

## How Has This Been Tested?
go test + Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
@balamurugana need your reviews here..

**Comment by krishnasrinivas** [comment]
@vadmeste this has conflicts

**Comment by vadmeste** [comment]
> @vadmeste this has conflicts

Conflict resolved @krishnasrinivas

**Review by balamurugana — APPROVED** [review]

**Comment by harshavardhana** [comment]
@vadmeste can you resolve the conflict?

**Comment by vadmeste** [comment]
> @vadmeste can you resolve the conflict?

Done

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
