### PR TITLE
support CRC32 Checksums on single drive setup

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
support CRC32 Checksums on single drive setup

## Motivation and Context
fixes the mint test failures

## How to test this PR?
Mint tests already cover the scenarios

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#05bfa28e-57e2-4931-8ff7-a4b420352a41) |
<a name="05bfa28e-57e2-4931-8ff7-a4b420352a41"></a>
### 15873-82e6a3b/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.20:30739
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp f5b0d7aba9d5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... FAILED in 6 seconds
{
  "args": {
    "bucketName": "minio-go-test-99oavqbk3tz94m9e",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "5ssmfwa0ozauh2js1neddditnet0p9",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3090,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 31 seconds
(9/14) Running minio-js tests ... done in 35 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 11 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 3 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#d07da2fe-700b-4e93-aa48-41ee3cf19dce) |
| mint-pools.sh | :x: [more...](#f01bf7bf-7a00-4f50-b055-94f2d4d59be7) |
<a name="f01bf7bf-7a00-4f50-b055-94f2d4d59be7"></a>
### 15873-e3175d4/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:30833
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 68c64f118fb8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dsyxl4xeytxvuc",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 395,
  "error": "InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 171E1E8B65CEF100, host id: ",
  "function": "testListObjects",
  "message": "AWS SDK Go listobjects expected to success but got InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 171E1E8B65CEF100, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/14) Running aws-sdk-java tests ... done in 1 seconds
(2/14) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-634a2101f1fe8",
    "Object": "obj1"
  },
  "duration": "341",
  "status": "FAIL",
  "error": "Error executing \"ListObjects\" on \"http://15.15.15.3:30833/aws-sdk-php-634a2101f1fe8?encoding-type=url\"; AWS HTTP error: Server error: `GET http://15.15.15.3:30833/aws-sdk-php-634a2101f1fe8?encoding-type=url` resulted in a `500 Internal Server Error` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InternalError</Code><Message>We encountered an internal error, pleas (truncated...)\n InternalError (server): We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided) - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)</Message><BucketName>aws-sdk-php-634a2101f1fe8</BucketName><Resource>/aws-sdk-php-634a2101f1fe8</Resource><RequestId>171E1E8BF339D5D5</RequestId><HostId>ec95fb16-6e50-4919-a22b-a6e9749fd91e</HostId></Error>"
}
(2/14) Running aws-sdk-ruby tests ... done in 7 seconds
(3/14) Running awscli tests ... FAILED in 16 seconds
{
  "name": "awscli",
  "duration": 5086,
  "function": "aws --endpoint-url http://15.15.15.3:30833 s3api list-objects --bucket awscli-mint-test-bucket-29869 --prefix linux\n",
  "status": "FAIL",
  "error": ""
}
(3/14) Running healthcheck tests ... done in 0 seconds
(4/14) Running mc tests ... FAILED in 22 seconds
{
  "name": "mc",
  "duration": "10449",
  "function": "test_list_dir",
  "status": "FAIL",
  "error": "unexpected listing dir"
}
(4/14) Running minio-go tests ... FAILED in 14 seconds
{
  "args": {
    "bucketName": "minio-go-test-ikwwie3sg0ratshd",
    "region": "eu-west-1"
  },
  "duration": 4510,
  "error": "We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)",
  "function": "MakeBucket(bucketName, region)",
  "message": "CleanupBucket failed while removing bucket recursively",
  "name": "minio-go: testMakeBucketRegionsV2",
  "status": "FAIL"
}
(4/14) Running minio-java tests ... done in 38 seconds
(5/14) Running minio-js tests ... done in 51 seconds
(6/14) Running minio-py tests ... done in 2 minutes and 6 seconds
(7/14) Running s3cmd tests ... done in 17 seconds
(8/14) Running s3select tests ... done in 5 seconds
(9/14) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 9 out of 14 tests successfully.
```
<a name="d07da2fe-700b-4e93-aa48-41ee3cf19dce"></a>
### 15873-e3175d4/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.2:32365
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp b3ba5f8268c7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... FAILED in 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-klidkmcpmuokzpzg",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "tu3uu91j5b9rkpls9pkgjxr1l0gmrm",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3557,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 38 seconds
(9/14) Running minio-js tests ... done in 37 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 18 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 2 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#07d6ef16-cf3e-430b-bc50-a933ec9efc6d) |
<a name="07d6ef16-cf3e-430b-bc50-a933ec9efc6d"></a>
### 15873-44b0110/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:32150
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 0116fbaa072f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... FAILED in 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-ceufll0bjkwe069o",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "4xjxw61sxe9lfynlytln1b6lbrvzzt",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3564,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 38 seconds
(9/14) Running minio-js tests ... done in 38 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 18 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 6 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
