### PR TITLE
Change console address port from 9001 to 9090, to keep consistency

### PR DESCRIPTION
**Pull request by jingsam**
…th https://min.io/docs

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
The console address port in readme is 9001, in min.io/docs is 9090

## Motivation and Context
To keep consistency, use 9090

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [x] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — COMMENTED** [review]
Consistency with what?

**Comment by jingsam** [comment]
> Consistency with what?

Use the same console address port across the ReadMe and min.io/docs, to avoid confusion for new users.

**Comment by harshavardhana** [comment]
> Use the same console address port across the ReadMe and min.io/docs, to avoid confusion for new users.

I would prefer our official docs move to 9001 for the console port, consecutive ports are the normal.  The 9001 usage is normal than 9090, so we should fix it at github.com/minio/docs

Closing this PR.

**Comment by klauspost** [comment]
@ravindk89

**Comment by jingsam** [comment]
> > Use the same console address port across the ReadMe and min.io/docs, to avoid confusion for new users.
> 
> I would prefer our official docs move to 9001 for the console port, consecutive ports are the normal. The 9001 usage is normal than 9090, so we should fix it at github.com/minio/docs
> 
> Closing this PR.

Submitted a PR in https://github.com/minio/docs/pull/1081

**Comment by ravindk89** [comment]
@harshavardhana @klauspost if we are making this change should it not also be the same for Operator?

https://github.com/minio/operator/blob/38dc7e3878ffd95b150718e46d48798bfd7f9243/api/config.go#L90-L98

My understanding is the Console Service is `9090` by default.

TBH if we're talking about formalizing this, I would raise putting down the dynamic port allocation behavior entirely as an optional flag and binding to 9001 by default.

**Comment by harshavardhana** [comment]
> My understanding is the Console Service is `9090` by default.

No, there is no such thing as default port 9090 @ravindk89 for Console - console for testing purposes chose 9090, but that is not default. It doesn't have any defaults to begin with it has to be manually provided each time, depending on the deployment. 

However as practice, we should only document consecutive ports for simplicity, we shouldn't come up with new ports like 9090.

**Comment by harshavardhana** [comment]
> https://github.com/minio/operator/blob/38dc7e3878ffd95b150718e46d48798bfd7f9243/api/config.go#L90-L98

That is the Operator UI port, which has nothing to do with the MinIO Console port.

**Comment by ravindk89** [comment]
Gotcha - we'll update the docs then. That said I believe at least the Operator Tenant helm chart sets 9090 for the non-TLS access to the Console port. It's 9443 otherwise, which bypasses this entire conversation nicely :)

**Comment by lam-guo** [comment]
please check [minio-dev.yaml](https://raw.githubusercontent.com/minio/docs/master/source/extra/examples/minio-dev.yaml) of still using port 9090.
And [doc-line117](https://github.com/minio/docs/blob/main/source/includes/k8s/quickstart.rst?plain=1#L117)
[doc-line119](https://github.com/minio/docs/blob/main/source/includes/k8s/quickstart.rst?plain=1#L119)

**Comment by ravindk89** [comment]
@lam-guo please open a ticket in github.com/minio/docs , as we cannot meaningfully track bugs reported on tickets closed months ago.

**Pull request closed without merging**
