### PR TITLE
include ip address while doing checkPortAvailability

### LINKED ISSUE #7685: checkPortAvailability ignores host/ip given with --address
The code in checkPortAvailability does not take into account the given address, leading to false positives while checking for availability.

## Expected Behavior
If I have a local process using port 9000 on IP 10.0.0.1 and start minio with port 9000 with `--address=10.0.0.2:9000`, minio should start just fine.
## Current Behavior
Due to the implementation of the port availability test, minio complains about the port being already in use.

## Possible Solution
checkPortAvailability should not only accept the port but hostAddr and should only check for availability on the given host/IP.

## Reproduce
Add two dedicated IP addresses:
```
ip a a 10.0.0.1/24 dev eth0
ip a a 10.0.0.2/24 dev eth0
```
Open two shells/tmux whatever and in one do
```
minio server --address=10.0.0.1:9000 /tmp/test1
```
and in the other
```
minio server --address=10.0.0.2:9000 /tmp/test2
```
leading to
```
ERROR Unable to start the server: Port :9000 is already in use.
```

## Context
This would be useful when multiple minio instances should run on a single host, all using the default http/https port or alongside othe http/https services.

## Your Environment
Ubuntu Linux 18.04
```
$ minio version
Version: 2019-05-23T00:29:34Z
Release-Tag: RELEASE.2019-05-23T00-29-34Z
Commit-ID: e252114f067b07e6c22b91f46a6fa9815450e7a8
```

### PR DESCRIPTION
**Pull request by kanagarajkm**
## Description

While checking for port availability, ip address should be included.
When a machine has multiple ip addresses, multiple minio instances
or some other applications can be run on the same port but different
ip address.

Fixes #7685

## Motivation and Context

When multiple minio instances needs to be run on a single host which has multiple ip addresses,
they can use same port but different ip addresses.

## Regression

No

## How Has This Been Tested?

1. Run minio on a particular ip:port (`./minio server ~/tmp/d1 --address localhost:9000`)
2. Run another minio instance on differnt ip same port (`./minio server ~/tmp/d2 --address 192.168.86.145:9000`)
3. Make both are accessible and working fine on their respective ip:port
4. Run minio on a particular port but all ip (`./minio server ~/tmp/d1 --address :9000`)
5. Run minio on a particular port but all ip (`./minio server ~/tmp/d2 --address :9000`)
6. The last one should fail
7. Run minio default (`./minio server ~/tmp/d1`)
8. Run another minio instance on a particular ip and same port (`./minio server ~/tmp/d2 --address 192.168.86.145:9000`)
9. The last one should fail

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [x] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#470359dc-2a7f-42af-813d-46db681dda81) |
| mint-large-bucket.sh | :x: [more...](#cac6be7f-bed5-4507-b6fa-494903fa6131) |
| mint-dist-xl.sh | :x: [more...](#bd3c4274-7a90-4b2c-b0b5-5c932d60dcd0) |
| mint-gateway-nas.sh | :x: [more...](#56502be7-665c-4d48-8cd2-11f3d34b8de4) |
<a name="56502be7-665c-4d48-8cd2-11f3d34b8de4"></a>
### 7818-899dbe0/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31602
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4604261a374a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-n5g4h9ebd5s5gb",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3060,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31602/aws-sdk-go-test-n5g4h9ebd5s5gb: dial tcp 72.28.97.57:31602: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="cac6be7f-bed5-4507-b6fa-494903fa6131"></a>
### 7818-899dbe0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31057
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9a386f68414d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 23 seconds
{
  "name": "mc",
  "duration": "109788",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-24994 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-5976  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-5976/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-5976/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-5976/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-5976/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-5976/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-5976/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-5976/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-5976/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-5976/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-5976/datafile-129-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-5976/datafile-100-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-5976/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-5976/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-5976/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-5976/datafile-5243880-b`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 530.80 MiB, Speed: 4.84 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="470359dc-2a7f-42af-813d-46db681dda81"></a>
### 7818-899dbe0/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31444
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5aeb1c24532b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-au4f94isi9023l",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360012,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15AA2C6D5AA61FF4, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="bd3c4274-7a90-4b2c-b0b5-5c932d60dcd0"></a>
### 7818-899dbe0/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32162
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58ceb9c19577:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 56 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 38 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 12 seconds
(10/14) Running minio-java tests ... FAILED in 48 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 437,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3d7putd, objectName=minio-java-test-63h5gk, resource=/minio-java-test-3d7putd/minio-java-test-63h5gk, requestId=15AA2C5F2A28FC19, hostId=86d64092-d240-496a-a3f8-e1ecf9cb0737)\nrequest={method=DELETE, url=http://72.28.97.59:32162/minio-java-test-3d7putd/minio-java-test-63h5gk?uploadId=c313a6d2-e581-4980-8887-f5cd97db78a1, headers=Host: 72.28.97.59:32162\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190621T092328Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190621/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-21T09-05-31Z\nVary: Origin\nX-Amz-Request-Id: 15AA2C5F2A28FC19\nX-Minio-Deployment-Id: 86d64092-d240-496a-a3f8-e1ecf9cb0737\nX-Xss-Protection: 1; mode=block\nDate: Fri, 21 Jun 2019 09:23:28 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Review by poornas — APPROVED** [review]
LGTM

**Comment by kannappanr** [comment]
ping @vadmeste

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Pull request merged**
