### PR TITLE
Fix possible race in shutdown callbacks process and simplify shutting down profiler

### LINKED ISSUE #2673: Data race when server stopped with Ctrl + C.
## Expected behaviour

No race when server is shutdown.
## Actual behaviour

```
WARNING: DATA RACE
Read by goroutine 61:
  github.com/minio/minio/cmd.startMonitorShutdownSignal.func1()
      /home/minio/gopath/src/github.com/minio/minio/cmd/utils.go:206 +0x2fb

Previous write by main goroutine:
  [failed to restore the stack]

Goroutine 61 (running) created at:
  github.com/minio/minio/cmd.startMonitorShutdownSignal()
      /home/minio/gopath/src/github.com/minio/minio/cmd/utils.go:260 +0x8b
  github.com/minio/minio/cmd.initGracefulShutdown()
      /home/minio/gopath/src/github.com/minio/minio/cmd/utils.go:149 +0x161
  github.com/minio/minio/cmd.configureServerHandler()
      /home/minio/gopath/src/github.com/minio/minio/cmd/routers.go:78 +0x466
  github.com/minio/minio/cmd.serverMain()
      /home/minio/gopath/src/github.com/minio/minio/cmd/server-main.go:252 +0x424
  github.com/minio/minio/vendor/github.com/minio/cli.Command.Run()
      /home/minio/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:117 +0x1fc3
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run()
      /home/minio/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:186 +0x62e
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).RunAndExitOnError()
      /home/minio/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:197 +0x66
  github.com/minio/minio/cmd.Main()
      /home/minio/gopath/src/github.com/minio/minio/cmd/main.go:185 +0x101
  main.main()
      /home/minio/gopath/src/github.com/minio/minio/main.go:22 +0x25
==================
Found 1 data race(s)
```
## Steps to reproduce the behaviour
- Build the binary with race detection enabled
- Start the server. 
- Shutdown the server with Ctrl + C .
  ## Minio version
- (paste output of `minio version`)
  Latest master at 85e2d886bcb005d49f3876d6849a2b5a55e03cd3 . 
  ## System information
  Minio 2 server.

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #2673

### CODE REVIEW

**Comment by harshavardhana** [comment]
@hackintoshrao can you validate this?

**Comment by hackintoshrao** [comment]
Sure.

**Comment by hackintoshrao** [comment]
@harshavardhana : Issue is fixed, not able to reproduce with code from this branch.

**Comment by harshavardhana** [comment]
> @harshavardhana : Issue is fixed, not able to reproduce with code from this branch.

Thanks @hackintoshrao

**Pull request merged**
