### PR TITLE
Ensure that sig/sha are in the same layer

### LINKED ISSUE #2229: error syncing 'minio/...': Tar file extraction failed for file index: 2, with: EOF when updating minio
This is a follow-up to https://github.com/minio/minio/issues/19510.

While the issue of rolling upgrade partially breaking minio has been solved in minio by properly waiting for all nodes to have a consistent version, actual root cause still seems to exist even with the new operator 6.0.0.

## Expected Behavior

1. operator downloads the new minio binary
2. operator replaces the binary in all minio pods
3. operator simultaneously restarts all minio processes
4. operator triggers a rolling restart of the StatefulSet

## Current Behavior

What seems to be happening according to the discussion with @harshavardhana:

1. operator downloads the new minio binary, but fails to unpack the tar archive.
2. ~~operator replaces the binary in all minio pods~~ skipped
3. ~~operator simultaneously restarts all minio processes~~ skipped
4. operator triggers a rolling restart of the StatefulSet

## Possible Solution

no idea

## Steps to Reproduce (for bugs)

1. Setup k0s
5. Setup operator
6. Setup an any-sized minio cluster via operator
7. Change the minio version of the tenant

## Context

I have two affected setups:

1. k0s 1.30, single node (k8s + minio), archlinux, containerd/runc
2. k0s 1.29, 5 nodes (k8s + minio), debian bookworm, containerd/runc

This issue has been around for a while (part of it can be seen in the issue reference at the top and the issues that are referenced by that) across a bunch of k8s/k0s, minio and operator 5.x versions.

My setup is a single node k0s

## Your Environment

* Version used (`minio-operator`): 6.0.0
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes 1.30.1
* Server type and version:
* Operating System and version (`uname -a`): `Linux server 6.9.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 18 Jul 2024 18:06:13 +0000 x86_64 GNU/Linux`
* Link to your deployment file:

### PR DESCRIPTION
**Pull request by ramondeklein**
Fixes https://github.com/minio/operator/issues/2229.

### CODE REVIEW

**Comment by ramondeklein** [comment]
@harshavardhana I can't run `docker build -f Dockerfile.release .`, because of a minisign issue. Guess I'm missing some kind of key. So hard for me to test...

**Comment by harshavardhana** [comment]
> @harshavardhana I can't run `docker build -f Dockerfile.release .`, because of a minisign issue. Guess I'm missing some kind of key. So hard for me to test...

you can't just run `docker build -f Dockerfile.release` you need to pass `--build-arg` value check `docker-buildx.sh` what it does.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
I will republish the container of the latest release.

**Comment by harshavardhana** [comment]
@ramondeklein for next time create branches on your fork, and let's avoid creating `origin/<branch>` - just to avoid mistakes in future.

**Pull request merged**
