### PR TITLE
fix: potential data conflicts save site-resync metadata

### PR DESCRIPTION
**Pull request by jiuker**
## Description

Here I think we need to finish one batch of saves before we can move on to the next batch of saves.
Close this if on purpose.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by poornas — APPROVED** [review]

**Comment by harshavardhana** [comment]
If you have lets say 200 peers this will cause 200 parallel writes? @poornas

**Comment by poornas** [comment]
> If you have lets say 200 peers this will cause 200 parallel writes? @poornas

resync runs on only one node in the cluster

**Comment by harshavardhana** [comment]
> resync runs on only one node in the cluster

Isn't this invoking X callers without a top-level limit? - this PR doesn't look scalable to me. Calling wg.Add(1) for each peer with 300+ servers is going to be trouble for us in the long run.

**Comment by poornas** [comment]
> > resync runs on only one node in the cluster
> 
> Isn't this invoking X callers without a top-level limit? - this PR doesn't look scalable to me. Calling wg.Add(1) for each peer with 300+ servers is going to be trouble for us in the long run. 

Not sure about the concern here - there is only one site resync going on any time per site replication peer, so at the max there are as n-1 resyncs going on where n is number of sites. A leader lock is taken so only one node in the cluster is running site resync

**Comment by harshavardhana** [comment]
So the peersyncmap is actually just the replication peers not MinIO peers?

**Comment by poornas** [comment]
> So the peersyncmap is actually just the replication peers not MinIO peers?

That's right

**Comment by jiuker** [comment]
@harshavardhana What this pr is trying to convey is that if once the previous batch is not completed, because there is no limit, the next batch starts again. If the task of the latter batch writes data before the previous batch succeeds, which overwrites the data, the probability is small, but it has to be considered. If this probability is so small that you think it will not occur, turn off this pr.

**Comment by harshavardhana** [comment]
> @harshavardhana What this pr is trying to convey is that if once the previous batch is not completed, because there is no limit, the next batch starts again. If the task of the latter batch writes data before the previous batch succeeds, which overwrites the data, the probability is small, but it has to be considered. If this probability is so small that you think it will not occur, turn off this pr.

I understand that part, the issue was I wanted to know how many peers will be present in syncMap() - we really cannot afford an additional 100's goroutines because having more goroutines that are actively doing disk I/O - causes some amount of CPU to build up.

But it looks like the peerSyncMap is always quite small since this is for replication.

**Pull request merged**
