### PR TITLE
removed max length check for accesskey and secret key for svc-account

### LINKED ISSUE #15164: Service Account - accessKey Max Length issue
While minio does not check fox max length for access keys of regular users, it still checks the max length for accesskeys for new service accounts. Perhaps this is a oversight. There is no reason why access keys for service account should be restricts to maximum 20 characters.

## Expected Behavior

User should be able to create service account with accessKey longer than 20 characters.

## Current Behavior

User gets error below error when accesskey longer than 20 characters is specified.
```
mc: <ERROR> Unable to add a new service account. The access key is invalid. (access key length should be between 3 and 20)
```

## Possible Solution

[This code block](https://github.com/minio/minio/blob/master/internal/auth/credentials.go#L243-L245) should stop checking for max length. This code block is invoked as part of new svc account creation [here](https://github.com/minio/minio/blob/master/cmd/iam.go#L935)

## Steps to Reproduce (for bugs)

1. Provide access key of 21 characters to get the error.
`mc admin user svcacct add --debug --access-key "e12345678901234567890" --secret-key "testsecret2" minio <existing user>`
2. Provide access key of 20 characters to get svc account created successfully.
`mc admin user svcacct add --debug --access-key "e1234567890123456789" --secret-key "testsecret2" minio <existing user>`

## Your Environment

* Version used (`minio --version`): RELEASE.2022-03-03T21-21-16Z
* Server setup and configuration: Kubernetes based minio-ha operator
* Operating System and version (`uname -a`): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by dharapvj**
## Description
Fixes #15164

## How to test this PR?
Below command should work fine and create two svc accounts with specified accesskeys
```
mc admin user svcacct add --debug --access-key "e12345678901234567890" --secret-key "testsecret2" minio <existing user>
mc admin user svcacct add --debug --access-key "e123456789012345678901234567890123456789012345678901234567890" --secret-key "testsecret2" minio <existing user>

```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by harshavardhana** [comment]
@dharapvj - thanks for the PR - however this is on purpose. We cannot break this right now. It is kept to be compatible with AWS S3. 

The lengths of these values are part of the AWS Signature v4 calculation, these lengths are part of a protocol that we do not wish to lightly change without deeper understanding.

Any signature mechanism might in subtle break if certain lengths change, it is not like `username:  and password:` equivalent in  Basic Auth or Oauth

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0b936484-9f61-461f-b998-6728012b4a8f) |
<a name="0b936484-9f61-461f-b998-6728012b4a8f"></a>
### 15165-fb6d5fb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:32145
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 27 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 18 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 28 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 0 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 54081,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-cn60da, objectName = null, resource = /minio-java-test-cn60da, requestId = 16FB7BAB5027FFEB, hostId = 1bbc486b-b06b-4315-a287-80637d4cbe0c)\nrequest={method=DELETE, url=http://minio-k8s5:32145/minio-java-test-cn60da, headers=Host: minio-k8s5:32145\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.2\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20220624T064743Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20220624/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 326\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Request-Id: 16FB7BAB5027FFEB\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Fri, 24 Jun 2022 06:47:43 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(10/15) Running minio-js tests ... done in 1 minutes and 4 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 21 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by dharapvj** [comment]
@harshavardhana - Could you help me with document which specifies the limit? I looked at [this doc](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html) as well as we [this doc](https://docs.aws.amazon.com/STS/latest/APIReference/API_Credentials.html) from AWS.

They both are not talking about fixing the accessKey to 20 characters..

**Comment by dharapvj** [comment]
One more [reference documentation from AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html) - says max limit is 128 character

**Comment by harshavardhana** [comment]
> One more [reference documentation from AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html) - says max limit is 128 character

That is for AWS login not access key and secret key

**Comment by harshavardhana** [comment]
@dharapvj also currently the decision holds we are not planning to change this. We will do it when the time is right.

**Pull request closed without merging**
