### PR TITLE
Skip non-bucket dns entry in federated bucket list

### PR DESCRIPTION
**Pull request by donatello**
## Motivation and Context

In a federated setup, if there exists a DNS entry for the minio server in etcd, we need to skip it - otherwise a bucket with an empty name is returned in list buckets.

## Regression

No

## How Has This Been Tested?

Did not test yet.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) - for a special setup.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by nitisht — APPROVED** [review]

**Comment by adiospeds** [comment]
Thanks @donatello.. this was a crucial change to get minio working in our qa environment.

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by adiospeds** [comment]
I tested this today ..but the fix did not work .. my servername/domainname looks something like netops.prod.s3.xyz.com .. and a blank bucket is visible in the gui if I add an entry for it in etcd ... I think the code should look for a value in the etcd and if the value is something like "donotlist" or "iamadomain" something like that .. it shud get skipped from being listed in the gui and in the list buckets query

**Comment by harshavardhana** [comment]
> I tested this today ..but the fix did not work .. my servername/domainname looks something like netops.prod.s3.xyz.com .. and a blank bucket is visible in the gui if I add an entry for it in etcd ...

@adiospeds please re-open a new issue with the exact steps to reproduce the issue. Are you trying to manually modify the backend etcd entries?

**Comment by adiospeds** [comment]
Hi @harshavardhana .. yes I have added an extra entry inside the etcd backend - more details in this newly created issue: https://github.com/minio/minio/issues/7697

**Pull request merged**
