### PR TITLE
use rename() safety for in-place 'xl.meta' updates

### PR DESCRIPTION
**Pull request by poornas**
in the namespace

This makes it safer when replication metadata updates and listing occurs in parallel as listing does not take a lock.

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Motivation and Context
Avoid listing missing entries when concurrent replication activity is updating metadata

## How to test this PR?
- adapt this docker-compose https://github.com/minio/openlake/tree/main/spark/partition-test to set up site replication b/w 2 minio nodes 
-  exclude tmp prefixes from versioning -  --excluded-prefixes "*/_temporary/,*/.hive-staging,*/_staging for the bucket
- mark a site offline
- then run the spark notebook with repeated drop, create, insert table sequence
At some point , insert should fail with master branch with location already exists error.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
This also resolves https://github.com/minio/minio/issues/17416

**Review by klauspost — COMMENTED** [review]
Benchmarks to evaluate the impact would be great. Maybe a "mixed" benchmark with 1K objects.

**Comment by harshavardhana** [comment]
> Benchmarks to evaluate the impact would be great. Maybe a "mixed" benchmark with 1K objects.

Lets get this merged and give this to customer - we can do benchmarks in the meantime.

**Review by vadmeste — APPROVED** [review]

**Comment by harshavardhana** [comment]
There is hardly any performance difference in reality.

latest release v/s master 
```
19960431 operations loaded... Done!
20341861 operations loaded... Done!
-------------------
Operation: DELETE
Operations: 1996015 -> 2034168
* Average: +1.91% (+127.2) obj/s
* Requests: Avg: -350µs (-2%), P50: -351.413µs (-3%), P99: -639.109µs (-2%), Best: -37ns (-0%), Worst: +108.631567ms (+23%) StdDev: +225.279µs (+3%)
-------------------
Operation: GET
Operations: 8982226 -> 9153840
* Average: +1.91% (+71.5 MiB/s) throughput, +1.91% (+572.1) obj/s
* Requests: Avg: -150µs (-2%), P50: -102.686µs (-2%), P99: -317.551µs (-2%), Best: -18.784µs (-2%), Worst: +109.55021ms (+24%) StdDev: +26.449µs (+1%)
* TTFB: Avg: -100µs (-2%), P50: -102.191µs (-2%), P99: -315.183µs (-2%), Best: -10.952µs (-1%), Worst: +109.566309ms (+24%) StdDev: +26.123µs (+1%)
-------------------
Operation: PUT
Operations: 2994041 -> 3051288
* Average: +1.91% (+23.9 MiB/s) throughput, +1.91% (+190.8) obj/s
* Requests: Avg: -300µs (-2%), P50: -265.874µs (-2%), P99: -546.942µs (-2%), Best: +52.372µs (+2%), Worst: +102.123108ms (+22%) StdDev: +258.952µs (+4%)
-------------------
Operation: STAT
Operations: 5988149 -> 6102565
* Average: +1.91% (+381.4) obj/s
* Requests: Avg: -150µs (-2%), P50: -136.946µs (-2%), P99: -293.87µs (-1%), Best: -18.962µs (-3%), Worst: +110.902727ms (+24%) StdDev: +137.019µs (+3%)
```

< 5% differences are not helpful in reality for API calls.

**Comment by harshavardhana** [comment]
```
┌──────┬───────────────────────┬─────────────────────┬──────────────┐
│ Pool │ Drives Usage          │ Erasure stripe size │ Erasure sets │
│ 1st  │ 2.2% (total: 210 TiB) │ 8                   │ 6            │
└──────┴───────────────────────┴─────────────────────┴──────────────┘

48 drives online, 0 drives offline, EC:3
```

**Pull request merged**
