### PR TITLE
call Close on error to release the read lock

### PR DESCRIPTION
**Pull request by yaozongyou**
## Description
call `Close` on error to release the read lock

## Motivation and Context

considering the following requests:

```bash
POST /testbucket/hello.csv?select=&select-type=2 HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: aws-sdk-go/1.19.15 (go1.12.4; linux; amd64)
Content-Length: 490
Authorization: AWS4-HMAC-SHA256 Credential=MBX21LJAWC8A7ZF2LISL/20190625/us-east-1/s3/aws4_request, SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date, Signature=6cc29ed53063ef1705e92e927304d72b3085b8cf1d7697a558ff81d07ea454ac
X-Amz-Content-Sha256: 53ec9c7ace817289ba6ef4eb2f4f3d0da5ac0110eebd0f7ef2c88adc0c0b513f
X-Amz-Date: 20190625T095041Z
Accept-Encoding: gzip

<SelectObjectContentRequest xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Expression>Select s._1 from S3Object s limit 1</Expression><ExpressionType>SQL</ExpressionType><InputSerialization><CSV><FileHeaderInfo>IGNORE</FileHeaderInfo><RecordDelimiter>
</RecordDelimiter><FieldDelimiter>,</FieldDelimiter></CSV><CompressionType>GZIP</CompressionType></InputSerialization><OutputSerialization><CSV><QuoteFields>ASNEEDED</QuoteFields></CSV></OutputSerialization></SelectObjectContentRequest>HTTP/1.1 400 Bad Request
Accept-Ranges: bytes
Content-Length: 405
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/DEVELOPMENT.2019-06-25T09-50-02Z
Vary: Origin
X-Amz-Request-Id: 15AB682DC2B58B16
X-Minio-Deployment-Id: bdbdb029-e811-4d0b-87b7-648bbc9ee156
X-Xss-Protection: 1; mode=block
Date: Tue, 25 Jun 2019 09:50:41 GMT

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>TruncatedInput</Code><Message>Object decompression failed. Check that the object is properly compressed using the format specified in the request.</Message><Key>hello.csv</Key><BucketName>testbucket</BucketName><Resource>/testbucket/hello.csv</Resource><RequestId>15AB682DC2B58B16</RequestId><HostId>bdbdb029-e811-4d0b-87b7-648bbc9ee156</HostId></Error>
DELETE /testbucket/hello.csv HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: aws-sdk-go/1.19.15 (go1.12.4; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=MBX21LJAWC8A7ZF2LISL/20190625/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7456949e9e67a7bc2a337ff5d50eabdbf49a388e2e4fd8b8375e0d091f295d03
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190625T095041Z
Accept-Encoding: gzip
```
the `DELETE` request is stucked because of the read lock is not released.

## Regression

No

## How Has This Been Tested?

Yes: resent the above requests and the DELETE request can be successfully completed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3d30f50c-de7e-4ab3-886b-c30b4b9b63e6) |
| mint-compression-dist-xl.sh | :x: [more...](#a8605be9-bd22-44fc-bfe6-ef2e0ee7b375) |
| mint-dist-xl.sh | :x: [more...](#44dc5054-b172-4985-940f-73db1babd37d) |
<a name="a8605be9-bd22-44fc-bfe6-ef2e0ee7b375"></a>
### 7830-5253ad9/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32140
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ee326da6080a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-l9diqasqydc1mc",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3048,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32140/aws-sdk-go-test-l9diqasqydc1mc: dial tcp 72.28.97.57:32140: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="3d30f50c-de7e-4ab3-886b-c30b4b9b63e6"></a>
### 7830-5253ad9/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32017
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7f9ef7b1d0c7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-xby2tpg6gr2uhd",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3066,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32017/aws-sdk-go-test-xby2tpg6gr2uhd: dial tcp 72.28.97.57:32017: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="44dc5054-b172-4985-940f-73db1babd37d"></a>
### 7830-5253ad9/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31671
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fe526500ad81:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 54 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 41 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 50 seconds
(10/14) Running minio-java tests ... FAILED in 41 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 691,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1mmierb, objectName=minio-java-test-3r2ss1c, resource=/minio-java-test-1mmierb/minio-java-test-3r2ss1c, requestId=15AB6F77405B8995, hostId=a85dc36d-c1d7-4bf1-b742-2ce8ae0ec030)\nrequest={method=DELETE, url=http://72.28.97.56:31671/minio-java-test-1mmierb/minio-java-test-3r2ss1c?uploadId=966d3ddc-a190-4cc7-915e-125894aefc5f, headers=Host: 72.28.97.56:31671\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190625T120413Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190625/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-25T11-45-43Z\nVary: Origin\nX-Amz-Request-Id: 15AB6F77405B8995\nX-Minio-Deployment-Id: a85dc36d-c1d7-4bf1-b742-2ce8ae0ec030\nX-Xss-Protection: 1; mode=block\nDate: Tue, 25 Jun 2019 12:04:14 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#dc839657-97be-4d3c-b8f6-d4e704db46a0) |
| mint-fs.sh | :x: [more...](#0e31f4bc-f012-4220-887a-15c0b2933d49) |
| mint-dist-xl.sh | :x: [more...](#ca45a76f-7f26-4298-a8bd-582c9edafa8e) |
<a name="ca45a76f-7f26-4298-a8bd-582c9edafa8e"></a>
### 7830-3551d9a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32062
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 708e1e211088:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 0 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 42 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 54 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 6 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName)",
  "duration": 161,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.53:32062/minio-java-test-qgcp0d/minio-java-test-18nkut8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190625%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190625T122735Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=77d60033da152674aed33da7d0da4157a893e81b55984d5252def9136c598f10}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-18nkut8</Key><BucketName>minio-java-test-qgcp0d</BucketName><Resource>/minio-java-test-qgcp0d/minio-java-test-18nkut8</Resource><RequestId>15AB70BDB1C1F998</RequestId><HostId>48895513-f895-436c-ad25-f575c7f0ef6c</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test1(FunctionalTest.java:1767), FunctionalTest.runTests(FunctionalTest.java:2994), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="0e31f4bc-f012-4220-887a-15c0b2933d49"></a>
### 7830-3551d9a/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32487
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b2d71fbe02c2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wqjvw16kkksi9c",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3062,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32487/aws-sdk-go-test-wqjvw16kkksi9c: dial tcp 72.28.97.57:32487: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="dc839657-97be-4d3c-b8f6-d4e704db46a0"></a>
### 7830-3551d9a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32388
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1f5ed085cd98:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 53 seconds
{
  "name": "mc",
  "duration": "144073",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-23993 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-22065  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-22065/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-22065/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-22065/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-22065/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-22065/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-22065/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-22065/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-22065/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-22065/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-22065/datafile-5-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-22065/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-22065/datafile-5243880-b`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-22065/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-22065/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-22065/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 625.05 MiB, Speed: 4.34 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
{"name": "7830-3551d9a", "full_size": 63690551, "images": [{"size": 63690551, "architecture": "amd64", "variant": null, "features": null, "os": "linux", "os_version": null, "os_features": null}], "id": 60023142, "repository": 757613, "creator": 21164, "last_updater": 21164, "last_updated": "2019-06-25T12:09:26.438888Z", "image_id": null, "v2": true}

**Review by donatello — APPROVED** [review]
Thanks for the fix! Tested and verified.

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
