### PR TITLE
Start using custom HTTP transport for webhook endpoints

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Start using custom HTTP transport for webhook endpoints

## Motivation and Context
Use a more performant HTTP transport for webhook
endpoints with proper connection pooling, appropriate
timeouts etc.

## How to test this PR?
Specifically, look for cases mentioned in #8435 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d8ad2a95-bd1b-4005-ad96-1451f580c27c) |
| mint-compression-dist-xl.sh | :x: [more...](#0bd928a1-9acb-412a-9452-d7e3cdecb07b) |
<a name="d8ad2a95-bd1b-4005-ad96-1451f580c27c"></a>
### 8630-ea2a826/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32020
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 25de8b8f3f37:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 17 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 6 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 4 seconds
{
  "args": {},
  "duration": 47282,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="0bd928a1-9acb-412a-9452-d7e3cdecb07b"></a>
### 8630-ea2a826/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30425
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0b0d850bc4ee:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 54 seconds
(8/14) Running minio-dotnet tests ... done in 50 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 9 seconds
(10/14) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, String filename, String contentType)",
  "args": "contentType: application/javascript",
  "duration": 78,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-prnfli, objectName=minio-java-test-gcen45, resource=/minio-java-test-prnfli/minio-java-test-gcen45, requestId=15DF38F05C5F481E, hostId=34fb084d-5c25-41da-9ee5-81517cff6f8f)\nrequest={method=PUT, url=http://72.28.97.61:30425/minio-java-test-prnfli/minio-java-test-gcen45, headers=Content-Type: application/javascript\nHost: 72.28.97.61:30425\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: 4e04180acc6293d7bca0c42a7e92f6f1b85ba9e67b39e7e643ad67c4d031e671\nx-amz-date: 20191211T050959Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191211/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 359\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-11T04-44-41Z\nVary: Origin\nX-Amz-Request-Id: 15DF38F05C5F481E\nX-Xss-Protection: 1; mode=block\nDate: Wed, 11 Dec 2019 05:09:59 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:3879), FunctionalTest.putObject_test3(FunctionalTest.java:464), FunctionalTest.runTests(FunctionalTest.java:2986), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
Error: No such image: minio/minio:8630-ea2a826

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6399e99c-6d3a-4828-ab1e-9b0cbc89dfad) |
| mint-compression-dist-xl.sh | :x: [more...](#a4df2de7-bdbd-4329-81e4-7dff3ba7ae73) |
<a name="a4df2de7-bdbd-4329-81e4-7dff3ba7ae73"></a>
### 8630-5832d8f/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30529
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6849ec92a3c4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 53 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 31 seconds
(10/14) Running minio-java tests ... FAILED in 21 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 14187,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-37g7c9, objectName=minio-java-test-ea5ocr, resource=/minio-java-test-37g7c9/minio-java-test-ea5ocr, requestId=15DF6C7EED2786D9, hostId=e41b3420-2a96-4da1-be0c-4ef43de0f976)\nrequest={method=PUT, url=http://72.28.97.54:30529/minio-java-test-37g7c9/minio-java-test-ea5ocr, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.54:30529\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191211T205447Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191211/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 359\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-11T20-29-42Z\nVary: Origin\nX-Amz-Request-Id: 15DF6C7EED2786D9\nX-Xss-Protection: 1; mode=block\nDate: Wed, 11 Dec 2019 20:54:47 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="6399e99c-6d3a-4828-ab1e-9b0cbc89dfad"></a>
### 8630-5832d8f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30179
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 12c89dbcc079:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 30 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 20 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 41 seconds
{
  "args": {},
  "duration": 82793,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8630-5832d8f

**Review by Praveenrajmani — APPROVED** [review]
Tested and LGTM

**Review by kanagarajkm — APPROVED** [review]
Verified

**Pull request merged**
