### PR TITLE
fix: pass proper username (simple) string as expected

### LINKED ISSUE #16552: Unable to access files when using ldap:username policy substitution
I'm attempting to setup home directory access for LDAP-authenticated users as described in the [MinIO Multi-user Quickstart Guide](https://github.com/minio/minio/blob/master/docs/multi-user/README.md). In my environment, I'd like to have a bucket named `user-data` with subdirectories containing LDAP usernames with access scoped to the corresponding LDAP user, e.g.,

```
└── user-data
        └──  example.username
```

I've defined the following policy file to enable this scenario:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::user-data"
      ]
    },
    {
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::user-data"
      ],
      "Condition": {
        "StringLike": {
          "s3:prefix": [
            "${ldap:username}/*"
          ]
        }
      }
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::user-data/${ldap:username}/*"
      ]
    }
  ]
}
```

## Expected Behavior

LDAP-authenticated users should be able view the contents of their home directory as well as create and delete files.

## Current Behavior

Contents of the home directory can be viewed but access to upload or delete files is denied.

## Possible Solution

A static policy file defined on a per-user basis could be used to workaround the issue.

## Steps to Reproduce (for bugs)

The following steps can be used to reproduce the issue:

1. Start a local MinIO instance using `docker-compose`:

```
cat docker-compose.yaml << EOF
version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2023-01-31T02-24-19Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secretkey
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
volumes:
  minio-data:
EOF
```

```
docker-compose up -d
```

2. Define an alias for the MinIO instance:

```
mc alias set localdev-admin http://localhost:9000 admin secretkey
```

3. Enable the LDAP identity provider:

```
mc admin config set localdev-admin identity_ldap \
    server_addr="*****" \
    lookup_bind_dn="*****" \
    lookup_bind_password="*****" \
    user_dn_search_base_dn="*****" \
    user_dn_search_filter="*****" \
    group_search_filter="*****" \
    group_search_base_dn="*****"
```

```
mc admin service restart localdev-admin
```

4. Create the `user-data` bucket and copy a file into it.

```
mc mb localdev-admin/user-data
```

```
touch test.txt
mc cp test.txt localdev-admin/user-data/example.username/test.txt
```

5. Add the home directory policy using LDAP username policy substitution:

```
cat user-data-readwrite.json << EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::user-data"
      ]
    },
    {
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::user-data"
      ],
      "Condition": {
        "StringLike": {
          "s3:prefix": [
            "${ldap:username}/*"
          ]
        }
      }
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::user-data/${ldap:username}/*"
      ]
    }
  ]
}
EOF
```

```
mc admin policy add localdev-admin user-data-readwrite user-data-readwrite.json
```

6. Assign the home directory policy to an LDAP user:

```
mc admin policy set localdev-admin user-data-readwrite user='CN=Example Username,OU=Users,DC=company,DC=com'
```

7. Log in to the web console as the LDAP user and create a service account with credentials `user:secretkey`.

8. Define an alias for the MinIO instance using the LDAP user's service account:

```
mc alias set localdev-user http://localhost:9000 user secretkey
```

9. Observe that the home directory contents can be listed:

```
mc ls localdev-user/user-data
```

10. Attempt to copy the file created in step 4:

```
mc cp --debug localdev-user/user-data/example.username/test.txt /tmp/test.txt
```

The following output is produced:

```
mc: <DEBUG> GET /user-data/?location= HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v7.0.46 mc/RELEASE.2023-01-28T20-29-38Z
Authorization: AWS4-HMAC-SHA256 Credential=user/20230206/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230206T192300Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 270
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 06 Feb 2023 19:23:00 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Request-Id: 1741529F5FE77EF4
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>user-data</BucketName><Resource>/user-data/</Resource><RequestId>1741529F5FE77EF4</RequestId><HostId>ace2bdb5-ed3b-4da0-a485-a02021c57f8c</HostId></Error>mc: <DEBUG> Response Time:  4.496965ms

mc: <DEBUG> HEAD /user-data/example.username/test.txt HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v7.0.46 mc/RELEASE.2023-01-28T20-29-38Z
Authorization: AWS4-HMAC-SHA256 Credential=user/20230206/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230206T192300Z

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 319
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 06 Feb 2023 19:23:00 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Request-Id: 1741529F601A9FA0
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  2.844763ms

mc: <ERROR> Unable to validate source `localdev-user/user-data/example.username/test.txt`.
```

*Note: Access is also denied when the LDAP user is logged into the web console.

## Your Environment

* MinIO server version:

RELEASE.2023-01-31T02-24-19Z

* MinIO client version:

RELEASE.2023-01-28T20-29-38Z

* Operating System and version (`uname -a`):

21.6.0 Darwin Kernel Version 21.6.0; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: pass proper username (simple) string as expected

## Motivation and Context
fixes #16552

## How to test this PR?
As per #16552 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
