### PR TITLE
prom: Average TCP dial time to be reset for each scrape

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Currently, minio_inter_node_traffic_dial_avg_time prometheus 
metric shows the average TCP dial connection since the start 
of the cluster. However, this absolute average will not help 
detect any networking fluctuation. This commit will reset 
average TCP dial time each prometheus scrape

## Motivation and Context
Better added value for minio_inter_node_traffic_dial_avg_time metric

## How to test this PR?
Trivial

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — COMMENTED** [review]
We shouldn't make any metrics depend on scrape frequency.

Instead it should be a 1 minute rolling window with 1 second resolution.

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by vadmeste** [comment]
> We shouldn't make any metrics depend on scrape frequency.

I can do it, but I think it will need a new new mutex which will be held for each new connection creation.. At the same time, I don't see huge benefit from using the one minute rolling window over prometheus scarpe window

**Comment by harshavardhana** [comment]
PTAL @klauspost

**Comment by klauspost** [comment]
I have rewritten the profiling to be pretty much lockless. I don't really like how it ended up. I will simplify it a bit and send a PR.

**Comment by harshavardhana** [comment]
> I have rewritten the profiling to be pretty much lockless. I don't really like how it ended up. I will simplify it a bit and send a PR.

@vadmeste  is this PR still valid? as per this ^^?

**Comment by harshavardhana** [comment]
Closing this for now, if this needed in future let's resubmit with the changes requested by @klauspost

**Pull request closed without merging**
