### PR TITLE
Update browser UI with new logo and colors

### PR DESCRIPTION
**Pull request by rushenn**
## Description
Update Minio Browser UI with new branding colors and logo

## Motivation and Context
In order to apply the new branding changes to the Browser. 

## Regression
No

## How Has This Been Tested?
Tested locally

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0da905e8-257a-44b6-bdfd-2deea3e01321) |
<a name="0da905e8-257a-44b6-bdfd-2deea3e01321"></a>
### 7408-80ef3f8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30283
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3d31a6f3c059:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-tzbql990fnco44",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 321,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:30283/aws-sdk-go-test-tzbql990fnco44: dial tcp 72.28.97.59:30283: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]
You need to generate ui-assets.go with `yarn release` as well in the browser/ folder @rushenn

**Comment by kaankabalak** [comment]
- Can we use the white bird instead of the red bird throughout the app? However, we need the red bird on the favicon
- Can we rename the browser to "MinIO Browser"?
- When I autofill the Access Key field on Google Chrome, the text seems to be the same color as the background, so it appears hidden to the user:
Screen Shot 2019-03-22 at 6 55 25 PM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :x: [more...](#56cb0b76-f320-41eb-9af3-cdc07f1a22fb) |
<a name="56cb0b76-f320-41eb-9af3-cdc07f1a22fb"></a>
### 7408-3452b2e/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32041
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1683d9c5c190:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 31 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 49 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 46 seconds
(11/14) Running minio-js tests ... done in 39 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 8 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "duration": 102,
  "args": {
    "object_name": "8b4d8c1e-9d44-41a4-a5c4-f52080d443bb",
    "bucket_name": "minio-py-test-196f5b5f-3556-4c87-8680-96efcd838ef9"
  },
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "message": "AccessDenied: message: Access Denied"
}

Executed 11 out of 14 tests successfully.
```

**Review by harshavardhana — COMMENTED** [review]
LGTM, please add the new ui-assets.go

**Review by kanagarajkm — CHANGES_REQUESTED** [review]
title on index.html should be changed to `MinIO Browser`

**Comment by kanagarajkm** [comment]
favicon needs to be updated as well.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f7aa2116-c9eb-45f8-9f7a-75d575fcad0d) |
| mint-compression-dist-xl.sh | :x: [more...](#a79c7ff4-f78d-4416-bac8-baf1887d2634) |
| mint-fs.sh | :x: [more...](#d1b540e3-6bd6-4143-a63b-50d37c8c3cfe) |
| mint-dist-xl.sh | :x: [more...](#1d3cb727-3eb7-49da-9f05-668c6d796475) |
<a name="d1b540e3-6bd6-4143-a63b-50d37c8c3cfe"></a>
### 7408-382ec30/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30893
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 91a8bd0b3664:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vinrkg6tqxrr2m",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 379,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:30893/aws-sdk-go-test-vinrkg6tqxrr2m: dial tcp 72.28.97.61:30893: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="1d3cb727-3eb7-49da-9f05-668c6d796475"></a>
### 7408-382ec30/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31681
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c0d5c2b57002:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 49 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 25 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 51 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 45 seconds
(11/14) Running minio-js tests ... done in 39 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 29 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "name": "minio-py:test_presigned_get_object_response_headers",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1266, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 152, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1888, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1274, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "message": "'content-language'",
  "args": {
    "object_name": "a6b2aa3e-700c-4cfa-85a1-b57ca1bb53d4",
    "bucket_name": "minio-py-test-7dd3afbe-8f32-43d5-b885-e82d1cee0442"
  },
  "duration": 126,
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="a79c7ff4-f78d-4416-bac8-baf1887d2634"></a>
### 7408-382ec30/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31986
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 328d173f5af8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5ant2h4o4nwfwv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 280,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31986/aws-sdk-go-test-5ant2h4o4nwfwv: dial tcp 72.28.97.57:31986: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f7aa2116-c9eb-45f8-9f7a-75d575fcad0d"></a>
### 7408-382ec30/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31843
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 007c4f335bfe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-6t9hkbcnwq6zeb",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 306,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:31843/aws-sdk-go-test-6t9hkbcnwq6zeb: dial tcp 72.28.97.54:31843: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#781be482-6b80-4647-85f1-d304b18b6e48) |
<a name="781be482-6b80-4647-85f1-d304b18b6e48"></a>
### 7408-5465515/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31598
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8d4422c89a70:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-aporxkkkuzjm55",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 323,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:31598/aws-sdk-go-test-aporxkkkuzjm55: dial tcp 72.28.97.53:31598: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#5bdec20a-899e-4484-b6c6-7147c8575bc3) |
| mint-compression-dist-xl.sh | :x: [more...](#b317f228-14bf-4bda-9311-b200e100b4a8) |
| mint-dist-xl.sh | :x: [more...](#50edb813-ea7b-41f3-ab5b-d8772e3762bd) |
<a name="b317f228-14bf-4bda-9311-b200e100b4a8"></a>
### 7408-9567240/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31104
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 77c6ffa66b9a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ieode33ntgnplc",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 332,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31104/aws-sdk-go-test-ieode33ntgnplc: dial tcp 72.28.97.57:31104: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5bdec20a-899e-4484-b6c6-7147c8575bc3"></a>
### 7408-9567240/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31471
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 05a2f4464059:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-d9axplidp5zd9q",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 334,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:31471/aws-sdk-go-test-d9axplidp5zd9q: dial tcp 72.28.97.61:31471: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="50edb813-ea7b-41f3-ab5b-d8772e3762bd"></a>
### 7408-9567240/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31066
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c5a3fb764e14:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-e1tbp0qv0e52mr",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 331,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:31066/aws-sdk-go-test-e1tbp0qv0e52mr: dial tcp 72.28.97.61:31066: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#770412df-d301-4057-b46a-6caa7f5a9aba) |
<a name="770412df-d301-4057-b46a-6caa7f5a9aba"></a>
### 7408-bff0872/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30400
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1786768fb643:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vcxo02fldfh0ir",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 323,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:30400/aws-sdk-go-test-vcxo02fldfh0ir: dial tcp 72.28.97.53:30400: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#aabdb1d0-f60d-4b47-8c4c-d748f6e453d1) |
| mint-dist-xl.sh | :x: [more...](#f1d6de16-e7cd-4ee6-988d-957016a0cb27) |
<a name="f1d6de16-e7cd-4ee6-988d-957016a0cb27"></a>
### 7408-b400e76/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32582
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7a3bb9978405:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-cbrknfi6kydj2n",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 237,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:32582/aws-sdk-go-test-cbrknfi6kydj2n: dial tcp 72.28.97.53:32582: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="aabdb1d0-f60d-4b47-8c4c-d748f6e453d1"></a>
### 7408-b400e76/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31657
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9bbb59583506:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wfisirspor6hhv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 244,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:31657/aws-sdk-go-test-wfisirspor6hhv: dial tcp 72.28.97.59:31657: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Review by kanagarajkm — APPROVED** [review]

**Pull request merged**
