### PR TITLE
helm: (Bugfix) enable objectlocking

### PR DESCRIPTION
**Pull request by r0b1ndot**
## Description
in https://github.com/minio/minio/pull/15505 i implemented OBJECT LOCKING for Buckets.

## Motivation and Context
i discovered a bug, if you don't set any locking that no buckets are created.
this PR fixes that and also explains why the versioning is not touched if OBJECT LOCKING is enabled.

## How to test this PR?
in your values.yaml
```
  buckets:
  #   # Name of the bucket
      - name: examplebucket
        # Policy to be set on the
        # bucket [none|download|upload|public]
        policy: upload
        # Purge if bucket exists already
        purge: true
  #   # set versioning for
  #   # bucket [true|false]
        versioning: true
  #   # set objectlocking for
  #   # bucket [true|false] NOTE: versioning is enabled by default if you use locking 
  #   objectlocking: false
  
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here) #15505
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by harshavardhana** [comment]
@reyerdam for helm fixes use `helm: ` prefix to avoid clobbering the "title" with actual "object locking" code in MinIO.

**Comment by r0b1ndot** [comment]
> @reyerdam for helm fixes use `helm: ` prefix to avoid clobbering the "title" with actual "object locking" code in MinIO.

thanks for the hint, i adjusted the description :)

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Pull request merged**
