### PR TITLE
service port set to minioAPIPort in helm

### LINKED ISSUE #15175: Helm Chart: service port set to minioAPIPort
## NOTE
Currently it's hard set to port 9000 but I believe it should be set to MinioAPIPort which is the containerPort of the deployment.
https://github.com/minio/minio/blob/master/helm/minio/templates/service.yaml#L39

If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

### PR DESCRIPTION
**Pull request by dormanze**
## Description
fix #15175 

## Motivation and Context
Modify the fixed port in Helm.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#1d4d3eb4-11a4-42b2-84cb-2edffe459ffd) |
<a name="1d4d3eb4-11a4-42b2-84cb-2edffe459ffd"></a>
### 15223-92e6e16/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:31756
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 36 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 19 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 21 seconds
(10/15) Running minio-java tests ... done in 37 seconds
(11/15) Running minio-js tests ... FAILED in 1 minutes and 1 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook for \"removeObjects(bucketName, objectsList)",
  "args": "bucketName:minio-js-test-ver-presign-d59c03af-9586-4684-b5a5-f6885fcc9228\"",
  "duration": 8,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty. You must delete all versions in the bucket. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(11/15) Running minio-py tests ... done in 1 minutes and 36 seconds
(12/15) Running s3cmd tests ... done in 26 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by chel-ou** [comment]
Hello,
I believe that this commit introduces a bug, as the `targetPort` is set to `.Values.service.port` and not `.Values.minioAPIPort` (as written on the commit comment).

**Comment by dormanze** [comment]
> 

The .Values.service.port is sure to match it to .Values.minioAPIPort.
image

**Comment by chel-ou** [comment]
I had not seen this comment in `values.yaml`.
But in practice I believe that if you set `targetPort: {{ .Values.minioAPIPort }}` as you actually wrote in the commit message, the comment in `values.yaml` could become unnecessary.

I reviewed the code, and I think the further changes should be:
- In `networkpolicy.yaml`: replace `.Values.service.port` by `.Values.minioAPIPort`
- In `statefulset.yaml` also add `targetPort: {{ .Values.minioAPIPort }}` in the service template

Today I keep the `minioAPIPort` at `9000` and expose the service to port `80` without any problem. This commits break my set up though.

I'm happy to propose a PR if you support the changes.

**Comment by harshavardhana** [comment]
Feel to free to send PRs.

**Pull request merged**
