### PR TITLE
Add CodeQL security scanning

### PR DESCRIPTION
**Pull request by jhutchings1**
Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.

Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 

If you're interested in trying it out, you can merge this pull request to set up the Actions workflow.

### CODE REVIEW

**Comment by harshavardhana** [comment]
@jhutchings1 thanks for the PR - we would love to use CodeQL, looks like the PR is sent for a Java project we are a Go project can this be changed accordingly?

**Comment by jhutchings1** [comment]
Thanks @harshavardhana. It looks like the auto-language detection detected Java for some reason, but I've excluded it and started the build again.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by jhutchings1** [comment]
Thanks @kannappanr and @harshavardhana! If you're game, I'm happy to send PRs for the other Go, Python, or JavaScript repos in your org to get you jumpstarted. I've got a script that makes this easy, so just let me know! 

We also support other languages (C, C++, C#, Java), but the build configuration on those is occasionally more involved, so that's more likely to require work from a maintainer.

**Comment by harshavardhana** [comment]
> Thanks @kannappanr and @harshavardhana! If you're game, I'm happy to send PRs for the other Go, Python, or JavaScript repos in your org to get you jumpstarted. I've got a script that makes this easy, so just let me know! 
> 
> We also support other languages (C, C++, C#, Java), but the build configuration on those is occasionally more involved, so that's more likely to require work from a maintainer. 

Please do happy for all the work GitHub has done here.

**Pull request merged**
