### PR TITLE
browser: Remove hardcoding of minioBrowserPrefix=/minio

### LINKED ISSUE #5040: Removing hardcoding of /minio in browser code
Currently browser has hardcoding such that all browser requests are sent to `/minio` The problem with this is that webUI of different instances behind nginx reverse proxy can't be accessed using nginx rules.

Currently S3 requests can be routed by nginx using rules explained here: https://github.com/krishnasrinivas/wikinotes/wiki/Minio-Multi-tenancy

Similar mux'ing using path can't be achieved for webUI as `/minio` is hardcoded in browser code.

What needs to be done is remove hard coding of this:
```
constants.js:export const minioBrowserPrefix = '/minio'
```

and it should be initialised in index.js before calling `new Web()`

The value to which it should be initialised can be figured out by looking at `window.location.pathname`

There are other places where `/minio` is hardcoded which should be fixed:
```
krishna@escape:~/gocode/src/github.com/minio/minio/browser/app/js$ grep '\/minio' * -r
actions.js:    const uploadUrl = `${window.location.origin}/minio/upload/${currentBucket}/${objectName}`
components/Browse.js:          let url = `${window.location.origin}/minio/download/${currentBucket}/${encPrefix}?token=${res.token}`
components/Browse.js:        let requestUrl = location.origin + "/minio/zip?token=" + res.token
components/Browse.js:      loginButton = <a className='btn btn-danger' href='/minio/login'>Login</a>
components/Browse.js:                  <a href="https://minio.io" target="_blank"><img className="maii-logo" src={ logo } alt="" /></a>
components/BrowserDropdown.js:            <a target="_blank" href="https://github.com/minio/minio">Github <i className="fa fa-github"></i></a>
constants.js:export const minioBrowserPrefix = '/minio'
krishna@escape:~/gocode/src/github.com/minio/minio/browser/app/js$ 
```

### PR DESCRIPTION
**Pull request by krishnasrinivas**
This enable reverse proxy of minio-browser. Fixes #5040

## Description

Detailed explanation is available at: https://github.com/minio/minio/issues/5040

## How Has This Been Tested?

manual testing using nginx
```
http {
     server {
    	   listen       80;
	   location ~* ^/user1(.*)$ {
		rewrite ^/user1(.*)$ /minio$1 break;
		proxy_redirect     off;
		proxy_set_header Host $http_host;
		proxy_pass http://localhost:9000;
	   }
     }
}
```
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by vadmeste** [comment]
@krishnasrinivas, I understood what this PR does but I am not sure what problem it does solve.

```
http {
     server {
    	   listen       80;
	   location ~* ^/user1/(.*)$ {
		rewrite ^/user1/(.*)$ /minio$1 break;
		proxy_redirect     off;
		proxy_set_header Host $http_host;
		proxy_pass http://localhost:9000;
	   }
     }
}
```

Won't this nginx config route all incoming requests from all users to only one Minio instance ?
(`proxy_pass http://localhost:9000`)

Let's discuss this in private when you are available.

**Comment by vadmeste** [comment]
I discussed with @krishnasrinivas who explained to me that Minio Browser needs to call `/user_id/index.html` instead of default minio prefix `/minio/index.hml`

**Comment by vadmeste** [comment]
I tested it, basic operations work (:+1:) however there is a little problem with shared links.. it doesn't include the user prefix for now.

**Comment by krishnasrinivas** [comment]
yes @vadmeste shared links are presigned URLs accessing S3 directly and hence this nginx config will not be useful. It will need additional nginx config to route the presigned requests and outside the scope of this patch.

**Review by kannappanr — DISMISSED** [review]
LGTM

**Comment by harshavardhana** [comment]
can you rebase this PR @krishnasrinivas there is a conflict..

**Review by vadmeste — DISMISSED** [review]
LGTM

**Comment by vadmeste** [comment]
This fails with the following error:
```
=== RUN TestHTTPListenerAddr
--- FAIL: TestHTTPListenerAddr (0.01s)
	listener_test.go:333: Test 4: error: expected = <nil>, got = listen tcp 127.0.0.1:60004: bind: address already in use
=== RUN TestHTTPListenerAddrs
--- FAIL: TestHTTPListenerAddrs (0.01s)
	listener_test.go:378: Test 4: error: expected = <nil>, got = listen tcp 127.0.0.1:60010: bind: address already in use
```

**Comment by deekoder** [comment]
can reviewers also examine code coverage failures?

**Comment by krishnasrinivas** [comment]
@deekoder code coverage can be fixed by adding a test case in mint which fetches /minio/index.html

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by deekoder** [comment]
Codecoverage is addressed via https://github.com/minio/mint/issues/212

**Pull request merged**
