### PR TITLE
Add checks in DiskInfo() to protect against changing mounts

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add checks in DiskInfo() to protect against changing mounts

## Motivation and Context
There is a possibility of DiskInfo() call returning incorrect
values if the disks are not mounted properly.

## How to test this PR?
The checks added in this PR are inline with other calls in posix layer.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#ded79d0b-6144-4f5f-91db-f13158abce6c) |
| mint-large-bucket.sh | :x: [more...](#bc6743c3-ded8-4999-a87a-3dfad4475f81) |
<a name="bc6743c3-ded8-4999-a87a-3dfad4475f81"></a>
### 8286-39968aa/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31155
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 61d6721b2961:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 5 seconds
(3/14) Running aws-sdk-php tests ... done in 54 seconds
(4/14) Running aws-sdk-ruby tests ... done in 21 seconds
(5/14) Running awscli tests ... done in 2 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 23 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 24 seconds
(9/14) Running minio-go tests ... done in 2 minutes and 27 seconds
(10/14) Running minio-java tests ... done in 3 minutes and 13 seconds
(11/14) Running minio-js tests ... done in 1 minutes and 5 seconds
(12/14) Running minio-py tests ... FAILED in 6 minutes and 10 seconds
{
  "status": "FAIL",
  "duration": 667,
  "args": {
    "response.reason": "Forbidden",
    "object_name": "1746a9f9-272d-4da7-b320-1d9014d4401f",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-22T10-16-34Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C6BD02AFB61898\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Sun, 22 Sep 2019 10:48:59 GMT\"]}}",
    "bucket_name": "minio-py-test-5e963aec-0a11-4a32-a128-4d3d2fa203cb",
    "presigned_get_object_url": "http://72.28.97.52:31155/minio-py-test-5e963aec-0a11-4a32-a128-4d3d2fa203cb/1746a9f9-272d-4da7-b320-1d9014d4401f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190922%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190922T104853Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=169f836867ddbc03e64cd7e04a63c9202a85b2d1fb545b5bf5d382f1c67da527",
    "response.status": 403,
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>1746a9f9-272d-4da7-b320-1d9014d4401f</Key><BucketName>minio-py-test-5e963aec-0a11-4a32-a128-4d3d2fa203cb</BucketName><Resource>/minio-py-test-5e963aec-0a11-4a32-a128-4d3d2fa203cb/1746a9f9-272d-4da7-b320-1d9014d4401f</Resource><RequestId>15C6BD02AFB61898</RequestId><HostId>fee64c3f-25b3-4974-bf50-9f21b76a1223</HostId></Error>"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "message": "AccessDenied: message: Access Denied",
  "name": "minio-py:test_presigned_get_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```
<a name="ded79d0b-6144-4f5f-91db-f13158abce6c"></a>
### 8286-39968aa/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31038
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4ca86d972e4a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fdrv6xgg9pq3b9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365400,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C6BC4668C85133, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ebc1b361-e7f9-436a-8bb6-db1635bfac10) |
<a name="ebc1b361-e7f9-436a-8bb6-db1635bfac10"></a>
### 8286-04f189e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31617
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e5e3c6c52117:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 56 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 38 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 31 seconds
{
  "name": "mc",
  "duration": "6917",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-3154 --quiet --no-color cp myminio/mc-test-bucket-26028/mc-test-object-13447 mc-test-object-13447.downloaded  >>> \n`myminio/mc-test-bucket-26028/mc-test-object-13447` -> `mc-test-object-13447.downloaded`\nmc: <ERROR> Failed to copy `http://72.28.97.58:31617/mc-test-bucket-26028/mc-test-object-13447`. read tcp 172.17.0.10:41424->72.28.97.58:31617: read: connection reset by peer\nmc: <ERROR> Session safely terminated. To resume session `mc session resume ZGodiFPZ`"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#cdbfb41d-ce5f-4556-b836-1b18b8c10816) |
| mint-fs.sh | :x: [more...](#8cfd55d9-9615-4b84-adf4-06a025c56614) |
<a name="cdbfb41d-ce5f-4556-b836-1b18b8c10816"></a>
### 8286-b227acf/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31662
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5262d1b0e446:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 29 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 8 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 20 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 41 seconds
{
  "args": {},
  "duration": 103653,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="8cfd55d9-9615-4b84-adf4-06a025c56614"></a>
### 8286-b227acf/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32452
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dd7a992796b4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 37 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 47 seconds
(10/14) Running minio-java tests ... done in 50 seconds
(11/14) Running minio-js tests ... done in 42 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 12 seconds
{
  "duration": 48,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "presigned_get_object_url": "http://72.28.97.59:32452/minio-py-test-1ceb676f-d679-47bf-97a6-5e6845dc4b75/329eacc0-a616-4a37-b70b-131defaa6d65?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190923%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190923T012936Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=c1532349a8c6aee629a59c55bd128de991a8910d572ebbac1b9056c32f61c065",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-23T01-08-35Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C6ED12316E9D5D\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Mon, 23 Sep 2019 01:29:42 GMT\"]}}",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>329eacc0-a616-4a37-b70b-131defaa6d65</Key><BucketName>minio-py-test-1ceb676f-d679-47bf-97a6-5e6845dc4b75</BucketName><Resource>/minio-py-test-1ceb676f-d679-47bf-97a6-5e6845dc4b75/329eacc0-a616-4a37-b70b-131defaa6d65</Resource><RequestId>15C6ED12316E9D5D</RequestId><HostId>1e388851-cad5-481e-82ec-55cd36e471cb</HostId></Error>",
    "response.reason": "Forbidden",
    "response.status": 403,
    "bucket_name": "minio-py-test-1ceb676f-d679-47bf-97a6-5e6845dc4b75",
    "object_name": "329eacc0-a616-4a37-b70b-131defaa6d65"
  },
  "message": "AccessDenied: message: Access Denied",
  "name": "minio-py:test_presigned_get_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```

**Review by Praveenrajmani — APPROVED** [review]
LGTM

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
