### PR TITLE
Add prometheus auth-type to turn-off authentication

### LINKED ISSUE #8323: Minio monitoring with prometheus in K8s - authentication
Hi,
I'm setuped a prometheus and a minio cluster in K8s. I'm using the well known [prometheus-operator](https://github.com/coreos/prometheus-operator) to configure my prometheus scrape configuration. I'm able to add a [bearerTokenFile](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint) with the provided API from prometheus-operator. In general this is always the token from the serviceaccount running prometheus (`/var/run/secrets/kubernetes.io/serviceaccount/token`).

## Expected Behavior
Be able to monitor minio with a k8s serviceaccount token

## Current Behavior
After updating to [RELEASE.2019-09-25T18-25-51Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-09-25T18-25-51Z) I'm not able to monitor my minio cluster anymore. (403 Forbidden). I think generating the token via [mc tool](https://github.com/minio/cookbook/blob/master/docs/how-to-monitor-minio-with-prometheus.md#2-generate-the-prometheus-config-with-mc) is wrong in a k8s setup.

## Possible Solutions
1. Use k8s authentication service to secure metric endpoint
2. Give a option with environment variable to disable authentication
3. Give a option with environment variable to set a bearer token

## Steps to Reproduce (for bugs)
1. Setup K8s
2. Setup prometheus with prometheus-operator
3. Setup Minio with RELEASE.2019-09-25T18-25-51Z

## Regression
Yes,
[Minio version RELEASE.2019-09-25T18-25-51Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-09-25T18-25-51Z)
[Commit-Id](https://github.com/minio/minio/pull/7640/commits/8575c028161dbdcf014de915cad8b043eba27067)

## Your Environment
* Version used (`minio version`): RELEASE.2019-09-25T18-25-51Z
* Kubernetes: kubernetes v1.11.0+d4cacc0
* Openshift: openshift v3.11.0+1f48d99-299

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add Prometheus auth-type to turn-off authentication

## Motivation and Context
Also, this PR moves the original doc from the cookbook to
MinIO repo under docs/metrics/prometheus/

Fixes #8323

## How to test this PR?
Just set the `MINIO_PROMETHEUS_AUTH_TYPE=public` 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by harshavardhana** [comment]
> NOTE this is already verified with @abperiasamy

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :x: [more...](#a5091841-249e-44a5-a702-8d11846fd9c0) |
<a name="a5091841-249e-44a5-a702-8d11846fd9c0"></a>
### 8356-63786f8/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30653
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 37e9888de1ec:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 35 seconds
(8/14) Running minio-dotnet tests ... done in 28 seconds
(9/14) Running minio-go tests ... done in 37 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 18 seconds
(11/14) Running minio-js tests ... done in 43 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 32 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "response.status": 403,
    "bucket_name": "minio-py-test-cfacc443-de49-4a4a-b3d0-4f6ebc1eab79",
    "presigned_get_object_url": "http://72.28.97.58:30653/minio-py-test-cfacc443-de49-4a4a-b3d0-4f6ebc1eab79/5caefc13-987b-42a8-8ed9-c66a432cc37d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191003%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191003T213017Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=959f2b1f17b80fbc2dd75fb23c7d2835c57b23fe1b7e459eb970b61a929a7b2c",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-03T21-02-19Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CA4065C70848E3\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Thu, 03 Oct 2019 21:30:25 GMT\"]}}",
    "object_name": "5caefc13-987b-42a8-8ed9-c66a432cc37d",
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>5caefc13-987b-42a8-8ed9-c66a432cc37d</Key><BucketName>minio-py-test-cfacc443-de49-4a4a-b3d0-4f6ebc1eab79</BucketName><Resource>/minio-py-test-cfacc443-de49-4a4a-b3d0-4f6ebc1eab79/5caefc13-987b-42a8-8ed9-c66a432cc37d</Resource><RequestId>15CA4065C70848E3</RequestId><HostId>bd0ebbc3-20ff-46f4-981f-b8608906c884</HostId></Error>"
  },
  "message": "AccessDenied: message: Access Denied",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "duration": 118
}

Executed 11 out of 14 tests successfully.
```
Error: No such image: minio/minio:8356-63786f8

**Review by Praveenrajmani — APPROVED** [review]
Tested and LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
