### PR TITLE
Update go mod with sem versions of our libraries

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Update go mod with sem versions of our libraries

## Motivation and Context
This to start using sem versions of our libraries.

## Regression
No

## How Has This Been Tested?
Nothing new changed in this PR just version change

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#266270ea-2dd8-42bb-a723-cf166efec595) |
<a name="266270ea-2dd8-42bb-a723-cf166efec595"></a>
### 7687-10ed41d/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31308
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 89422353aeef:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mpj6aqtjwpoj2p",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360012,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A168DDB2A79766, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
Blocking merge of this until we get minio-go released after the new `go mod` compatible versioning change.

**Comment by harshavardhana** [comment]
Blocked on `mc` PR merge https://github.com/minio/mc/pull/2782

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d2fc59a9-5a11-4cd1-b0c3-55773696f3bd) |
<a name="d2fc59a9-5a11-4cd1-b0c3-55773696f3bd"></a>
### 7687-a8c4742/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31628
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2e421618efca:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 1 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 51 seconds
{
  "name": "mc",
  "duration": "108638",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-30725 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-11130/mc-test-object-18696  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-11130/mc-test-object-18696`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Session safely terminated. To resume session `mc session resume keeLuVtd`"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d8e40102-d1e1-4691-b7e8-80bf3493bccf) |
<a name="d8e40102-d1e1-4691-b7e8-80bf3493bccf"></a>
### 7687-452c495/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31808
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7a43282eb890:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 34 seconds
{
  "name": "mc",
  "duration": "126837",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-19403 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-22146  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-22146/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-22146/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-22146/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-22146/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-22146/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-22146/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-22146/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-22146/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-22146/datafile-100-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-22146/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-22146/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-22146/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-22146/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-22146/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 364.39 MiB, Speed: 2.87 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
This PR is unblocked now - PTAL @donatello @wlan0

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#637fcbe2-f35e-41b1-abf5-9fad604d80b5) |
| mint-dist-xl.sh | :x: [more...](#f847a086-4689-43af-8a66-fb2246ba479c) |
<a name="f847a086-4689-43af-8a66-fb2246ba479c"></a>
### 7687-5488e5a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32249
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4518b61f3468:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 8 seconds
(8/14) Running minio-dotnet tests ... done in 32 seconds
(9/14) Running minio-go tests ... done in 41 seconds
(10/14) Running minio-java tests ... FAILED in 34 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 377,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3t8g8g8, objectName=minio-java-test-gn832, resource=/minio-java-test-3t8g8g8/minio-java-test-gn832, requestId=15A3404EE4D391EB, hostId=3f6bf1b3-deca-459c-9389-6a16c0cca8cc)\nrequest={method=DELETE, url=http://72.28.97.55:32249/minio-java-test-3t8g8g8/minio-java-test-gn832?uploadId=48d916e8-3042-453d-ae2e-1a122b3ea2ba, headers=Host: 72.28.97.55:32249\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190529T201003Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190529/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-29T19-48-04Z\nVary: Origin\nX-Amz-Request-Id: 15A3404EE4D391EB\nX-Minio-Deployment-Id: 3f6bf1b3-deca-459c-9389-6a16c0cca8cc\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 May 2019 20:10:03 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="637fcbe2-f35e-41b1-abf5-9fad604d80b5"></a>
### 7687-5488e5a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30967
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 803ea7a5d162:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 11 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 42 seconds
{
  "name": "mc",
  "duration": "124997",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-11539 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-1561  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-1561/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-1561/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-1561/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-1561/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-1561/datafile-10-kB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-1561/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-1561/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-1561/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-1561/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-1561/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-1561/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-1561/datafile-5243880-b`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-1561/datafile-129-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-1561/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-1561/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 408.86 MiB, Speed: 3.27 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Review by wlan0 — DISMISSED** [review]

**Review by wlan0 — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#f2cdf034-f9b7-423c-ae02-9ebbfb8bb092) |
| mint-large-bucket.sh | :x: [more...](#c377f08a-e65d-481a-aa18-7b78bac756f7) |
| mint-dist-xl.sh | :x: [more...](#804360e9-c260-41bf-8ccb-94e788d3cc09) |
<a name="804360e9-c260-41bf-8ccb-94e788d3cc09"></a>
### 7687-cd485a5/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30874
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e02c48c0e6b1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 0 seconds
(10/14) Running minio-java tests ... FAILED in 33 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 252,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-ckqh8h, objectName=minio-java-test-3u6kjad, resource=/minio-java-test-ckqh8h/minio-java-test-3u6kjad, requestId=15A3453E5ABA47CE, hostId=1f33779d-9a46-4d9f-9b3b-f995bb19f6d9)\nrequest={method=DELETE, url=http://72.28.97.56:30874/minio-java-test-ckqh8h/minio-java-test-3u6kjad?uploadId=ec8c6243-4647-4c04-90d5-1647b1813a5b, headers=Host: 72.28.97.56:30874\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190529T214030Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190529/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-29T21-21-37Z\nVary: Origin\nX-Amz-Request-Id: 15A3453E5ABA47CE\nX-Minio-Deployment-Id: 1f33779d-9a46-4d9f-9b3b-f995bb19f6d9\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 May 2019 21:40:30 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="f2cdf034-f9b7-423c-ae02-9ebbfb8bb092"></a>
### 7687-cd485a5/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30185
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3f045517e401:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-4rm6zifnvull35",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360013,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A3453DF97EC906, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c377f08a-e65d-481a-aa18-7b78bac756f7"></a>
### 7687-cd485a5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31478
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1f5502ecc5e8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 21 seconds
(5/14) Running awscli tests ... done in 2 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 3 minutes and 38 seconds
{
  "name": "mc",
  "duration": "153516",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-12650 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-1567  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-1567/datafile-1-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-1567/datafile-1-b`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-1567/datafile-0-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-1567/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-1567/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-1567/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-1567/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-1567/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-1567/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-1567/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-1567/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-1567/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-1567/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-1567/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-1567/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 762.24 MiB, Speed: 4.97 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Pull request merged**
