### PR TITLE
Fix GetObjectNInfo caching

### PR DESCRIPTION
**Pull request by leitzler**
## Description
Use `GetObjectInfo` instead of `GetObjectNInfo` to fetch metadata before deciding if disk cache should be used or not.

## Motivation and Context
Currently a `GetObjectNInfo` call to the backend is performed before deciding if the disk cache should be used. The call also implies a `GetObject` call to the backend to get the reader, so the actual payload is already on the wire when the decision about using cache is made. If minio decides to use cache, the fetched payload is discarded and the object from cache is returned.

## How Has This Been Tested?
`make test` & by running `tcpdump` while using the cache to see that `HEAD` requests are being sent instead of `GET` requests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Thanks, @leitzler for the PR :+1:

**Review by poornas — APPROVED** [review]
LGTM.

**Review by donatello — APPROVED** [review]
Nice PR! LGTM.

**Comment by kannappanr** [comment]
@donatello @poornas Did you run mint locally for this PR?

**Comment by kannappanr** [comment]
Marking this PR as blocked until we have the mint automation up and running

**Comment by deekoder** [comment]
@poornas ran mint locally and everything is LGTM.

**Pull request merged**
