### PR TITLE
Disable browser redirect

### PR DESCRIPTION
**Pull request by mathiasaerts**
## Description
Introduce a new environment variable to disable redirecting to the Minio browser for files that don't exist or you don't have access to.

## Motivation and Context
When trying to access an object with insufficient rights or an object that does not exist from a web browser, it can be undesired to be redirected to the Minio web interface. Using the `MINIO_BROWSER_REDIRECT` environment variable, it is possible to disable this behaviour, returning a regular 403 (XML) response like you would expect from Amazon S3 as well.

Alternatively, it would be nice to have the option to bind to a second port which (only) exposes the Minio browser, while the regular listen port serves regular requests (without redirecting). That way, it would be possible to add extra security checks when running behind a reverse proxy.

## How to test this PR?
1. Build the minio server and start it with the `MINIO_BROWSER_REDIRECT` set to `off`.
```
make build
MINIO_BROWSER_REDIRECT=off ./minio server /tmp/minio-data
```
2. Try to open a random file in your web browser: `http://127.0.0.1:9000/non-existing-bucket/filename.example`
3. Expect to see a 403 response saying `AccessDenied` instead of being redirected to `http://127.0.0.1:9000/minio/non-existing-bucket/filename.example`
4. Verify that the browser still works by visiting `http://127.0.0.1:9000/minio/`
5. Restart the server with `MINIO_BROWSER_REDIRECT` set to `on`.
```
MINIO_BROWSER_REDIRECT=off ./minio server /tmp/minio-data
```
6. Verify that the previous URL now does redirect to the Minio browser.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [x] Unit tests needed
- [x] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by harshavardhana** [comment]
Thanks for the PR lets discuss first on https://slack.min.io on why it's not worth to use MINIO_BROWSER=off 

Going to close this PR for now.

**Review by harshavardhana — CHANGES_REQUESTED** [review]
what is the rationale behind this PR? why isn't MINIO_BROWSER=off sufficient? do you still want access to the browser and not have redirects? Because the redirects were added on purpose by an ask by one of our customers where they land on the browser to provide credentials since they are interested in the browser not an XML being thrown at them and we can't change that behavior now.  Additionally running the browser app on a separate port is unacceptable for us - we have decided long ago to not go that route.

Because if you look at it throwing an XML is useless for users of MinIO @mathiasaerts , as they see access denied a browser is shown to provide the right credentials. If the browser itself is not needed completely disable it which disables this functionality altogether. 

Adding new ENVs is a rabbit hole and we would like to avoid adding new ENVs as much as possible unless strictly needed and we have explored all other options.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#b90c3fd3-0389-4872-af3d-9ab768e46acb) |
| mint-large-bucket.sh | :x: [more...](#187f405e-9b0b-4354-a24f-67ff93f9487e) |
<a name="187f405e-9b0b-4354-a24f-67ff93f9487e"></a>
### 8798-b517a7c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31147
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8ea87979c6de:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 14 seconds
{"name": "awscli", "duration": 311894, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31147/awscli-mint-test-bucket-16954""}

Executed 0 out of 13 tests successfully.
```
<a name="b90c3fd3-0389-4872-af3d-9ab768e46acb"></a>
### 8798-b517a7c/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32595
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c5af62aaa4a9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 7 seconds
{"name": "awscli", "duration": 305236, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32595/awscli-mint-test-bucket-15426""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#8c408123-53d9-476c-9ce2-3a33ae75c6ab) |
<a name="8c408123-53d9-476c-9ce2-3a33ae75c6ab"></a>
### 8798-b517a7c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31089
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 722a29b1ec76:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 16 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 2 seconds
(5/13) Running minio-go tests ... FAILED in 2 minutes and 46 seconds
{
  "args": {},
  "duration": 64065,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#4f940c44-c2aa-4fdd-b5f9-1a728e79c593) |
| mint-dist-xl.sh | :x: [more...](#8122fcb5-724a-4875-b7bd-4e92a3b8f651) |
<a name="4f940c44-c2aa-4fdd-b5f9-1a728e79c593"></a>
### 8798-d036340/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30273
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e5df0befd41d:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 305663, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30273/awscli-mint-test-bucket-705""}

Executed 0 out of 13 tests successfully.
```
<a name="8122fcb5-724a-4875-b7bd-4e92a3b8f651"></a>
### 8798-d036340/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31679
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 686fcca43b44:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 306493, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31679/awscli-mint-test-bucket-23989""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
For now please keep this change in your fork, we would like to limit the number of options for now. Closing this PR for now as there is nothing actionable from our end.

**Comment by ForsakenHarmony** [comment]
@harshavardhana Hey there I want this feature, related to #7851
Just started working on this when I saw the PR

I do want there to just be the XML permission denied screen, if I want someone to access the web interface I can send them a direct link

This doesn't break any existing behaviour, to me the point where you added the redirect without any option was the point where you did a breaking change

**Comment by ChanceM** [comment]
+1 On this. I would like to expose a public bucket that doesn't redirect to the login if someone should try a url directly to the bucket name. For now my reverse proxy will return a 404 as I have it specifically matching the path. I have two rules configured for my server. On one domain it servers the public bucket and on a second domain it servers the whole server internally including the browser. I don't need the server to redirect the user, but it would still be nice to use it.

**Pull request closed without merging**
