### PR TITLE
Use pointer based TLS field

### PR DESCRIPTION
**Pull request by anjalshireesh**
## Description

This will help projects like `health-analyzer` to know when the tls
info is not available (TLS field would be nil)
Signed-off-by: Shireesh Anjal <shireesh@minio.io>

## Motivation and Context

This is required to ensure that `health-analyzer` can reliably perform TLS related checks,
and skip them when tls info is not available.

## How to test this PR?

- Build `minio` with this PR and start the server
- Build `mc` with PR [3866](https://github.com/minio/mc/pull/3866)
- Generate health report using `mc admin subnet health {alias} --airgap`
- Verify that the generated report contains the node `minio -> info -> tls -> tls_info_available` with value `true`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by anjalshireesh** [comment]
@harshavardhana I'm currently pointing to `main` branch of `madmin-go` here. Will update this PR with proper version number if you create the tag.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by klauspost** [comment]
I know https://github.com/minio/madmin-go/pull/46 was merged, but why wasn't it simply it simply changed to `TLS *TLSInfo `json:"tls"`` in [MinioInfo](https://github.com/minio/madmin-go/blob/main/health.go#L793)?

That way even in-between versions will work and just can just check if it is nil?

**Review by klauspost — COMMENTED** [review]
I know https://github.com/minio/madmin-go/pull/46 was merged, but why wasn't it simply it simply changed to `TLS *TLSInfo `json:"tls"`` in [MinioInfo](https://github.com/minio/madmin-go/blob/main/health.go#L793)?

That way even in-between versions will work and just can just check if it is nil?

**Comment by anjalshireesh** [comment]
> I know [minio/madmin-go#46](https://github.com/minio/madmin-go/pull/46) was merged, but why wasn't it simply it simply changed to `TLS *TLSInfo `json:"tls"`` in [MinioInfo](https://github.com/minio/madmin-go/blob/main/health.go#L793)?
> 
> That way even in-between versions will work and just can just check if it is nil?

@klauspost thanks, this simple solution didn't occur to me! I will send another PR in `madmin-go` and later update this PR.

**Comment by anjalshireesh** [comment]
> > I know [minio/madmin-go#46](https://github.com/minio/madmin-go/pull/46) was merged, but why wasn't it simply it simply changed to `TLS *TLSInfo `json:"tls"`` in [MinioInfo](https://github.com/minio/madmin-go/blob/main/health.go#L793)?
> > That way even in-between versions will work and just can just check if it is nil?
> 
> @klauspost thanks, this simple solution didn't occur to me! I will send another PR in `madmin-go` and later update this PR.

https://github.com/minio/madmin-go/pull/48

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]

**Pull request merged**
