### PR TITLE
create subcomposed objects if total parts are > 32

### LINKED ISSUE #4283: [gateway-gcs] Support for CompleteMultipart when number of parts is more than 32
Support CompleteMultipart when len(parts) > 32

```
func (l *gcsGateway) CompleteMultipartUpload(bucket string, key string, uploadID string, uploadedParts []completePart) (ObjectInfo, error) {                                             
        partZero := l.client.Bucket(bucket).Object(toGCSMultipartKey(key, uploadID, 0))                                                                                                  
                                                                                                                                                                                         
        partZeroAttrs, err := partZero.Attrs(l.ctx)                                                                                                                                      
        if err != nil {                                                                                                                                                                  
                return ObjectInfo{}, gcsToObjectError(traceError(err), bucket, key)                                                                                                      
        }                                                                                                                                                                                
                                                                                                                                                                                         
        parts := make([]*storage.ObjectHandle, len(uploadedParts))                                                                                                                       
        for i, uploadedPart := range uploadedParts {                                                                                                                                     
                // TODO: verify attrs / ETag                                                                                                                                             
                parts[i] = l.client.Bucket(bucket).Object(toGCSMultipartKey(key, uploadID, uploadedPart.PartNumber))                                                                     
        }                                                                                                                                                                                
                                                                                                                                                                                         
        if len(parts) > 32 {                                                                                                                                                             
                // we need to split up the compose of more than 32 parts                                                                                                                 
                // into subcomposes. This means that the first 32 parts will                                                                                                             
                // compose to a composed-object-0, next parts to composed-object-1,                                                                                                      
                // the final compose will compose composed-object* to 1.                                                                                                                 
                return ObjectInfo{}, NotSupported{}                                                                                                                                      
        }
```

### PR DESCRIPTION
**Pull request by balamurugana**
GCS supports a final composed object of up to 32 component objects.
In support to complete multipart, every 32 parts are composed as
subcomposed objects and final object is composed using subcomposed
objects.

Fixes #4283

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by krishnasrinivas — COMMENTED** [review]
@balamurugana this will be simpler https://github.com/krishnasrinivas/minio/commit/e65a3e81dec4d55c9f08b110673cf61cab878abc

**Comment by balamurugana** [comment]
@krishnasrinivas 
> @balamurugana this will be simpler krishnasrinivas/minio@e65a3e8

If I understand your PR correctly, I thought about this logic as well ie
1. let P1 is list of given parts.
2. if len(P1) < 32; then stop; else continue
3. compose first 32 parts in P1 as one single part SP
4. Remove first 32 parts in P1 and add SP as first index in P1
5. Repeat step 2.

I thought the above logic would require some thinking to understand hence used simple approach and would ease for debugging in case of crashes.

if @krisis agrees on your patch, I will close this PR and you can submit yours.

**Comment by krishnasrinivas** [comment]
@balamurugana https://github.com/krishnasrinivas/minio/commit/d5b6412e858e26bc1b97dc0b25a48997c9e6941e

a refactor of your commit but without subcomposeCount and the outer for loop

**Review by krisis — APPROVED** [review]
LGTM. Tested locally with 2.3GB file and confirmed expected component count using `gsutil stat`.

**Review by krishnasrinivas — APPROVED** [review]
Could not test though.

**Review by harshavardhana — APPROVED** [review]
Tested it yesterday night works for 2GB+ upload.

**Pull request merged**
