### PR TITLE
Show pointer when user hovers over folder name

### LINKED ISSUE #6411: UI: Cursor doesn't change into a pointer on folder name hover
## Expected Behavior

On Minio Browser, when the user hovers over the folder name, it would be better for the cursor to change into a pointer (finger) to indicate that there is an action tied into the user's click on the folder name.

## Current Behavior

On Minio Browser, when the user hovers over the folder name, the cursor stays as the default cursor and doesn't change into a pointer. Please refer to the screenshot below:

folder

## Possible Solution

Change the CSS class associated with the folder only, using the `data-type` attribute

## Steps to Reproduce (for bugs)

1. Open Minio browser
2. Create a folder under a bucket
3. Hover over the folder name and verify the cursor doesn't change

## Context

This might be confusing for users as they might think the click might not lead anywhere or folders are not viewable because the cursor didn't change.

## Regression

Yes, regression of #6193.

## Your Environment

* Version used (`minio version`): latest
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by kaankabalak**
## Description

To indicate that there is an action tied when the user clicks on the
folder name on the Minio Browser, the default cursor has been replaced
with a pointer on folder name hover.

## Motivation and Context

Fixes #6411

## Regression

Yes, regression from #6193.

## How Has This Been Tested?

This commit has been tested manually by hovering over the folder name and verifying that the cursor turns into a pointer. The case where hovering over file names and not seeing the cursor change has also been tested.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by kanagarajkm — DISMISSED** [review]

**Review by rushenn — DISMISSED** [review]

**Comment by nitisht** [comment]
@kaankabalak could you please fix the conflicts

**Comment by kaankabalak** [comment]
@nitisht, just rebased and fixed the conflict

**Comment by nitisht** [comment]
Thanks @kaankabalak , Appveyor seems to fail now

**Comment by kaankabalak** [comment]
@nitisht, the Appveyor failure should be fixed now.

@kanagarajkm @rushenn, would appreciate if you could review for one last time just to be sure.

**Review by kanagarajkm — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#9fe14ec6-2159-4f55-a061-a94ce4529dba) |
<a name="9fe14ec6-2159-4f55-a061-a94ce4529dba"></a>
### 6412-c4ca565/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31515
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 153d701e022d:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 2 minutes and 48 seconds
(2/13) Running aws-sdk-go tests ... done in 2 seconds
(3/13) Running aws-sdk-java tests ... done in 4 seconds
(4/13) Running aws-sdk-php tests ... done in 56 seconds
(5/13) Running aws-sdk-ruby tests ... done in 37 seconds
(6/13) Running mc tests ... done in 7 minutes and 9 seconds
(7/13) Running minio-dotnet tests ... done in 6 minutes and 7 seconds
(8/13) Running minio-go tests ... FAILED in 7 minutes and 31 seconds
{
  "args": {
    "policy": "{\"expiration\":\"2018-09-16T19:59:45.138Z\",\"conditions\":[[\"eq\",\"$bucket\",\"minio-go-test-ko2cvl6m3fov2kqb\"],[\"eq\",\"$key\",\"j040f1p2yb1zv3ii9r12rerbbjoksp\"],[\"eq\",\"$Content-Type\",\"binary/octet-stream\"],[\"eq\",\"$x-amz-meta-4dkzu04c5jrsl1jx131v0n1pgcyuus\",\"mx9m0bwte6hpf2kbwcp05t3lkukyxs\"],[\"content-length-range\", 10, 1048576]]}"
  },
  "duration": 373,
  "error": "400 Bad Request",
  "function": "PresignedPostPolicy(policy)",
  "message": "Http request failed",
  "name": "minio-go: testPresignedPostPolicy",
  "status": "FAIL"
}

Executed 7 out of 13 tests successfully.
```

**Comment by nitisht** [comment]
Thanks @kaankabalak .

**Comment by nitisht** [comment]
ping @rushenn

**Review by rushenn — APPROVED** [review]

**Pull request merged**
