### PR TITLE
check if have free space before creating file

### PR DESCRIPTION
**Pull request by andreikop**
Check if having available space before writing file to the storage

## Description

This PR adds check for free space for PutObject PutObjectPart and CopyObject.

## Motivation and Context

We often face a situation when 
1. Files are written to minio until the storage is 100% full
2. Minio get's stopped
3. Minio refuses to start because of [this check](https://github.com/minio/minio/blob/master/cmd/fs-v1.go#L157)

It is impossible to start minio and delete some files from S3 to free space. The only way to get minio working again is mounting it's volume and manually deleting some files.

After this patch it will be still possible to get 100% full storage, i.e. by concurrent requests, but the probability is much less. Need to discuss, why minio refuses to start if FS is full. I'd prefer to have storage available for Read and Delete.

## How Has This Been Tested?

There are tests for PutObject and PutObjectPart.
I've tried to make a test for CopyObject, but it requres stateful storage backend mock and is much more complicated then the code itself.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

This patch decreases available storage capacity by `minFreeSpace`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Minio already uses `PrepareFIle()` API for this which should disallow any file creates if the i/o.. which version of Minio are you running? also are you using XL or Standalone FS backend?

**Comment by harshavardhana** [comment]
Can you validate this @vadmeste ?  current master v/s released Minio server?

**Comment by andreikop** [comment]
It seems like we are using version, which doesn't have `PrepareFile`, because we face 100 full disk.
I've tested master before patching it. The problem is reproducible. `PrepareFile` checks if disk is free before writing a file, but it doesn't check if available space would be critical after writing a file.
It should be possible to modify check in `PrepareFile`.

**Comment by andreikop** [comment]
I'd prefer closing this PR and merging #3606

**Comment by vadmeste** [comment]
FS is user friendly and can be started on the rootfs or C:\. Users can fill their drive with any possible stuffs and not always through Minio, so I think it is better to avoid checking free space at boot time as @andreikop suggested.

However, @andreikop if you think that the disk got filled with Minio itself, then this is another bug that need to be fixed.

**Comment by vadmeste** [comment]
@harshavardhana, with FS, when I have 1.6 Gb remaining in the disk space and I want to upload a 1GB file, the disk will get filled and out of space error will appear. It is probably because in FS, we need more space than expected (2 * 1 Gb ?)

**Comment by harshavardhana** [comment]
> @harshavardhana, with FS, when I have 1.6 Gb remaining in the disk space and I want to upload a 1GB file, the disk will get filled and out of space error will appear. It is probably because in FS, we need more space than expected (2 * 1 Gb ?)

Yes for multipart we will be using 2 * x - due to background concat operation. @vadmeste

**Comment by harshavardhana** [comment]
> I'd prefer closing this PR and merging #3606

Closing this PR.

**Pull request closed without merging**
