### PR TITLE
gateway/gcs: Complete minio browser support for gcs.

### LINKED ISSUE #4460: Browser support needed for GCS as well
Accessing policy preferences on browser uses object layer instead of gateway layer for GCS. The changes made for Azure and S3 need to be replicated for GCS as well.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

When accessing policy preferences on browser for GCS,  "invalid bucket name" error is displayed because the .minio.sys meta bucket name is used. Needs to access bucket policy on GCS to be accurate.
## Your Environment

* Version used (`minio version`):
Version: 2017-06-01T20:24:59Z
Release-Tag: DEVELOPMENT.2017-06-01T20-24-59Z
Commit-ID: 772a86d3e337aca732275f35943c48d55430394a

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
 
screen shot 2017-06-01 at 12 51 11 pm

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Complete minio browser support for gcs.

## Motivation and Context
Fixes #4460

## How Has This Been Tested?
Manually.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by poornas — CHANGES_REQUESTED** [review]
For GCS, the browser setting changes also needs to be disabled. Other than that tested, and looks good.

**Comment by harshavardhana** [comment]
> For GCS, the browser setting changes also needs to be disabled. Other than that tested, and looks good.

What does this mean? @poornas

**Comment by poornas** [comment]
@harshavardhana , since GCS uses project id, the accesskey /secretkey setting functionality on browser will do nothing meaningful. Azure and S3 disable it to prevent inadvertent changes to the keys on browser, think GCS should be consistent in this aspect as well.

**Review by krishnasrinivas — APPROVED** [review]

**Comment by krishnasrinivas** [comment]
@poornas password change is greyed out and disabled:


passwd

**Review by poornas — APPROVED** [review]

**Pull request merged**
