### PR TITLE
refactor admin rpc to use generic quorum package. 

### PR DESCRIPTION
**Pull request by balamurugana**
Depends on https://github.com/minio/minio/pull/5840

quorum package brings any functions to be executed in parallel using goroutines with maximum timeout and delta time to get maximum success replies.  Admin RPC client/server code is rewritten to accommodate to execute RPC methods in parallel.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5946-1b07dae/gopath/src/github.com/minio
+ git -C 5946-1b07dae/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5946-1b07dae/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5946-1b07dae/gopath/src/github.com/minio/minio fetch --quiet minio pull/5946/head:pr5946
+ git -C 5946-1b07dae/gopath/src/github.com/minio/minio checkout --quiet pr5946
+ GOPATH=/home/bala/mintauto/5946-1b07dae/gopath
+ make -C 5946-1b07dae/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/admin-handlers.go:709:34: cannot use err (type map["github.com/minio/minio/pkg/net".Host]error) as type error in argument to logger.LogIf:
	map["github.com/minio/minio/pkg/net".Host]error does not implement error (missing Error method)
make: *** [build] Error 2

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5946-69407ad/gopath/src/github.com/minio
+ git -C 5946-69407ad/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5946-69407ad/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5946-69407ad/gopath/src/github.com/minio/minio fetch --quiet minio pull/5946/head:pr5946
+ git -C 5946-69407ad/gopath/src/github.com/minio/minio checkout --quiet pr5946
+ GOPATH=/home/bala/mintauto/5946-69407ad/gopath
+ make -C 5946-69407ad/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/admin-handlers.go:709:34: cannot use err (type map["github.com/minio/minio/pkg/net".Host]error) as type error in argument to logger.LogIf:
	map["github.com/minio/minio/pkg/net".Host]error does not implement error (missing Error method)
make: *** [build] Error 2

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5946-ea4e8fb/gopath/src/github.com/minio
+ git -C 5946-ea4e8fb/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5946-ea4e8fb/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5946-ea4e8fb/gopath/src/github.com/minio/minio fetch --quiet minio pull/5946/head:pr5946
+ git -C 5946-ea4e8fb/gopath/src/github.com/minio/minio checkout --quiet pr5946
+ GOPATH=/home/bala/mintauto/5946-ea4e8fb/gopath
+ make -C 5946-ea4e8fb/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/admin-handlers.go:709:34: cannot use err (type map["github.com/minio/minio/pkg/net".Host]error) as type error in argument to logger.LogIf:
	map["github.com/minio/minio/pkg/net".Host]error does not implement error (missing Error method)
make: *** [build] Error 2

```

**Comment by kannappanr** [comment]
@balamurugana Can you please fix the build issues seen in Travis and Appveyor?

**Comment by krishnasrinivas** [comment]
```
func Call(functions []Func, quorum int, maxExecTime, maxSuccessWait time.Duration) (int, []error) {
```

here maxExecTime is the hard-deadline.
maxSuccessWait is a soft-deadline which is a small delta after `if success >= quorum {`

is `maxExecTime` hard-deadline needed? because POST based `rpc.Client` already has a hard deadline.

is this how `readAllXLMetadata()` will look when using the quorum package:
```
func readAllXLMetadata(ctx context.Context, disks []StorageAPI, bucket, object string, readQuorum int) ([]xlMetaV1, []error) {
        errs := make([]error, len(disks))
        metadataArray := make([]xlMetaV1, len(disks))
        var wg = &sync.WaitGroup{}

        quorumFunc := func(i int, disk StorageAPI) quorum.Func {
                return func() <-chan quorum.Error {
                        errCh := make(chan quorum.Error)

                        go func() {
                                defer close(errCh)
                                metadataArray[i], errs[i] = readXLMeta(ctx, disk, bucket, object)
                                if errs[i] != nil {
                                        errCh <- quorum.Error{disk.String(), errs[i]}
                                }
                        }()
                        return errCh
                }
        }

        for i, disk := range disks {
                errs[i] = errDiskNotFound
                if disk == nil {
                        continue
                }
                functions = append(functions, quorumFunc(i, disk))
        }
        callFunctions(functions, readQuorum, 5*time.Minute, 250*time.Millisecond, true)
        // Return all the metadata.
        return metadataArray, errs
}
```
if not, how will this function look like?

is this how `xl.PrepareFile()` look like when using quorum package:
```
func (xl xlObjects) prepareFile(ctx context.Context, bucket, object string, size int64, onlineDisks []StorageAPI, blockSize int64, dataBlocks, writeQuorum int) error {
        pErrs := make([]error, len(onlineDisks))
        // Calculate the real size of the part in one disk.
        actualSize := xl.sizeOnDisk(size, blockSize, dataBlocks)

        quorumFunc := func(index int, disk StorageAPI) quorum.Func {
                return func() <-chan quorum.Error {
                        errCh := make(chan quorum.Error)
                        go func() {
                                defer close(errCh)
                                pErrs[index] = disk.PrepareFile(bucket, object, actualSize)
                        }()
                        return errCh
                }
        }
        var functions []quorum.Func
        for index, disk := range onlineDisks {
                pErrs[index] = errDiskNotFound
                if disk == nil {
                        continue
                }
                functions = append(functions, quorumFunc(index, disk))
        }
        callFunctions(functions, writeQuorum, 5*time.Minute, 250*time.Millisecond, false)
        return reduceWriteQuorumErrs(ctx, pErrs, objectOpIgnoredErrs, writeQuorum)
}
```
if not how will it look?

**Comment by balamurugana** [comment]
`quorum` package does not know about `[]quorum.Func` are RPC calls or not.  It is a generic package provides functionality to wait for quorum success of given functions to complete i.e. not limiting to RPC clients.

`maxExecTime` is used to do maximum wait for quorum success.  If you have requirement to do infinite wait on quorum success, `maxExecTime` could be set as zero to ignore it; similarly for `maxSuccessWait` i.e. it will return immediately after quorum success.

If a requirement is to wait functions to complete infinitely without quorum, `sync.WaitGroup` is the right choice.

**Comment by krishnasrinivas** [comment]
@balamurugana 
AB asked to handle the timeout problem differently, not quorum package style.

Here is the high-level approach:
There will be only one deadline at the rpc layer. This deadline should be as small as possible. If a server is busy and not able to respond quickly then it should keep sending whitespaces till it can reply. The high level code that we have today will need no change. At the RPC layer, if a peer is sendig errors repeatedly we mark that rpc-client down so that any calls to it from higher layer can be responded with error immediately.

**Comment by balamurugana** [comment]
@krishnasrinivas quorum package is not related to timeout problem and is not the goal. even its not related to rpc calls.  I don't see a valid reason of not using quorum package.

**Comment by krishnasrinivas** [comment]
@balamurugana I see quorum package being useful only to ignore slow/unresponsive servers (and hence the relation to timeout)
So far I see only two calls where it can be useful: `admin.GetConfig()` and `readAllXLMetadata()` where  ignoring slow servers is not harmful to the functionality of minio.

Also AB said things like ServerInfo()/ListLocks etc admin calls should not be quorum based, instead it should collect data from all the servers.

I will check with AB if he can be on a call to discuss this.

**Comment by harshavardhana** [comment]
We should close this PR @balamurugana  @krishnasrinivas as per your discussion on this??

**Pull request closed without merging**
