### PR TITLE
Fix S3 Select request XML parsing

### PR DESCRIPTION
**Pull request by donatello**
## Motivation and Context

Fix bugs in request XML parsing found during developing a Haskell client.

## How Has This Been Tested?

Using the Haskell client and mc

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )

### CODE REVIEW

**Comment by poornas** [comment]
@donatello, came across one more bug with legacy SelectObjectContentRequest, perhaps your PR can include a fix for this as well
```
aws s3api select-object-content --debug --bucket tbucket11 --key "airlines.csv" --expression-type SQL --input-serialization '{"CSV":{}}' --output-serialization '{"CSV":{}}' --expression "SELECT * FROM S3Object" /tmp/outfile   && cat /tmp/outfile
```
body sent by awscli includes namespace and xml decoding fails with minio server because of this. 
```
<SelectObjectContentRequest xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><ExpressionType>SQL</ExpressionType><InputSerialization><CSV /></InputSerialization><Expression>SELECT * FROM S3Object</Expression><OutputSerialization><CSV /></OutputSerialization></SelectObjectContentRequest>
```

**Comment by donatello** [comment]
@poornas Thanks for reporting - could you check with aws cli and see if this PR now works?

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#1ac4bc33-9f04-41d6-8d7a-6a70936ea836) |
<a name="1ac4bc33-9f04-41d6-8d7a-6a70936ea836"></a>
### 7202-b499ea6/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31740
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0d53a6d1b3f0:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 0 seconds
(3/13) Running aws-sdk-php tests ... done in 42 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-0e6f241d69a2",
    "file_name": "datafile-1-MB"
  },
  "duration": 24.52,
  "error": "Connection reset by peer",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

**Comment by poornas** [comment]
> @poornas Thanks for reporting - could you check with aws cli and see if this PR now works?
yes it is working now @donatello

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#c3e58e13-7e7d-46f7-a8b2-d8c4f4118600) |
<a name="c3e58e13-7e7d-46f7-a8b2-d8c4f4118600"></a>
### 7202-44af09e/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30607
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1055d8cf89dd:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-0f1a4c36c992",
    "file_name": "datafile-1-MB"
  },
  "duration": 38.38,
  "error": "Expected to be created object does NOT exist",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#b6ccc0c7-0e40-4773-ad77-9cd96a4c8c23) |
<a name="b6ccc0c7-0e40-4773-ad77-9cd96a4c8c23"></a>
### 7202-4d0f041/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32607
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7c5cb494b06d:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 0 seconds
(3/13) Running aws-sdk-php tests ... done in 42 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-c5a05e62bc4a",
    "file_name": "datafile-1-MB"
  },
  "duration": 39.02,
  "error": "Expected to be created object does NOT exist",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

**Review by poornas — APPROVED** [review]
LGTM

**Pull request merged**
