### PR TITLE
Create Cors handler with permissive configuration

### LINKED ISSUE #7181: Unable to get the metadata for an object for browser based application
When using the `getObject` API from a browser based application using the `aws-sdk-js` the `metadata` field returned is empty. However using the same API from a non-browser based application, returns the appropriate metadata.

## Expected Behavior

The `getObject` API should have the same behavior across various `aws-sdk`s.

## Current Behavior

The SDK does not return the `metadata` for a browser based application.
## Possible Solution

On looking through the code and the behavior, we observed the following:
1. The CORS ExposedHeaders only returns a certain fixed set of headers, and does not acknowledge any metadata headers.
2. Even though the API returns the headers in the `x-amz-meta-*` headers, this header is not exposed, preventing the SDK to catch it.
3. If custom `exposedHeaders` can be set for a bucket this can be resolved.
## Steps to Reproduce (for bugs)

1. Upload an object to minio using the `putObject` API
2. Retrieve the object through a browser UI application using `getObject` API

## Context

We obfuscate the file name of the object stored on minio, and keep that in the metadata. A user with only the valid permissions can download the file, and on downlaod the file name should be the original file name.
## Regression

No
## Your Environment

* Version used (`minio version`): RELEASE.2019-01-10T00-21-20Z
* Environment name and version (e.g. nginx 1.9.1): kubernetes
* Server type and version: 
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
Create new Cors handler allowing all origins with all standard
methods with any header and credentials.

Fixes #7181

## Motivation and Context
Issue #7181 

## Regression
No

## How Has This Been Tested?
By creating an object with metadata and then creating a browser app to download that object.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#af658b18-ccd0-4d71-ae07-a8e2140f09f1) |
<a name="af658b18-ccd0-4d71-ae07-a8e2140f09f1"></a>
### 7186-a2348ce/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30912
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 977f2e2e1081:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 37 seconds
(2/13) Running aws-sdk-go tests ... done in 1 seconds
(3/13) Running aws-sdk-java tests ... done in 3 seconds
(4/13) Running aws-sdk-php tests ... done in 47 seconds
(5/13) Running aws-sdk-ruby tests ... done in 4 seconds
(6/13) Running mc tests ... done in 18 seconds
(7/13) Running minio-dotnet tests ... done in 4 minutes and 17 seconds
(8/13) Running minio-go tests ... done in 3 minutes and 23 seconds
(9/13) Running minio-java tests ... FAILED in 1 minutes and 48 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream body, long size, String contentType)",
  "args": "contentType: application/javascript",
  "duration": 79719,
  "status": "FAIL",
  "error": "java.net.SocketException: Connection reset >>> [java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115), java.net.SocketOutputStream.write(SocketOutputStream.java:155), okio.Okio$1.write(Okio.java:78), okio.AsyncTimeout$1.write(AsyncTimeout.java:179), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171), okio.RealBufferedSink.write(RealBufferedSink.java:41), okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171), okio.RealBufferedSink.write(RealBufferedSink.java:109), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:74), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185), okhttp3.RealCall.execute(RealCall.java:69), io.minio.MinioClient.executeReq(MinioClient.java:1097), io.minio.MinioClient.execute(MinioClient.java:1056), io.minio.MinioClient.executePut(MinioClient.java:1399), io.minio.MinioClient.executePut(MinioClient.java:1421), io.minio.MinioClient.putObject(MinioClient.java:3986), io.minio.MinioClient.putObject(MinioClient.java:4078), io.minio.MinioClient.putObject(MinioClient.java:3952), FunctionalTest.testPutObjectUnknownStreamSize(FunctionalTest.java:556), FunctionalTest.putObject_test8(FunctionalTest.java:582), FunctionalTest.runTests(FunctionalTest.java:2998), FunctionalTest.main(FunctionalTest.java:3154)]"
}

Executed 8 out of 13 tests successfully.
```

**Comment by harshavardhana** [comment]
Another sporadic windows failure

```
=== RUN   TestDisksWithAllParts
--- FAIL: TestDisksWithAllParts (2.21s)
    xl-v1-healing-common_test.go:302: Unexpected error cannot create Encoder with zero or less data/parity shards
    xl-v1-healing-common_test.go:306: Disk erroneously filtered, diskIndex: 3
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]
You can remove also this constant `defaultAllowableHTTPMethods`

**Review by Praveenrajmani — APPROVED** [review]

**Comment by kannappanr** [comment]
Ping @harshavardhana

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#2e581ed5-02ef-46c4-acf8-d248267c8f66) |
<a name="2e581ed5-02ef-46c4-acf8-d248267c8f66"></a>
### 7186-8dd647c/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30438
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 93c4919e4313:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPost(bucket_name,file_name,expires_in_sec,max_byte_size)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-2e5839a68517",
    "file_name": "datafile-1-MB",
    "expires_in_sec": 60,
    "max_byte_size": 3145728
  },
  "duration": 54.31,
  "error": "Expected to be created object does NOT exist",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

**Pull request merged**
