### PR TITLE
Accept forbidden as response code in health check

### PR DESCRIPTION
**Pull request by g-w**
## Description
minio response with a 403 during the healthcheck, if used with Google Cloud Storage and without the browser. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
We should disable GCS return 403 instead return 404 to be consistent.

**Comment by nitisht** [comment]
sent https://github.com/minio/minio/pull/5156 to fix gateway behaviour.

**Comment by nitisht** [comment]
This is blocked till further discussion on #5156

**Comment by nitisht** [comment]
@g-w we discussed internally and decided to implement a separate healthcheck endpoint . The Docker healthcheck script will be updated accordingly. 

Thank you for the PR and bringing this to our notice. But, we'll not be taking this approach, so closing this PR.

**Pull request closed without merging**
