### PR TITLE
Add CopyObjectPart support to gateway S3

### LINKED ISSUE #4885: [gateway-s3] CopyObjectPart is not implemented mint:minio-go test fails.
## Expected Behavior
CopyObjectPart should be implemented. 

## Current Behavior
```go
// CopyObjectPart copy part of object to other bucket and object                                                                                                            
 func (l *s3Objects) CopyObjectPart(srcBucket string, srcObject string, destBucket string, destObject string, uploadID string, partID int, startOffset int64, length int64) \
 (info PartInfo, err error) {                                                                                                                                                
         // FIXME: implement CopyObjectPart                                                                                                                                  
         return PartInfo{}, traceError(NotImplemented{})                                                                                                                     
 }                                                                                                                                                                           
 ```

## Possible Solution
Implement CopyObjectPart()

## Steps to Reproduce (for bugs)
Just run 
```
$ SERVER_ENDPOINT=10.0.0.13:9000 ACCESS_KEY=**** SECRET_KEY=**** ENABLE_HTTPS=0 go run functional_tests.go 
INFO[0000] Running functional tests for minio-go sdk....  file="functional_tests.go" function:=main.main line#=4261
INFO[0000]                                               file="functional_tests.go" function:=main.testMakeBucketErrorV2 line#=2480
INFO[0000] skipping region functional tests for non s3 runs  file="functional_tests.go" function:=main.testMakeBucketErrorV2 line#=2482
INFO[0000]                                               file="functional_tests.go" function:=main.testGetObjectClosedTwiceV2 line#=2528
INFO[0002]                                               file="functional_tests.go" function:=main.testRemovePartiallyUploadedV2 line#=2608
INFO[0003]                                               file="functional_tests.go" function:=main.testFPutObjectV2 line#=2675
INFO[0039]                                               file="functional_tests.go" function:=main.testMakeBucketRegionsV2 line#=2822
INFO[0039] skipping region functional tests for non s3 runs  file="functional_tests.go" function:=main.testMakeBucketRegionsV2 line#=2824
INFO[0039]                                               file="functional_tests.go" function:=main.testGetObjectReadSeekFunctionalV2 line#=2875
INFO[0042]                                               file="functional_tests.go" function:=main.testGetObjectReadAtFunctionalV2 line#=3012
INFO[0047]                                               file="functional_tests.go" function:=main.testCopyObjectV2 line#=3153
INFO[0051]                                               file="functional_tests.go" function:=main.testFunctionalV2 line#=3938
INFO[0061]                                               file="functional_tests.go" function:=main.testComposeObjectErrorCasesV2 line#=3375
INFO[0070]                                               file="functional_tests.go" function:=main.testCompose10KSourcesV2 line#=3440
FATA[0076] Error:Error in upload-part-copy - A header you provided implies functionality that is not implemented  file="functional_tests.go" function:=main.testComposeMultipleSources line#=3425
exit status 1
```

## Context
Testing release readiness.

## Your Environment
RELEASE.2017-09-01T19-22-40Z

### PR DESCRIPTION
**Pull request by donatello**
## Description

Fixes #4885

- Adds a metadata argument to the CopyObjectPart API to facilitate
  implementing encryption for copying APIs too.

- Update vendored minio-go - this version implements the
  CopyObjectPart client API for use with the S3 gateway.

## How Has This Been Tested?

Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by donatello** [comment]
This was tested using direct upload-part-copy API calls via the awscli tool.

**Comment by nitisht** [comment]
@donatello can you pls resolve conflicts

**Comment by harshavardhana** [comment]
Can you fix the conflicts here @donatello ?

**Comment by donatello** [comment]
@harshavardhana @nitisht this is rebased and ready for review.

**Review by harshavardhana — APPROVED** [review]
LGTM

**Review by nitisht — APPROVED** [review]

**Comment by nitisht** [comment]
Ignoring code cov due to gateway changes

**Pull request merged**
