### PR TITLE
Deletion of subfolders of multipart

### PR DESCRIPTION
**Pull request by sinhaashish**
Upon CompleteMultipartUpload, AbortMultipartUpload and cleanupStaleMultipartUploads

The subfolders of multipart were not getting deleted upon Complete multipart Upload and cleanUp of incomplete uploads after two weeks.
## Description

Inside multipart folder there is a folder created with the SHA of bucket + object and inside this folder there is another folder with name as ObjetcID.
At present in FS mode  the the files under the UploadID and the Upload ID folder gets deleted ; but the  blank SHA folder is present upon `CompleteMultipartUpload` and `cleanupStaleMultipartUploads`.
This PR calls the fsRemoveDir function to remove the blank folders of multipart with the name as SHA of bucket and object.

Things are fine for XL mode.

## Motivation and Context

Removes the folder under multi part 

Fixes the [issue](https://github.com/minio/minio/issues/6913)

## Regression

No

## How Has This Been Tested?

Checked the contents of `multipart` folder upon ` CompleteMultipartUpload` , `AbortMultipartUpload` and ` cleanupStaleMultipartUploads` both for `FS` and `XL` mode 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by krishnasrinivas — DISMISSED** [review]

**Comment by krisis** [comment]
What would happen when a NewMultipartUpload creating directories for a given bucket-object pair races with cleanupStaleMultipartUploads' removing (momentarily) empty directory for the same bucket-object pair? IIUC, these two go routines don't use any cooperative locking for a given bucket-object pair.

**Comment by krishnasrinivas** [comment]
@krisis NewMultipartUpload() will return error to the client, since it's a corner case and harmless (it does not corruption) we can ignore it. Currently multipart backend of fs is lock free and simple.

**Comment by krisis** [comment]
@krishnasrinivas  what error response would the client receive if the race happened? Can applications recover from that error programmatically?

**Comment by harshavardhana** [comment]
Client has no way to recover AFAICS. maybe it will return internal error.

**Comment by krisis** [comment]
So, shouldn't we take the mutex lock inside `cleanupStaleMultipartUploads` on the multipart upload ID which we intend to remove and fix the race?
@krishnasrinivas Do you see any issue with taking a lock inside `cleanupStaleMultipartUploads`?

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas what error response would the client receive if the race happened? Can applications recover from that error programmatically?

Applications will have to retry the failed operation (depending on what error we return to the client, I have not checked) the same way it retries for let's say a network disconnect issue.

> @krishnasrinivas Do you see any issue with taking a lock inside cleanupStaleMultipartUploads?

Yes there is a problem because posix does not have lock semantics for directories. (needed for NFS)

A simpler fix is to retry the MkDir() if it fails during NewMultipart, but it is better to just ignore the case as the downside of this race condition does not cause any corruption and also unlikely to be seen in real world.

**Comment by krisis** [comment]
> Yes there is a problem because posix does not have lock semantics for directories. (needed for NFS)

OK, so then I am OK with taking this PR as is, since it solves an existing problem.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by krisis — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
