### PR TITLE
Remove B2 gateway implementation

### LINKED ISSUE #8584: Bacula / MINIO / Backblaze -- unstable
Trying to use Bacula with MINIO with Backblaze as the backend.  Uploading 10MB files and have problems (uploads fail) even with small data sets.

## Expected Behavior

Files should upload without error.

## Current Behavior

Only some files upload without error.

## Steps to Reproduce (for bugs)

Using MinIO/RELEASE.2019-10-12T01-39-57Z, Bacula 9.4.4, on CentOS 7.7.  Run MinIO in gateway mode connecting to backblaze.  Using sporadic "mc" commands seems to work, as does using the MinIO web interface.  Bacula is configured for cloud storage.  Bacula is configured to break up files into 10MB parts for uploading.  The daily backup fails almost daily uploading all the parts.  A rough guess would be that 85% of the parts upload without error.

1.
2.
3.
4.

## Context

I would like to use MinIO as a gateway between bacula and Backblaze and to use Backblaze storage for backups.

## Regression

No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
Information about environment provided above.

* Trace Log (Error): Edited to hide personal Information.
myalias [REQUEST s3.PutObject] 23:15:34.598
myalias PUT /Bucket/B2-Vol-1110/part.7
myalias Host: localhost:9000
myalias User-Agent: Mozilla/4.0 (Compatible; s3; libs3 3.0; Linux x86_64)
myalias X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
myalias X-Amz-Date: 20191127T231534Z
myalias Accept: */*
myalias Authorization: AWS4-HMAC-SHA256 Credential=xxxxxxxxxxxxxxxxxxxxxxxxx/20191127/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=a3bd80eef472541976daccc317522a2aefaf43400b2ba85a3a79c350bf100d93
myalias Content-Length: 10450944
myalias Expect: 100-continue
myalias <BODY>
myalias [RESPONSE] [23:18:04.388] [ Duration 2m29.790482s  🠉 3.8 MiB  🠋 628 B ]
myalias 500 Internal Server Error
myalias Content-Security-Policy: block-all-mixed-content
myalias Content-Type: application/xml
myalias Server: MinIO/RELEASE.2019-10-12T01-39-57Z
myalias Vary: Origin
myalias X-Amz-Request-Id: 15DB280DD6B647F8
myalias X-Xss-Protection: 1; mode=block
myalias Accept-Ranges: bytes
myalias Content-Length: 359
myalias <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key>B2-Vol-1110/part.7</Key><BucketName>Bucket</BucketName><Resource>/Bucket/B2-Vol-1110/part.7</Resource><RequestId>15DB280DD6B647F8</RequestId><HostId>0fffffff-0000-000f-0000-00ff000ff000</HostId></Error>
myalias
myalias [REQUEST s3.PutObject] 23:21:23.049
myalias PUT /Bucket/B2-Vol-1110/part.19
myalias Host: localhost:9000
myalias Expect: 100-continue
myalias User-Agent: Mozilla/4.0 (Compatible; s3; libs3 3.0; Linux x86_64)
myalias X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
myalias X-Amz-Date: 20191127T232123Z
myalias Accept: */*
myalias Authorization: AWS4-HMAC-SHA256 Credential=xxxxxxxxxxxxxxxxxxxxxxxxx/20191127/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=c828081c642d7b3a22ea6ae289bf261dcad2dad4aec58b7839e6299f72c7418b
myalias Content-Length: 10450944
myalias <BODY>
myalias [RESPONSE] [23:22:09.666] [ Duration 46.617462s  🠉 950 KiB  🠋 630 B ]
myalias 500 Internal Server Error
myalias Content-Type: application/xml
myalias Server: MinIO/RELEASE.2019-10-12T01-39-57Z
myalias Vary: Origin
myalias X-Amz-Request-Id: 15DB285EF805508E
myalias X-Xss-Protection: 1; mode=block
myalias Accept-Ranges: bytes
myalias Content-Length: 361
myalias Content-Security-Policy: block-all-mixed-content
myalias <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key>B2-Vol-1110/part.19</Key><BucketName>Bucket</BucketName><Resource>/Bucket/B2-Vol-1110/part.19</Resource><RequestId>15DB285EF805508E</RequestId><HostId>0fffffff-0000-000f-0000-00ff000ff000</HostId></Error>
myalias
*

It is unclear is this a a bacula problem, a MinIO problem, a Backblaze problem, or an ISP problem.  As the above trace log is from MinIO this issue is being reported here.

Thank You.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Remove B2 gateway implementation

## Motivation and Context
S3 is now natively supported by B2 cloud storage provider
there is no reason to use the specialized gateway for B2 anymore,
our current S3 gateway with caching would work with B2.

Resolves #8584

## How to test this PR?
Nothing to test check if all references to B2 are gone.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by krishnasrinivas — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#d7c5e689-f5b8-4bec-ab66-c04a0854b1e6) |
| mint-gateway-azure.sh | :x: [more...](#69d2fb80-ba2e-4830-a246-9eab61c34a96) |
| mint-gateway-nas.sh | :x: [more...](#0f87615a-4983-4544-84ce-f95f1cb408dc) |
<a name="69d2fb80-ba2e-4830-a246-9eab61c34a96"></a>
### 9547-3793186/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31948
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ef1e70503110:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 10 minutes and 47 seconds
(4/15) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 3 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 242569.94,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}
(4/15) Running awscli tests ... FAILED in 49 seconds
{
  "name": "awscli",
  "duration": 3630,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31948 s3api copy-object --bucket awscli-mint-test-bucket-16872 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-16872/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(4/15) Running healthcheck tests ... done in 0 seconds
(5/15) Running mc tests ... done in 3 minutes and 53 seconds
(6/15) Running minio-dotnet tests ... done in 3 minutes and 6 seconds
(7/15) Running minio-go tests ... FAILED in 4 minutes and 33 seconds
{}
(7/15) Running minio-java tests ... FAILED in 30 minutes and 59 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1749,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-25b5bh1, objectName = minio-java-test-2hkqi5g, resource = /minio-java-test-25b5bh1/minio-java-test-2hkqi5g, requestId = 160CF80464098BF8, hostId = 8cc16f0d-fb3d-486e-a3fb-3206bd6875ef)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31948/minio-java-test-25b5bh1/minio-java-test-2hkqi5g?legal-hold=, headers=Host: minio-dev6.minio.io:31948\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200508T055746Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200508/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CF80464098BF8\nX-Xss-Protection: 1; mode=block\nDate: Fri, 08 May 2020 05:57:46 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(7/15) Running minio-js tests ... done in 8 minutes and 59 seconds
(8/15) Running minio-py tests ... done in 12 minutes and 59 seconds
(9/15) Running s3cmd tests ... FAILED in 1 minutes and 4 seconds
{
  "name": "s3cmd",
  "duration": "2186",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(9/15) Running s3select tests ... done in 22 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="d7c5e689-f5b8-4bec-ab66-c04a0854b1e6"></a>
### 9547-3793186/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32215
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9b485a2f9016:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 4417,
  "function": "aws --endpoint-url http://minio-dev3.minio.io:32215 s3api get-object --bucket awscli-mint-test-bucket-8001 --key awscli-mint-test-bucket-8001-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "Etag mismatch for multipart 0 byte object"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 17 seconds
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... FAILED in 39 seconds
{}
(8/15) Running minio-java tests ... FAILED in 37 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 84,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-1jeegne, objectName = minio-java-test-1u558cs, resource = /minio-java-test-1jeegne/minio-java-test-1u558cs, requestId = 160CF5018FEB70C8, hostId = b01e4d5e-b443-4967-8443-8d6f20d0083b)\nrequest={method=PUT, url=http://minio-dev3.minio.io:32215/minio-java-test-1jeegne/minio-java-test-1u558cs?legal-hold=, headers=Host: minio-dev3.minio.io:32215\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200508T050235Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200508/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CF5018FEB70C8\nX-Xss-Protection: 1; mode=block\nDate: Fri, 08 May 2020 05:02:35 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... done in 49 seconds
(9/15) Running minio-py tests ... done in 1 minutes and 5 seconds
(10/15) Running s3cmd tests ... done in 1 minutes and 3 seconds
(11/15) Running s3select tests ... done in 1 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="0f87615a-4983-4544-84ce-f95f1cb408dc"></a>
### 9547-3793186/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31573
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 066d55caa698:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 34 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... FAILED in 55 seconds
{}
(9/15) Running minio-java tests ... FAILED in 24 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 35,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-3dqmfpg, objectName = minio-java-test-17p7blq, resource = /minio-java-test-3dqmfpg/minio-java-test-17p7blq, requestId = 160CF5119C22323F, hostId = c0897daf-84f8-4e58-9dac-3f3c9c4e9b0c)\nrequest={method=PUT, url=http://minio-dev4.minio.io:31573/minio-java-test-3dqmfpg/minio-java-test-17p7blq?legal-hold=, headers=Host: minio-dev4.minio.io:31573\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200508T050344Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200508/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CF5119C22323F\nX-Xss-Protection: 1; mode=block\nDate: Fri, 08 May 2020 05:03:44 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 36 seconds
(10/15) Running minio-py tests ... done in 58 seconds
(11/15) Running s3cmd tests ... done in 19 seconds
(12/15) Running s3select tests ... done in 0 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by jglopez** [comment]
Hi guys, 
I just wanted to let you know I noticed Backblaze is still listed as an Integration under _Hybrid Cloud_ at: 
https://min.io/product/integrations#hybrid-cloud

**Comment by harshavardhana** [comment]
> Hi guys,
> I just wanted to let you know I noticed Backblaze is still listed as an Integration under _Hybrid Cloud_ at:
> https://min.io/product/integrations#hybrid-cloud

We shall remove it @jglopez

**Pull request merged**
