### PR TITLE
Fix PUT bucket notification deadlocks

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This PR fixes two different variants of deadlocks in
notification.

## Motivation and Context
- holding write lock on the bucket competing with read lock
- holding competing locks on read/save notification config

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#4ee2a7a4-f71e-41e6-a3b8-85841ffd8f58) |
<a name="4ee2a7a4-f71e-41e6-a3b8-85841ffd8f58"></a>
### 5734-151b56f/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31634
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 94a719cc6d2d:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 6 minutes and 1 seconds
{
  "name": "aws-sdk-php",
  "function": "createMultipartUpload ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5abcbe4b492a9",
    "Object": "obj1"
  },
  "duration": "1489",
  "status": "FAIL",
  "error": "Error executing \"UploadPart\" on \"http://minikube:31634/aws-sdk-php-5abcbe4b492a9/obj1?uploadId=1ae25b857a9c40d998a2530ba4f2fd10&partNumber=1\"; AWS HTTP error: Client error: `PUT http://minikube:31634/aws-sdk-php-5abcbe4b492a9/obj1?uploadId=1ae25b857a9c40d998a2530ba4f2fd10&partNumber=1` resulted in a `404 Not Found` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not  (truncated...)\n NoSuchUpload (client): The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.</Message><Key></Key><BucketName></BucketName><Resource>/aws-sdk-php-5abcbe4b492a9/obj1</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>"
}

Executed 1 out of 12 tests successfully.
```

**Review by balamurugana — COMMENTED** [review]
Yep.  This issue I found few days ago.

LGTM

**Review by nitisht — APPROVED** [review]
LGTM and tested with Get & Put requests

**Review by donatello — APPROVED** [review]

**Comment by solsson** [comment]
Confirmed, fixed my issue with hanging `mc events add` in distributed mode.

**Pull request merged**
