### PR TITLE
build: Reduce binary size by using -s -w

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Reduce binary size for all minio source builds through `make`

## Motivation and Context
Refer #3939

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Upx needs to be done by the minio-release tool.

**Review by donatello — APPROVED** [review]
Looks good - I see the binary decreasing in size from 27MB to 17MB with this change.

I checked if log statements printing their source line is affected by removing either symbol table/DWARF symbols - it does not affect them.

So LGTM.

**Comment by harshavardhana** [comment]
> Looks good - I see the binary decreasing in size from 27MB to 17MB with this change.
> 
> I checked if log statements printing their source line is affected by removing either symbol table/DWARF symbols - it does not affect them.

Yes next step is upx 

```
$ upx --brute minio
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  17191936 ->   4303540   25.03%  linux/ElfAMD   minio                         

Packed 1 file.
$ du -sh minio
4.2M	minio
```

**Comment by vadmeste** [comment]
Shouldn't we check performance penalty after reducing size ?

**Comment by harshavardhana** [comment]
> Shouldn't we check performance penalty after reducing size ?

What performance penalty?

**Comment by vadmeste** [comment]
> Shouldn't we check performance penalty after reducing size ?
> What performance penalty?

Reducing size has usually impact on speed performance, but I see here that we are passing -s parameter to the linker and not compiler, so this is OK.

**Pull request merged**
