### PR TITLE
fix: disk healing should honor the right pool/set index

### LINKED ISSUE #16664: minio[28768]: Error: Following error has been printed 3 times.. context canceled (*fmt.wrapError)
Hello,

the minio reports continuously (each few minutes) some cryptic error log: "Following error has been printed 3 times.. context canceled":
```
minio[28768]: Time: 06:01:31 UTC 02/20/2023
minio[28768]: DeploymentID: c31ec917-cdb3-4ca8-8050-6190991fc03d
minio[28768]: Error: Following error has been printed 3 times.. context canceled (*fmt.wrapError)
minio[28768]:        endpoint="https://minio01n22.int.na.prodgdc.com:443/mnt/ebs/minio4"
minio[28768]:        3: internal/logger/logger.go:248:logger.LogAlwaysIf()
minio[28768]:        2: cmd/prepare-storage.go:62:cmd.glob..func7.1()
minio[28768]:        1: cmd/background-newdisks-heal-ops.go:452:cmd.monitorLocalDisksAndHeal.func1()
```
I expect this message is just a info that healing of new disks is not done yet based on the code "cmd/background-newdisks-heal-ops.go:452" , I'm right? Why to report it continuously in logs this as error and have nonsense message like "Error printed 3 times"?

## Expected Behavior
The new disk healing is in progress (or at least I hope it going forward) so there is no reason to continuosly report some error message without related content.

## Current Behavior
I have full log of  "Error: Following error has been printed 3 times.. context canceled (*fmt.wrapError)" when healing of new disks is running.

## Steps to Reproduce (for bugs)
1. change server by new with no data at disks
2. see log of minio service

## Your Environment
* Version used 
minio version RELEASE.2023-02-17T17-52-43Z (commit-id=84bb7d05a998a096b96acd68ea94053d28a87eb3)
Runtime: go1.19.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

* Server setup:
Two pools, each pool of 16 servers, each server 4 disks.

* Operating System and version:
CentOS 9 Stream

### LINKED ISSUE #16666: Background healing newer finish when changing server by new.
Hello

I'm observing strange behaviour of background healing when changing server fleet of minio service. The background healing newer finish for us and I need to force it by some manual "tricks" (restarting services repeatedly, running multiple time "mc admin heal -r alias").

Can you please check what is wrong with the healing in minio? I can easily reproduce it and run test as needed.

## Expected Behavior
* Change server by new with empty disks,
* background healing is running by "constant speed" and finish without manual operation tasks.

## Current Behavior
I would like to show it of attached "[healing.png](https://drive.google.com/file/d/19ro1nQh6MxICRKZ6WjiieJ5peVkUtgoD/view?usp=sharing)" graph. The graph reports how the disk are filled so it shows how healing is working in time:
0 - The healing is expected to finish when disks are having ~2TiB of free space.
1 - One server is replaced with new disks in each Minio pool (the disk are empty and havin ~4 TiB free)
2 - Background healing starts for almost all disks == OK
3 - Few disks do not start healing == WRONG
4 - The haling stops at ~3TiB for all disks == WRONG
now I need to manually restart the minio service  ```minio admin service alias restart```
5 - The few disks from (step 3) start to heal, but not all (disks from step4) == WRONG
after few hours later it stops the helaing of all disks again, the space free us still about ~3TiB.
6 - I have to run ```minio admin heal -r alias``` to enforce healing.

## Steps to Reproduce (for bugs)
1. Replace minio server in a pool by new with empty disks. 
2. Wait and observe storage usage by healing process. It shows "Estimated: 1 day" for few hours.
3. The healing stops to fill disks after few hours and the estimated healing time of disks start to grow like to days at first, then grows to months.

## Context

How has this issue affected you?
* Healings of new disks newer finish automatically. We must run manual restarts of service and run foreground healing process repeatedly (manually).

## Your Environment

* Version used 
minio version RELEASE.2023-02-17T17-52-43Z (commit-id=84bb7d05a998a096b96acd68ea94053d28a87eb3)
Runtime: go1.19.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

* Server setup:
Two pools, each pool of 16 servers, each server 4 disks.

* Operating System and version:
CentOS 9 Stream

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: disk healing should honor the right pool/set index

## Motivation and Context
fixes #16664
fixes #16666

## How to test this PR?
As per #16666 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#50e1d1ac-13a7-4c3c-a69e-9208174dfe60) |
<a name="50e1d1ac-13a7-4c3c-a69e-9208174dfe60"></a>
### 16712-2e522e4/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:30019
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 1f8323608501:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 10 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-go tests ... done in 58 seconds
(9/14) Running minio-java tests ... done in 37 seconds
(10/14) Running minio-js tests ... FAILED in 4 minutes and 2 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 130804,
  "status": "FAIL",
  "error": "Error: connect ETIMEDOUT 15.15.15.6:30019 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)"
}
(10/14) Running minio-py tests ... FAILED in 2 minutes and 7 seconds
{
  "name": "minio-py:test_make_bucket_default_region",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-a7c699df-8755-425c-b79f-7143c3e7ebfb",
    "location": "default value ('us-east-1')"
  },
  "message": "S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /minio-py-test-a7c699df-8755-425c-b79f-7143c3e7ebfb, request_id: 17474E8FC1E622CE, host_id: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, bucket_name: minio-py-test-a7c699df-8755-425c-b79f-7143c3e7ebfb",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 168, in test_make_bucket_default_region\n    _call(log_entry, _CLIENT.make_bucket, bucket_name)\n  File \"/mint/run/core/minio-py/tests.py\", line 109, in _call\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 618, in make_bucket\n    self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 386, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /minio-py-test-a7c699df-8755-425c-b79f-7143c3e7ebfb, request_id: 17474E8FC1E622CE, host_id: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, bucket_name: minio-py-test-a7c699df-8755-425c-b79f-7143c3e7ebfb\n",
  "function": "make_bucket(bucket_name, location, object_lock)",
  "duration": 127287
}
(10/14) Running s3cmd tests ... FAILED in 1 minutes and 51 seconds
{
  "name": "s3cmd",
  "duration": "110317",
  "function": "test_make_bucket",
  "status": "FAIL",
  "error": "WARNING: Retrying failed request: / (500 (InternalError): We encountered an internal error, please try again.: cause(remove /data/pools0/s3cmd-test-bucket-17842: read-only file system))\nWARNING: Waiting 3 sec...\nWARNING: Retrying failed request: / (500 (InternalError): We encountered an internal error, please try again.: cause(remove /data/pools0/s3cmd-test-bucket-17842: read-only file system))\nWARNING: Waiting 6 sec...\nWARNING: Retrying failed request: / (500 (InternalError): We encountered an internal error, please try again.: cause(remove /data/pools0/s3cmd-test-bucket-17842: read-only file system))\nWARNING: Waiting 9 sec...\nWARNING: Retrying failed request: / (500 (InternalError): We encountered an internal error, please try again.: cause(remove /data/pools0/s3cmd-test-bucket-17842: read-only file system))\nWARNING: Waiting 12 sec...\nWARNING: Retrying failed request: / (500 (InternalError): We encountered an internal error, please try again.: cause(remove /data/pools0/s3cmd-test-bucket-17842: read-only file system))\nWARNING: Waiting 15 sec...\nERROR: S3 error: 500 (InternalError): We encountered an internal error, please try again.: cause(remove /data/pools0/s3cmd-test-bucket-17842: read-only file system)"
}
(10/14) Running s3select tests ... FAILED in 2 minutes and 0 seconds
{
  "name": "s3select:test_csv_input_quote_char",
  "function": "select_object_content(bucket_name, object_name, request)",
  "args": {
    "bucket_name": "s3select-test-69b20cf5-8781-47c5-b657-42e6f08e4955"
  },
  "duration": 120160,
  "message": "S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /s3select-test-69b20cf5-8781-47c5-b657-42e6f08e4955, request_id: 17474EC59599CAFB, host_id: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, bucket_name: s3select-test-69b20cf5-8781-47c5-b657-42e6f08e4955",
  "error": "Traceback (most recent call last):\n  File \"./tests.py\", line 53, in main\n    test_csv_input_custom_quote_char(client, log_output)\n  File \"/mint/run/core/s3select/csv.py\", line 95, in test_csv_input_custom_quote_char\n    client.make_bucket(bucket_name)\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 618, in make_bucket\n    self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 386, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /s3select-test-69b20cf5-8781-47c5-b657-42e6f08e4955, request_id: 17474EC59599CAFB, host_id: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, bucket_name: s3select-test-69b20cf5-8781-47c5-b657-42e6f08e4955\n",
  "status": "FAIL"
}
(10/14) Running versioning tests ... FAILED in 32 minutes and 43 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-1xqtdizh6jn2l9"
  },
  "duration": 1962504,
  "function": "/mint/build/versioning/main.go:79: main.cleanupBucket",
  "message": "Unable to cleanup bucket after compliance tests",
  "name": "versioning",
  "status": "FAIL"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#50d275e2-a89c-4259-abe4-b18b3464ed9a) |
<a name="50d275e2-a89c-4259-abe4-b18b3464ed9a"></a>
### 16712-2584049/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.5:32293
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 52950da9c9dc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 14 seconds
(8/14) Running minio-go tests ... done in 56 seconds
(9/14) Running minio-java tests ... FAILED in 6 minutes and 17 seconds
{
  "name": "minio-java",
  "function": "getObject()",
  "args": "[single upload, offset]",
  "duration": 300011,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: timeout >>> [okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147), okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158), okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:337), okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320), okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29), okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 46 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 31 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 8 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by Praveenrajmani — APPROVED** [review]
Tested and LGTM

**Review by kanagarajkm — APPROVED** [review]

**Comment by igor-raits** [comment]
@harshavardhana @kanagarajkm @Praveenrajmani would it be possible to cut new release of minio that includes this fix please? Thanks in advance, much appreciated!

**Comment by harshavardhana** [comment]
> @harshavardhana @kanagarajkm @Praveenrajmani would it be possible to cut new release of minio that includes this fix please? Thanks in advance, much appreciated!

@ignatenkobrain we will soon.

**Pull request merged**
