### PR TITLE
verify: add minio gateway s3 setup for verification tests

### PR DESCRIPTION
**Pull request by balamurugana**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by poornas** [comment]
@balamurugana , s3 gateway test fails here for mc watch 
```
Testing in Gateway S3 setup
{"name": "mc", "duration": "178", "function": "test_make_bucket", "status": "PASS"}
{"name": "mc", "duration": "613", "function": "test_put_object", "status": "PASS"}
{"name": "mc", "duration": "30200", "function": "test_put_object_multipart", "status": "PASS"}
{"name": "mc", "duration": "791", "function": "test_get_object", "status": "PASS"}
{"name": "mc", "duration": "29257", "function": "test_get_object_multipart", "status": "PASS"}
{"name": "mc", "duration": "754", "function": "test_presigned_put_object", "status": "PASS"}
{"name": "mc", "duration": "693", "function": "test_presigned_get_object", "status": "PASS"}
{"name": "mc", "duration": "701", "function": "test_cat_object", "status": "PASS"}
{"name": "mc", "duration": "26594", "function": "test_mirror_list_objects", "status": "PASS"}
/home/kris/code/src/github.com/minio/minio/.verify-3319/functional-tests.sh: line 371: kill: (20727) - No such process
{"name": "mc", "duration": "2596", "function": "test_watch_object", "status": "FAIL", "error": ""ObjectCreated event not found\n""}

Endpoint:  http://192.168.1.157:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
```

**Comment by balamurugana** [comment]
@poornas Yep. Because notification is not supported in S3 gateway

**Comment by poornas** [comment]
@balamurugana , if that is the case shouldn't we ignore the failure and have the overall run status reflect this as a success?

**Comment by harshavardhana** [comment]
> @poornas Yep. Because notification is not supported in S3 gateway

Actually does ListenBucketNotification return NotImplemented in this case? @balamurugana @poornas - if yes we can ignore it.

**Comment by balamurugana** [comment]
Yes. Server returns `Not Implemented`

**Review by poornas — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
