### PR TITLE
gateway: add single encryption at s3 gateway

### PR DESCRIPTION
**Pull request by poornas**
## Description

Currently new feature #6423 adds double encryption at gateway or pass through encryption. Adding an option to turn on encryption at gateway without passing sse headers to backend. 

A new env variable MINIO_GW_SSE_MODE="backend;gateway" will allow setting encryption mode - "backend" will pass SSE headers to s3 backend, "gateway" to enable encryption at gateway and both can be specified delimited by ";" to turn on double encryption

## Motivation and Context

Allows flexibility in modes of operating.
## Regression
 No

## How Has This Been Tested?

Manually by setting MINIO_GW_SSE_MODE="gateway" and MINIO_GW_SSE="C;S3" and KMS settings enabled.
Run  MINIO_HTTP_TRACE=/dev/stdout ./minio gateway s3
  - all operations GET/PUT/Copy should be encrypted at the gateway only, and sse headers should not be forwarded to backend.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Just create one patch for new-features branch and pulling the latest. Always update it like master i.e rebase your changes on the latest.

In this PR this is not done with repeated commits.

**Comment by poornas** [comment]
updated PR

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
LGTM tested works.

**Pull request merged**
