### PR TITLE
update the blake2b implementation

### LINKED ISSUE #24: Speed vs. "Optimized" codahale version?
Per chance have you run speed comparisons vs. the other common implementation of blake2b?

### PR DESCRIPTION
**Pull request by aead**
Fixes a performance bug caused by SSE-AVX register savings on amd64.

Fixes minio/blake2b-simd#24

## Motivation and Context
Fixes the performance problems detected at [blake2b-simd](https://github.com/minio/blake2b-simd/issues/24)

## How Has This Been Tested?
`go test -v`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aead** [comment]
Sry for this long delay. The golang review took some time...

**Comment by harshavardhana** [comment]
> Sry for this long delay. The golang review took some time...

No problem @aead we can take this in now.

**Comment by aead** [comment]
> No problem @aead we can take this in now.

Ok, great :smile:
I'll close the [issue](https://github.com/minio/blake2b-simd/issues/24) if the PR is okay...

**Comment by harshavardhana** [comment]
> Ok, great 
> I'll close the issue if the PR is okay...

:+1:

**Review by harshavardhana — APPROVED** [review]

**Comment by fwessels** [comment]
LGTM

**Review by fwessels — APPROVED** [review]

**Pull request merged**
