### PR TITLE
[proposal] Support creating empty directories.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Every so often we get requirements for creating
directories/prefixes and we end up rejecting
such requirements. This PR is a propoal to show
that its possible to in-fact have empty directories
and be able to manage them like without much
backend format changes etc.

Two new additional APIs were implemented on StorageAPI
layer to facilitate this for distributed and standalone
erasure coded backend.

- DeletePrefix(vol, prefix)
- MakePrefix(vol, prefix)

DeletePrefix() deletes prefix and also its parent directories
if they are empty just like how DeleteFile() does.

MakePrefix() creates prefix all the time as if overwriting it
also creates all the top level directories as well along the
way. Behavior is similar to `mkdir -p`

## Motivation and Context
More S3 compatibility. 

## How Has This Been Tested?
Manually and using `go test` 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
This needs to be blocked @deekoder until we discuss with @abperiasamy

**Comment by krishnasrinivas** [comment]
Waiting for confirmation if this is :+1:  from @abperiasamy

**Comment by harshavardhana** [comment]
I explored many ways to do this locally for erasure coding as well but it won't work since an empty directory without `xl.json` is considered as object that needs healing. Currently we can only support FS but it would lead to a different backend behavior for erasure coding if we are okay with allowing FS to look like gateway mode. 

We need to discuss this since having this feature has sort of lot of benefits, we will be able to support large number of use cases.

**Comment by harshavardhana** [comment]
Closing this as not needed for now.

**Pull request closed without merging**
