### PR TITLE
Update minio-go dependencies to latest 5.0.0 release

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Update minio-go dependencies to latest 5.0.0 release

## Motivation and Context
    With following changes
    
    - Add SSE and refactor encryption API (#942) <Andreas Auernhammer>
    - add copyObject test changing metadata and preserving etag (#944) <Harshavardhana>
    - Add SSE-C tests for multipart, copy, get range operations (#941) <Harshavardhana>
    - Removing conditional check for notificationInfoCh in api-notication (#940) <Matthew Magaldi>
    - Honor prefix parameter in ListBucketPolicies API (#929) <kannappanr>
    - test for empty objects uploaded with SSE-C headers (#927) <kannappanr>
    - Encryption headers should also be set during initMultipart (#930) <Harshavardhana>
    - Add support for Content-Language metadata header (#928) <kannappanr>
    - Fix check for duplicate notification configuration entries (#917) <kannappanr>
    - allow OS to cleanup sockets in TIME_WAIT (#925) <Harshavardhana>
    - Sign V2: Fix signature calculation in virtual host style (#921) <A. Elleuch>
    - bucket policy: Support json string in Principal field (#919) <A. Elleuch>
    - Fix copyobject failure for empty files (#918) <kannappanr>
    - Add new constructor NewWithOptions to SDK (#915) <poornas>
    - Support redirect headers to sign again with new Host header. (#829) <Harshavardhana>
    - Fail in PutObject if invalid user metadata is passed <Harshavadhana>
    - PutObjectOptions Header: Don't include invalid header <Isaac Hess>
    - increase max retry count to 10 (#913) <poornas>
    - Add new regions for Paris and China west. (#905) <Harshavardhana>
    - fix s3signer to use req.Host header (#899) <Bartłomiej Nogaś>

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5640-c405f4c/gopath/src/github.com/minio
+ git -C 5640-c405f4c/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5640-c405f4c/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5640-c405f4c/gopath/src/github.com/minio/minio fetch --quiet minio pull/5640/head:pr5640
+ git -C 5640-c405f4c/gopath/src/github.com/minio/minio checkout --quiet pr5640
+ GOPATH=/home/bala/mintauto/5640-c405f4c/gopath
+ make -C 5640-c405f4c/gopath/src/github.com/minio/minio --quiet
vendor/github.com/minio/minio-go/pkg/credentials/file_aws_credentials.go:25:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
	/home/bala/mintauto/5640-c405f4c/gopath/src/github.com/minio/minio/vendor/github.com/mitchellh/go-homedir (vendor tree)
	/home/bala/golang/goroot/src/github.com/mitchellh/go-homedir (from $GOROOT)
	/home/bala/mintauto/5640-c405f4c/gopath/src/github.com/mitchellh/go-homedir (from $GOPATH)
vendor/github.com/minio/minio-go/pkg/encrypt/server-side.go:26:2: cannot find package "golang.org/x/crypto/argon2" in any of:
	/home/bala/mintauto/5640-c405f4c/gopath/src/github.com/minio/minio/vendor/golang.org/x/crypto/argon2 (vendor tree)
	/home/bala/golang/goroot/src/golang.org/x/crypto/argon2 (from $GOROOT)
	/home/bala/mintauto/5640-c405f4c/gopath/src/golang.org/x/crypto/argon2 (from $GOPATH)
make: *** [build] Error 1

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5640-f14860f/gopath/src/github.com/minio
+ git -C 5640-f14860f/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5640-f14860f/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5640-f14860f/gopath/src/github.com/minio/minio fetch --quiet minio pull/5640/head:pr5640
+ git -C 5640-f14860f/gopath/src/github.com/minio/minio checkout --quiet pr5640
+ GOPATH=/home/bala/mintauto/5640-f14860f/gopath
+ make -C 5640-f14860f/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/vendor/golang.org/x/crypto/argon2
vendor/golang.org/x/crypto/argon2/blake2b.go:19:11: undefined: blake2b.New
vendor/golang.org/x/crypto/argon2/blake2b.go:49:11: undefined: blake2b.New
make: *** [build] Error 2

```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#8320d605-36ce-4d58-9999-34a05172ee4f) |
<a name="8320d605-36ce-4d58-9999-34a05172ee4f"></a>
### 5640-b5ff34f/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31290
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 243f8083fa5c:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 6 minutes and 20 seconds
(3/12) Running aws-sdk-ruby tests ... done in 45 seconds
(4/12) Running awscli tests ... FAILED in 4 minutes and 5 seconds
{
  "name": "awscli",
  "duration": 9090,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-30628/datafile-1-MBremove_bucket: awscli-mint-test-bucket-30628"
}

Executed 3 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by nitisht — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
