### PR TITLE
[notify] Make sure to return when quorum is missing

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
[notify] Make sure to return when quorum is missing

## Motivation and Context
Fixes a regression introduced in 510ec153b96c52c67cb9ae816b3c2158e89c04a3

## Regression
Yes 510ec153b96c52c67cb9ae816b3c2158e89c04a3

## How Has This Been Tested?
Properly in a large distributed setup

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#33f505cc-227b-4b4c-bec5-9949b0f85644) |
| mint-large-bucket.sh | :x: [more...](#debb6545-5b37-4935-9afb-ef155fcb436a) |
| mint-dist-xl.sh | :x: [more...](#248b2b29-304c-4b7a-91b5-309b9d4805eb) |
| mint-gateway-nas.sh | :x: [more...](#358e9fd5-fb9b-4240-a8af-49c1af8137db) |
<a name="358e9fd5-fb9b-4240-a8af-49c1af8137db"></a>
### 7799-596bd5e/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32407
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 97a402b2ded2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-z94yg4e3d2kib2",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3055,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32407/aws-sdk-go-test-z94yg4e3d2kib2: dial tcp 72.28.97.57:32407: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="248b2b29-304c-4b7a-91b5-309b9d4805eb"></a>
### 7799-596bd5e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31069
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp da3f603058f5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 35 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 3 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 37 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 581,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1psk5qr, objectName=minio-java-test-1502sok, resource=/minio-java-test-1psk5qr/minio-java-test-1502sok, requestId=15A93882FF7FB068, hostId=794d9b0f-e7bc-4cc4-a0a0-da7d59497e7c)\nrequest={method=DELETE, url=http://72.28.97.52:31069/minio-java-test-1psk5qr/minio-java-test-1502sok?uploadId=b2528ff0-6a94-4a1b-93d9-4d74edcea68e, headers=Host: 72.28.97.52:31069\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190618T065441Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190618/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-18T06-35-10Z\nVary: Origin\nX-Amz-Request-Id: 15A93882FF7FB068\nX-Minio-Deployment-Id: 794d9b0f-e7bc-4cc4-a0a0-da7d59497e7c\nX-Xss-Protection: 1; mode=block\nDate: Tue, 18 Jun 2019 06:54:41 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="33f505cc-227b-4b4c-bec5-9949b0f85644"></a>
### 7799-596bd5e/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31916
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 47ca24325062:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fv512nwqo2g2sv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2907,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31916/aws-sdk-go-test-fv512nwqo2g2sv: dial tcp 72.28.97.57:31916: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="debb6545-5b37-4935-9afb-ef155fcb436a"></a>
### 7799-596bd5e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30102
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 23fa9b3f7adb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 12 seconds
{
  "name": "mc",
  "duration": "105633",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7808 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-11867  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-11867/datafile-1-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-11867/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-11867/datafile-1.03-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-11867/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-11867/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-11867/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-11867/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-11867/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-11867/datafile-11-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-11867/datafile-10-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-11867/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-11867/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-11867/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-11867/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-11867/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 562.02 MiB, Speed: 5.32 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f6c00ebd-a6a7-4c7a-a029-d5e8c51bccf5) |
| mint-gateway-nas.sh | :x: [more...](#b6eed803-e70e-4350-b8b2-92ecb5d1822d) |
<a name="f6c00ebd-a6a7-4c7a-a029-d5e8c51bccf5"></a>
### 7799-b0b92f6/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32444
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9076dc27313f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 49 seconds
{
  "name": "mc",
  "duration": "129452",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-18528 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-23244  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-23244/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-23244/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-23244/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-23244/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-23244/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-23244/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-23244/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-23244/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-23244/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-23244/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-23244/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-23244/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-23244/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-23244/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-23244/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 549.93 MiB, Speed: 4.25 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="b6eed803-e70e-4350-b8b2-92ecb5d1822d"></a>
### 7799-b0b92f6/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31203
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 00f94817bc60:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yqpwuvm2glny4i",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3054,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31203/aws-sdk-go-test-yqpwuvm2glny4i: dial tcp 72.28.97.57:31203: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by Praveenrajmani — APPROVED** [review]

**Comment by Praveenrajmani** [comment]
PTAL @vadmeste

**Review by poornas — APPROVED** [review]
LGTM

**Pull request merged**
