### PR TITLE
Support detecting mountpoints correctly

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Support detecting mount points correctly

## Motivation and Context
Currently, windows support was relying on Symlink as
a way to detect a drive, this doesn't work in the latest
Windows 2016, fix this to use a proper mechanism by
using win32 APIs.

Additionally, also add support for detecting bind mounts
on Linux.

## Regression
No

## How Has This Been Tested?
Using Windows 2016, involving a community member. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f1e6e673-a4cf-4fe6-a9ab-7892c24bec0a) |
| mint-compression-dist-xl.sh | :x: [more...](#b7bcc95a-42e7-4309-957d-ab3ef839708a) |
<a name="b7bcc95a-42e7-4309-957d-ab3ef839708a"></a>
### 7288-62a2f41/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30631
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7cf8d6418c34:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-zt0karbxi1nih9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 319,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.51:30631/aws-sdk-go-test-zt0karbxi1nih9: dial tcp 72.28.97.51:30631: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="f1e6e673-a4cf-4fe6-a9ab-7892c24bec0a"></a>
### 7288-62a2f41/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32338
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp da1a48b8dcb5:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 32 seconds
(2/13) Running aws-sdk-java tests ... done in 21 seconds
(3/13) Running aws-sdk-php tests ... done in 49 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 1 minutes and 16 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-826a6adf7768",
    "file_name": "datafile-1-MB"
  },
  "duration": 60044.14,
  "error": "execution expired",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

**Comment by harshavardhana** [comment]
Ping @kannappanr @krishnasrinivas

**Review by kannappanr — APPROVED** [review]
LGTM. Haven't tested Windows, but looks good.

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
