### PR TITLE
Add debugging for mutex, tracing

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add debugging for mutex, tracing

## Motivation and Context
More debugging requirements

## Regression
No

## How Has This Been Tested?
By setting new env variables such as 
```
export _MINIO_PROFILER=mutex
minio server ~/test
go tool pprof `which minio` <path>/mutex.pprof
```
```
export _MINIO_PROFILER=trace
minio server ~/test
go tool trace `which minio` <path>/trace.out
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by nitisht — DISMISSED** [review]

**Review by vadmeste — DISMISSED** [review]
Can you also add definition of the new profiler types in the beginning of pkg/madmin/profiling-commands.go ? (same as ProfilerCPU and others)

**Comment by harshavardhana** [comment]
@vadmeste that is out of scope for this PR, this PR only adds env support.

**Comment by vadmeste** [comment]
@harshavardhana actually, madmin profiler uses startProfiler() that you are changing right now, so we can use, this is all the diff that you need to apply

```diff
diff --git a/pkg/madmin/profiling-commands.go b/pkg/madmin/profiling-commands.go
index 76837615..74b190e9 100644
--- a/pkg/madmin/profiling-commands.go
+++ b/pkg/madmin/profiling-commands.go
@@ -38,6 +38,10 @@ const (
        ProfilerMEM = ProfilerType("mem")
        // ProfilerBlock represents Block profiler type
        ProfilerBlock = ProfilerType("block")
+       // ProfilerTrace respresents trace profiler type
+       ProfilerTrace = ProfilerType("trace")
+       // ProfilerMutex represents mutex profiler type
+       ProfilerMutex = ProfilerType("mutex")
 )

 // StartProfilingResult holds the result of starting
```

**Comment by harshavardhana** [comment]
> @harshavardhana actually, madmin profiler uses startProfiler() that you are changing right now, so we can use, this is all the diff that you need to apply
> 
> ```diff
> diff --git a/pkg/madmin/profiling-commands.go b/pkg/madmin/profiling-commands.go
> index 76837615..74b190e9 100644
> --- a/pkg/madmin/profiling-commands.go
> +++ b/pkg/madmin/profiling-commands.go
> @@ -38,6 +38,10 @@ const (
>         ProfilerMEM = ProfilerType("mem")
>         // ProfilerBlock represents Block profiler type
>         ProfilerBlock = ProfilerType("block")
> +       // ProfilerTrace respresents trace profiler type
> +       ProfilerTrace = ProfilerType("trace")
> +       // ProfilerMutex represents mutex profiler type
> +       ProfilerMutex = ProfilerType("mutex")
>  )
> 
>  // StartProfilingResult holds the result of starting
> ```

@vadmeste @nitisht made more changes to the API itself

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Review by nitisht — APPROVED** [review]
LGTM & Tested

**Pull request merged**
