### PR TITLE
Support V2 signatures when auto-encryption is enabled

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Support V2 signatures when auto-encryption is enabled

## Motivation and Context
When auto-encryption is turned on, we pro-actively add SSEHeader
for all PUT, POST operations. This is unusual for V2 signature
calculation because V2 signature doesn't have a pre-defined set
of signed headers in the request like V4 signature. According to
V2 we should canonicalize all incoming supported HTTP headers.

Make sure to validate signatures before we mutate HTTP headers

## Regression
Yes - perhaps introduced in auto encryption feature changes

## How Has This Been Tested?
Using minio-go functional tests which use V2 signature for many API operations.

```
~ SERVER_ENDPOINT=localhost:9000 ACCESS_KEY=minio SECRET_KEY=minio123 ENABLE_HTTPS=0 MINT_MODE=full go run functional_tests.go
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
This is a blocker for the release on Wed and should be included, mint functional tests fail with auto encryption at the moment.

**Review by poornas — DISMISSED** [review]
Tested locally, LGTM.

**Comment by krishnasrinivas** [comment]
> When auto-encryption is turned on, we pro-actively add SSEHeader for all PUT, POST operations

Does not look right to mutate incoming headers. It will cause unexpected behavior in some other part of the code (like in this case signature failures) Signature verification code should not be concerned about if globalAutoEncryption is set or not.

If we take this PR in, and client sets SSEHeader and signs it using v2 and auto-encryption is set then there will be signature verification failure.

**Comment by harshavardhana** [comment]
I have a better solution will send it tonight.

**Comment by harshavardhana** [comment]
Updated the PR by copying the headers to mutation and making sure that original headers are never touched.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9852d337-4443-4326-bc00-9ac06187f9e3) |
<a name="9852d337-4443-4326-bc00-9ac06187f9e3"></a>
### 7084-84c10d7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32168
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b5891b0dab0c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 3 minutes and 16 seconds
{
  "name": "awscli",
  "duration": 75546,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "remove_bucket failed: s3://awscli-mint-test-bucket-16243 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 0 out of 13 tests successfully.
```

**Comment by poornas** [comment]
@harshavardhana, the original signature verification error was only for NewMultipartUpload -instead of this and previous fix, just switching the order of adding sse headers and checkRequestAuthType in NewMultipartUploadHandler will fix the issue
```
	if s3Error := checkRequestAuthType(ctx, r, policy.PutObjectAction, bucket, object); s3Error != ErrNone {
		writeErrorResponse(w, s3Error, r.URL, guessIsBrowserReq(r))
		return
	}

	// This request header needs to be set prior to setting ObjectOptions
	if globalAutoEncryption && !crypto.SSEC.IsRequested(r.Header) {
		r.Header.Add(crypto.SSEHeader, crypto.SSEAlgorithmAES256)
	}

	// get gateway encryption options
	var opts ObjectOptions
	var err error

	opts, err = putEncryptionOpts(ctx, r, bucket, object, nil)
	if err != nil {
		writeErrorResponseHeadersOnly(w, toAPIErrorCode(ctx, err))
		return
	}
```

**Comment by harshavardhana** [comment]
> @harshavardhana, the original signature verification error was only for NewMultipartUpload -instead of this and previous fix, just switching the order of adding sse headers and checkRequestAuthType in NewMultipartUploadHandler will fix the issue
> 
> ```
> 	if s3Error := checkRequestAuthType(ctx, r, policy.PutObjectAction, bucket, object); s3Error != ErrNone {
> 		writeErrorResponse(w, s3Error, r.URL, guessIsBrowserReq(r))
> 		return
> 	}
> 
> 	// This request header needs to be set prior to setting ObjectOptions
> 	if globalAutoEncryption && !crypto.SSEC.IsRequested(r.Header) {
> 		r.Header.Add(crypto.SSEHeader, crypto.SSEAlgorithmAES256)
> 	}
> 
> 	// get gateway encryption options
> 	var opts ObjectOptions
> 	var err error
> 
> 	opts, err = putEncryptionOpts(ctx, r, bucket, object, nil)
> 	if err != nil {
> 		writeErrorResponseHeadersOnly(w, toAPIErrorCode(ctx, err))
> 		return
> 	}
> ```

I am making a comprehensive fix, we should never be mutating *http.Request* - this is not just a NewMultpartUpload issue it happens for all PUT/POST operations which adds headers. I also wanted a fix which makes encryption-v1.go decouple from *http.Request

**Comment by harshavardhana** [comment]
> if s3Error := checkRequestAuthType(ctx, r, policy.PutObjectAction, bucket, object); s3Error != ErrNone { writeErrorResponse(w, s3Error, r.URL, guessIsBrowserReq(r)) return }

This change also can be done @poornas but I need to make sure we don't mutate http.Header

**Comment by poornas** [comment]
@harshavardhana, once the request headers have been cloned - the rest of the handler logic  should only refer to the cloned headers. Feel this approach is more prone to error - for e.g. line 1236 clones the headers and adds sse headers for auto encryption whereas line 1256 checks against r.Header to see if it is an encryption request - thus failing to encrypt the stream. Mistakes would creep in quickly if there are 2 ways of accessing request headers here.

**Comment by harshavardhana** [comment]
> @harshavardhana, once the request headers have been cloned - the rest of the handler logic should only refer to the cloned headers. Feel this approach is more prone to error - for e.g. line 1236 clones the headers and adds sse headers for auto encryption whereas line 1256 checks against r.Header to see if it is an encryption request - thus failing to encrypt the stream. Mistakes would creep in quickly if there are 2 ways of accessing request headers here.

That is perhaps true for now I think your approach might be feasible.

**Review by krishnasrinivas — APPROVED** [review]

**Review by poornas — APPROVED** [review]

**Comment by harshavardhana** [comment]
Nevertheless, we should get rid of **http.Request**  requirement in `encryption-v1.go`

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Pull request merged**
