### PR TITLE
For MakeBucket error should be quorum based on multiple sets

### LINKED ISSUE #5533: Server returns `BucketAlreadyOwnedByYou`
* Start `minio` like `minio server http://node1/disk{1...4} http://node2/disk{1...4} http://node3/disk{1...4}`
* After successful some make buckets, stop `minio` in node3, then replace all disks of `node3`
* Bring up `node3`, now `unformatted disk found (unformatted disk found)` error message is shown `node1` and `node3` console.
* Now create non-existent bucket like `mc mb minio/testbucket3` which shows a trace like below
```
$ date; mc --debug mb test/mybucket3; date
Thu Feb 15 15:44:39 IST 2018
mc: <DEBUG> PUT /mybucket3/ HTTP/1.1
Host: node1:9000
User-Agent: Minio (linux; amd64) minio-go/4.0.7 mc/2018-02-15T07:35:19Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minio/20180215/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180215T101439Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 503 Service Unavailable
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Thu, 15 Feb 2018 10:24:40 GMT
Retry-After: 120
Server: Minio/DEVELOPMENT.2018-02-15T07-05-04Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 151378C37DE5C3D6

10b
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioWriteQuorum</Code><Message>Multiple disks failures, unable to write data.</Message><Key></Key><BucketName></BucketName><Resource>/mybucket3/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  10m0.620226469s

mc: <DEBUG> PUT /mybucket3/ HTTP/1.1
Host: node1:9000
User-Agent: Minio (linux; amd64) minio-go/4.0.7 mc/2018-02-15T07:35:19Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minio/20180215/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180215T102440Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 409 Conflict
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Thu, 15 Feb 2018 10:24:40 GMT
Server: Minio/DEVELOPMENT.2018-02-15T07-05-04Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 151378C37FE77F43

135
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BucketAlreadyOwnedByYou</Code><Message>Your previous request to create the named bucket succeeded and you already own it.</Message><Key></Key><BucketName></BucketName><Resource>/mybucket3/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  21.82074ms

mc: <ERROR> Unable to make bucket `test/mybucket3`. Your previous request to create the named bucket succeeded and you already own it.
 (1) mb-main.go:131 cmd.mainMakeBucket(..) Tags: [test/mybucket3]
 (0) client-s3.go:768 cmd.(*s3Client).MakeBucket(..)
 Release-Tag:DEVELOPMENT.2018-02-15T07-35-19Z | Commit:335a53ad2911 | Host:bala-ThinkPad-X1-Carbon-4th | OS:linux | Arch:amd64 | Lang:go1.9.4 | Mem:3.1MB/6.6MB | Heap:3.1MB/4.8MB
Thu Feb 15 15:54:40 IST 2018
```

All the requests are sent to `node1`

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
For MakeBucket error should be quorum based on multiple sets

## Motivation and Context
Fixes #5533

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#0241b179-4a5d-4913-b498-64b825c41797) |
<a name="0241b179-4a5d-4913-b498-64b825c41797"></a>
### 5560-c40beaa/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31784
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp aa708a88a986:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mhhw241yeo2aoe",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 254,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:31784/aws-sdk-go-test-mhhw241yeo2aoe: dial tcp 192.168.122.45:31784: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#27db0846-dfe6-49c0-ab90-9f74d0b3b7a1) |
<a name="27db0846-dfe6-49c0-ab90-9f74d0b3b7a1"></a>
### 5560-a9267f0/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32464
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp a30aa224215b:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-pynfp53tc0sgq0",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 309,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:32464/aws-sdk-go-test-pynfp53tc0sgq0: dial tcp 192.168.122.45:32464: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#50ab3a03-731c-45fa-8dc4-b2606a1582e1) |
<a name="50ab3a03-731c-45fa-8dc4-b2606a1582e1"></a>
### 5560-dff1257/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31588
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp dd9cbef8162e:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-tivw3bv6shzgqt",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 248,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:31588/aws-sdk-go-test-tivw3bv6shzgqt: dial tcp 192.168.122.45:31588: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

**Comment by fwessels** [comment]
This could create the situation where the deterministic hash of an object could point to a pack where the directory for the bucket does not exists, and hence a PUT operation would fail (but then for a differently named object it would succeed).

Unless we check, upon detecting that the bucket does not exist locally, that there is a quorum for the bucket and we create it on demand, then we can address the issue.

**Comment by harshavardhana** [comment]
> This could create the situation where the deterministic hash of an object could point to a pack where the directory for the bucket does not exists, and hence a PUT operation would fail (but then for a differently named object it would succeed).
> 
> Unless we check, upon detecting that the bucket does not exist locally, that there is a quorum for the bucket and we create it on demand, then we can address the issue.

What we need to do here is a two-part approach by allowing MakeBucket to occur on PutObject() such that when the quorum is involved we will have to pro-actively create the bucket. Will discuss with @abperiasamy until then this PR is blocked.

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#cfcbb0c3-21e9-425c-8e66-50cb8e568ff2) |
<a name="cfcbb0c3-21e9-425c-8e66-50cb8e568ff2"></a>
### 5560-d65ef58/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30230
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 1c8b84ff96c2:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 7 minutes and 5 seconds
(3/12) Running aws-sdk-ruby tests ... done in 1 minutes and 2 seconds
(4/12) Running awscli tests ... FAILED in 3 minutes and 12 seconds
{
  "name": "awscli",
  "duration": 7992,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 3 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5560-d1113fe/gopath/src/github.com/minio
+ git -C 5560-d1113fe/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5560-d1113fe/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5560-d1113fe/gopath/src/github.com/minio/minio fetch --quiet minio pull/5560/head:pr5560
+ git -C 5560-d1113fe/gopath/src/github.com/minio/minio checkout --quiet pr5560
+ GOPATH=/home/bala/mintauto/5560-d1113fe/gopath
+ make -C 5560-d1113fe/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/xl-sets.go:395:30: not enough arguments in call to reduceWriteQuorumErrs
	have ([]error, nil, int)
	want ("context".Context, []error, []error, int)
cmd/xl-sets.go:396:5: undefined: errors
make: *** [build] Error 2

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5560-a26b3c5/gopath/src/github.com/minio
+ git -C 5560-a26b3c5/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5560-a26b3c5/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5560-a26b3c5/gopath/src/github.com/minio/minio fetch --quiet minio pull/5560/head:pr5560
+ git -C 5560-a26b3c5/gopath/src/github.com/minio/minio checkout --quiet pr5560
+ GOPATH=/home/bala/mintauto/5560-a26b3c5/gopath
+ make -C 5560-a26b3c5/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/xl-sets.go:400:21: undefined: err
make: *** [build] Error 2

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5560-a99e410/gopath/src/github.com/minio
+ git -C 5560-a99e410/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5560-a99e410/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5560-a99e410/gopath/src/github.com/minio/minio fetch --quiet minio pull/5560/head:pr5560
+ git -C 5560-a99e410/gopath/src/github.com/minio/minio checkout --quiet pr5560
+ GOPATH=/home/bala/mintauto/5560-a99e410/gopath
+ make -C 5560-a99e410/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/xl-sets.go:400:21: undefined: err
make: *** [build] Error 2

```

**Comment by harshavardhana** [comment]
Do not have a clean way to address this without complicating the existing codebase.

**Pull request closed without merging**
