### PR TITLE
always close the channel on the writer's side

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
always close the channel on the writer's side

## Motivation and Context
to avoid a crash with `mc admin trace` every
the time it's run against a MinIO cluster.

```
Feb 05 17:12:00 s3-us-node11 minio[3973657]: panic: send on closed channel
Feb 05 17:12:00 s3-us-node11 minio[3973657]: goroutine 378007076 [running]:
Feb 05 17:12:00 s3-us-node11 minio[3973657]: github.com/minio/minio/internal/pubsub.(*PubSub[...]).SubscribeJSON.func1()
Feb 05 17:12:00 s3-us-node11 minio[3973657]:         github.com/minio/minio/internal/pubsub/pubsub.go:139 +0x12d
Feb 05 17:12:00 s3-us-node11 minio[3973657]: created by github.com/minio/minio/internal/pubsub.(*PubSub[...]).SubscribeJSON in goroutine 378010884
Feb 05 17:12:00 s3-us-node11 minio[3973657]:         github.com/minio/minio/internal/pubsub/pubsub.go:124 +0x352
Feb 05 17:12:01 s3-us-node11 systemd[1]: minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

## How to test this PR?
Nothing special.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression yes in #18903
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]

**Review by poornas — APPROVED** [review]

**Comment by harshavardhana** [comment]
This is still not safe, needs @klauspost eyes to get some clarification.

**Comment by harshavardhana** [comment]
Actually, it's fine; fixed the tests properly.

**Review by klauspost — CHANGES_REQUESTED** [review]
No. The only way to safely do this is to not close the responses. It is designed like that. This will not work and will be racy and leaky.

**Comment by harshavardhana** [comment]
> No. The only way to safely do this is to not close the responses. It is designed like that. This will not work and will be racy and leaky.

This fixes a race @klauspost that exists because the close(out) is called while the goroutine is still trying to write to `out <- value` 

This moves the closing where the writing is, otherwise there is no safer way to do this

**Comment by klauspost** [comment]
@harshavardhana There is. This will break. Sending a PR now.

**Comment by harshavardhana** [comment]
> @harshavardhana There is. This will break. Sending a PR now.

Ah good, closing this PR.

**Pull request closed without merging**
