### PR TITLE
fix: refresh JWKS public keys upon failure

### LINKED ISSUE #10359: [resolved] AssumeRoleWithWebIdentity - JWKS endpoint not refreshed
With recent MinIO versions, it seems that AssumeRoleWithWebIdentity does not recognize JWTs signed with a key not present at the JWKS endpoint when MinIO started (JWKS rotation).

## Expected Behavior
MinIO should perform the AssumeRoleWithWebIdentity correctly when provided with a JWT signed with a key created by the IDP after MinIO startup (as part of key rotation by the IdP).

## Current Behavior

MinIO errors out with:

```
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>key is of invalid type</Message></Error><RequestId>162EC31498921B31</RequestId></ErrorResponse>
```
while the token is correct and is signed with an existing key (at the IdP) with alg RS256.
Just after restarting MinIO, the exact same token is presented and the call correctly succeeds.

## Possible Solution
MinIO should update at least the JWKS key set (and probably the OpenID configuration URL if JWKS endpoint is not specified) from the JWKS endpoint, to discard expired keys and gather new ones.
This could be checked at regular intervals (configurable) and perhaps forcefully checked (w/short negative cache) like in the past when an unknown kid is presented.

## Steps to Reproduce (for bugs)

1. Start MinIO associated with an IdP that does quick key rotation
2. Wait for the key to actually rotate
3. Request an id token from the IdP
4. Submit the id token to MinIO via AssumeRoleWithWebIdentity (this fails)
5. Restart MinIO
6. Submit the same token; the AssumeRoleWithWebIdentity call will succeed.

## Context
MinIO associated with an OpenID IdP (Dex).
I was trying to get AK/SK/ST in a long-running MinIO cluster.
By the way, actual mc support for generating AK/SK/ST from OpenID in the same way that the kubelogin program does could be very interesting.

## Regression
Yes.
Although the implementation did not update the endpoint periodically, JWKS endpoint was actually re-scraped in case token validation failed in the past: https://github.com/minio/minio/commit/abbf6ce6ccf8e99d6e295b9d26483301f0c8139b 

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-08-08T04-50-06Z
* Server setup and configuration: identity_openid config_url=https://my-dex-endpoint.cluster.local/.well-known/openid-configuration client_id=minio.cluster.local claim_name=email claim_prefix= jwks_url= scopes=
* Operating System and version (`uname -a`): CentOS 7.8.2003

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: refresh JWKS public keys upon failure

## Motivation and Context
fixes #10359

## How to test this PR?
Use `dex` like IDP providers which change JWKS frequently.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression the bug was introduced in the last refactor
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Review by poornas — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :x: [more...](#6c140ac9-b279-4036-a3a0-aad4a3b295b2) |
<a name="6c140ac9-b279-4036-a3a0-aad4a3b295b2"></a>
### 10368-2f2f5cd/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30963
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a6b4671376e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 14 seconds
(8/15) Running minio-dotnet tests ... done in 49 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 54 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 19 seconds
(11/15) Running minio-js tests ... FAILED in 13 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 17,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(11/15) Running minio-py tests ... done in 3 minutes and 5 seconds
(12/15) Running s3cmd tests ... done in 33 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#e771aa5a-0bd9-4938-bf78-427188c7a3bf) |
<a name="e771aa5a-0bd9-4938-bf78-427188c7a3bf"></a>
### 10368-d0c86dc/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30012
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1a1d503cd64c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 55 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 2 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 4 minutes and 29 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 29 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 54 seconds
{
  "args": {
    "bucketName": "minio-go-test-xxjz5g31xifkvpve",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 627,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 2 seconds
(10/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 10 minutes and 13 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 27 seconds
(12/15) Running s3select tests ... done in 32 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10368-d0c86dc

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#7f3532e6-85c7-4fd5-babf-a6f445153885) |
| mint-zoned.sh | :x: [more...](#fcea51fb-2548-4821-9a38-f535e49ef675) |
<a name="7f3532e6-85c7-4fd5-babf-a6f445153885"></a>
### 10368-cdc817b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32330
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 981e42dbb15a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 2 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 2 seconds
{
  "name": "awscli",
  "duration": 1967,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:32330 s3api create-multipart-upload --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.-object\n",
  "status": "FAIL",
  "error": ""
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 19 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 25 seconds
(9/15) Running minio-java tests ... done in 6 minutes and 8 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 46 seconds
(11/15) Running minio-py tests ... done in 10 minutes and 36 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 34 seconds
(13/15) Running s3select tests ... done in 50 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="fcea51fb-2548-4821-9a38-f535e49ef675"></a>
### 10368-cdc817b/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30533
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 57d7243faa70:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ng2sl3bdbr1ljv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120880,
  "error": "BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.\n\tstatus code: 409, request id: 162F4BB1FBFE14EB, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-java tests ... done in 2 seconds
(2/15) Running aws-sdk-php tests ... done in 44 seconds
(3/15) Running aws-sdk-ruby tests ... done in 6 seconds
(4/15) Running awscli tests ... done in 1 minutes and 29 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 38 seconds
(7/15) Running minio-dotnet tests ... done in 49 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 53 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 41 seconds
(10/15) Running minio-js tests ... done in 52 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 8 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10368-cdc817b

**Review by Praveenrajmani — APPROVED** [review]

**Review by klauspost — APPROVED** [review]
LGTM

**Pull request merged**
