### PR TITLE
Increase max idle connections from 100 to 4096

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Increase max idle connections from 100 to 4096

## Motivation and Context
This is to be inline with our benchmarking results

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
PR #6236 
PR #6242 

Should be merged in that order.

**Review by kannappanr — DISMISSED** [review]
LGTM

**Comment by harshavardhana** [comment]
> PR #6236
> PR #6242
> 
> Should be merged in that order.

Actually will de-couple this PR since this can be merged independently.

**Comment by harshavardhana** [comment]
De-coupled the PR @kannappanr @fwessels - please review.

**Review by fwessels — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 6244-d5f72a4/gopath/src/github.com/minio
+ git clone --quiet https://github.com/minio/minio.git 6244-d5f72a4/gopath/src/github.com/minio/minio
fatal: write error: No space left on device
fatal: index-pack failed

```

**Pull request merged**
