### PR TITLE
xl-meta: update metadata version

### PR DESCRIPTION
**Pull request by poornas**
## Motivation and Context
update metadata version since https://github.com/minio/minio/pull/15956 bumped up the version

## How to test this PR?
for newer objects created with master, should be able to decode metadata
```
 xl-meta /tmp/multisitea/data/disterasure/xl1/olock/bin/aax/xl.meta
2022/10/27 14:18:49 decodeXLHeaders: Unknown xl meta version 2
```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
We need to support older version as well does it work with this change too? @poornas

**Comment by poornas** [comment]
> We need to support older version as well does it work with this change too? @poornas

it does work with older versions

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
We need an `mc` PR as well @poornas for this for `mc support inspect --export=json`

**Review by klauspost — APPROVED** [review]
I'm thinking we should maybe move the executable into cmd - or go all out and make it a separate package.

Either way this is fine for now.

**Comment by harshavardhana** [comment]
> I'm thinking we should maybe move the executable into cmd - or go all out and make it a separate package.

A central package such as at `minio/pkg` is useful for `mc`

**Pull request merged**
