### PR TITLE
Deprecate intel-32, arm64, arm support for minio builds.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Deprecate intel-32, arm64, arm support for minio builds.

## Motivation and Context
It was decided that we will be deprecating ARM support
for minio builds. ARM users should simply compile from source.

Additionally 32bit version of Linux, Windows and FreeBSD (64bit)
are deprecated.

## How Has This Been Tested?
Manually 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by donatello — APPROVED** [review]
Suggest modifying commit message to include that this deprecates 32-bit architectures as well.

**Comment by harshavardhana** [comment]
> Suggest modifying commit message to include that this deprecates 32-bit architectures as well.

Done @donatello

**Comment by nitisht** [comment]
Can we add a note on the Minio Quickstart Guide: https://docs.minio.io/docs/minio-quickstart-guide about how an affected user can build it themselves?

**Comment by harshavardhana** [comment]
> Can we add a note on the Minio Quickstart Guide: https://docs.minio.io/docs/minio-quickstart-guide about how an affected user can build it themselves?

Yes we do have that its called `Install from Source`  ? @NitishT

**Comment by nitisht** [comment]
> Yes we do have that its called Install from Source

Correct. I meant more specific commands for the platforms we are deprecating builds for. Say, how a user planning to run Minio on Raspberry Pi is supposed to build it.

**Comment by harshavardhana** [comment]
> Correct. I meant more specific commands for the platforms we are deprecating builds for. Say, how a user planning to run Minio on Raspberry Pi is supposed to build it.

Same `go get github.com/minio/minio`  - nothing special.

**Comment by nitisht** [comment]
> Same go get github.com/minio/minio - nothing special.

Got it.

**Review by nitisht — APPROVED** [review]
LGTM

**Pull request merged**
