### PR TITLE
Fix stale locks held by SelectParquet API

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Fix stale locks held by SelectParquet API

## Motivation and Context
Vendorize upstream parquet-go to fix this issue.

## Regression
Not sure, perhaps the bug was always there

## How Has This Been Tested?
Using `select` on parquet file and subsequently using `mc rm` to delete the parquet file.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by balamurugana — DISMISSED** [review]

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 7364-5742391/gopath/src/github.com/minio
+ git -C 7364-5742391/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 7364-5742391/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 7364-5742391/gopath/src/github.com/minio/minio fetch --quiet minio pull/7364/head:pr7364
+ git -C 7364-5742391/gopath/src/github.com/minio/minio checkout --quiet pr7364
+ GOPATH=/mnt/nvme/mint-auto/7364-5742391/gopath
+ make -C 7364-5742391/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/pkg/s3select/parquet
pkg/s3select/parquet/reader.go:32:8: undefined: "github.com/minio/minio/vendor/github.com/minio/parquet-go".File
make: *** [build] Error 2

```

**Comment by poornas** [comment]
travis failure @harshavardhana

**Comment by harshavardhana** [comment]
Fixed build issues PTAL @balamurugana @poornas

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#faa9b3f0-fe34-4e6d-9f0a-76898690dd4f) |
| mint-compression-dist-xl.sh | :x: [more...](#753f1377-b66b-4216-9ca7-47e2cbdea93e) |
<a name="753f1377-b66b-4216-9ca7-47e2cbdea93e"></a>
### 7364-03d6865/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30527
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5c597ad4f1ba:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 11 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 4 seconds
(4/14) Running aws-sdk-ruby tests ... FAILED in 1 minutes and 4 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-a9227dffe21d",
    "file_name": "datafile-1-kB"
  },
  "duration": 60020.16,
  "error": "execution expired",
  "status": "FAIL"
}

Executed 3 out of 14 tests successfully.
```
<a name="faa9b3f0-fe34-4e6d-9f0a-76898690dd4f"></a>
### 7364-03d6865/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31700
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 61dc4467f850:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ve1bs25h5b4v19",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31700/aws-sdk-go-test-ve1bs25h5b4v19: dial tcp 72.28.97.55:31700: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by poornas — APPROVED** [review]
LGTM

**Review by balamurugana — APPROVED** [review]

**Pull request merged**
