### PR TITLE
replace blake2b implementation

### PR DESCRIPTION
**Pull request by aead**
Replace the blake2b implementation

## Description
Replace the minio/blake2b-simd implementation with the implementation of golang/x/crypto/blake2b

## Motivation and Context
The implementation at golang.org/x/crypto is faster in my benchmarks

## How Has This Been Tested?
I ran the tests in the /cmd and the /pkg/*
Tests were ran under linux/amd64 with and without AVX2

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
@aead can you provide the 'go test -bench' results and comparison matrix we would like to know more. 

// cc @fwessels

**Comment by aead** [comment]
The blake2b-simd AVX vs. the blake2b SSE4.1 implementation:
```
name        old time/op    new time/op     delta
Size64-8       715ns ±13%      614ns ± 3%    ~     (p=0.084 n=6+6)
Size128-8      612ns ± 5%      634ns ± 8%    ~     (p=0.084 n=6+6)
Size1K-8      2.18µs ± 5%     2.09µs ± 7%    ~     (p=0.084 n=6+6)
Size8K-8      13.1µs ± 2%     13.4µs ± 3%    ~     (p=0.084 n=6+6)
Size32K-8     48.5µs ± 1%     49.5µs ± 3%    ~     (p=0.775 n=6+6)
Size128K-8     199µs ± 0%      198µs ± 3%    ~     (p=0.468 n=6+6)

name        old speed      new speed       delta
Size64-8    92.6MB/s ±11%  104.2MB/s ± 3%    ~     (p=0.139 n=6+6)
Size128-8    208MB/s ± 6%    202MB/s ± 8%    ~     (p=0.102 n=6+6)
Size1K-8     466MB/s ± 7%    492MB/s ± 7%    ~     (p=0.139 n=6+6)
Size8K-8     621MB/s ± 2%    610MB/s ± 3%    ~     (p=0.102 n=6+6)
Size32K-8    672MB/s ± 2%    669MB/s ± 1%    ~     (p=0.818 n=6+6)
Size128K-8   657MB/s ± 1%    672MB/s ± 0%  +2.28%  (p=0.002 n=6+6)
```
There is no significant difference (but AVX should probably be faster...)

And blake2b-simd AVX2 vs. blake2b AVX2:
```
name        old time/op   new time/op   delta
Size64-4      334ns ± 1%    243ns ± 0%  -27.14%  (p=0.029 n=4+4)
Size128-4     296ns ± 1%    242ns ± 0%  -18.21%  (p=0.029 n=4+4)
Size1K-4     1.44µs ± 0%   1.28µs ± 0%  -10.83%  (p=0.029 n=4+4)
Size8K-4     10.0µs ± 0%    9.4µs ± 0%   -6.23%  (p=0.029 n=4+4)
Size32K-4    39.8µs ± 1%   37.3µs ± 0%   -6.31%  (p=0.029 n=4+4)
Size128K-4    162µs ± 3%    149µs ± 0%   -7.72%  (p=0.029 n=4+4)

name        old speed     new speed     delta
Size64-4    192MB/s ± 1%  263MB/s ± 0%  +37.24%  (p=0.029 n=4+4)
Size128-4   431MB/s ± 0%  526MB/s ± 0%  +22.04%  (p=0.029 n=4+4)
Size1K-4    713MB/s ± 0%  800MB/s ± 0%  +12.17%  (p=0.029 n=4+4)
Size8K-4    815MB/s ± 0%  869MB/s ± 0%   +6.64%  (p=0.029 n=4+4)
Size32K-4   823MB/s ± 1%  878MB/s ± 0%   +6.72%  (p=0.029 n=4+4)
Size128K-4  810MB/s ± 3%  877MB/s ± 0%   +8.23%  (p=0.029 n=4+4)
```

edit: I made a c&p error at the AVX vs SSE4.1 benchmark - sorry for that!

**Comment by harshavardhana** [comment]
> edit: I made a c&p error at the AVX vs SSE4.1 benchmark - sorry for that!

No problem these benchmarks look great. Will let @fwessels provide his inputs.

**Comment by fwessels** [comment]
Nice work on the implementation. For AVX2 there was indeed still a 5% performance gain to be obtained, and obviously with Go 1.7 there is now much better support for SIMD instructions.

I would expect to see performance differences between AVX and SSE (although it can differ across processors as well).

Do you have any plans to add an AVX implementation?

**Comment by aead** [comment]
Thanks, I think you're are right about SSE4 vs AVX - especially on newer machines.  
(on my "old" i7-3632MQ there is no significant difference)  

I can implement an AVX version and submit it to code-review, but  Go dev cycle is closed until Feb. 2017 - blake2b lives in the x/crypto package and I don't know whether an AVX version will be accepted before 2017 or even ever

If you want to wait for AVX, than I will submit an implementation an update this PR as soon as I know more...

**Comment by fwessels** [comment]
Yeah, we have seen quite different performance on different CPU types. Also Atom processors (nice on low power of course) seem to have crippled SIMD performance (I guess they had to save somewhere...).

We would really like to see an AVX implementation, based on our own experience that shouldn't be too much work actually (once you have one technology working). With that in place we'll swap the implementation, but right now it would mean a performance drop on some systems that would fall back from AVX to SSE, and that wouldn't be too nice.

BTW Have you done any work on ARM by any chance?

**Comment by aead** [comment]
Ok, I'll add this to my TODO list - maybe I can push it for review before Christmas...

I'm not really familiar with ARM assembly (neither I'm an AMD64 guru ;-) ) - I have played a little bit with the Cortex-A7 (banana-pi) but I think, I'm not the right guy for an ARM implementation for blake2b...

**Comment by fwessels** [comment]
Great, looking forward to that.

Reason for ARM is not blake2 actually, since ARM has special instructions for SHA256 that would be of little use (see https://github.com/minio/sha256-simd), more just out of interest. (And Intel also has designed some special SHA256 instructions but they haven't made it into silicon yet.)

**Comment by aead** [comment]
Okay, thats an interesting topic, so maybe SHA-256 will become the favorite hash function (if it isn't already) - Thanks for the repo link! I'll keep an eye on it :)

**Comment by harshavardhana** [comment]
Thanks for adding AVX support @aead

**Comment by aead** [comment]
AVX implementation is submitted for review to the Go-Team - see [Gerrit](https://go-review.googlesource.com/#/c/34319/)
I will also update this PR if something changes while code review.

**Comment by aead** [comment]
Adam accepted the submitted code - so (if the change still looks good) it can be merged

**Comment by harshavardhana** [comment]
Looks like would require you need to rebase @aead

**Comment by aead** [comment]
I missed something on the rebase and now the repo is in a weird state - I'll open a new pull request to simplify this...

**Comment by aead** [comment]
#3481 is merged - so I close this PR

**Comment by harshavardhana** [comment]
> #3481 is merged - so I close this PR

Great contribution @aead - Thanks. :+1:

**Comment by fwessels** [comment]
I second this: 👍

**Comment by aead** [comment]
Thanks :smile:

**Pull request closed without merging**
