### PR TITLE
API is compatible with Elasticsearch 7.17.7

### PR DESCRIPTION
**Pull request by yanggangtony**
As github.com/elastic/go-elasticsearch is released 7.17.7 , So we can update go.mod to follow it for compatible with Elasticsearch 7.17.7

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [✔️] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by harshavardhana** [comment]
Right now we are not planning to update the dependency yet, what is the reason for the upgrade? - have you tested this with elasticsearch?

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by yanggangtony** [comment]
> Right now we are not planning to update the dependency yet, what is the reason for the upgrade? - have you tested this with elasticsearch?

not yet tested this with elasticsearch.
I just see the release note from [https://github.com/elastic/go-elasticsearch/releases](url) 
and the code changes between 7.17.1 and 7.17.7

**Comment by harshavardhana** [comment]
We need this tested with elasticsearch @yanggangtony

**Comment by yanggangtony** [comment]
> We need this tested with elasticsearch @yanggangtony

@harshavardhana 
OK ,I will test it.
when the result is ok , I will notify you.
thanks.

**Comment by yanggangtony** [comment]
@harshavardhana
Hi, I just now test this api change in es 7.17.7 and es 7.17.1 , it looks good..

---- 7.17.7 ---- 
image
image
image
image
image
image
image
image
image



---- 7.17.1 ---- 

image
image
image
image
image

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
