### PR TITLE
fix: fetchLambdaInfo should return consistent results

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description

fetchLambdaInfo should return a complete list of configured targets irrespective to the errors while initializing the targets.

- Introduced a function `FetchRegisteredTargets` which will return
  a complete set of registered targets irrespective to their states,
  if the `returnOnTargetError` flag is set to `False`
- Refactor NewTarget functions to return non-nil targets

## Motivation and Context

- `mc admin info --json` should not return empty notification list ('notifications': []) if any of configured target is offline
- In this case, fallback on target errors while initializing the targets for preparing a targetList (always add a target to the TargetList)

## How to test this PR?
- Configure multiple targets
- toggle the targets from offline -><- online
- `mc admin info --json` should always give a non-empty notification list and should say if the configured targets are online/offline

For eg, 

- Run a webhook on :8080
- Run a redis server
- Add webhook and redis endpoints in MinIO
- Make redis server offline
- Check `mc admin info --json`, It should provide a notification list with two targets and also stating redis target as "offline"

```
"notifications": [
                {
                    "redis": [
                        {
                            "1": {
                                "status": "Offline"
                            }
                        }
                    ]
                },
                {
                    "webhook": [
                        {
                            "1": {
                                "status": "Online"
                            }
                        }
                    ]
                }
            ]
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#7c36df35-9310-4b04-a849-afa7d9057e09) |
| mint-gateway-azure.sh | :x: [more...](#bac1ef87-092e-4b89-b1f7-651a41f1f942) |
<a name="7c36df35-9310-4b04-a849-afa7d9057e09"></a>
### 9332-b606fde/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:31519
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 292057f846d3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-rhmzypcqcghqrd",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365589,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 160552F22B6CAB43, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 15 tests successfully.
```
<a name="bac1ef87-092e-4b89-b1f7-651a41f1f942"></a>
### 9332-b606fde/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30507
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a456ea049624:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 12 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... done in 3 minutes and 0 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 9 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 19 seconds
(10/15) Running minio-java tests ... done in 27 minutes and 36 seconds
(11/15) Running minio-js tests ... FAILED in 4 minutes and 0 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-ce481abd-78ff-41e1-b471-093bd302f71d, recursive:true",
  "duration": 215,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 10 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by dvaldivia** [comment]
I have 5 targets (4 postgres, 1 redis) and if 2 are offline, it seems the `initAllSubsystems()` call on `server-main.go:263` fails and throws exceptions

```
Error: Unable to initialize notification target(s): dial tcp 127.0.0.1:6379: connect: connection refused
       7: cmd/config-current.go:451:cmd.lookupConfigs()
       6: cmd/config-current.go:571:cmd.loadConfig()
       5: cmd/config.go:253:cmd.initConfig()
       4: cmd/config.go:213:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:246:cmd.initAllSubsystems()
       2: cmd/server-main.go:220:cmd.initSafeMode()
       1: cmd/server-main.go:447:cmd.serverMain()

API: SYSTEM(bucket=bucket1)
Time: 12:54:36 PDT 04/13/2020
DeploymentID: b3f8577c-0b62-4aff-ad5b-579dc07c588b
Error: ARN 'arn:minio:sqs::1:postgresql' not found
       6: cmd/notification.go:1305:cmd.readNotificationConfig()
       5: cmd/notification.go:648:cmd.(*NotificationSys).load()
       4: cmd/notification.go:682:cmd.(*NotificationSys).Init()
       3: cmd/server-main.go:263:cmd.initAllSubsystems()
       2: cmd/server-main.go:220:cmd.initSafeMode()
       1: cmd/server-main.go:447:cmd.serverMain()
```

This causes `sys.targetList.List()` to return an empty list, there force trying to get a list of server arns fails for `mc admin info` since the `sys.targetList` was not initialized due to the error.

I think we should fail event targets individually, or have `GetARNList()` return a list of ARNs straight from the configuration, or both.

**Comment by harshavardhana** [comment]
> I have 5 targets (4 postgres, 1 redis) and if 2 are offline, it seems the `initAllSubsystems()` call on `server-main.go:263` fails and throws exceptions
> 
> ```
> Error: Unable to initialize notification target(s): dial tcp 127.0.0.1:6379: connect: connection refused
>        7: cmd/config-current.go:451:cmd.lookupConfigs()
>        6: cmd/config-current.go:571:cmd.loadConfig()
>        5: cmd/config.go:253:cmd.initConfig()
>        4: cmd/config.go:213:cmd.(*ConfigSys).Init()
>        3: cmd/server-main.go:246:cmd.initAllSubsystems()
>        2: cmd/server-main.go:220:cmd.initSafeMode()
>        1: cmd/server-main.go:447:cmd.serverMain()
> 
> API: SYSTEM(bucket=bucket1)
> Time: 12:54:36 PDT 04/13/2020
> DeploymentID: b3f8577c-0b62-4aff-ad5b-579dc07c588b
> Error: ARN 'arn:minio:sqs::1:postgresql' not found
>        6: cmd/notification.go:1305:cmd.readNotificationConfig()
>        5: cmd/notification.go:648:cmd.(*NotificationSys).load()
>        4: cmd/notification.go:682:cmd.(*NotificationSys).Init()
>        3: cmd/server-main.go:263:cmd.initAllSubsystems()
>        2: cmd/server-main.go:220:cmd.initSafeMode()
>        1: cmd/server-main.go:447:cmd.serverMain()
> ```
> 
> This causes `sys.targetList.List()` to return an empty list, there force trying to get a list of server arns fails for `mc admin info` since the `sys.targetList` was not initialized due to the error.
> 
> I think we should fail event targets individually, or have `GetARNList()` return a list of ARNs straight from the configuration, or both.

@dvaldivia this PR is trying to fix this situation. Are you saying its not behaving correctly?

**Comment by dvaldivia** [comment]
@harshavardhana it's fixing the part of `mc admin info` that returns the state of the services on `info.Services.Notifications` however, we also add a list of arns on `info.SQSARN` which is returning empty if the notifications did not initialize properly 

`info.SQSARN` gets set like
```
SQSARN:       globalNotificationSys.GetARNList(),
```
whereas `info.Services.Notifications` gets build via `fetchLambdaInfo(cfg)` which this PR fixed.

I'm just pointing that the same issue is present of a different place. This PR addresses `fetchLambdaInfo(cfg)` nicely, so we can go ahead and merge it for that and we can do a separate PR to address the `globalNotificationSys.GetARNList()` being empty if a single even target could not initialize

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#dc86a40a-5d49-4a41-bfb3-7a4987d646f6) |
<a name="dc86a40a-5d49-4a41-bfb3-7a4987d646f6"></a>
### 9332-92ff3e3/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30845
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 84d7db706bce:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 23 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... done in 3 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 6 minutes and 18 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/15) Running minio-go tests ... done in 18 minutes and 46 seconds
(10/15) Running minio-java tests ... done in 26 minutes and 19 seconds
(11/15) Running minio-js tests ... FAILED in 3 minutes and 46 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-09997a35-4f30-47d5-ac86-62be9ea3800c, recursive:true",
  "duration": 208,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 10 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by Praveenrajmani** [comment]
Fixed the SQS ARNs @dvaldivia

**Comment by Praveenrajmani** [comment]
One small note :- 

Currently, The `SQS ARNs` which is been displayed in the server startup console shows a complete list of configured targets

We have to fix it to display only active targets. This involves some some structural changes since we also need to check the stores. We should display the ARN even if its target is offline but store is configured for that target. This is considered to be a valid config in MinIO and MinIO treats it as a valid target.

Will fix this scenario in a separate PR to ease the reviewing process

cc @harshavardhana

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#ff5de84f-3b56-44e7-8c24-c18247247cef) |
<a name="ff5de84f-3b56-44e7-8c24-c18247247cef"></a>
### 9332-53a7d40/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30468
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 72254138100c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 32 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... done in 3 minutes and 2 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 6 minutes and 20 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 29 seconds
(9/15) Running minio-go tests ... done in 19 minutes and 51 seconds
(10/15) Running minio-java tests ... done in 26 minutes and 36 seconds
(11/15) Running minio-js tests ... FAILED in 3 minutes and 50 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-e2b8e77b-a9da-43f0-bc2a-710505fdd2f4, recursive:true",
  "duration": 213,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 10 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by dvaldivia** [comment]
tested. LGTM

**Review by dvaldivia — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
