### PR TITLE
fix: do not reload disk format.json on a reconnected disk

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: do not reload disk format.json on a reconnected disk

## Motivation and Context
An onlineDisk means its a valid disk but it may be a
re-connected disk, this PR verifies that based on LastConn()
to only trigger MRF. Current code would again re-load the
disk 'format.json' which is not necessary and perhaps an
unnecessary call.

A potential side effect of this is closing perfectly online
disks and getting re-replaced by reloading 'format.json'.

This PR tries to avoid this situation by making sure MRF
is triggered but not reloading 'format.json' because of MRF.

## How to test this PR?
verify this in a distributed setup and observe reconnected
disk reloads again spuriously.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#2b60578a-3ee5-4cad-a3f4-9b51d1278f76) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#8c54e61b-603a-466e-99b6-b900dde8097a) |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#c85a7d97-383d-44b9-91fd-94133d06dd68) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#dcc61c89-39b8-4152-bea8-ae4dc21d2804) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#b0a5b785-a58f-4ef8-9cde-c39fb256ebe3) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#0478ccac-4458-4477-a9eb-2e7ae1865da6) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#6405f5e2-e032-4f7a-8116-23e902ea3998) |
| mint-pools.sh | :heavy_exclamation_mark: [more...](#fbcfea62-a0f8-4443-a162-1531e0c66126) |
<a name="8c54e61b-603a-466e-99b6-b900dde8097a"></a>
### 14351-1a6eefd/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0478ccac-4458-4477-a9eb-2e7ae1865da6"></a>
### 14351-1a6eefd/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="fbcfea62-a0f8-4443-a162-1531e0c66126"></a>
### 14351-1a6eefd/mint-pools.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="6405f5e2-e032-4f7a-8116-23e902ea3998"></a>
### 14351-1a6eefd/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="b0a5b785-a58f-4ef8-9cde-c39fb256ebe3"></a>
### 14351-1a6eefd/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="dcc61c89-39b8-4152-bea8-ae4dc21d2804"></a>
### 14351-1a6eefd/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="2b60578a-3ee5-4cad-a3f4-9b51d1278f76"></a>
### 14351-1a6eefd/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="c85a7d97-383d-44b9-91fd-94133d06dd68"></a>
### 14351-1a6eefd/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
I can't speak for the correctness, but LGTM.

**Comment by harshavardhana** [comment]
PTAL @vadmeste

**Pull request merged**
