### PR TITLE
fs: fix a regression allow reading of existing files

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fs: fix a regression allow reading of existing files

## Motivation and Context
Regression

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#69109bc3-a533-4e8b-9620-9ba6873dbdac) |
| mint-gateway-azure.sh | :x: [more...](#044c644c-a60b-4789-9cdd-f7ff795f6285) |
<a name="69109bc3-a533-4e8b-9620-9ba6873dbdac"></a>
### 5889-54f42db/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32172
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp cec09bf58f49:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 3 seconds
(2/13) Running aws-sdk-java tests ... done in 17 seconds
(3/13) Running aws-sdk-php tests ... done in 49 seconds
(4/13) Running aws-sdk-ruby tests ... done in 22 seconds
(5/13) Running awscli tests ... done in 6 minutes and 33 seconds
(6/13) Running mc tests ... done in 2 minutes and 6 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 3 seconds
(8/13) Running minio-go tests ... done in 16 seconds
(9/13) Running minio-java tests ... done in 47 seconds
(10/13) Running minio-js tests ... FAILED in 52 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-9d6e04a8-4f93-4460-88d6-a21218cd4a93, events: s3:ObjectCreated:*",
  "duration": 8550,
  "status": "FAIL",
  "error": "Error: notification not received at client.removeObject.err (test/functional-tests.js:1031:43) at ClientRequest.<anonymous> (node_modules/minio/dist/main/minio.js:420:9) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:478:21) at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23) at Socket.socketOnData (_http_client.js:367:20) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at TCP.onread (net.js:559:20)"
}

Executed 9 out of 13 tests successfully.
```
<a name="044c644c-a60b-4789-9cdd-f7ff795f6285"></a>
### 5889-54f42db/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31574
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp c7956a81cbc7:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 3 seconds
(2/13) Running aws-sdk-java tests ... done in 16 seconds
(3/13) Running aws-sdk-php tests ... done in 40 seconds
(4/13) Running aws-sdk-ruby tests ... done in 29 seconds
(5/13) Running awscli tests ... done in 4 minutes and 46 seconds
(6/13) Running mc tests ... done in 8 minutes and 8 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 10 seconds
(8/13) Running minio-go tests ... done in 1 seconds
(9/13) Running minio-java tests ... done in 33 seconds
(10/13) Running minio-js tests ... FAILED in 2 minutes and 40 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-bba17d31-bc52-4aa3-9650-962da58204b9",
  "duration": 266,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 9 out of 13 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#4232d89c-dd08-4474-9cd4-6a89ed94404f) |
<a name="4232d89c-dd08-4474-9cd4-6a89ed94404f"></a>
### 5889-2593b7b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31321
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 9f772fa12a74:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 2 seconds
(2/13) Running aws-sdk-java tests ... done in 14 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 35 seconds
(5/13) Running awscli tests ... done in 5 minutes and 11 seconds
(6/13) Running mc tests ... done in 8 minutes and 10 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 18 seconds
(8/13) Running minio-go tests ... done in 1 seconds
(9/13) Running minio-java tests ... done in 26 seconds
(10/13) Running minio-js tests ... FAILED in 2 minutes and 34 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-8164d240-0470-4201-bc25-70556a150bc2",
  "duration": 282,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 9 out of 13 tests successfully.
```

**Review by nitisht — APPROVED** [review]

**Review by poornas — APPROVED** [review]

**Comment by deekoder** [comment]
This mint failure should have gone away.

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5889-6ced2d0/gopath/src/github.com/minio
mkdir: cannot create directory ‘5889-6ced2d0’: No space left on device

```

**Comment by deekoder** [comment]
Will merge after mint runs against this PR @harshavardhana

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#635c7656-e7ba-44b0-861b-5e1dc42574d5) |
| mint-gateway-azure.sh | :x: [more...](#cbe7bf4b-390f-4dd9-905e-5556a79fb359) |
<a name="cbe7bf4b-390f-4dd9-905e-5556a79fb359"></a>
### 5889-f4ac288/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31074
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp f83ed8bf571e:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 2 seconds
(2/13) Running aws-sdk-java tests ... done in 12 seconds
(3/13) Running aws-sdk-php tests ... done in 42 seconds
(4/13) Running aws-sdk-ruby tests ... done in 37 seconds
(5/13) Running awscli tests ... done in 4 minutes and 19 seconds
(6/13) Running mc tests ... done in 7 minutes and 5 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 11 seconds
(8/13) Running minio-go tests ... done in 1 seconds
(9/13) Running minio-java tests ... done in 33 seconds
(10/13) Running minio-js tests ... FAILED in 2 minutes and 19 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-f2101081-32be-42d0-9ace-29d0a6b904d6",
  "duration": 305,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 9 out of 13 tests successfully.
```
<a name="635c7656-e7ba-44b0-861b-5e1dc42574d5"></a>
### 5889-f4ac288/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31616
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 9585ba6e39d0:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 1 seconds
(2/13) Running aws-sdk-java tests ... done in 14 seconds
(3/13) Running aws-sdk-php tests ... done in 51 seconds
(4/13) Running aws-sdk-ruby tests ... done in 24 seconds
(5/13) Running awscli tests ... done in 5 minutes and 2 seconds
(6/13) Running mc tests ... done in 2 minutes and 4 seconds
(7/13) Running minio-dotnet tests ... done in 31 seconds
(8/13) Running minio-go tests ... done in 6 seconds
(9/13) Running minio-java tests ... done in 37 seconds
(10/13) Running minio-js tests ... FAILED in 51 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-3502b0a3-b129-41d6-b738-f27b8a642d31, events: s3:ObjectCreated:*",
  "duration": 8129,
  "status": "FAIL",
  "error": "Error: notification not received at client.removeObject.err (test/functional-tests.js:1031:43) at ClientRequest.<anonymous> (node_modules/minio/dist/main/minio.js:420:9) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:478:21) at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23) at Socket.socketOnData (_http_client.js:367:20) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at TCP.onread (net.js:559:20)"
}

Executed 9 out of 13 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#4b227d67-c8ce-4ea4-9906-dae077303f0d) |
| mint-gateway-azure.sh | :x: [more...](#d6d78327-a0a1-4db0-9381-b13f4b7b91bf) |
<a name="4b227d67-c8ce-4ea4-9906-dae077303f0d"></a>
### 5889-4d0a751/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30077
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 9a0d1fbeab36:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 1 seconds
(2/13) Running aws-sdk-java tests ... done in 14 seconds
(3/13) Running aws-sdk-php tests ... done in 49 seconds
(4/13) Running aws-sdk-ruby tests ... done in 29 seconds
(5/13) Running awscli tests ... done in 5 minutes and 38 seconds
(6/13) Running mc tests ... done in 1 minutes and 51 seconds
(7/13) Running minio-dotnet tests ... done in 46 seconds
(8/13) Running minio-go tests ... done in 12 seconds
(9/13) Running minio-java tests ... done in 51 seconds
(10/13) Running minio-js tests ... FAILED in 48 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-9ee87b26-242f-4122-a8d8-6870c3c822d7, events: s3:ObjectCreated:*",
  "duration": 13435,
  "status": "FAIL",
  "error": "Error: notification not received at client.removeObject.err (test/functional-tests.js:1031:43) at ClientRequest.<anonymous> (node_modules/minio/dist/main/minio.js:420:9) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:478:21) at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23) at Socket.socketOnData (_http_client.js:367:20) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at TCP.onread (net.js:559:20)"
}

Executed 9 out of 13 tests successfully.
```
<a name="d6d78327-a0a1-4db0-9381-b13f4b7b91bf"></a>
### 5889-4d0a751/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31089
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 16389c4a8631:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 2 seconds
(2/13) Running aws-sdk-java tests ... done in 14 seconds
(3/13) Running aws-sdk-php tests ... done in 42 seconds
(4/13) Running aws-sdk-ruby tests ... done in 36 seconds
(5/13) Running awscli tests ... done in 4 minutes and 21 seconds
(6/13) Running mc tests ... done in 7 minutes and 22 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 19 seconds
(8/13) Running minio-go tests ... done in 1 seconds
(9/13) Running minio-java tests ... done in 32 seconds
(10/13) Running minio-js tests ... FAILED in 2 minutes and 36 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-bcb9badb-1053-41af-bdb9-f062e16f6252",
  "duration": 279,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 9 out of 13 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#e8508158-917e-4cb7-8502-f73f1edbffe7) |
<a name="e8508158-917e-4cb7-8502-f73f1edbffe7"></a>
### 5889-cf4d47c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30847
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 06a1b5c91ed1:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 2 seconds
(2/13) Running aws-sdk-java tests ... done in 18 seconds
(3/13) Running aws-sdk-php tests ... done in 53 seconds
(4/13) Running aws-sdk-ruby tests ... done in 35 seconds
(5/13) Running awscli tests ... done in 4 minutes and 33 seconds
(6/13) Running mc tests ... done in 7 minutes and 14 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 13 seconds
(8/13) Running minio-go tests ... done in 1 seconds
(9/13) Running minio-java tests ... done in 22 seconds
(10/13) Running minio-js tests ... FAILED in 2 minutes and 20 seconds
{
  "name": "minio-js",
  "function": "listObjects(bucketName, prefix, recursive)",
  "args": "bucketName:minio-js-test-66f87a95-5171-4161-9a3a-739d0c3fe0ce, recursive:false",
  "duration": 184,
  "status": "FAIL",
  "error": "Error: listObjects lists 11 objects, expected 10 at Readable.client.listObjects.on.on (test/functional-tests.js:947:23) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 9 out of 13 tests successfully.
```

**Pull request merged**
