### PR TITLE
Add proper requestID for STS errors

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add proper requestID for STS errors

## Motivation and Context
General cleanup following #7232 

## Regression
No

## How Has This Been Tested?
Just using the STS and generating errors.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :x: [more...](#86dd8a15-1863-4282-bd28-dfdf823fde71) |
<a name="86dd8a15-1863-4282-bd28-dfdf823fde71"></a>
### 7245-2b27f21/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31787
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e08fd81d5564:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 2 seconds
(5/13) Running awscli tests ... done in 1 minutes and 43 seconds
(6/13) Running mc tests ... done in 19 seconds
(7/13) Running minio-dotnet tests ... done in 2 minutes and 24 seconds
(8/13) Running minio-go tests ... done in 10 seconds
(9/13) Running minio-java tests ... FAILED in 23 seconds
{
  "name": "minio-java",
  "function": "getObject(String bucketName, String objectName, String filename)",
  "args": "objectName: path/to/minio-java-test-3gmqjej",
  "duration": 201,
  "status": "FAIL",
  "error": "java.net.SocketException: Connection reset >>> [java.net.SocketInputStream.read(SocketInputStream.java:210), java.net.SocketInputStream.read(SocketInputStream.java:141), okio.Okio$2.read(Okio.java:138), okio.AsyncTimeout$2.read(AsyncTimeout.java:236), okio.RealBufferedSource.read(RealBufferedSource.java:45), okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:384), okio.RealBufferedSource$1.read(RealBufferedSource.java:429), java.io.InputStream.read(InputStream.java:101), com.google.common.io.ByteStreams.copy(ByteStreams.java:109), io.minio.MinioClient.getObject(MinioClient.java:1951), FunctionalTest.getObject_test5(FunctionalTest.java:1144), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3154)]"
}

Executed 8 out of 13 tests successfully.
```

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
