### PR TITLE
Allow uploading folders on supported browsers.

### LINKED ISSUE #9619: Web UI: Upload whole folder via drag&drop
Folder upload via drag&drop would be really nice.

### PR DESCRIPTION
**Pull request by darkdragon-001**
## Description
Update `react-dropzone` to version 8 which allows uploading folders via drag&drop on supported browsers.

Currently, there is no way to allow both selection of directories and files in a regular file input, therefore `MainActions` is not modified.

Fixes #9619

## Motivation and Context
Easier than creating folder tree manually and uploading files to every folder.

## How to test this PR?
Open Minio Web UI and drag&drop a folder.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by klauspost** [comment]
@darkdragon-001 Good addition, but please take a look at the [CI failure](https://github.com/minio/minio/runs/685015226), it looks relevant, but I have no idea about the JS parts so I cannot help you.

**Comment by darkdragon-001** [comment]
@klauspost This was the behavior _before_ upgrading node dependency `react-dropzone`. Do I need to change dependencies also at an additional place to `browser/package[-lock].json` for CI?

**Comment by darkdragon-001** [comment]
What is L115 good for?

    dispatch(addUpload(xhr, slug, file.size, file.name))

What is the `slug` for? Only to abort and track the upload? So it can be anything as long as it's unique? What is the `file.name` for? Is it needed or is this specified instead by `uploadUrl`?

**Comment by darkdragon-001** [comment]
I added a compatibility wrapper in the updated commit for the tests (and probably some old browsers).

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Can this be reviewed @kanagarajkm @kaankabalak ?

**Comment by kanagarajkm** [comment]
@darkdragon-001 could you please fix the conflicts?

**Comment by darkdragon-001** [comment]
@kanagarajkm Should be fixed now!

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by kaankabalak** [comment]
Thanks for the PR @darkdragon-001! Would it be possible for you to generate the ui-assets.go file by [running the `npm run release` command inside the browser directory](https://github.com/minio/minio/tree/master/browser#generate-ui-assetsgo), so that the changes in the UI are reflected when the binary is built?

**Comment by harshavardhana** [comment]
> Thanks for the PR @darkdragon-001! Would it be possible for you to generate the ui-assets.go file by [running the `npm run release` command inside the browser directory](https://github.com/minio/minio/tree/master/browser#generate-ui-assetsgo), so that the changes in the UI are reflected when the binary is built?

@kaankabalak generating ui-assets.go is controlled and is done by maintainers or MinIO team members only. If you need to test it locally generate it yourself for now.

**Comment by kaankabalak** [comment]
Whenever the user clicks on the portion which the Dropzone encloses (even when we are not dragging and dropping a file), the file upload system dialog opens. This is not completely desirable as it gets in the way of the user browsing the directories and selecting files because on each click the upload dialog opens.

Screen Shot 2020-05-21 at 5 35 07 PM

Screen Shot 2020-05-21 at 5 33 57 PM

**Comment by darkdragon-001** [comment]
@kaankabalak I was just instructed not to do so https://github.com/minio/minio/pull/9673#issuecomment-632393213

But if you want, I can add a commit with updated ui-assets.go.

**Comment by darkdragon-001** [comment]
@kaankabalak Thanks for testing!

The fix was not very [intuitive](https://github.com/react-dropzone/react-dropzone/issues/541#issuecomment-473106192). Should be fixed now.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by kaankabalak** [comment]
When I run the MinIO server on port 9000 after generating the ui-assets.go file and building the binary with the new ui-assets.go file, when I drag and drop a folder inside a bucket, I get the following error:

```
API: SYSTEM()
Time: 18:34:57 PDT 05/22/2020
DeploymentID: 88249d8b-591f-494a-84a8-88cba4e8c8a0
Error: Object name contains forward slash as pefix: bucket#/folder/image.jpg
       3: github.com/minio/minio@/cmd/web-handlers.go:2235:cmd.toWebAPIError()
       2: github.com/minio/minio@/cmd/web-handlers.go:2245:cmd.writeWebErrorResponse()
       1: github.com/minio/minio@/cmd/web-handlers.go:1146:cmd.(*webAPIHandlers).Upload()
```

However, I am not seeing this error when I use the `npm run dev` command and run the MinIO browser with live reload on port 8080.

**Comment by darkdragon-001** [comment]
@kaankabalak I would be interested to know why `npm run dev` didn't show up this issue. Furthermore, I added a UI fix to handle this problem even though I would prefer the backend to handle prefixes starting with a slash as well.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
@kaankabalak @kanagarajkm is this PR ready?

**Review by kanagarajkm — APPROVED** [review]

**Comment by harshavardhana** [comment]
PTAL @kaankabalak

**Review by kaankabalak — APPROVED** [review]

**Pull request merged**
