### PR TITLE
Fix ignored alias for aggregate result in S3 Select

### PR DESCRIPTION
**Pull request by ryantam626**
## Description

The SQL parser as it stands right now ignores alias for aggregate
result, e.g. `SELECT COUNT(*) AS thing FROM s3object` doesn't actually
return record like `{"thing": 42}`, it returns a record like `{"_1": 42}`.
Column alias for aggregate result is supported in AWS's S3 Select, so
this PR fixes that by respecting the `expr.As` in the expression.

## Motivation and Context

A new SQL parser is added in #7102, there is a small bug with column aliasing with aggregated result (it will be ignored, and the default `_%d` naming is used).

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [X] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by ryantam626** [comment]
~Hello, I have ticked `Unit tests needed`, but I don't read/write Go for a living, any pointers to how to write one? (the `expectedResult` byte seems pretty magical to me in `select_test.go`)~

I have Google'd around and dig around a little bit more, and added a few more test cases with aggregation with alias - hope it conforms to how you guys are doing things here (haven't looked around too much in this repo tbh).

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ef3428ec-f698-4e2a-8f98-138481002451) |
| mint-dist-xl.sh | :x: [more...](#8fe12d92-9eb1-4d9e-ac84-52b9c51c99b3) |
<a name="8fe12d92-9eb1-4d9e-ac84-52b9c51c99b3"></a>
### 7849-4c566c1/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30915
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d492566f7955:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 53 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 52 seconds
(10/14) Running minio-java tests ... FAILED in 47 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName)",
  "duration": 34,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.58:30915/minio-java-test-a06sq3/minio-java-test-39ipdmh?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190628%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190628T103350Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=ccf58f9b55485cd56bb333c0c3ed71956fa5cc4c0c181f1133d0b6e7eab829a1}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-39ipdmh</Key><BucketName>minio-java-test-a06sq3</BucketName><Resource>/minio-java-test-a06sq3/minio-java-test-39ipdmh</Resource><RequestId>15AC5646352ED91E</RequestId><HostId>bea91008-454e-4db7-b2c7-93139bbbf434</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test1(FunctionalTest.java:1767), FunctionalTest.runTests(FunctionalTest.java:2994), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="ef3428ec-f698-4e2a-8f98-138481002451"></a>
### 7849-4c566c1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32002
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cc200b70c6e3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 46 seconds
{
  "name": "mc",
  "duration": "121476",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-16184 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-27830  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-27830/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-27830/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-27830/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-27830/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-27830/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-27830/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-27830/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-27830/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-27830/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-27830/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-27830/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-27830/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-27830/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-27830/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-27830/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 521.99 MiB, Speed: 4.30 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9c980b08-8f19-41b3-92b1-c4ebf3fb69c7) |
| mint-dist-xl.sh | :x: [more...](#3452dff0-d0e8-4420-a186-1ac50fc69ea3) |
<a name="3452dff0-d0e8-4420-a186-1ac50fc69ea3"></a>
### 7849-55934f4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30773
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp db382be1f301:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 54 seconds
(10/14) Running minio-java tests ... FAILED in 40 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 656,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-39g6m5i, objectName=minio-java-test-31uobu7, resource=/minio-java-test-39g6m5i/minio-java-test-31uobu7, requestId=15AC618D62D13B74, hostId=ab711124-c3ab-4649-9920-6b83f630b929)\nrequest={method=DELETE, url=http://72.28.97.61:30773/minio-java-test-39g6m5i/minio-java-test-31uobu7?uploadId=43396789-08fc-4de0-b3d8-ec9e9ab589e2, headers=Host: 72.28.97.61:30773\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190628T140030Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190628/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-28T13-41-17Z\nVary: Origin\nX-Amz-Request-Id: 15AC618D62D13B74\nX-Minio-Deployment-Id: ab711124-c3ab-4649-9920-6b83f630b929\nX-Xss-Protection: 1; mode=block\nDate: Fri, 28 Jun 2019 14:00:31 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="9c980b08-8f19-41b3-92b1-c4ebf3fb69c7"></a>
### 7849-55934f4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30943
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 840891c2a42a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 21 seconds
{
  "name": "mc",
  "duration": "98378",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-24185 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-18978  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-18978/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-18978/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-18978/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-18978/datafile-10-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-18978/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-18978/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-18978/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-18978/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-18978/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-18978/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-18978/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-18978/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-18978/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-18978/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-18978/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 312.74 MiB, Speed: 3.18 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Review by donatello — APPROVED** [review]
LGTM - Thanks for the contribution!

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
