### PR TITLE
avoid attempting to migrate old configs

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
avoid attempting to migrate old configs

## Motivation and Context
instead of migration, move them in memory to a
local representation of new config.

In all other cases re-initialize if config's
missing.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
LGTM. I presume you tested as much as possible.

**Comment by vadmeste** [comment]
I think maybe we should start with adding MinIO version in format.json. It may be useful to prevent direct upgrade from very old versions when we do very old code clean up.

**Review by vadmeste — COMMENTED** [review]
@harshavardhana LGTM, but maybe if we want to just drop support of older config versions to clean up existing code, we can error out after testing on config version (<=33) and tell that the user needs to upgrade to 'RELEASE.2023-04-07T05-28-58Z' first.

**Comment by harshavardhana** [comment]
> @harshavardhana LGTM, but maybe if we want to just drop support of older config versions to clean up existing code, we can error out after testing on config version (<=33) and tell that the user needs to upgrade to 'RELEASE.2023-04-07T05-28-58Z' first.

We can but it's a bunch of stuff to document @vadmeste and confusing. I would like to avoid that completely.

@klauspost I did I will test more, there is one more change missing here. I am removing migration code for credentials based encryption to KMS based.

**Comment by harshavardhana** [comment]
re-did the decryption migration as well, we will never need to migrate any old content, we simply read them always as their original entity.

But let the WRITEs make sure that we write back in the new format, so we do not need to hold
MinIO startup migrating content.

**Review by krisis — APPROVED** [review]

**Pull request merged**
