### PR TITLE
improve server update behavior by re-using memory properly

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
improve server update behavior by re-using memory properly

## Motivation and Context
fixes, slow binary update behavior by reusing memory
and avoiding gob for megabyte streams.

## How to test this PR?
This PR needs https://github.com/minio/minio/pull/18826 to be merged first

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by klauspost** [comment]
Does this on purpose include https://github.com/minio/minio/pull/18826 ?

**Comment by harshavardhana** [comment]
> Does this on purpose include #18826 ?

Yes basically trying to get this in right after that.

**Comment by harshavardhana** [comment]
> Does this on purpose include #18826 ?

Decoupled this PR from #18826 to be self contained

**Review by krisis — APPROVED** [review]

**Review by poornas — APPROVED** [review]

**Review by fwessels — APPROVED** [review]
LGTM

**Pull request merged**
