### PR TITLE
S3 Select: Aggregate AVG/SUM as float

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Force sum/average to be calculated as float.

As noted in #8221

> run `SELECT AVG(CAST (Score as int)) FROM S3Object` on

```
Name,Score
alice,80
bob,81
```

> aws s3 gives 80.5 and minio gives 80.

This also makes overflows much more unlikely.

## Motivation and Context

Make avg/sum more precise and avoid potential int64 overflows.

## How to test this PR?

Test case above

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by klauspost** [comment]
Running on the sample above:
```
λ mc sql -e="SELECT AVG(CAST (Score as int)) FROM S3Object" local/test/avg.csv
80.5
λ mc sql -e="SELECT AVG(Score) FROM S3Object" local/test/avg.csv
80.5
```

It does of course change the output to float, which gives results like this:
```
λ mc sql -e="select COUNT(*), AVG(trip_id) from S3Object" local/test/nyc-taxi-data-10M.csv
10000000,8.3892463718089e+06
```

The pure integer result is `8389246`.

Example of overflow with existing code:
```
λ mc sql -e="select AVG(trip_id*100000000) from S3Object" play/testbucket/nyc-taxi-data-10M.csv
-402218172894
```

Fixed with this PR:
```
λ mc sql -e="select AVG(trip_id*100000000) from S3Object" local/test/nyc-taxi-data-10M.csv
8.389246371807819e+14
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0eed59b6-a517-4638-93ef-82bd733d1cfe) |
| mint-compression-dist-xl.sh | :x: [more...](#8dcdf4a7-378a-4377-b2d8-128b4fe503ae) |
| mint-dist-xl.sh | :x: [more...](#95ffd2dd-c9d2-44d5-a9b4-c55b606b8b53) |
<a name="8dcdf4a7-378a-4377-b2d8-128b4fe503ae"></a>
### 8326-64cc741/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31325
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 34ba93b50f9e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 52 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 36 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 8 seconds
(11/14) Running minio-js tests ... done in 55 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 31 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "duration": 113,
  "args": {
    "presigned_get_object_url": "http://72.28.97.52:31325/minio-py-test-5e2fc205-9a70-4aae-96e3-9fa13dfe646a/97565860-5273-4f3a-90cb-f151ae1d099f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190927%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190927T181544Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=52b3966c410c7a4161e0f0a80d71e3b3d779f920b1778ae7b87fee780cf64cda",
    "bucket_name": "minio-py-test-5e2fc205-9a70-4aae-96e3-9fa13dfe646a",
    "object_name": "97565860-5273-4f3a-90cb-f151ae1d099f"
  },
  "name": "minio-py:test_presigned_get_object_response_headers",
  "status": "FAIL",
  "message": "'content-language'",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="95ffd2dd-c9d2-44d5-a9b4-c55b606b8b53"></a>
### 8326-64cc741/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31246
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e3789331070b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 5 seconds
(8/14) Running minio-dotnet tests ... done in 45 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 29 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 58 seconds
(11/14) Running minio-js tests ... done in 55 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 18 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1168, in test_list_objects_with_1001_files\n    client.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 416, in remove_bucket\n    self._url_open('DELETE', bucket_name=bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1951, in _url_open\n    object_name).get_exception()\nminio.error.BucketNotEmpty: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2024, in main\n    test_list_objects_with_1001_files(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1170, in test_list_objects_with_1001_files\n    raise Exception(err)\nException: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n",
  "status": "FAIL",
  "function": "list_objects(bucket_name, prefix, recursive)",
  "message": "BucketNotEmpty: message: The bucket you tried to delete is not empty.",
  "args": {
    "bucket_name": "minio-py-test-a394e8f3-836d-4797-a957-0b3741fc9680",
    "object_name": "3372a4b1-a834-41f6-aeda-20af31a6f389_0 ~ 3372a4b1-a834-41f6-aeda-20af31a6f389_1000"
  },
  "duration": 168709
}

Executed 11 out of 14 tests successfully.
```
<a name="0eed59b6-a517-4638-93ef-82bd733d1cfe"></a>
### 8326-64cc741/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30831
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 28c40d30989d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 38 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 6 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 38 seconds
{
  "args": {},
  "duration": 95533,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#99a4d0a0-0700-403b-bcd0-5649f81d21d9) |
| mint-large-bucket.sh | :x: [more...](#5ef5f627-8bdd-429c-b736-41513cec7b77) |
<a name="5ef5f627-8bdd-429c-b736-41513cec7b77"></a>
### 8326-17f5681/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30869
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 16288804f955:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 25 seconds
(8/14) Running minio-dotnet tests ... done in 2 minutes and 9 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 28 seconds
{
  "args": {},
  "duration": 126810,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="99a4d0a0-0700-403b-bcd0-5649f81d21d9"></a>
### 8326-17f5681/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30884
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7eb132554bc3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ug3ogihi60h5as",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365609,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C862AEF05E214B, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by donatello — APPROVED** [review]
LGTM

**Pull request merged**
