### PR TITLE
remove OSS gateway due to lack of licensing

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
remove OSS gateway due to lack of licensing

## Motivation and Context
OSS go sdk lacks licensing terms in their
repository, and there has been no activity

On the issue here https://github.com/aliyun/aliyun-oss-go-sdk/issues/245

This PR is to ensure we remove any dependency code which
lacks explicit license file in their repo.

## How to test this PR?
Nothing special to test

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#9c650c0a-53ed-46b9-8f85-fa4d6541c107) |
| mint-gateway-nas.sh | :x: [more...](#abf176a3-3188-418f-9bce-589525de319d) |
<a name="abf176a3-3188-418f-9bce-589525de319d"></a>
### 9390-6293993/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31407
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ec5876377578:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 33 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... FAILED in 34 seconds
{}

Executed 8 out of 15 tests successfully.
```
<a name="9c650c0a-53ed-46b9-8f85-fa4d6541c107"></a>
### 9390-6293993/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30952
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e47333b7daaf:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 5 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... FAILED in 52 seconds
{
  "name": "awscli",
  "duration": 4914,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:30952 s3api head-object --bucket awscli-mint-test-bucket-12197 --key datafile-1-kB-copy\n",
  "status": "FAIL",
  "error": "StorageClass was not applied"
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by nitisht — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by jhagege** [comment]
Hi @harshavardhana  , there is a MIT license in the repository, see here: https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/LICENSE
Can you please bring back support in MinIO ? 
Please let me know if I can assist anyway, thanks much.

**Comment by harshavardhana** [comment]
> Hi @harshavardhana , there is a MIT license in the repository, see here: https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/LICENSE
> Can you please bring back support in MinIO ?
> Please let me know if I can assist anyway, thanks much.

The library is super confusing it has an MIT license in the repo now, and the readme.md states Apache 2.0 

For now it's not possible for us to bring it back @jhagege you may use older releases. There is nothing new we added to oss gateway.

**Comment by franklouwers** [comment]
I opened a PR https://github.com/aliyun/aliyun-oss-go-sdk/pull/252 Once it's merged, please reconsider adding OSS support.

**Comment by harshavardhana** [comment]
> I opened a PR [aliyun/aliyun-oss-go-sdk#252](https://github.com/aliyun/aliyun-oss-go-sdk/pull/252) Once it's merged, please reconsider adding OSS support.

We would love to but it's generally a burden for us to maintain @franklouwers , right now there is no real need for us from our customers. If that is a possibility in future we may bring it back.

**Comment by jhagege** [comment]
@harshavardhana 
We would like to build a solution based on Kubeflow Pipelines with Minio on OSS as a backbone for artifact storage. 
Are you aware of an alternative mechanism to support this use case in Minio ? 
Thanks.

**Comment by harshavardhana** [comment]
> @harshavardhana 
> We would like to build a solution based on Kubeflow Pipelines with Minio on OSS as a backbone for artifact storage. 
> Are you aware of an alternative mechanism to support this use case in Minio ? 
> Thanks.

Yes you can use the older releases of MinIO @jhagege which still have OSS gateway

**Pull request merged**
