### PR TITLE
azure: When container access type is private treat as no policy set

### PR DESCRIPTION
**Pull request by poornas**
## Description

Azure gateway's response to GetBucketPolicies call is not consistent with 
S3 and server response when a bucket does not have a public policy 
defined for it. Both S3 And minio server respond with NoSuchBucketPolicy 
error, which is interpeted by the client SDK's as policy type None
In the case of Azure, by default container is set to access private 
meaning no anonymous access.  Azure gateway currently returns 
a policy object with empty statements when container is private 
access. Instead it should be interpreted as policy not found. 

## Motivation and Context
 

Azure gateway and minio server handling of GetBucketPolicies needs to be consistent . See #4718 

## How Has This Been Tested?

Manually by running server in gateway mode for azure and testing with minio-py client SDK to connect to server and get bucket policy for a newly created bucket with no policy defined on it.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
@poornas you can keep the PR title to be more concise and not exceed 50 characters. This PR if you see has wrapped around in a weird manner and overflowed into the description of the PR.

**Review by harshavardhana — CHANGES_REQUESTED** [review]
@poornas you can keep the PR title to be more concise and not exceed 50 characters. This PR if you see has wrapped around in a weird manner and overflowed into the description of the PR.

PR title not just github PR title, you would need to fix also your commit message.

**Review by krishnasrinivas — APPROVED** [review]

**Review by harshavardhana — COMMENTED** [review]
@poornas have you seen my previous comment?

**Comment by poornas** [comment]
@harshavardhana , updated commit as well.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
