### PR TITLE
Filter listing buckets based on user level access

### LINKED ISSUE #6701: Minio Browser with canned bucket policy shows bucket list
Setup a canned policy per bucket for a user

## Expected Behavior
When logged on as the user, expected to see only the bucket in policy listed

## Current Behavior
All buckets are listed, with the message "Not enough permissions", when clicking on other buckets

## Steps to Reproduce (for bugs)
1. create policy file
`{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"s3:GetObject",
"s3:GetBucketLocation"
],
"Effect": "Allow",
"Resource": [
"arn:aws:s3:::023960535/*",
"arn:aws:s3:::023960535"
],
"Sid": "Public"
}
]
}`

2. create policy
`mc admin policies add minio 023960535 023960535.json`
3. create user
`mc admin users add minio 023960535 UxZTWa3MIQ 023960535`
4. access from minio browser
right bucket, can list files
wrong bucket: Don't have enough permissions to access this resource

## Context
different users should not see the bucket list of other users

## Your Environment
Docker minio, RELEASE.2018-10-25T01-27-03Z
screen shot 2018-10-25 at 1 27 20 am
screen shot 2018-10-25 at 1 28 34 am

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Filter listing buckets based on user level access

## Motivation and Context
Fixes #6701

## Regression
No

## How Has This Been Tested?
Setup a new policy
```
~ mc admin policy list myminio getonly
{"ID":"Policy1544228582829","Version":"2012-10-17","Statement":[{"Sid":"Stmt1544228580208","Effect":"Allow","Action":["s3:GetObject"],"Resource":["arn:aws:s3:::testbucket100/*"]}]}
```

```
~ mc admin user add myminio foobar foo12345 getonly
```

Create a set of buckets with admin credentials
```
~ mc mb myminio/testbucket{1..100}
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by nitisht — APPROVED** [review]
LGTM & Tested

**Review by poornas — APPROVED** [review]
LGTM

**Comment by ihamouda** [comment]
@harshavardhana 
thank you for finishing that
another problem arise though in distributed environment.
i have a distributed minio of 4 nodes in docker swarm, load balanced by traefik.
mc is configured pointing to traefik
i create the policy successfully, but it doesn't propagate to all the nodes, so when I try to create the user after that, I guess the command goes to another node where the policy is not there and it fails.

I confirmed this by doing mc policy list 4 times, the policy appears only once due to the round robin nature of traefik

do I open a new bug for that?

thanks again

**Comment by ihamouda** [comment]
@harshavardhana 
by the way it happens when adding the user too
propagation takes very long time to reach the other servers, average of 5 minutes

**Comment by harshavardhana** [comment]
Every 5 minutes there is a reload function so in distributed setup it takes 5 mins to propagate new users to neighboring nodes @ihamouda - we can definitely make it faster. But is it not acceptable to wait 5 mins ?

**Comment by ihamouda** [comment]
if you are scripting the creation of policy and user 5 minutes is too much
another solution will be adding a new mc command to do it in one step, is that possible?

**Comment by harshavardhana** [comment]
> another solution will be adding a new mc command to do it in one step, is that possible?

We will fix it as per https://github.com/minio/minio/issues/6957

**Comment by ihamouda** [comment]
@harshavardhana thank you for all your hard work

**Pull request merged**
