### PR TITLE
avoid calling 'admin info' for disk, cpu, net metrics collection

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
avoid calling 'admin info' for disk, cpu, net metrics collection

## Motivation and Context
resource metrics collection was incorrectly making fan-out 
liveness peer calls where it's not needed.

## How to test this PR?
In a distributed setup, observe that every minute when a node
is down, an odd log keeps populating the server log.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by klauspost — APPROVED** [review]
LGTM

**Review by anjalshireesh — APPROVED** [review]
LGTM, tested

**Review by shtripat — APPROVED** [review]
Changes looks fine.
To test I deployed a 4 node kind based setup and after loading few objects to a bucket, cordoned one node to make sure one MinIO pod doesnt come online. The logs I can see in pod logs are
```
│ API: SYSTEM.peers                                                                                                                                                         │
│ Time: 12:39:44 UTC 05/17/2024                                                                                                                                             │
│ DeploymentID: 9b5ce32d-d669-401d-82c3-0970f508058d                                                                                                                        │
│ Error: Drive: https://myminio-pool-0-3.myminio-hl.tenant-lite.svc.cluster.local:9000/export1 returned drive not found (*fmt.wrapError)                                    │
│        endpoint="https://myminio-pool-0-3.myminio-hl.tenant-lite.svc.cluster.local:9000/export1"                                                                          │
│        4: internal/logger/logger.go:258:logger.LogAlwaysIf()                                                                                                              │
│        3: cmd/logging.go:55:cmd.peersLogAlwaysIf()                                                                                                                        │
│        2: cmd/prepare-storage.go:51:cmd.init.func22.1()                                                                                                                   │
│        1: cmd/erasure-sets.go:239:cmd.(*erasureSets).connectDisks.func2()                                                                                                 │
│                                                                                                                                                                           │
│ API: StorageInfo                                                                                                                                                          │
│ Time: 12:46:25 UTC 05/17/2024                                                                                                                                             │
│ DeploymentID: 9b5ce32d-d669-401d-82c3-0970f508058d                                                                                                                        │
│ RequestID: 17D0476B4D42625E                                                                                                                                               │
│ RemoteHost: 10.244.1.2                                                                                                                                                    │
│ Host: myminio-pool-0-0.myminio-hl.tenant-lite.svc.cluster.local:9000                                                                                                      │
│ UserAgent: MinIO (linux; amd64) madmin-go/2.0.0                                                                                                                           │
│ Error: remote disconnected (grid.RemoteErr)                                                                                                                               │
│        5: internal/logger/logger.go:268:logger.LogIf()                                                                                                                    │
│        4: cmd/logging.go:36:cmd.adminLogIf()                                                                                                                              │
│        3: cmd/admin-handlers.go:1438:cmd.getAggregatedBackgroundHealState()                                                                                               │
│        2: cmd/admin-handlers.go:676:cmd.adminAPIHandlers.StorageInfoHandler()                                                                                             │
│        1: net/http/server.go:2166:http.HandlerFunc.ServeHTTP()   
```

**Pull request merged**
