### PR TITLE
Fix: send decrypted size to notification event

### LINKED ISSUE #7236: When auto-encryption is enabled, mc mirror --w doesn't work properly
## Expected Behavior
`mc mirror -w` should work properly when auto-encryption is enabled.

## Current Behavior
`mc mirror -w` fails with the following error:

```
mc: <ERROR> Failed to copy `https://192.168.1.121:9000/vadmeste/Dockerfile`. Input reader closed pre-maturely. Expected `584` bytes, but only received `552` bytes.
```

## Possible Solution
Most likely the object size reported in event notification is incorrect and should be fixed.

## Steps to Reproduce (for bugs)
Terminal 1: 
`$   MINIO_SSE_AUTO_ENCRYPTION=on minio server /tmp/fs`

Terminal 2:
1. `mc mb myminio/testbucket`
2. `mkdir /tmp/target/`
3. `mc mirror -w myminio/testbucket /tmp/target`

Terminal 3:
1. `mc cp file myminio/testbucket/`

## Context
Trying to accomplish a mirror

## Regression
Auto encryption is fairly new, there is no real regression.

## Your Environment
All

### PR DESCRIPTION
**Pull request by poornas**
## Description

Send decrypted size of object to notification events if uploading object with encryption
## Motivation and Context

Fixes #7236  
## Regression
 No

## How Has This Been Tested?

Follow steps in issue 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_exclamation_mark: [more...](#0201aa89-7829-4a58-bf6d-436407d3fbbe) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#9769d53c-776f-4462-ac3b-5c4d598740b0) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#a53445b9-873a-4b3c-9f9f-7e110287b646) |
| mint-compression-dist-xl.sh | :heavy_exclamation_mark: [more...](#d5d41416-5a4d-4605-8fe9-59dbb312f969) |
| mint-compression-fs.sh | :heavy_exclamation_mark: [more...](#0cb7bce9-f9fc-42ed-9d11-2be774e3d7b6) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#52bcd74a-df98-4361-86b0-93bf31898587) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#3a23df82-2bc5-45a7-ad39-8cdc3d5cfc38) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#4061c881-ef96-4645-8e8b-9cc5fb29c451) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#0cd5d813-55a1-450d-a19c-e3f80fe7cb66) |
<a name="0201aa89-7829-4a58-bf6d-436407d3fbbe"></a>
### 7248-d4a2c1b/mint-compression-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0cd5d813-55a1-450d-a19c-e3f80fe7cb66"></a>
### 7248-d4a2c1b/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="3a23df82-2bc5-45a7-ad39-8cdc3d5cfc38"></a>
### 7248-d4a2c1b/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="d5d41416-5a4d-4605-8fe9-59dbb312f969"></a>
### 7248-d4a2c1b/mint-compression-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="4061c881-ef96-4645-8e8b-9cc5fb29c451"></a>
### 7248-d4a2c1b/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="52bcd74a-df98-4361-86b0-93bf31898587"></a>
### 7248-d4a2c1b/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="9769d53c-776f-4462-ac3b-5c4d598740b0"></a>
### 7248-d4a2c1b/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a53445b9-873a-4b3c-9f9f-7e110287b646"></a>
### 7248-d4a2c1b/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0cb7bce9-f9fc-42ed-9d11-2be774e3d7b6"></a>
### 7248-d4a2c1b/mint-compression-fs.sh.xtrace:
```
DISABLED TIME BEING
```

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 7248-f708391/gopath/src/github.com/minio
+ git -C 7248-f708391/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 7248-f708391/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 7248-f708391/gopath/src/github.com/minio/minio fetch --quiet minio pull/7248/head:pr7248
+ git -C 7248-f708391/gopath/src/github.com/minio/minio checkout --quiet pr7248
+ GOPATH=/mnt/nvme/mint-auto/7248-f708391/gopath
+ make -C 7248-f708391/gopath/src/github.com/minio/minio --quiet
make: go: Command not found
make: go: Command not found
make: *** [checks] Error 1

```

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 7248-f708391/gopath/src/github.com/minio
+ git -C 7248-f708391/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
fatal: destination path 'minio' already exists and is not an empty directory.

```

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 7248-f708391/gopath/src/github.com/minio
+ git -C 7248-f708391/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
fatal: destination path 'minio' already exists and is not an empty directory.

```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by harshavardhana — APPROVED** [review]
LGTM - tested works properly now.

**Review by aead — APPROVED** [review]

**Pull request merged**
