### PR TITLE
[WIP] move bit-rot to per block

### LINKED ISSUE #5526: Bring bit-rot closer to erasure blocks instead of entire parts
** on purpose not using templates **

Bit-rot in current implementation computes for the entire part of the erasure coded file, this leaves room for bit-rot to occur on subsequent operations since we have discarded the data that we read.

Implement bit-rot to be more stricter for each block that is read from the backend. For this we need to implement and bring in bit-rot computed per erasure block size. This is to ensure that each block that was read and transferred over the network is always going to be the correct block from the backend. 

This requires us to implement a change in our `xl.json` to hold hashes for multiple erasureBlockSize blocks and should be verified as each block is decoded.

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #5526

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5532-3951325/gopath/src/github.com/minio
+ git -C 5532-3951325/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5532-3951325/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5532-3951325/gopath/src/github.com/minio/minio fetch --quiet minio pull/5532/head:pr5532
+ git -C 5532-3951325/gopath/src/github.com/minio/minio checkout --quiet pr5532
+ GOPATH=/home/bala/mintauto/5532-3951325/gopath
+ make -C 5532-3951325/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/xl-v1-metadata.go:86:17: duplicate key HighwayHash256G in map literal
make: *** [build] Error 2

```

**Comment by krishnasrinivas** [comment]
@harshavardhana 
```
krishna@escape:~/go/src/github.com/minio/minio$ go install
# github.com/minio/minio/cmd
cmd/xl-v1-metadata.go:86:17: duplicate key HighwayHash256G in map literal
krishna@escape:~/go/src/github.com/minio/minio$ 
```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5532-76d1b6a/gopath/src/github.com/minio
+ git -C 5532-76d1b6a/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5532-76d1b6a/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5532-76d1b6a/gopath/src/github.com/minio/minio fetch --quiet minio pull/5532/head:pr5532
+ git -C 5532-76d1b6a/gopath/src/github.com/minio/minio checkout --quiet pr5532
+ GOPATH=/home/bala/mintauto/5532-76d1b6a/gopath
+ make -C 5532-76d1b6a/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/xl-v1-metadata.go:86:17: duplicate key HighwayHash256G in map literal
make: *** [build] Error 2

```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#94125585-7883-492f-954e-1fe428e659a1) |
| mint-dist-xl.sh | :x: [more...](#7b26f629-97bf-48cd-8d85-608b4a6241d3) |
<a name="7b26f629-97bf-48cd-8d85-608b4a6241d3"></a>
### 5532-31b97fd/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30100
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp a2351abb4d67:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-i5raiqwvt2tfpq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 367,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30100/aws-sdk-go-test-i5raiqwvt2tfpq: dial tcp 192.168.122.45:30100: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```
<a name="94125585-7883-492f-954e-1fe428e659a1"></a>
### 5532-31b97fd/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32743
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp b864cd4dd716:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 0 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 1 seconds
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "http://minikube:32743/aws-sdk-php-5a879165b1ff7/obj1"; AWS HTTP error: Server error: `PUT http://minikube:32743/aws-sdk-php-5a879165b1ff7/obj1` resulted in a `500 Internal Server Error` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, pleas (truncated...)
 InternalError (server): We encountered an internal error, please try again. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key></Key><BucketName></BucketName><Resource>/aws-sdk-php-5a879165b1ff7/obj1</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>'

GuzzleHttp\Exception\ServerException: Server error: `PUT http://minikube:32743/aws-sdk-php-5a879165b1ff7/obj1` resulted in a `500 Internal Server Error` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalErr in /mint/run/core/aws-sdk-php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 191

Executed 1 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#332b5a71-a328-4948-b409-c5e54cc48750) |
| mint-dist-xl.sh | :x: [more...](#672a7caa-7951-45df-8cc9-ccca1a701984) |
<a name="672a7caa-7951-45df-8cc9-ccca1a701984"></a>
### 5532-bf3ae18/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31432
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp afb401212b66:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-h1hizwii6ytip1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 393,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:31432/aws-sdk-go-test-h1hizwii6ytip1: dial tcp 192.168.122.45:31432: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```
<a name="332b5a71-a328-4948-b409-c5e54cc48750"></a>
### 5532-bf3ae18/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30766
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp f7e433b99fd3:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 0 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 1 seconds
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "http://minikube:30766/aws-sdk-php-5a8a9a86a87f3/obj1"; AWS HTTP error: Server error: `PUT http://minikube:30766/aws-sdk-php-5a8a9a86a87f3/obj1` resulted in a `500 Internal Server Error` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, pleas (truncated...)
 InternalError (server): We encountered an internal error, please try again. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key></Key><BucketName></BucketName><Resource>/aws-sdk-php-5a8a9a86a87f3/obj1</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>'

GuzzleHttp\Exception\ServerException: Server error: `PUT http://minikube:30766/aws-sdk-php-5a8a9a86a87f3/obj1` resulted in a `500 Internal Server Error` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalErr in /mint/run/core/aws-sdk-php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 191

Executed 1 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#3e339b1a-3119-4fcd-90e6-521932841e28) |
| mint-dist-xl.sh | :x: [more...](#03b9d3ba-cc98-411c-a9ce-51161533ab7f) |
<a name="3e339b1a-3119-4fcd-90e6-521932841e28"></a>
### 5532-e5187a9/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32422
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 1faf5497055f:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 1 seconds
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "http://minikube:32422/aws-sdk-php-5a8c70f853954/obj1"; AWS HTTP error: Server error: `PUT http://minikube:32422/aws-sdk-php-5a8c70f853954/obj1` resulted in a `500 Internal Server Error` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, pleas (truncated...)
 InternalError (server): We encountered an internal error, please try again. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key></Key><BucketName></BucketName><Resource>/aws-sdk-php-5a8c70f853954/obj1</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>'

GuzzleHttp\Exception\ServerException: Server error: `PUT http://minikube:32422/aws-sdk-php-5a8c70f853954/obj1` resulted in a `500 Internal Server Error` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalErr in /mint/run/core/aws-sdk-php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 191

Executed 1 out of 12 tests successfully.
```
<a name="03b9d3ba-cc98-411c-a9ce-51161533ab7f"></a>
### 5532-e5187a9/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30089
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 54bef479e2b9:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-duywd0p0s40ep6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 363,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30089/aws-sdk-go-test-duywd0p0s40ep6: dial tcp 192.168.122.45:30089: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5532-65a20d2/gopath/src/github.com/minio
+ git -C 5532-65a20d2/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5532-65a20d2/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5532-65a20d2/gopath/src/github.com/minio/minio fetch --quiet minio pull/5532/head:pr5532
+ git -C 5532-65a20d2/gopath/src/github.com/minio/minio checkout --quiet pr5532
+ GOPATH=/home/bala/mintauto/5532-65a20d2/gopath
+ make -C 5532-65a20d2/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/erasure-readfile.go:116:1: missing return at end of function
make: *** [build] Error 2

```

**Pull request closed without merging**
