### PR TITLE
fix: delete globalProfiler should lock

### PR DESCRIPTION
**Pull request by jiuker**
delete globalProfiler should lock

## Description

delete globalProfiler should lock

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
The locking is wrong here, we should make it a bit more granular here and peer-specific. Let's fix this properly.

**Comment by jiuker** [comment]
> The locking is wrong here, we should make it a bit more granular here and peer-specific. Let's fix this properly.

But it does look like it has to be locked to work, is that because the delete logic shouldn't be performed here? Because I've seen other places where this deletion is performed that require a lock. @harshavardhana

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Let's merge this PR and work on improving the locking for profiler.

**Pull request merged**
