### PR TITLE
Reconstruct only missing data shards when reading erasure coded file

### PR DESCRIPTION
**Pull request by fwessels**
Building on PR #4683, this is an optimization to only reconstruct any missing data blocks when reading an erasure coded file.

NB Do not merge (yet), we should probably see if we can get the ReconstructMissingData method implemented in the official repo from @klauspost 

## Motivation and Context
Optimization to not reconstruct any parity blocks that are not used anyway.

## How Has This Been Tested?
Tested manually.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by klauspost** [comment]
I would have no problems with this. `ReconstructMissingData` -> `ReconstructData` would be preferred. After all "Reconstruct" already implies that data is missing.

It would be nice if [`SteamEncoder.Reconstruct`](https://godoc.org/github.com/klauspost/reedsolomon#StreamEncoder) could expose this functionality (allowing fill parity shards to be nil, would not reconstruct them). But I would still happily accept a PR, even if it didn't include it.

**Comment by fwessels** [comment]
@klauspost Great to hear, we will prepare a PR along those lines.

**Comment by fwessels** [comment]
@klauspost see PR https://github.com/klauspost/reedsolomon/pull/57

**Comment by harshavardhana** [comment]
@fwessels can you run `gofmt` looks like travis is failing for this..

**Comment by harshavardhana** [comment]
> @fwessels can you run gofmt looks like travis is failing for this..

^^ in-case you forgot this message.

**Comment by fwessels** [comment]
Closing this PR as PR for erasure coding updates will bring this in.

**Pull request closed without merging**
