### PR TITLE
Fix misspelling of Certbot

### PR DESCRIPTION
**Pull request by justinclift**
## Description
A somewhat important typo fix in one of the docs.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :x: [more...](#7919a9d5-398a-4693-807c-d18e3fe22adc) |
| mint-large-bucket.sh | :x: [more...](#bd902242-c2ce-4439-b23d-3a4fd943c127) |
| mint-fs.sh | :x: [more...](#0c7b46f5-e8bf-49ec-8ac7-3f31c28fc900) |
| mint-dist-xl.sh | :x: [more...](#d137a30f-2f12-45a5-bf9a-25970fbaf161) |
| mint-gateway-s3.sh | :x: [more...](#f9813ec5-f5d7-47a5-91d7-7432453cc76f) |
| mint-gateway-azure.sh | :x: [more...](#a958584e-9ae7-4a0c-8043-904af2100c9f) |
| mint-gateway-nas.sh | :x: [more...](#560f6ffe-adc0-4060-ab70-c8e97386ba47) |
<a name="a958584e-9ae7-4a0c-8043-904af2100c9f"></a>
### 9705-17ff604/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32647
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fa62d2816028:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 2 minutes and 53 seconds
{
  "name": "aws-sdk-php",
  "function": "headObject ( array $params = [] )",
  "args": {
    "aws-sdk-php-5eccb2abc504a": "obj1",
    "aws-sdk-php-5eccb2abc504c": "obj2"
  },
  "duration": "82",
  "status": "FAIL",
  "error": "headObject API Metadata didn't match for aws-sdk-php-5eccb2abc504a/obj1"
}
(3/15) Running aws-sdk-ruby tests ... done in 15 seconds
(4/15) Running awscli tests ... done in 2 minutes and 48 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 47 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 32 seconds
(8/15) Running minio-go tests ... done in 4 minutes and 19 seconds
(9/15) Running minio-java tests ... done in 25 minutes and 56 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 40 seconds
(11/15) Running minio-py tests ... done in 10 minutes and 3 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 23 seconds
(13/15) Running s3select tests ... done in 1 minutes and 0 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="bd902242-c2ce-4439-b23d-3a4fd943c127"></a>
### 9705-17ff604/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31187
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 01cfb7785499:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-php",
  "function": "headObject ( array $params = [] )",
  "args": {
    "aws-sdk-php-5eccb2a864e16": "obj1",
    "aws-sdk-php-5eccb2a864e17": "obj2"
  },
  "duration": "17",
  "status": "FAIL",
  "error": "headObject API Metadata didn't match for aws-sdk-php-5eccb2a864e16/obj1"
}
(3/15) Running aws-sdk-ruby tests ... done in 8 seconds
(4/15) Running awscli tests ... done in 2 minutes and 32 seconds
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 1 minutes and 4 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 26 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 45 seconds
(9/15) Running minio-java tests ... done in 6 minutes and 57 seconds
(10/15) Running minio-js tests ... done in 55 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 1 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 12 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="f9813ec5-f5d7-47a5-91d7-7432453cc76f"></a>
### 9705-17ff604/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32124
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7cc95e216111:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "name": "aws-sdk-php",
  "function": "headObject ( array $params = [] )",
  "args": {
    "aws-sdk-php-5eccb2a47fe5b": "obj1",
    "aws-sdk-php-5eccb2a47fe5d": "obj2"
  },
  "duration": "3",
  "status": "FAIL",
  "error": "headObject API Metadata didn't match for aws-sdk-php-5eccb2a47fe5b/obj1"
}
(3/15) Running aws-sdk-ruby tests ... done in 2 seconds
(4/15) Running awscli tests ... done in 2 minutes and 6 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 42 seconds
(7/15) Running minio-dotnet tests ... done in 31 seconds
(8/15) Running minio-go tests ... done in 43 seconds
(9/15) Running minio-java tests ... done in 35 seconds
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 58 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 2 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="d137a30f-2f12-45a5-bf9a-25970fbaf161"></a>
### 9705-17ff604/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32503
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 55956b66548f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "headObject ( array $params = [] )",
  "args": {
    "aws-sdk-php-5eccb2a614288": "obj1",
    "aws-sdk-php-5eccb2a614289": "obj2"
  },
  "duration": "8",
  "status": "FAIL",
  "error": "headObject API Metadata didn't match for aws-sdk-php-5eccb2a614288/obj1"
}
(3/15) Running aws-sdk-ruby tests ... done in 4 seconds
(4/15) Running awscli tests ... done in 2 minutes and 23 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 56 seconds
(7/15) Running minio-dotnet tests ... done in 48 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 26 seconds
(9/15) Running minio-java tests ... done in 2 minutes and 14 seconds
(10/15) Running minio-js tests ... done in 57 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 55 seconds
(12/15) Running s3cmd tests ... done in 29 seconds
(13/15) Running s3select tests ... done in 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="7919a9d5-398a-4693-807c-d18e3fe22adc"></a>
### 9705-17ff604/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32381
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 39a4322e5cc5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "headObject ( array $params = [] )",
  "args": {
    "aws-sdk-php-5eccb2a508c21": "obj1",
    "aws-sdk-php-5eccb2a508c22": "obj2"
  },
  "duration": "4",
  "status": "FAIL",
  "error": "headObject API Metadata didn't match for aws-sdk-php-5eccb2a508c21/obj1"
}
(3/15) Running aws-sdk-ruby tests ... done in 2 seconds
(4/15) Running awscli tests ... done in 2 minutes and 11 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 50 seconds
(7/15) Running minio-dotnet tests ... done in 32 seconds
(8/15) Running minio-go tests ... done in 40 seconds
(9/15) Running minio-java tests ... done in 50 seconds
(10/15) Running minio-js tests ... done in 57 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 54 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="560f6ffe-adc0-4060-ab70-c8e97386ba47"></a>
### 9705-17ff604/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32697
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 46b3a59083bb:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "name": "aws-sdk-php",
  "function": "headObject ( array $params = [] )",
  "args": {
    "aws-sdk-php-5eccb2a4a5fb4": "obj1",
    "aws-sdk-php-5eccb2a4a5fb5": "obj2"
  },
  "duration": "2",
  "status": "FAIL",
  "error": "headObject API Metadata didn't match for aws-sdk-php-5eccb2a4a5fb4/obj1"
}
(3/15) Running aws-sdk-ruby tests ... done in 2 seconds
(4/15) Running awscli tests ... done in 2 minutes and 5 seconds
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 41 seconds
(7/15) Running minio-dotnet tests ... done in 30 seconds
(8/15) Running minio-go tests ... done in 39 seconds
(9/15) Running minio-java tests ... done in 23 seconds
(10/15) Running minio-js tests ... FAILED in 14 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-27e30d8e-ceb1-4d9a-b4bc-3dd23eb63552",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(10/15) Running minio-py tests ... done in 1 minutes and 5 seconds
(11/15) Running s3cmd tests ... done in 15 seconds
(12/15) Running s3select tests ... done in 2 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="0c7b46f5-e8bf-49ec-8ac7-3f31c28fc900"></a>
### 9705-17ff604/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30194
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 04927c1bb210:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "name": "aws-sdk-php",
  "function": "headObject ( array $params = [] )",
  "args": {
    "aws-sdk-php-5eccb2a43946b": "obj1",
    "aws-sdk-php-5eccb2a43946c": "obj2"
  },
  "duration": "2",
  "status": "FAIL",
  "error": "headObject API Metadata didn't match for aws-sdk-php-5eccb2a43946b/obj1"
}
(3/15) Running aws-sdk-ruby tests ... done in 2 seconds
(4/15) Running awscli tests ... done in 2 minutes and 5 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 43 seconds
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... done in 45 seconds
(9/15) Running minio-java tests ... done in 27 seconds
(10/15) Running minio-js tests ... done in 44 seconds
(11/15) Running minio-py tests ... done in 56 seconds
(12/15) Running s3cmd tests ... done in 14 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
@justinclift please push again so that CI/CD can be rebuilt fixed an image issue on the backend

**Comment by justinclift** [comment]
No worries, looks like the CI/CD worked this time around. :wink:

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#a820b038-f5ab-4b76-bbc4-f79bbce1ed7b) |
<a name="a820b038-f5ab-4b76-bbc4-f79bbce1ed7b"></a>
### 9705-0da8dcd/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31388
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9d57e3c4e1f6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 22 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... done in 38 seconds
(10/15) Running minio-java tests ... done in 24 seconds
(11/15) Running minio-js tests ... FAILED in 18 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-5a0135f0-785f-47e5-ae06-336bf8079be6",
  "duration": 9,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 1 minutes and 16 seconds
(12/15) Running s3cmd tests ... done in 17 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by justinclift** [comment]
Hmmm, this is feeling like GlusterFS CI/CD all over again. :scream:

Guessing it needs to be resubmitted a 3rd time? :wink:

**Review by klauspost — APPROVED** [review]
:D

**Comment by harshavardhana** [comment]
> Hmmm, this is feeling like GlusterFS CI/CD all over again. 
> 
> Guessing it needs to be resubmitted a 3rd time?

@justinclift no this is good.

**Comment by justinclift** [comment]
Cool. :smile:

**Pull request merged**
