### PR TITLE
do not assume invalid buf to be non-xl.meta

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
do not assume invalid buf to be non-xl.meta

## Motivation and Context
it is important not to assume on the buffer
value read from disk to be authoritative
enough to issue deletes on the namespace,

cautiously decide it based on successful
read of 'xl.json', also use LoadOrConvert()
for cleaner parsing of `buf` before making
further decisions.

## How to test this PR?
Not easy to reproduce but can be hand-crafted. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by klauspost** [comment]
If it isn't JSON and not xlv2, what other valid metadata can it be?

Just looking to learn.

**Comment by harshavardhana** [comment]
> If it isn't JSON and not xlv2, what other valid metadata can it be?
> 
> Just looking to learn.

Something corrupted and bit-rot @klauspost our decision to delete it solely by the fact of a boolean here is perhaps not right.

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
time="2022-10-13T04:25:32Z" level=error msg="User-selected graph driver \"overlay\" overwritten by graph driver \"vfs\" from database - delete libpod local files to resolve"
time="2022-10-13T04:25:32Z" level=error msg="User-selected graph driver \"overlay\" overwritten by graph driver \"vfs\" from database - delete libpod local files to resolve"
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#cbf40126-a878-49e0-b26b-b9e50e042687) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#795fad93-2dfb-4931-bb68-659fe76654fe) |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#39961016-ae66-479d-8f2c-8d1694aa4514) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#3bf29b99-94d7-4bde-b2e7-99518b970d55) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#0cf8a1ff-aa6d-48d7-a871-6fee8efdfe20) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#c3705da9-8bfd-41cc-b420-e422e27823aa) |
| mint-pools.sh | :heavy_exclamation_mark: [more...](#5cda7ffa-16b1-4296-affd-a72d032f83f1) |
<a name="c3705da9-8bfd-41cc-b420-e422e27823aa"></a>
### 15843-74578a3/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="795fad93-2dfb-4931-bb68-659fe76654fe"></a>
### 15843-74578a3/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="3bf29b99-94d7-4bde-b2e7-99518b970d55"></a>
### 15843-74578a3/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="cbf40126-a878-49e0-b26b-b9e50e042687"></a>
### 15843-74578a3/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="39961016-ae66-479d-8f2c-8d1694aa4514"></a>
### 15843-74578a3/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0cf8a1ff-aa6d-48d7-a871-6fee8efdfe20"></a>
### 15843-74578a3/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="5cda7ffa-16b1-4296-affd-a72d032f83f1"></a>
### 15843-74578a3/mint-pools.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally
time="2022-10-13T04:30:45Z" level=error msg="User-selected graph driver \"overlay\" overwritten by graph driver \"vfs\" from database - delete libpod local files to resolve"
time="2022-10-13T04:30:45Z" level=error msg="User-selected graph driver \"overlay\" overwritten by graph driver \"vfs\" from database - delete libpod local files to resolve"

**Comment by harshavardhana** [comment]
PTAL @klauspost

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]

**Pull request merged**
