### PR TITLE
Fix New UX related bugs for Alerts, BucketList and Abort Upload modal

### LINKED ISSUE #5689: Center text on New UX Alert component
## Expected Behavior

The text on the Alert component should be centered

## Current Behavior

The text on the Alert component is currently left justified. Please see image below for reference.

screen shot 2018-03-22 at 1 33 06 pm

## Possible Solution

We can add `text-align: center` to the CSS selector for the `alert` class and adjust the dimensions of the alert div accordingly.

## Steps to Reproduce (for bugs)

1. Do any action that causes the Alert component to be rendered (Enter login credentials incorrectly, upload file successfully, try to delete a bucket that contains objects, etc.)

## Context

This issue was opened as per @harshavardhana's feedback. The unused space on the right side doesn't look completely appealing.

## Your Environment

* Version used (`minio version`): master
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by kaankabalak**
## Description

- Center text on Alert component appearing on top
- Change "Upload" to "Continue" on New UX Abort Upload modal
- Fix issue where long bucket names were overflowing instead of
continuing on the next line
- Fix word wrap issue similar to the last one for the alerts that appear
on top
- Help fix the cluttering issue on #5690 as the right margin has been
increased in alerts

## Motivation and Context

Fixes #5689, #5691 and #5695

## How Has This Been Tested?

Manually and unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#54871eeb-59fc-4287-9e0a-8636a2149c69) |
<a name="54871eeb-59fc-4287-9e0a-8636a2149c69"></a>
### 5694-57d1aea/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30651
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 8d32c11a6eaf:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 2 seconds
(2/12) Running aws-sdk-php tests ... done in 7 minutes and 5 seconds
(3/12) Running aws-sdk-ruby tests ... done in 59 seconds
(4/12) Running awscli tests ... FAILED in 2 minutes and 32 seconds
{
  "name": "awscli",
  "duration": 9951,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 3 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#249ed829-4480-435b-a28e-6053c345feb0) |
<a name="249ed829-4480-435b-a28e-6053c345feb0"></a>
### 5694-70f0392/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31943
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 19ab530e1620:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 7 minutes and 14 seconds
(3/12) Running aws-sdk-ruby tests ... done in 59 seconds
(4/12) Running awscli tests ... FAILED in 3 minutes and 37 seconds
{
  "name": "awscli",
  "duration": 11634,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 3 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by rushenn — APPROVED** [review]
LGTM

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Pull request merged**
