### PR TITLE
Align STS web-identity code snippet to documentation (minio#9114)

### LINKED ISSUE #9114: web-identity API example in STS/Keycloak docs is incorrect
While trying to wrap my head around how to integrate my service with minio and keycloak, I came across the [Using WebIdentity API section of the STS/Keycloak documentation](https://github.com/minio/minio/blob/5ab9cc029d1de8105388e02538ac78e1891de2d9/docs/sts/keycloak.md#4-using-webidentiy-api)

That section directs you to a go program - [docs/sts/web-identity.go](https://github.com/minio/minio/blob/c9940d8c3f1f7a2b3e087abaecd7550a68b4fdb6/docs/sts/web-identity.go) which is supposed to print out credentials, but which instead prints out some buckets.

It appears that the [code snippet was updated](https://github.com/minio/minio/commit/64759189f589f2995b71b4ebd7df5be8c6d1105c#diff-9621d8ca0476c134a0717cab3f014017L168), possibly to match some other piece of documentation, while the Keycloak documentation languished.

This caused me some confusion until I had a look at the code myself.

## Expected Behavior
Running the `web-identity.go` program prints out my credentials

## Current Behavior
Running the `web-identity.go` program prints out a list of buckets

## Possible Solution
I see 3 options

1. Revert the code snippet so that it prints out the credentials as specified by the STS/Keycloak docs
2. Change the STS/Keycloak docs to match the code snippet
3. Implement a separate snippet (as seems to be de rigueur inside that directory) that fleshes out the use-case specified in the Keycloak documentation.

##### Contrast:
* [the documentation](https://github.com/minio/minio/blob/5ab9cc029d1de8105388e02538ac78e1891de2d9/docs/sts/keycloak.md#4-using-webidentiy-api):
> [...]
> upon successful login, STS credentials will be printed on the screen, for example
> 
> ```
> ##### Credentials
> {
> 	"accessKey": "6N2BALX7ELO827DXS3GK",
> 	"secretKey": "23JKqAD+um8ObHqzfIh+bfqwG9V8qs9tFY6MqeFR",
> 	"expiration": "2019-10-01T07:22:34Z",
> 	"sessionToken": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI2TjJCQUxYN0VMTzgyN0RYUzNHSyIsImFjciI6IjAiLCJhdWQiOiJhY2NvdW50IiwiYXV0aF90aW1lIjoxNTY5OTEwNTUyLCJhenAiOiJhY2NvdW50IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJleHAiOjE1Njk5MTQ1NTQsImlhdCI6MTU2OTkxMDk1NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2RlbW8iLCJqdGkiOiJkOTk4YTBlZS01NDk2LTQ4OWYtYWJlMi00ZWE5MjJiZDlhYWYiLCJuYmYiOjAsInBvbGljeSI6InJlYWR3cml0ZSIsInByZWZlcnJlZF91c2VybmFtZSI6Im5ld3VzZXIxIiwic2Vzc2lvbl9zdGF0ZSI6IjJiYTAyYTI2LWE5MTUtNDUxNC04M2M1LWE0YjgwYjc4ZTgxNyIsInN1YiI6IjY4ZmMzODVhLTA5MjItNGQyMS04N2U5LTZkZTdhYjA3Njc2NSIsInR5cCI6IklEIn0._UG_-ZHgwdRnsp0gFdwChb7VlbPs-Gr_RNUz9EV7TggCD59qjCFAKjNrVHfOSVkKvYEMe0PvwfRKjnJl3A_mBA"
> }
> ```
> [...]

##### with
* [the code](https://github.com/minio/minio/blob/c9940d8c3f1f7a2b3e087abaecd7550a68b4fdb6/docs/sts/web-identity.go#L221):
```
		for _, bucket := range buckets {
			log.Println(bucket)
		}
```
vs.

```
			w.Write([]byte("##### Credentials\n"))
			c, err := json.MarshalIndent(a.Result.Credentials, "", "\t")
[...]
			w.Write(c)
```
## Context
I have an existing microservices platform that uses Keycloak/JWT's - and I am investigating whether to integrate minio as a storage backend for a RESTful service that is in charge of managing a "project" schema that resides on NFS. To that end, I am checking whether `minio` can act as a general-purpose File/CRUD API on top of the NFS with IAM being handled exclusively by Keycloak.

## Regression
Not a regression per se, but it was introduced by https://github.com/minio/minio/pull/8501

## Your Environment

* Version used (`minio version`):  I'm running off `origin/master` `5ab9cc02`.
* Operating System and version (`uname -a`): `Darwin NC-MBP-0288.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`

### PR DESCRIPTION
**Pull request by gzur**
Description

Resolves #9114 

Also added some server logging, to help people debug any problems they might have in their setup.

## Motivation and Context
Align code snippet in docs with what the documentation actually says.
Slight update to the documentation.

## How to test this PR?
1. follow the instructions in the [STS/Keycloak documentation](http://github.com/gzur/minio/blob/db80b3cbb7bdd830781bce48d96884edc1ed3a4c/docs/sts/keycloak.md)

1. Visit http://localhost:8888 in a browser.

1. Log in via the configured identify provider.

Something like the following should appear in the browser:
```
{
  "buckets": [
    "bucket-x"
  ],
  "credentials": {
    "AccessKeyID": "xxxx",
    "SecretAccessKey": "xxxx+xxx",
    "SessionToken": "xxxxx",
    "SignerType": 1
  }
}

```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by gzur** [comment]
@harshavardhana

**Review by harshavardhana — CHANGES_REQUESTED** [review]
> Signed-off-by: Gissur Þórhallsson <gissur@wuxinextcode.com>

We don't sign-offs @gzur - you can remove this.

**Comment by gzur** [comment]
> > Signed-off-by: Gissur Þórhallsson [gissur@wuxinextcode.com](mailto:gissur@wuxinextcode.com)
> 
> We don't sign-offs @gzur - you can remove this.

Done.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#f8169ee0-707f-4c14-9dde-7c2c1ae44332) |
<a name="f8169ee0-707f-4c14-9dde-7c2c1ae44332"></a>
### 9130-e6c8d35/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30353
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 36941d1d3d8b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 6 minutes and 36 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 59 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 6 minutes and 49 seconds
(8/14) Running minio-dotnet tests ... done in 2 minutes and 0 seconds
(9/14) Running minio-go tests ... done in 19 minutes and 52 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 24 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11055,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3u0eh47, objectName=minio-java-test-2km3rr3, resource=/minio-java-test-3u0eh47/minio-java-test-2km3rr3, requestId=15FBFE4E80EDFCAD, hostId=018e6316-869e-4f97-9caf-fe692b52bb16)\nrequest={method=PUT, url=http://minio-dev6.minio.io:30353/minio-java-test-3u0eh47/minio-java-test-2km3rr3?uploadId=d4a41173c50d08ea&partNumber=1, headers=x-amz-copy-source-if-match: bd602daf5b0e2833bd1b0a87cd8347e9-2\nx-amz-copy-source: minio-java-test-3u0eh47/minio-java-test-12chjbr\nAccept-Encoding: identity\nHost: minio-dev6.minio.io:30353\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200313T224147Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200313/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-13T21-41-38Z\nVary: Origin\nX-Amz-Request-Id: 15FBFE4E80EDFCAD\nX-Xss-Protection: 1; mode=block\nDate: Fri, 13 Mar 2020 22:41:47 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
