### PR TITLE
Fix incorrect merging of slash-suffixed objects

### PR DESCRIPTION
**Pull request by klauspost**
## Description
If two objects share everything but one object has a slash prefix those would be merged in listings, with secondary properties used to tiebreak.

Example An object with key `prefix/obj` would be merged with an object named `prefix/obj/`. While this violates the [no object can be prefix of another](https://min.io/docs/minio/linux/operations/concepts/thresholds.html#conflicting-objects) let's resolve these.

If we have an object with 'name' and a directory named 'name/' discard the directory only - but allow objects of 'name' and 'name/' (xldir) to be uniquely returned.

Regression from https://github.com/minio/minio/pull/15772

## How to test this PR?

See example. Requires objects to be placed on different sets.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — CHANGES_REQUESTED** [review]
can we add a test for this?

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
We can add a test later on this.

**Comment by harshavardhana** [comment]
Looks like there is some regression due to this PR

```
=== RUN   TestListObjectsVersionedFolders/Erasure-Test7
    object-api-listobjects_test.go:162: ListObjectVersions, bucket: test-bucket-folders prefix: unique/ marker:  delimiter:  maxkeys: 1000
    object-api-listobjects_test.go:246: want: [unique/folder/ unique/folder/ unique/folder/1.txt]
    object-api-listobjects_test.go:247: got: [unique/folder/1.txt]
    object-api-listobjects_test.go:248: Test 7: Erasure: Expected number of object in the result to be '3', but found '1' objects instead
    object-api-listobjects_test.go:256: Test 7: Erasure: Expected object name to be "unique/folder/", but found "unique/folder/1.txt" instead
    object-api-listobjects_test.go:252: Test 7: Erasure: Expected object name to be "unique/folder/", but not nothing instead
    object-api-listobjects_test.go:252: Test 7: Erasure: Expected object name to be "unique/folder/1.txt", but not nothing instead
--- FAIL: TestListObjectsVersionedFolders (0.28s)
    --- PASS: TestListObjectsVersionedFolders/ErasureSD-Test1 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/ErasureSD-Test2 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/ErasureSD-Test3 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/ErasureSD-Test4 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/ErasureSD-Test5 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/ErasureSD-Test6 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/ErasureSD-Test7 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/Erasure-Test1 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/Erasure-Test2 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/Erasure-Test3 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/Erasure-Test4 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/Erasure-Test5 (0.00s)
    --- PASS: TestListObjectsVersionedFolders/Erasure-Test6 (0.00s)
    --- FAIL: TestListObjectsVersionedFolders/Erasure-Test7 (0.00s)
```

**Comment by harshavardhana** [comment]
@klauspost can you resubmit this PR? I have currently reverted this change to make a new release.

**Comment by harshavardhana** [comment]
Reproduces with

```
go test -v -run TestListObjectsVersionedFolders --count=100
```

**Comment by klauspost** [comment]
Sure thing!

**Pull request merged**
