### PR TITLE
Let user specify access and secret key via command line

### PR DESCRIPTION
**Pull request by osallou**
This patch allow to specify both access and secret key via command line instead of generating them at startup. This eases the integration with other apps that could provide them (see issue #1142).

### CODE REVIEW

**Comment by harshavardhana** [comment]
> This patch allow to specify both access and secret key via command line instead of generating them at startup. This eases the integration with other apps that could provide them (see issue #1142).

Thank you for the patch @osallou - unfortunately but this won't be the right style. We would like to limit the amount of command line options.

We will discuss this internally on how it can be cleaned fixed. Thanks again for your work :-)

**Comment by abperiasamy** [comment]
@osallou Can you please re-implement like this:
--credential=ACCESS-KEY:SECRET-KEY

Config file is also going have a similar change. Internal code variables remain as is (accessKeyId and secretAccessKey).

**Comment by harshavardhana** [comment]
> Config file is also going have a similar change. Internal code variables remain as is (accessKeyId and secretAccessKey).

@abperiasamy one problem with this approach is access-key and secret-key are visible in 'ps' output, which is a security risk.

**Comment by abperiasamy** [comment]
Yes it is a security risk. It is convenient for devops to pass states as a cli flag in an automated secure environment.

**Comment by harshavardhana** [comment]
> Yes it is a security risk. It is convenient for devops to pass states as a cli flag in an automated secure environment.

Alternative is to use env variables since they are not accessible outside of the process pid's context, one of @fd0 suggestions.

**Comment by abperiasamy** [comment]
Today almost no one uses Linux's multi-user capabilities to enforce security. CLI flags convenient compared environment variables. Users notice cli flags, but not ENV variables. Having said that, I also prefer @fd0 's suggestion. 

So lets do like this:
MINIO_ACCESS_KEY
MINIO_SECRET_KEY

--help also documents these environment variables in addition to flags.

**Comment by osallou** [comment]
Do you want i adapt my patch to use env vars instead of cmd line args? Or
do you take this feature?

**Comment by harshavardhana** [comment]
> Do you want i adapt my patch to use env vars instead of cmd line args? Or
> do you take this feature?

@osallou - you are right from what i gather, we decided on env vars instead of CLI args.

**Comment by osallou** [comment]
I can submit a new pull request on monday, using env vars.

Le sam. 20 févr. 2016 11:07, Harshavardhana notifications@github.com a
écrit :

**Comment by osallou** [comment]
I have created pull request #1152 that makes use of env variables instead of cmd line args. Closing this pull request.

**Pull request closed without merging**
