### PR TITLE
CVE fix: updated coreos/go-oidc depdendency to allow newer version of go-jose/…

### PR DESCRIPTION
**Pull request by ritster**
…go-jose

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by harshavardhana** [comment]
Updating libraries is our internal cadence.

**Comment by ritster** [comment]
Understood!  Thanks for reviewing the PR - I just wanted to open it as a draft to check if updating dependencies fixed a CVE (https://github.com/advisories/GHSA-c5q2-7r4c-mv6g) and maintained functionality. Looks like most of the tests pass, so I got the data I needed!

**Comment by klauspost** [comment]
@harshavardhana This is a major version upgrade, so it requires code changes.

**Comment by harshavardhana** [comment]
> @harshavardhana This is a major version upgrade, so it requires code changes.

yeah.

**Pull request closed without merging**
