### PR TITLE
Add config to store subnet license

### PR DESCRIPTION
**Pull request by anjalshireesh**
## Description

Command to set subnet license:

`mc admin config set {alias} subnet license={token}`

Signed-off-by: Shireesh Anjal <shireesh@minio.io>

## Motivation and Context

Will be helpful in implementing `mc admin subnet register` where mc will fetch the cluster's license and then store in minio config for future use.

## How to test this PR?

- Run `mc admin config set/get` commands against minio built with the PR e.g.
 - to set the license:
`mc admin config set {alias} subnet license={token}`
 - Then get the value and verify that it is same as the one set above
`mc admin config get {alias} subnet`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by klauspost** [comment]
```
Running lint check
internal/config/subnet/license.go:23:2: exported: exported var DefaultKVS should have comment or be unexported (revive)
	DefaultKVS = config.KVS{
		config.KV{
```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by anjalshireesh** [comment]
> ```
> Running lint check
> internal/config/subnet/license.go:23:2: exported: exported var DefaultKVS should have comment or be unexported (revive)
> 	DefaultKVS = config.KVS{
> 		config.KV{
> ```

Resolved

**Review by klauspost — APPROVED** [review]
Having no validation can of course lead to invalid licenses being stored. 

I suppose we will just print a warning when the server starts.

**Review by harshavardhana — CHANGES_REQUESTED** [review]
looks like an incomplete PR @anjalshireesh did you test this? 

>         globalSubnetLicense = env.Get(config.EnvMinIOSubnetLicense, "")

You need to make sure that there is code to first validate this as well, i.e we should validate if the license is correct, and also the value should be a data structure that is returned as 

```
subnet.Lookup(kvs) (Config, error)
```

Then this is saved as `globalSubnetConfig` which has `globalSubnetConfig.License()` which returns the license and this is set for `CONSOLE_SUBNET_LICENSE=globalSubnetConfig.License()` 

Also, we need to start bringing in provisions for making the entire `mc admin subnet health --help` to be available on the server-side this can be done in the future. 

```
  --deadline value              maximum duration that health tests should be allowed to run (default: 1h0m0s) [$MC_HEALTH_DEADLINE, $MC_OBD_DEADLINE]
  --name value                  Cluster name to be saved in subnet on 1st upload
  --schedule value              Schedule of uploading to subnet in no of days (default: 0)
  --subnet-proxy value          HTTP(S) proxy URL to be used along with license flag
```

Each of these should become fully server-side options and customers can set it up once - subnet health will continuously run once in a while and upload directly to our subnet. 

```
mc admin config set alias/ subnet license=<license> health_deadline=2h health_schedule=10d health_subnet_proxy=<proxy to upload directly to subnet> health_cluster_name=<cluster_name>
```

Other than license rest can be done later.

**Comment by anjalshireesh** [comment]
> looks like an incomplete PR @anjalshireesh did you test this? 

Yes @harshavardhana , of course I have tested :-) but only the ability to set/get/reset the config from `mc`. This is the part I need to implement `mc admin subnet register`.

I will try to understand the rest of the requirements offline and update the PR with the parts that are required immediately.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by klauspost — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Pull request merged**
