### PR TITLE
cosmetic: Move request goroutines to methods

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Cosmetic change, but breaks up a big code block and will make goroutine dumps of streams more readable, so it is clearer what each goroutine is doing.

No functional changes.

## Motivation and Context

Maintenance and support

## Types of changes
- [x] Cleanup

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
Race detected

```
=== RUN   TestStreamSuite/testStreamCancel
=== RUN   TestStreamSuite/testStreamCancel/unbuffered
    grid_test.go:505: got resp:  err: context canceled
    grid_test.go:512: Client Context canceled. err state: context canceled
==================
WARNING: DATA RACE
Read at 0x00c00028e0d0 by goroutine 144:
  github.com/minio/minio/internal/grid.(*muxServer).sendResponses()
      /home/runner/work/minio/minio/internal/grid/muxserver.go:176 +0x6f
  github.com/minio/minio/internal/grid.newMuxStream.func4()
      /home/runner/work/minio/minio/internal/grid/muxserver.go:153 +0x17e

Previous write at 0x00c00028e0d0 by goroutine 126:
  github.com/minio/minio/internal/grid.(*muxServer).close()
      /home/runner/work/minio/minio/internal/grid/muxserver.go:373 +0x190
  github.com/minio/minio/internal/grid.(*Connection).handleDisconnectServerMux()
      /home/runner/work/minio/minio/internal/grid/connection.go:1406 +0xad
  github.com/minio/minio/internal/grid.(*Connection).handleMsg()
      /home/runner/work/minio/minio/internal/grid/connection.go:1189 +0x1d9
  github.com/minio/minio/internal/grid.(*Connection).handleMessages.func1()
      /home/runner/work/minio/minio/internal/grid/connection.go:1007 +0x92d

Goroutine 144 (running) created at:
  github.com/minio/minio/internal/grid.newMuxStream()
      /home/runner/work/minio/minio/internal/grid/muxserver.go:150 +0xc35
  github.com/minio/minio/internal/grid.(*Connection).handleConnectMux.func2()
      /home/runner/work/minio/minio/internal/grid/connection.go:1250 +0x125
  github.com/minio/minio/internal/grid.(*lockedServerMap).LoadOrCompute()
      /home/runner/work/minio/minio/internal/grid/grid.go:283 +0x91
  github.com/minio/minio/internal/grid.(*Connection).handleConnectMux()
      /home/runner/work/minio/minio/internal/grid/connection.go:1249 +0x332
  github.com/minio/minio/internal/grid.(*Connection).handleMsg()
      /home/runner/work/minio/minio/internal/grid/connection.go:1201 +0x129
  github.com/minio/minio/internal/grid.(*Connection).handleMessages.func1()
      /home/runner/work/minio/minio/internal/grid/connection.go:1007 +0x92d

```

**Comment by klauspost** [comment]
(let's run it twice... merge master if this passes)

**Comment by klauspost** [comment]
ok, two runs... For whatever reason the race wasn't triggering locally.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
