### PR TITLE
Update import for NATS clients in examples

### PR DESCRIPTION
**Pull request by wallyqs**
## Description
This updates a couple of NATS client examples to point to the new location of the repos.  

## Motivation and Context
The NATS clients repositories named were changed so updating the docs to reflect those changes.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#cece9124-e380-45f3-ae51-91ca652a852c) |
| mint-xl.sh | :x: [more...](#eb1ec96e-97a6-429d-8dab-0ce4f36d0075) |
| mint-dist-xl.sh | :x: [more...](#3ac414ae-4a92-4081-98f2-10f62307e8af) |
<a name="cece9124-e380-45f3-ae51-91ca652a852c"></a>
### 7743-d9032ad/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30574
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c427f466ac37:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fb6duubgtwtfed",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3077,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30574/aws-sdk-go-test-fb6duubgtwtfed: dial tcp 72.28.97.57:30574: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="eb1ec96e-97a6-429d-8dab-0ce4f36d0075"></a>
### 7743-d9032ad/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32163
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2c4fbade7127:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fo6n3x036x3p1a",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360019,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A4DC1D745B320F, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="3ac414ae-4a92-4081-98f2-10f62307e8af"></a>
### 7743-d9032ad/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31414
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3cdd9a8f1c5a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 32 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 47 seconds
(10/14) Running minio-java tests ... FAILED in 40 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 977,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-18vn40p, objectName=minio-java-test-b6tfor, resource=/minio-java-test-18vn40p/minio-java-test-b6tfor, requestId=15A4DC138340ACD0, hostId=a7b01794-c52e-4e58-96af-cbee7c7683ac)\nrequest={method=DELETE, url=http://72.28.97.53:31414/minio-java-test-18vn40p/minio-java-test-b6tfor?uploadId=d5762ebc-595c-45e2-baa8-ee7953f1e2a2, headers=Host: 72.28.97.53:31414\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190604T015547Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190604/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-04T01-37-33Z\nVary: Origin\nX-Amz-Request-Id: 15A4DC138340ACD0\nX-Minio-Deployment-Id: a7b01794-c52e-4e58-96af-cbee7c7683ac\nX-Xss-Protection: 1; mode=block\nDate: Tue, 04 Jun 2019 01:55:48 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
Thanks for the PR @wallyqs

**Review by Praveenrajmani — APPROVED** [review]
LGTM

**Review by nitisht — APPROVED** [review]
Thanks @wallyqs !

**Pull request merged**
