### PR TITLE
Refactor download object and bulk action components

### PR DESCRIPTION
**Pull request by kmkanagaraj**
## Description
- Refactored download object actions and added unit tests
- Moved object download and delete bulk actions to separate component

## Motivation and Context

Re-write browser code to follow best practices and guidelines of React
#5409 #5410

## How Has This Been Tested?

Unit tests and manual

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#f55f5d7a-fd9a-46e1-af49-c2afe11b75ac) |
| mint-dist-xl.sh | :x: [more...](#84404aee-9e30-424d-add5-f94c90b2ec11) |
<a name="f55f5d7a-fd9a-46e1-af49-c2afe11b75ac"></a>
### 5546-e85d00c/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32760
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp b2ba62794889:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 0 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 49 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5a8a63f841042"
  },
  "duration": "40420",
  "status": "FAIL",
  "error": "Expected getBucketPolicy to fail with 404"
}

Executed 1 out of 12 tests successfully.
```
<a name="84404aee-9e30-424d-add5-f94c90b2ec11"></a>
### 5546-e85d00c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30441
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 698f1ef5d675:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5t5vh64wey2sz0",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 345,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30441/aws-sdk-go-test-5t5vh64wey2sz0: dial tcp 192.168.122.45:30441: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#dd9ab177-b01a-40cd-99ec-2524f9930199) |
| mint-dist-xl.sh | :x: [more...](#9ad00c03-e55c-49fa-a42d-19cdc23eb341) |
<a name="9ad00c03-e55c-49fa-a42d-19cdc23eb341"></a>
### 5546-163331a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30526
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp b5fea597a63f:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-un1vc31k9aatze",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 334,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30526/aws-sdk-go-test-un1vc31k9aatze: dial tcp 192.168.122.45:30526: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```
<a name="dd9ab177-b01a-40cd-99ec-2524f9930199"></a>
### 5546-163331a/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30334
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp e3aa409550ac:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 0 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 47 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5a8a74a4dcfd4"
  },
  "duration": "40190",
  "status": "FAIL",
  "error": "Expected getBucketPolicy to fail with 404"
}

Executed 1 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#70794750-952f-4bb8-8d58-ee30d335eb2f) |
| mint-dist-xl.sh | :x: [more...](#07775a96-2c53-4385-9977-09ced09806f8) |
<a name="07775a96-2c53-4385-9977-09ced09806f8"></a>
### 5546-298c992/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31699
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp d3658388187e:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-u06z26bo2iuvts",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 382,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:31699/aws-sdk-go-test-u06z26bo2iuvts: dial tcp 192.168.122.45:31699: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```
<a name="70794750-952f-4bb8-8d58-ee30d335eb2f"></a>
### 5546-298c992/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31928
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp c83c57b264cd:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 49 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5a8a7ccba20f7"
  },
  "duration": "40165",
  "status": "FAIL",
  "error": "Expected getBucketPolicy to fail with 404"
}

Executed 1 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#86b3113f-2acc-4369-9b5d-58d5355b6d58) |
| mint-dist-xl.sh | :x: [more...](#8fee2c66-17b8-4a60-b453-cbf92ab96fd2) |
<a name="86b3113f-2acc-4369-9b5d-58d5355b6d58"></a>
### 5546-97afda1/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31641
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp c120397d615c:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 47 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5a8aa2af1d5c2"
  },
  "duration": "40092",
  "status": "FAIL",
  "error": "Expected getBucketPolicy to fail with 404"
}

Executed 1 out of 12 tests successfully.
```
<a name="8fee2c66-17b8-4a60-b453-cbf92ab96fd2"></a>
### 5546-97afda1/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30935
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp a989c0c0425e:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vxsciy3fhgrg0p",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 332,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30935/aws-sdk-go-test-vxsciy3fhgrg0p: dial tcp 192.168.122.45:30935: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

**Comment by krishnasrinivas** [comment]
* refactor download object action

Refactored download object action and added unit test.

* refactor object bulk actions components

Refactored objects delete and download all zip functionalities.

* reset checked objects list when prefix is changed

* hide object actions when some objects are checked

* fix unit test case description

* remove unwanted console.log from objects actions

**Pull request merged**
