### PR TITLE
Better error when the server is unable to write in the backend

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Better error when the server is unable to write in the backend

## Motivation and Context
Show a hint to fix permission access to the backend

## How to test this PR?
```
$ sudo mkdir /data/
$ minio server /data/
```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#cbac157a-ffcf-43c9-9b8c-3ea4877e759c) |
| mint-xl.sh | :x: [more...](#a5007123-2f41-4717-9064-375c8f962b4a) |
| mint-large-bucket.sh | :x: [more...](#4bf07529-5f60-4690-aaaf-86c573bde7cb) |
<a name="a5007123-2f41-4717-9064-375c8f962b4a"></a>
### 8697-29bb066/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32174
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 84d3c388ed08:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 14 seconds
{
  "name": "awscli",
  "duration": 12810,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="cbac157a-ffcf-43c9-9b8c-3ea4877e759c"></a>
### 8697-29bb066/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32435
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e6d97d4d3dbe:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 10 seconds
{
  "name": "awscli",
  "duration": 308652,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=32435): Max retries exceeded with url: /awscli-mint-test-bucket-18971 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7fa9d15220b8>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="4bf07529-5f60-4690-aaaf-86c573bde7cb"></a>
### 8697-29bb066/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30193
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6d1bb93d9fbe:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 8 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 1 minutes and 15 seconds
(5/13) Running minio-go tests ... FAILED in 2 minutes and 34 seconds
{
  "args": {},
  "duration": 44503,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by kannappanr** [comment]
@vadmeste Please fix Travis errors

```
Running lint check
/home/travis/gopath/src/github.com/minio/minio/cmd/config/errors-utils.go:39:1: exported method Err.Clone should have comment or be unexported
Found 1 lint suggestions; failing.
make: *** [lint] Error 1
The command "make verifiers" exited with 2.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#2ae9329e-312a-428e-958c-e17dc16ec0ac) |
| mint-large-bucket.sh | :x: [more...](#a61a8a40-e553-45cc-9362-6fbfeb41bb66) |
| mint-compression-dist-xl.sh | :x: [more...](#6067d3b0-abfd-47c8-b91f-74ca1f44f438) |
<a name="6067d3b0-abfd-47c8-b91f-74ca1f44f438"></a>
### 8697-0d5a1d5/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31350
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e86bd74964f2:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 14 seconds
{
  "name": "awscli",
  "duration": 312847,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=31350): Max retries exceeded with url: /awscli-mint-test-bucket-13451 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f2f242fb080>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="2ae9329e-312a-428e-958c-e17dc16ec0ac"></a>
### 8697-0d5a1d5/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32718
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0254a76b0d74:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 14 seconds
{
  "name": "awscli",
  "duration": 12640,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="a61a8a40-e553-45cc-9362-6fbfeb41bb66"></a>
### 8697-0d5a1d5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30456
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0515338ecb71:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 16 seconds
{
  "name": "awscli",
  "duration": 313816,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=30456): Max retries exceeded with url: /awscli-mint-test-bucket-27040 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f7963c84710>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#69a25a71-90b0-4d64-9123-846890396ba0) |
| mint-xl.sh | :x: [more...](#38fe87e5-0976-46f3-a2c2-c7a25271e8c2) |
| mint-large-bucket.sh | :x: [more...](#a9a751d3-d157-4838-98d9-9fde559bfcb9) |
| mint-worm.sh | :x: [more...](#779abb0e-015c-4c17-9550-9e3ea5a0f15a) |
<a name="a9a751d3-d157-4838-98d9-9fde559bfcb9"></a>
### 8697-04b4e7f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30168
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5faa1077d47e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{
  "name": "awscli",
  "duration": 306452,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=30168): Max retries exceeded with url: /awscli-mint-test-bucket-7242 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f86908e8080>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="69a25a71-90b0-4d64-9123-846890396ba0"></a>
### 8697-04b4e7f/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31449
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f869d45d6c24:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 7 seconds
{
  "name": "awscli",
  "duration": 305851,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=31449): Max retries exceeded with url: /awscli-mint-test-bucket-9496 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7fa6a6cfa160>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="38fe87e5-0976-46f3-a2c2-c7a25271e8c2"></a>
### 8697-04b4e7f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32196
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e969d9af48f1:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 15 seconds
{
  "name": "awscli",
  "duration": 13101,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="779abb0e-015c-4c17-9550-9e3ea5a0f15a"></a>
### 8697-04b4e7f/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30290
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6b6985e99454:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-ik0o4sna03qiwtta5dpn3rhqldahan3yzj5t3x2kafht9rh2wdyn1va",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120272,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30290/bucket-ik0o4sna03qiwtta5dpn3rhqldahan3yzj5t3x2kafht9rh2wdyn1va: dial tcp 72.28.97.55:30290: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#f3db67a9-44af-4702-8b3e-d5b5136da88e) |
| mint-xl.sh | :x: [more...](#ca2a6af1-b3d0-49a8-bf4e-4787130643a3) |
| mint-large-bucket.sh | :x: [more...](#a402be2d-7f1c-4303-8811-426bd326136b) |
| mint-compression-dist-xl.sh | :x: [more...](#d474cfd8-4548-4e22-ba69-5c434d0a3bb2) |
| mint-compression-fs.sh | :x: [more...](#f7d729e3-f077-4fb3-8706-12d52e938d6a) |
| mint-fs.sh | :x: [more...](#66d7c023-32d4-4a94-b4bc-b7f486d1dc03) |
| mint-dist-xl.sh | :x: [more...](#b845588b-e6ab-4b81-81d3-5c2579a5df54) |
| mint-gateway-nas.sh | :x: [more...](#83ed9f69-b05f-45d7-b555-6857f3c07fd7) |
<a name="d474cfd8-4548-4e22-ba69-5c434d0a3bb2"></a>
### 8697-6d6968a/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31617
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a662771374c4:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 24 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 29 seconds
(5/13) Running minio-go tests ... done in 1 minutes and 23 seconds
(6/13) Running minio-js tests ... FAILED in 5 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 12,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="b845588b-e6ab-4b81-81d3-5c2579a5df54"></a>
### 8697-6d6968a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31922
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3f97b0bb4c29:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 15 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 4 seconds
(4/13) Running mc tests ... done in 1 minutes and 3 seconds
(5/13) Running minio-go tests ... done in 1 minutes and 6 seconds
(6/13) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="ca2a6af1-b3d0-49a8-bf4e-4787130643a3"></a>
### 8697-6d6968a/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30695
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 51c63d282be9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 307323, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30695/awscli-mint-test-bucket-11794""}

Executed 0 out of 13 tests successfully.
```
<a name="f7d729e3-f077-4fb3-8706-12d52e938d6a"></a>
### 8697-6d6968a/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32727
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ab803ec9c6ac:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 7 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 3 seconds
(4/13) Running mc tests ... done in 46 seconds
(5/13) Running minio-go tests ... done in 47 seconds
(6/13) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="f3db67a9-44af-4702-8b3e-d5b5136da88e"></a>
### 8697-6d6968a/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30847
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8a539b924da5:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 12 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 1 seconds
(4/13) Running mc tests ... done in 15 seconds
(5/13) Running minio-go tests ... done in 22 seconds
(6/13) Running minio-js tests ... FAILED in 2 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="83ed9f69-b05f-45d7-b555-6857f3c07fd7"></a>
### 8697-6d6968a/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32404
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b4fb4d62354e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 4 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 2 seconds
(4/13) Running mc tests ... done in 45 seconds
(5/13) Running minio-go tests ... done in 47 seconds
(6/13) Running minio-js tests ... FAILED in 3 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 10,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="66d7c023-32d4-4a94-b4bc-b7f486d1dc03"></a>
### 8697-6d6968a/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32396
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eb6a4ab8e7f3:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 4 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 2 seconds
(4/13) Running mc tests ... done in 41 seconds
(5/13) Running minio-go tests ... done in 49 seconds
(6/13) Running minio-js tests ... FAILED in 3 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="a402be2d-7f1c-4303-8811-426bd326136b"></a>
### 8697-6d6968a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30171
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 343e65f032a3:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 30 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 11 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 40 seconds
{
  "args": {},
  "duration": 93611,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Looks like minio-js release has something breaking with MinIO

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#612df9ad-b328-48d4-85a4-a15324bf0604) |
| mint-dist-xl.sh | :x: [more...](#751874de-a492-439b-8ebe-f4b585bac93a) |
<a name="612df9ad-b328-48d4-85a4-a15324bf0604"></a>
### 8697-d514215/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30131
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7355b041f528:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 15 seconds
{"name": "awscli", "duration": 312413, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30131/awscli-mint-test-bucket-31954""}

Executed 0 out of 13 tests successfully.
```
<a name="751874de-a492-439b-8ebe-f4b585bac93a"></a>
### 8697-d514215/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31673
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 53dd011904c9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 305266, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31673/awscli-mint-test-bucket-1082""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
