### PR TITLE
choose max drives per set to be '8' by default

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
choose max drives per set to be '8' by default

## Motivation and Context
with this, we also change the default parity for '8'
to be 'EC:3' instead of 'EC:4'.

## How to test this PR?
This is a new change.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by ravindk89** [comment]
This is a big change @harshavardhana 

So we still support erasure set sizes of 9-16, but we are defaulting to a max of 8 unless specified otherwise?

Plus Standard EC:3 with max set size instead of EC:4.

Can you walk us through the logic/goal state here and what we gain/lose in this setup? We'll have a lot of guidance to redo.

**Comment by harshavardhana** [comment]
> This is a big change @harshavardhana
> 
> So we still support erasure set sizes of 9-16, but we are defaulting to a max of 8 unless specified otherwise?
> 
> Plus Standard EC:3 with max set size instead of EC:4.
> 
> Can you walk us through the logic/goal state here and what we gain/lose in this setup? We'll have a lot of guidance to redo.

Implications are same as if you set manually storage class standard to EC:3, and use SET_DRIVE_COUNT environment to 8.

Nothing else changes other than this @ravindk89 - instead of manually doing it we are simply agreeing as per "design" that by default we will never do wider stripes.

With our experience over last few years we do not see the value in it anymore. Also reducing stripe quite simply increases IOPs by 2x.

Also increases efficiency of the scanner, everything is more spread out and still provides a good amount of safety net. 

If you do not trust your hardware then you can simply set higher stripe count, with reduced performance.

**Comment by ravindk89** [comment]
Gotcha. We'll have to prep a few things.

A few follow-ups:

Assuming we continue to follow pool expansion logic.

So if I have pool 1 with stripe size of 16 and EC:8, the new pool should also require at least EC:8 and therefore stripe 8, correct? Even with this setting that is.

**Comment by klauspost** [comment]
@harshavardhana Will it prefer 5 over 10, 6 over 12, 7 over 14 - or will this just affect sizes divisible by 16?

**Comment by harshavardhana** [comment]
> @harshavardhana Will it prefer 5 over 10, 6 over 12, 7 over 14 - or will this just affect sizes divisible by 16?

yeah, well, it does right now. That's the question I have that needs clarification, but it is going to be a bit of a hoch-poch to digest after years of running things differently.

**Comment by klauspost** [comment]
Yeah.. Like I get it for 16 -> 8 and 14 -> 7.... But 10 -> 5 and maybe 12 ->6 seems like a rather big drop...

**Comment by harshavardhana** [comment]
This PR will move to EOS

**Pull request closed without merging**
