### PR TITLE
lifecycle: Suspend when the server receives clients requests

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Similar to healing, the lifecycle should suspend its operation
when the server receives too many requests, however lifecycle
is more aggressive than healing since lifecycle is not too
much costly.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#46e927fb-909f-4364-83f4-00826dcadeae) |
| mint-large-bucket.sh | :x: [more...](#13927aaa-f0a6-4330-ba52-c37734cb4d2e) |
| mint-compression-fs.sh | :x: [more...](#644ab02f-4cc1-4ce8-81d1-2e022892d14c) |
<a name="644ab02f-4cc1-4ce8-81d1-2e022892d14c"></a>
### 8417-f02a782/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30887
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f90f26329e2b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 45 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 49 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 19 seconds
(11/14) Running minio-js tests ... done in 42 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 31 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "duration": 65,
  "args": {
    "response.reason": "Forbidden",
    "response.status": 403,
    "bucket_name": "minio-py-test-4b5b3782-c9af-40fc-9e7c-28360e2cbb72",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>3cac96e1-40b8-4c77-ae62-340b6da29d61</Key><BucketName>minio-py-test-4b5b3782-c9af-40fc-9e7c-28360e2cbb72</BucketName><Resource>/minio-py-test-4b5b3782-c9af-40fc-9e7c-28360e2cbb72/3cac96e1-40b8-4c77-ae62-340b6da29d61</Resource><RequestId>15CEC9A758184AFF</RequestId><HostId>adfa78a5-ecd1-4782-bd13-c8ff196394c2</HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-18T15-42-25Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CEC9A758184AFF\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 18 Oct 2019 16:10:40 GMT\"]}}",
    "object_name": "3cac96e1-40b8-4c77-ae62-340b6da29d61",
    "presigned_get_object_url": "http://72.28.97.58:30887/minio-py-test-4b5b3782-c9af-40fc-9e7c-28360e2cbb72/3cac96e1-40b8-4c77-ae62-340b6da29d61?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191018%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191018T161029Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=7f7403a14744d2f279bbce2af5fee4a9c3242e3b8c2c862bd8776d9c7d6ed67c"
  },
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="46e927fb-909f-4364-83f4-00826dcadeae"></a>
### 8417-f02a782/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32526
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3310cbabc046:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-bful23nadfo6ae",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 366017,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15CEC97CDB780934, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="13927aaa-f0a6-4330-ba52-c37734cb4d2e"></a>
### 8417-f02a782/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30849
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 56af2d3e58a7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 39 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 14 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 28 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 4 seconds
{
  "args": {},
  "duration": 97779,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
{"name": "8417-f02a782", "full_size": 34550206, "images": [{"size": 34550206, "architecture": "amd64", "variant": null, "features": null, "os": "linux", "os_version": null, "os_features": null}], "id": 73075488, "repository": 757613, "creator": 21164, "last_updater": 21164, "last_updated": "2019-10-18T15:43:16.816598Z", "image_id": null, "v2": true}Error: No such image: minio/minio:8417-f02a782

**Comment by harshavardhana** [comment]
Can lifecycle piggy back on the data usage active IO count implementation here @vadmeste ?

**Comment by harshavardhana** [comment]
@vadmeste will this PR be ready for review? - this seems to be going stale. If it's not ready let's close it and get back to this later?

**Comment by harshavardhana** [comment]
PTAL #9026 changes which adds minimal changes to throttle lifecycle.

**Comment by harshavardhana** [comment]
Let's close this as stale, it's around 6months old. Please resubmit if you have further changes.

**Pull request closed without merging**
