### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by carsoni**
The change is suggested to clarify the instigation of https access to a docker containerized MinIO instance. Couldn't find the documentation elsewhere

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#a7725023-2d10-40a0-951a-84561e1d5548) |
| mint-large-bucket.sh | :x: [more...](#a0badf4f-af8d-483c-b72c-31ed2d0a43cc) |
| mint-worm.sh | :x: [more...](#a87ada5d-1c6a-4b57-8160-7af21cebaf61) |
| mint-dist-xl.sh | :x: [more...](#3880f9e2-874b-49d4-ac38-70f8c1d12c10) |
| mint-gateway-nas.sh | :x: [more...](#4755f03a-135b-45ef-9521-3233e3e49e9c) |
<a name="a0badf4f-af8d-483c-b72c-31ed2d0a43cc"></a>
### 7854-7159801/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32727
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 12f63e2bd613:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 8 seconds
{
  "name": "mc",
  "duration": "92304",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-1716 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-14915  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-14915/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-14915/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-14915/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-14915/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-14915/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-14915/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-14915/datafile-10-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-14915/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-14915/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-14915/datafile-5-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-14915/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-14915/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-14915/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-14915/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-14915/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 551.49 MiB, Speed: 5.98 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="4755f03a-135b-45ef-9521-3233e3e49e9c"></a>
### 7854-7159801/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31149
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e4ac9fa1c7a2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-z1zz24fq1rtwtc",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3072,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31149/aws-sdk-go-test-z1zz24fq1rtwtc: dial tcp 72.28.97.57:31149: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="a87ada5d-1c6a-4b57-8160-7af21cebaf61"></a>
### 7854-7159801/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30782
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f1abd68ab43f:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-sd9fduvl7to0vsl0d75nk1tnukyi70mkr5makydswmsva2r8cbmzmv1",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 3078,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30782/bucket-sd9fduvl7to0vsl0d75nk1tnukyi70mkr5makydswmsva2r8cbmzmv1: dial tcp 72.28.97.57:30782: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="a7725023-2d10-40a0-951a-84561e1d5548"></a>
### 7854-7159801/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31994
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0508ed77e921:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-uisogdeoz0gla5",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360015,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15AD3AC63A5D8AA0, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="3880f9e2-874b-49d4-ac38-70f8c1d12c10"></a>
### 7854-7159801/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32351
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5ebbe8a61c24:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 24 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 1406,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3500adj, objectName=minio-java-test-172q2m1, resource=/minio-java-test-3500adj/minio-java-test-172q2m1, requestId=15AD3AD0FB5D5CAF, hostId=2dbb4ca4-0488-4d48-b5c3-0a409282e788)\nrequest={method=DELETE, url=http://72.28.97.56:32351/minio-java-test-3500adj/minio-java-test-172q2m1?uploadId=65a08f99-a81b-44f9-9bc9-776dd9b6ad98, headers=Host: 72.28.97.56:32351\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190701T082155Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190701/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-01T08-01-48Z\nVary: Origin\nX-Amz-Request-Id: 15AD3AD0FB5D5CAF\nX-Minio-Deployment-Id: 2dbb4ca4-0488-4d48-b5c3-0a409282e788\nX-Xss-Protection: 1; mode=block\nDate: Mon, 01 Jul 2019 08:21:55 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Review by aead — APPROVED** [review]

**Review by eco-minio — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
There is some issue in our container running as regular users @eco-minio is opening an issue, keeping this PR blocked since `--address` is not needed to run MinIO in TLS inside containers.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#fb8b3aad-6e91-45fb-8da6-1efbff5c799f) |
| mint-large-bucket.sh | :x: [more...](#465c4ac4-4d55-43e2-a63a-55898c9c3e65) |
| mint-worm.sh | :x: [more...](#5aaaeac3-27b6-44ae-83f3-04449f7777f7) |
| mint-dist-xl.sh | :x: [more...](#b1b19d90-bc0a-4d86-9a41-adf75cabb05a) |
| mint-gateway-nas.sh | :x: [more...](#451b50c6-2bd0-4308-af96-e4cb2310bb49) |
<a name="451b50c6-2bd0-4308-af96-e4cb2310bb49"></a>
### 7854-eedbc74/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32047
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cad9ccbe742f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wmt2yug9m5jtwx",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3071,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32047/aws-sdk-go-test-wmt2yug9m5jtwx: dial tcp 72.28.97.57:32047: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5aaaeac3-27b6-44ae-83f3-04449f7777f7"></a>
### 7854-eedbc74/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30778
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a741aeb26e7d:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-if1z6hvqtmuttpjh7gg2skabkkrj9300poskswkv7dyfjnsliwc3bqq",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 2918,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30778/bucket-if1z6hvqtmuttpjh7gg2skabkkrj9300poskswkv7dyfjnsliwc3bqq: dial tcp 72.28.97.57:30778: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="b1b19d90-bc0a-4d86-9a41-adf75cabb05a"></a>
### 7854-eedbc74/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30574
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 42259a1666b1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 44 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 49 seconds
(10/14) Running minio-java tests ... FAILED in 43 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 306,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1vh5mkg, objectName=minio-java-test-25d69dr, resource=/minio-java-test-1vh5mkg/minio-java-test-25d69dr, requestId=15AEA2661811B3A4, hostId=ca0f236d-42f3-4bbd-aa9e-73a121d36311)\nrequest={method=DELETE, url=http://72.28.97.55:30574/minio-java-test-1vh5mkg/minio-java-test-25d69dr?uploadId=874dbd3e-07e6-497e-8569-1dbe2e4992f8, headers=Host: 72.28.97.55:30574\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190705T221120Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190705/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-05T21-52-31Z\nVary: Origin\nX-Amz-Request-Id: 15AEA2661811B3A4\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Jul 2019 22:11:20 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="fb8b3aad-6e91-45fb-8da6-1efbff5c799f"></a>
### 7854-eedbc74/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32087
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c565b8d72d61:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ndlu6nvfsctyxt",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2941,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32087/aws-sdk-go-test-ndlu6nvfsctyxt: dial tcp 72.28.97.57:32087: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="465c4ac4-4d55-43e2-a63a-55898c9c3e65"></a>
### 7854-eedbc74/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31064
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d6b0c90b6757:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 19 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 29 seconds
{
  "name": "mc",
  "duration": "117998",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-10029 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-3565  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-3565/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-3565/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-3565/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-3565/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-3565/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-3565/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-3565/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-3565/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-3565/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-3565/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-3565/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-3565/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-3565/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-3565/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-3565/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 456.64 MiB, Speed: 3.87 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
This is not needed, closing this issue as fixed by #7930

**Pull request closed without merging**
