### PR TITLE
gateway-azure: Return right error when Part size is > 100MB

### LINKED ISSUE #4640: azure: minio-java test fails on azure gateway
## Expected Behavior
Minio-Java functional tests work on azure gateway 

## Current Behavior
Minio-Java Functional Tests fails on azure backend. 

```
$ ./gradlew runFunctionalTest
:api:compileJava UP-TO-DATE
:api:processResources UP-TO-DATE
:api:classes UP-TO-DATE
:api:jar UP-TO-DATE
:functional:compileJava UP-TO-DATE
:functional:processResources UP-TO-DATE
:functional:classes UP-TO-DATE
:functional:runFunctionalTest
Test: makeBucket(String bucketName)
Test: listBuckets()
Test: bucketExists(String bucketName)
Test: removeBucket(String bucketName)
Test: putObject(String bucketName, String objectName, String filename)
Test: multipart: putObject(String bucketName, String objectName, String filename)
Test: multipart resume: putObject(String bucketName, String objectName, String filename)
Test: putObject(String bucketName, String objectName, String contentType, long size, InputStream body)
Test: putObject(String bucketName, String objectName, String filename, String contentType)
Test: objectName with path segments: putObject(String bucketName, String objectName, String filename)
Test: putObject(String bucketName, String objectName, InputStream body, String contentType)
Test: multipart: putObject(String bucketName, String objectName, InputStream body, String contentType)
java.net.SocketException: Connection reset
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at okio.Okio$1.write(Okio.java:78)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
        at okio.RealBufferedSink.write(RealBufferedSink.java:41)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
        at okio.RealBufferedSink.write(RealBufferedSink.java:109)
        at io.minio.MinioClient$3.writeTo(MinioClient.java:871)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall.execute(RealCall.java:69)
        at io.minio.MinioClient.execute(MinioClient.java:998)
        at io.minio.MinioClient.executePut(MinioClient.java:1266)
        at io.minio.MinioClient.executePut(MinioClient.java:1288)
        at io.minio.MinioClient.putObject(MinioClient.java:3480)
        at io.minio.MinioClient.putObject(MinioClient.java:3590)
        at io.minio.MinioClient.putObject(MinioClient.java:3175)
        at FunctionalTest.putObject_test8(FunctionalTest.java:291)
        at FunctionalTest.runTests(FunctionalTest.java:1601)
        at FunctionalTest.main(FunctionalTest.java:1704)
:functional:runFunctionalTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':functional:runFunctionalTest'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 59.525 secs

```

## Possible Solution
Not known

## Steps to Reproduce (for bugs)
- Build Minio server from current master
- Run it in `azure` gateway mode. 
- Point minio-java functional tests to your Minio instance and run with `./gradlew runFunctionalTest`

### PR DESCRIPTION
**Pull request by krishnasrinivas**
## Description

Max part size for azure is 100MB, return appropriate error.

## How Has This Been Tested?

manual

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
@krishnasrinivas I am sure the client will see `closed connection` error with this PR too. what is the expected behavior in the client?

**Comment by krishnasrinivas** [comment]
@balamurugana confirmed that minio-java/okhttp misbehaves on slack:
```
okhttp streams 525MB of data in one end and the connection is set to keep alive.
    server reads the stream and passes to azure. azure fails due to the stream size is beyond 100MB in the middle of read.
    the server replies the error and closes the connection.
    async write to okhttp fails to write (java.net.SocketException: Connection reset at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)) because of the connection is closed at server side.
    even though the error response to the call is available, write to the connection throws error before reading the response.
    It looks like a violation in closing keep alive connection.
```

previously it was returning internal error, now with the fix it returns:
```
mc: <ERROR> Failed to copy `/tmp/1000g`. Your proposed upload exceeds the maximum allowed object size.
```

**Comment by balamurugana** [comment]
This behavior is not only in minio-java, minio-go returns error in the same way ie `2017/07/09 20:13:44 read tcp [::1]:45980->[::1]:9000: use of closed network connection`

@krishnasrinivas This PR does not fix the mentioned issue.  It handles Azure error properly and returns correct error.  This issue needs to be discussed and take the call accordingly.

**Comment by krishnasrinivas** [comment]
@balamurugana I used the same script given by you:
```
krishna@escape:/tmp$ go run bala.go
---------START-HTTP---------
GET /mybucket/?location= HTTP/1.1
Host: localhost:9001
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170710/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170710T091350Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Type: application/xml
Date: Mon, 10 Jul 2017 09:13:51 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14CFED3954741774
---------END-HTTP---------
---------START-HTTP---------
POST /mybucket/myobject?uploads= HTTP/1.1
Host: localhost:9001
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170710/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170710T091351Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Length: 223
Accept-Ranges: bytes
Content-Type: application/xml
Date: Mon, 10 Jul 2017 09:13:51 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14CFED39549DE02B
---------END-HTTP---------
---------START-HTTP---------
PUT /mybucket/myobject?partNumber=1&uploadId=myobject HTTP/1.1
Host: localhost:9001
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Content-Length: 603979776
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170710/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: 07081ab506eb0f2e10d0fdf35c376d456d74eaf2840ea3ea391f2cfe3295799c
X-Amz-Date: 20170710T091355Z
Accept-Encoding: gzip

HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 286
Accept-Ranges: bytes
Content-Type: application/xml
Date: Mon, 10 Jul 2017 09:13:55 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14CFED3A405D4DE8

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed object size.</Message><Key></Key><BucketName></BucketName><Resource>/mybucket/myobject</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>---------END-HTTP---------
---------START-HTTP---------
DELETE /mybucket/myobject?uploadId=myobject HTTP/1.1
Host: localhost:9001
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170710/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170710T091356Z
Accept-Encoding: gzip

Accept-Ranges: bytes
Date: Mon, 10 Jul 2017 09:13:56 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14CFED3A89EEB531
---------END-HTTP---------
2017/07/10 02:13:56 Your proposed upload exceeds the maximum allowed object size.
exit status 1
krishna@escape:/tmp$ 
```

works as expected, have you updated minio-go?

**Review by vadmeste — APPROVED** [review]
LGTM, tested with mc after tweaking minimal part size. mc shows the expected error message.

**Comment by deekoder** [comment]
@harshavardhana & @krishnasrinivas  please see the repro in @balamurugana's machine.

**Review by harshavardhana — APPROVED** [review]

**Review by balamurugana — DISMISSED** [review]
As I mentioned this PR is not fixing #4640. commit log/PR description should be fixed.

**Comment by krishnasrinivas** [comment]
@harshavardhana's comment on https://github.com/minio/minio/issues/4640

> We should open a bug on minio-go or minio-java to handle this situation of server closing the connection @balamurugana and this issue can be closed.

if this PR is fine can you approve @balamurugana

**Comment by harshavardhana** [comment]
> @harshavardhana's comment on #4640
> 
> We should open a bug on minio-go or minio-java to handle this situation of server closing the connection @balamurugana and this issue can be closed.

This is invalid from the last discussion client and server both are behaving correctly and the bug #4640 should be closed. 

This PR still needs to be merged.

**Comment by balamurugana** [comment]
@krishnasrinivas As you agreed to remove reference to https://github.com/minio/minio/issues/4640, I will approve once the change is done.

**Comment by krishnasrinivas** [comment]
@balamurugana done

**Pull request merged**
