### PR TITLE
fix privilege escalation against S3 and Web handlers

### PR DESCRIPTION
**Pull request by aead**
## Description

This commit fixes a privilege escalation issue against
the S3 and web handlers. An authenticated IAM user
can:
a) Read from or write to the internal '.minio.sys'
   bucket by simply sending a properly signed
   S3 GET or PUT request. Further, the user can
b) Read from or write to the internal '.minio.sys'
   bucket using the 'Upload'/'Download'/'DownloadZIP'
   API by sending a "browser" request authenticated
   with its JWT token.

This fix just prevents this by checking that only
S3/"browser" requests signed/authenticated with the
admin secret key can access the '.minio.sys' bucket.

However, this is just a security fix and ONLY prevents
users request to this specific meta-bucket. It is no holistic
approach to prevent similar issues in the future.

## Motivation and Context
Fixing a security issue

## Regression
no

## How Has This Been Tested?
Manually. You need to either extract the JWT from the browser and manually create a web request accessing the `.minio.sys` bucket or send a GET/PUT request for an object in the `.minio.sys` bucket signed by the access/secret key of an IAM user. Note that mc (without specially patched) won't work.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#e6e89d97-bcf9-4031-9640-7b7fa3f25434) |
| mint-compression-dist-xl.sh | :x: [more...](#f19fb26d-bc51-41be-93d1-aaa3a9163f6f) |
| mint-compression-fs.sh | :x: [more...](#dcbc9e52-55e9-415c-8f6b-6ccaa7d988bb) |
| mint-fs.sh | :x: [more...](#11ef14bd-5479-4c35-9cfd-0b091fca69a9) |
<a name="dcbc9e52-55e9-415c-8f6b-6ccaa7d988bb"></a>
### 7473-dc3e183/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32065
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b536c1315308:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mtedpjusjkplsr",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2771,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32065/aws-sdk-go-test-mtedpjusjkplsr: dial tcp 72.28.97.57:32065: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f19fb26d-bc51-41be-93d1-aaa3a9163f6f"></a>
### 7473-dc3e183/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30990
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3ffafad86a51:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-su4p2b26urv5yu",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2128,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30990/aws-sdk-go-test-su4p2b26urv5yu: dial tcp 72.28.97.57:30990: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="e6e89d97-bcf9-4031-9640-7b7fa3f25434"></a>
### 7473-dc3e183/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30128
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eb20c00878c4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 45 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-dotnet tests ... done in 22 seconds
(9/14) Running minio-go tests ... done in 22 seconds
(10/14) Running minio-java tests ... done in 15 seconds
(11/14) Running minio-js tests ... done in 34 seconds
(12/14) Running minio-py tests ... FAILED in 58 seconds
{
  "function": "presigned_put_object(bucket_name, object_name, expires)",
  "args": {
    "bucket_name": "minio-py-test-44deefb1-ff4b-4a72-86a0-554ad8b59aec",
    "object_name": "36cf6874-add7-4e7f-9d15-57818d24b8fc"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1347, in test_presigned_put_object_expiry_5sec\n    raise ValueError('Presigned put url failed to expire!')\nValueError: Presigned put url failed to expire!\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1894, in main\n    test_presigned_put_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1349, in test_presigned_put_object_expiry_5sec\n    raise Exception(err)\nException: Presigned put url failed to expire!\n",
  "status": "FAIL",
  "message": "Presigned put url failed to expire!",
  "duration": 5015,
  "name": "minio-py:test_presigned_put_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```
<a name="11ef14bd-5479-4c35-9cfd-0b091fca69a9"></a>
### 7473-dc3e183/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30464
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 55f6eade7c7c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-1zi1zq4x2nlicu",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3056,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30464/aws-sdk-go-test-1zi1zq4x2nlicu: dial tcp 72.28.97.57:30464: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#05f33d79-5973-4790-acb8-0f6fb13114db) |
| mint-compression-dist-xl.sh | :x: [more...](#72dae216-eb58-4a2c-be8e-18983c949f1c) |
| mint-fs.sh | :x: [more...](#4e604053-768f-430c-be9b-48871c9e5005) |
<a name="72dae216-eb58-4a2c-be8e-18983c949f1c"></a>
### 7473-96dcfa5/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31475
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5ba45933c5d5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-kz1x0hyad6dhal",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2132,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31475/aws-sdk-go-test-kz1x0hyad6dhal: dial tcp 72.28.97.57:31475: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="4e604053-768f-430c-be9b-48871c9e5005"></a>
### 7473-96dcfa5/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31618
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a3a154f98e0c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-paiudhvj94f94l",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 333,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:31618/aws-sdk-go-test-paiudhvj94f94l: dial tcp 72.28.97.54:31618: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="05f33d79-5973-4790-acb8-0f6fb13114db"></a>
### 7473-96dcfa5/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30082
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9cab24ee3764:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vkbm5fcyxbzmbo",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3077,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30082/aws-sdk-go-test-vkbm5fcyxbzmbo: dial tcp 72.28.97.57:30082: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by deekoder** [comment]
@aead  i am not the right person to review. Assigning this to @kannappanr

**Comment by harshavardhana** [comment]
This fix is not correct @aead the right fix is in `checkBucketExist()`

**Review by harshavardhana — CHANGES_REQUESTED** [review]
This fix is not correct @aead the right fix is in checkBucketExist()

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/7476 PR supersedes this PR.

**Pull request closed without merging**
