### PR TITLE
fix metrics panic in node metrics endpoint

### PR DESCRIPTION
**Pull request by poornas**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
panic with duplicate label names in constant and variable lables for metrics "minio_replication_Current_Active_workers (

## How to test this PR?
test /minio/v2/metrics/node endpoint with replication enabled

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — CHANGES_REQUESTED** [review]
@poornas let's bring a unit/functional test - minimal

based on https://pkg.go.dev/github.com/minio/madmin-go/v3#ParsePrometheusResults 

So that we can avoid these kind of regressions in future.

**Comment by jiuker** [comment]
why not give another name for this? https://github.com/minio/minio/pull/18897

**Comment by poornas** [comment]
> @poornas let's bring a unit/functional test - minimal
> 
> based on https://pkg.go.dev/github.com/minio/madmin-go/v3#ParsePrometheusResults
> 
> So that we can avoid these kind of regressions in future.

adding these to the multi site tests since we need replication enabled anyway for some of the metrics

**Review by harshavardhana — APPROVED** [review]

**Comment by poornas** [comment]
@harshavardhana , This needs a change in mc as well - I can add these tests after https://github.com/minio/mc/pull/4835 is in a release to avoid test failures. will send the tests as a separate PR

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by joreize** [comment]
Do you plan to release a BugFix-Release with these Changes?

**Pull request merged**
