### PR TITLE
Remove curl after the usage

### PR DESCRIPTION
**Pull request by mkumatag**
## Description

This will remove the curl package after the usage
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Can this be done for `Dockerfile` as well ??

**Comment by mkumatag** [comment]
> Can this be done for Dockerfile as well ??

done! 👍

**Review by harshavardhana — APPROVED** [review]

**Review by donatello — APPROVED** [review]

**Comment by mkumatag** [comment]
@harshavardhana @kannappanr @donatello do you mind spinning a build with this fix?

**Comment by harshavardhana** [comment]
> @harshavardhana @kannappanr @donatello do you mind spinning a build with this fix?

It will happen when we make a release @mkumatag

**Comment by kannappanr** [comment]
@mkumatag We will be making a release in the next couple of days.

**Comment by fergbrain** [comment]
I'm getting an "unhealthy" status when I run Minio in docker. The error report says, "/usr/bin/healthcheck.sh: line 1: curl: not found"

I'm wondering if this change breaks healthcheck.sh?

**Comment by harshavardhana** [comment]
> I'm getting an "unhealthy" status when I run Minio in docker. The error report says, "/usr/bin/healthcheck.sh: line 1: curl: not found"
> 
> I'm wondering if this change breaks healthcheck.sh?

Yep this change broke the build @fergbrain

**Comment by mkumatag** [comment]
bingo...! I see https://github.com/minio/minio/blob/master/dockerscripts/healthcheck.sh#L37 is using curl command.. Do you mind adding some comment in the dockerfile so that people know that we are using curl not just in dockerfile.!

**Comment by harshavardhana** [comment]
> bingo...! I see https://github.com/minio/minio/blob/master/dockerscripts/healthcheck.sh#L37 is using curl command.. Do you mind adding some comment in the dockerfile so that people know that we are using curl not just in dockerfile.!

There is no reason to, we should have checked anyways. In-fact we will rewrite the healthcheck to be not a script instead use Go itself.

**Pull request merged**
