### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

Found few misspellings.
Please consider switching to `typos`.

Please help me finish this PR: I do not speak go, and I am not a minio user.

### CODE REVIEW

**Comment by szepeviktor** [comment]
`.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
    ".codespellrc",
    "docs/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Patrick Collison",
    "Copyright 2014 Unknwon",
    "[0-9A-Za-z/+=]{64}",
    "ZXJuZXQxDjAMBgNVBA-some-junk-Q4wDAYDVQQLEwVNaW5pbzEOMAwGA1UEAxMF",
    "eyJmb28iOiJiYXIifQ",
    'http\.Header\{"X-Amz-Server-Side-Encryptio":',
]

[default.extend-words]
"encrypter" = "encrypter"
"requestor" = "requestor"

[default.extend-identifiers]
"bui" = "bui"
"dm2nd" = "dm2nd"
"HashiCorp" = "HashiCorp"
"ParseND" = "ParseND"
"ParseNDStream" = "ParseNDStream"
"TestGetPartialObjectMisAligned" = "TestGetPartialObjectMisAligned"
```

**Review by shtripat — APPROVED** [review]
lgtm

**Comment by harshavardhana** [comment]
@szepeviktor thanks for the PR these are typos however they look like are touching a lot of code randomly. 

We will do these changes internally more carefully and merge them. Thank you for letting us know about the tool called `typos`.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request closed without merging**
