### PR TITLE
Allow CopyObject() in S3 gateway to support metadata

### LINKED ISSUE #4924: [gateway/azure/s3/gcs]: copy object with metadata doesn't set metadata on destination object
While running below minio-java test, azure gateway fails.

```java 
  /**
   * Test: copyObject(String bucketName, String objectName, String destBucketName,
   * CopyConditions copyConditions, Map metadata) replace
   * object metadata.
   */
  public static void copyObject_test8() throws Exception {
    if (!mintEnv) {
      System.out.println("Test: copyObject(String bucketName, String objectName, String destBucketName,"
                        + "CopyConditions copyConditions, Map<String, String> metadata)"
                        + " replace object metadata");
    }

    long startTime = System.currentTimeMillis();
    try {
      String objectName = getRandomName();
      InputStream is = new ContentInputStream(3 * MB);
      client.putObject(bucketName, objectName, is, 3 * MB, "application/octet-stream");
      is.close();

      String destBucketName = getRandomName();
      client.makeBucket(destBucketName);

      CopyConditions copyConditions = new CopyConditions();
      copyConditions.setReplaceMetadataDirective();

      Map<String, String> metadata = new HashMap<>();
      metadata.put("Content-Type", customContentType);

      client.copyObject(bucketName, objectName, destBucketName, objectName, copyConditions, metadata);

      ObjectStat objectStat = client.statObject(destBucketName, objectName);
      if (!customContentType.equals(objectStat.contentType())) {
        throw new Exception("content type differs. expected: " + customContentType + ", got: "
                            + objectStat.contentType());
      }

      client.removeObject(bucketName, objectName);
      client.removeObject(destBucketName, objectName);
      client.removeBucket(destBucketName);
      mintSuccessLog("copyObject(String bucketName, String objectName, String destBucketName, "
                     + "CopyConditions copyConditions, Map<String, String> metadata)",
                     null, startTime);
    } catch (Exception e) {
      mintFailedLog("copyObject(String bucketName, String objectName, String destBucketName, "
                    + "CopyConditions copyConditions, Map<String, String> metadata)",
                    null, startTime, null,
                    e.toString() + " >>> " + Arrays.toString(e.getStackTrace()));
      throw e;
    }
  }
```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Allow CopyObject() in S3 gateway to support metadata

## Motivation and Context
Fixes #4924

## How Has This Been Tested?
Manually and using minio-java tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by balamurugana — APPROVED** [review]
LGTM

**Review by donatello — APPROVED** [review]

**Review by balamurugana — CHANGES_REQUESTED** [review]
Does not fix the problem. Able to reproduce with this PR

**Comment by harshavardhana** [comment]
> Does not fix the problem. Able to reproduce with this PR

Looks like a bug in our minio-go implementation converts everything to `X-Amz-Meta`

```
PUT /minio-java-test-1ki832e HTTP/1.1
Host: minio-java-test-24g0cqo.s3.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/4.0.0
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170930/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date;x-amz-meta-content-type;x-amz-metadata-directive, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Copy-Source: minio-java-test-r77h4n/minio-java-test-1ki832e
X-Amz-Copy-Source-If-Match: 7716b449206546dc4f9b614eb73b9b0f
X-Amz-Date: 20170930T162509Z
X-Amz-Meta-Content-Type: application/javascript
X-Amz-Metadata-Directive: REPLACE
Accept-Encoding: gzip
```

**Comment by harshavardhana** [comment]
After looking at this for last 2 hours, looks like its not a simple change. It is little more involved and requires minio-go fixes for which i just sent a PR.  Along with that we need to incorporate it into server code and make use of it.  

We need to re-evaluate if we need to keep this bug for S3 gateway a release blocker.

**Review by donatello — CHANGES_REQUESTED** [review]
This is due to a bug in the underlying ComposeObject. I don't think the proposed fix at https://github.com/minio/minio-go/pull/836 is the right way.

**Comment by harshavardhana** [comment]
> This is due to a bug in the underlying ComposeObject. I don't think the proposed fix at minio/minio-go#836 is the right way.

That is the right way because we need a one to one relationship for S3 gateway, not a higher level function like ComposeObject. ComposeObject is not the right API to be used for this since it uses Multipart API underneath.

**Comment by harshavardhana** [comment]
@donatello @balamurugana PR is updated with the changes.

**Review by balamurugana — APPROVED** [review]
Tested

**Review by donatello — APPROVED** [review]

**Pull request merged**
