### PR TITLE
save format.json by default for inspect API

### PR DESCRIPTION
**Pull request by poornas**
## Motivation and Context
Save format.json by default for inspect command
Also save the path passed to inspect command

## How to test this PR?
`mc support inspect`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
@poornas does this handle `mc support inspect --export=json`

**Comment by harshavardhana** [comment]
More than capturing the `mc support inspect` command it is better to capture server command line @poornas

**Comment by poornas** [comment]
> More than capturing the `mc support inspect` command it is better to capture server command line @poornas

that would be useful - we can add it

**Pull request merged**
