### PR TITLE
fix: errNoSuchPolicy should use errors.Is

### PR DESCRIPTION
**Pull request by jiuker**
## Description

https://github.com/minio/minio/blob/eebdd2b31dc0e83e1618243c62592552cff35e75/cmd/iam-store.go#L1797-L1799 Here is the errNoSuchPolicy witch is wrapped.
So,we should use `errors.Is` to do this.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :x: [more...](#f40db1dd-8fe7-4b72-935b-0662b8a8a67f) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#cef20082-7bf5-4e1d-bcd6-952db7c650e3) |
| mint-pools.sh | :x: [more...](#d0d0186c-349d-4798-a7f2-b1161f4cfc1b) |
<a name="d0d0186c-349d-4798-a7f2-b1161f4cfc1b"></a>
### 16656-175ad40/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:30167
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 4b9062b073e7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 2 seconds
(9/14) Running minio-java tests ... FAILED in 6 minutes and 29 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 380684,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: timeout >>> [okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147), okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158), okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:337), okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320), okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29), okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 53 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 54 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 19 seconds

Executed 13 out of 14 tests successfully.
```
<a name="f40db1dd-8fe7-4b72-935b-0662b8a8a67f"></a>
### 16656-175ad40/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:30945
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp fca10659e0f5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 14 seconds
(8/14) Running minio-go tests ... done in 43 seconds
(9/14) Running minio-java tests ... done in 24 seconds
(10/14) Running minio-js tests ... FAILED in 4 minutes and 4 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-aa198dda-fdfc-400d-a2ee-d85a41b01f78, events: s3:ObjectCreated:*",
  "duration": 233816,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 7 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 28 seconds

Executed 13 out of 14 tests successfully.
```
<a name="cef20082-7bf5-4e1d-bcd6-952db7c650e3"></a>
### 16656-175ad40/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:31230
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp a453e56b79f5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 1 seconds
(9/14) Running minio-java tests ... FAILED in 1 minutes and 28 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 60348,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: connect timed out >>> [java.base/java.net.PlainSocketImpl.socketConnect(Native Method), java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412), java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255), java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237), java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392), java.base/java.net.Socket.connect(Socket.java:609), okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128), okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295), okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207), okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226), okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106), okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74), okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:189), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 58 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 41 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 3 minutes and 52 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by klauspost** [comment]
@jiuker So we don't risk random breakage in the future, we should do a translation:

```Go
	var errToErrCode = []struct {
		from error
		to   APIErrorCode
	}{
		{from: nil, to: ErrNone},
		{from: errInvalidArgument, to: ErrAdminInvalidArgument},
		{from: errNoSuchUser, to: ErrAdminNoSuchUser},
	}
```

... and in toAPIErrorCode:

```Go
	for _, v := range errToErrCode {
		if err == v.from || errors.Is(err, v.from) {
			return v.to
		}
	}
```

**Comment by klauspost** [comment]
To make the the types unwrap we can do:

```Go
	for {
		switch err.(type) {
		case StorageFull:
...
		case dns.ErrBucketConflict:
			apiErr = ErrBucketAlreadyExists
		default:
			var ie, iw int
			// This work-around is to handle the issue golang/go#30648
			//nolint:gocritic
			if _, ferr := fmt.Fscanf(strings.NewReader(err.Error()),
				"request declared a Content-Length of %d but only wrote %d bytes",
				&ie, &iw); ferr != nil {
				apiErr = ErrInternalError
				// Make sure to log the errors which we cannot translate
				// to a meaningful S3 API errors. This is added to aid in
				// debugging unexpected/unhandled errors.
				logger.LogIf(ctx, err)
			} else if ie > iw {
				apiErr = ErrIncompleteBody
			} else {
				if unErr := errors.Unwrap(err); unErr != nil {
					err = unErr
					continue
				}
				apiErr = ErrInternalError
				// Make sure to log the errors which we cannot translate
				// to a meaningful S3 API errors. This is added to aid in
				// debugging unexpected/unhandled errors.
				logger.LogIf(ctx, err)
			}
		}
		break
	}

	return apiErr
}
```

This will unwrap unknown errors if they can.

**Comment by harshavardhana** [comment]
> To make the the types unwrap we can do:
> 
> ```go
> 	for {
> 		switch err.(type) {
> 		case StorageFull:
> ...
> 		case dns.ErrBucketConflict:
> 			apiErr = ErrBucketAlreadyExists
> 		default:
> 			var ie, iw int
> 			// This work-around is to handle the issue golang/go#30648
> 			//nolint:gocritic
> 			if _, ferr := fmt.Fscanf(strings.NewReader(err.Error()),
> 				"request declared a Content-Length of %d but only wrote %d bytes",
> 				&ie, &iw); ferr != nil {
> 				apiErr = ErrInternalError
> 				// Make sure to log the errors which we cannot translate
> 				// to a meaningful S3 API errors. This is added to aid in
> 				// debugging unexpected/unhandled errors.
> 				logger.LogIf(ctx, err)
> 			} else if ie > iw {
> 				apiErr = ErrIncompleteBody
> 			} else {
> 				if unErr := errors.Unwrap(err); unErr != nil {
> 					err = unErr
> 					continue
> 				}
> 				apiErr = ErrInternalError
> 				// Make sure to log the errors which we cannot translate
> 				// to a meaningful S3 API errors. This is added to aid in
> 				// debugging unexpected/unhandled errors.
> 				logger.LogIf(ctx, err)
> 			}
> 		}
> 		break
> 	}
> 
> 	return apiErr
> }
> ```
> 
> This will unwrap unknown errors if they can.

I think we should avoid for loops here, these are potential places for hard to find bugs.

It's better to be explicit error translation, and have applications report to us if there are error that return unexpected internal errors.

**Comment by jiuker** [comment]
> 

@harshavardhana what's the change should I do?

**Comment by jiuker** [comment]
@harshavardhana How do I need to perfect this pr？

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
> @harshavardhana How do I need to perfect this pr？

This PR is fine, we need to improve our error translation robust that's all.

**Pull request merged**
