### PR TITLE
Fix Invalid setting

### PR DESCRIPTION
**Pull request by jiuker**
## Description

When line:73 is set, it will be invalid.

```go
// validateID - checks if ID is valid or not.
func (r Rule) validateID() error {
	IDLen := len(r.ID)
	// generate new ID when not provided
	// cannot be longer than 255 characters
	if IDLen == 0 {
		if newID, err := getNewUUID(); err == nil {
			r.ID = newID
		} else {
			return err
		}
	} else if IDLen > 255 {
		return errInvalidRuleID
	}
	return nil
}
```
Example:
```go
package main

import "fmt"

func main() {
	a := A{}
	a.SetB("Test")
	fmt.Println("output:", a.B)
	a.SetBWithPoint("Test")
	fmt.Println("output:", a.B)
}

type A struct {
	B string
}

func (a A) SetB(str string) {
	a.B = str
}

func (a *A) SetBWithPoint(str string) {
	a.B = str
}
```
```shell
$ go run main.go  
output: 
output: Test
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
updating a variable while validating is an anti-pattern coding, we need to fix that first instead of making `Rule` a pointer.

This needs to be fixed properly - cc @krisis

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#861a235f-1c98-463a-b0b4-2129f6923132) |
| mint-dist-erasure.sh | :x: [more...](#cd6b7cc5-ba58-452b-ae29-834cd3046139) |
<a name="861a235f-1c98-463a-b0b4-2129f6923132"></a>
### 15722-df2af25/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:30060
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 22 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 11 seconds
(9/14) Running minio-java tests ... done in 19 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 8 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-64ef94d7-2af3-411f-b37c-cfb554708f39, events: s3:ObjectCreated:*",
  "duration": 50035,
  "status": "FAIL",
  "error": "Error: notification not received at /mint/run/core/minio-js/test/functional-tests.js:1440:43 at ClientRequest.<anonymous> (node_modules/minio/dist/main/minio.js:569:9) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27) at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17) at Socket.socketOnData (_http_client.js:515:22) at addChunk (internal/streams/readable.js:293:12) at readableAddChunk (internal/streams/readable.js:267:9) at Socket.Readable.push (internal/streams/readable.js:206:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"
}
(10/14) Running minio-py tests ... done in 52 seconds
(11/14) Running s3cmd tests ... done in 23 seconds
(12/14) Running s3select tests ... done in 1 seconds
(13/14) Running versioning tests ... done in 1 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="cd6b7cc5-ba58-452b-ae29-834cd3046139"></a>
### 15722-df2af25/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:30793
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 16 seconds
(9/14) Running minio-java tests ... FAILED in 1 minutes and 21 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[negative unmodified since]",
  "duration": 54466,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s2:30793/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 1 minutes and 2 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 18 seconds
(11/14) Running s3cmd tests ... done in 24 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by jiuker** [comment]
I only found one place where this function is used. It does not break existing functionality. Instead, it is possible that this ID was previously set to restore the function, and whether it has an impact on the current function.

internal/bucket/lifecycle/rule.go:161
```go
// Validate - validates the rule element
func (r Rule) Validate() error {
	if err := r.validateID(); err != nil {
		return err
	}
	if err := r.validateStatus(); err != nil {
		return err
	}
	if err := r.validateExpiration(); err != nil {
		return err
	}
	if err := r.validateNoncurrentExpiration(); err != nil {
		return err
	}
	if err := r.validatePrefixAndFilter(); err != nil {
		return err
	}
	if err := r.validateTransition(); err != nil {
		return err
	}
	if err := r.validateNoncurrentTransition(); err != nil {
		return err
	}
	if !r.Expiration.set && !r.Transition.set && !r.NoncurrentVersionExpiration.set && !r.NoncurrentVersionTransition.set {
		return errXMLNotWellFormed
	}
	return nil
}
``` 
@harshavardhana

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
This will be fixed properly in a separate PR - this change is not needed - // cc @krisis

**Comment by krisis** [comment]
@jiuker Your analysis is correct, the previous fix to handle rules with empty id was incorrect.

 All rules with empty id in a lifecycle configuration must be assigned unique ids such that subsequent GetLifecycle API request must be observe these ids (consistently) thereafter. So, the right place to assign a unique rule id would be at the time of importing a bucket lifecycle configuration via PutBucketLifecycle API.
 
Thank you for bringing this issue to our attention through this PR. I will be sending a fix for this shortly.

**Pull request closed without merging**
