### PR TITLE
Disable printing access/secrets in systemd

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Disable printing access/secrets in systemd

## Motivation and Context
Minio, when run as a service in `systemd`, should
avoid printing access/secret keys.

## Regression
No

## How Has This Been Tested?
Running `minio` under non-terminals.

- Such as `systemd`
- `docker` system

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by krishnasrinivas — APPROVED** [review]

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 6621-1a7bde0/gopath/src/github.com/minio
+ git clone --quiet https://github.com/minio/minio.git 6621-1a7bde0/gopath/src/github.com/minio/minio
fatal: unable to access 'https://github.com/minio/minio.git/': Could not resolve host: github.com; Unknown error

```

**Comment by jgoerner** [comment]
Just a question out of curiosity based on this Issue/PR: What is the recommended way to extract the autogenerated access/secret keys if started with `docker run` (without explicitly stating those via env variables)?

**Comment by harshavardhana** [comment]
@jgoerner you can run in docker run -it or use `mc admin get config`

**Comment by jgoerner** [comment]
> @jgoerner you can run in docker run -it or use `mc admin get config`

Thanks, working as expected 👍

**Pull request merged**
