### PR TITLE
Bump response header timeout for proxying list request

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Bump response header timeout for proxying list request

## Motivation and Context
Increase response header timeout for proxying list requests

## How to test this PR?
Nothing much change needed as observed on some clusters

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Review by krishnasrinivas — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]

**Review by poornas — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#e116e862-c6db-494b-bf1e-6cb22a1d0ca2) |
<a name="e116e862-c6db-494b-bf1e-6cb22a1d0ca2"></a>
### 10420-942c9c4/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31321
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ccf3f10fe367:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 37 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... FAILED in 41 seconds
{
  "name": "awscli",
  "duration": 3702,
  "function": "aws --endpoint-url http://minio-c2.minio.io:31321 s3api copy-object --bucket awscli-mint-test-bucket-7920 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-7920/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D8511DE738C3A9-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 36 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 44 seconds
{
  "args": {
    "bucketName": "minio-go-test-co0a9epgm410ba5h",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 723,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 7 minutes and 38 seconds
(9/15) Running minio-js tests ... FAILED in 48 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 79,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 13 minutes and 3 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 11 seconds
(11/15) Running s3select tests ... done in 38 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10420-942c9c4

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#21c59149-c734-4ec1-9fe1-4d484b61162d) |
| mint-zoned.sh | :x: [more...](#c1e6e039-f3ee-46eb-9679-70854305c749) |
<a name="21c59149-c734-4ec1-9fe1-4d484b61162d"></a>
### 10420-d9c7265/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31584
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fdea4affdb53:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 55 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 50 seconds
{
  "name": "awscli",
  "duration": 4031,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:31584 s3api copy-object --bucket awscli-mint-test-bucket-31539 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-31539/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D85124F948ACC6-1"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 18 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 38 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 53 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 42 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 38 seconds
(11/15) Running minio-py tests ... done in 12 minutes and 52 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 27 seconds
(13/15) Running s3select tests ... done in 59 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="c1e6e039-f3ee-46eb-9679-70854305c749"></a>
### 10420-d9c7265/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31842
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4e61cd79621e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 50 seconds
(8/15) Running minio-dotnet tests ... done in 46 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 56 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 7 seconds
(11/15) Running minio-js tests ... done in 51 seconds
(12/15) Running minio-py tests ... done in 2 minutes and 58 seconds
(13/15) Running s3cmd tests ... FAILED in 21 seconds
{
  "name": "s3cmd",
  "duration": "11195",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10420-d9c7265

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#cfec3ade-e0c1-4aa6-a31b-95b8340dcc2a) |
| mint-gateway-azure.sh | :x: [more...](#cbff6195-e5cd-4658-a905-0710368a4f54) |
| mint-zoned.sh | :x: [more...](#723a85e2-78b3-4778-bf75-78eb2728d851) |
<a name="723a85e2-78b3-4778-bf75-78eb2728d851"></a>
### 10420-e9d56c7/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30079
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d76730539287:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 23 seconds
{
  "name": "awscli",
  "duration": 81077,
  "function": "aws --endpoint-url http://minio-c2.minio.io:30079 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-9541/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-9541/datafile-0-bupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-9541/datafile-1-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-9541/datafile-1-kBupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-9541/datafile-10-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-9541/datafile-100-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-9541/datafile-33-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-9541/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-9541/datafile-1.03-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-9541/datafile-5243880-bupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-9541/datafile-5-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-9541/datafile-6-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-9541/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-9541/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-9541/datafile-65-MBupload failed: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-9541/datafile-129-MB An error occurred (SlowDown) when calling the UploadPart operation (reached max retries: 4): Please reduce your request"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 55 seconds
(7/15) Running minio-dotnet tests ... done in 45 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 0 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 21 seconds
(10/15) Running minio-js tests ... done in 58 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 23 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="cbff6195-e5cd-4658-a905-0710368a4f54"></a>
### 10420-e9d56c7/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32077
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5d46d48d10b1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 21 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 37 seconds
{
  "name": "awscli",
  "duration": 1408,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 11 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 49 seconds
{
  "args": {
    "bucketName": "minio-go-test-rqr2kl2ddxvmbiik",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 688,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 7 minutes and 48 seconds
(9/15) Running minio-js tests ... FAILED in 48 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 79,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 14 minutes and 11 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 14 seconds
(11/15) Running s3select tests ... done in 37 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="cfec3ade-e0c1-4aa6-a31b-95b8340dcc2a"></a>
### 10420-e9d56c7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31386
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e70a59a8ebda:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 16 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 1 hours 1 minutes and 3 seconds
{
  "name": "mc",
  "duration": "3652831",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21839 --quiet --no-color cp /mint/data/datafile-65-MB myminio/mc-test-bucket-26485/mc-test-object-24693  >>> \n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-26485/mc-test-object-24693`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. A timeout occurred while trying to lock a resource, please reduce your request rate\nTotal: 0 B, Transferred: 34.38 MiB, Speed: 9.64 KiB/s"
}
(7/15) Running minio-dotnet tests ... done in 40 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 24 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 12 seconds
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 16 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10420-e9d56c7

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3d596716-4237-4a71-9a8b-cc32fe411cca) |
| mint-gateway-azure.sh | :x: [more...](#c4e2961f-f700-497c-b71d-2ca1b832a621) |
<a name="3d596716-4237-4a71-9a8b-cc32fe411cca"></a>
### 10420-47eb957/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32416
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e2d0924c56f0:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 11 minutes and 41 seconds
{"name": "awscli", "duration": 636213, "function": "aws --endpoint-url http://minio-c2.minio.io:32416 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-28842/\n", "status": "FAIL", "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-28842/datafile-0-bupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-28842/datafile-1-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-28842/datafile-10-kBupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-28842/datafile-1-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-28842/datafile-100-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-28842/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-28842/datafile-1-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-28842/datafile-5-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-28842/datafile-6-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-28842/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-28842/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-28842/datafile-11-MBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-28842/datafile-33-kBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-28842/datafile-129-MBupload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-28842/datafile-65-MB Connection was closed before we received a valid response from endpoint URL: "http://minio-c2.minio.io:32416/awscli-mint-test-bucket-28842/datafile-65-MB?uploadId=e578787d-ee29-4b50-a392-fd40f519d510&partNumber=8"."}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 32 seconds
(7/15) Running minio-dotnet tests ... done in 41 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 43 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 17 seconds
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 8 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="c4e2961f-f700-497c-b71d-2ca1b832a621"></a>
### 10420-47eb957/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30742
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7e600ccf033b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 35 seconds
(4/15) Running aws-sdk-ruby tests ... done in 28 seconds
(5/15) Running awscli tests ... FAILED in 48 seconds
{
  "name": "awscli",
  "duration": 3997,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:30742 s3api copy-object --bucket awscli-mint-test-bucket-13457 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-13457/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D85138406D2F7A-1"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 4 minutes and 31 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 50 seconds
{
  "args": {
    "bucketName": "minio-go-test-1jquo25n11efbapv",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 715,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 7 minutes and 32 seconds
(9/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 75,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 13 minutes and 48 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 15 seconds
(11/15) Running s3select tests ... done in 37 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10420-47eb957

**Pull request merged**
