### PR TITLE
Include the entirety of vendor folder in .gitignore

### PR DESCRIPTION
**Pull request by kaankabalak**
## Description
Include the entirety of "vendor" folder in .gitignore

## Motivation and Context
The 'go mod vendor' command generates a directory called 'vendor' in the
main module's root directory, which includes the required packages to
support builds. Therefore, we can include the 'vendor' directory in
.gitignore completely, regardless of any file extension.

## How to test this PR?
1- Run go mod vendor, or change the "vendor" folder in any way
2- Verify that the changes are not shown on `git status`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
no one should be doing `go mod vendor`  - are you just attempting this PR as a defensive mechanism? @kaankabalak

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by kaankabalak** [comment]
> no one should be doing `go mod vendor` - are you just attempting this PR as a defensive mechanism? @kaankabalak

@harshavardhana I saw the following happen to me when I tried running the `make` command, so that was why I ran the `go mod vendor` command and sent the PR. Please let me know if there is any other way to fix this. Thanks in advance 👍

```
kaan@Kaans-MacBook-Pro-2 minio % make
go: inconsistent vendoring in /Users/kaan/go/src/github.com/minio/minio:
	cloud.google.com/go/storage@v1.10.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/Azure/azure-storage-blob-go@v0.10.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/Shopify/sarama@v1.30.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/alecthomas/participle@v0.2.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/bcicen/jstream@v1.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/beevik/ntp@v0.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/bits-and-blooms/bloom/v3@v3.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/buger/jsonparser@v1.1.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/cespare/xxhash/v2@v2.1.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/cheggaaa/pb@v1.0.29: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/coredns/coredns@v1.9.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/coreos/go-oidc@v2.1.0+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/cosnicolaou/pbzip2@v1.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/dchest/siphash@v1.2.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/djherbis/atime@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/dswarbrick/smart@v0.0.0-20190505152634-909a45200d6d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/dustin/go-humanize@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/eclipse/paho.mqtt.golang@v1.3.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/elastic/go-elasticsearch/v7@v7.17.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/fatih/color@v1.13.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/felixge/fgprof@v0.9.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/fraugster/parquet-go@v0.10.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-ldap/ldap/v3@v3.4.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/loads@v0.21.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-sql-driver/mysql@v1.6.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/golang-jwt/jwt/v4@v4.4.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/gomodule/redigo@v1.8.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/google/uuid@v1.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/gorilla/mux@v1.8.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/hashicorp/golang-lru@v0.5.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/inconshreveable/mousetrap@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/json-iterator/go@v1.1.12: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/klauspost/compress@v1.15.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/klauspost/cpuid/v2@v2.0.11: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/klauspost/pgzip@v1.2.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/klauspost/readahead@v1.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/klauspost/reedsolomon@v1.9.15: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/lib/pq@v1.10.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/miekg/dns@v1.1.48: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/cli@v1.22.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/console@v0.18.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/csvparser@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/dperf@v0.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/highwayhash@v1.0.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/kes@v0.19.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/madmin-go@v1.3.14: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/minio-go/v7@v7.0.27: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/pkg@v1.1.24: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/selfupdate@v0.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/sha256-simd@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/simdjson-go@v0.4.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/sio@v0.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/zipindex@v0.2.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/mitchellh/go-homedir@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/montanaflynn/stats@v0.6.6: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/nats-io/nats-server/v2@v2.7.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/nats-io/nats.go@v1.13.1-0.20220308171302-2f2f6968e98d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/nats-io/stan.go@v0.10.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/ncw/directio@v1.0.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/nsqio/go-nsq@v1.0.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/philhofer/fwd@v1.1.2-0.20210722190033-5c56ac6d0bb9: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/pierrec/lz4@v2.6.1+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/pkg/errors@v0.9.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/prometheus/client_golang@v1.12.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/prometheus/client_model@v0.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/prometheus/procfs@v0.7.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/rs/cors@v1.7.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/rs/dnscache@v0.0.0-20211102005908-e0241e321417: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/secure-io/sio-go@v0.3.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/shirou/gopsutil/v3@v3.22.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/streadway/amqp@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/tinylib/msgp@v1.1.7-0.20211026165309-e818a1881b0e: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/valyala/bytebufferpool@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/xdg/scram@v0.0.0-20180814205039-7eeb5667e42c: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/yargevad/filepathx@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/zeebo/xxh3@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	go.etcd.io/etcd/api/v3@v3.5.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	go.etcd.io/etcd/client/v3@v3.5.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	go.uber.org/atomic@v1.9.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	go.uber.org/zap@v1.21.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/crypto@v0.0.0-20220411220226-7b82a4e95df4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/oauth2@v0.0.0-20220411215720-9780585627b5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/sys@v0.0.0-20220502124256-b6088ccd6cba: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/time@v0.0.0-20220224211638-0e9765cccd65: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	google.golang.org/api@v0.78.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	gopkg.in/yaml.v2@v2.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	cloud.google.com/go@v0.100.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	cloud.google.com/go/compute@v1.6.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	cloud.google.com/go/iam@v0.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/Azure/azure-pipeline-go@v0.2.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/Azure/go-ntlmssp@v0.0.0-20211209120228-48547f28849e: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/apache/thrift@v0.15.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/asaskevich/govalidator@v0.0.0-20210307081110-f21760c49a8d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/beorn7/perks@v1.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/bits-and-blooms/bitset@v1.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/briandowns/spinner@v1.18.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/charmbracelet/bubbles@v0.10.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/charmbracelet/bubbletea@v0.20.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/charmbracelet/lipgloss@v0.5.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/containerd/console@v1.0.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/coreos/go-semver@v0.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/coreos/go-systemd/v22@v22.3.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/davecgh/go-spew@v1.1.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/decred/dcrd/dcrec/secp256k1/v4@v4.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/docker/go-units@v0.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/eapache/go-resiliency@v1.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/eapache/go-xerial-snappy@v0.0.0-20180814174437-776d5712da21: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/eapache/queue@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/fatih/structs@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/frankban/quicktest@v1.14.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/gdamore/encoding@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/gdamore/tcell/v2@v2.4.1-0.20210905002822-f057f0a857a1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-asn1-ber/asn1-ber@v1.5.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-ole/go-ole@v1.2.6: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/analysis@v0.21.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/errors@v0.20.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/jsonpointer@v0.19.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/jsonreference@v0.20.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/runtime@v0.23.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/spec@v0.20.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/strfmt@v0.21.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/swag@v0.21.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/validate@v0.21.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-stack/stack@v1.8.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/goccy/go-json@v0.9.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/gogo/protobuf@v1.3.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/golang/groupcache@v0.0.0-20210331224755-41bb18bfe9da: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/golang/protobuf@v1.5.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/golang/snappy@v0.0.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/google/pprof@v0.0.0-20211214055906-6f57359322fd: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/google/shlex@v0.0.0-20191202100458-e7afc7fbc510: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/googleapis/gax-go/v2@v2.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/gorilla/websocket@v1.5.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/hashicorp/errwrap@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/hashicorp/go-multierror@v1.1.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/hashicorp/go-uuid@v1.0.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/jcmturner/aescts/v2@v2.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/jcmturner/dnsutils/v2@v2.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/jcmturner/gofork@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/jcmturner/gokrb5/v8@v8.4.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/jcmturner/rpc/v2@v2.0.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/jessevdk/go-flags@v1.5.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/josharian/intern@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/lestrrat-go/backoff/v2@v2.0.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/lestrrat-go/blackmagic@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/lestrrat-go/httpcc@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/lestrrat-go/iter@v1.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/lestrrat-go/jwx@v1.2.19: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/lestrrat-go/option@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/lucasb-eyer/go-colorful@v1.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/lufia/plan9stats@v0.0.0-20211012122336-39d0f177ccd0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/mailru/easyjson@v0.7.7: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/mattn/go-colorable@v0.1.12: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/mattn/go-ieproxy@v0.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/mattn/go-isatty@v0.0.14: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/mattn/go-runewidth@v0.0.13: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/matttproud/golang_protobuf_extensions@v1.0.2-0.20181231171920-c182affec369: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/colorjson@v1.0.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/filepath@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/mc@v0.0.0-20220512134321-aa60a8db1e4d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/minio/md5-simd@v1.1.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/mitchellh/mapstructure@v1.4.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/modern-go/concurrent@v0.0.0-20180306012644-bacd9c7ef1dd: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/modern-go/reflect2@v1.0.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/muesli/ansi@v0.0.0-20211031195517-c9f0611b6c70: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/muesli/reflow@v0.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/muesli/termenv@v0.11.1-0.20220212125758-44cd13922739: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/nats-io/jwt/v2@v2.2.1-0.20220113022732-58e87895b296: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/nats-io/nats-streaming-server@v0.24.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/nats-io/nkeys@v0.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/nats-io/nuid@v1.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/navidys/tvxwidgets@v0.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/oklog/ulid@v1.3.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/olekukonko/tablewriter@v0.0.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/pkg/xattr@v0.4.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/posener/complete@v1.2.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/power-devops/perfstat@v0.0.0-20220216144756-c35f1ee13d7c: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/pquerna/cachecontrol@v0.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/prometheus/common@v0.34.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/prometheus/prom2json@v1.3.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/rcrowley/go-metrics@v0.0.0-20201227073835-cf1acfcdf475: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/rivo/tview@v0.0.0-20220216162559-96063d6082f3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/rivo/uniseg@v0.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/rjeczalik/notify@v0.9.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/rogpeppe/go-internal@v1.8.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/rs/xid@v1.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/sirupsen/logrus@v1.8.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/tidwall/gjson@v1.14.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/tidwall/match@v1.1.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/tidwall/pretty@v1.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/tklauser/go-sysconf@v0.3.10: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/tklauser/numcpus@v0.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/unrolled/secure@v1.10.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/xdg/stringprep@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/yusufpapurcu/wmi@v1.2.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	go.etcd.io/etcd/client/pkg/v3@v3.5.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	go.mongodb.org/mongo-driver@v1.8.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	go.opencensus.io@v0.23.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	go.uber.org/goleak@v1.1.12: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	go.uber.org/multierr@v1.8.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/mod@v0.5.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/net@v0.0.0-20220425223048-2871e0cb64e4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/term@v0.0.0-20210927222741-03fcf44c2211: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/text@v0.3.7: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/tools@v0.1.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/xerrors@v0.0.0-20220411194840-2f41105eb62f: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	google.golang.org/appengine@v1.6.7: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	google.golang.org/genproto@v0.0.0-20220429170224-98d788798c3e: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	google.golang.org/grpc@v1.46.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	google.golang.org/protobuf@v1.28.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	gopkg.in/h2non/filetype.v1@v1.0.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	gopkg.in/ini.v1@v1.66.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	gopkg.in/square/go-jose.v2@v2.5.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	maze.io/x/duration@v0.0.0-20160924141736-faac084b6075: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
```

**Pull request merged**
