### PR TITLE
Append "-1" to etag when it is not MD5

### PR DESCRIPTION
**Pull request by krishnasrinivas**
## Description

"-1" is appended to ETag returned from Azure so that clients do not interpret it as MD5.

## Motivation and Context

https://github.com/minio/minio/issues/4537

https://github.com/s3tools/s3cmd/issues/880

## How Has This Been Tested?

manual, test case

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
LGTM not tested with s3cmd. Did you test further @krishnasrinivas ?

**Review by balamurugana — APPROVED** [review]
Not tested

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Keeping until we get reply from @krishnasrinivas

**Comment by krishnasrinivas** [comment]
s3cmd still does not work @harshavardhana 
I have updated https://github.com/s3tools/s3cmd/issues/880

**Review by harshavardhana — APPROVED** [review]
LGTM for the AWS S3 convention. s3cmd might have an issue still its upto s3cmd to resolve it.

**Comment by deekoder** [comment]
Holding on merging this PR hence.

**Comment by aead** [comment]
#4648

**Comment by deekoder** [comment]
@aead @krishnasrinivas  is this pr already addressing #4648

**Comment by aead** [comment]
@deekoder I don't think so - #4648 is S3 behavior, this PR addresses azure gateway

**Comment by harshavardhana** [comment]
> @deekoder I don't think so - #4648 is S3 behavior, this PR addresses azure gateway

@aead @deekoder this PR addresses azure gateway only. But it is a subset fix for #4648 which needs to cater for all our gateway and server backends as well.  @krishnasrinivas correct me here if i am wrong.

**Comment by deekoder** [comment]
Ah ok. Merging. Reviewers please advise on codecov/patch failing. Can it be re run?

**Comment by harshavardhana** [comment]
> Reviewers please advise on codecov/patch failing. Can it be re run?

codecov/patch won't be addressed since this is a GCS change. NO way to add unit tests.

**Comment by deekoder** [comment]
That i got @harshavardhana I am comparing 3 days ago it was a very different code coverage and post reviewers feedback it's very different.

**Comment by harshavardhana** [comment]
Oh I didn't see that. Perhaps @krishnasrinivas added unit tests.

**Pull request merged**
