### PR TITLE
minio-browser: do not redirect to /minio if MINIO_BROWSER=off

### LINKED ISSUE #2837: Endpoint gets redirected when server started with browser disabled
## Expected behaviour

Endpoint shouldn't be redirected to `/minio`
## Actual behaviour

Started minio server with browser disabled, but default endpoint URL is getting redirected to `/minio`
## Steps to reproduce the behaviour

```
$ MINIO_BROWSER=off minio server ~/storage/

Endpoint:  http://192.168.0.67:9000  http://127.0.0.1:9000  http://192.168.99.1:9000
AccessKey: floppyfloppy
SecretKey: floppyfloppy
Region:    us-east-1
SqsARNs:

Browser Access:
   http://192.168.0.67:9000  http://127.0.0.1:9000  http://192.168.99.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.0.67:9000 floppyfloppy floppyfloppy

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide


$ curl -i -X GET http://127.0.0.1:9000

HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Server: Minio/RELEASE.2016-09-11T17-42-18Z (darwin; amd64)
Vary: Origin
X-Amz-Request-Id: XG1DQ5BWMJUD3FFQ
Date: Tue, 04 Oct 2016 07:11:39 GMT
Content-Type: text/xml; charset=utf-8
Transfer-Encoding: chunked

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

⬆️  `curl` seems to be acting good, but browsers (Chrome, Safari, Firefox) are getting redirected.

See screenshots below:

chrome
firefox
safari
## Minio version
- (paste output of `minio version`)

```
$ minio version
Version: 2016-09-11T17:42:18Z
Release-Tag: RELEASE.2016-09-11T17-42-18Z
Commit-ID: 85e2d886bcb005d49f3876d6849a2b5a55e03cd3
```
## System information

OSX El Capitan (10.11.6)

EDIT: Markdown format

### PR DESCRIPTION
**Pull request by krishnasrinivas**
fixes #2837

### CODE REVIEW

**Comment by gowithplanb** [comment]
Why not allow to redirect to a custom URL when MINIO_BROWSER=off (set as for example MINIO_REDIRECT= ...) ?

**Comment by harshavardhana** [comment]
> Why not allow to redirect to a custom URL when MINIO_BROWSER=off (set as for example MINIO_REDIRECT= ...) ?

Can you open a new issue @gowithplanb and let us know why it is needed?

**Comment by krishnasrinivas** [comment]
> Why not allow to redirect to a custom URL when MINIO_BROWSER=off (set as for example MINIO_REDIRECT= ...) ?

@gowithplanb it's not useful for most people. Also you can achieve the same effect using nginx/traefik proxy, setting should be - if the path is "/" and Authorization header is not present redirect to your desired URL

**Comment by gowithplanb** [comment]
Opened issue #2866

**Pull request merged**
