### PR TITLE
Support TLS auth for Kafka notification target

### PR DESCRIPTION
**Pull request by rzrbld**
## Description
Added TLS auth with client cert\key pair for kafka message broker

## Motivation and Context
TLS auth for kafka

## How to test this PR?
[run a simple test](https://github.com/rzrbld/minio-kafka-notification-test)
or manually:
- make minio binary file and docker image
- run kafka broker with SSL auth
- add a kafka notify config to minio and restart minio service
```
mc admin config set local notify_kafka:1 tls_skip_verify="on"  queue_dir="" queue_limit="0" sasl="off" sasl_password="" sasl_username="" tls_client_auth="0" tls="on" client_tls_cert="/path/to/cert/client.crt" client_tls_key="/path/to/key/client.key" brokers="broker.host:9093" topic="minio_event_notification"
```
- make bucket and add event listener on it 
```
mc event add local/testbucket arn:minio:sqs::1:kafka
```
- put some files to that bucket
- consume messages from kafka topic

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#ef1c78f3-6f3f-45a5-9265-c64e4cf15df8) |
| mint-large-bucket.sh | :x: [more...](#cdb5132b-f505-4453-aba3-1d9c01e64a8e) |
| mint-worm.sh | :x: [more...](#fc5cadb3-4cbd-4929-a7e0-ba8bc4057fc3) |
| mint-fs.sh | :x: [more...](#5941411a-5f88-443c-b2ba-b49d0269cb87) |
| mint-dist-xl.sh | :x: [more...](#e5bfecd7-44e4-4e5c-921f-d8f1d9aedac2) |
<a name="5941411a-5f88-443c-b2ba-b49d0269cb87"></a>
### 8609-053840c/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30680
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eba7544f36ae:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ehxt1iiot1p1ye",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 319,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.56:30680/aws-sdk-go-test-ehxt1iiot1p1ye: dial tcp 72.28.97.56:30680: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="cdb5132b-f505-4453-aba3-1d9c01e64a8e"></a>
### 8609-053840c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30840
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e4d3a0f20b97:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-9eqiabe5rwkmzi",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365362,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15DD87012CEBE365, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="fc5cadb3-4cbd-4929-a7e0-ba8bc4057fc3"></a>
### 8609-053840c/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30814
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 25ddb989d7a1:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-7lb53j9yyxzqk1236u18wytpvkgiwwouajo09v3lv3akf22fzbf5msr",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 352,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.52:30814/bucket-7lb53j9yyxzqk1236u18wytpvkgiwwouajo09v3lv3akf22fzbf5msr: dial tcp 72.28.97.52:30814: connect: connection refused",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="ef1c78f3-6f3f-45a5-9265-c64e4cf15df8"></a>
### 8609-053840c/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31708
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e9b0d378be0a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 7 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-lsnlzb0r1jab3u",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 366318,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15DD87014D239D67, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="e5bfecd7-44e4-4e5c-921f-d8f1d9aedac2"></a>
### 8609-053840c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32296
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7742c178ed9b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 7 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gujcseixy4656h",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 366192,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15DD87017649F7E5, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Error: No such image: minio/minio:8609-053840c

**Comment by harshavardhana** [comment]
Can you please update the PR title to "Support TLS auth for Kafka notification target" ?

**Comment by rzrbld** [comment]
done :+1:

**Review by harshavardhana — APPROVED** [review]

**Comment by rzrbld** [comment]
@harshavardhana thanks for your collaboration. @poornas can you please review this PR?

**Review by poornas — APPROVED** [review]
LGTM

**Comment by rzrbld** [comment]
@poornas thank you

**Comment by rzrbld** [comment]
@harshavardhana @nitisht  sorry for bothering you, but all the checks passed and all the reviewers is complete their reviews, but merge isn't started

**Comment by harshavardhana** [comment]
> @harshavardhana @nitisht sorry for bothering you, but all the checks passed and all the reviewers is complete their reviews, but merge isn't started

We will get to it @rzrbld in time, no need to panic.

**Comment by rzrbld** [comment]
ok :+1:

**Pull request merged**
