### PR TITLE
add additional logging during server formatting

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
add additional logging during server formatting

## Motivation and Context
Just more logging refer #9052 

## How to test this PR?
Nothing special

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#edf9797e-f3c5-4bf0-a576-771d2909dfb4) |
| mint-gateway-azure.sh | :x: [more...](#59d122fe-fe6a-4a2b-8fe7-a28095e0be63) |
<a name="59d122fe-fe6a-4a2b-8fe7-a28095e0be63"></a>
### 9102-173cdb0/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30126
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 735686775f1d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-u46churm4l2lge",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120274,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30126/aws-sdk-go-test-u46churm4l2lge: dial tcp 72.28.97.55:30126: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="edf9797e-f3c5-4bf0-a576-771d2909dfb4"></a>
### 9102-173cdb0/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30021
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6dbe5d1c5ad9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wbs9cl5mokpvd0",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120336,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30021/aws-sdk-go-test-wbs9cl5mokpvd0: dial tcp 72.28.97.55:30021: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#6ac9c37a-4eaf-4e0f-a0a3-7895320f264c) |
<a name="6ac9c37a-4eaf-4e0f-a0a3-7895320f264c"></a>
### 9102-f0245a4/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30713
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b6d7efedd793:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 6 minutes and 33 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 3 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 25 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(9/14) Running minio-go tests ... done in 19 minutes and 48 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 32 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11308,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-gpuana, objectName=minio-java-test-2hrso8a, resource=/minio-java-test-gpuana/minio-java-test-2hrso8a, requestId=15FA4AE2B7BF6B38, hostId=f0b8f53f-46c5-4ad1-99bc-5a37ca178fbf)\nrequest={method=PUT, url=http://72.28.97.59:30713/minio-java-test-gpuana/minio-java-test-2hrso8a?uploadId=00ff02dd0ab06352&partNumber=1, headers=x-amz-copy-source-if-match: 4f53eda56d84161c491e32ec2e166357-2\nx-amz-copy-source: minio-java-test-gpuana/minio-java-test-2ibd7qr\nAccept-Encoding: identity\nHost: 72.28.97.59:30713\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200308T094236Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200308/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-08T08-37-44Z\nVary: Origin\nX-Amz-Request-Id: 15FA4AE2B7BF6B38\nX-Xss-Protection: 1; mode=block\nDate: Sun, 08 Mar 2020 09:42:36 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
LGTM

**Review by poornas — APPROVED** [review]
LGTM

**Pull request merged**
