### PR TITLE
Add missing env doc for MINIO_DOMAIN

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add missing env doc for MINIO_DOMAIN

## Motivation and Context
fixing docs

## How Has This Been Tested?
visually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by balamurugana — DISMISSED** [review]
LGTM

**Review by nitisht — COMMENTED** [review]
IMHO we can change `To enable virtual-host-style requests. By default only path-style requests are allowed.` to `To enable virtual-host-style requests, set this value to Minio host's domain name.` 

This will be clearer for users on what should be set in this variable.

**Comment by harshavardhana** [comment]
> IMHO we can change To enable virtual-host-style requests. By default only path-style requests are allowed. to To enable virtual-host-style requests, set this value to Minio host's domain name.
> 
> This will be clearer for users on what should be set in this variable.

done @nitisht

**Review by nitisht — APPROVED** [review]
LGTM

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by balamurugana — APPROVED** [review]
LGTM

**Pull request merged**
