### PR TITLE
log: Pretty print some errors

### LINKED ISSUE #4390: minio gateway help instead of error
```
minio gateway gcs
FATA[0000] Access and secret keys are mandatory to run Minio gateway server.  cause=Missing credentials source=[gateway-main.go:113:mustGetGatewayConfigFromEnv()]
```

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Some errors are better to be shown more friendly. prettyFatalIf and
prettyErrorIf are added.

## Motivation and Context
Fixes #4390 

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by vadmeste** [comment]
This doesn't fully fix the issue #4390, it prints like this:
```
$ minio gateway s3
FATA[0000] Unable to validate access and secret keys before running Minio gateway server: Missing credentials. 
```

I thought we probably can keep `FATA[0000]` since it indicates that minio was obliged to quit due to the printed error

**Comment by harshavardhana** [comment]
what is the problem in existing printing? @vadmeste.  Regardless this requires architecture review from @abperiasamy

**Comment by vadmeste** [comment]
> what is the problem in existing printing?

This issue fixes #4442 

> Regardless this requires architecture review from @abperiasamy

Yeah, let's discuss it.

**Comment by harshavardhana** [comment]
Can you rebase this PR @vadmeste ?

**Comment by vadmeste** [comment]
> Can you rebase this PR @vadmeste ?

Done

**Comment by deekoder** [comment]
Show help instead of log message. Log messages are shown only after server starts. For input validation pretty print message & do not show log messaging.

**Pull request closed without merging**
