### PR TITLE
fix: lock expiry on zoned setups

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: lock expiry on zoned setups

## Motivation and Context
lock ownership is limited to endpoints on the first zone,
as we do not hold locks on other zones in an expanded
setup. current code unintentionally expired active locks
when it couldn't see ownership from the secondary zone
which leads to unexpected bugs as locking fails to work
as expected.

## How to test this PR?
```
minio server --address :9001 http://localhost:9001/data/mindev/data/disterasure/xl{1...4} http://localhost:9002/data/mindev/data/disterasure/xl{5...8}
minio server --address :9002 http://localhost:9001/data/mindev/data/disterasure/xl{1...4} http://localhost:9002/data/mindev/data/disterasure/xl{5...8}
```

In the following setup observe `mc admin top locks myminio` and 
see `leader-data-usage-info` automatically gets cleared up upon expiry. With this PR
this won't happen leader locks stay on forever. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#1b9895f8-e361-47ca-aeba-cd571e62b712) |
| mint-gateway-nas.sh | :x: [more...](#f2e228ae-7db4-4ec4-8f40-216b845ad1a5) |
<a name="1b9895f8-e361-47ca-aeba-cd571e62b712"></a>
### 9084-98890b8/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30017
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7404ad389943:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 31 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 3 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 4 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(9/14) Running minio-go tests ... done in 20 minutes and 59 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 25 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11812,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-20ljedq, objectName=minio-java-test-177p52l, resource=/minio-java-test-20ljedq/minio-java-test-177p52l, requestId=15F93284D5F13467, hostId=05770f9a-00dd-4a25-8da7-b9ec573a5f36)\nrequest={method=PUT, url=http://72.28.97.57:30017/minio-java-test-20ljedq/minio-java-test-177p52l?uploadId=2dc9f1b071e1e4ba&partNumber=1, headers=x-amz-copy-source-if-match: e1b24dc0efff77ff77481b16c587c3c6-2\nx-amz-copy-source: minio-java-test-20ljedq/minio-java-test-a131eb\nAccept-Encoding: identity\nHost: 72.28.97.57:30017\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200304T200450Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200304/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-04T18-59-46Z\nVary: Origin\nX-Amz-Request-Id: 15F93284D5F13467\nX-Xss-Protection: 1; mode=block\nDate: Wed, 04 Mar 2020 20:04:50 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="f2e228ae-7db4-4ec4-8f40-216b845ad1a5"></a>
### 9084-98890b8/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31526
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aaa5dd477efa:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-frrc3fodfek9y3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120316,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31526/aws-sdk-go-test-frrc3fodfek9y3: dial tcp 72.28.97.55:31526: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#f46a6c09-474c-47b0-a715-e3e4ebfb97a5) |
| mint-gateway-azure.sh | :x: [more...](#8ae77e2a-912f-4c10-81f5-949c558cfc07) |
<a name="f46a6c09-474c-47b0-a715-e3e4ebfb97a5"></a>
### 9084-81f7f4a/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32349
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bb901a25b707:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-hzix6rsuui5uuq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365931,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F933EDFD8662AE, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="8ae77e2a-912f-4c10-81f5-949c558cfc07"></a>
### 9084-81f7f4a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32026
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e9ee01b8fede:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 3 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 20 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 44 seconds
(9/14) Running minio-go tests ... done in 21 minutes and 34 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 22 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 10924,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-1q6rlnf, objectName=minio-java-test-3712mbr, resource=/minio-java-test-1q6rlnf/minio-java-test-3712mbr, requestId=15F93631621EBE83, hostId=d1f9ce3f-0c5e-4b46-9761-a743093146d2)\nrequest={method=PUT, url=http://72.28.97.52:32026/minio-java-test-1q6rlnf/minio-java-test-3712mbr?uploadId=c1a23b0e3a67f75e&partNumber=1, headers=x-amz-copy-source-if-match: be55b8c6e79321bb953d8899541ae8ab-2\nx-amz-copy-source: minio-java-test-1q6rlnf/minio-java-test-283mqp4\nAccept-Encoding: identity\nHost: 72.28.97.52:32026\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200304T211209Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200304/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-04T20-05-59Z\nVary: Origin\nX-Amz-Request-Id: 15F93631621EBE83\nX-Xss-Protection: 1; mode=block\nDate: Wed, 04 Mar 2020 21:12:10 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by poornas — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
