### PR TITLE
Add more advanced cases for dangling

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Add more advanced cases for dangling

## Motivation and Context
unreadable xl.meta returning errCorrupt
we can leave them as is and not consider
for dangling as part of future inspections.

## How to test this PR?
CI/CD is updated to test the scenarios

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by vadmeste** [comment]
Removing validMeta.IsRemote() is a bit dangerous for such a dangerous function.

The reason is that parts do not really exist  in a transitioned object and any further changes in another place the code in can break this and I do no think we have enough unit tests to cover this specific use case.

**Comment by harshavardhana** [comment]
There is no reason to have that because that is redundant @vadmeste

**Comment by harshavardhana** [comment]
You should read the code again not just in silo some portions, but instead read it fully to understand.

**Pull request merged**
