### PR TITLE
docs: Created new illustration for docs.

### LINKED ISSUE #3919: docs: Images need an overhaul to match styles on docs.minio.io

### PR DESCRIPTION
**Pull request by belvid**
Replacing illustrations in docs.minio.io to match style of new UI. Fixed #3919

### CODE REVIEW

**Comment by harshavardhana** [comment]
Waiting on testing reports from @deekoder

**Comment by deekoder** [comment]
Testing now

**Review by deekoder — CHANGES_REQUESTED** [review]
Test Failed. Analyzing root cause on why.

**Comment by justinclift** [comment]
Nice looking graphics @belvid. :smile:

**Comment by harshavardhana** [comment]
what is pending on this? @deekoder @belvid

**Comment by deekoder** [comment]
I will verify the images today!!!

**Comment by harshavardhana** [comment]
> I will verify the images today!!!

:+1:

**Comment by deekoder** [comment]
Ugh. I am finally doing this now.

**Comment by deekoder** [comment]
Finally verified. It looks good to me. Here are the screenshots. I do have one question. I have 2 more images from you @belvid which i don't see a place for in in our docs. 

erasure
distributed

**Review by deekoder — APPROVED** [review]
In general the styling now fits well with our docs.

**Comment by harshavardhana** [comment]
> In general the styling now fits well with our docs.

Thank you @deekoder

**Comment by belvid** [comment]
The screenshot looks good to me too. \o/

**Comment by belvid** [comment]
About those two images, I'll check location and I'll get back to you. I'm sure they most be somewhere in the docs.

**Comment by belvid** [comment]
@deekoder @harshavardhana The Architecture image is located on Minio Deployment Quickstart Guide, almost at the bottom of the list.

**Comment by harshavardhana** [comment]
Are the png's going to be updated here as well? or is this PR ready to be merged?

**Comment by belvid** [comment]
I think it is ready Harsha. You can go ahead.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
