### PR TITLE
Fix tier addition validation

### PR DESCRIPTION
**Pull request by poornas**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
preliminary probe was not cleaning up the versioned content created on remote tier.

## Motivation and Context
Fix tier in use error

## How to test this PR?
```
 mc admin tier add minio sitea tier1 --endpoint http://localhost:9004 --access-key minio --secret-key minio123 --bucket bucket --prefix prefix6/
mc: <ERROR> Unable to configure remote tier target. Specified remote tier is already in use.
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by harshavardhana** [comment]
@poornas I think the idea was we do not expect DeleteVersion permission on the backend bucket. This will bring it back. Can we do cleanup differently? Or not do at all?

**Comment by vadmeste** [comment]
@poornas can you show how to reproduce from scratch ? I **think** the point of the error is that a path in the warm tier is already in use probably by another tiering configuration, so we abort quickly. I do not think we should clean up in the first place.

**Comment by poornas** [comment]
> @poornas can you show how to reproduce from scratch ? I **think** the point of the error is that a path in the warm tier is already in use probably by another tiering configuration, so we abort quickly. I do not think we should clean up in the first place.

clean up was only for the probe object created to test permissions - just try tier addition on a versioned bucket. It will fail with tier in use error

**Comment by vadmeste** [comment]
> clean up was only for the probe object created to test permissions - just try tier addition on a versioned bucket. It will fail with tier in use error

It doesn't fail for me. Can you try with a new versioned bucket without this PR ?

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
I talked with @kannappanr and I understand more now;

In all cases, we need s3:DeleteObjectVersion in case the user enabled versioning in the warm tier and that may cause a lot of soft deletes not being correctly cleaned up

**Pull request merged**
