### PR TITLE
feat(Router): Add route name

### PR DESCRIPTION
**Pull request by MoonJustry**
convenient for monitoring and management, etc.

## Description
1. Set the name for all current api routes. 
2. Typo: `completemutipartupload` to `completemultipartupload `

## Motivation and Context
Get the current route name in the request context to facilitate some things, such as custom monitoring and reporting.

## How to test this PR?
Nothing special to test

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
What kind of monitoring does this facilitate?

**Comment by MoonJustry** [comment]
> What kind of monitoring does this facilitate?

After adding the route name, it is easy to get the route name (api name) wherever the request context can be obtained. It can be used as a monitoring metrics tag or as a log field, instead of relying on the api name registered in the handler context. If I need to customize a filter handler to collect all the request delay, status code and other information uniformly, the route name is indispensable.

**Comment by harshavardhana** [comment]
> After adding the route name, it is easy to get the route name (api name) wherever the request context can be obtained. It can be used as a monitoring metrics tag or as a log field, instead of relying on the api name registered in the handler context. If I need to customize a filter handler to collect all the request delay, status code and other information uniformly, the route name is indispensable.

how?

**Comment by klauspost** [comment]
> [...] instead of relying on the api name registered in the handler context

@MoonJustry Then please make it so it doesn't have to be specified in multiple places. It should only be specified once, otherwise there is too big a chance of mistakes.

**Comment by harshavardhana** [comment]
> 2\. Typo: `completemutipartupload` to `completemultipartupload `

The only valid change here is this, the rest we should avoid for now - not comfortable making changes at the routing layer at this point in time.

**Comment by MoonJustry** [comment]
> > [...] instead of relying on the api name registered in the handler context
> 
> @MoonJustry Then please make it so it doesn't have to be specified in multiple places. It should only be specified once, otherwise there is too big a chance of mistakes.

What you said makes sense, so can you consider using a more general approach in the future? For example, set the route name uniformly, and get the api name from the route. But now some APIs have API name set inside the handler context, and some don't even have it.

My current purpose is to add a pre handler to report some monitoring information to my monitoring system (although Prometheus is currently supported). At this time, I hope to get the routing name at the routing layer.

**Comment by harshavardhana** [comment]
Relevant PR is merged - lets table this for another rainy day

**Pull request closed without merging**
