### PR TITLE
validate bucket before attempting batch replication

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
validate bucket before attempting batch replication

## Motivation and Context
- source bucket must exist and readable
- target bucket must exist and matches source bucket configuration

## How to test this PR?
Need two servers and some data to start batch replication.
```yaml
replicate:
  apiVersion: v1
  flags:
    notify:
      endpoint: "http://localhost:8080"
      
  source:
    type: "minio"
    bucket: "testbucket-v"
    prefix: ""
  
  target:
    type: "minio"
    bucket: "testbucket-v"
    endpoint: "http://localhost:9001"
    credentials:
      accessKey: "minioadmin"
      secretKey: "minioadmin"
      sessionToken: ""
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#24078bd0-3c3d-41ec-a5b7-68ead4690ea0) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#8cd9f9ea-d979-441b-9019-1104321a90bd) |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#47878d13-5407-441c-b154-f42a02093bed) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#3cdba201-81b4-4886-9f8d-c430a2306675) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#70af78dc-db80-4b59-921e-64bb9ad4ee73) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#add9d4f0-2258-4eb3-8aeb-b5f418b78b5d) |
| mint-pools.sh | :heavy_exclamation_mark: [more...](#d7906926-8d92-483e-94d5-409cfe3846d3) |
<a name="47878d13-5407-441c-b154-f42a02093bed"></a>
### 15861-3a0b105/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="24078bd0-3c3d-41ec-a5b7-68ead4690ea0"></a>
### 15861-3a0b105/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="add9d4f0-2258-4eb3-8aeb-b5f418b78b5d"></a>
### 15861-3a0b105/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="3cdba201-81b4-4886-9f8d-c430a2306675"></a>
### 15861-3a0b105/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="8cd9f9ea-d979-441b-9019-1104321a90bd"></a>
### 15861-3a0b105/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="d7906926-8d92-483e-94d5-409cfe3846d3"></a>
### 15861-3a0b105/mint-pools.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="70af78dc-db80-4b59-921e-64bb9ad4ee73"></a>
### 15861-3a0b105/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#2aa7fdf1-3bda-475e-a891-becb8f53152d) |
| mint-gateway-s3.sh | :x: [more...](#14dd490b-d82e-40d8-8f0c-2bd7a6f00202) |
<a name="2aa7fdf1-3bda-475e-a891-becb8f53152d"></a>
### 15861-2d14bea/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.22:30692
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp c10fd59cfe43:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 12 seconds
(8/14) Running minio-go tests ... FAILED in 4 seconds
{
  "args": {
    "bucketName": "minio-go-test-5ep1jle6huuhbtxx",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "dfbxl66vdzz0tubldr5ald6c5eejr3",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2522,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 16 seconds
(9/14) Running minio-js tests ... done in 42 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 5 seconds
(11/14) Running s3cmd tests ... done in 12 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="14dd490b-d82e-40d8-8f0c-2bd7a6f00202"></a>
### 15861-2d14bea/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:32675
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 151faca1496c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... FAILED in 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-n5fhzhowyazc4mid",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "kcopi01iqbwfeqkr9y6i6kr6d3dxm4",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3873,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 38 seconds
(9/14) Running minio-js tests ... done in 37 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 18 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 2 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#6376d0de-9800-4190-89fc-e39763433538) |
| mint-gateway-s3.sh | :x: [more...](#3a420848-39d6-4318-8a76-a1ac68dd1696) |
<a name="6376d0de-9800-4190-89fc-e39763433538"></a>
### 15861-2801b13/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.18:30429
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 465e60c7d385:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... FAILED in 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-ye9cr32nkm24tq9e",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "0ums0ipiq5ixxkaz0rwz2wlbrnyirh",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2983,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 17 seconds
(9/14) Running minio-js tests ... done in 43 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 8 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="3a420848-39d6-4318-8a76-a1ac68dd1696"></a>
### 15861-2801b13/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.2:30549
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 237407869efd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 14 seconds
(8/14) Running minio-go tests ... FAILED in 6 seconds
{
  "args": {
    "bucketName": "minio-go-test-y2yntsyj6opivgn5",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "9lrmii1fnvn22iq9ewnkyhctglvo9s",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3268,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 29 seconds
(9/14) Running minio-js tests ... done in 34 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 9 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 3 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#e9475744-5cba-4e70-b353-b0b53dd9b4f5) |
| mint-gateway-s3.sh | :x: [more...](#58ceeb75-5740-46ae-88d9-624177a2f137) |
<a name="e9475744-5cba-4e70-b353-b0b53dd9b4f5"></a>
### 15861-f9dd29f/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.5:31888
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 0c0633cd5a24:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... FAILED in 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-bbtnh039hu4yj1u9",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "j19p55niw92nmynfqxnneudrkpj5ax",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2808,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 17 seconds
(9/14) Running minio-js tests ... done in 42 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 8 seconds
(11/14) Running s3cmd tests ... done in 13 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="58ceeb75-5740-46ae-88d9-624177a2f137"></a>
### 15861-f9dd29f/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:30621
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 90556355cf62:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... FAILED in 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-rs9eepnauou2mxjv",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "cd6uy42dynytfup2ie1ifb4slirs4n",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 4080,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 37 seconds
(9/14) Running minio-js tests ... done in 37 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 17 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 6 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
Tested. LGTM

**Pull request merged**
