### PR TITLE
Support any string as delimiter for listing

### PR DESCRIPTION
**Pull request by krishnasrinivas**
## Description
To support any string as delimiter. Currently we support empty string and /

## How to test this PR?
Make the bucket public and send hand crafted curl requests.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#b51f09f1-ebb5-4ccf-aa7e-e17922743508) |
| mint-gateway-nas.sh | :x: [more...](#948f0b27-81c3-41c8-9fb6-fa9606fedb8f) |
<a name="b51f09f1-ebb5-4ccf-aa7e-e17922743508"></a>
### 7882-2ab6709/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30118
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp adf9acf6600f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 56 seconds
(10/14) Running minio-java tests ... FAILED in 41 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 1136,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2qb3pv1, objectName=minio-java-test-2gpt3pl, resource=/minio-java-test-2qb3pv1/minio-java-test-2gpt3pl, requestId=15AE7473ECB4598A, hostId=fcea8bc0-7b69-411d-9115-9b2cd5bc2b61)\nrequest={method=DELETE, url=http://72.28.97.60:30118/minio-java-test-2qb3pv1/minio-java-test-2gpt3pl?uploadId=9ca5ab8d-c059-48ee-b23e-cca19c98e0da, headers=Host: 72.28.97.60:30118\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190705T080921Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190705/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-05T07-50-17Z\nVary: Origin\nX-Amz-Request-Id: 15AE7473ECB4598A\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Jul 2019 08:09:22 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="948f0b27-81c3-41c8-9fb6-fa9606fedb8f"></a>
### 7882-2ab6709/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32694
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 53ac7a148ae3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-eicuomwgtju2ip",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3081,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32694/aws-sdk-go-test-eicuomwgtju2ip: dial tcp 72.28.97.57:32694: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
Is this WIP @krishnasrinivas can you also add some unit tests for this change ?

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#4ffff47b-1260-42cd-9894-260aea5ed5f3) |
| mint-fs.sh | :x: [more...](#b2c81e3a-cfe7-4a62-b9ee-0f829b0ae429) |
| mint-dist-xl.sh | :x: [more...](#0259c20c-d546-4713-90e7-76ea68b08b5d) |
<a name="4ffff47b-1260-42cd-9894-260aea5ed5f3"></a>
### 7882-531cd9b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31325
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f68ce14baf30:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 4 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 12 seconds
(4/14) Running aws-sdk-ruby tests ... done in 22 seconds
(5/14) Running awscli tests ... done in 2 minutes and 32 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 3 minutes and 3 seconds
{
  "name": "mc",
  "duration": "124286",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-14022 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-6823  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-6823/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-6823/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-6823/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-6823/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-6823/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-6823/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-6823/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-6823/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-6823/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-6823/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-6823/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-6823/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-6823/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-6823/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-6823/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 557.40 MiB, Speed: 4.49 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="b2c81e3a-cfe7-4a62-b9ee-0f829b0ae429"></a>
### 7882-531cd9b/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32072
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f696ac71e43e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-4mxscubgmdneci",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3068,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32072/aws-sdk-go-test-4mxscubgmdneci: dial tcp 72.28.97.57:32072: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0259c20c-d546-4713-90e7-76ea68b08b5d"></a>
### 7882-531cd9b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30166
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 31072d55d22d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 57 seconds
(10/14) Running minio-java tests ... FAILED in 43 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 590,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1m3iol9, objectName=minio-java-test-fm391h, resource=/minio-java-test-1m3iol9/minio-java-test-fm391h, requestId=15AE9D01538459C3, hostId=f5870b82-76e5-4ebd-8593-1540fd372e75)\nrequest={method=DELETE, url=http://72.28.97.55:30166/minio-java-test-1m3iol9/minio-java-test-fm391h?uploadId=f23d0162-74d7-4102-8b4f-2ab0e97673bb, headers=Host: 72.28.97.55:30166\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190705T203229Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190705/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-05T20-13-21Z\nVary: Origin\nX-Amz-Request-Id: 15AE9D01538459C3\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Jul 2019 20:32:30 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#98c28ab1-47f4-4260-9b07-3c37ef1d1ac0) |
| mint-worm.sh | :x: [more...](#1d9d56bc-6c5f-4c58-9150-f70262f6ec1d) |
| mint-fs.sh | :x: [more...](#13367d9d-1572-4eba-81d2-2db8f93faf86) |
<a name="13367d9d-1572-4eba-81d2-2db8f93faf86"></a>
### 7882-4114804/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31607
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cbc7d2ff00ca:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dt5tiv9hav0mix",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3051,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31607/aws-sdk-go-test-dt5tiv9hav0mix: dial tcp 72.28.97.57:31607: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="98c28ab1-47f4-4260-9b07-3c37ef1d1ac0"></a>
### 7882-4114804/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30211
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 636e9e12c24f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 10 minutes and 48 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5d1fb810dc6b3"
  },
  "duration": "41138",
  "status": "FAIL",
  "error": "Error executing \"PutObject\" on \"http://72.28.97.55:30211/aws-sdk-php-5d1fb810dc6b3/test-anon\"; AWS HTTP error: Client error: `PUT http://72.28.97.55:30211/aws-sdk-php-5d1fb810dc6b3/test-anon` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of byte (truncated...)\n IncompleteBody (client): You did not provide the number of bytes specified by the Content-Length HTTP header. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of bytes specified by the Content-Length HTTP header.</Message><Key>test-anon</Key><BucketName>aws-sdk-php-5d1fb810dc6b3</BucketName><Resource>/aws-sdk-php-5d1fb810dc6b3/test-anon</Resource><RequestId>15AE9E9260EE6D5E</RequestId><HostId>36b6a148-8478-40c4-ad89-1044d0b798ba</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="1d9d56bc-6c5f-4c58-9150-f70262f6ec1d"></a>
### 7882-4114804/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32607
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d32cee24fd24:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-8kq8ty5zcbflimpsfdqc281q3nm7yiqe2gyzg8npu23z6bvln72qpiu",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 3013,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32607/bucket-8kq8ty5zcbflimpsfdqc281q3nm7yiqe2gyzg8npu23z6bvln72qpiu: dial tcp 72.28.97.57:32607: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```

**Review by poornas — APPROVED** [review]

**Pull request merged**
