### PR TITLE
feat: time to bring back http2.0 support

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
feat: time to bring back http2.0 support

## Motivation and Context
Bonus move our CI/CD to go1.14

## How to test this PR?
```bash
#!/usr/bin/env bash

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"
export MINIO_ARGS="https://localhost:9002/tmp/02 https://localhost:9003/tmp/03 https://localhost:9004/tmp/04 https://localhost:9005/tmp/05 https://localhost:9006/tmp/06 https://localhost:9007/tmp/07 https://localhost:9008/tmp/08 https://localhost:9009/tmp/09"

for i in {02..09}; do
    "${GOPATH}/bin/minio" server --certs-dir ../minio-go/testcerts/ --address ":90${i}" &
done
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#5893e83a-3db7-4d0e-bd44-a5323c5c5a89) |
| mint-gateway-azure.sh | :x: [more...](#560db4e0-6fe8-49e1-a1ed-3ebf31e7e972) |
<a name="5893e83a-3db7-4d0e-bd44-a5323c5c5a89"></a>
### 10230-87e7ac1/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31451
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 62fa03a5053f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 13 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 26 seconds
{
  "name": "mc",
  "duration": "9826",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-29162 --quiet --no-color cp myminio/mc-test-bucket-25719/mc-test-object-21442 mc-test-object-21442.downloaded  >>> \n`myminio/mc-test-bucket-25719/mc-test-object-21442` -> `mc-test-object-21442.downloaded`\nmc: <ERROR> Failed to copy `http://minio-dev6.minio.io:31451/mc-test-bucket-25719/mc-test-object-21442`. read tcp 172.17.0.8:37992->72.28.97.55:31451: read: connection reset by peer\nTotal: 0 B, Transferred: 60.84 MiB, Speed: 27.65 MiB/s"
}
(7/15) Running minio-dotnet tests ... done in 1 minutes and 1 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 54 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 29 seconds
(10/15) Running minio-js tests ... done in 52 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 18 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="560db4e0-6fe8-49e1-a1ed-3ebf31e7e972"></a>
### 10230-87e7ac1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32723
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp df88c8a92784:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 9 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 6 seconds
{
  "name": "awscli",
  "duration": 1594,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 23 seconds
(7/15) Running minio-dotnet tests ... done in 2 minutes and 42 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 28 seconds
(9/15) Running minio-java tests ... done in 6 minutes and 9 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 36 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 27 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 22 seconds
(13/15) Running s3select tests ... done in 1 minutes and 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :x: [more...](#145bb3d7-614c-4cd2-96f6-87bf85b6ca13) |
| mint-large-bucket.sh | :x: [more...](#ad074574-cfb7-4a85-a0ae-5fda11979635) |
| mint-fs.sh | :x: [more...](#9096e63f-f432-4433-9307-e5b96535d772) |
| mint-dist-xl.sh | :x: [more...](#483b67dc-210d-4e5f-b30b-4d9677270a9d) |
| mint-gateway-s3.sh | :x: [more...](#f509743e-112e-40be-acb3-e5bc32237432) |
| mint-gateway-azure.sh | :x: [more...](#1ae275b9-5633-4a8f-992a-10dc844cb187) |
| mint-zoned.sh | :x: [more...](#95a38128-04fc-4dd7-a2cb-e6e92dbb4078) |
| mint-gateway-nas.sh | :x: [more...](#0eb6b4dd-e445-422e-8c53-42093749fe0e) |
<a name="ad074574-cfb7-4a85-a0ae-5fda11979635"></a>
### 10230-9f67ca0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31782
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fe6bf04be67b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 26 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 5 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 4 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 55 seconds
(10/15) Running minio-java tests ... done in 2 minutes and 9 seconds
(11/15) Running minio-js tests ... done in 59 seconds
(12/15) Running minio-py tests ... FAILED in 3 minutes and 49 seconds
{
  "name": "minio-py:test_presigned_get_object_version",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-6e8f1b39-80ad-46a4-844b-d07f97e0559b",
    "object_name": "c30621e5-9874-4e9e-b245-4716d8c7d374"
  },
  "message": "InvalidArgument: message: Invalid Argument",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 147, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1508, in test_presigned_get_object_version\n    object_name).get_exception()\nminio.error.InvalidArgument: InvalidArgument: message: Invalid Argument\n",
  "duration": 494
}
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... FAILED in 0 seconds
Traceback (most recent call last):
  File "./tests.py", line 23, in <module>
    from sql_ops import *
  File "/mint/run/core/s3select/sql_ops.py", line 22, in <module>
    from minio.select.options import (SelectObjectOptions, CSVInput, JSONInput,
ImportError: cannot import name 'JsonOutput'
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="9096e63f-f432-4433-9307-e5b96535d772"></a>
### 10230-9f67ca0/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30809
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 36b71b816690:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 1 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 35 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 28 seconds
(10/15) Running minio-java tests ... done in 24 seconds
(11/15) Running minio-js tests ... done in 58 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 24 seconds
(13/15) Running s3cmd tests ... done in 17 seconds
(14/15) Running s3select tests ... FAILED in 0 seconds
Traceback (most recent call last):
  File "./tests.py", line 23, in <module>
    from sql_ops import *
  File "/mint/run/core/s3select/sql_ops.py", line 22, in <module>
    from minio.select.options import (SelectObjectOptions, CSVInput, JSONInput,
ImportError: cannot import name 'JsonOutput'
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="483b67dc-210d-4e5f-b30b-4d9677270a9d"></a>
### 10230-9f67ca0/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30187
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ad4f2a49dc0a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 23 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 57 seconds
(8/15) Running minio-dotnet tests ... done in 45 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 30 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 20 seconds
(11/15) Running minio-js tests ... done in 55 seconds
(12/15) Running minio-py tests ... FAILED in 2 minutes and 50 seconds
{
  "name": "minio-py:test_presigned_get_object_version",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-203bdc2c-79d0-48ac-99b5-704249e87e3c",
    "object_name": "5902421a-13dc-4719-be4f-743b1e8fd3c3"
  },
  "message": "InvalidArgument: message: Invalid Argument",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 147, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1508, in test_presigned_get_object_version\n    object_name).get_exception()\nminio.error.InvalidArgument: InvalidArgument: message: Invalid Argument\n",
  "duration": 314
}
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... FAILED in 1 seconds
Traceback (most recent call last):
  File "./tests.py", line 23, in <module>
    from sql_ops import *
  File "/mint/run/core/s3select/sql_ops.py", line 22, in <module>
    from minio.select.options import (SelectObjectOptions, CSVInput, JSONInput,
ImportError: cannot import name 'JsonOutput'
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="f509743e-112e-40be-acb3-e5bc32237432"></a>
### 10230-9f67ca0/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31369
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e9a14347b2da:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 1 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 50 seconds
(8/15) Running minio-dotnet tests ... done in 31 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 12 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-6zmm0vryblrcgcsf",
      "Object": "srcObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-6zmm0vryblrcgcsf",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 579,
  "error": "This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.",
  "function": "CopyObject(destination, source)",
  "message": "CopyObject failed",
  "name": "minio-go: testEncryptedSSES3ToSSES3CopyObject",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 25 seconds
(10/15) Running minio-js tests ... done in 48 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 36 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 11 seconds
(13/15) Running s3select tests ... FAILED in 1 seconds
Traceback (most recent call last):
  File "./tests.py", line 23, in <module>
    from sql_ops import *
  File "/mint/run/core/s3select/sql_ops.py", line 22, in <module>
    from minio.select.options import (SelectObjectOptions, CSVInput, JSONInput,
ImportError: cannot import name 'JsonOutput'
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="95a38128-04fc-4dd7-a2cb-e6e92dbb4078"></a>
### 10230-9f67ca0/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32541
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 641a0712f673:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 1 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 0 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 24 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 43 seconds
(11/15) Running minio-js tests ... done in 1 minutes and 2 seconds
(12/15) Running minio-py tests ... FAILED in 3 minutes and 37 seconds
{
  "name": "minio-py:test_presigned_get_object_version",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-68dde478-2d54-49fb-aa43-0d26afda258c",
    "object_name": "1579dcf4-c18c-4f24-9a9f-b5c27206251d"
  },
  "message": "InvalidArgument: message: Invalid Argument",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 147, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1508, in test_presigned_get_object_version\n    object_name).get_exception()\nminio.error.InvalidArgument: InvalidArgument: message: Invalid Argument\n",
  "duration": 424
}
(12/15) Running s3cmd tests ... FAILED in 20 seconds
{
  "name": "s3cmd",
  "duration": "9234",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(12/15) Running s3select tests ... FAILED in 0 seconds
{
  "name": "s3cmd",
  "duration": "9234",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="145bb3d7-614c-4cd2-96f6-87bf85b6ca13"></a>
### 10230-9f67ca0/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31961
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8ff3bf6feb76:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 44 seconds
(8/15) Running minio-dotnet tests ... done in 34 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 0 seconds
(10/15) Running minio-java tests ... done in 53 seconds
(11/15) Running minio-js tests ... done in 55 seconds
(12/15) Running minio-py tests ... FAILED in 2 minutes and 18 seconds
{
  "name": "minio-py:test_presigned_get_object_version",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-8ac0743f-0d5b-4ece-b281-cf56c0708b00",
    "object_name": "962e3330-c9d7-4537-adc1-4b18235dc58f"
  },
  "message": "InvalidArgument: message: Invalid Argument",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 147, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1508, in test_presigned_get_object_version\n    object_name).get_exception()\nminio.error.InvalidArgument: InvalidArgument: message: Invalid Argument\n",
  "duration": 109
}
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... FAILED in 0 seconds
Traceback (most recent call last):
  File "./tests.py", line 23, in <module>
    from sql_ops import *
  File "/mint/run/core/s3select/sql_ops.py", line 22, in <module>
    from minio.select.options import (SelectObjectOptions, CSVInput, JSONInput,
ImportError: cannot import name 'JsonOutput'
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="0eb6b4dd-e445-422e-8c53-42093749fe0e"></a>
### 10230-9f67ca0/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30173
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 71cf26c3a224:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 0 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 50 seconds
(8/15) Running minio-dotnet tests ... done in 31 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 13 seconds
(10/15) Running minio-java tests ... done in 21 seconds
(11/15) Running minio-js tests ... done in 51 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 18 seconds
(13/15) Running s3cmd tests ... done in 21 seconds
(14/15) Running s3select tests ... FAILED in 1 seconds
Traceback (most recent call last):
  File "./tests.py", line 23, in <module>
    from sql_ops import *
  File "/mint/run/core/s3select/sql_ops.py", line 22, in <module>
    from minio.select.options import (SelectObjectOptions, CSVInput, JSONInput,
ImportError: cannot import name 'JsonOutput'
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1ae275b9-5633-4a8f-992a-10dc844cb187"></a>
### 10230-9f67ca0/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32754
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 033f86e53de1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 9 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 48 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 7 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 32 seconds
(9/15) Running minio-go tests ... FAILED in 4 minutes and 55 seconds
{
  "args": {},
  "duration": 943,
  "error": "The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.",
  "function": "CopyObjectPart(destination, source)",
  "message": "CompleteMultipartUpload call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 7 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 37 seconds
(11/15) Running minio-py tests ... FAILED in 2 seconds
{
  "name": "minio-py:test_negative_make_bucket_invalid_name",
  "status": "FAIL",
  "args": {
    "location": "default value ('us-east-1')",
    "bucket_name": ".minio-py-test-3957da59-084a-4315-9fae-793a1bcc57bb"
  },
  "message": "NoSuchBucket: message: The specified bucket does not exist.",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 147, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 241, in test_negative_make_bucket_invalid_name\n    _call(log_entry, _CLIENT.make_bucket, bucket_name)\n  File \"/mint/run/core/minio-py/tests.py\", line 130, in _call\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 336, in make_bucket\n    raise ResponseError(response, method, bucket_name).get_exception()\nminio.error.NoSuchBucket: NoSuchBucket: message: The specified bucket does not exist.\n",
  "function": "make_bucket(bucket_name, location, object_lock)",
  "duration": 403
}
(11/15) Running s3cmd tests ... done in 1 minutes and 23 seconds
(12/15) Running s3select tests ... FAILED in 0 seconds
Traceback (most recent call last):
  File "./tests.py", line 23, in <module>
    from sql_ops import *
  File "/mint/run/core/s3select/sql_ops.py", line 22, in <module>
    from minio.select.options import (SelectObjectOptions, CSVInput, JSONInput,
ImportError: cannot import name 'JsonOutput'
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
