### PR TITLE
add ObjectOptions to ObjectLayer calls

### PR DESCRIPTION
**Pull request by poornas**
This will facilitate passing SSE options to gateway layer

## Description

Add ObjectOptions as argument to Put/Get/Head calls in the ObjectLayer interface. This will help facilitate passing sse headers to gateway client.
** after https://github.com/minio/minio-go/pull/1020 is merged, this PR needs to vendorize minio-go.
## Motivation and Context

It will help implement encryption at gateway and passing sse options to backend 
 https://github.com/minio/minio/issues/6323
## Regression
 No

## How Has This Been Tested?

Manually with Mint
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by poornas** [comment]
@harshavardhana & @krisis , PTAL. Rebased and vendored in minio-go

**Comment by krisis** [comment]
I think you have accidentally checked in ` vendor/github.com/minio/minio-go/validator` binary.

**Review by krisis — DISMISSED** [review]

**Comment by poornas** [comment]
@krisis, fixed this.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#08cb8d9b-f384-44ca-ad4e-a34b2365dd7a) |
| mint-gateway-nas.sh | :x: [more...](#7881988a-30d1-4b2c-9efa-0e6b50302d12) |
<a name="08cb8d9b-f384-44ca-ad4e-a34b2365dd7a"></a>
### 6382-9e33eed/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31602
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aed90820274f:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 57 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 4 seconds
(4/13) Running aws-sdk-php tests ... done in 42 seconds
(5/13) Running aws-sdk-ruby tests ... done in 3 seconds
(6/13) Running mc tests ... done in 18 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 13 seconds
(8/13) Running minio-go tests ... done in 18 seconds
(9/13) Running minio-java tests ... done in 1 minutes and 0 seconds
(10/13) Running minio-js tests ... done in 37 seconds
(11/13) Running minio-py tests ... FAILED in 30 minutes and 6 seconds
{
  "message": "HTTPConnectionPool(host='minikube', port=31602): Max retries exceeded with url: /minio-py-test-834fbec7-7b52-441a-b334-f7f6a93204c1/ (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "name": "minio-py:test_make_bucket_default_region",
  "args": {
    "bucket_name": "minio-py-test-834fbec7-7b52-441a-b334-f7f6a93204c1",
    "location": "default value ('us-east-1')"
  },
  "function": "make_bucket(bucket_name, location)",
  "status": "FAIL",
  "duration": 1806018,
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 600, in urlopen\n    chunked=chunked)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 384, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 2, in raise_from\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 380, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.5/http/client.py\", line 1197, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.5/http/client.py\", line 297, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.5/http/client.py\", line 266, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 165, in test_make_bucket_default_region\n    client.make_bucket(bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 286, in make_bucket\n    headers=headers)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py\", line 322, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 638, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py\", line 398, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minikube', port=31602): Max retries exceeded with url: /minio-py-test-834fbec7-7b52-441a-b334-f7f6a93204c1/ (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1707, in main\n    test_make_bucket_default_region(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 173, in test_make_bucket_default_region\n    raise Exception(err)\nException: HTTPConnectionPool(host='minikube', port=31602): Max retries exceeded with url: /minio-py-test-834fbec7-7b52-441a-b334-f7f6a93204c1/ (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n"
}

Executed 10 out of 13 tests successfully.
```
<a name="7881988a-30d1-4b2c-9efa-0e6b50302d12"></a>
### 6382-9e33eed/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32447
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 45aa0e5d0999:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 56 seconds
(2/13) Running aws-sdk-go tests ... done in 1 seconds
(3/13) Running aws-sdk-java tests ... done in 3 seconds
(4/13) Running aws-sdk-php tests ... done in 41 seconds
(5/13) Running aws-sdk-ruby tests ... done in 2 seconds
(6/13) Running mc tests ... FAILED in 5 seconds
{
  "name": "mc",
  "duration": "2750",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-folder /tmp/.mc-9926 --quiet --no-color cp myminio/mc-test-bucket-31484/mc-test-object-14483 mc-test-object-14483.downloaded  >>> \n`myminio/mc-test-bucket-31484/mc-test-object-14483` -> `mc-test-object-14483.downloaded`\nmc: <ERROR> Failed to copy `http://minikube:32447/mc-test-bucket-31484/mc-test-object-14483`. read tcp 172.17.0.28:59920->192.168.122.201:32447: read: connection reset by peer\nmc: <ERROR> Session safely terminated. To resume session `mc session resume ehJAVAaH`"
}

Executed 5 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#30fc20d7-f678-4fe5-ac83-fce0f2185901) |
<a name="30fc20d7-f678-4fe5-ac83-fce0f2185901"></a>
### 6382-2cffd18/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31948
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5aa264d01f08:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 59 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 3 seconds
(4/13) Running aws-sdk-php tests ... done in 42 seconds
(5/13) Running aws-sdk-ruby tests ... done in 2 seconds
(6/13) Running mc tests ... done in 21 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 27 seconds
(8/13) Running minio-go tests ... done in 20 seconds
(9/13) Running minio-java tests ... done in 1 minutes and 16 seconds
(10/13) Running minio-js tests ... done in 36 seconds
(11/13) Running minio-py tests ... FAILED in 30 minutes and 6 seconds
{
  "message": "HTTPConnectionPool(host='minikube', port=31948): Max retries exceeded with url: /minio-py-test-9a24f4ab-014f-40d3-835f-c1203ec0fab0/ (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "status": "FAIL",
  "name": "minio-py:test_make_bucket_default_region",
  "args": {
    "bucket_name": "minio-py-test-9a24f4ab-014f-40d3-835f-c1203ec0fab0",
    "location": "default value ('us-east-1')"
  },
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 600, in urlopen\n    chunked=chunked)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 384, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 2, in raise_from\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 380, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.5/http/client.py\", line 1197, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.5/http/client.py\", line 297, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.5/http/client.py\", line 266, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 165, in test_make_bucket_default_region\n    client.make_bucket(bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 286, in make_bucket\n    headers=headers)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py\", line 322, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 638, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py\", line 398, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minikube', port=31948): Max retries exceeded with url: /minio-py-test-9a24f4ab-014f-40d3-835f-c1203ec0fab0/ (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1707, in main\n    test_make_bucket_default_region(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 173, in test_make_bucket_default_region\n    raise Exception(err)\nException: HTTPConnectionPool(host='minikube', port=31948): Max retries exceeded with url: /minio-py-test-9a24f4ab-014f-40d3-835f-c1203ec0fab0/ (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "function": "make_bucket(bucket_name, location)",
  "duration": 1806032
}

Executed 10 out of 13 tests successfully.
```

**Comment by krisis** [comment]
@poornas the PR looks good to me, I am waiting for CI failures to be resolved before approving the PR.

**Comment by poornas** [comment]
@krisis , build passes now.

**Review by krisis — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#34e48cfa-fdd4-4df5-a99b-1fc5ff893d4f) |
| mint-xl.sh | :x: [more...](#86b74769-08f1-4308-b3a2-ae94b5205166) |
| mint-gateway-nas.sh | :x: [more...](#99cfc112-811d-40da-ac15-6390c188be43) |
<a name="34e48cfa-fdd4-4df5-a99b-1fc5ff893d4f"></a>
### 6382-71a67ec/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30678
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c279ad5a3b57:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 2 minutes and 49 seconds
(2/13) Running aws-sdk-go tests ... done in 2 seconds
(3/13) Running aws-sdk-java tests ... done in 3 seconds
(4/13) Running aws-sdk-php tests ... done in 1 minutes and 11 seconds
(5/13) Running aws-sdk-ruby tests ... done in 37 seconds
(6/13) Running mc tests ... done in 7 minutes and 17 seconds
(7/13) Running minio-dotnet tests ... FAILED in 5 minutes and 6 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.AreEqual failed. Expected:<0x8D614FE43362480-1>. Actual:<0x8D614FE42B5927F-1>. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.AreEqual failed. Expected:<0x8D614FE43362480-1>. Actual:<0x8D614FE42B5927F-1>. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[T](T expected, T actual, String message, Object[] parameters)
   at Minio.Functional.Tests.FunctionalTest.CopyObject_Test3(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 960
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 223

Executed 6 out of 13 tests successfully.
```
<a name="99cfc112-811d-40da-ac15-6390c188be43"></a>
### 6382-71a67ec/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32517
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8c49fd35fe26:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 57 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 2 seconds
(4/13) Running aws-sdk-php tests ... done in 41 seconds
(5/13) Running aws-sdk-ruby tests ... done in 3 seconds
(6/13) Running mc tests ... done in 19 seconds
(7/13) Running minio-dotnet tests ... done in 54 seconds
(8/13) Running minio-go tests ... done in 23 seconds
(9/13) Running minio-java tests ... done in 1 minutes and 10 seconds
(10/13) Running minio-js tests ... done in 27 seconds
(11/13) Running minio-py tests ... FAILED in 1 hours 1 minutes and 21 seconds
{
  "status": "FAIL",
  "name": "minio-py:test_thread_safe",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 600, in urlopen\n    chunked=chunked)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 384, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 2, in raise_from\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 380, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.5/http/client.py\", line 1197, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.5/http/client.py\", line 297, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.5/http/client.py\", line 266, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1427, in test_thread_safe\n    client.remove_object(bucket_name, object_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 942, in remove_object\n    object_name=object_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1752, in _url_open\n    preload_content=preload_content)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py\", line 322, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 638, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py\", line 398, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minikube', port=32517): Max retries exceeded with url: /minio-py-test-c25cad74-b990-4a58-9789-43f8b909a2fe/b723f0b8-a6d8-4eea-bc1d-83406aa80e00 (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1800, in main\n    test_thread_safe(client, testfile, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1430, in test_thread_safe\n    raise Exception(err)\nException: HTTPConnectionPool(host='minikube', port=32517): Max retries exceeded with url: /minio-py-test-c25cad74-b990-4a58-9789-43f8b909a2fe/b723f0b8-a6d8-4eea-bc1d-83406aa80e00 (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "function": "put_object(bucket_name, object_name, data, length, content_type, metadata)",
  "message": "HTTPConnectionPool(host='minikube', port=32517): Max retries exceeded with url: /minio-py-test-c25cad74-b990-4a58-9789-43f8b909a2fe/b723f0b8-a6d8-4eea-bc1d-83406aa80e00 (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "duration": 3612251,
  "args": {
    "bucket_name": "minio-py-test-c25cad74-b990-4a58-9789-43f8b909a2fe",
    "object_name": "b723f0b8-a6d8-4eea-bc1d-83406aa80e00"
  }
}

Executed 10 out of 13 tests successfully.
```
<a name="86b74769-08f1-4308-b3a2-ae94b5205166"></a>
### 6382-71a67ec/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30421
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 809a1069f397:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 55 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 2 seconds
(4/13) Running aws-sdk-php tests ... done in 41 seconds
(5/13) Running aws-sdk-ruby tests ... done in 2 seconds
(6/13) Running mc tests ... done in 18 seconds
(7/13) Running minio-dotnet tests ... done in 52 seconds
(8/13) Running minio-go tests ... done in 28 seconds
(9/13) Running minio-java tests ... done in 1 minutes and 18 seconds
(10/13) Running minio-js tests ... done in 33 seconds
(11/13) Running minio-py tests ... FAILED in 1 hours 1 minutes and 18 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 600, in urlopen\n    chunked=chunked)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 384, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 2, in raise_from\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 380, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.5/http/client.py\", line 1197, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.5/http/client.py\", line 297, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.5/http/client.py\", line 266, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1427, in test_thread_safe\n    client.remove_object(bucket_name, object_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 942, in remove_object\n    object_name=object_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1752, in _url_open\n    preload_content=preload_content)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py\", line 322, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 638, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py\", line 398, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minikube', port=30421): Max retries exceeded with url: /minio-py-test-7af9f4ce-571a-4b56-838f-7439646590c9/7954b79b-036a-4050-a930-6e0ea80c272d (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1800, in main\n    test_thread_safe(client, testfile, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1430, in test_thread_safe\n    raise Exception(err)\nException: HTTPConnectionPool(host='minikube', port=30421): Max retries exceeded with url: /minio-py-test-7af9f4ce-571a-4b56-838f-7439646590c9/7954b79b-036a-4050-a930-6e0ea80c272d (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "message": "HTTPConnectionPool(host='minikube', port=30421): Max retries exceeded with url: /minio-py-test-7af9f4ce-571a-4b56-838f-7439646590c9/7954b79b-036a-4050-a930-6e0ea80c272d (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "duration": 3612233,
  "function": "put_object(bucket_name, object_name, data, length, content_type, metadata)",
  "args": {
    "bucket_name": "minio-py-test-7af9f4ce-571a-4b56-838f-7439646590c9",
    "object_name": "7954b79b-036a-4050-a930-6e0ea80c272d"
  }
}

Executed 10 out of 13 tests successfully.
```

**Comment by poornas** [comment]
@harshavardhana, this PR is waiting for your approval

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
