### PR TITLE
SSL support for Kafka

### LINKED ISSUE #8211: Kafka TLS Connection with custom CAs not working
Connecting a Kafka Bucket Notification service by a self-signed certificate SSL encryption to a Kafka broker fails because we are not able to provide the custom CAs to the Shopify/sarama library, which is used for connection by the Kafka Bucket Notification service. 

## Expected Behavior
1. Starting Minio with "--cert-dir" argument to provide the custom CA which has signed all certificates used for the ssl connection
2. By `mc admin config set` we update the config to configure kafka endpoints and events
2. Kafka Bucket Notification connects to Kafka 

## Current Behavior
Connection to kafka fails.
Error on Minio side: 
`mc: <ERROR> Cannot set server configuration file. kafka(provenance): kafka: client has run out of available brokers to talk to (Is your cluster reachable?).`
Error on Kafka side:
`INFO [SocketServer brokerId=0] Failed authentication with 10.128.3.108/10.128.3.108 (SSL handshake failed) (org.apache.kafka.common.network.Selector)`

## Possible Solution
The connection to kafka works properly but the the clients needs to verify the certificates.
The [global variable](https://github.com/minio/minio/blob/8a71b0ec5a722ce0ce67ee0ad84eb87d2feedc1a/cmd/globals.go#L162) of minio which stores the custom CAs pool  is not provided when [creating](https://github.com/minio/minio/blob/16a45e5aff422caed577067b3eb3a16462debc74/pkg/event/target/kafka.go#L201) the config of sarama.
I think the problem could be solved in the same way like this commit [3d22a9d](https://github.com/minio/minio/commit/3d22a9d84fc85f402599e6205b8336e1b86e5b84).

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
Point the rootCAs to kafka TLS config.

## Motivation and Context
Fixes #8211

## How to test this PR?
steps provided in the issue 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#90a059e0-b27d-45f6-9803-88d76f0a9294) |
| mint-large-bucket.sh | :x: [more...](#689c0836-eba6-431b-a108-df3f48b6c1a5) |
<a name="689c0836-eba6-431b-a108-df3f48b6c1a5"></a>
### 8236-6d08e5b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32433
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fe1cdd43256a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 56 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 35 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 43 seconds
{
  "args": {},
  "duration": 59755,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="90a059e0-b27d-45f6-9803-88d76f0a9294"></a>
### 8236-6d08e5b/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32577
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 784ddb3ad668:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dn2w4xoyjluqgv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365603,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C3EDCA11C0540F, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by aead — APPROVED** [review]

**Comment by Praveenrajmani** [comment]
Looks like a sporadic error in travis 
```
FAIL: TestXLCleanupStaleMultipartUploads (1.21s)
xl-v1-multipart_test.go:63: Unexpected err:  Object not found: bucket#object
```

**Comment by Praveenrajmani** [comment]
PTAL @vadmeste

**Comment by vadmeste** [comment]
@Praveenrajmani, LGTM, but can you just fix the commit message: Add rootCAs support to kafka & mqtt

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d6e2f6de-b3a6-458a-bce8-ef037ac65340) |
| mint-compression-dist-xl.sh | :x: [more...](#7de4d7b8-54c3-4122-8d9e-440c5f18bd15) |
<a name="7de4d7b8-54c3-4122-8d9e-440c5f18bd15"></a>
### 8236-8003e23/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31585
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9565f73e385d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 3 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 52 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 6 seconds
(11/14) Running minio-js tests ... done in 50 seconds
(12/14) Running minio-py tests ... done in 2 minutes and 17 seconds
(13/14) Running s3cmd tests ... FAILED in 10 seconds
{
  "name": "s3cmd",
  "duration": "4628",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  following lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nInvoked as: /usr/local/bin/s3cmd --config /tmp/.s3cmd-15338/s3cfg get s3://s3cmd-test-bucket-18743/s3cmd-test-object-20146 s3cmd-test-object-20146.downloaded\nProblem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer\nS3cmd:   2.0.2\npython:   3.5.2 (default, Nov 12 2018, 13:43:14) \n[GCC 5.4.0 20160609]\nenvironment LANG=C.UTF-8\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 3092, in <module>\n    rc = main()\n  File \"/usr/local/bin/s3cmd\", line 3001, in main\n    rc = cmd_func(args)\n  File \"/usr/local/bin/s3cmd\", line 590, in cmd_object_get\n    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 716, in object_get\n    response = self.recv_file(request, stream, labels, start_position)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 1742, in recv_file\n    data = http_response.read(this_chunk)\n  File \"/usr/lib/python3.5/http/client.py\", line 448, in read\n    n = self.readinto(b)\n  File \"/usr/lib/python3.5/http/client.py\", line 488, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  above lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
}

Executed 12 out of 14 tests successfully.
```
<a name="d6e2f6de-b3a6-458a-bce8-ef037ac65340"></a>
### 8236-8003e23/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30185
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 978b0cfe38e2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 7 minutes and 41 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 54 seconds
(8/14) Running minio-dotnet tests ... done in 2 minutes and 59 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 7 seconds
{
  "args": {},
  "duration": 65021,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

**Comment by Praveenrajmani** [comment]
@vadmeste done :+1:

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
