### PR TITLE
Always pull the latest mint image when running tests

### PR DESCRIPTION
**Pull request by marktheunissen**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

I'm not sure how this refreshed previously, but without this, it's unclear which mint image is being used and whether it is the latest, since there is no SHA of the image in the test log output.

If the image is already available then this call completes quickly. 

## Motivation and Context

Ensure tests are always correct

## How to test this PR?

Let's see it run in GH

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by marktheunissen** [comment]
@harshavardhana All I'm doing in this PR is pulling latest mint image, now there is failing test:

```
{
  "time": "2024-12-04T21:15:58.543068059Z",
  "level": "ERROR",
  "name": "minio-go: testGetObjectAttributes",
  "duration": 489,
  "function": "GetObjectAttributes(ctx, bucketName, objectName, opts)",
  "args": {
    "bucketName": "minio-go-test-versioned-aoevl5",
    "objectName": "file1",
    "opts": "minio.ObjectAttributesOptions{}"
  },
  "status": "FAIL",
  "message": "Validating GetObjectsAttributes response failed, table test: versioned",
  "error": "Full object checksum not found"
}
```

I'll try take a look at fixing it this morning

**Comment by harshavardhana** [comment]
Yeah some PRs are not merged upstream such as GetObjectAttributes API.

This is not the the actual fix, the cloning must happen properly under miniohq/eos on its own repo. 

We need to figure that out.

**Comment by marktheunissen** [comment]
GetObjectAttributes exists here in upstream: https://github.com/minio/minio/blob/master/cmd/object-handlers.go#L985

This mint test works locally when running without compression. When running with compression, it fails. It is easy to reproduce the test failure locally, by applying the above settings to a SNSD MinIO.

```
      MINIO_COMPRESSION_ENABLE: "on"
      MINIO_COMPRESSION_MIME_TYPES: "*"
```

I've tried to figure out what the intention is here - here is a change made to this test case: https://github.com/marktheunissen/minio-go/commit/aa6b5dbd79a9f7086e6e3e568fd3148dc0c66b8a#diff-fcd2423fdb45eef4722b602ad655574b9c416102d0353494b43c2464c9a9f8e3R3265

The mint test is basically something like "upload an object with a ChecksumCRC32C, to a compressed MinIO instance, to a versioned bucket, and then GetObjectAttributes to ensure the CRC32 is returned".

But in PutObject there are some lines that indicate checksums are removed when compressible here: https://github.com/minio/minio/blob/master/cmd/object-handlers.go#L1926-L1927 although those are not CRC32 but I'm not sure how that works exactly.

So what do we want to do when providing CRC32 to a compressed backend? 

Ping @klauspost

**Comment by marktheunissen** [comment]
@klauspost has fixed this here: https://github.com/minio/minio/pull/20743

**Pull request closed without merging**
