### PR TITLE
[proposal] Support creating directories on erasure coded backend

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Support creating directories on erasure coded backend

## Motivation and Context
This PR continues from #5049 where we started supporting
directories for filesystem backend.

## How Has This Been Tested?
Manually using `awscli` tests on mint for the same feature on FS backend.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
To test please use the commit before a recent merge to remove the awscli test to test directory creates. https://github.com/minio/mint/commits/master 

```
docker run --net=host -e SERVER_ENDPOINT=127.0.0.1:9000 -e ACCESS_KEY=minio -e SECRET_KEY=minio123 -e ENABLE_HTTPS=0 -e MINT_MODE=full minio/mint:edge awscli
Running with
SERVER_ENDPOINT: 127.0.0.1:9000
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       full

To get logs, run 'sudo docker cp ecaa38ce02e7:/mint/log /tmp/mint-logs'
(1/1) Running awscli tests ... done in 40 seconds

All tests ran successfully
```

**Comment by harshavardhana** [comment]
this is blocked on @abperiasamy // cc @nitisht

**Comment by harshavardhana** [comment]
Closing PR and re-opening again.

**Comment by balamurugana** [comment]
```
mint-xl.sh: PASSED
---
mint-fs.sh: PASSED
---
mint-dist-xl.sh: PASSED
---

```

**Pull request closed without merging**
