### PR TITLE
fix:sort will rand by map

### PR DESCRIPTION
**Pull request by jiuker**
## Description

sort will rand by map
```go
package main

import (
	"fmt"
	"sort"
)

type A struct {
	A string
	T string
}

func main() {
	MA := map[string]A{
		"1231": {
			A: "1231",
			T: "inter",
		},
		"1232": {
			A: "1232",
			T: "inter",
		},
		"1233": {
			A: "1233",
			T: "inter",
		},
		"1234": {
			A: "1234",
			T: "inter",
		},
		"1235": {
			A: "1235",
			T: "",
		},
		"1236": {
			A: "1236",
			T: "",
		},
		"1237": {
			A: "1237",
			T: "",
		},
		"1238": {
			A: "1238",
			T: "",
		},
		"1239": {
			A: "1239",
			T: "",
		},
	}
	sa := []A{}
	for _, v := range MA {
		sa = append(sa, v)
	}
	sort.Slice(sa, func(i, j int) bool {
		//if sa[i].T == "inter" && sa[j].T == "inter" {
		//	return sa[i].A < sa[j].A
		//}
		if sa[i].T == "inter" {
			return true
		}
		if sa[j].T == "inter" {
			return false
		}
		return sa[i].A < sa[j].A
	})
	fmt.Println(sa)
}
```
first output:
```shell
[{1234 inter} {1232 inter} {1233 inter} {1231 inter} {1235 } {1236 } {1237 } {1238 } {1239 }]
```
second output:
```shell
[{1234 inter} {1232 inter} {1231 inter} {1233 inter} {1235 } {1236 } {1237 } {1238 } {1239 }]
```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — COMMENTED** [review]
It is kind of a no-change, since there will only be one "internal", since TierType cannot be "internal".

**Comment by jiuker** [comment]
> It is kind of a no-change, since there will only be one "internal", since TierType cannot be "internal".
@klauspost This is true by context, but it's more rigorous, isn't it?

**Comment by jiuker** [comment]
@klauspost This is true by context, but it's more rigorous, isn't it?

**Comment by klauspost** [comment]
Changing something always has a risk of regressions, no matter how perfect we are. So unless it fixes a problem or a race, there isn't much gained by taking that risk. 

I'm not saying that we shouldn't add this change, but the gains should be clear. In this case it is removing a possible error on future changes.

**Comment by harshavardhana** [comment]
I think we should avoid this change, it's not fixing anything.

**Pull request closed without merging**
