### PR TITLE
fix InvalidAccessKeyId error according to amazon documentation

### PR DESCRIPTION
**Pull request by samkevich**
http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

## Description

fix InvalidAccessKeyId error according to amazon documentation http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

## Motivation and Context

Error code in case of invalid access key in amazon documentation (http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) and code are different (InvalidAccessKeyId in docs and InvalidAccessKeyID in code)

## How Has This Been Tested?

It didn't tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by samkevich** [comment]
https://github.com/minio/minio-go/pull/692

**Review by deekoder — CHANGES_REQUESTED** [review]
There are other places in the code where InvalidAccessKeyID is used. You are right that AWS seems to use the code : InvalidAccessKeyId instead of InvalidAccessKeyID. A pr that can comprehensively look at all error codes and see if they are identical will be great. @samkevich  please see s3-errors.go file. I think this string is available there as well.

**Comment by harshavardhana** [comment]
> There are other places in the code where InvalidAccessKeyID is used. You are right that AWS seems to use the code : InvalidAccessKeyId instead of InvalidAccessKeyID. A pr that can comprehensively look at all error codes and see if they are identical will be great. @samkevich please see s3-errors.go file. I think this string is available there as well.

ErrInvalidAccessKeyID is internal representation and is valid according to idomatic Go convention an `Id` should be `ID` instead.  This PR only changes the XML response Code which is sent back to the client it doesn't need to change say `ErrInvalidAccessKeyID` into `ErrInvalidAccessKeyId`.

Also all other error codes are listed in a map `api-errors.go`, most of them are directly picked from http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html and all the extended versions are named as XMinio for brevity. 

```
// error code to APIError structure, these fields carry respective
// descriptions for all the error responses.
var errorCodeResponse = map[APIErrorCode]APIError{
``` 

This PR is good to merge IMO.

**Review by harshavardhana — APPROVED** [review]

**Review by balamurugana — APPROVED** [review]

**Comment by deekoder** [comment]
I get that its go idiomatic. My point is below. How about changing it everywhere as seen below : cmd/bucket-handlers_test.go & in minio-go library s3-error.go

```
grep -r 'InvalidAccessKeyID' *
cmd/api-errors.go:	ErrInvalidAccessKeyID
cmd/api-errors.go:	ErrInvalidAccessKeyID: {
cmd/api-errors.go:		Code:           "InvalidAccessKeyID",
cmd/auth-rpc-server_test.go:			expectedErr: errInvalidAccessKeyID,
cmd/browser-peer-rpc_test.go:		if err.Error() != errInvalidAccessKeyID.Error() {
cmd/bucket-handlers_test.go:				Code:     "InvalidAccessKeyID",
cmd/jwt.go:	errInvalidAccessKeyID   = errors.New("The access key ID you provided does not exist in our records")
cmd/jwt.go:		return "", errInvalidAccessKeyID
cmd/jwt_test.go:		{"myuser", "mypassword", errInvalidAccessKeyID},
cmd/object-handlers_test.go:			expectedContent:    encodeResponse(getAPIErrorResponse(getAPIError(ErrInvalidAccessKeyID), getGetObjectURL("", bucketName, objectName))),
cmd/object-handlers_test.go:			expectedContent: encodeResponse(getAPIErrorResponse(getAPIError(ErrInvalidAccessKeyID),
cmd/object-handlers_test.go:	invalidAccessID := getAPIError(ErrInvalidAccessKeyID)
cmd/prepare-storage.go:	case errMap[errInvalidAccessKeyID] > 0:
cmd/prepare-storage_test.go:		errInvalidAccessKeyID, nil, nil, nil,
cmd/signature-v2.go:		return ErrInvalidAccessKeyID
cmd/signature-v2.go:		return ErrInvalidAccessKeyID
cmd/signature-v2.go:		return ErrInvalidAccessKeyID
cmd/signature-v2_test.go:			expected: ErrInvalidAccessKeyID,
cmd/signature-v2_test.go:			expectedError: ErrInvalidAccessKeyID,
cmd/signature-v2_test.go:		{"invalidAccessKey", policy, calculateSignatureV2(policy, creds.SecretKey), ErrInvalidAccessKeyID},
cmd/signature-v4-parser.go:		return credentialHeader{}, ErrInvalidAccessKeyID
cmd/signature-v4-parser_test.go:			expectedErrCode:     ErrInvalidAccessKeyID,
cmd/signature-v4.go:		return ErrInvalidAccessKeyID
cmd/signature-v4.go:		return ErrInvalidAccessKeyID
cmd/signature-v4.go:		return ErrInvalidAccessKeyID
cmd/signature-v4_test.go:			expected: ErrInvalidAccessKeyID,
cmd/signature-v4_test.go:			expected: ErrInvalidAccessKeyID,
cmd/storage-rpc-client.go:	case errInvalidAccessKeyID.Error():
cmd/storage-rpc-client.go:		return errInvalidAccessKeyID
cmd/storage-rpc-client_test.go:			expectedErr: errInvalidAccessKeyID,
cmd/storage-rpc-client_test.go:			err:         fmt.Errorf("%s", errInvalidAccessKeyID.Error()),
cmd/streaming-signature-v4.go:		return "", time.Time{}, ErrInvalidAccessKeyID
cmd/web-handlers.go:	} else if err == errInvalidAccessKeyID {
Binary file minio matches
vendor/github.com/minio/minio-go/s3-error.go:	"InvalidAccessKeyID":                "The access key ID you provided does not exist in our records.",
```

**Review by deekoder — APPROVED** [review]

**Comment by krishnasrinivas** [comment]
yes, we can fix in cmd/bucket-handlers_test.go minio-go library s3-error.go @deekoder

**Comment by harshavardhana** [comment]
> yes, we can fix in cmd/bucket-handlers_test.go minio-go library s3-error.go @deekoder

minio-go is fixed as well and @samkevich fixed bucket-handlers_test.go as well in this PR.

**Pull request merged**
