### PR TITLE
friendly message for s3select MalformedXML error

### LINKED ISSUE #7911: XML Error on S3 Select
I want to run S3 in local to try my lambda in local env. All seem to be ok for S3 calls (getObject, putObject etc.) but, I have an error using selectObjectContent.

My S3 Client override
```
this.buildS3Client = (endpoint) => {
    if (endpoint) {
        return new this.aws.S3({
            signatureVersion: 's3',
            s3ForcePathStyle: true,
            endpoint: endpoint,
            apiVersion: "2006-03-01"
        });
    }
            
    return new this.aws.S3({ apiVersion: "2006-03-01" });
};
```

My S3 Select Param
```
const params = {
    Bucket: bucketName,
    Key: filePath,
    ExpressionType: 'SQL',
    Expression: "SELECT s.* FROM S3Object s WHERE s.line_number = '1'",
    InputSerialization: {
        CSV: {
            FileHeaderInfo: 'USE',
            FieldDelimiter: ';',
            QuoteCharacter: '"',
            AllowQuotedRecordDelimiter: true
        }
    },
    OutputSerialization: {
        JSON: {
            RecordDelimiter: '\n'
        }
    }
};
```
## Expected Behavior
Get my S3 Select Query result

## Current Behavior
I have this error

```
{
    "errorMessage": "The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.",
    "errorType": "Error",
}
```

The same query with AWS S3 (without overriding S3 Client) work fine.

I've compared the generated SelectObjectContentRequest, this is the same for AWS S3 and Minio

## Steps to Reproduce (for bugs)

1. Create a lambda and set S3 Endpoint to minio (like the example above)
2. Do a selectObjectContent Query (with param above)
```
let data = await this.s3.selectObjectContent(params).promise();
const events = data.Payload;
for await (const event of events) {
    if (event.Records) {
        return event.Records.Payload.toString();
    }
}
```

## Your Environment

* Docker image : minio/minio:RELEASE.2019-03-27T22-35-21Z
* Node lambda version : 10.x
* Operating System and version : Mac OS 10.14.5
* Serverless version : 1.45.1

Thanks for your help

### PR DESCRIPTION
**Pull request by yaozongyou**
partly fix #7911

## Description

more friendly prompt for s3select MalformedXML  error

## Motivation and Context

more friendly prompt for s3select MalformedXML  error

## How to test this PR?

before:

```xml
<Message>The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.</Message>
```

after 
```xml
<Message>The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again: flag AllowQuotedRecordDelimiter is unsupported at the moment</Message>
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#7e1d023d-b89a-48ce-9e6b-8e1406cf4a1f) |
| mint-xl.sh | :x: [more...](#09e8fba9-fa60-4f55-aaae-dcae645ebd30) |
| mint-large-bucket.sh | :x: [more...](#44a08260-2f6b-4f4d-a96c-870dfb5bd9e9) |
<a name="09e8fba9-fa60-4f55-aaae-dcae645ebd30"></a>
### 8171-7c98edf/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31826
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6332b703902e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 43 seconds
(8/14) Running minio-dotnet tests ... done in 28 seconds
(9/14) Running minio-go tests ... done in 47 seconds
(10/14) Running minio-java tests ... done in 29 seconds
(11/14) Running minio-js tests ... FAILED in 10 seconds
{
  "name": "minio-js",
  "function": "fGetObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-2e08c715-f99d-4bf6-8452-a4f812bc137d, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB.download",
  "duration": 433,
  "status": "FAIL",
  "error": "Error: Size mismatch between downloaded file and the object at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:965:12 at nextTask (node_modules/minio/node_modules/async/dist/async.js:4578:13) at next (node_modules/minio/node_modules/async/dist/async.js:4586:13) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:325:20 at FSReqWrap.oncomplete (fs.js:123:15)"
}

Executed 10 out of 14 tests successfully.
```
<a name="44a08260-2f6b-4f4d-a96c-870dfb5bd9e9"></a>
### 8171-7c98edf/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31589
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0b877f2570b5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 25 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 23 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 52 seconds
{
  "args": {},
  "duration": 94013,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="7e1d023d-b89a-48ce-9e6b-8e1406cf4a1f"></a>
### 8171-7c98edf/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31391
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dae6d5b966ba:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5r3yclcrwbl5u4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360015,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C0847449971DE2, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#42a3b11a-8e22-487f-9843-ecf63ff5d2cb) |
| mint-compression-fs.sh | :x: [more...](#1440329b-4f08-4b85-afcf-c009c2d47467) |
<a name="1440329b-4f08-4b85-afcf-c009c2d47467"></a>
### 8171-23e789e/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31205
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3ff620b1f031:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 40 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 24 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... FAILED in 7 minutes and 10 seconds
{
  "args": {
    "bucketName": "minio-go-test-40y6pnbbl9dqmfgx",
    "fileName": "/mint/data/datafile-129-MB",
    "location": "us-east-1",
    "objectName": "minio-go-test-40y6pnbbl9dqmfgxFPutObject-standard",
    "opts": {
      "UserMetadata": null,
      "Progress": null,
      "ContentType": "application/octet-stream",
      "ContentEncoding": "",
      "ContentDisposition": "",
      "ContentLanguage": "",
      "CacheControl": "",
      "ServerSideEncryption": null,
      "NumThreads": 0,
      "StorageClass": "",
      "WebsiteRedirectLocation": "",
      "PartSize": 0
    }
  },
  "duration": 407611,
  "error": "Put http://72.28.97.57:31205/minio-go-test-40y6pnbbl9dqmfgx/minio-go-test-40y6pnbbl9dqmfgxFPutObject-standard?partNumber=1&uploadId=4da6dd03-5eca-45c4-bb8b-6cf5442e3e3c: dial tcp 72.28.97.57:31205: connect: no route to host",
  "function": "FPutObject(bucketName, objectName, fileName, opts)",
  "message": "FPutObject failed",
  "name": "minio-go: testFPutObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="42a3b11a-8e22-487f-9843-ecf63ff5d2cb"></a>
### 8171-23e789e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30262
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e36d345b6ce1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... FAILED in 13 minutes and 42 seconds
{
  "name": "awscli",
  "duration": 754649,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "remove_bucket failed: s3://awscli-mint-test-bucket-30775 HTTPConnectionPool(host='72.28.97.52', port=30262): Read timed out. (read timeout=60)"
}

Executed 4 out of 14 tests successfully.
```
Error: No such image: minio/minio:8171-23e789e

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#ad852d69-39ec-4e9b-bfbe-6c4d8ef641ad) |
<a name="ad852d69-39ec-4e9b-bfbe-6c4d8ef641ad"></a>
### 8171-cab71a9/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32379
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 84227d39822e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-r2j1zf99acaiz2",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360014,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C1AFE816B23E39, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
Ping @balamurugana

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6eb1d287-8b3c-44e8-bfdd-c448c30a324a) |
| mint-compression-dist-xl.sh | :x: [more...](#d3106505-b7da-4ae2-9b76-433abf1dca50) |
<a name="6eb1d287-8b3c-44e8-bfdd-c448c30a324a"></a>
### 8171-50f7ab9/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32303
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4409518ffa31:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 5 minutes and 4 seconds
{
  "name": "aws-sdk-php",
  "function": "getObject ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5d727c5cbe133",
    "Object": "obj1"
  },
  "duration": "36",
  "status": "FAIL",
  "error": "Error executing \"PutObject\" on \"http://72.28.97.52:32303/aws-sdk-php-5d727c5cbe133/obj1\"; AWS HTTP error: Client error: `PUT http://72.28.97.52:32303/aws-sdk-php-5d727c5cbe133/obj1` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of byte (truncated...)\n IncompleteBody (client): You did not provide the number of bytes specified by the Content-Length HTTP header. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of bytes specified by the Content-Length HTTP header.</Message><Key>obj1</Key><BucketName>aws-sdk-php-5d727c5cbe133</BucketName><Resource>/aws-sdk-php-5d727c5cbe133/obj1</Resource><RequestId>15C1E38B594A47F0</RequestId><HostId>dcc834e2-b604-49b5-b3dd-b28dea0ae5a8</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="d3106505-b7da-4ae2-9b76-433abf1dca50"></a>
### 8171-50f7ab9/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31186
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp be42d306faad:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-1qtf4thtlysdr5",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360018,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C1E3978CAC3356, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by klauspost — APPROVED** [review]

**Review by balamurugana — APPROVED** [review]

**Pull request merged**
