### PR TITLE
[proposal] Preserve prefixes after object deletes

### LINKED ISSUE #5102: Keep empty directories after deleting all items from directory
To crete an empty directory, i used minio:edge image. Creating an empty directory works fine, but i found one problem. If I create an empty directory and next I upload a file there. Deleting a file will also remove the parent directory. I would like to keep empty parent directories.

## Expected Behavior
I would like to keep empty directories after deleting all items.

## Current Behavior
Delete all items from directory also remove parent directory.

## Steps to Reproduce (for bugs)

1. Create empty directory ( /testDirectory ) 
2. Upload file to directory /testDirectory/testFile.txt
3. Remove file testFile.txt from directory testDirectory.

## Your Environment

* Version used (`minio edge`):

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes https://github.com/minio/minio/issues/5102

## Description
Preserve prefixes after object deletes

## Motivation and Context
Completeness for b2cbade4776577a81df8cb9e8ba2a94b0a60961b empty directory support.

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
Problem with this is a lot empty directories will be left after object deletes. I think we can live with #5102 behaviour.

**Comment by harshavardhana** [comment]
> Problem with this is a lot empty directories will be left after object deletes. I think we can live with #5102 behaviour.

We can but we need to discuss this once and close the bug #5102 - this is waiting on inputs from  @abperiasamy ATM.

**Comment by vadmeste** [comment]
If we are going to support odd characters in prefixes, like many characters unsupported for Windows, then that would resolve this problem.

**Comment by harshavardhana** [comment]
Closing this PR for now, until we decide that we want to do this.

**Pull request closed without merging**
