### PR TITLE
simplify FS multipart cleanup

### LINKED ISSUE #9671: CompleteMultipartUpload: Reduce Time Between File Rename and Stat
When Minio is running as an object storage server there can be a significant time delay during the CompleteMultipartUpload operation between the file rename and file stat if the server is writing/deleting to a bucket on a NAS and the file uploaded consists of hundred or thousands of parts. This scenario presents a window of opportunity for the CompleteMultipartUpload to fail. For example, if the renamed file is moved out of the bucket by an external process before it can be stat'd by the CompleteMultipartUpload caller.

Here is the applicable [code](https://github.com/minio/minio/blob/master/cmd/fs-v1-multipart.go#L685):

```
        err = fsRenameFile(ctx, appendFilePath, pathJoin(fs.fsPath, bucket, object))
	if err != nil {
		logger.LogIf(ctx, err)
		return oi, toObjectErr(err, bucket, object)
	}
	fsRemoveAll(ctx, uploadIDDir)
	// It is safe to ignore any directory not empty error (in case there were multiple uploadIDs on the same object)
	fsRemoveDir(ctx, fs.getMultipartSHADir(bucket, object))
	fi, err := fsStatFile(ctx, pathJoin(fs.fsPath, bucket, object))
	if err != nil {
		return oi, toObjectErr(err, bucket, object)
	}
```

## Expected Behavior

I would expect the fsStatFile call to occur immediately after the fsRenameFile call to reduce the chance of an error being returned to the client that initiated the completion of the multipart upload.

## Current Behavior

If the renamed file is moved out of the bucket or to a different position in the bucket before the file stat is performed then a confusing response is returned to the client where an error message is found in the response body but the status code is set to 200. I am not sure, but this mapping of NoSuchKey with a 200 status code may also be a sign of a shadowed err variable.

Here is a sample response when using the AWS CLI as a client:

```
2020-05-21 17:09:50,830 - ThreadPoolExecutor-0_1 - botocore.hooks - DEBUG - Event request-created.s3.CompleteMultipartUpload: calling handler <function signal_transferring at 0x10f3bc040>
2020-05-21 17:09:50,831 - ThreadPoolExecutor-0_1 - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=http://127.0.0.1:9000/test/1G.bin?uploadId=3d57e713-d617-40f2-8d86-6b27bbe4e4a2, headers={'User-Agent': b'aws-cli/1.17.9 Python/3.8.1 Darwin/19.4.0 botocore/1.14.9', 'X-Amz-Date': b'20200521T210950Z', 'X-Amz-Content-SHA256': b'a400509105d17c93563b8301c1ba56b7e8559512180df18edfdf6a09adc77bda', 'Authorization': b'AWS4-HMAC-SHA256 Credential=minioadmin/20200521/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=26899cb9c885f0c3ddc313fdef017e74865f413d9dfd0812eb9b8d7fafb1ddbe', 'Content-Length': '17591'}>
2020-05-21 17:10:00,842 - ThreadPoolExecutor-0_1 - urllib3.connectionpool - DEBUG - http://127.0.0.1:9000 "POST /test/1G.bin?uploadId=3d57e713-d617-40f2-8d86-6b27bbe4e4a2 HTTP/1.1" 200 None
2020-05-21 17:10:51,135 - ThreadPoolExecutor-0_1 - botocore.parsers - DEBUG - Response headers: {'Content-Security-Policy': 'block-all-mixed-content', 'Content-Type': 'text/event-stream', 'Vary': 'Origin', 'X-Amz-Request-Id': '161127555182F0D8', 'X-Xss-Protection': '1; mode=block', 'Date': 'Thu, 21 May 2020 21:10:00 GMT', 'Transfer-Encoding': 'chunked'}
2020-05-21 17:10:51,136 - ThreadPoolExecutor-0_1 - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n      <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>1G.bin</Key><BucketName>test</BucketName><Resource>/test/1G.bin</Resource><RequestId>161127555182F0D8</RequestId><HostId>f42342a9-dc70-45f3-a3fe-1b3371a9ae62</HostId></Error>'
```

## Possible Solution

Move the fsStatFile() as closely as possible to the fsRenameFile(). For example, maybe this would be better.

```
        err = fsRenameFile(ctx, appendFilePath, pathJoin(fs.fsPath, bucket, object))
	if err != nil {
		logger.LogIf(ctx, err)
		return oi, toObjectErr(err, bucket, object)
	}
	fi, err := fsStatFile(ctx, pathJoin(fs.fsPath, bucket, object))
	if err != nil {
		return oi, toObjectErr(err, bucket, object)
	}
	fsRemoveAll(ctx, uploadIDDir)
	// It is safe to ignore any directory not empty error (in case there were multiple uploadIDs on the same object)
	fsRemoveDir(ctx, fs.getMultipartSHADir(bucket, object))
```

## Steps to Reproduce (for bugs)

1. Upload a large multipart file to Minio that will require the CompleteMultipartUpload() a minute or more to finish (i.e., due to part cleanup). Alternatively, modify source code to sleep between file rename and stat in the CompleteMultipartUpload() function.
2. Remove file from Minio bucket once it is renamed while CompleteMultipartUpload() is still in progress.
3. Observe the 200 status code that is returned with a NoSuchKey error message in the response body.

## Context

I am not sure if this could occur with multiple clients accessing the same file. For example, client 1 completes multipart upload and client 2 deletes file that is renamed before it can be stat'd.

In my environment, I have a customer who automates the moving of files from the Minio bucket as they show up in the bucket. However, the bucket is using NAS and for large files (> 100GB) with thousands of parts, the part deletion can take a few minutes. If the file is moved out of the bucket during this time, then the client waiting for the multipart upload to complete gets notified that the upload failed.

This may be an edge case but it might also highlight a better ordering of the operations inside the fs.CompleteMultipartUpload() function.

## Your Environment
* Version used (`minio version`): RELEASE.2020-05-16T01-33-21Z (built from source)
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Darwin SBarnes 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
simplify FS multipart cleanup

## Motivation and Context
fixes #9671

## How to test this PR?
As mentioned in the issue #9671 cleanup is simply faster now

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#99083bf9-2e09-42a3-a409-c7ee3f914f2f) |
| mint-gateway-s3.sh | :x: [more...](#e7fb0eeb-a211-4549-b655-165f28263415) |
| mint-gateway-azure.sh | :x: [more...](#7d80ba2a-2970-4866-97a3-a7ab579271f4) |
| mint-gateway-nas.sh | :x: [more...](#fc26984f-9f61-45b8-9616-73c61f912f20) |
<a name="fc26984f-9f61-45b8-9616-73c61f912f20"></a>
### 9740-850e9aa/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31932
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 31c411538196:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 1 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... done in 22 seconds
(10/15) Running minio-java tests ... done in 34 seconds
(11/15) Running minio-js tests ... FAILED in 16 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... FAILED in 46 seconds
{
  "name": "minio-py:test_remove_incomplete_upload",
  "function": "remove_incomplete_upload(bucket_name, object_name)",
  "args": {
    "bucket_name": "minio-py-test-57da9c4e-7a14-4401-81d7-f163ff272e9b",
    "object_name": "8af3250a-c2ba-4c57-bdc9-a4d22a103b7f"
  },
  "duration": 29,
  "message": "NoSuchUpload: message: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1276, in test_remove_incomplete_upload\n    client.remove_incomplete_upload(bucket_name, object_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 1408, in remove_incomplete_upload\n    upload.upload_id)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 1825, in _remove_incomplete_upload\n    headers={})\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2020, in _url_open\n    object_name).get_exception()\nminio.error.NoSuchUpload: NoSuchUpload: message: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2097, in main\n    test_remove_incomplete_upload(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1287, in test_remove_incomplete_upload\n    raise Exception(err)\nException: NoSuchUpload: message: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.\n",
  "status": "FAIL"
}
(11/15) Running s3cmd tests ... done in 15 seconds
(12/15) Running s3select tests ... done in 2 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="7d80ba2a-2970-4866-97a3-a7ab579271f4"></a>
### 9740-850e9aa/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31018
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6de6135a87f0:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 31 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... done in 2 minutes and 40 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 5 minutes and 8 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 22 seconds
(9/15) Running minio-go tests ... done in 3 minutes and 52 seconds
(10/15) Running minio-java tests ... FAILED in 24 minutes and 41 seconds
error occurred
ErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-3kkbpfs, objectName = null, resource = /minio-java-test-3kkbpfs, requestId = 1613BA1610EF62E3, hostId = 9c8f842e-92ec-41e2-a4d8-57d01a7fb8f5)
request={method=DELETE, url=http://minio-dev7.minio.io:31018/minio-java-test-3kkbpfs, headers=Host: minio-dev7.minio.io:31018
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/dev
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200530T062137Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200530/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=409, headers=Accept-Ranges: bytes
Content-Length: 328
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 1613BA1610EF62E3
X-Xss-Protection: 1; mode=block
Date: Sat, 30 May 2020 06:21:37 GMT
}

	at io.minio.MinioClient.execute(MinioClient.java:1211)
	at io.minio.MinioClient.execute(MinioClient.java:1236)
	at io.minio.MinioClient.executeDelete(MinioClient.java:1366)
	at io.minio.MinioClient.removeBucket(MinioClient.java:3686)
	at FunctionalTest.teardown(FunctionalTest.java:414)
	at FunctionalTest.runTests(FunctionalTest.java:4122)
	at FunctionalTest.main(FunctionalTest.java:4192)
(10/15) Running minio-js tests ... done in 2 minutes and 45 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 32 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 22 seconds
(13/15) Running s3select tests ... done in 1 minutes and 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="e7fb0eeb-a211-4549-b655-165f28263415"></a>
### 9740-850e9aa/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32097
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 84046e65b316:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 7 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 27 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... done in 43 seconds
(10/15) Running minio-java tests ... done in 38 seconds
(11/15) Running minio-js tests ... done in 34 seconds
(12/15) Running minio-py tests ... FAILED in 52 seconds
{
  "name": "minio-py:test_remove_incomplete_upload",
  "function": "remove_incomplete_upload(bucket_name, object_name)",
  "args": {
    "bucket_name": "minio-py-test-3538a065-81de-4681-b2f9-90939243f7d7",
    "object_name": "b40a1606-4c2d-494f-a24e-a913c2cc8c46"
  },
  "duration": 83,
  "message": "NoSuchUpload: message: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1276, in test_remove_incomplete_upload\n    client.remove_incomplete_upload(bucket_name, object_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 1408, in remove_incomplete_upload\n    upload.upload_id)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 1825, in _remove_incomplete_upload\n    headers={})\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2020, in _url_open\n    object_name).get_exception()\nminio.error.NoSuchUpload: NoSuchUpload: message: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2097, in main\n    test_remove_incomplete_upload(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1287, in test_remove_incomplete_upload\n    raise Exception(err)\nException: NoSuchUpload: message: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.\n",
  "status": "FAIL"
}
(12/15) Running s3cmd tests ... done in 1 minutes and 0 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="99083bf9-2e09-42a3-a409-c7ee3f914f2f"></a>
### 9740-850e9aa/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31461
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 451ee61d1ea5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 42 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... done in 35 seconds
(10/15) Running minio-java tests ... done in 35 seconds
(11/15) Running minio-js tests ... done in 45 seconds
(12/15) Running minio-py tests ... FAILED in 45 seconds
{
  "name": "minio-py:test_remove_incomplete_upload",
  "function": "remove_incomplete_upload(bucket_name, object_name)",
  "args": {
    "bucket_name": "minio-py-test-8f16ba4d-7488-49fe-9787-a064724423c5",
    "object_name": "13c4f20f-83b0-4e58-bcdc-61b03e4d6a35"
  },
  "duration": 43,
  "message": "NoSuchUpload: message: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1276, in test_remove_incomplete_upload\n    client.remove_incomplete_upload(bucket_name, object_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 1408, in remove_incomplete_upload\n    upload.upload_id)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 1825, in _remove_incomplete_upload\n    headers={})\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2020, in _url_open\n    object_name).get_exception()\nminio.error.NoSuchUpload: NoSuchUpload: message: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2097, in main\n    test_remove_incomplete_upload(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1287, in test_remove_incomplete_upload\n    raise Exception(err)\nException: NoSuchUpload: message: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.\n",
  "status": "FAIL"
}
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by kannappanr** [comment]
The minio-py error needs to be looked at

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#605a5d09-cafa-460b-bbb9-3b0a1ace6178) |
<a name="605a5d09-cafa-460b-bbb9-3b0a1ace6178"></a>
### 9740-f4503ef/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30683
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1c7c4d166677:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 36 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 3 minutes and 41 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 3 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 35 seconds
(9/15) Running minio-go tests ... done in 3 minutes and 44 seconds
(10/15) Running minio-java tests ... FAILED in 25 minutes and 49 seconds
error occurred
ErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-vrd9o0, objectName = null, resource = /minio-java-test-vrd9o0, requestId = 1613E1C32C4C6254, hostId = 09f766e8-12b4-4559-be4e-beed4741a881)
request={method=DELETE, url=http://minio-dev6.minio.io:30683/minio-java-test-vrd9o0, headers=Host: minio-dev6.minio.io:30683
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/dev
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200530T182841Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200530/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=409, headers=Accept-Ranges: bytes
Content-Length: 326
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 1613E1C32C4C6254
X-Xss-Protection: 1; mode=block
Date: Sat, 30 May 2020 18:28:41 GMT
}

	at io.minio.MinioClient.execute(MinioClient.java:1211)
	at io.minio.MinioClient.execute(MinioClient.java:1236)
	at io.minio.MinioClient.executeDelete(MinioClient.java:1366)
	at io.minio.MinioClient.removeBucket(MinioClient.java:3686)
	at FunctionalTest.teardown(FunctionalTest.java:414)
	at FunctionalTest.runTests(FunctionalTest.java:4122)
	at FunctionalTest.main(FunctionalTest.java:4192)
(10/15) Running minio-js tests ... done in 2 minutes and 37 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 46 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 22 seconds
(13/15) Running s3select tests ... done in 1 minutes and 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
