### PR TITLE
XL/boot: For XL setup, MINIO_ACCESS_KEY and MINIO_SECRET_KEY are mand…

### LINKED ISSUE #2509: [distributed]: Show error when keys are not set.
When Access and Secret keys are not set and RPC authentication across node fails no error is shown, It just doesn't work. 

A meaningful error message has to be displayed.

### PR DESCRIPTION
**Pull request by krishnasrinivas**
…atory. (for healing and storage RPC calls)

fixes #2509

### CODE REVIEW

**Comment by harshavardhana** [comment]
This is an incorrect fix . We are not forcing people to set envs all the time. In a simpler setup we are asking them to copy `config.json`

**Comment by harshavardhana** [comment]
Is there a reason you would force people to have envs ?

**Comment by krishnasrinivas** [comment]
> This is an incorrect fix . We are not forcing people to set envs all the time. In a simpler setup we are asking them to copy config.json

I see .. for some reason I had assumed that for distributed XL keys are always from env var, let me fix it then.

**Comment by harshavardhana** [comment]
Closing this PR - please re-open @krishnasrinivas if needed freshly.

**Pull request closed without merging**
