### PR TITLE
Move logging handlers to a more specific location

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Currently, each handler chooses to log the whole http request or only headers.
This PR uses a new way of calling specific looging functions in each handler to make
it more elegant and easier to add fine grained functions per handler in the future.

## Motivation and Context
Simplify the code

## How Has This Been Tested?
go test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#d0b76cf4-88cb-4e3f-b739-d2650421dccb) |
<a name="d0b76cf4-88cb-4e3f-b739-d2650421dccb"></a>
### 5558-0e649d3/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31919
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 0aa8432c31e2:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gc6txwwabog9cn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 335,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:31919/aws-sdk-go-test-gc6txwwabog9cn: dial tcp 192.168.122.45:31919: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

**Comment by poornas** [comment]
@vadmeste, isn't a similar change needed for gateway handlers? With api-router converged for object and gateway handlers, think it would make sense to leave the httpTraceAll wrapper in api-router. This change seems to duplicate code without there being a specific need for custom logging - is this in prep for another requirement?

**Review by krishnasrinivas — COMMENTED** [review]
> @vadmeste, isn't a similar change needed for gateway handlers? With api-router converged for object and gateway handlers, think it would make sense to leave the httpTraceAll wrapper in api-router. This change seems to duplicate code without there being a specific need for custom logging - is this in prep for another requirement?

 @poornas You removed gateway-handlers when ObjectLayer and GatewayLayer was merged. But otherwise I agree with Poorna.

@vadmeste I feel the current style is better than the one you have proposed.

```
 func (api objectAPIHandlers) GetObjectHandler(w http.ResponseWriter, r *http.Request) {
	httpTraceHdrs(api.getObjectHandler)(w, r)
}

func (api objectAPIHandlers) getObjectHandler(w http.ResponseWriter, r *http.Request) {
```

Using Capital letter to indicate logging is not intuitive as Capital letter is for exporting , You can use `LogGetObjectHandler` instead. But this commit makes the code more verbose without adding much value.

**Comment by vadmeste** [comment]
This commit helps to implement the following feature:

Return an error to clients making HTTPS requests to Minio server when TLS certificate is revoked (this is related to OCSP commit), but all other requests (rpc, storage) should continue to work normally.

So in this case, Object APIs will need to run a new handler to return that "tls revoked error", which is somehow similar to the logging problem (each handler chooses to log only headers or headers & body)

So this PR demonstrates an elegant way to do this. Each handler decides which other handlers to wrap the request.

Otherwise, we will have more ugly code in api-router.go. 

`bucket.Methods("GET").Path("/{object:.+}").HandlerFunc(checkTLSCert(httpTraceHdrs(api.GetObjectHandler)))`

**Comment by krishnasrinivas** [comment]
```
bucket.Methods("GET").Path("/{object:.+}").HandlerFunc(checkTLSCert(httpTraceHdrs(api.GetObjectHandler)))
```

Does not seem ugly @vadmeste I mean this is a familiar pattern in functional programming right?

Even with this commit, you will have to do this?:

```
 func (api objectAPIHandlers) GetObjectHandler(w http.ResponseWriter, r *http.Request) {
	checkTLSCert(httpTraceHdrs(api.getObjectHandler))(w, r)
}

func (api objectAPIHandlers) getObjectHandler(w http.ResponseWriter, r *http.Request) {
```

This looks similar to `bucket.Methods("GET").Path("/{object:.+}").HandlerFunc(checkTLSCert(httpTraceHdrs(api.GetObjectHandler)))`

**Pull request closed without merging**
