### PR TITLE
Move all Dockerfiles to alpine-3.6

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Fix this to avoid issues like below

```
docker run --rm minio/minio:edge-armhf version
minio: <ERROR> .... is not compiled by Go >= 1.8.3. ... recompile...
```

## Motivation and Context
Refer #4759 

## How Has This Been Tested?
Manually by building containers locally. 

```
$ docker run --rm --privileged multiarch/qemu-user-static:register --reset
$ docker build -t minio/minio:edge-armhf . -f Dockerfile.armhf
$ docker build -t minio/minio:edge-aarch64 . -f Dockerfile.aarch64
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by nitisht — COMMENTED** [review]
Tested locally, LGTM

**Comment by harshavardhana** [comment]
Can this is be reviewed and merged?

**Review by poornas — APPROVED** [review]
Tested - looks good.

**Comment by harshavardhana** [comment]
@NitishT any review from your end?

**Review by nitisht — APPROVED** [review]
Tested locally, LGTM

**Pull request merged**
