### PR TITLE
fix: readdir fallback on root of the drive

### LINKED ISSUE #15452: Insufficient number of disks online for ListBuckets
At startup the server is "Unable to list buckets to heal: Read failed. Insufficient number of disks online". `mc admin info` is all green. Interactions with a bucket works. But `mc ls myserver`  fails, and we can't log into the web console because of the same error.

## Expected Behavior
Should work properly because all drives are online and reachable.

## Current Behavior
- Can't list buckets.
- Can't use the web console.

## Steps to Reproduce (for bugs)
1. Upgrade from `RELEASE.2022-01-08T03-11-54Z` to `RELEASE.2022-07-30T05-21-40Z`. (Or else, I didn't try).
2. `mc ls cold`
3.  `mc admin info cold --json`
```
mc: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(Read failed. Insufficient number of disks online)
```
```json
{
  "status": "success",
  "info": {
    "mode": "online",
    "domain": ["cold-objects.liiib.re", "minio-cold.svc.cluster.local"],
    "deploymentID": "6ccb138d-7f98-4197-9617-bf5671b0cb3f",
    "buckets": { "count": 91 },
    "objects": { "count": 674953 },
    "versions": { "count": 0 },
    "usage": { "size": 2365564670348 },
    "services": {
      "kms": { "status": "disabled" },
      "ldap": {},
      "audit": [{ "": { "status": "online" } }]
    },
    "backend": {
      "backendType": "Erasure",
      "onlineDisks": 10,
      "rrSCParity": 2,
      "standardSCParity": 5
    },
    "servers": [
      {
        "state": "online",
        "endpoint": "cold-pool-0-0.cold-hl.minio-cold.svc.cluster.local:9000",
        "uptime": 2355,
        "version": "2022-07-30T05:21:40Z",
        "commitID": "e6eab2091f632622fadbe3b25bb4732125b2d5df",
        "network": {
          "cold-pool-0-0.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-1.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-2.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-3.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-4.cold-hl.minio-cold.svc.cluster.local:9000": "online"
        },
        "drives": [
          {
            "endpoint": "https://cold-pool-0-0.cold-hl.minio-cold.svc.cluster.local:9000/export0",
            "path": "/export0",
            "state": "ok",
            "uuid": "863b28b0-9fb8-4bf5-b21a-ddfc942865ff",
            "totalspace": 1999422177280,
            "usedspace": 492754219008,
            "availspace": 1506667958272,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 3, "acc_time_ns": 68522615 },
                "ReadXL": { "count": 88, "acc_time_ns": 59321080 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 3,
                "CreateFile": 15,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 3,
                "ReadMultiple": 0,
                "ReadVersion": 717,
                "ReadXL": 4426,
                "RenameData": 29,
                "RenameFile": 0,
                "StatInfoFile": 0,
                "StatVol": 33,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193367130,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 0
          },
          {
            "endpoint": "https://cold-pool-0-0.cold-hl.minio-cold.svc.cluster.local:9000/export1",
            "path": "/export1",
            "state": "ok",
            "uuid": "d917f9a2-28a4-4eef-9ce7-16676f22c638",
            "totalspace": 1999422177280,
            "usedspace": 492770521088,
            "availspace": 1506651656192,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 3, "acc_time_ns": 49382338 },
                "ReadXL": { "count": 88, "acc_time_ns": 35144390 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 3,
                "CreateFile": 15,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 3,
                "ReadMultiple": 0,
                "ReadVersion": 717,
                "ReadXL": 4426,
                "RenameData": 29,
                "RenameFile": 0,
                "StatInfoFile": 0,
                "StatVol": 33,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193367034,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 5
          }
        ],
        "poolNumber": 1,
        "mem_stats": {
          "Alloc": 503876424,
          "TotalAlloc": 42245016928,
          "Mallocs": 514867790,
          "Frees": 512458640,
          "HeapAlloc": 503876424
        }
      },
      {
        "state": "online",
        "endpoint": "cold-pool-0-1.cold-hl.minio-cold.svc.cluster.local:9000",
        "uptime": 2277,
        "version": "2022-07-30T05:21:40Z",
        "commitID": "e6eab2091f632622fadbe3b25bb4732125b2d5df",
        "network": {
          "cold-pool-0-0.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-1.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-2.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-3.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-4.cold-hl.minio-cold.svc.cluster.local:9000": "online"
        },
        "drives": [
          {
            "endpoint": "https://cold-pool-0-1.cold-hl.minio-cold.svc.cluster.local:9000/export0",
            "path": "/export0",
            "state": "ok",
            "uuid": "7286fd5f-5236-4b08-86a3-9a8656b0910c",
            "totalspace": 1999422177280,
            "usedspace": 492790312960,
            "availspace": 1506631864320,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 2, "acc_time_ns": 32836705 },
                "ReadXL": { "count": 88, "acc_time_ns": 193056199 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 3,
                "CreateFile": 9,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 3,
                "ReadMultiple": 0,
                "ReadVersion": 716,
                "ReadXL": 4315,
                "RenameData": 20,
                "RenameFile": 1,
                "StatInfoFile": 0,
                "StatVol": 25,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193366872,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 1
          },
          {
            "endpoint": "https://cold-pool-0-1.cold-hl.minio-cold.svc.cluster.local:9000/export1",
            "path": "/export1",
            "state": "ok",
            "uuid": "b0a51fe5-487f-4106-9190-a990475fb7ab",
            "totalspace": 1999422177280,
            "usedspace": 492790165504,
            "availspace": 1506632011776,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 2, "acc_time_ns": 39966338 },
                "ReadXL": { "count": 88, "acc_time_ns": 63284321 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 3,
                "CreateFile": 9,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 2,
                "ReadMultiple": 0,
                "ReadVersion": 716,
                "ReadXL": 4315,
                "RenameData": 20,
                "RenameFile": 1,
                "StatInfoFile": 0,
                "StatVol": 25,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193366877,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 6
          }
        ],
        "poolNumber": 1,
        "mem_stats": {
          "Alloc": 555301360,
          "TotalAlloc": 9896781800,
          "Mallocs": 117514642,
          "Frees": 114365775,
          "HeapAlloc": 555301360
        }
      },
      {
        "state": "online",
        "endpoint": "cold-pool-0-2.cold-hl.minio-cold.svc.cluster.local:9000",
        "uptime": 2351,
        "version": "2022-07-30T05:21:40Z",
        "commitID": "e6eab2091f632622fadbe3b25bb4732125b2d5df",
        "network": {
          "cold-pool-0-0.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-1.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-2.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-3.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-4.cold-hl.minio-cold.svc.cluster.local:9000": "online"
        },
        "drives": [
          {
            "endpoint": "https://cold-pool-0-2.cold-hl.minio-cold.svc.cluster.local:9000/export0",
            "path": "/export0",
            "state": "ok",
            "uuid": "ad4f751c-55c3-4773-8cd9-3468698d2671",
            "totalspace": 1999422177280,
            "usedspace": 493674569728,
            "availspace": 1505747607552,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 6, "acc_time_ns": 93021219 },
                "ReadXL": { "count": 84, "acc_time_ns": 491778379 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 5,
                "CreateFile": 10,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 4,
                "ReadMultiple": 0,
                "ReadVersion": 740,
                "ReadXL": 4313,
                "RenameData": 27,
                "RenameFile": 1,
                "StatInfoFile": 0,
                "StatVol": 31,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193360921,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 2
          },
          {
            "endpoint": "https://cold-pool-0-2.cold-hl.minio-cold.svc.cluster.local:9000/export1",
            "path": "/export1",
            "state": "ok",
            "uuid": "b30d1c13-6297-4a02-9e28-9b402c7986c3",
            "totalspace": 1999422177280,
            "usedspace": 493668155392,
            "availspace": 1505754021888,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 6, "acc_time_ns": 89417586 },
                "ReadXL": { "count": 84, "acc_time_ns": 80697037 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 5,
                "CreateFile": 10,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 3,
                "ReadMultiple": 0,
                "ReadVersion": 740,
                "ReadXL": 4313,
                "RenameData": 27,
                "RenameFile": 1,
                "StatInfoFile": 0,
                "StatVol": 31,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193360929,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 7
          }
        ],
        "poolNumber": 1,
        "mem_stats": {
          "Alloc": 524474752,
          "TotalAlloc": 10185364440,
          "Mallocs": 121652554,
          "Frees": 118887339,
          "HeapAlloc": 524474752
        }
      },
      {
        "state": "online",
        "endpoint": "cold-pool-0-3.cold-hl.minio-cold.svc.cluster.local:9000",
        "uptime": 2150,
        "version": "2022-07-30T05:21:40Z",
        "commitID": "e6eab2091f632622fadbe3b25bb4732125b2d5df",
        "network": {
          "cold-pool-0-0.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-1.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-2.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-3.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-4.cold-hl.minio-cold.svc.cluster.local:9000": "online"
        },
        "drives": [
          {
            "endpoint": "https://cold-pool-0-3.cold-hl.minio-cold.svc.cluster.local:9000/export0",
            "path": "/export0",
            "state": "ok",
            "uuid": "28d6bb70-e581-414a-87c1-028dc2d08189",
            "totalspace": 1999422177280,
            "usedspace": 492859105280,
            "availspace": 1506563072000,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 5, "acc_time_ns": 65529520 },
                "ReadXL": { "count": 88, "acc_time_ns": 48888534 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 1,
                "CreateFile": 11,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 1,
                "ReadMultiple": 0,
                "ReadVersion": 697,
                "ReadXL": 4130,
                "RenameData": 23,
                "RenameFile": 0,
                "StatInfoFile": 0,
                "StatVol": 27,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193366447,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 3
          },
          {
            "endpoint": "https://cold-pool-0-3.cold-hl.minio-cold.svc.cluster.local:9000/export1",
            "path": "/export1",
            "state": "ok",
            "uuid": "2ad7fb8a-a96a-4cba-b084-aabcc23877da",
            "totalspace": 1999422177280,
            "usedspace": 492859097088,
            "availspace": 1506563080192,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 5, "acc_time_ns": 60499273 },
                "ReadXL": { "count": 88, "acc_time_ns": 114468842 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 1,
                "CreateFile": 11,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 1,
                "ReadMultiple": 0,
                "ReadVersion": 697,
                "ReadXL": 4130,
                "RenameData": 23,
                "RenameFile": 0,
                "StatInfoFile": 0,
                "StatVol": 27,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193366456,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 8
          }
        ],
        "poolNumber": 1,
        "mem_stats": {
          "Alloc": 350377936,
          "TotalAlloc": 9375408504,
          "Mallocs": 111676062,
          "Frees": 111149245,
          "HeapAlloc": 350377936
        }
      },
      {
        "state": "online",
        "endpoint": "cold-pool-0-4.cold-hl.minio-cold.svc.cluster.local:9000",
        "uptime": 2145,
        "version": "2022-07-30T05:21:40Z",
        "commitID": "e6eab2091f632622fadbe3b25bb4732125b2d5df",
        "network": {
          "cold-pool-0-0.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-1.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-2.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-3.cold-hl.minio-cold.svc.cluster.local:9000": "online",
          "cold-pool-0-4.cold-hl.minio-cold.svc.cluster.local:9000": "online"
        },
        "drives": [
          {
            "endpoint": "https://cold-pool-0-4.cold-hl.minio-cold.svc.cluster.local:9000/export0",
            "path": "/export0",
            "state": "ok",
            "uuid": "3ce93a7a-1fc5-46c8-82bf-7d199da935cd",
            "totalspace": 1999422177280,
            "usedspace": 492668305408,
            "availspace": 1506753871872,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 3, "acc_time_ns": 40520831 },
                "ReadXL": { "count": 91, "acc_time_ns": 130619459 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 2,
                "CreateFile": 14,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 2,
                "ReadMultiple": 0,
                "ReadVersion": 713,
                "ReadXL": 4116,
                "RenameData": 26,
                "RenameFile": 0,
                "StatInfoFile": 0,
                "StatVol": 30,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193366923,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 4
          },
          {
            "endpoint": "https://cold-pool-0-4.cold-hl.minio-cold.svc.cluster.local:9000/export1",
            "path": "/export1",
            "state": "ok",
            "uuid": "7067e1b6-84f7-4106-b6e5-efdaf661e470",
            "totalspace": 1999422177280,
            "usedspace": 492661469184,
            "availspace": 1506760708096,
            "metrics": {
              "lastMinute": {
                "ReadVersion": { "count": 3, "acc_time_ns": 46955906 },
                "ReadXL": { "count": 91, "acc_time_ns": 73400250 }
              },
              "apiCalls": {
                "AppendFile": 0,
                "CheckParts": 2,
                "CreateFile": 14,
                "Delete": 0,
                "DeleteVersion": 0,
                "DeleteVersions": 0,
                "DeleteVol": 0,
                "ListDir": 0,
                "ListVols": 0,
                "MakeVol": 0,
                "MakeVolBulk": 0,
                "ReadAll": 2,
                "ReadFile": 0,
                "ReadFileStream": 2,
                "ReadMultiple": 0,
                "ReadVersion": 713,
                "ReadXL": 4116,
                "RenameData": 26,
                "RenameFile": 0,
                "StatInfoFile": 0,
                "StatVol": 30,
                "UpdateMetadata": 0,
                "VerifyFile": 0,
                "WalkDir": 5,
                "WriteAll": 0,
                "WriteMetadata": 0
              }
            },
            "free_inodes": 193366935,
            "pool_index": 0,
            "set_index": 0,
            "disk_index": 9
          }
        ],
        "poolNumber": 1,
        "mem_stats": {
          "Alloc": 533376464,
          "TotalAlloc": 9463903224,
          "Mallocs": 111856634,
          "Frees": 109045018,
          "HeapAlloc": 533376464
        }
      }
    ]
  }
}
```

## Context
We just updated our cluster to the latest release (RELEASE.2022-07-30T05-21-40Z) from RELEASE.2022-01-08T03-11-54Z. We're using the latest version of the operator (v4.4.27) on k8s (v1.21).

On Slack @prakashsvmx asked for the disks permissions :
```
drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export0
drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export1

drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export0
drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export1

drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export0
drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export1

drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export0
drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export1

drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export0
drwxrwsr-x  94 root 1000 4096 Jul 22 09:39 export1
```

## Regression
It's possible.

## Your Environment
* Version used:  RELEASE.2022-07-30T05-21-40Z
* Server setup and configuration: k8s, 5 servers of 2 disks.
* Operating System and version: Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: readdir fallback on root of the drive

## Motivation and Context
fixes #15452

## How to test this PR?
As per #15452 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression yes mostly introduced in #15426
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Review by Alevsk — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by dvaldivia — APPROVED** [review]
Tested. LGTM.

**Comment by hrenard** [comment]
I confirm this fixes the issue https://github.com/minio/minio/issues/15452. Though I don't understand why.

Anyway, thanks for reacting this quickly !

**Comment by harshavardhana** [comment]
> I confirm this fixes the issue #15452. Though I don't understand why.
> 
> Anyway, thanks for reacting this quickly !

The reason is O_NOATIME requires root mount to have the same permissions as the running user under security context.

Since the mount itself is done by root and there is no chown attempted after that for the mount folder this doesn't work.

This is a nuance of open flags kernel behavior.

**Pull request merged**
