### PR TITLE
Websocket grid benchmarks & improvements

### PR DESCRIPTION
**Pull request by klauspost**
(against `next`)

## Description

Add stream benchmarks. Reduce allocations.

Fixes a few minor issues as well.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Optimization (provides speedup with no functional changes)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
This PR caused some issue with `healing functional tests` - server returning 403's 

https://github.com/minio/minio/actions/runs/6695145724/job/18190054122?pr=18344

Canceled this 4hr run

**Comment by klauspost** [comment]
@harshavardhana It is a race, where `ReadAll` can succeed before the grid is connected. I have reproduced it locally.

Since `loadFormatErasure` relies on response from `ReadAll` for quorum, it may be able to perform the call before the grid is up (it may be in a retry backoff).

I inserted a `DiskInfo` call before the ReadAll. This gets rid of the race.

**Comment by klauspost** [comment]
@harshavardhana You may want to consider adding a check that reformats if the initial formatting is not successful.

**Comment by harshavardhana** [comment]
> @harshavardhana You may want to consider adding a check that reformats if the initial formatting is not successful.

Not sure I follow @klauspost what is this about ?

**Pull request merged**
