### PR TITLE
Don't exit background append if backend specific files show up

### LINKED ISSUE #7518: Minio does not ignore .nfs files
API: PutObjectPart(bucket=XXX-XX, object=xxexxxxi.sc_dts_b_base.322297.19686)
Time: 12:48:34 UTC 04/12/2019
RequestID: 1594BAD6ACF06575
RemoteHost: 10.20.78.121
UserAgent: rclone/v1.46
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
entry=.nfs8082d4900000d71000000003, uploadID=1938dd53-81d6-4774-b370-396546196b4d
1: cmd/fs-v1-multipart.go:102:cmd.(*FSObjects).backgroundAppend()

## Expected Behavior

Minio should avoid parsing non-minio files (like ".nfs" files)

## Current Behavior

Minio tries to parse .nfs files and panic with the above error

Reference for nfs files: https://uisapp2.iu.edu/confluence-prd/pages/viewpage.action?pageId=123962105

### PR DESCRIPTION
**Pull request by krisis**
As part of background append Minio expects part files to be of the form `partNumber.etag.size`. In some backend filesystems, like in #7518, special files appear in Minio's internal upload directory, causing background append to exit due to invalid part file name. We should skip non part files.

## Description

The PR ignores invalid part file name error to accommodate backend specific files appearing during a background append.
Fixes #7518 
## Motivation and Context

See #7518 

## Regression

No
## How Has This Been Tested?

1. Start a multipart upload
2. Add a file like `/etc/issue` to the upload directory in Minio's backend
3. Complete the multipart upload and check if file is successfully uploaded

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#cc0765ac-7df3-42db-8e5a-76ad7688626d) |
| mint-large-bucket.sh | :x: [more...](#58ded8f4-e691-4071-964a-43ee3b3d57b7) |
| mint-compression-dist-xl.sh | :x: [more...](#a0cd3ff0-7a80-420d-baca-8086c99ca8ba) |
| mint-worm.sh | :x: [more...](#ffbd3443-a2c1-4e99-b2cb-9f8a109ec896) |
| mint-dist-xl.sh | :x: [more...](#80f2d479-dcad-4aa7-858a-2cbd85ba4744) |
<a name="58ded8f4-e691-4071-964a-43ee3b3d57b7"></a>
### 7519-e7ac57c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31961
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5f040dbedfb0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wahmzhcbbqlysm",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 343,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:31961/aws-sdk-go-test-wahmzhcbbqlysm: dial tcp 72.28.97.59:31961: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="ffbd3443-a2c1-4e99-b2cb-9f8a109ec896"></a>
### 7519-e7ac57c/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31134
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1faf0349f36a:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-kml2zu1dkn3n1khih0ihqqvws6zfnthwkvn3fw1b31c7hvevv32swnk",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 287,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:31134/bucket-kml2zu1dkn3n1khih0ihqqvws6zfnthwkvn3fw1b31c7hvevv32swnk: dial tcp 72.28.97.59:31134: connect: connection refused",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="80f2d479-dcad-4aa7-858a-2cbd85ba4744"></a>
### 7519-e7ac57c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30629
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 250b116f5b57:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0xbt14vr04n311",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 4355,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30629/aws-sdk-go-test-0xbt14vr04n311: dial tcp 72.28.97.55:30629: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="cc0765ac-7df3-42db-8e5a-76ad7688626d"></a>
### 7519-e7ac57c/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30530
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 96e081144e48:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 30 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 27 seconds
(11/14) Running minio-js tests ... done in 37 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 17 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL",
  "duration": 88,
  "args": {
    "bucket_name": "minio-py-test-67e1f57b-121e-4cdd-a235-a3836b916181",
    "object_name": "e4a30cba-da81-449a-aa0c-79e747a67e1f"
  }
}

Executed 11 out of 14 tests successfully.
```
<a name="a0cd3ff0-7a80-420d-baca-8086c99ca8ba"></a>
### 7519-e7ac57c/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30546
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bc1cf97bb784:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-9nziqf4qrkat4d",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 327,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30546/aws-sdk-go-test-9nziqf4qrkat4d: dial tcp 72.28.97.60:30546: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#f8b9c28a-1595-4e89-abcd-1ffd1740fe87) |
| mint-large-bucket.sh | :x: [more...](#88da20fa-1ffb-445f-ac68-08672a6c8d00) |
| mint-dist-xl.sh | :x: [more...](#67793bc2-c06e-4198-ab62-dd8e14be3fd6) |
<a name="67793bc2-c06e-4198-ab62-dd8e14be3fd6"></a>
### 7519-3d7039b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30850
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a34dc603e01a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mpy66mzkx3dznq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 299,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.52:30850/aws-sdk-go-test-mpy66mzkx3dznq: dial tcp 72.28.97.52:30850: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f8b9c28a-1595-4e89-abcd-1ffd1740fe87"></a>
### 7519-3d7039b/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32066
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d703ec90300a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-n9u2nqfw3sd60x",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 284,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:32066/aws-sdk-go-test-n9u2nqfw3sd60x: dial tcp 72.28.97.54:32066: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="88da20fa-1ffb-445f-ac68-08672a6c8d00"></a>
### 7519-3d7039b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32451
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 021526314cd6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ymymkp0amweelh",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 337,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:32451/aws-sdk-go-test-ymymkp0amweelh: dial tcp 72.28.97.53:32451: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by kannappanr — DISMISSED** [review]
Tested with List Incomplete parts. LGTM.

**Review by poornas — DISMISSED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d5468895-5800-4736-b1d8-b8d17d9a2958) |
| mint-compression-dist-xl.sh | :x: [more...](#5a40080f-1ae1-4098-ab72-a9d4050e7d36) |
| mint-compression-fs.sh | :x: [more...](#37196e11-60a0-4a9a-913d-182213848356) |
| mint-dist-xl.sh | :x: [more...](#c941afe6-a12f-47ba-a443-9855de17222a) |
<a name="d5468895-5800-4736-b1d8-b8d17d9a2958"></a>
### 7519-6a8ac45/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31322
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d1d61cb83730:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-pu1yoz41ylg5or",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 282,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:31322/aws-sdk-go-test-pu1yoz41ylg5or: dial tcp 72.28.97.61:31322: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c941afe6-a12f-47ba-a443-9855de17222a"></a>
### 7519-6a8ac45/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31145
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 234a8dfeec3a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... FAILED in 1 minutes and 4 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPost(bucket_name,file_name,expires_in_sec,max_byte_size)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-8190645036ce",
    "file_name": "datafile-1-kB",
    "expires_in_sec": 60,
    "max_byte_size": 3145728
  },
  "duration": 60025.34,
  "error": "execution expired",
  "status": "FAIL"
}

Executed 3 out of 14 tests successfully.
```
<a name="37196e11-60a0-4a9a-913d-182213848356"></a>
### 7519-6a8ac45/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30549
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 41e0f6138a75:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-6uc14dd0lhqwfb",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 334,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.51:30549/aws-sdk-go-test-6uc14dd0lhqwfb: dial tcp 72.28.97.51:30549: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5a40080f-1ae1-4098-ab72-a9d4050e7d36"></a>
### 7519-6a8ac45/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31531
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp feda91170f6a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 19 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-etv2a3cw44t2yd",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 18404,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31531/aws-sdk-go-test-etv2a3cw44t2yd: dial tcp 72.28.97.57:31531: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by kannappanr — APPROVED** [review]

**Review by poornas — APPROVED** [review]

**Pull request merged**
