### PR TITLE
docs(README): add enable option to events examples

### PR DESCRIPTION
**Pull request by PacoDu**
## Description
CLI examples for minio events configuration are missing the enable argument.

## Motivation and Context
Broken examples

## How to test this PR?
Run the example command

### CODE REVIEW

**Comment by harshavardhana** [comment]
@PacoDu enable is implicit, it is on purpose not mentioned. I don't think we need this PR.

**Comment by harshavardhana** [comment]
Can you demonstrate an issue without using enable key?

**Comment by PacoDu** [comment]
> @PacoDu enable is implicit, it is on purpose not mentioned. I don't think we need this PR.

I'm writing a related issue on mc repo that I'm trying to fix: I'm facing a nil pointer exception when I run the example. As I already faced the issue with the environment variable ENABLE that was missing, I thought that it was the same for the CLI. But I misunderstood the issue we can close the PR, sorry for the noise. (see https://github.com/minio/mc/issues/3086 for the real issue)

**Comment by harshavardhana** [comment]
Thanks

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#1dc19d1f-e49a-4665-bb86-21288da9c96c) |
| mint-gateway-azure.sh | :x: [more...](#dc03986f-55e5-4683-baa5-732139196149) |
| mint-gateway-nas.sh | :x: [more...](#93ceed05-f9fe-440f-803c-53c65d3acc0f) |
<a name="1dc19d1f-e49a-4665-bb86-21288da9c96c"></a>
### 9019-0072fb7/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30140
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7ef5b9e48c88:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-zt4vl6hh4nd2pj",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120332,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30140/aws-sdk-go-test-zt4vl6hh4nd2pj: dial tcp 72.28.97.55:30140: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="dc03986f-55e5-4683-baa5-732139196149"></a>
### 9019-0072fb7/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31725
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7c254825256b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 36 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 23 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/14) Running minio-go tests ... done in 21 minutes and 4 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 32 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11305,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-2g1s1r9, objectName=minio-java-test-3mbi4dv, resource=/minio-java-test-2g1s1r9/minio-java-test-3mbi4dv, requestId=15F4CBEFEBE230FC, hostId=92499012-0d5f-4a16-b0d6-848e39476ecc)\nrequest={method=PUT, url=http://72.28.97.58:31725/minio-java-test-2g1s1r9/minio-java-test-3mbi4dv?uploadId=6d59090fe4eebb46&partNumber=1, headers=x-amz-copy-source-if-match: 37b0bd320a16542a0df5894020a49c06-2\nx-amz-copy-source: minio-java-test-2g1s1r9/minio-java-test-d8jj38\nAccept-Encoding: identity\nHost: 72.28.97.58:31725\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200219T120000Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200219/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-19T10-54-26Z\nVary: Origin\nX-Amz-Request-Id: 15F4CBEFEBE230FC\nX-Xss-Protection: 1; mode=block\nDate: Wed, 19 Feb 2020 12:00:00 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="93ceed05-f9fe-440f-803c-53c65d3acc0f"></a>
### 9019-0072fb7/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32322
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b1adac0bd3ce:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-x9a1e9rxaucoj5",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120267,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32322/aws-sdk-go-test-x9a1e9rxaucoj5: dial tcp 72.28.97.55:32322: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request closed without merging**
