### PR TITLE
Expose version info in prometheus

### LINKED ISSUE #7795: Add minio_info metric or similar that exposed the same information as "minio version:" does.
It's great to have version number in Prometheus.. I have a lot of minio instances and a lot of them are probably not up to date because it's kind of hard to track.

This is an established pattern:

```
prometheus_build_info{branch="HEAD",goversion="go1.12.5",instance="localhost:9090",job="prometheus",revision="d20e84d0fb64aff2f62a977adc8cfb656da4e286",version="2.10.0"}


go_info{instance="localhost:9090",job="prometheus",version="go1.12.5"}


python_info{implementation="CPython",instance="e:443",job="....,major="3",minor="7",patchlevel="3",version="3.7.3"}
```

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
Expose MinIO's version information <version, commitID> 

## Motivation and Context
Fixes #7795

## Regression
No

## How Has This Been Tested?
- Start MinIO server on localhost:9000
- check `http://localhost:9000/minio/prometheus/metrics` for the `minio_version_info` metric

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#cae3464a-dfc8-4688-b9b4-18c1fcdf4eb3) |
| mint-dist-xl.sh | :x: [more...](#1633a9ec-c712-4f0d-a278-0fa0e86fe1b6) |
<a name="1633a9ec-c712-4f0d-a278-0fa0e86fe1b6"></a>
### 7812-e7708bf/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30059
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3b9ce57091f1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 30 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 19 seconds
(10/14) Running minio-java tests ... FAILED in 53 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName)",
  "duration": 41,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.52:30059/minio-java-test-32hdcu8/minio-java-test-t31909?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190620%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190620T121701Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=7ab95f2d3a639b590ccc6e8b6237d0a30122599dffed22de61e2375102a928e8}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-t31909</Key><BucketName>minio-java-test-32hdcu8</BucketName><Resource>/minio-java-test-32hdcu8/minio-java-test-t31909</Resource><RequestId>15A9E74318606F0F</RequestId><HostId>b06922f9-81ca-4951-b70b-6859d879463b</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test1(FunctionalTest.java:1767), FunctionalTest.runTests(FunctionalTest.java:2994), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="cae3464a-dfc8-4688-b9b4-18c1fcdf4eb3"></a>
### 7812-e7708bf/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31019
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9460af1e0fc8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-nzvkre4z39hiee",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3074,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31019/aws-sdk-go-test-nzvkre4z39hiee: dial tcp 72.28.97.57:31019: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
{"name": "7812-e7708bf", "full_size": 63684858, "images": [{"size": 63684858, "architecture": "amd64", "variant": null, "features": null, "os": "linux", "os_version": null, "os_features": null}], "id": 59515194, "repository": 757613, "creator": 21164, "last_updater": 21164, "last_updated": "2019-06-20T11:59:54.065250Z", "image_id": null, "v2": true}

**Review by harshavardhana — APPROVED** [review]

**Comment by Praveenrajmani** [comment]
PTAL @sinhaashish

**Comment by kannappanr** [comment]
ping @sinhaashish

**Review by sinhaashish — APPROVED** [review]
LGTM

**Pull request merged**
