### PR TITLE
Automatically set goroutines based on shardSize

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Update reedsolomon library to enable feature to automatically
set number of go-routines based on the input shard size,
since shard size is sort of a constant in Minio for
objects > 10MiB (default blocksize)

## Motivation and Context
klauspost reported around 15-20% improvement in performance
numbers on older systems such as AVX and SSE3

```
name                  old speed      new speed      delta
Encode10x2x10000-8    5.45GB/s ± 1%  6.22GB/s ± 1%  +14.20%    (p=0.000 n=9+9)
Encode100x20x10000-8  1.44GB/s ± 1%  1.64GB/s ± 1%  +13.77%  (p=0.000 n=10+10)
Encode17x3x1M-8       10.0GB/s ± 5%  12.0GB/s ± 1%  +19.88%  (p=0.000 n=10+10)
Encode10x4x16M-8      7.81GB/s ± 5%  8.56GB/s ± 5%   +9.58%   (p=0.000 n=10+9)
Encode5x2x1M-8        15.3GB/s ± 2%  19.6GB/s ± 2%  +28.57%   (p=0.000 n=9+10)
Encode10x2x1M-8       12.2GB/s ± 5%  15.0GB/s ± 5%  +22.45%  (p=0.000 n=10+10)
Encode10x4x1M-8       7.84GB/s ± 1%  9.03GB/s ± 1%  +15.19%    (p=0.000 n=9+9)
Encode50x20x1M-8      1.73GB/s ± 4%  2.09GB/s ± 4%  +20.59%   (p=0.000 n=10+9)
Encode17x3x16M-8      10.6GB/s ± 1%  11.7GB/s ± 4%  +10.12%   (p=0.000 n=8+10)
```

## How Has This Been Tested?
Manually using `go test` 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by aead — APPROVED** [review]
LGTM

**Review by fwessels — APPROVED** [review]
LGTM

**Comment by kannappanr** [comment]
@harshavardhana Does this PR need mint tests to be run? If yes, can you please comment on the mint tests that were run and the results?

**Comment by harshavardhana** [comment]
Mint tests run fine, do you want me to post the results ?

**Comment by kannappanr** [comment]
No, just want to make sure that it is run.

**Comment by balamurugana** [comment]
b'mint-xl.sh: PASSED\n---\nmint-fs.sh: PASSED\n---\nmint-dist-xl.sh: PASSED\n---\n'

**Comment by balamurugana** [comment]
```mint-xl.sh: PASSED
---
mint-fs.sh: PASSED
---
mint-dist-xl.sh: PASSED
---
```

**Comment by harshavardhana** [comment]
@balamurugana how about markdown style 

| TEST | STATUS |
---|----
|mint-fs.sh | PASSED|
|mint-dist-xl.sh | PASSED|

**Comment by balamurugana** [comment]
```
mint-xl.sh: PASSED
---
mint-fs.sh: PASSED
---
mint-dist-xl.sh: PASSED
---

```

**Pull request merged**
