### PR TITLE
[WIP] Remove support for multiple notification targets

### PR DESCRIPTION
**Pull request by krishnasrinivas**
## Description

Filter notify config such that if any of the notification config has more than one target we show
a warning message and retain only one target. This is just to test waters to see if we can
do away with supporting multiple targets in the new key/value style config.

## Regression

No

## How Has This Been Tested?

Manual (i.e playing with config settings with more than 1 target)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by harshavardhana — CHANGES_REQUESTED** [review]
All our notification docs should be updated to reflect this change @krishnasrinivas

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :x: [more...](#e0a6846c-bc56-4536-9883-7296eb9d4a4f) |
| mint-xl.sh | :x: [more...](#60df0073-9753-4c77-9c50-4f8c74f207bb) |
| mint-large-bucket.sh | :x: [more...](#5669ee67-8577-47fd-841e-52224be47c1d) |
| mint-compression-dist-xl.sh | :x: [more...](#913ab368-f78a-4ad9-8c67-f752dfa46926) |
| mint-compression-fs.sh | :x: [more...](#34e07b01-0dca-471a-98f7-0307e6ff4136) |
| mint-worm.sh | :x: [more...](#975f6525-7aec-4053-ade6-1f9ee996982f) |
| mint-fs.sh | :x: [more...](#d30043d2-5cb9-4fe0-b6a7-5393a3393bd3) |
| mint-dist-xl.sh | :x: [more...](#5162cea9-4819-46cf-8845-1656bbbf3766) |
| mint-gateway-nas.sh | :x: [more...](#b778718b-1d90-4d36-bcb7-4746c0b4c815) |
<a name="d30043d2-5cb9-4fe0-b6a7-5393a3393bd3"></a>
### 7192-0090511/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32454
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 737cc701ef4c:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 1 seconds
(5/13) Running awscli tests ... done in 1 minutes and 43 seconds
(6/13) Running mc tests ... done in 11 seconds
(7/13) Running minio-dotnet tests ... done in 2 minutes and 22 seconds
(8/13) Running minio-go tests ... done in 17 seconds
(9/13) Running minio-java tests ... FAILED in 18 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 1565,
  "status": "FAIL",
  "error": "java.io.EOFException: input contained no data >>> [org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003), org.xmlpull.mxp1.MXParser.more(MXParser.java:3046), org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410), org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395), org.xmlpull.mxp1.MXParser.next(MXParser.java:1093), com.google.api.client.xml.Xml.parseElementInternal(Xml.java:245), com.google.api.client.xml.Xml.parseElement(Xml.java:222), io.minio.messages.XmlEntity.parseXml(XmlEntity.java:75), io.minio.messages.ErrorResponse.parseXml(ErrorResponse.java:159), io.minio.messages.ErrorResponse.<init>(ErrorResponse.java:64), io.minio.MinioClient.executeReq(MinioClient.java:1135), io.minio.MinioClient.execute(MinioClient.java:1056), io.minio.MinioClient.executePut(MinioClient.java:1399), io.minio.MinioClient.executePut(MinioClient.java:1421), io.minio.MinioClient.putObject(MinioClient.java:3986), io.minio.MinioClient.putObject(MinioClient.java:4029), io.minio.MinioClient.putObject(MinioClient.java:3570), FunctionalTest.listObject_test5(FunctionalTest.java:1493), FunctionalTest.runTests(FunctionalTest.java:3018), FunctionalTest.main(FunctionalTest.java:3154)]"
}

Executed 8 out of 13 tests successfully.
```
<a name="5162cea9-4819-46cf-8845-1656bbbf3766"></a>
### 7192-0090511/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30592
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ae34882fbbd0:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-a0l6f24tz4uwwv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 230,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:30592/aws-sdk-go-test-a0l6f24tz4uwwv: dial tcp 72.28.97.54:30592: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="5669ee67-8577-47fd-841e-52224be47c1d"></a>
### 7192-0090511/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30076
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 80d7e49939a3:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-rllwx2m0rz6lfs",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 338,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30076/aws-sdk-go-test-rllwx2m0rz6lfs: dial tcp 72.28.97.55:30076: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="34e07b01-0dca-471a-98f7-0307e6ff4136"></a>
### 7192-0090511/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31256
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2be9d46f9c50:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-45m9trevrkju0t",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 352,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:31256/aws-sdk-go-test-45m9trevrkju0t: dial tcp 72.28.97.54:31256: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="60df0073-9753-4c77-9c50-4f8c74f207bb"></a>
### 7192-0090511/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31537
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cc8e0f61922f:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mj6m1s6y03xwz9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 340,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:31537/aws-sdk-go-test-mj6m1s6y03xwz9: dial tcp 72.28.97.60:31537: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="b778718b-1d90-4d36-bcb7-4746c0b4c815"></a>
### 7192-0090511/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30174
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d8948d36a174:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-ee6ea86aeb11",
    "file_name": "datafile-1-MB"
  },
  "duration": 22.38,
  "error": "Connection reset by peer",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```
<a name="975f6525-7aec-4053-ade6-1f9ee996982f"></a>
### 7192-0090511/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32092
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9737c90b94aa:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-f4du91m4j70nrmmpzd1p7yf2zfyv8f6p8j1h52mbbs3cyfoioemssy9",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 271,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:32092/bucket-f4du91m4j70nrmmpzd1p7yf2zfyv8f6p8j1h52mbbs3cyfoioemssy9: dial tcp 72.28.97.61:32092: connect: connection refused",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="913ab368-f78a-4ad9-8c67-f752dfa46926"></a>
### 7192-0090511/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32210
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6c57efef68c7:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-al6qnlwgx3eszi",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 351,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.58:32210/aws-sdk-go-test-al6qnlwgx3eszi: dial tcp 72.28.97.58:32210: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="e0a6846c-bc56-4536-9883-7296eb9d4a4f"></a>
### 7192-0090511/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31122
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 86481b9c20a0:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 2 seconds
(5/13) Running awscli tests ... done in 43 seconds
(6/13) Running mc tests ... done in 17 seconds
(7/13) Running minio-dotnet tests ... done in 2 minutes and 30 seconds
(8/13) Running minio-go tests ... done in 14 seconds
(9/13) Running minio-java tests ... done in 42 seconds
(10/13) Running minio-js tests ... FAILED in 23 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-a0cd547e-94e3-4d60-b16e-8d7407934d03, events: s3:ObjectCreated:*",
  "duration": 20052,
  "status": "FAIL",
  "error": "Error: connect ECONNREFUSED 72.28.97.61:31122 at Object.exports._errnoException (util.js:1020:11) at exports._exceptionWithHostPort (util.js:1043:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"
}

Executed 9 out of 13 tests successfully.
```

**Comment by krishnasrinivas** [comment]
I have marked this WIP as there is discussion going on to allow multiple targets.

**Comment by krishnasrinivas** [comment]
Closing this, as we will be supporting multiple notification targets using a different approach to config format.

**Pull request closed without merging**
