### PR TITLE
Fix goroutine test fatalf

### PR DESCRIPTION
**Pull request by leitzler**
## Description
This PR replaces `t.Fatal` and `t.Fatalf` with `t.Error` and `t.Errorf` when called from within a goroutine.

## Motivation and Context
`t.Fatal` and `t.Fatalf` must be called from the same goroutine running the Test function, see https://godoc.org/testing#T.

## How Has This Been Tested?
`make test`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
what bug does this fix @leitzler ?

**Comment by leitzler** [comment]
Several tests that isn’t working as intended since they call `t.Fatalf` from within a goroutine that isn’t the one executing the test. That won’t work.
But since the tests pass right now it’s not visible.

**Comment by leitzler** [comment]
Check out the docs link I provided in the description. `t.Error` is ok to call from multiple goroutines, `t.Fatal` (and others that is supposed to fail fast) isn’t ok.

**Comment by harshavardhana** [comment]
> everal tests that isn’t working as intended since they call `t.Fatalf` from within a goroutine that isn’t the one executing the test. That won’t work.
> But since the tests pass right now it’s not visible.

Why would they not work? I don't see a CI issue at this moment this PR fixes. Are you saying this is an improvement?

**Comment by leitzler** [comment]
Yes, if a bug is introduced here the bug (in the tests) will show.

**Comment by leitzler** [comment]
They won’t work since `t.Fatal` is supposed to fail fast, and end the test running. It won’t when called from a spawned goroutine.

**Review by balamurugana — CHANGES_REQUESTED** [review]
@leitzler 
> They won’t work since `t.Fatal` is supposed to fail fast, and end the test running. It won’t when called from a spawned goroutine.

`t.Fatalf()` is cautiously used to fail fast in goroutines.  As there is no problem seen so far with this code, I couldn't able to see why this chance is required.

If you provide a separate test program why bad to use `f.Fatalf()` in goroutine is better.

**Comment by kannappanr** [comment]
@balamurugana There are other projects where they have done this

https://github.com/golang/go/issues/17900

https://github.com/ipfs/go-ipfs/issues/2043

**Comment by balamurugana** [comment]
@kannappanr Why aren't we facing those issues?

**Comment by leitzler** [comment]
@balamurugana That code is only executed if a test fails. And there are no failing tests now.

**Comment by balamurugana** [comment]
@leitzler What will happen on failure?

**Comment by leitzler** [comment]
The change is submitted to increase overall code quality (you could see it as a part of issue #4812), since the documentation clearly states that:
> A test ends when its Test function returns or calls any of the methods FailNow, Fatal, Fatalf, SkipNow, Skip, or Skipf. Those methods, as well as the Parallel method, must be called only from the goroutine running the Test function.

Maintaining good code quality will minimize the risk of introducing new bugs, and will make it easier for new contributors to understand the code.

This PR will not alter the behavior. A common and idiomatic way to handle this is to have an error channel that the goroutine communicates the error from, but that is another change. First of all the code should do what is says, then additional improvement can be added.

Here is an narrowed down concrete example:
```go
package main

import (
	"testing"
	"time"
)

func TestHelloWorld(t *testing.T) {
	go func() {
		t.Fatal("Fail")
	}()

	time.Sleep(time.Second)

	t.Log("This line should not be called since the purpose of Fatal is to fail fast")
}
```

```bash
$ go test . 
--- FAIL: TestHelloWorld (1.00s)
    main_test.go:11: Fail
    main_test.go:16: This line should not be called since the purpose of Fatal is to fail fast
FAIL
FAIL	_/tmp/test	1.003s
```

**Comment by balamurugana** [comment]
Previously I encountered that `testing.T` was not thread-safe and had custom `fail()` function (unfortunately I couldn't able to find in the current master).  In later time, `testing.T` doesn't show up.  Hence `bufconn_test.go` (As I wrote consciously) used `t.Fatal()` in goroutines.

I consider this PR is trying to deal with `testing.T` thread safety, but replacing `t.Fatal()` with `t.Error()` is insufficient i.e. `t.Fatal()` stops executing next checks.  This needs to be handled correctly in this PR.

**Comment by leitzler** [comment]
You are indeed right, it does alter the behaviour in the case that the goroutine will continue. But calling `t.Fatal` won't stop the test as it is supposed to when called from a goroutine. That's why the documentation states that you **must not** use it that way, it doesn't work.

I could add returns after `t.Error` calls within goroutines, then the behaviour won't change but the code will actually do what it says. If you truly want a fail fast behaviour the tests must be redesigned. This PR only solves the fact that the code doesn't do what it says since it is used in an incorrect way.

**Review by balamurugana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by harshavardhana — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]

**Pull request merged**
