### PR TITLE
Expose total and available disk space

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Expose total and available disk space

## Motivation and Context
Expose more values

## Regression
No

## How Has This Been Tested?
Just call madmin.ServerInfo() API

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#6ed3fa1f-fcad-4a19-8731-33158a20ed80) |
| mint-large-bucket.sh | :x: [more...](#c300761c-2497-4880-bd36-1dbc5e9cbc69) |
| mint-compression-dist-xl.sh | :x: [more...](#c8612137-3906-40fc-99d7-367e63a9bf18) |
| mint-dist-xl.sh | :x: [more...](#0d6a66d7-008d-40bc-8e6b-fedf87f1ce33) |
<a name="6ed3fa1f-fcad-4a19-8731-33158a20ed80"></a>
### 7453-5438625/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32541
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 55b56a0a446e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-u41j9rcqaspits",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 330,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:32541/aws-sdk-go-test-u41j9rcqaspits: dial tcp 72.28.97.54:32541: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0d6a66d7-008d-40bc-8e6b-fedf87f1ce33"></a>
### 7453-5438625/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31153
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cca8d5542479:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-xvzbzutsml0zdz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 350,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:31153/aws-sdk-go-test-xvzbzutsml0zdz: dial tcp 72.28.97.60:31153: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c300761c-2497-4880-bd36-1dbc5e9cbc69"></a>
### 7453-5438625/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32545
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 31bcadb3197c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 minutes and 2 seconds
(2/14) Running aws-sdk-java tests ... FAILED in 51 seconds
com.amazonaws.services.s3.model.AmazonS3Exception: Server not initialized, please try again. (Service: Amazon S3; Status Code: 503; Error Code: XMinioServerNotInitialized; Request ID: 15917709A87ECA16; S3 Extended Request ID: 15917709A87ECA16), S3 Extended Request ID: 15917709A87ECA16
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4330)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4277)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1025)
	at io.minio.awssdk.tests.FunctionalTests.initTests(Unknown Source)
	at io.minio.awssdk.tests.FunctionalTests.main(Unknown Source)

Executed 1 out of 14 tests successfully.
```
<a name="c8612137-3906-40fc-99d7-367e63a9bf18"></a>
### 7453-5438625/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32576
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 79bb3c973f4a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 29 seconds
(8/14) Running minio-dotnet tests ... done in 41 seconds
(9/14) Running minio-go tests ... done in 53 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 3 seconds
(11/14) Running minio-js tests ... done in 39 seconds
(12/14) Running minio-py tests ... done in 3 minutes and 47 seconds
(13/14) Running s3cmd tests ... FAILED in 1 seconds
{
  "name": "s3cmd",
  "duration": "447",
  "function": "test_put_object",
  "status": "FAIL",
  "error": "\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  following lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nInvoked as: /usr/local/bin/s3cmd --config /tmp/.s3cmd-6391/s3cfg rm s3://s3cmd-test-bucket-4472/s3cmd-test-object-13144\nProblem: <class 'OSError: [Errno 113] No route to host\nS3cmd:   2.0.2\npython:   3.5.2 (default, Nov 12 2018, 13:43:14) \n[GCC 5.4.0 20160609]\nenvironment LANG=C.UTF-8\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 3092, in <module>\n    rc = main()\n  File \"/usr/local/bin/s3cmd\", line 3001, in main\n    rc = cmd_func(args)\n  File \"/usr/local/bin/s3cmd\", line 639, in cmd_object_del\n    rc = subcmd_object_del_uri(uri_str)\n  File \"/usr/local/bin/s3cmd\", line 766, in subcmd_object_del_uri\n    response = s3.object_delete(S3Uri(item['object_uri_str']))\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 759, in object_delete\n    response = self.send_request(request)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 1258, in send_request\n    conn = ConnMan.get(self.get_hostname(resource['bucket']))\n  File \"/usr/local/lib/python3.5/dist-packages/S3/ConnMan.py\", line 253, in get\n    conn.c.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 849, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n  File \"/usr/lib/python3.5/socket.py\", line 711, in create_connection\n    raise err\n  File \"/usr/lib/python3.5/socket.py\", line 702, in create_connection\n    sock.connect(sa)\nOSError: [Errno 113] No route to host\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  above lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
}

Executed 12 out of 14 tests successfully.
```

**Review by nitisht — CHANGES_REQUESTED** [review]
Total space shows up as `0` on FS instance (both using Prometheus and madmin.ServerInfo())

```
# HELP minio_disk_storage_total_bytes Total disk space seen by Minio server instance
# TYPE minio_disk_storage_total_bytes gauge
minio_disk_storage_total_bytes 0
# HELP minio_disk_storage_used_bytes Total disk storage used by current Minio server instance
# TYPE minio_disk_storage_used_bytes gauge
minio_disk_storage_used_bytes 20574
```

**Comment by harshavardhana** [comment]
The reason is I didn't change FS mode @nitisht should be fixed now.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by nitisht — COMMENTED** [review]
LGTM & Tested. 

Can we update the Prometheus and madmin docs as well

**Comment by harshavardhana** [comment]
> Can we update the Prometheus and madmin docs as well

That is not part of this PR needs to be sent here https://github.com/minio/cookbook/blob/master/docs/how-to-monitor-minio-with-prometheus.md

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#b1ee625b-fa20-4e19-8b28-8c43d25cbd70) |
| mint-large-bucket.sh | :x: [more...](#6437f758-159e-4008-977b-7947a50220ee) |
| mint-compression-dist-xl.sh | :x: [more...](#b7b7f2f7-4dcd-47f1-a295-34b34efa63a4) |
| mint-dist-xl.sh | :x: [more...](#7c695041-a6e3-4969-bae1-f0ac0de012ca) |
<a name="7c695041-a6e3-4969-bae1-f0ac0de012ca"></a>
### 7453-9ceed05/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30611
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5cff760204d8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-icywohj5xjzmph",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3056,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30611/aws-sdk-go-test-icywohj5xjzmph: dial tcp 72.28.97.57:30611: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="b7b7f2f7-4dcd-47f1-a295-34b34efa63a4"></a>
### 7453-9ceed05/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32571
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a98c1ce720f2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-3wjz0xpxigr4jx",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 237,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:32571/aws-sdk-go-test-3wjz0xpxigr4jx: dial tcp 72.28.97.60:32571: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="b1ee625b-fa20-4e19-8b28-8c43d25cbd70"></a>
### 7453-9ceed05/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30028
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a228c5b3e2f4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-u15d34ef4spfd1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120292,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30028/aws-sdk-go-test-u15d34ef4spfd1: dial tcp 72.28.97.60:30028: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="6437f758-159e-4008-977b-7947a50220ee"></a>
### 7453-9ceed05/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32091
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1ba85b4c4c1a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-xjva2gzhpqmkdn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360013,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159237F6C5ADCE33, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by nitisht — DISMISSED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#860fb8ea-391b-46f8-aeed-fc059e602411) |
| mint-compression-dist-xl.sh | :x: [more...](#6ac3e183-c971-4eff-bbba-fff9a60dff2c) |
<a name="6ac3e183-c971-4eff-bbba-fff9a60dff2c"></a>
### 7453-afaab2f/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31398
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp af01adefda55:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fhfy5ejsyjt9iz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3071,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31398/aws-sdk-go-test-fhfy5ejsyjt9iz: dial tcp 72.28.97.57:31398: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="860fb8ea-391b-46f8-aeed-fc059e602411"></a>
### 7453-afaab2f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31314
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bafe755cfb3a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-dotnet tests ... done in 32 seconds
(9/14) Running minio-go tests ... done in 51 seconds
(10/14) Running minio-java tests ... done in 3 minutes and 39 seconds
(11/14) Running minio-js tests ... done in 40 seconds
(12/14) Running minio-py tests ... FAILED in 8 minutes and 51 seconds
{
  "duration": 209,
  "status": "FAIL",
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "bucket_name": "minio-py-test-406e9e92-7c13-407b-a538-3aa7acc1a54d",
    "object_name": "cb6f6ad5-47da-4e97-b51b-72e518b2efb7"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "name": "minio-py:test_presigned_get_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```

**Review by wlan0 — APPROVED** [review]

**Review by nitisht — APPROVED** [review]

**Pull request merged**
