### PR TITLE
Merge versions across sets when listing

### PR DESCRIPTION
**Pull request by klauspost**
## Description

This is to compensate for the same object being placed in multiple server pools, if a transient error occurred when updating.

Merge all versions found.

## How to test this PR?

Upload different versions to different server pools.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#70906581-e2a3-427f-8837-af168f11568f) |
<a name="70906581-e2a3-427f-8837-af168f11568f"></a>
### 16003-4ab203a/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:31866
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp f2749c3fd14e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... FAILED in 1 seconds
Nov 04, 2022 3:51:33 PM com.amazonaws.util.Base64 warn
WARNING: JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided) (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 17246C8819E086F9; S3 Extended Request ID: c9521c55-1831-4890-a0e2-40bce92e61e0), S3 Extended Request ID: c9521c55-1831-4890-a0e2-40bce92e61e0
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1347)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4992)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:895)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:863)
	at io.minio.awssdk.tests.FunctionalTests.teardown(Unknown Source)
	at io.minio.awssdk.tests.FunctionalTests.main(Unknown Source)
(2/14) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-636535060fbf9",
    "Object": "obj1"
  },
  "duration": "428",
  "status": "FAIL",
  "error": "Error executing \"ListObjects\" on \"http://15.15.15.3:31866/aws-sdk-php-636535060fbf9?encoding-type=url\"; AWS HTTP error: Server error: `GET http://15.15.15.3:31866/aws-sdk-php-636535060fbf9?encoding-type=url` resulted in a `500 Internal Server Error` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InternalError</Code><Message>We encountered an internal error, pleas (truncated...)\n InternalError (server): We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided) - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)</Message><BucketName>aws-sdk-php-636535060fbf9</BucketName><Resource>/aws-sdk-php-636535060fbf9</Resource><RequestId>17246C884F6991D4</RequestId><HostId>c9521c55-1831-4890-a0e2-40bce92e61e0</HostId></Error>"
}
(2/14) Running aws-sdk-ruby tests ... done in 7 seconds
(3/14) Running awscli tests ... FAILED in 35 seconds
{
  "name": "awscli",
  "duration": 11019,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete_bucket for test_max_key_list failed"
}
(3/14) Running healthcheck tests ... done in 0 seconds
(4/14) Running mc tests ... FAILED in 26 seconds
{
  "name": "mc",
  "duration": "5906",
  "function": "test_mv_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-9911 --quiet --no-color stat myminio/mc-test-bucket-18579/dir-28035-29334/object-2  >>> \nmc: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\nmc: <ERROR> Unable to stat `myminio/mc-test-bucket-18579/dir-28035-29334/object-2`. "
}
(4/14) Running minio-go tests ... FAILED in 1 minutes and 2 seconds
{
  "args": {
    "bucketName": "minio-go-test-wj2uylzdmih5qqaa",
    "objectName": "urt9cjg4ya1wbrbqprlxtwlv9lmgp9"
  },
  "duration": 3946,
  "error": "We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)",
  "function": "GetObject(bucketName, objectName)",
  "message": "CleanupBucket failed",
  "name": "minio-go: testGetObjectReadSeekFunctional",
  "status": "FAIL"
}
(4/14) Running minio-java tests ... done in 44 seconds
(5/14) Running minio-js tests ... FAILED in 12 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 11,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(5/14) Running minio-py tests ... done in 1 minutes and 52 seconds
(6/14) Running s3cmd tests ... done in 34 seconds
(7/14) Running s3select tests ... done in 5 seconds
(8/14) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-z4wyjdj9lu50a5",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 615,
  "error": "InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 17246CD6E49092F2, host id: ",
  "function": "/mint/build/versioning/put.go:103: main.testPutObject",
  "message": "PUT expected to succeed but got InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 17246CD6E49092F2, host id: ",
  "name": "versioning",
  "status": "FAIL"
}

Executed 7 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by poornas** [comment]
With this PR, still dont see versions getting merged across pools - have a 2 pool setup with 3 versions of the same object in one pool and a delete marker, object version in second pool. The second pool's versions are not listed - verified the second pool has same signature across each disk in that pool
```
~ tree -a /tmp/multisitea/data/disterasure/xl*/bucket/bin/a2
/tmp/multisitea/data/disterasure/xl1/bucket/bin/a2
└── xl.meta
/tmp/multisitea/data/disterasure/xl2/bucket/bin/a2
└── xl.meta
/tmp/multisitea/data/disterasure/xl3/bucket/bin/a2
└── xl.meta
/tmp/multisitea/data/disterasure/xl4/bucket/bin/a2
└── xl.meta
/tmp/multisitea/data/disterasure/xl5/bucket/bin/a2
└── xl.meta
/tmp/multisitea/data/disterasure/xl6/bucket/bin/a2
└── xl.meta
/tmp/multisitea/data/disterasure/xl7/bucket/bin/a2
└── xl.meta
/tmp/multisitea/data/disterasure/xl8/bucket/bin/a2
└── xl.meta

0 directories, 8 files
➜  ~ xl-meta /tmp/multisitea/data/disterasure/xl5/bucket/bin/a2/xl.meta
{
  "Versions": [
    {
      "Header": {
        "Flags": 0,
        "ModTime": "2022-11-04T08:51:14.238256985-07:00",
        "Signature": "386cc1f5",
        "Type": 2,
        "VersionID": "7367d311e2b549b5b91c6b20ec02e5dc"
      },
      "Idx": 0,
      "Metadata": {
        "DelObj": {
          "ID": "c2fTEeK1SbW5HGsg7ALl3A==",
          "MTime": 1667577074238256985,
          "MetaSys": {}
        },
        "Type": 2,
        "v": 0
      }
    },
    {
      "Header": {
        "Flags": 6,
        "ModTime": "2022-11-03T23:20:49.098410588-07:00",
        "Signature": "f4aa0c71",
        "Type": 1,
        "VersionID": "f0b16f1cbe42458bb82cc29e82340c89"
      },
      "Idx": 1,
      "Metadata": {
        "Type": 1,
        "V2Obj": {
          "CSumAlgo": 1,
          "DDir": "oqgbg/NnT2mCvHl6DHzfcw==",
          "EcAlgo": 1,
          "EcBSize": 1048576,
          "EcDist": [
            1,
            2,
            3,
            4
          ],
          "EcIndex": 1,
          "EcM": 2,
          "EcN": 2,
          "ID": "8LFvHL5CRYu4LMKegjQMiQ==",
          "MTime": 1667542849098410588,
          "MetaSys": {
            "x-minio-internal-inline-data": "dHJ1ZQ=="
          },
          "MetaUsr": {
            "content-type": "application/octet-stream",
            "etag": "1e0f0a891c768b80861f5d1f7d097dfa"
          },
          "PartASizes": [
            26
          ],
          "PartETags": null,
          "PartNums": [
            1
          ],
          "PartSizes": [
            26
          ],
          "Size": 26
        },
        "v": 0
      }
    }
  ]
}
  ~ xl-meta /tmp/multisitea/data/disterasure/xl4/bucket/bin/a2/xl.meta 
{
  "Versions": [
    {
      "Header": {
        "Flags": 6,
        "ModTime": "2022-11-03T23:17:35.085850587-07:00",
        "Signature": "ee6a77a8",
        "Type": 1,
        "VersionID": "143e76380a6b46e38340f08fca62b4d4"
      },
      "Idx": 0,
      "Metadata": {
        "Type": 1,
        "V2Obj": {
          "CSumAlgo": 1,
          "DDir": "5/eotxPFSI+BWoUIhkd4SQ==",
          "EcAlgo": 1,
          "EcBSize": 1048576,
          "EcDist": [
            1,
            2,
            3,
            4
          ],
          "EcIndex": 4,
          "EcM": 2,
          "EcN": 2,
          "ID": "FD52OAprRuODQPCPymK01A==",
          "MTime": 1667542655085850587,
          "MetaSys": {
            "x-minio-internal-inline-data": "dHJ1ZQ=="
          },
          "MetaUsr": {
            "content-type": "application/octet-stream",
            "etag": "1e0f0a891c768b80861f5d1f7d097dfa"
          },
          "PartASizes": [
            26
          ],
          "PartETags": null,
          "PartNums": [
            1
          ],
          "PartSizes": [
            26
          ],
          "Size": 26
        },
        "v": 0
      }
    },
    {
      "Header": {
        "Flags": 6,
        "ModTime": "2022-11-03T23:17:26.830697732-07:00",
        "Signature": "e2d67d7b",
        "Type": 1,
        "VersionID": "6f81e426fdcc4798bf1c6ec0652d1dc9"
      },
      "Idx": 1,
      "Metadata": {
        "Type": 1,
        "V2Obj": {
          "CSumAlgo": 1,
          "DDir": "q6VGj48HR+GVlub8jN29zw==",
          "EcAlgo": 1,
          "EcBSize": 1048576,
          "EcDist": [
            1,
            2,
            3,
            4
          ],
          "EcIndex": 4,
          "EcM": 2,
          "EcN": 2,
          "ID": "b4HkJv3MR5i/HG7AZS0dyQ==",
          "MTime": 1667542646830697732,
          "MetaSys": {
            "x-minio-internal-inline-data": "dHJ1ZQ=="
          },
          "MetaUsr": {
            "content-type": "application/octet-stream",
            "etag": "1e0f0a891c768b80861f5d1f7d097dfa"
          },
          "PartASizes": [
            26
          ],
          "PartETags": null,
          "PartNums": [
            1
          ],
          "PartSizes": [
            26
          ],
          "Size": 26
        },
        "v": 0
      }
    },
    {
      "Header": {
        "Flags": 6,
        "ModTime": "2022-11-03T23:17:10.67239446-07:00",
        "Signature": "385fc71d",
        "Type": 1,
        "VersionID": "2e13c6e3f3dc40c3a5e746364967c86b"
      },
      "Idx": 2,
      "Metadata": {
        "Type": 1,
        "V2Obj": {
          "CSumAlgo": 1,
          "DDir": "alwxCuOlSx+Dc1iRi7tPPw==",
          "EcAlgo": 1,
          "EcBSize": 1048576,
          "EcDist": [
            1,
            2,
            3,
            4
          ],
          "EcIndex": 4,
          "EcM": 2,
          "EcN": 2,
          "ID": "LhPG4/PcQMOl50Y2SWfIaw==",
          "MTime": 1667542630672394460,
          "MetaSys": {
            "x-minio-internal-inline-data": "dHJ1ZQ=="
          },
          "MetaUsr": {
            "content-type": "application/octet-stream",
            "etag": "1e0f0a891c768b80861f5d1f7d097dfa"
          },
          "PartASizes": [
            26
          ],
          "PartETags": null,
          "PartNums": [
            1
          ],
          "PartSizes": [
            26
          ],
          "Size": 26
        },
        "v": 0
      }
    }
  ]
}

 mc ls sitea/bucket -r -versions
[2022-11-03 23:17:35 PDT]    26B STANDARD 143e7638-0a6b-46e3-8340-f08fca62b4d4 v3 PUT bin/a2
[2022-11-03 23:17:26 PDT]    26B STANDARD 6f81e426-fdcc-4798-bf1c-6ec0652d1dc9 v2 PUT bin/a2
[2022-11-03 23:17:10 PDT]    26B STANDARD 2e13c6e3-f3dc-40c3-a5e7-46364967c86b v1 PUT bin/a2

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by poornas — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#f7874b1e-da47-4af1-be9f-74640051d7fe) |
<a name="f7874b1e-da47-4af1-be9f-74640051d7fe"></a>
### 16003-ac19f77/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.21:30528
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp c9d6bf2a9485:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 0 seconds
(9/14) Running minio-java tests ... FAILED in 31 seconds
{
  "name": "minio-java",
  "function": "getObjectRetention()",
  "duration": 69,
  "status": "FAIL",
  "error": "java.time.format.DateTimeParseException: Text '2022-11-07T17:28:44.8Z' could not be parsed at index 19 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioAsyncClient.lambda$getObjectRetention$35(MinioAsyncClient.java:1738), java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642), java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506), java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073), io.minio.S3Base$1.onResponse(S3Base.java:559), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 52 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 40 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
