### PR TITLE
Avoid modifying object layer after initialization

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Avoid modifying object layer after initialization

## Motivation and Context
Keep reflection-less code and move loading bucket policies
and initialize event nofitier into each object layer
initialization.

## How Has This Been Tested?
Manually, code cleanup

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#ff7be272-6abf-4122-9ce7-93041992d0f8) |
<a name="ff7be272-6abf-4122-9ce7-93041992d0f8"></a>
### 5529-ed6c166/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31141
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp c9c5c58818c7:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-way5j5rugh9xso",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 378,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:31141/aws-sdk-go-test-way5j5rugh9xso: dial tcp 192.168.122.45:31141: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#1b0f558b-ab66-436c-88e7-8f9c4a788a75) |
| mint-gateway-azure.sh | :x: [more...](#2de5a2eb-7dca-4269-8fa3-6c29c08eca2c) |
<a name="1b0f558b-ab66-436c-88e7-8f9c4a788a75"></a>
### 5529-5993d32/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30676
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp d28af9c954b5:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ehvwcbgcuoxgmt",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 363,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30676/aws-sdk-go-test-ehvwcbgcuoxgmt: dial tcp 192.168.122.45:30676: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```
<a name="2de5a2eb-7dca-4269-8fa3-6c29c08eca2c"></a>
### 5529-5993d32/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32114
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 03ba5b4bb9bd:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 3 minutes and 56 seconds
(3/12) Running aws-sdk-ruby tests ... done in 55 seconds
(4/12) Running awscli tests ... FAILED in 2 minutes and 6 seconds
{
  "name": "awscli",
  "duration": 9860,
  "function": "aws --endpoint-url http://minikube:32114 s3api put-object --body /mint/data/datafile-1-MB --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key datafile-1-MB\n",
  "status": "FAIL",
  "error": "usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"
}

Executed 3 out of 12 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#5d8c9d0e-41e1-4577-9798-01503b23d805) |
<a name="5d8c9d0e-41e1-4577-9798-01503b23d805"></a>
### 5529-f105c38/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30969
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 77eb79db7a2f:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-z9el9cztnymx11",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 371,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30969/aws-sdk-go-test-z9el9cztnymx11: dial tcp 192.168.122.45:30969: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

**Review by poornas — APPROVED** [review]
LGTM.

**Comment by harshavardhana** [comment]
Already merged closing.

**Pull request closed without merging**
