### PR TITLE
Removing Azure, GCS, HDFS gateway implementations

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Removing Azure, GCS, HDFS gateway implementations

## Motivation and Context
refer #14331

## How to test this PR?
Nothing spectacular to test. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by harshavardhana** [comment]
No need for review yet on this PR since this shall be merged by end of May.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
A new branch is created to pour in all the PRs to merge the new change.

**Comment by nawa** [comment]
@harshavardhana what is the reason of removing them? We are very interesting in using Azure gateway

**Comment by harshavardhana** [comment]
> @harshavardhana what is the reason of removing them? We are very interesting in using Azure gateway

Please read https://blog.min.io/deprecation-of-the-minio-gateway/

**Comment by meirsegev** [comment]
Hi,

Will I be able to use older versions which support gcs as docker image ?
I mean to use the "docker pull minio/minio:RELEASE.2022-04-16T04-26-02Z.fips"
Will it continue work in the future or the minio docker-hub will delete those versions ?

**Comment by harshavardhana** [comment]
> Will I be able to use older versions which support gcs as docker image ?

yes

**Comment by zxl7049** [comment]
Removing Azure, GCS, HDFS gateway 。but I want use HDFS gateway, How to download historical  minio versions

**Comment by mbmcmullen27** [comment]
Also wondering this ^^ What's the latest release version that still had the azure gateway?

**Pull request merged**
