### PR TITLE
Allow creating a delete marker in a suspended prefix

### PR DESCRIPTION
**Pull request by vadmeste**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Fix delete marker creation when only a prefix is supended.

Both DeleteObject and DeleteObjects handlers are affected here

## How to test this PR?
Create a versioned bucket then,
```
mc mb myminio/testbucket --with-versioning
mc cp go.mod myminio/testbucket/
mc version enable myminio/testbucket --excluded-prefixes "*"
mc rm myminio/testbucket/go.mod
mc rm myminio/testbucket/go.mod
```
go.mod is still visible

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by klauspost** [comment]
Context?

**Comment by vadmeste** [comment]
>  Context?

I updated this ticket comments, I wanted to test our CI/CD before marking this PR as ready

**Comment by harshavardhana** [comment]
wait why is this needed?

**Comment by harshavardhana** [comment]
Closing this PR, as its not needed. This PR will over extend our implementation with no extra benefits. Check the slack conversation.

**Pull request closed without merging**
