### PR TITLE
Fixing Sia file uploads

### PR DESCRIPTION
**Pull request by mtlynch**
## Description

This adds a goroutine that watches the file upload progress and doesn't delete the file until the upload reaches 100% complete.

Note that this solution has the limitation where if the minio process dies in the middle of upload, it will leave orphaned files in the `SIA_TEMP` directory that the user will need to remove manually.

## Motivation and Context

The Sia gateway had a bug with uploading that prevented the user's uploads from reaching the Sia backend. The `PutObject` function called `fsRemoveFile` at the end of the function, which didn't give the Sia backend enough time to upload the file to the Sia network.

## How Has This Been Tested?

Tested by manually uploading files under Ubuntu16.04 LTS with the latest Sia source.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — DISMISSED** [review]
LGTM

**Comment by mtlynch** [comment]
Whoops, sorry, I didn't realize that the one-line fix would invalidate the review.

**Review by krisis — DISMISSED** [review]

**Comment by nitisht** [comment]
@mtlynch can you please resolve the conflicts here

**Comment by mtlynch** [comment]
>@mtlynch can you please resolve the conflicts here

done

**Comment by nitisht** [comment]
> done

Thanks!

**Review by harshavardhana — APPROVED** [review]

**Review by krisis — APPROVED** [review]

**Pull request merged**
