### PR TITLE
optimize max-keys=2 listing for spark workloads

### PR DESCRIPTION
**Pull request by poornas**
to return results appropriately for versioned buckets, especially when underlying prefixes have been deleted

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Motivation and Context
solve partitioned overwrite issues in versioned buckets for spark/hadoop workloads using minio as object store  - prefixes in deleted state should not be returned in the result for calls similar to this:
```
 GET /warehouse/?list-type=2&delimiter=%2F&max-keys=2&prefix=partition%2Fnyc_taxis%2Fdata.parquet%2F_temporary%2F0%2Ftask_202405120118115803861317163525099_0000_m_000000%2F&fetch-owner=false
```

## How to test this PR?
run a spark+hive+minio job on a versioned bucket
https://github.com/minio/openlake/tree/main/spark/partition-test

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by harshavardhana** [comment]
Can we run the code when we are running mint tests?

**Comment by poornas** [comment]
> Can we run the code when we are running mint tests?

we may be able to do this in minio-go by setting a custom user agent

**Comment by harshavardhana** [comment]
> we may be able to do this in minio-go by setting a custom user agent

okay cool, we should do that @poornas IMO.

**Review by klauspost — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
Will merge this PR however can we please add a unit test atleast @poornas ? 

It sounds like TestListObjects() would be the right place.

**Pull request merged**
