### PR TITLE
Preallocate space before append to avoid disk full error

### LINKED ISSUE #2194: [distributed] fallocate/fadvise to provide hint for I/O
Under `CompleteMultipartUpload` we should use fallocate/fadvise when available to allocate disk space.

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #2194 

Please do not merge immediately under considered really stable.

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
we do AppendFile in 128K chunks so Fallocate at posix won't be helpful.

**Comment by harshavardhana** [comment]
> we do AppendFile in 128K chunks so Fallocate at posix won't be helpful.

Perhaps if posix knows what will be the final size..

**Comment by vadmeste** [comment]
> we do AppendFile in 128K chunks so Fallocate at posix won't be helpful.

yeah, I noticed that.. actually I suggested to add a new func PrepareFile() in storage-interface for this purpose, but the way why it is 128K, couldn't we increase it ?

**Comment by harshavardhana** [comment]
> yeah, I noticed that.. actually I suggested to add a new func PrepareFile() in storage-interface for this purpose, but the way why it is 128K, couldn't we increase it ?

It something coming from erasure itself, because of the block size i.e 10MB.

**Comment by vadmeste** [comment]
Anyway, as a general rule it is good to use fallocate to make disks less fragmented, fallocate() is really fast

**Comment by krishnasrinivas** [comment]
> Anyway, as a general rule it is good to use fallocate to make disks less fragmented, fallocate() is really fast

if you write() 128k in one go the FS implementations make sure that it's not fragmented. so in this situation fallocate will not help. If you write in smaller chunks say 4K with time gap between the writes then it will lead to fragmentation (in that situation fallocate will help)

**Comment by harshavardhana** [comment]
Can this patch be rebased? @vadmeste

**Comment by krishnasrinivas** [comment]
> Can this patch be rebased? @vadmeste

@harshavardhana this commit is not adding value, check the discussion above

**Comment by harshavardhana** [comment]
> @harshavardhana this commit is not adding value, check the discussion above

Yes ended up reading a lot about fallocate, it is not useful for us.  Closing this PR for now.

**Pull request closed without merging**
