### PR TITLE
Handle errs returned with etcd properly for config init and migration

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Handle errs returned with etcd properly for config init and migration

## Motivation and Context
Returning unexpected errors can cause problems for config handling,
which is what led gateway deployments with etcd to misbehave and
had stopped working properly

## Regression
Do not know, maybe

## How Has This Been Tested?
Follow the fresh STS deployment documentation and start the gateway with following params

```
#!/bin/bash

export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export MINIO_ETCD_ENDPOINTS=http://localhost:2379
minio gateway nas ~/test
```

Gateway starts fine but `mc admin config get myminio` would return

```
mc: <ERROR> Cannot get server configuration file. We encountered an internal error, please try again.
 (0) admin-config-get.go:91 cmd.mainAdminConfigGet(..)
 Release-Tag:DEVELOPMENT.2019-01-20T07-25-34Z | Commit:b3167b86134d | Host:backspace | OS:linux | Arch:amd64 | Lang:go1.11.4 | Mem:2.1MB/72MB | Heap:2.1MB/67MB
```

This is because due to a bug we were not creating config.json on fresh deployments leading to config initialization issues.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by poornas — CHANGES_REQUESTED** [review]
was able to repro the error and validate this fix for NAS gateway. A side-effect of fixing this is that we would return empty config for ``` mc admin config get mys3 ``` for other gateways, possibly misleading users into thinking they could manage config for gateways via mc admin. Perhaps we should return a MethodNotAllowed error for non NAS

**Comment by harshavardhana** [comment]
Yes we can @poornas

**Comment by kannappanr** [comment]
It seems to be returning `mc: <ERROR> Cannot get server configuration file. The specified method is not allowed against this resource.` when `etcd` server is not used and `minio` is started in `gateway nas` mode, which is correct

**Comment by harshavardhana** [comment]
Yes that is expected @kannappanr

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
ping @poornas @kannappanr this PR is ready with required changes.

**Review by poornas — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by navossoc** [comment]
So, there is no way to configure `notifications` when using the `gateway` mode?

**Comment by harshavardhana** [comment]
Yes no way @navossoc

**Pull request merged**
