### PR TITLE
Add deploymentID to web handler logs

### PR DESCRIPTION
**Pull request by krisis**
This change makes Web API Handlers log the deploymentID in their logs. 

## Description

The change extends the existing mechanism to add deploymentID and other request related information to the logger entry. 

## Motivation and Context

This would help admins managing logs from multiple MinIO clusters.

## Regression

No

## How Has This Been Tested?

1. Create a Bucket and upload an object to it
2. Open MinIO browser and try deleting the above non-empty bucket
3. MinIO server logs should have an entry like,
```
API: webDeleteBucket()
Time: 14:02:07 PDT 05/29/2019
DeploymentID: b2053bb0-2b9f-49ae-8d7f-0ccc7f4f96f5
RemoteHost: 127.0.0.1
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Error: Bucket not empty: test
       3: cmd/web-handlers.go:1988:cmd.toWebAPIError()
       2: cmd/web-handlers.go:1868:cmd.toJSONError()
       1: cmd/web-handlers.go:283:cmd.(*webAPIHandlers).DeleteBucket()
```
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#3b4816cd-88bc-42f3-947f-7fa30e41a42c) |
| mint-large-bucket.sh | :x: [more...](#2f0b1e29-be45-40c4-830a-2bb64c342aa0) |
| mint-dist-xl.sh | :x: [more...](#997b4b01-3fa7-4079-bce9-36da54c0ba7a) |
<a name="997b4b01-3fa7-4079-bce9-36da54c0ba7a"></a>
### 7712-adbb996/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31349
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 27d40dc4e833:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 51 seconds
(10/14) Running minio-java tests ... FAILED in 30 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 393,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-103mife, objectName=minio-java-test-908399, resource=/minio-java-test-103mife/minio-java-test-908399, requestId=15A3469366C44045, hostId=104d1dd5-1ace-4b11-9936-07f365e504bd)\nrequest={method=DELETE, url=http://72.28.97.60:31349/minio-java-test-103mife/minio-java-test-908399?uploadId=5ca8a2e3-59a1-4601-acca-511e7d463291, headers=Host: 72.28.97.60:31349\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190529T220454Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190529/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-29T21-46-30Z\nVary: Origin\nX-Amz-Request-Id: 15A3469366C44045\nX-Minio-Deployment-Id: 104d1dd5-1ace-4b11-9936-07f365e504bd\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 May 2019 22:04:55 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="2f0b1e29-be45-40c4-830a-2bb64c342aa0"></a>
### 7712-adbb996/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30629
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c5934b5119af:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 4 seconds
(4/14) Running aws-sdk-ruby tests ... done in 21 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 5 seconds
{
  "name": "mc",
  "duration": "89443",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-14020 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-14503  >>> \n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-14503/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-14503/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-14503/datafile-1-b`\n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-14503/datafile-1-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-14503/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-14503/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-14503/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-14503/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-14503/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-14503/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-14503/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-14503/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-14503/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-14503/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-14503/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 585.49 MiB, Speed: 6.55 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="3b4816cd-88bc-42f3-947f-7fa30e41a42c"></a>
### 7712-adbb996/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30909
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d4eccedafbf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-25m3dxcmro5ioo",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360010,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A3469882B58047, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d12f0fe9-25e0-4b70-9af0-4cb765d05082) |
| mint-dist-xl.sh | :x: [more...](#22704ff4-c7cd-4f1d-8124-1d022b09c7b2) |
<a name="d12f0fe9-25e0-4b70-9af0-4cb765d05082"></a>
### 7712-acb7024/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31215
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f0736528b668:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 57 seconds
{
  "name": "mc",
  "duration": "133638",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-11566 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-5261  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-5261/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-5261/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-5261/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-5261/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-5261/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-5261/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-5261/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-5261/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-5261/datafile-100-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-5261/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-5261/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-5261/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-5261/datafile-65-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-5261/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-5261/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 545.81 MiB, Speed: 4.09 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="22704ff4-c7cd-4f1d-8124-1d022b09c7b2"></a>
### 7712-acb7024/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30548
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eb307358074e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 25 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 50 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 54 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 328,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2or56sj, objectName=minio-java-test-1av1aeb, resource=/minio-java-test-2or56sj/minio-java-test-1av1aeb, requestId=15A3480D59F022E0, hostId=67d6a62c-6d1c-4da1-b842-3bb4e1abfa67)\nrequest={method=DELETE, url=http://72.28.97.56:30548/minio-java-test-2or56sj/minio-java-test-1av1aeb?uploadId=8363fa35-4483-4328-9125-3ee3fbb14924, headers=Host: 72.28.97.56:30548\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190529T223158Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190529/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-29T22-10-13Z\nVary: Origin\nX-Amz-Request-Id: 15A3480D59F022E0\nX-Minio-Deployment-Id: 67d6a62c-6d1c-4da1-b842-3bb4e1abfa67\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 May 2019 22:31:58 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#79501aaf-1858-4d2e-911b-c898ddfcf094) |
| mint-large-bucket.sh | :x: [more...](#0777ea51-a2b3-4a2b-b43a-1395fe33e17c) |
| mint-dist-xl.sh | :x: [more...](#4d5b277b-1554-4f62-b99e-1f4a29be7e3d) |
<a name="0777ea51-a2b3-4a2b-b43a-1395fe33e17c"></a>
### 7712-34a491b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31503
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ab9340185e72:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 38 seconds
{
  "name": "mc",
  "duration": "125551",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-8755 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-22740  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-22740/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-22740/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-22740/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-22740/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-22740/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-22740/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-22740/datafile-100-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-22740/datafile-33-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-22740/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-22740/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-22740/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-22740/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-22740/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-22740/datafile-65-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-22740/datafile-11-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 497.74 MiB, Speed: 3.97 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="4d5b277b-1554-4f62-b99e-1f4a29be7e3d"></a>
### 7712-34a491b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32327
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6a53a2f47731:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 28 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 19 seconds
(10/14) Running minio-java tests ... FAILED in 41 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName)",
  "duration": 34,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.51:32327/minio-java-test-2s90371/minio-java-test-jg7psi?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190530%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190530T073629Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=ac97d69bcd296213beda1854cc6e2a3dbbc8bad830a24eb2f4d5590d2689a148}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-jg7psi</Key><BucketName>minio-java-test-2s90371</BucketName><Resource>/minio-java-test-2s90371/minio-java-test-jg7psi</Resource><RequestId>15A365C448677A76</RequestId><HostId>79ae7304-94fd-4817-9523-eaff631199ce</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test1(FunctionalTest.java:1767), FunctionalTest.runTests(FunctionalTest.java:2994), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="79501aaf-1858-4d2e-911b-c898ddfcf094"></a>
### 7712-34a491b/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30355
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d4c8fd7ee2ba:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-m9hcqunqryw0tg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360022,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A365D3E2AD772A, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by nitisht — APPROVED** [review]
LGTM & Tested

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
