### PR TITLE
cache: handle cache cleanup correctly when backend

### LINKED ISSUE #7558: Panic on 404 in B2 Gateway with Disk Cache
When using the `B2` gateway mode and requesting a file that doesn't exist, an internal error is thrown and the client received a socket disconnect.

## Expected Behavior
Returns a 404.

## Current Behavior
1. Hangs up on client.
2. Shows error `http: panic serving 127.0.0.1:36678: runtime error: invalid memory address or nil pointer dereference`

## Steps to Reproduce (for bugs)

1. Deploy a minio instance in gateway mode for B2.
2. Enable disk cache.
3. Request a file that does not exist in a bucket that does exist.

## Your Environment

```
Version: 2019-04-18T01:15:57Z
Release-Tag: RELEASE.2019-04-18T01-15-57Z
Commit-ID: 4c048963dc05edf642538b8bc71588f475854ac6
```

## Full Traceback
```
API: GetObject(bucket=xyz, object=test.txt)
Time: 18:31:32 UTC 04/18/2019
RequestID: 1596A5233E118185
RemoteHost: 127.0.0.1
UserAgent: curl/7.54.0
Error: b2_download_file_by_name: 404: not_found: bucket xyz does not have file: test.txt
       1: cmd/gateway/b2/gateway-b2.go:453:b2.(*b2Objects).GetObjectInfo()
       2: cmd/disk-cache.go:970:cmd.newServerCacheObjects.func2()
       3: cmd/disk-cache.go:198:cmd.cacheObjects.GetObjectNInfo()
       4: cmd/object-handlers.go:333:cmd.objectAPIHandlers.GetObjectHandler()
       5: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
2019/04/18 18:31:32 http: panic serving 127.0.0.1:36686: runtime error: invalid memory address or nil pointer dereference
goroutine 172 [running]:
net/http.(*conn).serve.func1(0xc0003686e0)
	/opt/go/src/net/http/server.go:1769 +0xc9
panic(0x1639a40, 0x2ba9910)
	/opt/go/src/runtime/panic.go:522 +0x1b5
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:829 +0x248
panic(0x1639a40, 0x2ba9910)
	/opt/go/src/runtime/panic.go:522 +0x1b5
github.com/minio/minio/cmd.(*GetObjectReader).Close(0x0, 0xc0004205e0, 0x2bc9640)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-api-utils.go:636 +0x3b
github.com/minio/minio/cmd.cacheObjects.GetObjectNInfo(0xc0000145c0, 0xc0000145e0, 0x0, 0x0, 0x0, 0x190d360, 0x190d350, 0x190d358, 0x190d368, 0x190d370, ...)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/disk-cache.go:203 +0x3c6
github.com/minio/minio/cmd.objectAPIHandlers.GetObjectHandler(0x190d310, 0x190d308, 0xc0001b4a70, 0x1b500a0, 0xc0004201e0, 0xc00020c200)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:333 +0xdb4
net/http.HandlerFunc.ServeHTTP(0xc000028d40, 0x1b500a0, 0xc0004201e0, 0xc00020c200)
	/opt/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001140c0, 0x1b500a0, 0xc0004201e0, 0xc00020c000)
	/q/.q/sources/gopath/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xce
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x1b263a0, 0xc0001140c0, 0x1b4fe20, 0xc0004201c0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:800 +0x1a6
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1b29300, 0xc00022bdf0, 0x1b4fe20, 0xc0004201c0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:815 +0x1f0
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc000014a40, 0x1b29480, 0xc00022be00, 0x1b4fe20, 0xc0004201c0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:643 +0x87
github.com/minio/minio/cmd.rateLimit.ServeHTTP(0xc000245090, 0x1b29280, 0xc000014a60, 0x1b4fe20, 0xc0004201c0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:777 +0x2fa
github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x1b293a0, 0xc000014a80, 0x1b4fe20, 0xc0004201c0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:628 +0x58f
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1b29420, 0xc00022be20, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:552 +0xb5
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1b29340, 0xc00022be30, 0x50004000000, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:71 +0xd0
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1b29400, 0xc000014ac0, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:96 +0x264
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1b293e0, 0xc00022be40, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x81
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1b292e0, 0xc00022be50, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:247 +0x68
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1b293c0, 0xc00022be60, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:305 +0xae
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1b29380, 0xc00022be70, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:274 +0x6d
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1b292a0, 0xc00022be80, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:375 +0x574
github.com/rs/cors.(*Cors).Handler.func1(0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 +0xc2
net/http.HandlerFunc.ServeHTTP(0xc000014b40, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/opt/go/src/net/http/server.go:1995 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1b29fe0, 0xc000014b40, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:503 +0xb9
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1b29460, 0xc00022bf00, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:405 +0x3ba
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x1b29260, 0xc00022bf10, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:850 +0x7c
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1b294a0, 0xc00022bf20, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:139 +0x264
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1b29440, 0xc00022bf30, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:832 +0x8d
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/server.go:126 +0xe7
net/http.HandlerFunc.ServeHTTP(0xc00044a0a0, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/opt/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc00047e280, 0x1b52360, 0xc00001a0e0, 0xc00020c000)
	/opt/go/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc0003686e0, 0x1b58a20, 0xc0005de280)
	/opt/go/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:2884 +0x2f4
```

### PR DESCRIPTION
**Pull request by poornas**
object was deleted.

Fixes: #7558

## Motivation and Context

fixes issue referenced above - cacheReader was being referenced without first checking if the GetObjectNInfo call returned a valid reader
## Regression
 Yes

1d492959431fbd59f4b3164eb563c198a9d03997
## How Has This Been Tested?

1. Run MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 MINIO_CACHE_DRIVES=/tmp/cache ./minio server ~/export
2. Access a object that doesnt exist on cache or backend. Expected to return a 404, was panicking earlier
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f737c2de-337f-4cd6-89e8-772a1f71d860) |
| mint-dist-xl.sh | :x: [more...](#cecc1b13-aba9-4fab-9c2a-b53122050f1d) |
<a name="f737c2de-337f-4cd6-89e8-772a1f71d860"></a>
### 7560-164e8d6/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32415
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f5bd1b8c2a33:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-zz4lm0jttbzik9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 405,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:32415/aws-sdk-go-test-zz4lm0jttbzik9: dial tcp 72.28.97.54:32415: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="cecc1b13-aba9-4fab-9c2a-b53122050f1d"></a>
### 7560-164e8d6/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30590
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9e954e7654f7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mhpmj2ijb2n1uq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 288,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:30590/aws-sdk-go-test-mhpmj2ijb2n1uq: dial tcp 72.28.97.61:30590: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#faa82fdc-eb0b-4f2f-9ffc-9b1da64ab8be) |
| mint-compression-dist-xl.sh | :x: [more...](#25daef97-e499-442f-aeac-3fa600182198) |
| mint-compression-fs.sh | :x: [more...](#4b42382d-31da-47e4-b601-992114070e36) |
| mint-fs.sh | :x: [more...](#1e038bdb-a24f-4336-9460-6a934a5cac5a) |
| mint-dist-xl.sh | :x: [more...](#99e49490-46e5-457a-8d17-9d8db940ea59) |
<a name="1e038bdb-a24f-4336-9460-6a934a5cac5a"></a>
### 7560-ab887e4/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32213
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 82389bd8c30e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-bv463u3avhxbdq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3055,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32213/aws-sdk-go-test-bv463u3avhxbdq: dial tcp 72.28.97.57:32213: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="99e49490-46e5-457a-8d17-9d8db940ea59"></a>
### 7560-ab887e4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32266
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a0ccb6a16991:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 22 seconds
(8/14) Running minio-dotnet tests ... done in 32 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 4 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 0 seconds
(11/14) Running minio-js tests ... done in 39 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 35 seconds
{
  "message": "'content-language'",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 116,
  "name": "minio-py:test_presigned_get_object_response_headers",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-875cb5e9-9264-40f2-a1c4-3c4e521c973c",
    "object_name": "690ecf9b-ba13-42fe-985d-351e05079051"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1266, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 152, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1888, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1274, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="25daef97-e499-442f-aeac-3fa600182198"></a>
### 7560-ab887e4/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32626
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cf776a8fa48a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gz30tssumyx9ml",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 355,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32626/aws-sdk-go-test-gz30tssumyx9ml: dial tcp 72.28.97.55:32626: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="4b42382d-31da-47e4-b601-992114070e36"></a>
### 7560-ab887e4/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30894
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 792181b61c58:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 0 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 45 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 20 seconds
(8/14) Running minio-dotnet tests ... done in 23 seconds
(9/14) Running minio-go tests ... done in 27 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 16 seconds
(11/14) Running minio-js tests ... done in 36 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 5 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "object_name": "0e3d3e6c-f54f-412a-be61-4a9ddecffffc",
    "bucket_name": "minio-py-test-bfd4b8a8-7ecc-4061-8c22-b4bb891f58c5"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "duration": 155,
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="faa82fdc-eb0b-4f2f-9ffc-9b1da64ab8be"></a>
### 7560-ab887e4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30289
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a92ab5f28c3a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fcvcmm4fubd6uq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 253,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:30289/aws-sdk-go-test-fcvcmm4fubd6uq: dial tcp 72.28.97.59:30289: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]
Reproduced verified as fixed.

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
