### PR TITLE
Fix cleanup of pipe in GetObjectNInfo handlers

### PR DESCRIPTION
**Pull request by donatello**
## Description

Fix cleaning up of io.Pipe in GetObjectNInfo handler

## Motivation and Context

Fixes a bug that causes a go routine leak and a hang in gateway type setups.

## Regression

No

## How Has This Been Tested?

With mc functional tests - they were producing the hang earlier, and they are fixed with this change.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#730f9c6b-1705-45a0-9fc9-5f05526eaaef) |
<a name="730f9c6b-1705-45a0-9fc9-5f05526eaaef"></a>
### 6509-143e1d6/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32543
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1595d826c9ba:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 2 minutes and 42 seconds
(2/13) Running aws-sdk-go tests ... done in 2 seconds
(3/13) Running aws-sdk-java tests ... done in 5 seconds
(4/13) Running aws-sdk-php tests ... done in 54 seconds
(5/13) Running aws-sdk-ruby tests ... done in 36 seconds
(6/13) Running mc tests ... done in 6 minutes and 32 seconds
(7/13) Running minio-dotnet tests ... FAILED in 5 minutes and 30 seconds
{
  "name": "minio-dotnet: CopyObject_Test5",
  "function": "Task<CopyObjectResult> CopyObjectAsync(string bucketName, string objectName, string destBucketName, string destObjectName = null, CopyConditions copyConditions = null, CancellationToken cancellationToken = default(CancellationToken))",
  "args": {
    "bucketName": "miniodotnet8v4occ81913vy82",
    "objectName": "miniodotnetuc3zczon5v",
    "destBucketName": "miniodotnetdnkq0ma7i8vjkig",
    "destObjectName": "miniodotnetv5r7yh1nru",
    "data": "6MB",
    "size": "6MB"
  },
  "duration": 8288,
  "status": "FAIL",
  "alert": "",
  "message": "Minio API responded with message=A header you provided implies functionality that is not implemented",
  "error": "A header you provided implies functionality that is not implemented: Minio.Exceptions.MinioException: Minio API responded with message=A header you provided implies functionality that is not implemented\n   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 362\n   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 504\n   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 350\n   at Minio.MinioClient.CopyObjectRequestAsync(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions, Dictionary`2 customHeaders, String resource, CancellationToken cancellationToken, Type type) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 986\n   at Minio.MinioClient.MultipartCopyUploadAsync(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions, Int64 copySize, Dictionary`2 metadata, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 1045\n   at Minio.MinioClient.CopyObjectAsync(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions, Dictionary`2 metadata, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 939\n   at Minio.Functional.Tests.FunctionalTest.CopyObject_Test5(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1059"
}

Executed 6 out of 13 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Comment by vadmeste** [comment]
Not only for gateway @donatello, this also affects the server:

This is my diff

```diff
diff --git a/cmd/xl-sets.go b/cmd/xl-sets.go
index 13fd7bb7..85d533ab 100644
--- a/cmd/xl-sets.go
+++ b/cmd/xl-sets.go
@@ -638,7 +638,7 @@ func (s *xlSets) CopyObject(ctx context.Context, srcBucket, srcObject, destBucke
 	}
 
 	go func() {
-		if gerr := srcSet.getObject(ctx, srcBucket, srcObject, 0, srcInfo.Size, srcInfo.Writer, srcInfo.ETag, srcOpts); gerr != nil {
+		if gerr := srcSet.getObject(ctx, srcBucket, srcObject, 0, srcInfo.Size, srcInfo.Writer, srcInfo.ETag, srcOpts, nil); gerr != nil {
 			if gerr = srcInfo.Writer.Close(); gerr != nil {
 				logger.LogIf(ctx, gerr)
 			}
diff --git a/cmd/xl-v1-multipart.go b/cmd/xl-v1-multipart.go
index b4d37af1..ccb5d164 100644
--- a/cmd/xl-v1-multipart.go
+++ b/cmd/xl-v1-multipart.go
@@ -270,7 +270,7 @@ func (xl xlObjects) CopyObjectPart(ctx context.Context, srcBucket, srcObject, ds
 	}
 
 	go func() {
-		if gerr := xl.getObject(ctx, srcBucket, srcObject, startOffset, length, srcInfo.Writer, srcInfo.ETag, srcOpts); gerr != nil {
+		if gerr := xl.getObject(ctx, srcBucket, srcObject, startOffset, length, srcInfo.Writer, srcInfo.ETag, srcOpts, nil); gerr != nil {
 			if gerr = srcInfo.Writer.Close(); gerr != nil {
 				logger.LogIf(ctx, gerr)
 			}
diff --git a/cmd/xl-v1-object.go b/cmd/xl-v1-object.go
index 54a123dc..721e2bb1 100644
--- a/cmd/xl-v1-object.go
+++ b/cmd/xl-v1-object.go
@@ -20,6 +20,7 @@ import (
 	"bytes"
 	"context"
 	"encoding/hex"
+	"errors"
 	"io"
 	"net/http"
 	"path"
@@ -140,7 +141,7 @@ func (xl xlObjects) CopyObject(ctx context.Context, srcBucket, srcObject, dstBuc
 
 	go func() {
 		var startOffset int64 // Read the whole file.
-		if gerr := xl.getObject(ctx, srcBucket, srcObject, startOffset, length, pipeWriter, srcInfo.ETag, srcOpts); gerr != nil {
+		if gerr := xl.getObject(ctx, srcBucket, srcObject, startOffset, length, pipeWriter, srcInfo.ETag, srcOpts, nil); gerr != nil {
 			pipeWriter.CloseWithError(toObjectErr(gerr, srcBucket, srcObject))
 			return
 		}
@@ -201,14 +202,19 @@ func (xl xlObjects) GetObjectNInfo(ctx context.Context, bucket, object string, r
 		return nil, toObjectErr(err, bucket, object)
 	}
 
-	fn, off, length, nErr := NewGetObjectReader(rs, objInfo, nsUnlocker)
+	stopCh := make(chan struct{})
+	stopFn := func() {
+		close(stopCh)
+	}
+
+	fn, off, length, nErr := NewGetObjectReader(rs, objInfo, nsUnlocker, stopFn)
 	if nErr != nil {
 		return nil, nErr
 	}
 
 	pr, pw := io.Pipe()
 	go func() {
-		err := xl.getObject(ctx, bucket, object, off, length, pw, "", ObjectOptions{})
+		err := xl.getObject(ctx, bucket, object, off, length, pw, "", ObjectOptions{}, stopCh)
 		pw.CloseWithError(err)
 	}()
 
@@ -228,11 +234,11 @@ func (xl xlObjects) GetObject(ctx context.Context, bucket, object string, startO
 		return err
 	}
 	defer objectLock.RUnlock()
-	return xl.getObject(ctx, bucket, object, startOffset, length, writer, etag, opts)
+	return xl.getObject(ctx, bucket, object, startOffset, length, writer, etag, opts, nil)
 }
 
 // getObject wrapper for xl GetObject
-func (xl xlObjects) getObject(ctx context.Context, bucket, object string, startOffset int64, length int64, writer io.Writer, etag string, opts ObjectOptions) error {
+func (xl xlObjects) getObject(ctx context.Context, bucket, object string, startOffset int64, length int64, writer io.Writer, etag string, opts ObjectOptions, stop chan struct{}) error {
 
 	if err := checkGetObjArgs(ctx, bucket, object); err != nil {
 		return err
@@ -321,6 +327,12 @@ func (xl xlObjects) getObject(ctx context.Context, bucket, object string, startO
 	}
 
 	for ; partIndex <= lastPartIndex; partIndex++ {
+		select {
+		case <-stop:
+			return toObjectErr(errors.New("getobject proactively stopped"), bucket, object)
+		default:
+			// continue
+		}
 		if length == totalBytesRead {
 			break
 		}
```

**Comment by donatello** [comment]
@vadmeste There is also a change for xl in this PR - we are closing the pipe.

~I am trying to understand what your diff is doing.~ The pipe closure will take care of causing getObject to stop writing so we dont have to do it in this channel style.

**Comment by vadmeste** [comment]
> @vadmeste There is also a change for xl in this PR - we are closing the pipe. I am trying to understand what your diff is doing.

I also don't understand why GC is not doing its job here, but I confirm this diff is needed with testing

**Review by poornas — APPROVED** [review]

**Comment by vadmeste** [comment]
We should not merge this, still need to be updated

**Comment by harshavardhana** [comment]
> doing

GC doesn't do anything because it cannot do, its an active reference.

**Pull request merged**
