### PR TITLE
Update version of madmin-go to v1.7.3

### PR DESCRIPTION
**Pull request by anjalshireesh**
## Description

It adds the time zone field to the time-info node in the health report.

## Motivation and Context

Capture time zone info in health report so that `health-analyzer` can add check(s) related to the same.

## How to test this PR?

- Register the cluster if not registered using `mc license register {alias}`
- Generate a health report using `mc support diag {alias} --airgap`
- Inspect the contents of the generated report and verify that field `time_zone` is present under `config -> time-info`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#24cac839-e88d-463e-801a-36af2f05253b) |
<a name="24cac839-e88d-463e-801a-36af2f05253b"></a>
### 15994-489b0c9/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:30527
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 8543bb4930ea:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 12 seconds
(8/14) Running minio-go tests ... done in 29 seconds
(9/14) Running minio-java tests ... FAILED in 14 seconds
{
  "name": "minio-java",
  "function": "getObjectRetention()",
  "duration": 21,
  "status": "FAIL",
  "error": "java.time.format.DateTimeParseException: Text '2022-11-06T05:31:09.2Z' could not be parsed at index 19 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioAsyncClient.lambda$getObjectRetention$35(MinioAsyncClient.java:1738), java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642), java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506), java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073), io.minio.S3Base$1.onResponse(S3Base.java:559), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 42 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 4 seconds
(11/14) Running s3cmd tests ... done in 12 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
I am thinking of doing something like 

```diff
diff --git a/internal/init/init.go b/internal/init/init.go
index 7d0c432f8..60c5067e3 100644
--- a/internal/init/init.go
+++ b/internal/init/init.go
@@ -16,3 +16,9 @@
 // along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 package init
+
+import "os"
+
+func init() {
+       os.Setenv("TZ", "UTC")
+}
diff --git a/internal/init/init_darwin_amd64.go b/internal/init/init_darwin_amd64.go
index 7bc01758e..4a0ed4e81 100644
--- a/internal/init/init_darwin_amd64.go
+++ b/internal/init/init_darwin_amd64.go
@@ -22,6 +22,8 @@ import (
 )
 
 func init() {
+       os.Setenv("TZ", "UTC")
+
        // Temporary workaround for
        // https://github.com/golang/go/issues/49233
        // Keep until upstream has been fixed.
```

Something came to mind today that we could force the TZ for UTC and have all time.Now() defaults to UTC - I am testing this locally.

**Comment by harshavardhana** [comment]
> I am thinking of doing something like
> 
> ```diff
> diff --git a/internal/init/init.go b/internal/init/init.go
> index 7d0c432f8..60c5067e3 100644
> --- a/internal/init/init.go
> +++ b/internal/init/init.go
> @@ -16,3 +16,9 @@
>  // along with this program.  If not, see <http://www.gnu.org/licenses/>.
>  
>  package init
> +
> +import "os"
> +
> +func init() {
> +       os.Setenv("TZ", "UTC")
> +}
> diff --git a/internal/init/init_darwin_amd64.go b/internal/init/init_darwin_amd64.go
> index 7bc01758e..4a0ed4e81 100644
> --- a/internal/init/init_darwin_amd64.go
> +++ b/internal/init/init_darwin_amd64.go
> @@ -22,6 +22,8 @@ import (
>  )
>  
>  func init() {
> +       os.Setenv("TZ", "UTC")
> +
>         // Temporary workaround for
>         // https://github.com/golang/go/issues/49233
>         // Keep until upstream has been fixed.
> ```
> 
> Something came to mind today that we could force the TZ for UTC and have all time.Now() defaults to UTC - I am testing this locally.

This change has been merged. This is enough for the UTC enforcement, however, we can still verify the OS settings so this PR can be taken.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
