### PR TITLE
Remove go1.9 specific code for windows

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Remove go1.9 specific code for windows

## Motivation and Context
Following fix https://go-review.googlesource.com/#/c/41834/ has
been merged upstream and released with go1.9.

## How Has This Been Tested?
Manually on windows

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by balamurugana — CHANGES_REQUESTED** [review]
We have backward compatible with go1.8

**Comment by harshavardhana** [comment]
Tests will run why would we need to build a release on go1.8 ? We don't need this code IMO.

**Comment by harshavardhana** [comment]
Also the code being removed is very contextual happens with volume synlinks on windows and has no other functionality changed.

Now if we decide to not build releases with Go1.9 then it's a problem. I would like this PR to be blocked until such a decision can be arrived.

**Comment by harshavardhana** [comment]
Moving this to blocked on further discussion..

**Comment by harshavardhana** [comment]
> Moving this to blocked on further discussion..

We have decided to move to 1.9 without backward compatibility.

**Comment by vadmeste** [comment]
Tests are not passed here @harshavardhana, please ping me again when it is fixed.

**Comment by harshavardhana** [comment]
> Tests are not passed here @harshavardhana, please ping me again when it is fixed.

Fixed build issue @vadmeste @balamurugana

**Review by vadmeste — APPROVED** [review]
LGTM, basic operations tested under Windows

**Review by balamurugana — APPROVED** [review]

**Pull request merged**
