### PR TITLE
Add support for Timestamp data type in SQL Select

### PR DESCRIPTION
**Pull request by donatello**
## Description

This change adds support for casting strings to Timestamp via CAST:
`CAST('2010T' AS TIMESTAMP)`

It also implements the following date-time functions:
  - UTCNOW()
  - DATE_ADD()
  - DATE_DIFF()
  - EXTRACT()

Reference: https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-glacier-select-sql-reference-date.html

## How Has This Been Tested?

Manually, here are some sample queries:

```shell
mc sql --query "select date_diff(hour, '2013-01-02T04:00Z', '2013-01-02T05:59Z') from s3object"  myminio/sqlselectapi/2.csv
mc sql --query "select date_diff(HOUR, '2013-01-02T04:00Z', '2013-01-02T05:59Z') from s3object"  myminio/sqlselectapi/2.csv
mc sql --query "select date_diff(hour, '2013-01-02T04:00Z', '2013-01-02T05:59Z') from s3object"  myminio/sqlselectapi/2.csv
mc sql --query "select date_diff(day, '2013-01-02T04:00Z', '2013-03-01T04:00Z') from s3object"  myminio/sqlselectapi/2.csv
mc sql --query "select date_diff(day, '2016-02-01T04:00Z', '2016-03-01T04:00Z') from s3object"  myminio/sqlselectapi/2.csv
mc sql --query "select date_diff(day, '2016-02-01T04:00Z', '2016-03-01T04:00Z') from s3object"  myminio/sqlselectapi/2.csv
mc sql --query "select date_add(year, 1, '2014-01-01T') from s3object" myminio/sqlselectapi/1.csv
mc sql --query "select utcnow() from s3object" myminio/sqlselectapi/1.csv
mc sql --query "select extract(year from utcnow()) from s3object" myminio/sqlselectapi/1.csv
mc sql --query "select extract(month from utcnow()) from s3object" myminio/sqlselectapi/1.csv
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by balamurugana — DISMISSED** [review]

**Review by harshavardhana — DISMISSED** [review]
Can you update the docs/select/README.md with latest implementation status?

**Comment by donatello** [comment]
Updated implementation status - PTAL @harshavardhana  @balamurugana

**Review by harshavardhana — APPROVED** [review]
LGTM & tested

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by donatello** [comment]
@balamurugana Could you take a look?

**Review by balamurugana — APPROVED** [review]

**Pull request merged**
