### PR TITLE
[WIP] Move object lock configuration into bucket metadata

### PR DESCRIPTION
**Pull request by balamurugana**
Depends on https://github.com/minio/minio/pull/9465
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by harshavardhana** [comment]
The plan was not to move all the bucket files into a single metadata file @balamurugana we may have disparate data structures that we cannot club together. 

Another advantage of having separate files is that we get to place them in different erasure sets. What is done in the PR #9465 perhaps is enough IMO - all other parts of the code should stay as is.

Object lock configuration is a completely different API and brings a different data structure that cannot be fit into a single file.

**Comment by balamurugana** [comment]
This PR is split of @klauspost recommended approach sent in https://github.com/minio/minio/pull/9465

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#6fe88550-4528-4349-9676-bce8f4ef2b60) |
| mint-gateway-azure.sh | :x: [more...](#e5a9e83d-d94c-47d5-b105-05c929ee4ae2) |
| mint-gateway-nas.sh | :x: [more...](#60bd2dae-0ff7-4314-9f5c-5975d507aff1) |
<a name="60bd2dae-0ff7-4314-9f5c-5975d507aff1"></a>
### 9505-6092494/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30809
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 66eebaa6b4fd:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 3 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 41 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 39 seconds
{}
(9/15) Running minio-java tests ... FAILED in 23 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 44,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-b101n8, objectName = minio-java-test-1pcjlrf, resource = /minio-java-test-b101n8/minio-java-test-1pcjlrf, requestId = 160ADCDFDDB3323C, hostId = e272610e-25d1-4bcf-9328-fcce78e29e5e)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30809/minio-java-test-b101n8/minio-java-test-1pcjlrf?legal-hold=, headers=Host: minio-dev4.minio.io:30809\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200501T091752Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200501/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160ADCDFDDB3323C\nX-Xss-Protection: 1; mode=block\nDate: Fri, 01 May 2020 09:17:52 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 35 seconds
(10/15) Running minio-py tests ... done in 55 seconds
(11/15) Running s3cmd tests ... done in 16 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="e5a9e83d-d94c-47d5-b105-05c929ee4ae2"></a>
### 9505-6092494/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31859
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e92da0bc887d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 27 seconds
(4/15) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 3 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 242538.58,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}
(4/15) Running awscli tests ... FAILED in 48 seconds
{
  "name": "awscli",
  "duration": 3767,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:31859 s3api copy-object --bucket awscli-mint-test-bucket-20970 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-20970/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(4/15) Running healthcheck tests ... done in 1 seconds
(5/15) Running mc tests ... done in 2 minutes and 51 seconds
(6/15) Running minio-dotnet tests ... done in 3 minutes and 15 seconds
(7/15) Running minio-go tests ... FAILED in 4 minutes and 6 seconds
{}
(7/15) Running minio-java tests ... FAILED in 28 minutes and 15 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 2087,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-3kpmrqg, objectName = minio-java-test-3r74h4a, resource = /minio-java-test-3kpmrqg/minio-java-test-3r74h4a, requestId = 160ADF6175975485, hostId = c7e433f4-8c43-4c90-8027-f4be6497651b)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31859/minio-java-test-3kpmrqg/minio-java-test-3r74h4a?legal-hold=, headers=Host: minio-dev7.minio.io:31859\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200501T100348Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200501/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160ADF6175975485\nX-Xss-Protection: 1; mode=block\nDate: Fri, 01 May 2020 10:03:48 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(7/15) Running minio-js tests ... FAILED in 6 minutes and 20 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-692073f1-de2e-41b8-acb9-e3b6ac9c4e9f, recursive:true",
  "duration": 210,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(7/15) Running minio-py tests ... done in 11 minutes and 48 seconds
(8/15) Running s3cmd tests ... FAILED in 41 seconds
{
  "name": "s3cmd",
  "duration": "1633",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(8/15) Running s3select tests ... done in 22 seconds
(9/15) Running security tests ... done in 0 seconds

Executed 9 out of 15 tests successfully.
```
<a name="6fe88550-4528-4349-9676-bce8f4ef2b60"></a>
### 9505-6092494/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30432
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 160e10c77270:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 3 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 42 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 40 seconds
{}
(9/15) Running minio-java tests ... FAILED in 33 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 66,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-1s7jhki, objectName = minio-java-test-394lpcd, resource = /minio-java-test-1s7jhki/minio-java-test-394lpcd, requestId = 160ADCE2D856F1FE, hostId = 92293fb8-35cf-43e8-98d3-de7c13883e0a)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30432/minio-java-test-1s7jhki/minio-java-test-394lpcd?legal-hold=, headers=Host: minio-dev4.minio.io:30432\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200501T091805Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200501/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160ADCE2D856F1FE\nX-Xss-Protection: 1; mode=block\nDate: Fri, 01 May 2020 09:18:05 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 33 seconds
(10/15) Running minio-py tests ... done in 56 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 1 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
> This PR is split of @klauspost recommended approach sent in #9465

@balamurugana what I meant is `object-lock.xml` has no reason being in .metadata.bin as they are not the same thing and it conflicts with what we want.  object-lock.xml is mutating value and we don't want an entity that carries other information about the bucket to be mutating. 

This PR is not needed as we are actually done with what is needed with `.metadata.bin`

**Comment by harshavardhana** [comment]
> > This PR is split of @klauspost recommended approach sent in #9465
> 
> @balamurugana what I meant is `object-lock.xml` has no reason being in .metadata.bin as they are not the same thing and it conflicts with what we want. object-lock.xml is mutating value and we don't want an entity that carries other information about the bucket to be mutating.
> 
> This PR is not needed as we are actually done with what is needed with `.metadata.bin`

Let's discuss this as there are advantages and disadvantages for both approaches.

**Comment by klauspost** [comment]
Superseded by #9586 AFAICT.

**Comment by balamurugana** [comment]
> Superseded by #9586 AFAICT.

Closing

**Pull request closed without merging**
