### PR TITLE
relax O_DIRECT in single drive mode if unsupported

### LINKED ISSUE #15042: Minio on macos + docker no longer starts with RELEASE.2022-06-02T02-11-04Z
## Expected Behavior
Minio should start with `minio:latest` / `minio:RELEASE.2022-06-02T02-11-04Z`

## Current Behavior

As per older issues (https://github.com/minio/minio/issues/9554, https://github.com/minio/minio/issues/10277), with `RELEASE.2022-06-02T02-11-04Z` minio fails to start and complains about requiring `O_DIRECT` support.

As stated in https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html#pre-existing-data, it seems single drive mode now uses erasure coding (which requires `O_DIRECT`?). Where before the recommendation was to ensure you run in filesystem / single drive mode for macos + docker, it seems this may no longer be possible? As stated in that link it suggests running an older version of minio.

## Possible Solution
Run older version (e.g. `RELEASE.2022-05-26T05-48-41Z`) of minio (precluding future updates)

## Steps to Reproduce (for bugs)

1. Start `minio` on macos + docker with version `RELEASE.2022-06-02T02-11-04Z`
2. Minio will error on startup complaining about requiring `O_DIRECT` support.

## Regression

See versions above.

## Your Environment

* Version used (`minio --version`): `RELEASE.2022-06-02T02-11-04Z`
* Server setup and configuration: minio invoked with `minio server --console-address :9001 /data`
* Operating System and version (`uname -a`): `Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64`

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
relax O_DIRECT in single drive mode if unsupported

## Motivation and Context
fixes #15042 

## How to test this PR?
You would need something like #15042 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
LGTM

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
