### PR TITLE
Support HBase gateway for medium and small files.

### PR DESCRIPTION
**Pull request by haosdent**
## Description

To resolve this problem https://github.com/minio/minio/issues/8025. 
Since HDFS is only suitable for large files, I implement an HBase backend to support files < 1G.

## Motivation and Context

To support store medium and small files.

## How to test this PR?

```
# ./minio gateway hbase localhost:2181
Endpoint:  http://127.0.0.1:9000
AccessKey: xxx
SecretKey: xxxxxxxx

# mc config host add hbase-s3 http://127.0.0.1:9000 xxx xxxxxxxx --api S3v

# mc mb hbase-s3/test
Bucket created successfully `hbase-s3/test`.
# mc tree hbase-s3 test
hbase-s3
└─ test

# mc cp ~/Downloads/logo.png hbase-s3/test/
...e/haosdent/Downloads/logo.png:  25.35 KiB / 25.35 KiB
# mc ls hbase-s3/test
[2020-03-02 16:26:30 +08]   25KiB logo.png


# hbase(main):045:0> scan 'test_meta'
ROW                                              COLUMN+CELL
 1_logo.png                                      column=cf:value, timestamp=1583137590733, value={"name":"logo.png","size":25958,"is_dir":false,"mod_time":1583137590,"parts":1}
1 row(s)

hbase(main):046:0> scan 'test_data'
ROW                                              COLUMN+CELL
 1bb87d41d15fe27b500a4bfcde01bb0e_0              column=cf:value, timestamp=1583137590690, value=\xFF\xD8\.....
 ```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [x] Unit tests needed
- [x] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#64ac9cf6-a95c-4daf-9207-27298c7e2df1) |
| mint-gateway-azure.sh | :x: [more...](#2543900b-804a-4d1e-8487-a0f7394a58ad) |
<a name="2543900b-804a-4d1e-8487-a0f7394a58ad"></a>
### 9071-43ba200/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30451
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dd83129503c4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 17 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 27 seconds
{
  "name": "awscli",
  "duration": 1538,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 14 tests successfully.
```
<a name="64ac9cf6-a95c-4daf-9207-27298c7e2df1"></a>
### 9071-43ba200/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31005
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 78dbbc2d5045:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ez39on04n0yyd0",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120332,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31005/aws-sdk-go-test-ez39on04n0yyd0: dial tcp 72.28.97.55:31005: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Thanks for the PR @haosdent - thanks for the work. Currently we are not accepting any new gateway implementations into our master branch, without any prior discussion on who is going to maintain this in future, other logistics.

Please join our https://slack.min.io for further discussion.

**Comment by haosdent** [comment]
Ohoh, @harshavardhana do you support plugin way?

**Comment by harshavardhana** [comment]
> Ohoh, @harshavardhana do you support plugin way?

No, we don't that is only supported on Linux @haosdent - feel free to keep this in your fork.  Let's close this PR for now and revisit in future.

**Pull request closed without merging**
