### PR TITLE
Compression: Handle auto encryption when size is unknown

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
When object size is unknown and auto encryption is enabled and compression is turned on in the config,
putobject API is failing.

Moving adding the SSE-S3 header as part of the request to before
checking if compression can be done, otherwise the size is set to -1
and that seems to cause problems.

## Motivation and Context
A `minio-js` functional test was failing against play, when play had auto encryption on and compression was set to true in config.json.

## Regression
Don't know

## How Has This Been Tested?
```
var Minio = require('minio')
var fs = require('fs')

var s3Client = new Minio.Client({
  endPoint: '127.0.0.1',
  accessKey: 'minio',
  secretKey: 'minio123',
  useSSL: true,
  region: "us-east-1",
  port: 9000
})

var metaData = {
  'Content-Type': 'application/octet-stream',
  'X-Amz-Meta-Testing': 1234,
  'example': 5678
}
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0
var _100kb = (new Buffer(100 * 1024)).fill(0)
var tmpFileUploadWithExt = '/tmp/ttt.txt'
fs.writeFileSync(tmpFileUploadWithExt, _100kb)
s3Client.fPutObject("test", "my_object", tmpFileUploadWithExt, function(e) {
  if (e) {
    return console.log(e)
  }
  console.log("Success")
})

```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Praveenrajmani — DISMISSED** [review]
Tested and LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_exclamation_mark: [more...](#4259b586-f217-4a55-b0a3-23a8aeef9271) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#91798b36-0bd4-45a2-8bf8-b2512f4a45c0) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#190afded-613b-4bf6-8e69-fc7da6cf08eb) |
| mint-compression-dist-xl.sh | :heavy_exclamation_mark: [more...](#47f3ec47-e3de-47f1-beca-6cef38c88192) |
| mint-compression-fs.sh | :heavy_exclamation_mark: [more...](#f26e9f9a-77e3-41d0-8baa-8b137f66e0c0) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#01e0ff13-7ce6-43e4-a5cb-51fedaefa47b) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#8513fe49-b664-4a44-afcf-138f4111bba8) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#1a197f6b-9626-4f94-ba16-a0a012c5e36d) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#f5f50ddb-ac3a-4ff1-97d9-3a7beb36d07d) |
<a name="01e0ff13-7ce6-43e4-a5cb-51fedaefa47b"></a>
### 7600-e7d919b/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="47f3ec47-e3de-47f1-beca-6cef38c88192"></a>
### 7600-e7d919b/mint-compression-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="1a197f6b-9626-4f94-ba16-a0a012c5e36d"></a>
### 7600-e7d919b/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="f26e9f9a-77e3-41d0-8baa-8b137f66e0c0"></a>
### 7600-e7d919b/mint-compression-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="91798b36-0bd4-45a2-8bf8-b2512f4a45c0"></a>
### 7600-e7d919b/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="8513fe49-b664-4a44-afcf-138f4111bba8"></a>
### 7600-e7d919b/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="4259b586-f217-4a55-b0a3-23a8aeef9271"></a>
### 7600-e7d919b/mint-compression-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="190afded-613b-4bf6-8e69-fc7da6cf08eb"></a>
### 7600-e7d919b/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="f5f50ddb-ac3a-4ff1-97d9-3a7beb36d07d"></a>
### 7600-e7d919b/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_exclamation_mark: [more...](#b3fb5188-42fa-4042-a647-cebf3d1fb2a9) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#0d03f7d6-0da6-4d6e-844f-cadd357314a8) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#1b154620-d6d6-462d-a2f3-2390b868754e) |
| mint-compression-dist-xl.sh | :heavy_exclamation_mark: [more...](#fdd6f618-a403-47f0-8870-415f116238a0) |
| mint-compression-fs.sh | :heavy_exclamation_mark: [more...](#fff3b7c4-011d-4bec-bd41-3500985e50c6) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#30663db8-8ec4-4c22-b008-b5d02a054a0b) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#9368ebef-9962-401a-870d-ff526a943174) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#f9ad13b6-9d71-417c-a41e-58b701a723ee) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#4261294c-3c1b-4232-8e74-12f228ec724b) |
<a name="1b154620-d6d6-462d-a2f3-2390b868754e"></a>
### 7600-95dfd59/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="b3fb5188-42fa-4042-a647-cebf3d1fb2a9"></a>
### 7600-95dfd59/mint-compression-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0d03f7d6-0da6-4d6e-844f-cadd357314a8"></a>
### 7600-95dfd59/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="4261294c-3c1b-4232-8e74-12f228ec724b"></a>
### 7600-95dfd59/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="9368ebef-9962-401a-870d-ff526a943174"></a>
### 7600-95dfd59/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="f9ad13b6-9d71-417c-a41e-58b701a723ee"></a>
### 7600-95dfd59/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="fff3b7c4-011d-4bec-bd41-3500985e50c6"></a>
### 7600-95dfd59/mint-compression-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="30663db8-8ec4-4c22-b008-b5d02a054a0b"></a>
### 7600-95dfd59/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="fdd6f618-a403-47f0-8870-415f116238a0"></a>
### 7600-95dfd59/mint-compression-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```

**Review by harshavardhana — APPROVED** [review]

**Review by poornas — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Pull request merged**
