### PR TITLE
Remove LogIf called on error returned by a listbuckets call

### LINKED ISSUE #7367: [gateway-gcs] complains when storage.buckets.list permission is missing
When starting a GCS gateway that's using a service account without global `storage.buckets.list` permission for the whole project, minio gateway gcs complains loudly, while it being a perfectly valid scenario. We should detect such cases, and not try to request more than we're able to access.

## Expected Behavior
The GCS gateway should start up, and simple CRUD requests inside buckets should just work.

## Current Behavior
On bootup, things look terribly broken at first:
```
{"level":"ERROR","time":"2019-03-14T14:23:15.006578162Z","api":{"name":"SYSTEM","args":{}},"error":{"message":"googleapi: Error 403: foo@myproject.iam.gserviceaccount.com does not have storage.buckets.list access to project 123456789., forbidden","source":["/build/go/src/github.com/minio/minio/cmd/gateway/gcs/gateway-gcs.go:399:gcs.(*gcsGateway).CleanupGCSMinioSysTmp()"]}}
{"level":"ERROR","time":"2019-03-14T14:23:15.013295994Z","api":{"name":"SYSTEM","args":{}},"error":{"message":"googleapi: Error 403: foo@myproject.iam.gserviceaccount.com does not have storage.buckets.list access to project 123456789., forbidden","source":["/build/go/src/github.com/minio/minio/cmd/gateway/gcs/gateway-gcs.go:463:gcs.(*gcsGateway).ListBuckets()","/build/go/src/github.com/minio/minio/cmd/policy.go:99:cmd.(*PolicySys).ref$
esh()","/build/go/src/github.com/minio/minio/cmd/policy.go:163:cmd.(*PolicySys).Init()"]}}
{"level":"ERROR","time":"2019-03-14T14:23:15.013374963Z","api":{"name":"SYSTEM","args":{}},"error":{"message":"Prefix access is denied: /","source":["/build/go/src/github.com/minio/minio/cmd/policy.go:101:cmd.(*PolicySys).refresh()","/build/go/src/github.com/minio/minio/cmd/policy.go:163:cmd.(*PolicySys).Init()"]}}
```

Afterwards, minio still seems to run properly though.

## Possible Solution
This looks like starting up the gateway triggers some PolicySys init that requires project-wide `storage.buckets.list` permission (which it doesn't have via that service account)

Minio should be able to handle such cases a bit more gracefully.

## Steps to Reproduce (for bugs)

Create the bucket and service account in GCP:
```hcl
resource "google_storage_bucket" "mybucket" {
  name          = "mybucket"
  location      = "US"
  storage_class = "MULTI_REGIONAL"
}
resource "google_service_account" "mybucket" {
  account_id   = "${var.name}-sa"
  display_name = "${var.name} SA"
}
resource "google_storage_bucket_iam_member" "sevice_account_mybucket" {
  bucket = "${google_storage_bucket.mybucket.name}"

  role = "roles/storage.admin"

  member = "serviceAccount:${google_service_account.mybucket.email}"
}
```

Run the gateway:
```
export AWS_ACCESS_KEY_ID=accesskey
export AWS_SECRET_ACCESS_KEY=$RANDOM-$RANDOM
export MINIO_ACCESS_KEY=$AWS_ACCESS_KEY_ID
export MINIO_SECRET_KEY=$AWS_SECRET_ACCESS_KEY
export MINIO_CONFIG_DIR=$(mktemp -d)
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json
minio gateway gcs --address 127.0.0.1:9000 --json
```

## Context
I'm trying to use S3 protocol to read/write from a bucket in GCS, 

## Your Environment

* Version used (`minio version`): 2019-02-26T19-51-46Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): NixOS 19.03
* Link to your project:

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
Even though the user does not have list buckets permission, he is still able to read and write to a GCS bucket as long as the user has those permissions. The error log seems to scare the users and can be ignored, so it is not being logged.

Fixes #7367

## Motivation and Context
Issue #7367

## Regression
No

## How Has This Been Tested?
Removed LogIf calls based on the error log that was pasted in issue #7367 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f3d00d26-1687-48a6-944b-c70655c12dfc) |
| mint-compression-dist-xl.sh | :x: [more...](#e2ecbbc4-5e76-4baa-96c7-f72ed1e3c84a) |
<a name="e2ecbbc4-5e76-4baa-96c7-f72ed1e3c84a"></a>
### 7370-0290f1a/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32717
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e596d01bd253:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-s5sqk349rrmikd",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 279,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:32717/aws-sdk-go-test-s5sqk349rrmikd: dial tcp 72.28.97.60:32717: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f3d00d26-1687-48a6-944b-c70655c12dfc"></a>
### 7370-0290f1a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31236
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 867f10fe9970:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-xbgqpc22c9pqa1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 320,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:31236/aws-sdk-go-test-xbgqpc22c9pqa1: dial tcp 72.28.97.54:31236: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by flokli** [comment]
I'm not sure if just removing the log statements is the right approach - why do we try to list there in first place? Can't we make this logic a bit smarter, checking for project-wide listing permissions first before doing it? If that's not possible, we should at least add a comment on why we don't log there.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#818adab3-4e7b-4f17-bf10-117e2580a31f) |
| mint-large-bucket.sh | :x: [more...](#097c48c0-4aef-47c5-af00-97c52964b426) |
| mint-dist-xl.sh | :x: [more...](#7512d6a9-51ba-41b4-a2ee-75dd1698f808) |
<a name="097c48c0-4aef-47c5-af00-97c52964b426"></a>
### 7370-cd3ce1b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30522
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58eec09d5db4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 59 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 37 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 23 seconds
(9/14) Running minio-go tests ... done in 2 minutes and 27 seconds
(10/14) Running minio-java tests ... done in 4 minutes and 58 seconds
(11/14) Running minio-js tests ... done in 45 seconds
(12/14) Running minio-py tests ... FAILED in 8 minutes and 56 seconds
{
  "duration": 394,
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "AccessDenied: message: Access Denied",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "args": {
    "object_name": "b3a09c15-a723-4519-8450-41b4f6c39136",
    "bucket_name": "minio-py-test-eb06deea-e4e7-4fc0-a5d9-7ced5344e575"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="7512d6a9-51ba-41b4-a2ee-75dd1698f808"></a>
### 7370-cd3ce1b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31401
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4663244254b2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 54 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 38 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 56 seconds
(11/14) Running minio-js tests ... done in 43 seconds
(12/14) Running minio-py tests ... FAILED in 5 minutes and 49 seconds
{
  "args": {
    "bucket_name": "minio-py-test-b2418576-798b-4d61-bb6d-2dc7bfab8982",
    "object_name": "369bf3bf-9d31-42d8-b209-11a09e905bc8"
  },
  "message": "AccessDenied: message: Access Denied",
  "duration": 191,
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="818adab3-4e7b-4f17-bf10-117e2580a31f"></a>
### 7370-cd3ce1b/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31329
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3d57972eca36:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-z14n6wliurd1dv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3049,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31329/aws-sdk-go-test-z14n6wliurd1dv: dial tcp 72.28.97.57:31329: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#5f9ad628-97d0-4347-ad27-df764c37c622) |
| mint-compression-dist-xl.sh | :x: [more...](#ec9aa0d0-45cc-450a-98e4-f8b846f60501) |
| mint-dist-xl.sh | :x: [more...](#b15dce92-f38c-4821-beeb-4f29aa3661d4) |
<a name="b15dce92-f38c-4821-beeb-4f29aa3661d4"></a>
### 7370-33f8e9c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31682
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 931d70acb517:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-s54wtfscwqcn95",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3077,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31682/aws-sdk-go-test-s54wtfscwqcn95: dial tcp 72.28.97.57:31682: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5f9ad628-97d0-4347-ad27-df764c37c622"></a>
### 7370-33f8e9c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30669
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d82791d79702:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 15 seconds
{
  "name": "mc",
  "duration": "114174",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-1253 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-21393  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-21393/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-21393/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-21393/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-21393/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-21393/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-21393/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-21393/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-21393/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-21393/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-21393/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-21393/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-21393/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-21393/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-21393/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-21393/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 498.42 MiB, Speed: 4.37 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="ec9aa0d0-45cc-450a-98e4-f8b846f60501"></a>
### 7370-33f8e9c/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31918
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a809dbde27d3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-jym6myxwwfgrzf",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2777,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31918/aws-sdk-go-test-jym6myxwwfgrzf: dial tcp 72.28.97.57:31918: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by kannappanr** [comment]
ping @Praveenrajmani

**Review by Praveenrajmani — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#1df56ba3-9364-4844-8305-d06fb5058297) |
| mint-dist-xl.sh | :x: [more...](#e2183b22-fb6d-4845-a661-6d500c44b95c) |
<a name="e2183b22-fb6d-4845-a661-6d500c44b95c"></a>
### 7370-1b9252e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32295
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4b42122d2ee0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 0 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 34 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 469,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3964tfe, objectName=minio-java-test-18c8j1i, resource=/minio-java-test-3964tfe/minio-java-test-18c8j1i, requestId=15A692C65D8AD783, hostId=fa4c0722-eac3-492b-bae3-e36c9a6a7832)\nrequest={method=DELETE, url=http://72.28.97.54:32295/minio-java-test-3964tfe/minio-java-test-18c8j1i?uploadId=d3b4665d-8e3c-4c3e-bb6a-df956155b052, headers=Host: 72.28.97.54:32295\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190609T155501Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190609/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-09T15-35-23Z\nVary: Origin\nX-Amz-Request-Id: 15A692C65D8AD783\nX-Minio-Deployment-Id: fa4c0722-eac3-492b-bae3-e36c9a6a7832\nX-Xss-Protection: 1; mode=block\nDate: Sun, 09 Jun 2019 15:55:01 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="1df56ba3-9364-4844-8305-d06fb5058297"></a>
### 7370-1b9252e/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32669
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8519060268da:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-olv0oc66qn1jo1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360014,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A692BAFCBF6163, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Pull request merged**
