### PR TITLE
azure: Support non standard Azure cloud environments 

### LINKED ISSUE #6110: [gateway/azure] AzureGermanCloud azure server endpoint not working
The Azure German Cloud has a different endpoint: core.cloudapi.de. When trying to give https://core.cloudapi.de as endpoint, minio complains, that it can not resolve the hostname core.cloudapi.de and does not start.

## Expected Behavior
Minio should start and resolv the correct hostname (see possible solution)

## Current Behavior
Minio tries to resolve a not existing hostname ``<endpoint>`` and fails, because there is no DNS-Entry for this hostname.

``` ERROR Invalid argument: lookup core.cloudapi.de on <DNS-Server>: no such host. ```

## Possible Solution
Minio should try to resolve the blob endpoint of the storage account: ``<accountname>.blob.<endpoint>``

## Steps to Reproduce (for bugs)
1. Create an Azure German account 
2. Create a resource group with an azure storage account
3. Create an blob storage container in the azure storage account
4. Set MINIO_ACCESS_KEY and MINIO_SECRET_KEY as described in the minio documentation
5. Try to start minio by issuing the following command in a shell: ``minio gateway azure https://core.cloudapi.de``

## Context
I can not use minio as azure blob storage gateway on my local machine

## Your Environment
minio version: 2018-06-29T02:11:29Z
OS: ubuntu 16.04

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
This change will allow users to enter the endpoint of the
storage account if this latter belongs to a different Azure
cloud environment, such as US gov cloud.

e.g:

  `MINIO_ACCESS_KEY=testaccount \
     MINIO_SECRET_KEY=accountsecretkey \
     minio gateway azure https://testaccount.blob.usgovcloudapi.net`

## Motivation and Context
Fixes #6110 

## Regression
No

## How Has This Been Tested?
Tested only with Azure public cloud:
MINIO_ACCESS_KEY=testaccount MINIO_SECRET_KEY=testsecret minio gateway azure https://testaccount.blob.windows.net

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#85a05a35-b1c3-4c25-aefe-fc07ef85e102) |
<a name="85a05a35-b1c3-4c25-aefe-fc07ef85e102"></a>
### 6712-4d79ea7/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31126
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 252562afe4de:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 1 minutes and 32 seconds
(2/13) Running aws-sdk-go tests ... done in 1 seconds
(3/13) Running aws-sdk-java tests ... done in 5 seconds
(4/13) Running aws-sdk-php tests ... done in 51 seconds
(5/13) Running aws-sdk-ruby tests ... done in 9 seconds
(6/13) Running mc tests ... done in 15 seconds
(7/13) Running minio-dotnet tests ... FAILED in 3 minutes and 28 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=We encountered an internal error, please try again.) (Minio API responded with message=We encountered an internal error, please try again.)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=We encountered an internal error, please try again.) (Minio API responded with message=We encountered an internal error, please try again.) ---> Minio.Exceptions.MinioException: Minio API responded with message=We encountered an internal error, please try again.
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 363
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 505
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 351
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 483
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 229
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 740
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1738
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 218

Executed 6 out of 13 tests successfully.
```

**Comment by kannappanr** [comment]
Can we test azurite with this change?

`https://github.com/Azure/Azurite`

**Comment by vadmeste** [comment]
> Can we test azurite with this change?
> 
> `https://github.com/Azure/Azurite`

@kannappanr, I wasn't aware about Azurite, I updated the PR now and it works with it.

**Review by poornas — DISMISSED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by vadmeste** [comment]
@poornas @krishnasrinivas I just rebased the PR, can you review/approve again ?

**Review by poornas — APPROVED** [review]

**Comment by vadmeste** [comment]
ping @krishnasrinivas

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
