### PR TITLE
Remove applying custom policies with STS access keys

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Remove applying custom policies with STS access keys

## Motivation and Context
Move away from allowing custom policies, all policies in
STS come from OPA otherwise they fail.

## Regression
No

## How Has This Been Tested?
Disallowing `Policy` string along with STS tokens to avoid providing full access to
backend without JWT based claims. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by poornas — APPROVED** [review]
LGTM

**Review by vadmeste — DISMISSED** [review]
Can you update the docs, like docs/multi-user/README.md ?

**Comment by harshavardhana** [comment]
> Can you update the docs, like docs/multi-user/README.md ?

There is no doc update @vadmeste it is only meant for STS

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
