### PR TITLE
support 'ldap:user' variable replacement properly

### LINKED ISSUE #10367: ldap:user not working when authenticating using an STS credential which was authorized from LDAP
ldap:user not working when authenticating using an STS credential which was authorized from LDAP

## Expected Behavior
Assigning the below policy to the user, the user is not able to write into test/<username>. 

{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:ListBucket"
   ],
   "Resource": [
    "arn:aws:s3:::test"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:PutObject",
    "s3:GetObject"
   ],
   "Resource": [
    "arn:aws:s3:::test/${ldap:user}/*"
   ]
  }
 ]

## Current Behavior
Puts fail with insufficient permissions error message

## Possible Solution
Using hardcoded username value in the policy works. 

## Steps to Reproduce (for bugs)

1. Add above policy to user - mc admin policy set myminio home user=xyz 
2. Get STS credentials using curl and using them with export MC_HOST_myminio2=http://access_key:secret_key:token@endpoint
3. Puts to test/xyz fails. 
4.

## Context
Cannot automate policy on home directory for multiple users. 

## Regression
 No

## Your Environment

* Version used (`minio --version`): 2020-08-26T00:00:49Z
* Server setup and configuration: minio running in filesystem mode
* Operating System and version (`uname -a`): Linux  3.10.0-1127.13.1.el7.x86_64 #1 SMP Fri Jun 12 14:34:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
support 'ldap:user' variable replacement properly

## Motivation and Context
also update `ldap.go` examples with latest
minio-go changes

Fixes #10367

## How to test this PR?
As per the original reproducer in #10367 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#b5da09f1-f10f-47c8-bbaf-f8d92a2a540a) |
<a name="b5da09f1-f10f-47c8-bbaf-f8d92a2a540a"></a>
### 10391-32d76cf/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32385
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3f1d2799d75c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 36 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 45 seconds
{
  "name": "awscli",
  "duration": 3907,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:32385 s3api copy-object --bucket awscli-mint-test-bucket-13923 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-13923/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected ae9a3f1d83c6d5c7e2f1abff06064890, got 0x8D84DE648AFDBEB-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 5 minutes and 23 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 43 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 36 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 43 seconds
(11/15) Running minio-py tests ... done in 13 minutes and 5 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 21 seconds
(13/15) Running s3select tests ... done in 54 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#aa19b844-b180-4364-8c74-1d63beb61e42) |
| mint-zoned.sh | :x: [more...](#a5aeebc5-effb-4ec6-a8de-67e330623557) |
<a name="a5aeebc5-effb-4ec6-a8de-67e330623557"></a>
### 10391-d5a1c62/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32047
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cfed73743bfd:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 16 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 18 seconds
(8/15) Running minio-dotnet tests ... done in 46 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 23 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 38 seconds
(11/15) Running minio-js tests ... done in 1 minutes and 5 seconds
(12/15) Running minio-py tests ... done in 3 minutes and 22 seconds
(13/15) Running s3cmd tests ... FAILED in 32 seconds
{
  "name": "s3cmd",
  "duration": "16696",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="aa19b844-b180-4364-8c74-1d63beb61e42"></a>
### 10391-d5a1c62/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31364
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0506e4f60e3b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 57 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 45 seconds
{
  "name": "awscli",
  "duration": 3932,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:31364 s3api copy-object --bucket awscli-mint-test-bucket-16594 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-16594/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected ae9a3f1d83c6d5c7e2f1abff06064890, got 0x8D84E20219607DC-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 31 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 38 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 45 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 29 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 41 seconds
(11/15) Running minio-py tests ... done in 13 minutes and 3 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 15 seconds
(13/15) Running s3select tests ... done in 54 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10391-d5a1c62

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#a1d3a48a-b39c-4a13-8009-b379c44fd2f8) |
| mint-gateway-azure.sh | :x: [more...](#b19f2f4f-6a1e-41eb-b031-c487d4de1830) |
<a name="b19f2f4f-6a1e-41eb-b031-c487d4de1830"></a>
### 10391-6a2ca5c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30775
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dec56566294d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 59 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... FAILED in 45 seconds
{
  "name": "awscli",
  "duration": 3938,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:30775 s3api copy-object --bucket awscli-mint-test-bucket-15849 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-15849/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected ae9a3f1d83c6d5c7e2f1abff06064890, got 0x8D84E27F6632797-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 6 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 46 seconds
{
  "args": {
    "bucketName": "minio-go-test-ls50zc4hxd2fhy9p",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 707,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 7 minutes and 31 seconds
(9/15) Running minio-js tests ... FAILED in 48 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 75,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 12 minutes and 38 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 11 seconds
(11/15) Running s3select tests ... done in 46 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="a1d3a48a-b39c-4a13-8009-b379c44fd2f8"></a>
### 10391-6a2ca5c/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32634
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6f2494cdf2e4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 59 seconds
{
  "name": "awscli",
  "duration": 63241,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:32634 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-13901/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-13901/datafile-0-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-13901/datafile-1-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-13901/datafile-1-bupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-13901/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-13901/datafile-100-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-13901/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-13901/datafile-1-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-13901/datafile-5-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-13901/datafile-6-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-13901/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-13901/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-13901/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-13901/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-13901/datafile-129-MBupload failed: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-13901/datafile-10-kB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 36 seconds
(7/15) Running minio-dotnet tests ... done in 34 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 7 seconds
(9/15) Running minio-java tests ... done in 43 seconds
(10/15) Running minio-js tests ... done in 41 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 3 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 5 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10391-6a2ca5c

**Review by nitisht — APPROVED** [review]
LGTM

**Pull request merged**
