### PR TITLE
Use syscall.exec for server restarts

### LINKED ISSUE #7350: Use execve for restart or disallow Minio restart admin command per deployment
I'd like to have an option to disable the ability to restart Minio via the admin API, or make the restart use `execve` directly without doing a `fork` (currently it uses `exec.Start`, which does a usual `fork+exec` under the hood).

Rationale is when Minio is deployed under systemd with `Type=simple` and auto-restart enabled at the systemd level, when minio restarts itself the system can end up with two `minio` processes after the restart - one started by the old `minio` process as a part of processing the restart command issued by admin, and one by systemd as a reaction to the old `minio` process termination. In this scenario, it is preferred to only have `minio` process started by systemd, as it is managed by the system, while the other process - the one that was started by `minio` itself as a restart routine - is not managed by anything.

There are two possible solutions for this problem:

1. Use [syscall.Exec](https://golang.org/pkg/syscall/#Exec) to issue `execve` directly. It solves this and a few other problems - like changed pid of the process, which is an issue if you're using pid lockfiles for process management.
2. Add the ability to disallow invoking `restart` service command (i.e. `mc admin service restart`) for a particular Minio deployment, preferably via an env var.

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description

This fixes varying pids for server-respawns. And avoids duplicate process
creating multiple pids when the server restart signal is triggered with
service restart configured to `Always`.

## Motivation and Context
Fixes #7350

## Regression
No

## How Has This Been Tested?
- Bring-up minio.service with the steps provided in `https://github.com/minio/minio-service`
- The restart option is configured to `Always` by default.
- Start the minio.service with `systemctl start minio.service`
- Now if we hit `mc admin service restart <alias>` We can see the the process restarted with a new pid. (which is fixed in this PR)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by harshavardhana — DISMISSED** [review]
LGTM

**Comment by Praveenrajmani** [comment]
Have added a comment on the change. PTAL @harshavardhana @vadmeste

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#b687006c-fba8-418c-8fc2-3397a1c4277e) |
| mint-large-bucket.sh | :x: [more...](#f2595dae-fd2a-4315-ae3e-cebbf3f262fd) |
<a name="b687006c-fba8-418c-8fc2-3397a1c4277e"></a>
### 7373-8dd7930/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32239
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 79e3c3c55e4a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-k1jp2nsrpnr1n2",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 308,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:32239/aws-sdk-go-test-k1jp2nsrpnr1n2: dial tcp 72.28.97.61:32239: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f2595dae-fd2a-4315-ae3e-cebbf3f262fd"></a>
### 7373-8dd7930/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32657
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f1d7269cc230:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-g50kawvnv3tjvv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 274,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32657/aws-sdk-go-test-g50kawvnv3tjvv: dial tcp 72.28.97.57:32657: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by vadmeste — APPROVED** [review]
LGTM & tested with Docker

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#9ea875a4-e075-458d-b0f4-12405fce8ce6) |
| mint-gateway-nas.sh | :x: [more...](#185b0102-6c3c-46eb-a0f9-f877e9247ad2) |
<a name="9ea875a4-e075-458d-b0f4-12405fce8ce6"></a>
### 7373-872876a/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32628
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 290d711bbbb1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 41 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 22 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 19 seconds
(10/14) Running minio-java tests ... FAILED in 51 seconds
{
  "name": "minio-java",
  "function": "copyObject(String bucketName, String objectName, String destBucketName, CopyConditions copyConditions)",
  "duration": 597,
  "status": "FAIL",
  "error": "java.io.EOFException >>> [okio.RealBufferedSink.write(RealBufferedSink.java:107), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:74), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185), okhttp3.RealCall.execute(RealCall.java:69), io.minio.MinioClient.executeReq(MinioClient.java:1097), io.minio.MinioClient.execute(MinioClient.java:1056), io.minio.MinioClient.executePut(MinioClient.java:1399), io.minio.MinioClient.executePut(MinioClient.java:1421), io.minio.MinioClient.putObject(MinioClient.java:3994), io.minio.MinioClient.putObject(MinioClient.java:4037), io.minio.MinioClient.putObject(MinioClient.java:3578), FunctionalTest.copyObject_test5(FunctionalTest.java:2185), FunctionalTest.runTests(FunctionalTest.java:3043), FunctionalTest.main(FunctionalTest.java:3154)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="185b0102-6c3c-46eb-a0f9-f877e9247ad2"></a>
### 7373-872876a/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31822
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a178d1c4e2cb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 45 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 27 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 33 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 18 seconds
(11/14) Running minio-js tests ... done in 26 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 1 seconds
{
  "status": "FAIL",
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "object_name": "0cdd1cfa-8025-496f-a633-46e965db565b",
    "bucket_name": "minio-py-test-c6b81ae1-5db0-4122-a048-f63d04c5b54d"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 46,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#dfac19f4-ea4e-476d-963e-e9a565cf355b) |
| mint-compression-dist-xl.sh | :x: [more...](#b5e8ae61-58b9-45c7-bf84-3baefe7344e6) |
| mint-dist-xl.sh | :x: [more...](#f68d4e46-dd4e-4b11-b29b-b7e89c3f92a3) |
<a name="b5e8ae61-58b9-45c7-bf84-3baefe7344e6"></a>
### 7373-872876a/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30939
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8e255383e7c9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-v6rpeakwclhoa1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 304,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.51:30939/aws-sdk-go-test-v6rpeakwclhoa1: dial tcp 72.28.97.51:30939: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="dfac19f4-ea4e-476d-963e-e9a565cf355b"></a>
### 7373-872876a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32499
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b6f9b1b6dc63:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0ia1t1z51o6apn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 243,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.52:32499/aws-sdk-go-test-0ia1t1z51o6apn: dial tcp 72.28.97.52:32499: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f68d4e46-dd4e-4b11-b29b-b7e89c3f92a3"></a>
### 7373-872876a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30036
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 942557ed6161:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-y3ptkxer9sxzlg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 244,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:30036/aws-sdk-go-test-y3ptkxer9sxzlg: dial tcp 72.28.97.54:30036: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#580899b1-bca2-488b-aa21-0e46fc0904ba) |
<a name="580899b1-bca2-488b-aa21-0e46fc0904ba"></a>
### 7373-b396a39/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30692
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ba1218e0f5a2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0kd69lqfyw2ogt",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 362,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.56:30692/aws-sdk-go-test-0kd69lqfyw2ogt: dial tcp 72.28.97.56:30692: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Ping @vadmeste

**Comment by MOZGIII** [comment]
Be aware that if you have some locks (or something similar) that rely on different instances of mitio process having different PIDs - that may start to behave differently, and a good fix would be to manually generate some random string per runtime and to probe running processes of whether thy are or are not in posession of the same random string - the mismatch of that random string would signal that the process was restarted (even though is has the same pid).

**Pull request merged**
