### PR TITLE
update go dependencies

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
update go dependencies

## Motivation and Context
keeping it up to date.

## How to test this PR?
Nothing should change.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#9ab9f179-2003-4f84-8e9a-216fdb8dcd7f) |
<a name="9ab9f179-2003-4f84-8e9a-216fdb8dcd7f"></a>
### 16798-e4ff887/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:32577
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 50e610dca5ff:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... FAILED in 1 minutes and 9 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 62312.64,
  "error": "execution expired",
  "status": "FAIL"
}
(4/14) Running awscli tests ... done in 1 minutes and 53 seconds
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... done in 37 seconds
(7/14) Running minio-go tests ... done in 1 minutes and 2 seconds
(8/14) Running minio-java tests ... FAILED in 2 minutes and 15 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 125167,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-3tjv0m8, objectName = null, resource = /minio-java-test-3tjv0m8, requestId = 174BEF42CB2E48DA, hostId = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)\nrequest={method=DELETE, url=http://15.15.15.3:32577/minio-java-test-3tjv0m8, headers=Host: 15.15.15.3:32577\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.6\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20230313T090556Z\nAuthorization: ██\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 356\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Id-2: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nX-Amz-Request-Id: 174BEF42CB2E48DA\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Mon, 13 Mar 2023 09:05:56 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(8/14) Running minio-js tests ... done in 52 seconds
(9/14) Running minio-py tests ... done in 4 minutes and 8 seconds
(10/14) Running s3cmd tests ... done in 17 seconds
(11/14) Running s3select tests ... done in 5 seconds
(12/14) Running versioning tests ... done in 3 minutes and 13 seconds

Executed 12 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
LGTM

**Comment by klauspost** [comment]
```
2023-03-13T09:15:16.4154892Z === RUN   TestAPIGetObjectHandler/compressed
2023-03-13T09:15:16.4266011Z ==================
2023-03-13T09:15:16.4266293Z WARNING: DATA RACE
2023-03-13T09:15:16.4266564Z Write at 0x000007eaaef0 by goroutine 380270:
2023-03-13T09:15:16.4266913Z   github.com/minio/minio/cmd.newErasureServerPools()
2023-03-13T09:15:16.4267775Z       /home/runner/work/minio/minio/cmd/erasure-server-pool.go:159 +0x1191
2023-03-13T09:15:16.4268171Z   github.com/minio/minio/cmd.newTestObjectLayer()
2023-03-13T09:15:16.4268707Z       /home/runner/work/minio/minio/cmd/test-utils_test.go:1498 +0x67
2023-03-13T09:15:16.4269056Z   github.com/minio/minio/cmd.initObjectLayer()
2023-03-13T09:15:16.4269590Z       /home/runner/work/minio/minio/cmd/test-utils_test.go:1503 +0x76
2023-03-13T09:15:16.4269914Z   github.com/minio/minio/cmd.prepareFS()
2023-03-13T09:15:16.4270435Z       /home/runner/work/minio/minio/cmd/test-utils_test.go:194 +0xb2
2023-03-13T09:15:16.4270812Z   github.com/minio/minio/cmd.ExecObjectLayerAPITest()
2023-03-13T09:15:16.4271354Z       /home/runner/work/minio/minio/cmd/test-utils_test.go:1750 +0xc6
2023-03-13T09:15:16.4271763Z   github.com/minio/minio/cmd.ExecExtendedObjectLayerAPITest.func1()
2023-03-13T09:15:16.4272346Z       /home/runner/work/minio/minio/cmd/test-utils_test.go:1803 +0x64
2023-03-13T09:15:16.4272705Z   github.com/minio/minio/cmd.execExtended.func2()
2023-03-13T09:15:16.4273167Z       /home/runner/work/minio/minio/cmd/object_api_suite_test.go:570 +0x4b
2023-03-13T09:15:16.4273676Z   testing.tRunner()
2023-03-13T09:15:16.4274107Z       /opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1576 +0x216
2023-03-13T09:15:16.4274413Z   testing.(*T).Run.func1()
2023-03-13T09:15:16.4274851Z       /opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1629 +0x47
2023-03-13T09:15:16.4275049Z 
2023-03-13T09:15:16.4275199Z Previous read at 0x000007eaaef0 by goroutine 380251:
2023-03-13T09:15:16.4275567Z   github.com/minio/minio/cmd.getBucketInfoLocal.func1()
2023-03-13T09:15:16.4276108Z       /home/runner/work/minio/minio/cmd/peer-s3-server.go:138 +0x90
2023-03-13T09:15:16.4276501Z   github.com/minio/minio/internal/sync/errgroup.(*Group).Go.func1()
2023-03-13T09:15:16.4277013Z       /home/runner/work/minio/minio/internal/sync/errgroup/errgroup.go:123 +0x314
2023-03-13T09:15:16.4277217Z 
2023-03-13T09:15:16.4277441Z Goroutine 380270 (running) created at:
2023-03-13T09:15:16.4277688Z   testing.(*T).Run()
2023-03-13T09:15:16.4278121Z       /opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1629 +0x805
2023-03-13T09:15:16.4279205Z   github.com/minio/minio/cmd.execExtended()
2023-03-13T09:15:16.4279663Z       /home/runner/work/minio/minio/cmd/object_api_suite_test.go:567 +0x1b7
2023-03-13T09:15:16.4280085Z   github.com/minio/minio/cmd.ExecExtendedObjectLayerAPITest()
2023-03-13T09:15:16.4280706Z       /home/runner/work/minio/minio/cmd/test-utils_test.go:1802 +0xf2
2023-03-13T09:15:16.4281084Z   github.com/minio/minio/cmd.TestAPIGetObjectHandler()
2023-03-13T09:15:16.4281639Z       /home/runner/work/minio/minio/cmd/object-handlers_test.go:332 +0x134
2023-03-13T09:15:16.4281933Z   testing.tRunner()
2023-03-13T09:15:16.4282365Z       /opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1576 +0x216
2023-03-13T09:15:16.4282653Z   testing.(*T).Run.func1()
2023-03-13T09:15:16.4283099Z       /opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1629 +0x47
2023-03-13T09:15:16.4283291Z 
2023-03-13T09:15:16.4283412Z Goroutine 380251 (finished) created at:
2023-03-13T09:15:16.4283761Z   github.com/minio/minio/internal/sync/errgroup.(*Group).Go()
2023-03-13T09:15:16.4284250Z       /home/runner/work/minio/minio/internal/sync/errgroup/errgroup.go:105 +0x10e
2023-03-13T09:15:16.4284623Z   github.com/minio/minio/cmd.getBucketInfoLocal()
2023-03-13T09:15:16.4285160Z       /home/runner/work/minio/minio/cmd/peer-s3-server.go:137 +0x2bd
2023-03-13T09:15:16.4285520Z   github.com/minio/minio/cmd.(*S3PeerSys).GetBucketInfo()
2023-03-13T09:15:16.4286055Z       /home/runner/work/minio/minio/cmd/peer-s3-client.go:142 +0x233
2023-03-13T09:15:16.4286451Z   github.com/minio/minio/cmd.(*erasureServerPools).GetBucketInfo()
2023-03-13T09:15:16.4287027Z       /home/runner/work/minio/minio/cmd/erasure-server-pool.go:1600 +0x115
2023-03-13T09:15:16.4287400Z   github.com/minio/minio/cmd.checkBucketExist()
2023-03-13T09:15:16.4288050Z       /home/runner/work/minio/minio/cmd/object-api-input-checks.go:204 +0xae
2023-03-13T09:15:16.4288426Z   github.com/minio/minio/cmd.checkListObjsArgs()
2023-03-13T09:15:16.4288983Z       /home/runner/work/minio/minio/cmd/object-api-input-checks.go:67 +0xc0
2023-03-13T09:15:16.4289376Z   github.com/minio/minio/cmd.(*erasureServerPools).Walk()
2023-03-13T09:15:16.4289946Z       /home/runner/work/minio/minio/cmd/erasure-server-pool.go:1765 +0x144
2023-03-13T09:15:16.4290330Z   github.com/minio/minio/cmd.listIAMConfigItems.func1()
2023-03-13T09:15:16.4290891Z       /home/runner/work/minio/minio/cmd/iam-object-store.go:509 +0x158
2023-03-13T09:15:16.4291157Z ==================
2023-03-13T09:15:18.5427060Z     testing.go:1446: race detected during execution of test
```
Doesn't appear related, and in test framework setup. Re-running test and also seeing if I can fix the issue (`globalLocalDrives` being reset without locks)

Edit: Fix in https://github.com/minio/minio/pull/16800

**Comment by klauspost** [comment]
Seems like upgrading dependencies for whatever triggers this more often. Fix is in https://github.com/minio/minio/pull/16800

**Comment by klauspost** [comment]
What is happening here?
```
Error: listPathRaw: 0 drives provided (*errors.errorString)
       5: internal/logger/logger.go:258:logger.LogIf()
       4: cmd/api-errors.go:2273:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:[229](https://github.com/minio/minio/actions/runs/4405245152/jobs/7715885067#step:5:230)8:cmd.toAPIError()
       2: cmd/bucket-listobjects-handlers.go:249:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2122:http.HandlerFunc.ServeHTTP()
```

`disks, _ := (erasureObjects).getOnlineDisksWithHealing()` -> (erasureObjects).getDisks() -> https://github.com/minio/minio/blob/b4ef5ff294021932ef26198173dfca0bc808d5d1/cmd/erasure-sets.go#L337

Either `(erasureObjects).setDriveCount == 0` or no non-healing disks are found (slightly more likely).

Seems like something is breaking with this upgrade.

**Comment by harshavardhana** [comment]
> What is happening here?
> 
> ```
> Error: listPathRaw: 0 drives provided (*errors.errorString)
>        5: internal/logger/logger.go:258:logger.LogIf()
>        4: cmd/api-errors.go:2273:cmd.toAPIErrorCode()
>        3: cmd/api-errors.go:[229](https://github.com/minio/minio/actions/runs/4405245152/jobs/7715885067#step:5:230)8:cmd.toAPIError()
>        2: cmd/bucket-listobjects-handlers.go:249:cmd.objectAPIHandlers.ListObjectsV2Handler()
>        1: net/http/server.go:2122:http.HandlerFunc.ServeHTTP()
> ```
> 
> `disks, _ := (erasureObjects).getOnlineDisksWithHealing()` -> (erasureObjects).getDisks() ->
> 
> https://github.com/minio/minio/blob/b4ef5ff294021932ef26198173dfca0bc808d5d1/cmd/erasure-sets.go#L337
> 
> Either `(erasureObjects).setDriveCount == 0` or no non-healing disks are found (slightly more likely).
> 
> Seems like something is breaking with this upgrade.

No @klauspost this happens sporadically I have observed it in clusters with flaky DNS, it is entirely possible to have all disks offline in a set and Listing() arrives at that point you get `0 drives provided` error.

**Comment by klauspost** [comment]
Ah yeah. That sounds like a very reasonable explanation.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#68a5d9ab-adef-456e-8446-2fa2df2691ac) |
<a name="68a5d9ab-adef-456e-8446-2fa2df2691ac"></a>
### 16798-a083f20/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:31020
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 2c06d4e73bff:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 41 seconds
{
  "name": "mc",
  "duration": "40438",
  "function": "test_rb",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21193 --quiet --no-color cp /mint/data/datafile-1-MB myminio/mc-test-bucket-15248-1/mc-test-object-32274  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-15248-1/mc-test-object-32274`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Get \"http://15.15.15.8:31020/mc-test-bucket-15248-1/?location=\": dial tcp 15.15.15.8:31020: i/o timeout\nTotal: 0 B, Transferred: 0 B, Speed: 0 B/s"
}
(7/14) Running minio-go tests ... done in 1 minutes and 48 seconds
(8/14) Running minio-java tests ... done in 18 seconds
(9/14) Running minio-js tests ... done in 45 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 25 seconds
(11/14) Running s3cmd tests ... done in 2 minutes and 13 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 15 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by poornas — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#68a759e1-023f-4746-be80-8a168392a7cb) |
<a name="68a759e1-023f-4746-be80-8a168392a7cb"></a>
### 16798-1f41a32/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:31110
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 78cd2adf35e6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 10 seconds
(5/14) Running awscli tests ... done in 1 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 19 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 5 seconds
(9/14) Running minio-java tests ... done in 37 seconds
(10/14) Running minio-js tests ... done in 52 seconds
(11/14) Running minio-py tests ... FAILED in 51 seconds
{
  "name": "minio-py:test_stat_object",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-c3bf1b43-fd6c-4269-b69f-6e3505681f88",
    "object_name": "7fe03d96-cdc1-4f6d-bc9a-139a82d54535-metadata",
    "length": 11534336,
    "data": "LimitedRandomReader(11 * MB)",
    "metadata": {
      "X-Amz-Meta-Testing": "value"
    },
    "content_type": "application/octet-stream"
  },
  "message": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 820, in test_stat_object\n    _test_stat_object(log_entry, sse)\n  File \"/mint/run/core/minio-py/tests.py\", line 794, in _test_stat_object\n    result = _CLIENT.put_object(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1766, in put_object\n    raise exc\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1725, in put_object\n    upload_id = self._create_multipart_upload(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1565, in _create_multipart_upload\n    response = self._execute(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 403, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 266, in _url_open\n    response = self._http.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n",
  "duration": 34132
}
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
