### PR TITLE
Return the line number of the syntax error when found by json.Unmarshal - WIP

### PR DESCRIPTION
**Pull request by vadmeste**

### CODE REVIEW

**Comment by vadmeste** [comment]
To show the location of the json syntax error according to this template :

```
      version" :  5, 
      ^
```

we need to calculate the width of the terminal to avoid printing overlapping lines, however if the json file contains TAB characters, we should know how much space a terminal allocates for a TAB character to make sure that '^' character will be placed exactly below the json error position. I cannot find how to do that under Windows, but if Windows cannot provide us this information, we still can replace all TAB with a chosen number of spaces.

**Comment by harshavardhana** [comment]
> we need to calculate the width of the terminal to avoid printing overlapping lines, however if the json file contains TAB characters, we should know how much space a terminal allocates for a TAB character to make sure that '^' character will be placed exactly below the json error position. I cannot find how to do that under Windows, but if Windows cannot provide us this information, we still can replace all TAB with a chosen number of spaces.

Easiest is pick standard tabs width as a default, to avoid this the highlighting can be changed to a single line as 

```
"version" : 5,   <- 
```

Doesn't change the purpose IMHO.

**Comment by vadmeste** [comment]
you may need to update govendor before compiling the project in your local machine. The new version of govendor asked me to migrate, vendor.json was moved to vendor/ directory..

Still not ready for _MERGING_

**Comment by harshavardhana** [comment]
Can you do this "git rebase -i HEAD~4" to squash all your commits into one and remove unnecessary ones ? 

Also revert back govendor to previous version, there seems to be a migration bug which is not working for everyone.

**Comment by vadmeste** [comment]
I tried today to squash as you said, `git log` in my local machine is fine but `git push -f` doesn't correct this PR. I must have done something wrong to reach this situation. However, I think github will smartly merge everything.

Okay pour govendor.

I will create a new clean PR.

**Comment by harshavardhana** [comment]
> I tried today to squash as you said, git log in my local machine is fine but git push -f doesn't correct this PR. I must have done something wrong to reach this situation. However, I think github will smartly merge everything.

You don't have to create a new PR all you have to do is just this

```
$ git rebase origin/master
```

Make sure that your origin here is pointing to the recent change at github.com/minio/minio

**Comment by harshavardhana** [comment]
Next step is 

```
$ git reset HEAD^ --hard

revert 'govendor' to an older version

$ export GO15VENDOREXPERIMENT=1
$ govendor add github.com/olekukonko/ts

then commit .. and same drill 

```

**Comment by vadmeste** [comment]
Could you tell me what's the revision of govendor that you are currently using ?

**Comment by harshavardhana** [comment]
> Could you tell me what's the revision of govendor that you are currently using ?

`99446fd394b24ec992513d719f8c15424714e221`

**Comment by vadmeste** [comment]
It must be okay now (hopefully)

**Comment by harshavardhana** [comment]
> It must be okay now (hopefully)

Really good work! - thank you

**Comment by harshavardhana** [comment]
> are you not using "goimports" and "gofmt" ?

Don't worry about this.. will merge it locally after those changes.

**Comment by vadmeste** [comment]
> are you not using "goimports" and "gofmt" ?

I run make and check what it reports, maybe I didn't pay attention

> $ git rebase origin/master

Thanks for this, I was doing "$ git rebase master" which usually works..

> Really good work! - thank you

Thanks :), the code still allocates more than needed memory in readLine when the input buffer contains large data without new lines.. I will see how to fix that later

**Comment by harshavardhana** [comment]
> I run make and check what it reports, maybe I didn't pay attention

You have to use "goimports" to fix your imports

```
;; Compile key binding
(defun go-mode-setup ()
  "Go mode."
  (global-auto-complete-mode t)
  (projectile-global-mode)
  (go-eldoc-setup)
  (setq gofmt-command "goimports")
  (add-hook 'before-save-hook 'gofmt-before-save))
(add-hook 'go-mode-hook 'go-mode-setup)
(setq compilation-scroll-output 'first-error)
```

Would be useful if you are using emacs.

**Pull request closed without merging**
