### PR TITLE
Improvements in logger and audit webhooks

### PR DESCRIPTION
**Pull request by anjalshireesh**
## Description

- When any of the webhooks initialization fails, an error is returned immediately and subsequent configured webhooks are not initialized. Fix this by trying to initialize all the webhooks, capturing their errors (if any).

- The health diagnostics report (and also the JSON output of `mc admin info`) tries to capture status of all configured webhooks. When initialization of any webhook fails, it is not included at all in the JSON. Fix this by capturing even these targets in the HTTP/audit webhooks list (ensuring that `Send` methods doesn't do anything in case the initialization had failed)

- Name of the webhook is not getting captured in the above mentioned JSON. Fix this.

- In case of webhooks where initialization had failed, try to initialize them again whenever `mc admin info` or `mc support diag` is executed that tries to get current status of the target (online/offline)

## Motivation and Context

- Better handling of configured logger and audit webhooks
- More accurate capturing of the webhook targets' statuses in health diagnostics report and `mc admin info` JSON output

## How to test this PR?

- Configure two logger webhooks
- Ensure that one is online and the other is offline
- Run `mc admin info {alias} --json`
- Verify that the statuses of both these are printed correctly in the JSON output e.g.
```json
      "logger": [
          {
            "test1": {
              "status": "online"
            }
          },
          {
            "test2": {
              "status": "offline"
            }
          }
        ],
```
- Bring up the endpoint of the target that is currently offline
- Run `mc admin info {alias} --json`
- Verify that it is now shown as `online` in the output, and that minio starts sending the logs to this endpoint also
- Test the same with audit webhooks as well

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
LGTM

**Review by vadmeste — COMMENTED** [review]
If I am not mistaken, what is missing is retry to re-initialize in Send() when the initialization is failed. Because otherwise, it will indefinitely be offline? No?

You can follow how webhook and kafka bucket notifications is doing

**Comment by anjalshireesh** [comment]
> If I am not mistaken, what is missing is retry to re-initialize in Send() when the initialization is failed. Because otherwise, it will indefinitely be offline? No?
> 
> You can follow how webhook and kafka bucket notifications is doing

@vadmeste retaining current behavior, `Send` will return without doing anything if the target was `offline` when server tried to initialize it. I have added code to automatically try to initialize again (if currently marked offline) during `mc admin info` or `mc support diag` which need to report current status of the targets. I feel trying to initialize in `Send` for an offline target could be an overhead. But can be discussed and added if required in a separate PR.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#bb178891-65ba-4d4c-9143-a1bca04b2e0d) |
<a name="bb178891-65ba-4d4c-9143-a1bca04b2e0d"></a>
### 16102-1f308f9/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:32662
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 2a7af68745c4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... FAILED in 2 seconds
Nov 23, 2022 8:22:03 AM com.amazonaws.util.Base64 warn
WARNING: JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided) (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 172A29076FA01CFD; S3 Extended Request ID: 03655aad-51d3-4c97-9f5d-0e93f9a0c1b2), S3 Extended Request ID: 03655aad-51d3-4c97-9f5d-0e93f9a0c1b2
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1347)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4992)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:895)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:863)
	at io.minio.awssdk.tests.FunctionalTests.teardown(Unknown Source)
	at io.minio.awssdk.tests.FunctionalTests.main(Unknown Source)
(2/14) Running aws-sdk-php tests ... done in 43 seconds
(3/14) Running aws-sdk-ruby tests ... done in 7 seconds
(4/14) Running awscli tests ... FAILED in 22 seconds
{
  "name": "awscli",
  "duration": 12132,
  "function": "aws --endpoint-url http://15.15.15.6:32662 s3api list-objects --bucket awscli-mint-test-bucket-401 --prefix datafile-1-kB\n",
  "status": "FAIL",
  "error": ""
}
(4/14) Running healthcheck tests ... done in 0 seconds
(5/14) Running mc tests ... done in 37 seconds
(6/14) Running minio-go tests ... done in 1 minutes and 31 seconds
(7/14) Running minio-java tests ... done in 37 seconds
(8/14) Running minio-js tests ... FAILED in 12 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(8/14) Running minio-py tests ... done in 1 minutes and 49 seconds
(9/14) Running s3cmd tests ... done in 24 seconds
(10/14) Running s3select tests ... done in 5 seconds
(11/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 11 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
