### PR TITLE
upgrade mqtt library to v1.4.1

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
upgrade mqtt library to v1.4.1

## Motivation and Context
mainly to address some connect()/reconnect() packet
exhaustion issues, that	were found in some deployments.

## How to test this PR?
Nothing special, according to mqtt library nothing should break.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by cniackz — APPROVED** [review]
LGTM, tested already!.

**Comment by cniackz** [comment]
Thank you @harshavardhana for the update.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#9050f5b1-7042-454c-8696-5a0ad4147ede) |
<a name="9050f5b1-7042-454c-8696-5a0ad4147ede"></a>
### 15366-fcf5ceb/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:32757
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running awscli tests ... done in 1 minutes and 10 seconds
(2/14) Running aws-sdk-go tests ... done in 1 seconds
(3/14) Running aws-sdk-java tests ... done in 2 seconds
(4/14) Running aws-sdk-php tests ... done in 43 seconds
(5/14) Running aws-sdk-ruby tests ... done in 6 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 24 seconds
(9/14) Running minio-java tests ... done in 28 seconds
(10/14) Running minio-js tests ... done in 1 minutes and 4 seconds
(11/14) Running minio-py tests ... FAILED in 6 minutes and 25 seconds
{
  "name": "minio-py:test_remove_object_versions",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-bbd8684e-a01a-46e2-b127-e81b64b1260c",
    "delete_object_list": [
      [
        "prefix-0",
        "5bf55538-56fd-48f1-97a8-4fd3682da1e8"
      ],
      [
        "prefix-1",
        "52437b1e-6252-4313-87ac-3a00d28d2d7f"
      ],
      [
        "prefix-2",
        "6ddf04ee-c81e-4eb5-833e-bee4005aa87b"
      ],
      [
        "prefix-3",
        "aee1faac-0ae1-4514-8304-c4d0c43d6d17"
      ],
      [
        "prefix-4",
        "bd5af75c-7a24-41b6-9a45-412d845f5516"
      ],
      [
        "prefix-5",
        "9e2abf5a-ddb2-4eaf-a1a1-74b404352c2c"
      ],
      [
        "prefix-6",
        "90cfa96b-57b0-41fe-9169-4dc8ce3fe152"
      ],
      [
        "prefix-7",
        "fd426974-275c-451e-b15d-636160b15927"
      ],
      [
        "prefix-8",
        "3d7e1ade-fae8-4b10-91ef-eef6fa2d7898"
      ],
      [
        "prefix-9",
        "6512957e-f999-4ec6-9ee9-e3c914a0db8f"
      ]
    ]
  },
  "message": "HTTPConnectionPool(host='minio-k8s7', port=32757): Read timed out. (read timeout=300)",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1834, in test_remove_object_versions\n    _test_remove_objects(log_entry, version_check=True)\n  File \"/mint/run/core/minio-py/tests.py\", line 1817, in _test_remove_objects\n    for err in errs:\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1989, in remove_objects\n    result = self._delete_objects(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1922, in _delete_objects\n    response = self._execute(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 403, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 266, in _url_open\n    response = self._http.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py\", line 770, in reraise\n    raise value\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 451, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 340, in _raise_timeout\n    raise ReadTimeoutError(\nurllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='minio-k8s7', port=32757): Read timed out. (read timeout=300)\n",
  "duration": 307517
}
(11/14) Running s3cmd tests ... done in 25 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
