### PR TITLE
IAM import test with missing entities

### PR DESCRIPTION
**Pull request by shtripat**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## How to test this PR?
Needs https://github.com/minio/minio/pull/20352

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by harshavardhana** [comment]
@shtripat test seems to be broken

```
/home/runner/work/minio/minio/docs/distributed/iam-import-with-missing-entities.sh: line 29: minio: command not found
mc: <ERROR> Couldn't construct anonymous client for `myminio`. No valid configuration found for 'myminio' host alias.
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://localhost:9000/probe-bsign-eqyeiwwl65xson5q0j96mm4al91ykb/?location=": dial tcp [::1]:9000: connect: connection refused.
mc: <ERROR> Unable to initialize admin connection. No valid configuration found for 'myminio' host alias.
mc: <ERROR> Unable to initialize admin connection. No valid configuration found for 'myminio' host alias.
mc: <ERROR> Unable to initialize admin client. No valid configuration found for 'myminio' host alias.
mc: <ERROR> Unable to initialize admin connection. No valid configuration found for 'myminio' host alias.
mc: <ERROR> Unable to initialize admin connection. No valid configuration found for 'myminio' host alias.
BUG: Expected no of users: 6 Found: 0
```

**Comment by harshavardhana** [comment]
```
Docs: https://docs.min.io
WARN: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
mc: <ERROR> Couldn't construct anonymous client for `myminio`. No valid configuration found for 'myminio' host alias.
Added `myminio` successfully.
Successfully applied new settings.
Please restart your server 'mc admin service restart myminio'.
mc: <ERROR> Unable to initialize service restart UI: could not open a new TTY: open /dev/tty: no such device or address.
The cluster is ready
Added policies: consoleAdmin, diagnostics, readonly, readwrite, writeonly
Added service accounts: bobfisher-svcacct-1, bobfisher-svcacct-2, dillon-svcacct-1, dillon-svcacct-2
Added policies for sts: uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io, uid=dillon,ou=people,ou=swengg,dc=min,dc=io
BUG: Expected no of users: 2 Found: 0
make: *** [Makefile:102: test-iam-import-with-missing-entities] Error 1
Error: Process completed with exit code 2.
```

You may use `--json` or something with `mc admin service restart` @shtripat

**Comment by harshavardhana** [comment]
> mc: <ERROR> Couldn't construct anonymous client for `myminio`. No valid configuration found for 'myminio' host alias.

you can use `export MC_HOST_myminio` in the beginning of the test.

**Comment by shtripat** [comment]
Is below error related to recent actual size change
```
(9/15) Running minio-go tests ... FAILED in 47 seconds
{
  "time": "2024-09-12T04:41:30.724187329Z",
  "level": "ERROR",
  "name": "minio-go: testSSES3EncryptedGetObjectReadSeekFunctional",
  "duration": 2115,
  "function": "GetObject(bucketName, objectName)",
  "args": {
    "bucketName": "minio-go-test-om40mp5fhgkidf39",
    "objectName": "dauw2braypw3qhc115ttxq2luouu04"
  },
  "status": "FAIL",
  "message": "Incorrect read bytes v/s original buffer"
}
```

**Comment by harshavardhana** [comment]
> (9/15) Running minio-go tests ... FAILED in 47 seconds
> {
>   "time": "2024-09-12T04:41:30.724187329Z",
>   "level": "ERROR",
>   "name": "minio-go: testSSES3EncryptedGetObjectReadSeekFunctional",
>   "duration": 2115,
>   "function": "GetObject(bucketName, objectName)",
>   "args": {
>     "bucketName": "minio-go-test-om40mp5fhgkidf39",
>     "objectName": "dauw2braypw3qhc115ttxq2luouu04"
>   },
>   "status": "FAIL",
>   "message": "Incorrect read bytes v/s original buffer"
> }

Not really. This has happened for some time now. Its compression + encryption related, but there is no conclusive evidence.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
