### PR TITLE
xl: Remove wrong wording for errCorruptedFormat

### PR DESCRIPTION
**Pull request by vadmeste**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Also add errCorruptedBackend to make it easier to differentiate between
corrupted content or something else wrong in the backend drive

## Motivation and Context
Better error messages

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
We are having some random mint failures with latest minio-js release.

```
(10/14) Running minio-js tests ... FAILED in 3 minutes and 22 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 8,
  "status": "FAIL",
  "error": "S3Error: The specified bucket does not exist at parseError (minio-js/src/internal/xml-parser.ts:26:13) at Object.parseResponseError (minio-js/src/internal/xml-parser.ts:75:11) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Client.makeRequestStreamAsync (minio-js/src/internal/client.ts:629:19) at Client.makeRequestAsyncOmit (minio-js/src/internal/client.ts:550:17) at Client.removeBucket (minio-js/src/internal/client.ts:796:5)"
```

**Comment by harshavardhana** [comment]
@prakashsvmx ^^

**Review by harshavardhana — APPROVED** [review]

**Comment by prakashsvmx** [comment]
I have run the mino-js  tests locally it all passes.   i will investigate further as minio-js was release ~4 months back.

**Comment by harshavardhana** [comment]
> I have run the mino-js tests locally it all passes. i will investigate further as minio-js was release ~4 months back.

the failure is sporadic @prakashsvmx

**Pull request merged**
