### PR TITLE
Adjusts help content dynamically according to OS

### LINKED ISSUE #7598: Service help description wrong for windows user
On Windows `export` not working to set enviorment variable, use `SET` instead.
https://stackoverflow.com/questions/18701783/windows-equivalent-of-export

File to change [server-main.go](https://github.com/minio/minio/blob/091b9b661fe79f992af8167e17b794977f9214cf/cmd/server-main.go)

### PR DESCRIPTION
**Pull request by ebozduman**
## Summary
Fixes #7598 (Service help description wrong for windows user)
Our help content does not dynamically adjusts the content according to OS, like when setting an environment variable, the command `export <env-name>=<value>` in Linux/Unix bash becomes `set <env-name>=<value>` in Windows. Command line prompt is also needs to be adjusted as `$` for Linux and `C:\>` for Windows.
## Description
3 new help variables are defined; one for the prompt, one for the set command and a third variable for assignment operator. In case, if we want to dynamically sense the shell and adjust accordingly.
## Motivation and Context
Community filed the issue.
## Regression
No
## How Has This Been Tested?
Yes. I've tested on Linux (Ubuntu) and Windows (10)
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#654708bf-d5a7-45a7-a2e2-8ec02b026144) |
| mint-compression-dist-xl.sh | :x: [more...](#41863086-8c91-4666-92a6-0d46f75af8a3) |
<a name="654708bf-d5a7-45a7-a2e2-8ec02b026144"></a>
### 7646-3c5dc4c/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30619
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp de54705e7ccf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cdb5675cb367",
    "Object": "obj1"
  },
  "duration": "386",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.58:30619/aws-sdk-php-5cdb5675cb367/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.58:30619/aws-sdk-php-5cdb5675cb367/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cdb5675cb367</BucketName><Resource>/aws-sdk-php-5cdb5675cb367/obj1-copy-0</Resource><RequestId>159EB224570089B7</RequestId><HostId>1bf13159-23bd-4aa8-861e-3689a47c8eae</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="41863086-8c91-4666-92a6-0d46f75af8a3"></a>
### 7646-3c5dc4c/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31093
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d13d08d200ae:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cdb567680f41",
    "Object": "obj1"
  },
  "duration": "541",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.57:31093/aws-sdk-php-5cdb567680f41/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.57:31093/aws-sdk-php-5cdb567680f41/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cdb567680f41</BucketName><Resource>/aws-sdk-php-5cdb567680f41/obj1-copy-0</Resource><RequestId>159EB2248B440743</RequestId><HostId>aaf1f1d1-5a99-4262-91e1-5dd967915b81</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 7646-82d4508/gopath/src/github.com/minio
+ git -C 7646-82d4508/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 7646-82d4508/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 7646-82d4508/gopath/src/github.com/minio/minio fetch --quiet minio pull/7646/head:pr7646
+ git -C 7646-82d4508/gopath/src/github.com/minio/minio checkout --quiet pr7646
+ GO111MODULE=on
+ GOPATH=/mnt/nvme/mint-auto/7646-82d4508/gopath
+ make -C 7646-82d4508/gopath/src/github.com/minio/minio --quiet
go: errors parsing go.mod:
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:40: invalid module version "HEAD": unrecognized import path "<<<<<<<" (import path does not begin with hostname)
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:42: usage: require module/path v1.2.3
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:44: usage: require module/path v1.2.3
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:62: invalid module version "HEAD": unrecognized import path "<<<<<<<" (import path does not begin with hostname)
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:66: usage: require module/path v1.2.3
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:69: usage: require module/path v1.2.3
go: errors parsing go.mod:
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:40: invalid module version "HEAD": unrecognized import path "<<<<<<<" (import path does not begin with hostname)
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:42: usage: require module/path v1.2.3
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:44: usage: require module/path v1.2.3
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:62: invalid module version "HEAD": unrecognized import path "<<<<<<<" (import path does not begin with hostname)
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:66: usage: require module/path v1.2.3
/mnt/nvme/mint-auto/7646-82d4508/gopath/src/github.com/minio/minio/go.mod:69: usage: require module/path v1.2.3
make: *** [build] Error 1

```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by harshavardhana — APPROVED** [review]

**Review by Praveenrajmani — APPROVED** [review]
LGTM

**Pull request merged**
