### PR TITLE
api: Allow reconnection of policy/notification rpc clients.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Since we moved out reconnection logic from net-rpc-client.go
we should do it from the top-layer properly and bring back
the code to reconnect properly in-case the connection is lost.

## Motivation and Context
Reconnection is handled by top layer not internally in net-rpc-client.go

## How Has This Been Tested?
make test and distributed setup. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by donatello — APPROVED** [review]

**Comment by krisis** [comment]
@harshavardhana I still see code in the Call() method, in net-rpc-client.go, to connect if the underlying rpc connection was found disconnected. Do we still need to try once more for policy change notifications alone?

**Comment by harshavardhana** [comment]
> @harshavardhana I still see code in the Call() method, in net-rpc-client.go, to connect if the underlying rpc connection was found disconnected. Do we still need to try once more for policy change notifications alone?

Where do you see? @krisis - rpclocalStack is not nil on the first attempt here since it is not proactively closed yet.

**Comment by harshavardhana** [comment]
> Where do you see? @krisis - rpclocalStack is not nil on the first attempt here since it is not proactively closed yet.

This now tells me that i need to Close() first.

**Comment by krisis** [comment]
@harshavardhana Ok, I overlooked the fact that the Call() method doesn't call clearRPCClient(), to trigger a reconnect on subsequent invocation of Call().

**Pull request merged**
