### PR TITLE
fix nats TLS unit tests

### PR DESCRIPTION
**Pull request by aead**
## Description
This commit fixes the nats TLS tests by generating new certificates
(root CA, server and client) - each valid for 10y. The new certificates
don't have a common name (deprecated by X.509) but SANs instead.

Since Go 1.15 the Go `crypto/x509` package rejects certificates that
only have a common name and no SAN. See: https://golang.org/doc/go1.15#commonname

## Motivation and Context
TLS, Go 1.15

## How to test this PR?
Inspect the certificate with `openssl x509 -text -noout -in <certificate>.pem`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
Thanks a bunch!

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#3fe466b3-0976-48c3-bec1-1db3e9de613d) |
| mint-zoned.sh | :x: [more...](#bfccf46d-994f-4e49-8e80-10fb822e3590) |
| mint-gateway-nas.sh | :x: [more...](#4900ea80-d8df-4696-bd1b-92d0101648f4) |
<a name="bfccf46d-994f-4e49-8e80-10fb822e3590"></a>
### 10476-c7167a2/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32602
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 668493dc6100:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 4 minutes and 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-v05rlqp9ydj9vo",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 242793,
  "error": "BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.\n\tstatus code: 409, request id: 1634A83C0660FD40, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-java tests ... done in 1 seconds
(2/15) Running aws-sdk-php tests ... done in 45 seconds
(3/15) Running aws-sdk-ruby tests ... FAILED in 3 seconds
{
  "name": "aws-sdk-ruby",
  "function": "makeBucket(bucket_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-340f8db9cf38"
  },
  "duration": 2166.34,
  "error": "Please reduce your request",
  "status": "FAIL"
}
(3/15) Running awscli tests ... FAILED in 7 seconds
{
  "name": "awscli",
  "duration": 5785,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (SlowDown) when calling the CreateBucket operation (reached max retries: 4): Please reduce your request"
}
(3/15) Running healthcheck tests ... done in 0 seconds
(4/15) Running mc tests ... FAILED in 1 minutes and 12 seconds
{
  "name": "mc",
  "duration": "71693",
  "function": "test_make_bucket",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-13096 --quiet --no-color mb myminio/mc-test-bucket-6967  >>> \nmc: <ERROR> Unable to make bucket `myminio/mc-test-bucket-6967`. Please reduce your request"
}
(4/15) Running minio-dotnet tests ... FAILED in 18 seconds
{
  "name": "minio-dotnet : RemoveObject_Test1",
  "function": "Task RemoveObjectAsync(string bucketName, string objectName, CancellationToken cancellationToken = default(CancellationToken))",
  "args": {
    "bucketName": "miniodotnet1vyku5zdv5fowtz",
    "objectName": "b}&[ad$&)c"
  },
  "duration": 15,
  "status": "FAIL",
  "alert": "",
  "message": "MinIO API responded with message=Please reduce your request",
  "error": "Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=Please reduce your request\n   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 538\n   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 431\n   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 605\n   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 405\n   at Minio.MinioClient.MakeBucketAsync(String bucketName, String location, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 98\n   at Minio.Functional.Tests.FunctionalTest.Setup_Test(MinioClient minio, String bucketName) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 374\n   at Minio.Functional.Tests.FunctionalTest.RemoveObject_Test1(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2011"
}
(4/15) Running minio-go tests ... done in 1 minutes and 26 seconds
(5/15) Running minio-java tests ... done in 1 minutes and 19 seconds
(6/15) Running minio-js tests ... done in 55 seconds
(7/15) Running minio-py tests ... done in 3 minutes and 22 seconds
(8/15) Running s3cmd tests ... done in 20 seconds
(9/15) Running s3select tests ... done in 7 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="3fe466b3-0976-48c3-bec1-1db3e9de613d"></a>
### 10476-c7167a2/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32134
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 51c91715a97a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 23 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 45 seconds
{
  "name": "awscli",
  "duration": 4338,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:32134 s3api copy-object --bucket awscli-mint-test-bucket-27430 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-27430/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D858AEAEC6FA46-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 57 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(8/15) Running minio-go tests ... FAILED in 3 minutes and 17 seconds
{
  "args": {
    "bucketName": "minio-go-test-ruzwfnqalkx2a39y",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 681,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 7 minutes and 32 seconds
(9/15) Running minio-js tests ... FAILED in 44 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 76,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 13 minutes and 57 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 10 seconds
(11/15) Running s3select tests ... done in 34 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="4900ea80-d8df-4696-bd1b-92d0101648f4"></a>
### 10476-c7167a2/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30205
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dbf0f03632a9:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 16 minutes and 20 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5f5f69b682a27"
  },
  "duration": "978637",
  "status": "FAIL",
  "error": "Error executing \"CreateBucket\" on \"http://minio-c2.minio.io:30205/aws-sdk-php-5f5f69b682a27\"; AWS HTTP error: Client error: `PUT http://minio-c2.minio.io:30205/aws-sdk-php-5f5f69b682a27` resulted in a `403 Forbidden` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the reque (truncated...)\n RequestTimeTooSkewed (client): The difference between the request time and the server's time is too large. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the server&#39;s time is too large.</Message><Resource>/aws-sdk-php-5f5f69b682a27</Resource><RequestId></RequestId><HostId>86c83b87-04ec-4a52-92fe-ae4f54f79560</HostId></Error>"
}
(3/15) Running aws-sdk-ruby tests ... done in 1 seconds
(4/15) Running awscli tests ... done in 2 minutes and 3 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 17 seconds
(7/15) Running minio-dotnet tests ... done in 27 seconds
(8/15) Running minio-go tests ... done in 29 seconds
(9/15) Running minio-java tests ... done in 17 seconds
(10/15) Running minio-js tests ... done in 31 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 2 seconds
(12/15) Running s3cmd tests ... done in 13 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10476-c7167a2

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#a465c69d-36b4-448d-83ad-01f81a46ef45) |
<a name="a465c69d-36b4-448d-83ad-01f81a46ef45"></a>
### 10476-b16277c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31593
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a769ebc45b32:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 21 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 44 seconds
{
  "name": "awscli",
  "duration": 3945,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31593 s3api copy-object --bucket awscli-mint-test-bucket-26005 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-26005/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D858B53E2690F9-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 55 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 45 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 41 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 33 seconds
(11/15) Running minio-py tests ... done in 13 minutes and 11 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 23 seconds
(13/15) Running s3select tests ... done in 1 minutes and 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10476-b16277c

**Pull request merged**
