### PR TITLE
Remove bootstrap platform check (#12202)

### PR DESCRIPTION
**Pull request by noahwilliamsson**
## Description

This removes a platform check preventing use of mixed hardware platforms (e.g. ARM64 and AMD64) in a distributed MinIO setup.

This check was originally introduced in #8550 (Add bootstrap REST handler for verifying server config) about 18 months ago (Nov, 2019).

As noted in a performance benchmark posted on https://blog.min.io/intel_vs_gravitron/ (June, 2020):

> [...] what is clear is that the ARM architecture, with the introduction of the Graviton2 processor by AWS, has closed the performance gap to Intel and even surpassed it for multi-core performance

So let's drop it.

## Motivation and Context

See #12202.

## How to test this PR?

Follow the instructions in https://docs.min.io/docs/distributed-minio-quickstart-guide.html and bring up MinIO on three nodes:

- two on AMD64 based hardware platforms (e.g. your PC)
- one on a different hardware platform (e.g. Raspberry Pi 4 with a 64-bit OS)

After the initial setup, restart MinIO one the nodes and confirm that none of them no longer fails with e.g.:

> incorrect configuration: Expected platform 'OS: linux | Arch: arm64', found to be running 'OS: linux | Arch: amd64'

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#1d9eefb8-8e0b-4cbe-bab3-00b88cac28c9) |
<a name="1d9eefb8-8e0b-4cbe-bab3-00b88cac28c9"></a>
### 12203-b41f5d7/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32190
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5f3dcc0d7ddb:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2488,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:32190 s3api copy-object --bucket awscli-mint-test-bucket-27502 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-27502/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 43 seconds
(7/15) Running minio-dotnet tests ... done in 47 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 57 seconds
{
  "args": {},
  "duration": 544,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 7 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 173,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-26lrvug, objectName = minio-java-test-2g6d5bh-copy, resource = /minio-java-test-26lrvug/minio-java-test-2g6d5bh-copy, requestId = 167B440DC8C27B9A, hostId = 6689dea9-bf7f-4fb8-b96e-4f741e158d0b)\nrequest={method=PUT, url=http://minio-dev7.minio.io:32190/minio-java-test-26lrvug/minio-java-test-2g6d5bh-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-13coufj/minio-java-test-2g6d5bh\nHost: minio-dev7.minio.io:32190\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210502T134836Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210502/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Sun, 02 May 2021 13:48:36 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167B440DC8C27B9A\nX-Xss-Protection: 1; mode=block\nDate: Sun, 02 May 2021 13:48:36 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 46 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 52 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2684",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-9739/s3cmd-test-object-26047 560f2b88-3228-4c70-ba94-b58b1ecae1ba\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 560f2b88-3228-4c70-ba94-b58b1ecae1ba put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — CHANGES_REQUESTED** [review]
why should we drop it? @noahwilliamsson  doesn't make sense.  We want customers to deploy in homogenous hardware.

This behavior as per requirement - the blog that you are posting is not justification for this change. Even there it is expected that if you are using ARM64 use all ARM64 do not mix and match.

**Comment by noahwilliamsson** [comment]
Hi,

Thanks for the quick feedback here and in #12202.

In the linked issue, you wrote that serious deployments should use hardware of equal performance metrics as well as the fact that you _want_ your customers to adhere to these requirements.

I understand and acknowledge these arguments.  I'll also note that something similar is already stated in bold in the documentation at https://docs.min.io/docs/distributed-minio-quickstart-guide.html:

> All the nodes running distributed MinIO setup are recommended to be homogeneous, i.e. same operating system, same number of disks and same network interconnects.

(and as you're probably already aware, there's also https://min.io/product/reference-hardware)

Personally I think that having this clearly stated in the documentation is a great way of ensuring that serious deployments actually adhere to these recommendations/requirements.

The code currently enforces that all the nodes use the same CPU architecture and the same OS during the bootstrap process.  It does not enforce any of the other requirements you listed in the linked issue: CPU, disk, network, vendor or firmware.  So, while not recommended, it's currently _possible_ to mix and match older generation processors with newer generations, slow SSD disks with faster NVME disks, and so forth.

Given this, why should the CPU _architecture_ be treated differently?

The benefits of allowing the underlying hardware to be replaced over time (years) should be clear.  Imagine if, once you had deployed a MinIO cluster, you couldn't change the CPU core count, the CPU generation, increase the amount of RAM or replace slower SSD disks with faster NVME disks.  That would mean that a MinIO cluster couldn't outlive the original hardware it was deployed on, forcing you to buy a complete new set of hardware, mirror many TBs worth of data and then switch over.

What I'm trying to argue is that the platform check I'm attempting to delete is largely arbitrary, doesn't provide any value and just gets in the way.  Similar to how old websites refused to work unless you were using some particular browser vendor and/or version.  The intentions were probably good at the time, but technology progressed and the well-intended checks just got in the way and broke things in surprising ways.

I'm one of the 49% in this picture: https://images.anandtech.com/doci/16640/Neoverse_Intro_10.png.  I'm looking to gradually (because the alternative is worse) replace a set of AMD64 nodes with ARM64 nodes, and I ran smack into this issue on my niche deployment where I was testing things out on.

It turns out that it is in fact possible to bring up a cluster with mixed AMD64 and ARM64 nodes.  But once you restart your `minio server ...` processes, you're eventually greeted with:

> Expected platform 'OS: linux | Arch: arm64', found to be running 'OS: linux | Arch: amd64'

(tested with `Version: 2021-04-22T15:44:28Z`)

I understand that deployments / hardware roll-out changes like mine are not supported (or even "forbidden") per the "homogenous hardware requirements".  However, I do think it would be _useful_ to _NOT enforce_ it per the robustness principle.

In the last year, you've had at least two reports regarding the CPU architecture/OS check.  Will I be the last one attempting something like this?  Given the increasing availability of performant ARM64 servers, I think it would be a safe bet to predict that you're going to see more of these reports.

(The intention of referencing the benchmark blog post was merely to show that one of the previously stated reasons -- `amd64 >> arm64` -- for keeping the check might not hold up over time; I apologize for not making this clear from the start.)

So what I'm asking for is that the platform check is dropped to allow the underlying hardware to be replaced over time with no software-enforced constraints.  This will ensure that I'm one of the last existing, or potential, customers making the mistake to run into this issue.

Thanks!

**Comment by harshavardhana** [comment]
> Hi,
> 
> Thanks for the quick feedback here and in #12202.
> 
> In the linked issue, you wrote that serious deployments should use hardware of equal performance metrics as well as the fact that you _want_ your customers to adhere to these requirements.
> 
> I understand and acknowledge these arguments. I'll also note that something similar is already stated in bold in the documentation at https://docs.min.io/docs/distributed-minio-quickstart-guide.html:
> 
> > All the nodes running distributed MinIO setup are recommended to be homogeneous, i.e. same operating system, same number of disks and same network interconnects.
> 
> (and as you're probably already aware, there's also https://min.io/product/reference-hardware)
> 
> Personally I think that having this clearly stated in the documentation is a great way of ensuring that serious deployments actually adhere to these recommendations/requirements.
> 
> The code currently enforces that all the nodes use the same CPU architecture and the same OS during the bootstrap process. It does not enforce any of the other requirements you listed in the linked issue: CPU, disk, network, vendor or firmware. So, while not recommended, it's currently _possible_ to mix and match older generation processors with newer generations, slow SSD disks with faster NVME disks, and so forth.
> 
> Given this, why should the CPU _architecture_ be treated differently?
> 
> The benefits of allowing the underlying hardware to be replaced over time (years) should be clear. Imagine if, once you had deployed a MinIO cluster, you couldn't change the CPU core count, the CPU generation, increase the amount of RAM or replace slower SSD disks with faster NVME disks. That would mean that a MinIO cluster couldn't outlive the original hardware it was deployed on, forcing you to buy a complete new set of hardware, mirror many TBs worth of data and then switch over.
> 
> What I'm trying to argue is that the platform check I'm attempting to delete is largely arbitrary, doesn't provide any value and just gets in the way. Similar to how old websites refused to work unless you were using some particular browser vendor and/or version. The intentions were probably good at the time, but technology progressed and the well-intended checks just got in the way and broke things in surprising ways.
> 
> I'm one of the 49% in this picture: https://images.anandtech.com/doci/16640/Neoverse_Intro_10.png. I'm looking to gradually (because the alternative is worse) replace a set of AMD64 nodes with ARM64 nodes, and I ran smack into this issue on my niche deployment where I was testing things out on.
> 
> It turns out that it is in fact possible to bring up a cluster with mixed AMD64 and ARM64 nodes. But once you restart your `minio server ...` processes, you're eventually greeted with:
> 
> > Expected platform 'OS: linux | Arch: arm64', found to be running 'OS: linux | Arch: amd64'
> 
> (tested with `Version: 2021-04-22T15:44:28Z`)
> 
> I understand that deployments / hardware roll-out changes like mine are not supported (or even "forbidden") per the "homogenous hardware requirements". However, I do think it would be _useful_ to _NOT enforce_ it per the robustness principle.
> 
> In the last year, you've had at least two reports regarding the CPU architecture/OS check. Will I be the last one attempting something like this? Given the increasing availability of performant ARM64 servers, I think it would be a safe bet to predict that you're going to see more of these reports.
> 
> (The intention of referencing the benchmark blog post was merely to show that one of the previously stated reasons -- `amd64 >> arm64` -- for keeping the check might not hold up over time; I apologize for not making this clear from the start.)
> 
> So what I'm asking for is that the platform check is dropped to allow the underlying hardware to be replaced over time with no software-enforced constraints. This will ensure that I'm one of the last existing, or potential, customers making the mistake to run into this issue.
> 
> Thanks!

Once you deployed we ask for `mc admin subnet health` which further verifies such authenticity. 

This is available as part our subscription for customers where we guide and architecture their deployments.

Making this change contradicts our prime principle of symmetric deployment model for a MinIO cluster.

Unfortunately we can't take this change. Sorry.

**Pull request closed without merging**
