### PR TITLE
fix: update allowed max chunk payloadsize to 16MiB

### LINKED ISSUE #13163: Internal error, malformed chunked encoding
The modern Minio version returns "Internal Error". The old version works.

## Expected Behavior
No error from Minio or to permit a user set the desired limit in Minio config.

## Current Behavior
Our application has worked flawlessly with old Minio versions.
Recently we updated Minio to the latest version: RELEASE.2021-09-03T03-56-13Z

After that our application started to get errors from Minio:
`We encountered an internal error, please try again.: cause(malformed chunked encoding)`
It happens when the application uploads relatively big files.

The error message itself is quite odd, we didn't change chunk encoding.
We didn't change any settings in Minio service.

After investigation I found the guilty code: https://github.com/minio/minio/blame/1f262daf6fe369a57d8e183b3e3758644407e485/cmd/streaming-signature-v4.go#L222
So the 1MiB limit for chunk size was just hard-coded!
And if the receiving chunk size if larger than the new limit the "malformed chunked encoding" error is returned regardless the real cause
similarly with other error cases.
See https://github.com/minio/minio/blame/1f262daf6fe369a57d8e183b3e3758644407e485/cmd/streaming-signature-v4.go#L253

Our application works in the high performance environment and uses several carefully tuned parameters.
One of them is the ASW HTTP chunk size. We found that the best performance is achieved with 2MiB chunks in our environment.

## Possible Solution
With Minio I see the following problem:
1. The error message is confusing. It doesn't tell the real reason for the error.
I'd suggest returning an explicit error reason, for instance "employed chunk size exceeds the 1MiB limit".
2. Hard-coded constants should be avoided! For a software that is deployed in different environment, this "One 1 MB is a reasonable max limit" is inappropriate IMHO.  We suggest to get rid of the hard coded constant and make it a Minio configuration parameter.
3. Our application is regularly tested against many other S3 compatible cloud applications including AWS S3.
No other applications except Minio complain about large chunk sizes. And I has not been able to find some documented **upper** limit in AWS S3 API docs.
If Minio introduces this limit because you believe it's a good design, then the documentation should be updated.

## Regression
- [x] Yes, PR#: https://github.com/minio/minio/pull/11801

### PR DESCRIPTION
**Pull request by harshavardhana**
fixes #13163

## Description
fix: update allowed max chunk payloadsize to 16MiB

## Motivation and Context
fixes #13163

## How to test this PR?
As per #13163 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by aead — APPROVED** [review]

**Pull request merged**
