### PR TITLE
Rename iam/validator -> iam/openid and add tests

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Rename iam/validator -> iam/openid and add tests

## Motivation and Context
Refactor as part of config migration

## How to test this PR?
Nothing special just renaming of iam/validator to iam/openid

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 8340-68a4484/gopath/src/github.com/minio
+ git -C 8340-68a4484/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 8340-68a4484/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 8340-68a4484/gopath/src/github.com/minio/minio fetch --quiet minio pull/8340/head:pr8340
+ git -C 8340-68a4484/gopath/src/github.com/minio/minio checkout --quiet pr8340
+ GO111MODULE=on
+ GOPATH=/mnt/nvme/mint-auto/8340-68a4484/gopath
+ make -C 8340-68a4484/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.21.0
go: downloading github.com/Azure/azure-sdk-for-go v27.0.0+incompatible
go: downloading github.com/json-iterator/go v1.1.7
go: downloading github.com/Azure/go-autorest v11.7.0+incompatible
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading google.golang.org/api v0.4.0
go: downloading github.com/minio/minio-go v0.0.0-20190327203652-5325257a208f
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: extracting github.com/json-iterator/go v1.1.7
go: extracting github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading gopkg.in/ldap.v3 v3.0.3
go: extracting github.com/minio/cli v1.21.0
go: downloading github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: extracting gopkg.in/ldap.v3 v3.0.3
go: extracting github.com/Azure/go-autorest v11.7.0+incompatible
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/rs/cors v1.6.0
go: extracting github.com/rs/cors v1.6.0
go: downloading github.com/minio/highwayhash v1.0.0
go: extracting github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: extracting github.com/minio/minio-go v0.0.0-20190327203652-5325257a208f
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: extracting gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/minio/minio-go/v6 v6.0.37
go: downloading github.com/gorilla/handlers v1.4.0
go: downloading github.com/ncw/directio v1.0.5
go: extracting github.com/gorilla/handlers v1.4.0
go: downloading go.uber.org/atomic v1.3.2
go: extracting go.uber.org/atomic v1.3.2
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/ncw/directio v1.0.5
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/minio/highwayhash v1.0.0
go: downloading github.com/miekg/dns v1.1.8
go: extracting github.com/gorilla/rpc v1.2.0
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/minio/minio-go/v6 v6.0.37
go: downloading golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
go: extracting github.com/klauspost/reedsolomon v1.9.3
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: downloading github.com/klauspost/cpuid v1.2.1
go: extracting github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/klauspost/cpuid v1.2.1
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: extracting github.com/miekg/dns v1.1.8
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/mattn/go-isatty v0.0.7
go: extracting github.com/djherbis/atime v1.0.0
go: downloading github.com/cheggaaa/pb v1.0.28
go: extracting github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading google.golang.org/grpc v1.20.1
go: extracting github.com/mattn/go-isatty v0.0.7
go: extracting github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/pkg/profile v1.3.0
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/dustin/go-humanize v1.0.0
go: extracting github.com/cheggaaa/pb v1.0.28
go: downloading github.com/gorilla/mux v1.7.0
go: extracting github.com/pkg/profile v1.3.0
go: extracting github.com/dustin/go-humanize v1.0.0
go: downloading golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: extracting github.com/gorilla/mux v1.7.0
go: downloading github.com/minio/sio v0.2.0
go: extracting google.golang.org/grpc v1.20.1
go: extracting github.com/minio/sio v0.2.0
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: extracting github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19
go: extracting golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: extracting github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: extracting golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
go: downloading go.opencensus.io v0.21.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting github.com/minio/hdfs/v3 v3.0.1
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/klauspost/compress v1.8.3
go: extracting go.opencensus.io v0.21.0
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/minio/lsync v1.0.1
go: extracting github.com/minio/lsync v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/klauspost/readahead v1.3.0
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: extracting github.com/klauspost/readahead v1.3.0
go: downloading contrib.go.opencensus.io/exporter/ocagent v0.5.0
go: extracting contrib.go.opencensus.io/exporter/ocagent v0.5.0
go: downloading gopkg.in/yaml.v2 v2.2.2
go: extracting gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/golang/protobuf v1.3.1
go: extracting golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: extracting github.com/golang/protobuf v1.3.1
go: extracting google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: extracting github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/census-instrumentation/opencensus-proto v0.2.0
go: extracting github.com/census-instrumentation/opencensus-proto v0.2.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/streadway/amqp v0.0.0-20190402114354-16ed540749f6
go: extracting github.com/streadway/amqp v0.0.0-20190402114354-16ed540749f6
go: downloading github.com/minio/parquet-go v0.0.0-20190318185229-9d767baf1679
go: extracting github.com/minio/parquet-go v0.0.0-20190318185229-9d767baf1679
go: downloading github.com/nsqio/go-nsq v1.0.7
go: extracting github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/eclipse/paho.mqtt.golang v1.1.2-0.20190322152051-20337d8c3947
go: extracting github.com/eclipse/paho.mqtt.golang v1.1.2-0.20190322152051-20337d8c3947
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: extracting github.com/go-sql-driver/mysql v1.4.1
go: downloading github.com/klauspost/pgzip v1.2.1
go: extracting github.com/klauspost/pgzip v1.2.1
go: downloading gopkg.in/ini.v1 v1.48.0
go: extracting gopkg.in/ini.v1 v1.48.0
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/fatih/color v1.7.0
go: extracting github.com/fatih/color v1.7.0
go: downloading cloud.google.com/go v0.37.2
go: extracting cloud.google.com/go v0.37.2
go: downloading github.com/tidwall/gjson v1.2.1
go: extracting github.com/klauspost/compress v1.8.3
go: extracting github.com/tidwall/gjson v1.2.1
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/pkg/errors v0.8.1
go: downloading git.apache.org/thrift.git v0.12.0
go: extracting github.com/pkg/errors v0.8.1
go: downloading github.com/minio/mc v0.0.0-20190924013003-643835013047
go: extracting github.com/coredns/coredns v1.4.0
go: downloading gopkg.in/Shopify/sarama.v1 v1.20.0
go: extracting github.com/minio/mc v0.0.0-20190924013003-643835013047
go: extracting gopkg.in/Shopify/sarama.v1 v1.20.0
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: extracting github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: extracting github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/mattn/go-colorable v0.1.1
go: extracting github.com/mattn/go-colorable v0.1.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/minio/dsync v1.0.0
go: extracting github.com/minio/dsync v1.0.0
go: downloading github.com/minio/dsync/v2 v2.0.0
go: extracting github.com/minio/dsync/v2 v2.0.0
go: downloading github.com/googleapis/gax-go v2.0.0+incompatible
go: extracting github.com/googleapis/gax-go v2.0.0+incompatible
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: extracting github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/davecgh/go-spew v1.1.1
go: extracting github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/go-resiliency v1.2.0
go: extracting github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/hashicorp/vault v1.1.0
go: extracting git.apache.org/thrift.git v0.12.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: extracting github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading github.com/pierrec/lz4 v2.0.5+incompatible
go: extracting github.com/Azure/azure-sdk-for-go v27.0.0+incompatible
go: extracting google.golang.org/api v0.4.0
go: extracting github.com/pierrec/lz4 v2.0.5+incompatible
go: downloading github.com/prometheus/common v0.2.0
go: extracting github.com/prometheus/common v0.2.0
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.9.0
go: extracting github.com/grpc-ecosystem/grpc-gateway v1.9.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/eapache/queue v1.1.0
go: extracting github.com/eapache/queue v1.1.0
go: downloading github.com/fatih/structs v1.1.0
go: extracting github.com/alecthomas/participle v0.2.1
go: downloading github.com/tidwall/match v1.0.1
go: extracting github.com/fatih/structs v1.1.0
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/tidwall/pretty v1.0.0
go: extracting github.com/tidwall/match v1.0.1
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: extracting github.com/tidwall/pretty v1.0.0
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: extracting github.com/hashicorp/golang-lru v0.5.1
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: extracting github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: extracting golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading github.com/rjeczalik/notify v0.9.2
go: extracting github.com/minio/sha256-simd v0.1.1
go: extracting github.com/rjeczalik/notify v0.9.2
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/lib/pq v1.0.0
go: extracting gopkg.in/olivere/elastic.v5 v5.0.80
go: extracting github.com/lib/pq v1.0.0
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: extracting github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: downloading github.com/nats-io/nats.go v1.8.0
go: extracting github.com/nats-io/nats.go v1.8.0
go: downloading github.com/nats-io/nuid v1.0.1
go: extracting github.com/nats-io/nuid v1.0.1
go: extracting github.com/gogo/protobuf v1.2.1
go: downloading github.com/satori/go.uuid v1.2.0
go: downloading golang.org/x/text v0.3.2
go: extracting github.com/satori/go.uuid v1.2.0
go: downloading github.com/nats-io/stan.go v0.4.5
go: extracting github.com/nats-io/stan.go v0.4.5
go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: extracting golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: downloading github.com/marstr/guid v1.1.0
go: extracting github.com/hashicorp/vault v1.1.0
go: extracting github.com/marstr/guid v1.1.0
go: downloading github.com/nats-io/nkeys v0.0.2
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: extracting github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: extracting github.com/nats-io/nkeys v0.0.2
go: downloading github.com/golang/snappy v0.0.1
go: extracting github.com/golang/snappy v0.0.1
go: extracting github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: extracting github.com/hashicorp/hcl v1.0.0
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: extracting github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting golang.org/x/text v0.3.2
go: downloading github.com/hashicorp/go-retryablehttp v0.5.3
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: extracting github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: extracting github.com/hashicorp/go-retryablehttp v0.5.3
go: extracting github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/ryanuber/go-glob v1.0.0
go: extracting github.com/ryanuber/go-glob v1.0.0
go: extracting github.com/hashicorp/go-sockaddr v1.0.2
go: extracting github.com/minio/gokrb5/v7 v7.2.5
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: extracting gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: extracting gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: extracting github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: extracting gopkg.in/jcmturner/aescts.v1 v1.0.1
go: extracting github.com/hashicorp/go-uuid v1.0.1
go: extracting gopkg.in/jcmturner/rpc.v1 v1.1.0
go: finding github.com/minio/gokrb5/v7 v7.2.5
go: finding google.golang.org/api v0.4.0
go: finding github.com/minio/hdfs/v3 v3.0.1
go: finding github.com/minio/minio-go/v6 v6.0.37
go: finding github.com/minio/cli v1.21.0
go: finding github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: finding github.com/dustin/go-humanize v1.0.0
go: finding github.com/json-iterator/go v1.1.7
go: finding cloud.google.com/go v0.37.2
go: finding github.com/Azure/go-autorest v11.7.0+incompatible
go: finding github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: finding github.com/fatih/color v1.7.0
go: finding github.com/Azure/azure-sdk-for-go v27.0.0+incompatible
go: finding github.com/minio/sha256-simd v0.1.1
go: finding github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: finding github.com/gorilla/mux v1.7.0
go: finding github.com/mattn/go-isatty v0.0.7
go: finding github.com/minio/mc v0.0.0-20190924013003-643835013047
go: finding github.com/minio/highwayhash v1.0.0
go: finding github.com/hashicorp/go-uuid v1.0.1
go: finding google.golang.org/grpc v1.20.1
go: finding github.com/mattn/go-colorable v0.1.1
go: finding github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: finding gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding github.com/rjeczalik/notify v0.9.2
go: finding golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: finding golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
go: finding gopkg.in/jcmturner/aescts.v1 v1.0.1
go: finding github.com/golang/protobuf v1.3.1
go: finding google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19
go: finding gopkg.in/jcmturner/rpc.v1 v1.1.0
go: finding github.com/mitchellh/go-homedir v1.1.0
go: finding gopkg.in/ini.v1 v1.48.0
go: finding golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: finding go.opencensus.io v0.21.0
go: finding gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: finding github.com/googleapis/gax-go/v2 v2.0.4
go: finding contrib.go.opencensus.io/exporter/ocagent v0.5.0
go: finding github.com/gogo/protobuf v1.2.1
go: finding github.com/hashicorp/golang-lru v0.5.1
go: finding github.com/marstr/guid v1.1.0
go: finding github.com/satori/go.uuid v1.2.0
go: finding golang.org/x/text v0.3.2
go: finding github.com/census-instrumentation/opencensus-proto v0.2.0
go: finding golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: finding github.com/grpc-ecosystem/grpc-gateway v1.9.0
go: finding github.com/cheggaaa/pb v1.0.28
go: finding github.com/mattn/go-runewidth v0.0.4
go: finding github.com/coreos/etcd v3.3.12+incompatible
go: finding github.com/djherbis/atime v1.0.0
go: finding github.com/elazarl/go-bindata-assetfs v1.0.0
go: finding github.com/gorilla/handlers v1.4.0
go: finding github.com/gorilla/rpc v1.2.0
go: finding github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: finding github.com/klauspost/compress v1.8.3
go: finding github.com/klauspost/cpuid v1.2.1
go: finding github.com/klauspost/readahead v1.3.0
go: finding github.com/klauspost/reedsolomon v1.9.3
go: finding github.com/miekg/dns v1.1.8
go: finding github.com/minio/dsync/v2 v2.0.0
go: finding github.com/minio/lsync v1.0.1
go: finding github.com/minio/minio-go v0.0.0-20190327203652-5325257a208f
go: finding github.com/hashicorp/vault v1.1.0
go: finding github.com/hashicorp/errwrap v1.0.0
go: finding github.com/hashicorp/go-cleanhttp v0.5.1
go: finding github.com/hashicorp/go-multierror v1.0.0
go: finding github.com/hashicorp/go-retryablehttp v0.5.3
go: finding github.com/hashicorp/go-rootcerts v1.0.1
go: finding github.com/hashicorp/hcl v1.0.0
go: finding github.com/golang/snappy v0.0.1
go: finding github.com/pierrec/lz4 v2.0.5+incompatible
go: finding github.com/hashicorp/go-sockaddr v1.0.2
go: finding github.com/ryanuber/go-glob v1.0.0
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding github.com/ncw/directio v1.0.5
go: finding github.com/minio/sio v0.2.0
go: finding github.com/coredns/coredns v1.4.0
go: finding github.com/eclipse/paho.mqtt.golang v1.1.2-0.20190322152051-20337d8c3947
go: finding github.com/go-sql-driver/mysql v1.4.1
go: finding github.com/gomodule/redigo v2.0.0+incompatible
go: finding github.com/lib/pq v1.0.0
go: finding github.com/nats-io/nats.go v1.8.0
go: finding github.com/nats-io/nkeys v0.0.2
go: finding github.com/nats-io/nuid v1.0.1
go: finding github.com/nats-io/stan.go v0.4.5
go: finding github.com/nsqio/go-nsq v1.0.7
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: finding github.com/streadway/amqp v0.0.0-20190402114354-16ed540749f6
go: finding gopkg.in/Shopify/sarama.v1 v1.20.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/eapache/go-resiliency v1.2.0
go: finding github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: finding github.com/eapache/queue v1.1.0
go: finding github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: finding gopkg.in/olivere/elastic.v5 v5.0.80
go: finding github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: finding github.com/fatih/structs v1.1.0
go: finding github.com/tidwall/gjson v1.2.1
go: finding github.com/tidwall/match v1.0.1
go: finding github.com/tidwall/pretty v1.0.0
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding github.com/klauspost/pgzip v1.2.1
go: finding github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: finding github.com/alecthomas/participle v0.2.1
go: finding github.com/minio/parquet-go v0.0.0-20190318185229-9d767baf1679
go: finding git.apache.org/thrift.git v0.12.0
go: finding github.com/pkg/profile v1.3.0
go: finding github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: finding github.com/prometheus/common v0.2.0
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: finding github.com/rs/cors v1.6.0
go: finding go.uber.org/atomic v1.3.2
go: finding gopkg.in/ldap.v3 v3.0.3
go: finding gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
# github.com/minio/minio/cmd
cmd/config-current.go:644:49: undefined: openid
cmd/config-current.go:645:16: undefined: openid
cmd/config-current.go:648:18: undefined: openid
cmd/config-migrate.go:2656:20: undefined: openid
cmd/globals.go:270:23: undefined: openid
cmd/sts-handlers.go:183:18: undefined: openid
cmd/sts-handlers.go:284:8: undefined: openid
cmd/sts-handlers.go:292:8: undefined: openid
make: *** [build] Error 2

```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#5b3c1f48-54cc-4b38-a953-3fa9b80a6550) |
| mint-dist-xl.sh | :x: [more...](#efa2a989-6c21-49a8-b8f0-1d1cac48c032) |
<a name="5b3c1f48-54cc-4b38-a953-3fa9b80a6550"></a>
### 8340-c32bf53/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32129
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8ec03e05ae80:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 54 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 17 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 37 seconds
{
  "args": {},
  "duration": 73597,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="efa2a989-6c21-49a8-b8f0-1d1cac48c032"></a>
### 8340-c32bf53/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32608
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 197f60f8d62f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 28 seconds
(8/14) Running minio-dotnet tests ... done in 53 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 43 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 12 seconds
(11/14) Running minio-js tests ... done in 56 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 31 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "duration": 91,
  "args": {
    "object_name": "0a0782e5-5706-4579-9666-c1a93cde015a",
    "response.status": 403,
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-30T23-23-22Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C95C39F15256C0\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Mon, 30 Sep 2019 23:49:09 GMT\"]}}",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>0a0782e5-5706-4579-9666-c1a93cde015a</Key><BucketName>minio-py-test-acb71ee6-760a-4714-83a5-dbd5f1deae1d</BucketName><Resource>/minio-py-test-acb71ee6-760a-4714-83a5-dbd5f1deae1d/0a0782e5-5706-4579-9666-c1a93cde015a</Resource><RequestId>15C95C39F15256C0</RequestId><HostId>7ba08ddc-d061-41a7-9b75-34496a42e608</HostId></Error>",
    "response.reason": "Forbidden",
    "bucket_name": "minio-py-test-acb71ee6-760a-4714-83a5-dbd5f1deae1d",
    "presigned_get_object_url": "http://72.28.97.56:32608/minio-py-test-acb71ee6-760a-4714-83a5-dbd5f1deae1d/0a0782e5-5706-4579-9666-c1a93cde015a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190930%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190930T234901Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=5b420d8664dc8bbcb95658ea9b5d1fe6e89e14519041b8f544e001c617f2a702"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied"
}

Executed 11 out of 14 tests successfully.
```

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
ping @donatello

**Review by donatello — APPROVED** [review]

**Pull request merged**
