### PR TITLE
Add support for reading and saving config on Gateway.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add support for reading and saving config on Gateway.

## Motivation and Context
This is also a first step towards supporting bucket notification for gateway.

## How Has This Been Tested?
Manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by poornas — CHANGES_REQUESTED** [review]
Tested with azure - config gets saved, but when the environment vars are unset, gateway server doesn't use saved credentials to  start server.

**Comment by harshavardhana** [comment]
> Tested with azure - config gets saved, but when the environment vars are unset, gateway server doesn't use saved credentials to start server.

Should be fixed now.. @poornas

**Comment by poornas** [comment]
Saved config gets used now when gateway credentials are stored in the config.json. 

However, server generates random access key/secret key when gateway server is started for the first time( both config.json and env. vars are not present). This is misleading behavior and should instead fail if env. variables are missing.

**Review by poornas — APPROVED** [review]
LGTM.

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
