### PR TITLE
replace hash-based bitrot detection with generic mechanism

### PR DESCRIPTION
**Pull request by aead**
This change introduces the new pkg/bitrot package and include it into the minio server.

## Description
This change replace the old hash-based bitrot detection approach with a new (more generic) solution.
Now it is possible to use hash-functions or authenticators (esp. polynomial authenticators).
Therefore this change adds a new field in the XL format (checkSumInfo now has also a key).

## Motivation and Context
This is the first step to support server-side-encryption (SSE).
Updates #4416 

## How Has This Been Tested?
Add test to ensure that currently just hash-functions (or similar non-key based techniques) can be used.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by fwessels — APPROVED** [review]
Thus far, LGTM.

**Review by harshavardhana — APPROVED** [review]

**Comment by deekoder** [comment]
Blocked -  squash commits

**Comment by deekoder** [comment]
@aead can this be merged now?

**Comment by deekoder** [comment]
@aead  Travis is not passed. Can you take a look?

**Comment by aead** [comment]
@deekoder 
Really? Maybe a timeout CI fail?! Because github says: "All checks have passed"
edit: Yeah, just CI timeout...

**Comment by harshavardhana** [comment]
> @deekoder
> Really? Maybe a timeout CI fail?! Because github says: "All checks have passed"

I rebuilt it @aead @deekoder it is a transient CI failure we get because of the bug https://github.com/minio/minio/issues/4461

**Pull request merged**
