### PR TITLE
fix routing issue for esoteric characters in gorilla/mux

### LINKED ISSUE #8647: Splunk Smartstore configuration sends wrong characters to Minio
I'm trying to enable Splunk Smartstore with Minio backend. Splunk is running on a Windows host. I see the following errors in mc trace output:
```
<Error><Code>XMinioInvalidObjectName</Code><Message>Object name contains unsupported characters.</Message><Key>remote_volume/\_internal/db/33/65/1~F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73/guidSplunk-F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73\.rawSize</Key><BucketName>smartstore</BucketName><Resource>/smartstore/remote_volume/\_internal/db/33/65/1~F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73/guidSplunk-F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73\.rawSize</Resource><RequestId>15DFCC15D7A73011</RequestId><HostId>c93d43ff-a17b-45d9-8e25-687a9e869fe7</HostId></Error>
```
## Expected Behavior

PUT request should be successful

## Steps to Reproduce (for bugs)

indexes.conf content on Splunk server:

[default]
remotePath = volume:s3/$_index_name

[volume:s3]
storageType = remote
path = s3://smartstore/remote_volume
remote.s3.access_key = $7$wY9aSdtLUJ3mtWdK2+BUfKNyyYFGczOwzYDMzzAxGAmK8elddQ==
remote.s3.secret_key = $7$U4YWebjzY3IWvKo++XPLHShpp+QqnIVlv9JUBrJjQ1pmfzbgaSN7/A==
remote.s3.supports_versioning = false
remote.s3.endpoint = http://io-wt-11:9000

# This example stanza configures a custom index, "cs_index".
[cs_index]
homePath = $SPLUNK_DB/$_index_name/db
# SmartStore-enabled indexes do not use thawedPath or coldPath, but you
 must still specify them here.
coldPath = $SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/cs_index/thaweddb
remotePath = volume:s3/$_index_name

[_internal]
remotePath = volume:s3/$_index_name

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### LINKED ISSUE #8950: Minio doesn't handle special characters correctly.
I'm working on tool called rclone that allows you to manager files on various cloud storage providers. We recently noticed that some of our S3 integrations tests fail when running against minio. These tests throw a variety of special characters like punction and control characters at the API.

## Expected Behavior

Match Amazon S3. While most of these characters would realistically never be used in names minio should match Amazon S3 for consistency.

## Current Behavior

The API returns a `MalformedXML` error

## Steps to Reproduce (for bugs)

The tests that are failing on our side are:
   - `TestIntegration/FsMkdir/FsPutFiles/SetTier`
   - `TestIntegration/FsMkdir/FsEncoding/control_chars`
   - `TestIntegration/FsMkdir/FsEncoding/leading_LF`
   - `TestIntegration/FsMkdir/FsEncoding/leading_VT` 
   - `TestIntegration/FsMkdir/FsEncoding/punctuation` 
   - `TestIntegration/FsMkdir/FsEncoding/trailing_LF` 
   - `TestIntegration/FsMkdir/FsEncoding/trailing_VT`

These are implemented here:  
https://github.com/rclone/rclone/blob/fe6f4135b420fb22bafc9a25baf1ee91ec9291ac/fstest/fstests/fstests.go#L557 

If you want to run these yourself you'll have to setup an Minio backend in rclone as described in our docs [here](https://rclone.org/s3/) and run the [S3 integration tests](https://github.com/rclone/rclone/blob/fe6f4135b420fb22bafc9a25baf1ee91ec9291ac/backend/s3/s3_test.go#L12) against it.

## Context

Minio is one of the backends we use for testing and these errors can effect other tests too.

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-01-25T02-50-51Z
* Operating System and version (`uname -a`): Linux ws 4.19.99-1-bmn #1 SMP Mon Jan 27 15:10:18 UTC 2020 x86_64 GNU/Linux

* Link to your project: https://github.com/rclone/rclone

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix routing issue for esoteric characters in gorilla/mux

## Motivation and Context
First step is to ensure that Path component is not decoded
by gorilla/mux to avoid routing issues while handling
certain characters while uploading through PutObject()

Delay the decoding and use PathUnescape() to escape
the `object` path component.

Thanks to @buengese and @ncw for neat test cases for us
to test with.

Fixes #8950
Fixes #8647

## How to test this PR?
You need rclone project integration tests running as mentioned here https://github.com/rclone/rclone/issues/3934#issuecomment-583376344

NOTE: Ignore the STANDARD_IA storage-class header

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#ea5c4def-39c3-4864-b5ea-3fe8a5ad315e) |
| mint-large-bucket.sh | :x: [more...](#a158be25-5db3-4d39-ab08-60d0a7770342) |
| mint-gateway-azure.sh | :x: [more...](#9724146a-a6ef-4745-9e80-019658e4b6d7) |
| mint-gateway-nas.sh | :x: [more...](#ad206803-2790-4490-8e4f-00c32ca7bcfe) |
<a name="ad206803-2790-4490-8e4f-00c32ca7bcfe"></a>
### 8967-3290759/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31985
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dc35fdd60208:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 7 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 2 seconds
(4/13) Running mc tests ... done in 16 seconds
(5/13) Running minio-go tests ... FAILED in 12 minutes and 28 seconds
{
  "args": {
    "bucketName": "minio-go-test-mtvutgjchtcme6ub",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 102348,
  "error": "We encountered an internal error, please try again.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 2 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="ea5c4def-39c3-4864-b5ea-3fe8a5ad315e"></a>
### 8967-3290759/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32382
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d8520492106a:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 11017,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="a158be25-5db3-4d39-ab08-60d0a7770342"></a>
### 8967-3290759/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30474
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fd20d9722aa3:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 25 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 9 seconds
(4/13) Running mc tests ... done in 1 minutes and 8 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 46 seconds
{
  "args": {},
  "duration": 118330,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="9724146a-a6ef-4745-9e80-019658e4b6d7"></a>
### 8967-3290759/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32126
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c86a2462563f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 26 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 17 seconds
(4/13) Running mc tests ... done in 6 minutes and 49 seconds
(5/13) Running minio-go tests ... FAILED in 26 minutes and 0 seconds
{
  "args": {
    "bucketName": "minio-go-test-sl3xkbkwq1fg52xm",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 111323,
  "error": "We encountered an internal error, please try again.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 2 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e44c9cc6-e0be-4516-a549-47547d6f34dc) |
| mint-fs.sh | :x: [more...](#4d8af987-e119-4e01-97d8-ab418af56110) |
| mint-gateway-azure.sh | :x: [more...](#f3f6e1da-e04e-4d2a-9e48-1cc94faaf102) |
| mint-gateway-nas.sh | :x: [more...](#32a63da3-f845-4c4b-9a89-bf2dd1a332ea) |
<a name="32a63da3-f845-4c4b-9a89-bf2dd1a332ea"></a>
### 8967-3a4ab3a/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31299
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dd66e3ad82b5:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 5 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 2 seconds
(4/13) Running mc tests ... done in 17 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 14 seconds
{
  "args": {
    "bucketName": "minio-go-test-twqz9gmwwtri6ifv",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 68800,
  "error": "We encountered an internal error, please try again.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 2 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="f3f6e1da-e04e-4d2a-9e48-1cc94faaf102"></a>
### 8967-3a4ab3a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30196
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 70c12e2f3d4c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 9 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 18 seconds
(4/13) Running mc tests ... done in 6 minutes and 18 seconds
(5/13) Running minio-go tests ... FAILED in 33 minutes and 38 seconds
{
  "args": {
    "bucketName": "minio-go-test-pn2yegrehvohey20",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 74162,
  "error": "We encountered an internal error, please try again.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 2 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="e44c9cc6-e0be-4516-a549-47547d6f34dc"></a>
### 8967-3a4ab3a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31797
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 821db5b27853:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 46 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 7 seconds
{
  "args": {},
  "duration": 82066,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="4d8af987-e119-4e01-97d8-ab418af56110"></a>
### 8967-3a4ab3a/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31402
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cf5b54bbe429:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 307561, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31402/awscli-mint-test-bucket-19680""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#55520b8a-3589-41dd-b7eb-1f69cbd45414) |
| mint-gateway-azure.sh | :x: [more...](#258ea49c-ae82-4497-8ff5-823c2f859c88) |
<a name="258ea49c-ae82-4497-8ff5-823c2f859c88"></a>
### 8967-907ae1e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31811
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 299105b3f239:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 19 seconds
{
  "name": "awscli",
  "duration": 1605,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 0 out of 13 tests successfully.
```
<a name="55520b8a-3589-41dd-b7eb-1f69cbd45414"></a>
### 8967-907ae1e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30005
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b4d6326fc28e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 51 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 35 seconds
{
  "args": {},
  "duration": 85190,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by nitisht — APPROVED** [review]
LGTM

**Review by nitisht — CHANGES_REQUESTED** [review]
Could you check Travis failures

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#106e266e-34c7-4315-8e0e-72c408aea9a7) |
| mint-large-bucket.sh | :x: [more...](#c2a12edf-32aa-4da8-92ae-ac4024aa2f0a) |
<a name="c2a12edf-32aa-4da8-92ae-ac4024aa2f0a"></a>
### 8967-5da0f77/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32408
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0c598de06a2f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 40 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 48 seconds
{
  "args": {},
  "duration": 113550,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="106e266e-34c7-4315-8e0e-72c408aea9a7"></a>
### 8967-5da0f77/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32328
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1e397ec43d4f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 11414,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Fixed @nitisht

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#3528d82f-7d8a-4e6f-aec6-e36d7754f8d8) |
| mint-large-bucket.sh | :x: [more...](#efc0ae27-1fe1-4f8d-a2ad-29def401ebfd) |
<a name="efc0ae27-1fe1-4f8d-a2ad-29def401ebfd"></a>
### 8967-b564ba4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31139
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a4bda95ab730:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 21 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 41 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 23 seconds
{
  "args": {},
  "duration": 92429,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="3528d82f-7d8a-4e6f-aec6-e36d7754f8d8"></a>
### 8967-b564ba4/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31758
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b767482cf67a:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 6 seconds
{
  "name": "awscli",
  "duration": 3261,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by nitisht — APPROVED** [review]

**Review by donatello — APPROVED** [review]

**Pull request merged**
