### PR TITLE
Add support for {jwt:sub} substitutions for policies

### LINKED ISSUE #8345: AssumeRoleWithWebIdentity in combination with conditions/stable userids in policy
We're trying to create user scoped folders in a bucket, so that the user is only able to upload data to his own subfolder in a bucket (Basically a similar policy as https://github.com/minio/minio/issues/7086 is using). The `aws:userid` condition is mapped to the accesskey of the temporary credentials, which is changing if we're rerequesting new ones. A user won't be able to continue his upload as a result. 

Would it be possible to somehow consider the sub field of the access token in a condition of a bucket policy in order to limit access to a folder instead of the access key? 

Sample:

First Auth Request: User is allowed to upload files to `testbucket/users/KIDH9E7JWDMVUPBH9WR9/*`

``` perl
AWS_SESSION_TOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJLSURIOUU3SldETVZVUEJIOVdSOSIsImF1ZCI6Im1hZ2VudG8tY29ubmVjdG9yIiwiY2lkIjoiMG9hbXMybHU0aVNYWTI2SUowaDciLCJleHAiOjE1NzAwMzQ1ODMsImlhdCI6MTU2OTk0ODE4MywiaXNzIjoiaHR0cHM6Ly9kZXYtMjIwMDU0Lm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzZnZyazFsY0VteU0xOW0waDciLCJqdGkiOiJBVC4zZms1azhCMm1YZV9NTW5mNWNRSG1GLUw3QWpncmpwVU5yZWhRNzJMb2E4IiwicG9saWN5Ijoib2t0YS1kZWZhdWx0LXBvbGljeSIsInNjcCI6WyJtYWdlbnRvLWNvbm5lY3RvciJdLCJzdWIiOiIwb2FtczJsdTRpU1hZMjZJSjBoNyIsInZlciI6MX0.ZkC3mt25gUgIftZ8EY0eGW0yBt-scGNPBqEWN2QRUrEcfgwUPSyT0rHqIwuC2355n61H4jDwvNjj5ajNRWpshA
AWS_ACCESS_KEY_ID=KIDH9E7JWDMVUPBH9WR9
```

2nd Auth Request: User is only allowed to upload files to `testbucket/users/PRQTO5SWXBUJAQ4JRAR3/*`

``` perl
AWS_SESSION_TOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJQUlFUTzVTV1hCVUpBUTRKUkFSMyIsImF1ZCI6Im1hZ2VudG8tY29ubmVjdG9yIiwiY2lkIjoiMG9hbXMybHU0aVNYWTI2SUowaDciLCJleHAiOjE1NzAwMzQ5ODYsImlhdCI6MTU2OTk0ODU4NiwiaXNzIjoiaHR0cHM6Ly9kZXYtMjIwMDU0Lm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzZnZyazFsY0VteU0xOW0waDciLCJqdGkiOiJBVC5CbHZZQnNEVXdSZS1pRU1CRjFHWldRM0hLMlFVdEpMSS1XMGFQQjhYZnIwIiwicG9saWN5Ijoib2t0YS1kZWZhdWx0LXBvbGljeSIsInNjcCI6WyJtYWdlbnRvLWNvbm5lY3RvciJdLCJzdWIiOiIwb2FtczJsdTRpU1hZMjZJSjBoNyIsInZlciI6MX0.othsAZvfXgXyh3-dMKbj7mQYAetilC3MrntkAFhFcxbG8stGxJQzaQQbTajnJsK-KHMbF4HiHhwduqFEINbomw
AWS_ACCESS_KEY_ID=PRQTO5SWXBUJAQ4JRAR3
```

It would be great if it would be somehow possible to map it to the sub claim, which would correspond to `testbucket/users/0oams2lu4iSXY26IJ0h7/*`. If a user has to request new temporary credentials, he'll automatically lose access to the existing folders atm.

[Script to obtain temporary credentials](https://github.com/minio/minio/files/3677649/auth.txt)
[Sample policy](https://github.com/minio/minio/files/3677650/policy.txt)

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add support for {jwt:sub} substitutions for policies

## Motivation and Context
Fixes #8345

## How to test this PR?
You need to generate new policies with variable substitutions
and when generating credentials with STS API. This PRs 
adds additional variable substitutions

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#34e2f34d-8868-4cad-bf46-f1ecb11960ac) |
| mint-xl.sh | :x: [more...](#4fbc79ea-249b-4a9a-9f62-145ed235c986) |
| mint-large-bucket.sh | :x: [more...](#f93647f2-1b9e-41bc-bee0-246e1413828f) |
| mint-compression-dist-xl.sh | :x: [more...](#9a7716da-cd1c-401d-bcfc-fc30f66bc18e) |
<a name="34e2f34d-8868-4cad-bf46-f1ecb11960ac"></a>
### 8393-57282cc/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32750
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8f0348a9a4b2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 7 seconds
{
  "name": "mc",
  "duration": "3556",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-26448 --quiet --no-color cp myminio/mc-test-bucket-17963/mc-test-object-29308 mc-test-object-29308.downloaded  >>> \n`myminio/mc-test-bucket-17963/mc-test-object-29308` -> `mc-test-object-29308.downloaded`\nmc: <ERROR> Failed to copy `http://72.28.97.59:32750/mc-test-bucket-17963/mc-test-object-29308`. read tcp 172.17.0.4:37540->72.28.97.59:32750: read: connection reset by peer\nmc: <ERROR> Session safely terminated. To resume session `mc session resume UnkjudUo`"
}

Executed 6 out of 14 tests successfully.
```
<a name="9a7716da-cd1c-401d-bcfc-fc30f66bc18e"></a>
### 8393-57282cc/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30623
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c4ea6ec0dfa2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 54 seconds
(8/14) Running minio-dotnet tests ... done in 44 seconds
(9/14) Running minio-go tests ... done in 58 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 39 seconds
(11/14) Running minio-js tests ... done in 59 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 57 seconds
{
  "name": "minio-py:test_presigned_get_object_response_headers",
  "args": {
    "object_name": "34e11087-866d-4c7b-99bc-42943b3bab4b",
    "bucket_name": "minio-py-test-3737107f-14ac-4a4e-87a4-54c781afbb48",
    "presigned_get_object_url": "http://72.28.97.54:30623/minio-py-test-3737107f-14ac-4a4e-87a4-54c781afbb48/34e11087-866d-4c7b-99bc-42943b3bab4b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191014%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191014T033807Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=ed26f72e5aff0c2ecfe747a5f70966d8c5d70d2f63e1668f7fb281a325a9dbd3"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "duration": 106,
  "message": "'content-language'",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="4fbc79ea-249b-4a9a-9f62-145ed235c986"></a>
### 8393-57282cc/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31914
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 83f3e961905e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 29 seconds
(8/14) Running minio-dotnet tests ... done in 23 seconds
(9/14) Running minio-go tests ... done in 56 seconds
(10/14) Running minio-java tests ... done in 30 seconds
(11/14) Running minio-js tests ... done in 48 seconds
(12/14) Running minio-py tests ... done in 2 minutes and 19 seconds
(13/14) Running s3cmd tests ... FAILED in 16 seconds
{
  "name": "s3cmd",
  "duration": "8289",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  following lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nInvoked as: /usr/local/bin/s3cmd --config /tmp/.s3cmd-29031/s3cfg get s3://s3cmd-test-bucket-18954/s3cmd-test-object-22040 s3cmd-test-object-22040.downloaded\nProblem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer\nS3cmd:   2.0.2\npython:   3.5.2 (default, Jul 10 2019, 11:58:48) \n[GCC 5.4.0 20160609]\nenvironment LANG=C.UTF-8\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 3092, in <module>\n    rc = main()\n  File \"/usr/local/bin/s3cmd\", line 3001, in main\n    rc = cmd_func(args)\n  File \"/usr/local/bin/s3cmd\", line 590, in cmd_object_get\n    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 716, in object_get\n    response = self.recv_file(request, stream, labels, start_position)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 1742, in recv_file\n    data = http_response.read(this_chunk)\n  File \"/usr/lib/python3.5/http/client.py\", line 458, in read\n    n = self.readinto(b)\n  File \"/usr/lib/python3.5/http/client.py\", line 498, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  above lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
}

Executed 12 out of 14 tests successfully.
```
<a name="f93647f2-1b9e-41bc-bee0-246e1413828f"></a>
### 8393-57282cc/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31562
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e27bd72820b1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 14 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 19 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 32 seconds
{
  "args": {},
  "duration": 111808,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8393-57282cc

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c02017fd-3697-4b83-a392-46a0cddb7453) |
| mint-gateway-nas.sh | :x: [more...](#5e1c20d2-7f66-4803-bdde-1c8e97b8f3f2) |
<a name="5e1c20d2-7f66-4803-bdde-1c8e97b8f3f2"></a>
### 8393-3de38d9/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30906
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6f2d293ef50e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 52 seconds
(8/14) Running minio-dotnet tests ... done in 29 seconds
(9/14) Running minio-go tests ... done in 47 seconds
(10/14) Running minio-java tests ... done in 51 seconds
(11/14) Running minio-js tests ... done in 32 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 4 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "args": {
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-15T03-59-58Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CDB788AF6D5527\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 15 Oct 2019 04:27:22 GMT\"]}}",
    "object_name": "138ddb94-3840-400e-8392-1540cf950bd0",
    "response.reason": "Forbidden",
    "presigned_get_object_url": "http://72.28.97.54:30906/minio-py-test-79469fc5-da31-4407-be80-966ef2401fc6/138ddb94-3840-400e-8392-1540cf950bd0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191015%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191015T042712Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=118ec04336d268217e223475ead560e6b8496c492a27b2200848af1c6fc9005a",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>138ddb94-3840-400e-8392-1540cf950bd0</Key><BucketName>minio-py-test-79469fc5-da31-4407-be80-966ef2401fc6</BucketName><Resource>/minio-py-test-79469fc5-da31-4407-be80-966ef2401fc6/138ddb94-3840-400e-8392-1540cf950bd0</Resource><RequestId>15CDB788AF6D5527</RequestId><HostId>7d466a07-c33e-4b0f-99fd-0c389d2fdc29</HostId></Error>",
    "response.status": 403,
    "bucket_name": "minio-py-test-79469fc5-da31-4407-be80-966ef2401fc6"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 74,
  "status": "FAIL",
  "message": "AccessDenied: message: Access Denied"
}

Executed 11 out of 14 tests successfully.
```
<a name="c02017fd-3697-4b83-a392-46a0cddb7453"></a>
### 8393-3de38d9/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31584
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7df16fe9551c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 3 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 28 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 47 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 38 seconds
{
  "args": {},
  "duration": 114209,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8393-3de38d9

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#699c5e63-26ad-43fe-a1eb-f90974a0c4fd) |
| mint-large-bucket.sh | :x: [more...](#be3f4833-3dab-4b9d-8a6a-a1d405902ba5) |
| mint-compression-dist-xl.sh | :x: [more...](#07c40094-8d48-48c9-b95b-0a276fd2b94a) |
<a name="699c5e63-26ad-43fe-a1eb-f90974a0c4fd"></a>
### 8393-239a5bb/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30864
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d94ceeb995de:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2usdejuheg5320",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365180,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15CE03F969941DF5, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="be3f4833-3dab-4b9d-8a6a-a1d405902ba5"></a>
### 8393-239a5bb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31258
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c20e349b18c0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 55 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 12 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 25 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 43 seconds
{
  "args": {},
  "duration": 136703,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="07c40094-8d48-48c9-b95b-0a276fd2b94a"></a>
### 8393-239a5bb/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31654
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0b4e31d693fe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 56 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 39 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 2 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 40 seconds
(11/14) Running minio-js tests ... done in 53 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 46 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "args": {
    "response.status": 403,
    "response.reason": "Forbidden",
    "object_name": "7121cf64-2f89-40cf-9852-c4efce61f65e",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>7121cf64-2f89-40cf-9852-c4efce61f65e</Key><BucketName>minio-py-test-c32d0902-03d5-467e-b663-1a39a11d1301</BucketName><Resource>/minio-py-test-c32d0902-03d5-467e-b663-1a39a11d1301/7121cf64-2f89-40cf-9852-c4efce61f65e</Resource><RequestId>15CE0437BFA19466</RequestId><HostId>33fcf975-3d0d-4135-b998-e9a122a9d6d8</HostId></Error>",
    "presigned_get_object_url": "http://72.28.97.61:31654/minio-py-test-c32d0902-03d5-467e-b663-1a39a11d1301/7121cf64-2f89-40cf-9852-c4efce61f65e?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191016%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191016T035227Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=05eea1f7d55ae19cc44640be77febaf5b12a0e7da6a54d4dd211a2368fa77527",
    "bucket_name": "minio-py-test-c32d0902-03d5-467e-b663-1a39a11d1301",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-16T03-22-45Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CE0437BFA19466\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Wed, 16 Oct 2019 03:52:37 GMT\"]}}"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "AccessDenied: message: Access Denied",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "duration": 92,
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
Error: No such image: minio/minio:8393-239a5bb

**Review by kanagarajkm — APPROVED** [review]
LGTM, Verified.

**Review by sinhaashish — APPROVED** [review]
Tested and LGTM

**Pull request merged**
