### PR TITLE
WIP: add support for SSE-S3 bulk ETag decryption

### PR DESCRIPTION
**Pull request by aead**
## Description
This commit adds experimental support for
bulk ETag decryption for SSE-S3 encrypted
objects.

Currently, this feature has to be enabled
using `MINIO_DEBUG_KMS_KES_BULK_API=on`.

If KES supports a bulk decryption API, then
MinIO will check whether its policy grants
access to this API. If so, MinIO will use
a bulk API call instead of sending encrypted
ETags serially to KES.

Note that MinIO will not use the KES bulk API
if its client certificate is an admin identity.

## Motivation and Context
KMS, performance, SSE-S3

## How to test this PR?
KES `v.0.19.0`. Setup MinIO+KES as explained here: https://github.com/minio/kes/wiki/MinIO-Object-Storage
Also set `MINIO_DEBUG_KMS_KES_BULK_API=on` and allow the `/v1/key/bulk/decrypt/*` API in the KES policy.

Then, MinIO should be able to use the bulk decryption API for object listing.
**This is an experimental implementation**

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Why there is a restriction here @aead for bulk decryption?

**Comment by harshavardhana** [comment]
> using `MINIO_DEBUG_KMS_KES_BULK_API=on`.

We shouldn't have this kind of ENVs and this should be default behavior @aead - what is the problem to make it default?

**Comment by harshavardhana** [comment]
Can you remove wip on this @aead when you get a chance?

**Comment by harshavardhana** [comment]
Closing this PR since this is not needed?

**Pull request closed without merging**
