### PR TITLE
Add policy conditions support for Listing operations on browser

### LINKED ISSUE #7095: Unable to create policy condition for root folder
When creating a policy with StringEquals "" it doesn't seem to match for the root of a bucket.
The policy I'm using for example:
``` json
{
  "Version": "2012-10-17",
  "Statement": [
    {
     "Sid": "",
     "Action": [
       "s3:*"
     ],
     "Effect": "Allow",
     "Resource": [
       "arn:aws:s3:::bucket",
       "arn:aws:s3:::bucket/*"
     ],
     "Condition": {
		"StringEquals": {
			"s3:prefix": [
				"",
				"/",
				"data",
				"data/"
			]
		}
	 }
    }
  ]
}
```

## Expected Behavior
User with that policy can access / and /data/ but nothing else.

## Current Behavior
User can access /data/ directly but isn't able to access /
```mc ls minio/bucket/data/``` is successful
```mc ls minio/bucket/``` results in:
```
mc: <ERROR> Unable to stat `minio/bucket/`. Access Denied.
```
Minio Browser is empty. (Doesn't show any bucket)

## Possible Solution
Make "s3:prefix": "" match the root folder

It might also be related that if I use
```
     "Action": [
       "s3:ListBucket",
       "s3:GetObject"
     ],
```
instead of s3:*, then I get a:
```
mc: <ERROR> Cannot add new policy. Policy has invalid resource.
```

## Steps to Reproduce (for bugs)

1. Use above policy on a user (replace bucket and folder)
2. Create the folder.
3. mc ls minio/bucket/data/ (Is successful)
4. mc ls minio/bucket/ (fails)

## Context
I need the user to see what folders are available.

## Regression
No (I think)

## Your Environment

* Version used (`minio version`): 2019-01-10T00:21:20Z
* Environment name and version (e.g. nginx 1.9.1): docker
* Server type and version: Docker under Ubuntu Linux for Server / Windows with mc client

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add policy conditions support for Listing operations on browser

## Motivation and Context
Fixes https://github.com/minio/minio/issues/7095

## Regression
No

## How Has This Been Tested?
Using the policy and reproducer mentioned in https://github.com/minio/mc/issues/2647

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#b8540552-30b5-44a8-a3c5-015ecbb9aa32) |
<a name="b8540552-30b5-44a8-a3c5-015ecbb9aa32"></a>
### 7106-55994b8/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32178
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c29888e364c1:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 28 seconds
(2/13) Running aws-sdk-go tests ... done in 1 seconds
(3/13) Running aws-sdk-java tests ... done in 5 seconds
(4/13) Running aws-sdk-php tests ... done in 50 seconds
(5/13) Running aws-sdk-ruby tests ... done in 15 seconds
(6/13) Running mc tests ... done in 1 minutes and 11 seconds
(7/13) Running minio-dotnet tests ... FAILED in 5 minutes and 59 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=We encountered an internal error, please try again.)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=We encountered an internal error, please try again.) ---> Minio.Exceptions.MinioException: Minio API responded with message=We encountered an internal error, please try again.
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 371
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 513
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 359
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, Dictionary`2 sseHeaders, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 492
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 254
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 923
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2134
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 221

Executed 6 out of 13 tests successfully.
```

**Review by Praveenrajmani — APPROVED** [review]
Tested with iam user role + readwrite policy. LGTM

**Review by poornas — APPROVED** [review]
Tested LGTM

**Pull request merged**
