### PR TITLE
Fix credential parsing in signature v4

### LINKED ISSUE #7376: Handle wrong formatted MINIO_ACCESS_KEY
minio does not complain about an access key like "bWluaW8=". Instead, it returns 400 on any request.

## Expected Behavior
If an access key like "bWluaW8=" is not allowed, minio should complain during startup phase. Additionally, the returned error should be self-explanatory, e.g. "The access key provided contains bad characters".

## Current Behavior
minio does not complain about an access key like "bWluaW8=". Instead, it returns 400 on any request.

```bash
mc: <ERROR> Unable to initialize new config from the provided credentials. Missing fields in request.
```

Server side error log:
```
[RESPONSE] [155274006.544475] [2019-03-16 12:41:05 +0000]
400 Bad Request
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 158C70DCDD58DD48
X-Minio-Deployment-Id: 636d5d4a-20f6-40a6-bc58-792156c2cc01
Server: Minio/RELEASE.2019-03-13T21-59-47Z
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MissingFields</Code><Message>Missing fields in request.</Message><BucketName>probe-bucket-sign-diizp61djrhh</BucketName><Resource>/probe-bucket-sign-diizp61djrhh/</Resource><RequestId>158C70DCDD58DD48</RequestId><HostId>636d5d4a-20f6-40a6-bc58-792156c2cc01</HostId></Error>
```
Currently, a non well formatted access key leads to non-concluding errrors.

## Steps to Reproduce (for bugs)
1. Configure access key like "bWluaW8="
2. Start minio
3. Add the host using`mc config host add server http://minio:9000 bWluaW8= test1230912384231 --api S3v4`
4. Run any `mc`command against the host

## Your Environment
* Version used (`minio version`): minio/minio:RELEASE.2019-03-13T21-59-47Z
* MC version used: Version: 2019-03-13T21:05:06Z
* Environment name and version: docker-1.13.1-65.git1185cfd.fc29.x86_64
* Operating System and version (`uname -a`): Fedora 29 4.18.16-300.fc29.x86_64

### PR DESCRIPTION
**Pull request by poornas**
fixes : #7376

## Motivation and Context

See issue referenced above.

## Regression
 No

## How Has This Been Tested?

with repro given in issue
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — DISMISSED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2c793e11-afa2-4495-ac43-ce924ffbe92a) |
| mint-compression-fs.sh | :x: [more...](#cdd23946-c9de-4edb-be21-94da1cc774bd) |
<a name="cdd23946-c9de-4edb-be21-94da1cc774bd"></a>
### 7377-aa49dea/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31747
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b91d0a909b8a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 49 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 24 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 41 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 41 seconds
(11/14) Running minio-js tests ... done in 37 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 22 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "args": {
    "bucket_name": "minio-py-test-6c8226d6-17c9-478f-b0a6-4501e7bd9b64",
    "object_name": "b9dfc386-c294-4782-947f-23912284d936"
  },
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 69,
  "message": "AccessDenied: message: Access Denied"
}

Executed 11 out of 14 tests successfully.
```
<a name="2c793e11-afa2-4495-ac43-ce924ffbe92a"></a>
### 7377-aa49dea/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30468
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 60e77b5f083e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ub5w3uu9xzrsmw",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 368,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:30468/aws-sdk-go-test-ub5w3uu9xzrsmw: dial tcp 72.28.97.59:30468: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by kannappanr — DISMISSED** [review]
LGTM and tested

**Review by kannappanr — APPROVED** [review]

**Comment by poornas** [comment]
can you reapprove? there was a staticcheck warning failing travis build

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0760f9fa-1e4f-4e73-b529-6644f04a6e58) |
| mint-worm.sh | :x: [more...](#46832666-30ec-45c0-9ee2-845475972de6) |
<a name="0760f9fa-1e4f-4e73-b529-6644f04a6e58"></a>
### 7377-156cd97/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30200
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8f16538f42ab:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mbrfcz42n3yrbx",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 286,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.51:30200/aws-sdk-go-test-mbrfcz42n3yrbx: dial tcp 72.28.97.51:30200: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="46832666-30ec-45c0-9ee2-845475972de6"></a>
### 7377-156cd97/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30738
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b22307e9a6fe:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-73o2w2rtso5b3y46z9aatkeerrvfdkwxc2yz1h6dp0y5a66i9zgc00n",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 4443,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30738/bucket-73o2w2rtso5b3y46z9aatkeerrvfdkwxc2yz1h6dp0y5a66i9zgc00n: dial tcp 72.28.97.55:30738: connect: connection refused",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```

**Pull request merged**
