### PR TITLE
fix: Audit tests on the correct response writer type

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Make Audit TTFB, response time and status code works.

## How to test this PR?

1. Run an audit http logger (to run with python 2)

```python
import socket
import thread

def handle(client_socket, address):
  # while True:
  data = client_socket.recv(2048)
  #   if not data: break
  print(data)
  client_socket.close()

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind((socket.gethostname(), 8080))
server.listen(20)

while True: # listen for incoming connections
  client_socket, address = server.accept()
  print("request from the ip",address[0])
  # spawn a new thread that run the function handle()
  thread.start_new_thread(handle, (client_socket, address))
```

2. 
```
$ export MINIO_AUDIT_WEBHOOK_ENABLE_target1=on
$ export MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://localhost:8080/
$ minio server /tmp/fs/
```

3. Do some S3 operations with mc

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by vadmeste** [comment]
Ready for review!

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#47c29cce-4fc6-4caf-aed4-05caca7ba6cb) |
| mint-gateway-azure.sh | :x: [more...](#eb1f4585-ec03-45bf-87ce-0f6ed4c97855) |
| mint-gateway-nas.sh | :x: [more...](#bd64415c-f79b-43f0-941f-57ac5f7e6b7f) |
<a name="eb1f4585-ec03-45bf-87ce-0f6ed4c97855"></a>
### 9445-d7f658d/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31052
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f2d6843943cd:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 37 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... FAILED in 49 seconds
{
  "name": "awscli",
  "duration": 3733,
  "function": "aws --endpoint-url http://minio-dev3.minio.io:31052 s3api copy-object --bucket awscli-mint-test-bucket-12035 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-12035/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 2 minutes and 53 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 37 seconds
(8/15) Running minio-go tests ... FAILED in 4 minutes and 2 seconds
{}
(8/15) Running minio-java tests ... FAILED in 25 minutes and 58 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1691,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-9sknck, objectName = minio-java-test-2ffgsqr, resource = /minio-java-test-9sknck/minio-java-test-2ffgsqr, requestId = 160A5399D994DB7F, hostId = d2b90eb4-4e22-4324-bb45-b01038cfb39a)\nrequest={method=PUT, url=http://minio-dev3.minio.io:31052/minio-java-test-9sknck/minio-java-test-2ffgsqr?legal-hold=, headers=Host: minio-dev3.minio.io:31052\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200429T152218Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200429/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160A5399D994DB7F\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 Apr 2020 15:22:18 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... FAILED in 2 minutes and 7 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-81bc47e1-3f2e-4e98-9bb2-f5ae971966b7, recursive:true",
  "duration": 215,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(8/15) Running minio-py tests ... done in 9 minutes and 45 seconds
(9/15) Running s3cmd tests ... FAILED in 41 seconds
{
  "name": "s3cmd",
  "duration": "1625",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(9/15) Running s3select tests ... done in 21 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="bd64415c-f79b-43f0-941f-57ac5f7e6b7f"></a>
### 9445-d7f658d/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32504
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9e386058961a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 18 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... FAILED in 39 seconds
{}
(9/15) Running minio-java tests ... FAILED in 26 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 24,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-nbk0c4, objectName = minio-java-test-3o7iemr, resource = /minio-java-test-nbk0c4/minio-java-test-3o7iemr, requestId = 160A51B70B99DEE1, hostId = debe30df-afef-4848-9984-0272398aedd6)\nrequest={method=PUT, url=http://minio-c3.minio.io:32504/minio-java-test-nbk0c4/minio-java-test-3o7iemr?legal-hold=, headers=Host: minio-c3.minio.io:32504\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200429T144745Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200429/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160A51B70B99DEE1\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 Apr 2020 14:47:45 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 30 seconds
(10/15) Running minio-py tests ... done in 53 seconds
(11/15) Running s3cmd tests ... done in 19 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="47c29cce-4fc6-4caf-aed4-05caca7ba6cb"></a>
### 9445-d7f658d/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32669
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e1fbbb6761c3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 40 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... FAILED in 37 seconds
{}
(9/15) Running minio-java tests ... FAILED in 37 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 129,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-3sr5vlv, objectName = minio-java-test-20hf8a5, resource = /minio-java-test-3sr5vlv/minio-java-test-20hf8a5, requestId = 160A51CAFF8708F0, hostId = 2b6a8399-b1fb-4305-9f7c-4779db3a47cf)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32669/minio-java-test-3sr5vlv/minio-java-test-20hf8a5?legal-hold=, headers=Host: minio-dev6.minio.io:32669\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200429T144910Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200429/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160A51CAFF8708F0\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 Apr 2020 14:49:10 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 48 seconds
(10/15) Running minio-py tests ... done in 58 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 0 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#adfa9141-f54d-4467-a85b-87614e16cb88) |
| mint-gateway-azure.sh | :x: [more...](#00ae4e61-6ec7-4d4a-81c5-0601bee6f27c) |
| mint-gateway-nas.sh | :x: [more...](#3c2b861d-23ad-4df7-a403-76d0897a3aae) |
<a name="00ae4e61-6ec7-4d4a-81c5-0601bee6f27c"></a>
### 9445-5bb7aa1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31472
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7f6c59350507:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... FAILED in 49 seconds
{
  "name": "awscli",
  "duration": 3722,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31472 s3api copy-object --bucket awscli-mint-test-bucket-30467 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-30467/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 8 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 22 seconds
(8/15) Running minio-go tests ... FAILED in 3 minutes and 59 seconds
{}
(8/15) Running minio-java tests ... FAILED in 26 minutes and 13 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1647,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-3vfah9r, objectName = minio-java-test-107nlb, resource = /minio-java-test-3vfah9r/minio-java-test-107nlb, requestId = 160A56CDCF50B2E0, hostId = 13387367-4044-49be-9f6b-fec4c61b83fb)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31472/minio-java-test-3vfah9r/minio-java-test-107nlb?legal-hold=, headers=Host: minio-dev6.minio.io:31472\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200429T162100Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200429/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160A56CDCF50B2E0\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 Apr 2020 16:21:00 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... FAILED in 2 minutes and 8 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-b7efcc64-cab8-4be5-88c8-473e35caabfb, recursive:true",
  "duration": 207,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(8/15) Running minio-py tests ... done in 9 minutes and 40 seconds
(9/15) Running s3cmd tests ... FAILED in 41 seconds
{
  "name": "s3cmd",
  "duration": "1713",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(9/15) Running s3select tests ... done in 21 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="adfa9141-f54d-4467-a85b-87614e16cb88"></a>
### 9445-5bb7aa1/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31149
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e19d6d95f13f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 21 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... FAILED in 31 seconds
{}
(9/15) Running minio-java tests ... FAILED in 39 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 48,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-1qvhmpt, objectName = minio-java-test-3pc34fp, resource = /minio-java-test-1qvhmpt/minio-java-test-3pc34fp, requestId = 160A54E7C76F0FAE, hostId = 2f11b0d5-9a3b-4bf8-9c6a-50e8eb1bce6d)\nrequest={method=PUT, url=http://minio-dev3.minio.io:31149/minio-java-test-1qvhmpt/minio-java-test-3pc34fp?legal-hold=, headers=Host: minio-dev3.minio.io:31149\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200429T154613Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200429/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160A54E7C76F0FAE\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 Apr 2020 15:46:13 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 36 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 2 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 2 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="3c2b861d-23ad-4df7-a403-76d0897a3aae"></a>
### 9445-5bb7aa1/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31736
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 034b058c70c4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 43 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 34 seconds
{}
(9/15) Running minio-java tests ... FAILED in 26 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 33,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-3eru3gt, objectName = minio-java-test-21qa6j1, resource = /minio-java-test-3eru3gt/minio-java-test-21qa6j1, requestId = 160A54F984BEA0B5, hostId = cffb195b-1ce8-4ef5-a9c6-2b5125092990)\nrequest={method=PUT, url=http://minio-dev3.minio.io:31736/minio-java-test-3eru3gt/minio-java-test-21qa6j1?legal-hold=, headers=Host: minio-dev3.minio.io:31736\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200429T154729Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200429/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160A54F984BEA0B5\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 Apr 2020 15:47:29 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... FAILED in 9 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, metaData)",
  "args": "bucketName:minio-js-test-37dc6f48-a791-402f-accb-c9da67d714e8, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 837,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)"
}
(9/15) Running minio-py tests ... done in 56 seconds
(10/15) Running s3cmd tests ... done in 17 seconds
(11/15) Running s3select tests ... done in 1 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by anthu** [comment]
Hey,
First of all thank you for fixing this!

I didn't see this PR and sat yesterday on this bug, (related to and raised in #9406). Unfortunately this fix breaks the audit log for several other endpoints which are not covered by the metrics, such as `AssumeRoleWithClientGrants`.

see audit log produced by current master:
```
{
   "version":"1",
   "deploymentid":"99c6fa2b-103e-4645-8258-9839390d2378",
   "api":{
      "name":"AssumeRoleWithClientGrants",
      "timeToFirstByte":"0s",
      "timeToResponse":"0s"
   },
   "remotehost":"::1",
   "requestID":"160A8FB897DB99F8",
   "userAgent":"curl/7.64.1",
   "requestQuery":{
      "Action":"AssumeRoleWithClientGrants",
      "DurationSeconds":"3600",
      "Token":"asdsfA",
      "Version":"2011-06-15"
   },
   "requestHeader":{
      "Accept":"*/*",
      "User-Agent":"curl/7.64.1"
   },
   "responseHeader":{
      "Accept-Ranges":"bytes",
      "Content-Length":"284",
      "Content-Security-Policy":"block-all-mixed-content",
      "Content-Type":"application/xml",
      "ETag":"",
      "Server":"MinIO/DEVELOPMENT.GOGET",
      "Vary":"Origin",
      "X-Amz-Request-Id":"160A8FB897DB99F8",
      "X-Xss-Protection":"1; mode=block"
   }
}
```

I could not fix it myself yesterday, but maybe we need a fallback assertion to `logger.ResponseWriter` at https://github.com/minio/minio/blob/master/cmd/logger/audit.go#L148

**Comment by vadmeste** [comment]
@anthu yes you are right. I didn't see that. I will merge S3 stats and the other stats.

**Pull request merged**
