### PR TITLE
Set maxResources appropriately for gateway like server

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Set maxResources appropriately for gateway like server

## Motivation and Context
Set upto max resources appropriately

## How Has This Been Tested?
Manually using minio-dotnet project

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by kannappanr** [comment]
@harshavardhana Should we run mint in Gteway mode for this change?

**Comment by nitisht** [comment]
> Should we run mint in Gteway mode for this change?

Tested with minio-dotnet tests, failing test passed.

**Review by nitisht — APPROVED** [review]

**Comment by nitisht** [comment]
Ignoring codecov as this is gateway change

**Pull request merged**
