### PR TITLE
fix: remove extra newline from GetConfig() output

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: remove extra newline from GetConfig() output

## Motivation and Context
The cosmetic change removes an extra spurious newline

## How to test this PR?
Compile and inspect `mc admin config expory myminio` output

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#6b836610-887f-4983-8219-b595a52c6ea8) |
| mint-large-bucket.sh | :x: [more...](#c0a301f5-75e8-45f7-bd3f-9da7f28e6a37) |
| mint-worm.sh | :x: [more...](#4c60127a-e2cf-4518-8c32-fe3e509c92b8) |
<a name="4c60127a-e2cf-4518-8c32-fe3e509c92b8"></a>
### 8678-949a5ed/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30266
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f586de350688:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-j337lmr02lo725hnhbk2si9g2yp5gs8xjpwdjb68b6jqtx6pl5n7s7m",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120293,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30266/bucket-j337lmr02lo725hnhbk2si9g2yp5gs8xjpwdjb68b6jqtx6pl5n7s7m: dial tcp 72.28.97.55:30266: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="c0a301f5-75e8-45f7-bd3f-9da7f28e6a37"></a>
### 8678-949a5ed/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31879
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 62fe29d3e538:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 10 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 1 minutes and 26 seconds
(5/13) Running minio-go tests ... FAILED in 4 minutes and 1 seconds
{
  "args": {},
  "duration": 126808,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="6b836610-887f-4983-8219-b595a52c6ea8"></a>
### 8678-949a5ed/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31039
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9b112fa21714:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{
  "name": "awscli",
  "duration": 309702,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=31039): Max retries exceeded with url: /awscli-mint-test-bucket-20400 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7fa6842fe160>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by Praveenrajmani — APPROVED** [review]
LGTM and tested

**Comment by harshavardhana** [comment]
PTAL @vadmeste

**Review by kannappanr — APPROVED** [review]
Tested. LGTM

**Pull request merged**
