### PR TITLE
add timeout while getHostIP

### PR DESCRIPTION
**Pull request by TestMsr**
## Description
net.LookupIP method timeout depending on the system config,such as options timeout:60 in /etc/resolv.conf.
program will stuck in poor situation while dns server unreachable

## Motivation and Context
use the more flexible method to control timeout in program.
avoid stuck for a long time.

## How to test this PR?
1. add options timeout:60 to resolv.conf and point nameserver to bellow server
2. add time.Sleep(30*time.Second) before server response [simple dns server](https://gist.github.com/walm/0d67b4fb2d5daf3edd4fad3e13b162cb)

3. afert 5 second console shows **ERROR Invalid argument: i/o timeout**

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
It is blocking for a reason, what is supposed to happen if the resolver takes more than 5 seconds? - this is not acceptable behavior. 

Can you explain what are you trying to solve here?

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#7edda213-d73e-4f81-abbb-b084ea9fda50) |
<a name="7edda213-d73e-4f81-abbb-b084ea9fda50"></a>
### 14098-31f86ef/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:32601
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 49 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 15 seconds
(8/15) Running minio-dotnet tests ... done in 26 seconds
(9/15) Running minio-go tests ... done in 43 seconds
(10/15) Running minio-java tests ... FAILED in 7 seconds
Exception in thread "main" java.lang.AssertionError: object count; expected=1050, got=1049 expected:<1049> but was:<1050>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at FunctionalTest.testListObjects(FunctionalTest.java:1406)
	at FunctionalTest.listObjects(FunctionalTest.java:1451)
	at FunctionalTest.runObjectTests(FunctionalTest.java:3682)
	at FunctionalTest.runTests(FunctionalTest.java:3718)
	at FunctionalTest.runEndpointTests(FunctionalTest.java:3817)
	at FunctionalTest.main(FunctionalTest.java:3937)
(10/15) Running minio-js tests ... done in 37 seconds
(11/15) Running minio-py tests ... done in 38 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 1 seconds
(14/15) Running versioning tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by TestMsr** [comment]
> It is blocking for a reason, what is supposed to happen if the resolver takes more than 5 seconds? - this is not acceptable behavior.
> 
> Can you explain what are you trying to solve here?

[there](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts) have some related reference about kubernetes dns problem which sometimes taking 5 or even more seconds.
add timeout may expose these problem directly instead of unstable stuck

**Comment by harshavardhana** [comment]
> [there](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts) have some related reference about kubernetes dns problem which sometimes taking 5 or even more seconds.

I don't know if this is true even now the blog is from 4yrs ago. Even if we want to do it, this PR is not complete - we cannot just print `i/o timeout` on the screen - it requires proper guidance to the user what they can do. 

Please close the PR - I shall send a PR that incorporates guiding the user etc.

**Comment by TestMsr** [comment]
sure,waiting for your pr.

**Pull request closed without merging**
