### PR TITLE
Return bucketNameInvalid properly in B2 gateway

### LINKED ISSUE #5758: b2 gateway gives misleading error messages for "mc mb" failures
The b2 gateway gives several error messages which are misleading in the face of failures to make buckets (`mc mb`) on b2. None of these are fatal, just cosmetic, but they had me wondering whether I had set up the system incorrectly.

## Expected Behavior

Example 1.

```
Eds-MacBook-Pro:~ ed$ mc mb myb2/mp3
mc: <ERROR> Unable to make bucket `myb2/mp3`. We encountered an internal error, please try again.
```

b2 buckets have a minimum size length of 6 characters, per the Backblaze web site which reads: "Each bucket name must be at least 6 characters long."

Example 2.

```
Eds-MacBook-Pro:~ ed$ mc mb myb2/b2-mp3
mc: <ERROR> Unable to make bucket `myb2/b2-mp3`. The specified bucket does not exist
```

b2 buckets cannot be named with the initial prefix characters "b2-", per the Backblaze web site which reads: "BucketName must not start with 'b2-'. reserved for Backblaze use."

## Current Behavior

Error messages are less informative than they might be, though there is no loss of data, just a little temporary confusion.

## Possible Solution

Perhaps the detailed API responses for these two failures (bucket name too short; bucket name reserved) can be examined to give a better error report.

## Context

After setting up a b2 gateway, I was surprised that my first two tries to use it failed.

## Your Environment
* Version used (`minio version`):

```
$ docker run minio/minio version
Version: 2018-03-30T00:38:44Z
Release-Tag: RELEASE.2018-03-30T00-38-44Z
Commit-ID: 804a4f9c159ecef7093585a5b577e03a382af50e
```

* Operating System and version (`uname -a`):
```
Linux bastion-0 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Return bucketNameInvalid properly in B2 gateway

## Motivation and Context
Fixes #5758

## How Has This Been Tested?
Manually using B2 gateway

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5787-62f5be5/gopath/src/github.com/minio
+ git -C 5787-62f5be5/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5787-62f5be5/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5787-62f5be5/gopath/src/github.com/minio/minio fetch --quiet minio pull/5787/head:pr5787
+ git -C 5787-62f5be5/gopath/src/github.com/minio/minio checkout --quiet pr5787
+ GOPATH=/home/bala/mintauto/5787-62f5be5/gopath
+ make -C 5787-62f5be5/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#fc8c6c2b-4017-47dc-94f0-e6201ff9557f) |
<a name="fc8c6c2b-4017-47dc-94f0-e6201ff9557f"></a>
### 5787-974df47/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31044
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp a3007f76ece1:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 8 minutes and 7 seconds
(3/12) Running aws-sdk-ruby tests ... done in 50 seconds
(4/12) Running awscli tests ... done in 3 minutes and 36 seconds
(5/12) Running mc tests ... done in 7 minutes and 35 seconds
(6/12) Running minio-dotnet tests ... done in 1 minutes and 14 seconds
(7/12) Running minio-go tests ... done in 2 seconds
(8/12) Running minio-java tests ... done in 30 seconds
(9/12) Running minio-js tests ... FAILED in 2 minutes and 33 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-f4d62dac-d7a3-451e-8313-c696c66336a7",
  "duration": 268,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:511:10) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 8 out of 12 tests successfully.
```

**Review by nitisht — DISMISSED** [review]

**Comment by harshavardhana** [comment]
@nitisht @krishnasrinivas PTAL

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#9d95f326-7f56-48f7-b622-7e17ace31c04) |
<a name="9d95f326-7f56-48f7-b622-7e17ace31c04"></a>
### 5787-c467452/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30573
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp c0c6ac9e57d1:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 7 minutes and 54 seconds
(3/12) Running aws-sdk-ruby tests ... done in 42 seconds
(4/12) Running awscli tests ... done in 4 minutes and 2 seconds
(5/12) Running mc tests ... done in 7 minutes and 34 seconds
(6/12) Running minio-dotnet tests ... done in 1 minutes and 9 seconds
(7/12) Running minio-go tests ... done in 1 seconds
(8/12) Running minio-java tests ... done in 35 seconds
(9/12) Running minio-js tests ... FAILED in 2 minutes and 49 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-f697918d-bdc9-4d53-8e69-822303ff1da0",
  "duration": 278,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:511:10) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 8 out of 12 tests successfully.
```

**Review by nitisht — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
