### PR TITLE
Support custom endpoint for Azure remote storage tier

### LINKED ISSUE #19186: AzureGov endpoint not working
## Expected Behavior

Setting up a lifecycle policy to backup buckets to Azure Blob

## Current Behavior

The azure.net endpoint is used instead of the azure.us, the endpoint is hardcoded [here](https://github.com/minio/minio/blob/d5656eeb6535b20eeb9a925cdad277153e75a33b/cmd/warm-backend-azure.go#L181)

## Possible Solution

Update the codebase to switch off the cloud type to change how the URL is constructed

### PR DESCRIPTION
**Pull request by jgriff**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

This commits adds support for using the `--endpoint` arg when creating a tier of type `azure`. This is needed to connect to Azure's Gov Cloud instance.  For example,

```
mc ilm tier add azure TARGET TIER_NAME \
   --account-name ACCOUNT \
   --account-key KEY \
   --bucket CONTAINER \
   --endpoint https://ACCOUNT.blob.core.usgovcloudapi.net
   --prefix PREFIX \
   --storage-class STORAGE_CLASS
```

## Motivation and Context

Prior to this, the endpoint was hardcoded to `https://ACCOUNT.blob.core.windows.net`. The docs were even explicit about this, stating that `--endpoint` is:

  "Required for `s3` or `minio` tier types. This option has no effect for any
  other value of `TIER_TYPE`."

Now, if the endpoint arg is present it will be used.  If not, it will fall back to the same default behavior of `ACCOUNT.blob.core.windows.net`.

### Preserves existing default behavior

Verify you can still target normal Azure (`https://ACCOUNT.blob.core.windows.net`) without the `--endpoint`:

```
mc ilm tier add azure TARGET TIER_NAME \
   --account-name ACCOUNT \
   --account-key KEY \
   --bucket CONTAINER \
   --prefix PREFIX \
   --storage-class cool
``` 

### Targeting Azure Gov Cloud

If you have access to an Azure Gov Cloud instance, verify you can target it by explicitly specifying the `--endpoint`:

```
mc ilm tier add azure TARGET TIER_NAME \
   --account-name ACCOUNT \
   --account-key KEY \
   --bucket CONTAINER \
   --endpoint https://ACCOUNT.blob.core.usgovcloudapi.net
   --prefix PREFIX \
   --storage-class cool
``` 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [x] Internal documentation updated (see https://github.com/minio/docs/pull/1146)
- [x] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by vadmeste — COMMENTED** [review]
LGTM

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by gXkch** [comment]
I think this commit breaks existing Azure Tiers. I had to revert back to an older docker image because it tries to do put requests on blob.core.windows.net instead of \<Account\>.blob.core.windows.net. At least something has changed with existing Azure Tiers so that they cannot connect to the storage account anymore.

**Comment by harshavardhana** [comment]
> I think this commit breaks existing Azure Tiers. I had to revert back to an older docker image because it tries to do put requests on blob.core.windows.net instead of <Account>.blob.core.windows.net. At least something has changed with existing Azure Tiers so that they cannot connect to the storage account anymore.

Please provide more details like logs etc.

**Comment by bjornuppeke** [comment]
I am experiencing the exact same thing. An Azure Tier created in a previous version of Minio is now broken after updating Minio.

from the logs while trying to delete from cold storage:

```
API: SYSTEM.transition                                                                                                                                                                                                                                                                                                                                                                                                             
Time: 09:46:09 UTC 10/07/2024                                                                                                                                                                                                                                                                                                                                                                                                      
DeploymentID: 79a29093-0787-4e64-90c2-64edc87bffc0                                                                                                                                                                                                                                                                                                                                                                                 
Error: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, github.com/Azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157                                                                                                                                                                                                                                                                                                    
HTTP request failed                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                   
Delete "http://blob.core.windows.net/bucket/path/timeout=61": dial tcp: lookup blob.core.windows.net on 10.0.0.10:53: no such host                                                                                                                                                                                                   
 (*pipeline.pcError)                                                                                                                                                                                                                                                                                                                                                                                                               
       3: internal/logger/logger.go:268:logger.LogIf()                                                                                                                                                                                                                                                                                                                                                                             
       2: cmd/logging.go:120:cmd.transitionLogIf()                                                                                                                                                                                                                                                                                                                                                                                 
       1: cmd/bucket-lifecycle.go:364:cmd.(*expiryState).Worker()
```

**Pull request merged**
