### PR TITLE
[proposal] remove GCS gateway, use S3 gateway instead

### LINKED ISSUE #8918: GCS Gateway - CopyObject: io: read/write on closed pipe
With minio running as GCS gateway in docker, When trying to copy a file from one bucket to another using the "copy_object" method, the minio server throws an io error:
```
minio_1           | 
minio_1           | API: CopyObject(bucket=<redacted>, object=<redacted>)
minio_1           | Time: 02:45:47 UTC 01/29/2020
minio_1           | RequestID: <redacted>
minio_1           | RemoteHost: 192.168.16.11
minio_1           | UserAgent: MinIO (Linux; x86_64) minio-py/5.0.6
minio_1           | Error: io: read/write on closed pipe
minio_1           |        2: cmd/gateway/gcs/gateway-gcs.go:788:gcs.(*gcsGateway).GetObject()
minio_1           |        1: cmd/gateway/gcs/gateway-gcs.go:750:gcs.(*gcsGateway).GetObjectNInfo.func1()
```

The file does appear to be copied successfully, however.
I've also tried this on a couple different versions including :latest with same behavior.

## Current Behavior
Object is copied successfully, but throws an IO error.

## Steps to Reproduce (for bugs)
With minio running as gcs gateway, simply using the copy_object method should reproduce. Using the mc command line client does not reproduce the issue, however.

## Your Environment

* Version used (`minio version`): 2019-05-14T23:57:45Z
* Environment name and version (e.g. nginx 1.9.1): python:3.7.3
* Server type and version: Docker version 19.03.5, build 633a0ea

### LINKED ISSUE #8928: GCS Gateway: PutObject: Error: storage: object doesn't exist
When using GCS Gateway minio logs an error when uploading objects. The object got uploaded after several tries. 

We are also using S3 Gateway and it works as expected.

The error logged:

```
API: PutObject(bucket=test-bucket, object=v2/merchant=60003/hour=2020020317/ls.s3.fc3644b4-7a00-43ca-beb5-2a5dead213eb.2020-02-03T17.40.part6.txt)
Time: 17:42:22 UTC 02/03/2020
DeploymentID: bc85f804-af0d-499a-ac05-72a9dad5e293
RequestID: 15EFF555AAAAD529
RemoteHost: 127.0.0.1
Host: test-bucket.localhost:9000
UserAgent: aws-sdk-ruby2/2.11.427 jruby/2.5.3 java resources
Error: storage: object doesn't exist
       4: cmd/gateway/gcs/gateway-gcs.go:871:gcs.(*gcsGateway).GetObjectInfo()
       3: cmd/object-lock.go:171:cmd.checkPutObjectLockAllowed()
       2: cmd/object-handlers.go:1314:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

Sometimes the exception has different stack trace:

```
Error: storage: object doesn't exist
       4: cmd/gateway/gcs/gateway-gcs.go:871:gcs.(*gcsGateway).GetObjectInfo()
       3: cmd/object-lock.go:539:cmd.checkPutObjectRetentionAllowed()
       2: cmd/object-handlers.go:1251:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

## Regression

Last working version `RELEASE.2019-10-12T01-39-57Z`, all newer have the problem.

## Your Environment

* Version used: `RELEASE.2019-12-17T23-16-33Z`, but all earlier versions up to `RELEASE.2019-10-12T01-39-57Z` have this issue
Client: `aws-sdk-ruby2/2.11.427 jruby/2.5.3 ` (`logstash`)

Mini env variables:

```
MINIO_DOMAIN=localhost
MINIO_ACCESS_KEY_FILE=access_key
MINIO_KMS_MASTER_KEY_FILE=kms_master_key
MINIO_SSE_MASTER_KEY_FILE=sse_master_key
MINIO_ACCESS_KEY=admin
MINIO_UPDATE=off
MINIO_SECRET_KEY_FILE=secret_key
MINIO_SECRET_KEY=password
MINIO_CACHE_MAXUSE=0
```

let me know if you need more info

### LINKED ISSUE #8934: GCS Gateway - GetObject return incorrect metadata from disk cache
With minio running as GCS gateway in docker (disk caching is enabled). After updated metadata  "get_object" method returned old data if the object is already in disk cache.

I'm using AWS SDK for .NET with MinIO Server.
```
const string bucketName = "test-container-1";
const string objectName = "586191.webp";

var request = new CopyObjectRequest
                {
                    SourceBucket = bucketName,
                    SourceKey = objectName,
                    DestinationBucket = bucketName,
                    DestinationKey = objectName,
                    MetadataDirective = S3MetadataDirective.REPLACE,
                };
request.Metadata.Add("watermark", "true");
var result = await s3Client.CopyObjectAsync(request );

var requestMeta = new GetObjectMetadataRequest { BucketName = bucketName, Key = objectName,  };
//The response contains incorrect metadata (old data from disk cache)
var responseMetaBefore = await s3Client.GetObjectMetadataAsync(requestMeta);

 var requestGetObject = new GetObjectRequest {BucketName = bucketName, Key = objectName};
//The response contains incorrect metadata (old data from disk cache)
var responseGetObject = await s3Client.GetObjectAsync(requestGetObject);

//The response contains correct metadata (new data from disk cache)
var responseMetaAfter = await s3Client.GetObjectMetadataAsync(requestMeta);
```
I think this is because  **cacheReader** contains not updated data.

https://github.com/minio/minio/blob/881e983ed97ae2101835f307f09fda93eb3428ad/cmd/disk-cache.go#L262-L268

## Current Behavior

Metadata in GCS is updated successfully. Metadata in disk cache is updated after running method get_object but returned old data.

## Steps to Reproduce (for bugs)

With minio running as gcs gateway with disk caching enabled, using the copy_object method with "x-amz-metadata-directive: REPLACE" to update metadata. Using the get_object method for get old metadata.

## Your Environment

* Version used (`minio version`): RELEASE.2020-01-25T02-50-51Z
* Server type and version: Docker version 19.03.5

### PR DESCRIPTION
**Pull request by harshavardhana**
Resolves #8934
Resolves #8928
Resolves #8918

## Description
[proposal] remove GCS gateway, use S3 gateway instead

## Motivation and Context
We do not maintain it, GCS supports S3 API use S3 gateway instead

## How to test this PR?
N/A

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#dae10519-7d05-413a-bb46-a39c2c9ad767) |
| mint-worm.sh | :x: [more...](#c727832c-7c5d-4e90-9cf0-1d561372bbfb) |
| mint-fs.sh | :x: [more...](#f41be20f-9fd3-47d9-978e-c0f00046a77e) |
| mint-gateway-azure.sh | :x: [more...](#f09d43eb-2503-4069-b034-e85b3d7a88c6) |
<a name="f41be20f-9fd3-47d9-978e-c0f00046a77e"></a>
### 8939-a44c225/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31006
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 40481109ba12:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 310643, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31006/awscli-mint-test-bucket-24995""}

Executed 0 out of 13 tests successfully.
```
<a name="dae10519-7d05-413a-bb46-a39c2c9ad767"></a>
### 8939-a44c225/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32374
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6fec668e712b:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 24 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 50 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 28 seconds
{
  "args": {},
  "duration": 110411,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="f09d43eb-2503-4069-b034-e85b3d7a88c6"></a>
### 8939-a44c225/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32184
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0253d9f21c05:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 5 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 48 seconds
(5/13) Running minio-go tests ... FAILED in 21 minutes and 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-1gkif3hhbfds535v",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 223,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="c727832c-7c5d-4e90-9cf0-1d561372bbfb"></a>
### 8939-a44c225/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30324
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2ffa7b0643ce:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-6fbeshamnakliivwgyi90g3w53zpshgefeul1zph8z5y5b2w3x0yq4s",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120274,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30324/bucket-6fbeshamnakliivwgyi90g3w53zpshgefeul1zph8z5y5b2w3x0yq4s: dial tcp 72.28.97.55:30324: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
PTAL @kannappanr check with @abperiasamy . IMO this will help reduce some cycles on our end and avoids unmaintained codebase.

**Comment by retinio** [comment]
My issue [#8934 ](url)
How to use S3 gateway to GCS? My current docker-compose.yml (according to the [documetation](https://docs.min.io/docs/minio-gateway-for-gcs.html))
```
version: '3.7'
minio:
    image: minio/minio
    container_name: minio
    volumes:
      - data-1:/data1
      - ./credentials.json:/credentials.json        
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_CACHE: "on"
      MINIO_CACHE_DRIVES: "/data1/cache"
      MINIO_CACHE_EXPIRY: 14
      MINIO_CACHE_QUOTA: 80 
      GOOGLE_APPLICATION_CREDENTIALS: ./credentials.json
    restart: always      
    command: gateway gcs my-storage

volumes:
  data-1:
```
I changed command:
```
    ...
    command:  gateway s3 https://storage.googleapis.com
```
but I get error
```
   ERROR Unable to initialize gateway backend: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
```

**Comment by harshavardhana** [comment]
@retinio first we don't want to keep the GCS gateway if it's your interest fork the project and maintain it yourself.

Secondary we will check why S3 gateway is not working with GCS - NOTE: you need to enable S3 https://cloud.google.com/storage/docs/interoperability if you have not done so, please do

**Comment by shamil** [comment]
@harshavardhana not sure about this change, but whole point of using Minio GCS gateway is because we want Minio to talk with native APIs with cloud providers, otherwise I don't see any point (except for caching) using the gateway. For our case, we use it only to put objects in buckets, so caching is not relevant here.

**Comment by harshavardhana** [comment]
@shamil we cannot satisfy all users here. Unfortunately it's a burden for us to maintain, work through these issues and reproduce them. Which makes it a maintenance nightmare, our current priorities do not align anymore with this gateway.

If it's important for you feel free to fork the project we cannot support it on our end.  if you need us to support and keep the code. Help us fix the bugs by sending PRs which we shall be happy to accept.

As long as the code is maintained, currently it's not maintained.

**Comment by harshavardhana** [comment]
So let me know if it can be maintained @shamil @retinio if not, we will be purging this functionality.

**Comment by retinio** [comment]
@harshavardhana Thank you! I created HMAC keys. Now minio is working with GCS. But error #8934 is reproducing. 
I still think this is becouse **cacheReader i**nitialize before the disk cache updated
https://github.com/minio/minio/blob/881e983ed97ae2101835f307f09fda93eb3428ad/cmd/disk-cache.go#L203
and  is not updated after metadata changes
https://github.com/minio/minio/blob/881e983ed97ae2101835f307f09fda93eb3428ad/cmd/disk-cache.go#L262-L268

**Comment by harshavardhana** [comment]
> @harshavardhana Thank you! I created HMAC keys. Now minio is working with GCS. But error #8934 is reproducing.
> I still think this is becouse **cacheReader i**nitialize before the disk cache updated

@retinio you should open a separate issue for that using GCS with `s3` gateway

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#a88497d1-8305-4d8a-ba9a-fff529239618) |
| mint-large-bucket.sh | :x: [more...](#6bbb3d47-bda8-4110-8440-d3a7ac3625cd) |
| mint-dist-xl.sh | :x: [more...](#9dc001ab-b174-4bf6-96d3-2af3654a13af) |
| mint-gateway-azure.sh | :x: [more...](#73132f12-0c4e-4875-9b98-238fb40e32a7) |
<a name="6bbb3d47-bda8-4110-8440-d3a7ac3625cd"></a>
### 8939-df4db0e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32396
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d4f464194276:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 7 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 50 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 15 seconds
{
  "args": {},
  "duration": 66939,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="9dc001ab-b174-4bf6-96d3-2af3654a13af"></a>
### 8939-df4db0e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32481
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e4e5b186839e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 25 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 31 seconds
(5/13) Running minio-go tests ... done in 11 minutes and 16 seconds
(6/13) Running minio-js tests ... FAILED in 14 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, metaData)",
  "args": "bucketName:minio-js-test-30bf3160-d411-4dc1-88c2-b5858a6e3325, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 557,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)"
}

Executed 5 out of 13 tests successfully.
```
<a name="73132f12-0c4e-4875-9b98-238fb40e32a7"></a>
### 8939-df4db0e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32525
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 17e801a03d16:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 18 seconds
(4/13) Running mc tests ... done in 7 minutes and 9 seconds
(5/13) Running minio-go tests ... FAILED in 21 minutes and 21 seconds
{
  "args": {
    "bucketName": "minio-go-test-mjxzs23xjrey43tt",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 234,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="a88497d1-8305-4d8a-ba9a-fff529239618"></a>
### 8939-df4db0e/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31845
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8324e6166706:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 11 seconds
{
  "name": "awscli",
  "duration": 9071,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by retinio** [comment]
@harshavardhana #8942

**Comment by harshavardhana** [comment]
Thanks @retinio

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#cec32659-20d1-49fa-8d26-79e6584769e9) |
| mint-large-bucket.sh | :x: [more...](#68d94c51-0fea-4ceb-8ff1-3226c36d6277) |
| mint-dist-xl.sh | :x: [more...](#39c31b96-64a1-47f7-b23d-1ba0c1a7355a) |
| mint-gateway-azure.sh | :x: [more...](#3ebd44bb-6df7-4995-b8ad-7619660e288a) |
<a name="68d94c51-0fea-4ceb-8ff1-3226c36d6277"></a>
### 8939-58e9175/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31710
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e1977b336430:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 21 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 46 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 17 seconds
{
  "args": {},
  "duration": 83066,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="39c31b96-64a1-47f7-b23d-1ba0c1a7355a"></a>
### 8939-58e9175/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32460
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d84edb48268e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 6 seconds
{"name": "awscli", "duration": 303752, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32460/awscli-mint-test-bucket-28341""}

Executed 0 out of 13 tests successfully.
```
<a name="3ebd44bb-6df7-4995-b8ad-7619660e288a"></a>
### 8939-58e9175/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31662
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 30db4a8754dd:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 19 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 17 seconds
(4/13) Running mc tests ... done in 6 minutes and 25 seconds
(5/13) Running minio-go tests ... FAILED in 21 minutes and 28 seconds
{
  "args": {
    "bucketName": "minio-go-test-91d6oazixjwa4zjt",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 241,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="cec32659-20d1-49fa-8d26-79e6584769e9"></a>
### 8939-58e9175/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31344
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9a3d4c17e455:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 8 seconds
{
  "name": "awscli",
  "duration": 5998,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#19516f07-4472-461e-a009-e13d21a17252) |
| mint-gateway-azure.sh | :x: [more...](#69ba2899-a630-43cc-b6a0-e23023036e4a) |
<a name="19516f07-4472-461e-a009-e13d21a17252"></a>
### 8939-778e757/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31625
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 359f56aab1a0:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 305813, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31625/awscli-mint-test-bucket-12172""}

Executed 0 out of 13 tests successfully.
```
<a name="69ba2899-a630-43cc-b6a0-e23023036e4a"></a>
### 8939-778e757/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31350
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7a7ff6f0c52f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 59 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 57 seconds
(5/13) Running minio-go tests ... FAILED in 21 minutes and 19 seconds
{
  "args": {
    "bucketName": "minio-go-test-m64hcf629dtzzjwm",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 239,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
@kannappanr has this been decided?

**Comment by harshavardhana** [comment]
We decided not to remove GCS gateway for now.

**Comment by adamhooper** [comment]
A note on my experience using the s3 gateway for GCS, for posterity:

Google Cloud Storage's "Interoperability" mode doesn't support the DeleteObjects API. The response is `InvalidArgument` with message: `Cannot create buckets using a POST.` (This is https://github.com/minio/mc/issues/2398)

**Pull request closed without merging**
