### PR TITLE
Allow skipping the credential validation for S3 gateway

### PR DESCRIPTION
**Pull request by jaym**
## Description
Add environment variable to skip credential check for S3 gateway

## Motivation and Context
The credential validation probes a random bucket, which seems to cause
problems for some people using proxies that limit which buckets are
accessible.

## How to test this PR?
The following example will fail to start the gateway because the credentials are invalid:
```
# export MINIO_ACCESS_KEY=fake_aws_s3_access_key
# export MINIO_SECRET_KEY=fake_aws_s3_secret_key
# go run ./ gateway s3
```

The following example will allow the gateway to start:
```
# export MINIO_ACCESS_KEY=fake_aws_s3_access_key
# export MINIO_SECRET_KEY=fake_aws_s3_secret_key
# export SKIP_CREDENTIAL_CHECK=true
# go run ./ gateway s3
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by harshavardhana** [comment]
What seems to be the problem that it causes using proxies ?

**Comment by jaym** [comment]
We've had some people with internal security policies that only allow access to a whitelisted set of buckets. The way credentials are validated currently in the minio gateway, they probe a random bucket which would not be whitelisted.

**Comment by harshavardhana** [comment]
> We've had some people with internal security policies that only allow access to a whitelisted set of buckets. The way credentials are validated currently in the minio gateway, they probe a random bucket which would not be whitelisted.

Then we should have a code that should automatically proceed, we don't need this type of environment variable. Can you should me what is the error that you see?

**Comment by jaym** [comment]
I'll try to track down the code, but it might be specific to the persons environment (could be that they just 500 all those requests). It might be a few days to get this info back.

Another option instead of disabling it would be if we could specify which bucket the credentials are validated against

**Comment by harshavardhana** [comment]
> I'll try to track down the code, but it might be specific to the persons environment (could be that they just 500 all those requests). It might be a few days to get this info back.

@jaym 500 looks wrong, either it should be 403 or 400 - we should investigate why there is 5xx here.

**Comment by jaym** [comment]
The 5xx wouldn't be coming from minio or S3, but from the proxy. It very well could be a 403. I've asked the person who was having problems and am waiting to hear back.

For more clarity though, the setup looks something like this:

```
minio +---> proxy +----> s3
```

When minio sends a bucket probe to the proxy, it provides a random bucket. The proxy has an internal security policy that says you may only use buckets that are whitelisted. So this request would never be sent to S3. Instead, it could do any number of things such as reset the connection, return a 5xx or 400/403. The proxy is the thing messing with our requests and we don't control what it does when we give it a bucket that isn't in the whitelist.

**Comment by harshavardhana** [comment]
> When minio sends a bucket probe to the proxy, it provides a random bucket. The proxy has an internal security policy that says you may only use buckets that are whitelisted. So this request would never be sent to S3. Instead, it could do any number of things such as reset the connection, return a 5xx or 400/403. The proxy is the thing messing with our requests and we don't control what it does when we give it a bucket that isn't in the whitelist.

So if you send 403 then it will work, the current code handles this already.  If you do send 500 it means there is an error on the backend which is unhandled. 

So until this is clear, I don't think this PR is correct. We would like to limit the number of ENVs that get added as it is a burden for us to maintain and test in future.

**Comment by jaym** [comment]
yea, cant be a 403, but could be one of the other things. I'll go ahead and close this for now and suggest that a 403 be returned for all the `probe-bucket-sign-*` requests through the proxy

**Pull request closed without merging**
