### PR TITLE
Change YAML files to reference the newer APIs

### PR DESCRIPTION
**Pull request by sinhaashish**
## Description
Yaml files modified to be compatible with k8s 1.16

## Motivation and Context
Kubernetes API's have changed , some deprecated APIs have been removed.
Refer
 https://kubernetes.io/blog/
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

## How to test this PR?
1. Deploy standalone MinIO server on Kubernetes.
2.  Deploy distributed MinIO server on Kubernetes.
3. Deploy MinIO GCS Gateway on Kubernetes.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#8d1bacb5-2f60-477d-a638-23ad8614cbaf) |
<a name="8d1bacb5-2f60-477d-a638-23ad8614cbaf"></a>
### 8299-724116c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32552
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f026af58253a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 56 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 32 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 33 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 14 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 28 seconds
{
  "args": {},
  "duration": 107837,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
Should we keep both type of files one with k8s1.16 default and another with .yaml.k8s1.13 ?

**Comment by sinhaashish** [comment]
> Should we keep both type of files one with k8s1.16 default and another with .yaml.k8s1.13 ?

I ran with older version (1.13) of kubectl client and server as  1.16 as Minikube took the latest version of k8s(1.16) . Refer [here](https://github.com/kubernetes/minikube/releases/tag/v1.4.0) 
With this PR and client 1.13 it works so IMO we dont need to keep two both types of yaml files.

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by harshavardhana** [comment]
I am talking about kubernetes sever versions are mostly 1.13 still

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by sinhaashish** [comment]
> I am talking about kubernetes sever versions are mostly 1.13 still

Tested it with server version 1.14 and it works Our docs says that minimum k8s version is 1.14
`To run this example, you need Kubernetes version >=1.4 cluster installed and running. ` 
Refer https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/k8s-yaml.md
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

The  main change in this PR is ` extensions/v1beta1` -> `apps.v1` and  `apps/v1beta1` -> `apps/v1` . 
`apps/v1` is present in k8s from 1.9 onwards. Refer https://kubernetes.io/blog/page/2/ .
So there is no breaking change, It was just that we were using a deprecated value in `appVersion` and with 1.16 those deprecated has been removed and this PR fixes that issue.

**Comment by harshavardhana** [comment]
Ah I see it is not clear from the PR description

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#22bbb83d-b61e-4dc7-85e6-a872035b2c48) |
| mint-large-bucket.sh | :x: [more...](#fef2feff-e1c4-4e81-b9d8-db087e884d01) |
| mint-dist-xl.sh | :x: [more...](#ac31e42a-d6ec-4c92-9a06-fc00c6c7d9fe) |
<a name="fef2feff-e1c4-4e81-b9d8-db087e884d01"></a>
### 8299-61f80ee/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32283
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2b595e15a5a1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 1 minutes and 37 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 42 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 54 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 38 seconds
{
  "args": {},
  "duration": 119405,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="22bbb83d-b61e-4dc7-85e6-a872035b2c48"></a>
### 8299-61f80ee/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31766
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 59a0b8afb987:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 12 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 44 seconds
(10/14) Running minio-java tests ... done in 19 seconds
(11/14) Running minio-js tests ... FAILED in 13 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-a2b79093-dc3b-43f4-83ba-d002871d93f3, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 1583,
  "status": "FAIL",
  "error": "Error: socket hang up at createHangUpError (_http_client.js:268:15) at Socket.socketOnEnd (_http_client.js:360:23) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```
<a name="ac31e42a-d6ec-4c92-9a06-fc00c6c7d9fe"></a>
### 8299-61f80ee/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32617
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7a09999687da:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 34 seconds
(8/14) Running minio-dotnet tests ... done in 52 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 40 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 3 seconds
(11/14) Running minio-js tests ... done in 56 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 48 seconds
{
  "duration": 117,
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "args": {
    "bucket_name": "minio-py-test-baf8dcee-576b-4dff-a750-2a434b95f6a8",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-28T08-46-23Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C88F35AF0031BC\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Sat, 28 Sep 2019 09:12:10 GMT\"]}}",
    "response.reason": "Forbidden",
    "presigned_get_object_url": "http://72.28.97.58:32617/minio-py-test-baf8dcee-576b-4dff-a750-2a434b95f6a8/2c37933d-90e8-4345-94b1-f7edfdec2e6d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190928%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190928T091203Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=1d43a4b37ca85f7ba79e9a93e754ab7cb9de027d9f954eded9e4ef41d488318a",
    "response.status": 403,
    "object_name": "2c37933d-90e8-4345-94b1-f7edfdec2e6d",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>2c37933d-90e8-4345-94b1-f7edfdec2e6d</Key><BucketName>minio-py-test-baf8dcee-576b-4dff-a750-2a434b95f6a8</BucketName><Resource>/minio-py-test-baf8dcee-576b-4dff-a750-2a434b95f6a8/2c37933d-90e8-4345-94b1-f7edfdec2e6d</Resource><RequestId>15C88F35AF0031BC</RequestId><HostId>ceffd5f5-9260-43a1-b44e-70cbcdfb9cd3</HostId></Error>"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "message": "AccessDenied: message: Access Denied",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
