### PR TITLE
Add randomize sleep times for lock checkers

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add randomize sleep times for lock checkers

## Motivation and Context
Add randomize sleep times for lock checkers

## How to test this PR?
Randomize sleep times to avoid network bursts
at the same intervals

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6b10cf76-8b3d-474c-a5b2-ef32cb39072e) |
| mint-compression-dist-xl.sh | :x: [more...](#2ac60dd9-070a-4353-b39f-cf9ae2d58347) |
| mint-dist-xl.sh | :x: [more...](#81a288f3-3681-4a34-ac9e-23db10044767) |
<a name="2ac60dd9-070a-4353-b39f-cf9ae2d58347"></a>
### 8628-b4d36a1/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32652
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c93243c65e7f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 30 seconds
(8/14) Running minio-dotnet tests ... done in 45 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 23 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 6 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 60374,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3jub53i, objectName=minio-java-test-a0ham3, resource=/minio-java-test-3jub53i/minio-java-test-a0ham3, requestId=15DF1DAE1AAAF18C, hostId=57e6b1d3-e791-449b-9b25-7bd7dee60651)\nrequest={method=PUT, url=http://72.28.97.61:32652/minio-java-test-3jub53i/minio-java-test-a0ham3, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.61:32652\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191210T205028Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191210/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-10T20-25-21Z\nVary: Origin\nX-Amz-Request-Id: 15DF1DAE1AAAF18C\nX-Xss-Protection: 1; mode=block\nDate: Tue, 10 Dec 2019 20:50:28 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="81a288f3-3681-4a34-ac9e-23db10044767"></a>
### 8628-b4d36a1/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32648
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6a1cbe63a576:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 59 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 17 seconds
(10/14) Running minio-java tests ... FAILED in 8 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 1210,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3039sp4, objectName=minio-java-test-3n41otp, resource=/minio-java-test-3039sp4/minio-java-test-3n41otp, requestId=15DF1DAE4CA0FD3A, hostId=9050eb0c-5b4c-4c9a-a257-eddd169c9aef)\nrequest={method=PUT, url=http://72.28.97.52:32648/minio-java-test-3039sp4/minio-java-test-3n41otp, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.52:32648\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191210T205029Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191210/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-10T20-25-21Z\nVary: Origin\nX-Amz-Request-Id: 15DF1DAE4CA0FD3A\nX-Xss-Protection: 1; mode=block\nDate: Tue, 10 Dec 2019 20:50:29 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="6b10cf76-8b3d-474c-a5b2-ef32cb39072e"></a>
### 8628-b4d36a1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31262
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fef040c26222:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 30 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 2 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 16 seconds
{
  "args": {},
  "duration": 93828,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8628-b4d36a1

**Comment by harshavardhana** [comment]
PTAL @BigUstad @kannappanr

**Review by BigUstad — APPROVED** [review]
LGTM. Thanks.

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
