### PR TITLE
Ignore errors reading fs.json

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Ignore errors reading fs.json

## Motivation and Context
Allow fs.json be corrupted, or missing.

## Regression
No

## How Has This Been Tested?
Corrupted and missing

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f8e1f472-b50c-466d-a795-7aeb57208f39) |
| mint-dist-xl.sh | :x: [more...](#10a43575-7822-47f1-ac11-6bd820708536) |
<a name="f8e1f472-b50c-466d-a795-7aeb57208f39"></a>
### 7777-65f6437/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32158
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7ae3246b407f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 13 seconds
{
  "name": "mc",
  "duration": "93660",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-12001 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-23708  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-23708/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-23708/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-23708/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-23708/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-23708/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-23708/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-23708/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-23708/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-23708/datafile-11-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-23708/datafile-10-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-23708/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-23708/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-23708/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-23708/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-23708/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 568.42 MiB, Speed: 6.07 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="10a43575-7822-47f1-ac11-6bd820708536"></a>
### 7777-65f6437/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30977
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8410fa566b00:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 3 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 55 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 15 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 850,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2h022pa, objectName=minio-java-test-13g1in3, resource=/minio-java-test-2h022pa/minio-java-test-13g1in3, requestId=15A789719FFCC98C, hostId=eea46c44-64ec-4ab6-afad-66663dbacdda)\nrequest={method=DELETE, url=http://72.28.97.55:30977/minio-java-test-2h022pa/minio-java-test-13g1in3?uploadId=28612dca-1b10-4657-b1c8-0ca921a37c28, headers=Host: 72.28.97.55:30977\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190612T191517Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190612/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-12T18-55-35Z\nVary: Origin\nX-Amz-Request-Id: 15A789719FFCC98C\nX-Minio-Deployment-Id: eea46c44-64ec-4ab6-afad-66663dbacdda\nX-Xss-Protection: 1; mode=block\nDate: Wed, 12 Jun 2019 19:15:17 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#67b8bca2-3c3d-4e08-9296-b46573ec18b2) |
<a name="67b8bca2-3c3d-4e08-9296-b46573ec18b2"></a>
### 7777-d0915e4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30482
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 007275d7ede4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 0 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... FAILED in 44 seconds
{
  "name": "awscli",
  "duration": 13865,
  "function": "aws --endpoint-url http://72.28.97.51:30482 s3api upload-part --bucket awscli-mint-test-bucket-7872 --key awscli-mint-test-bucket-7872-object --body /mint/data/datafile-10-MB --upload-id 8459cda5-1375-40d8-b428-da61b3f0a551 --part-number 2\n",
  "status": "FAIL",
  "error": ""
}

Executed 4 out of 14 tests successfully.
```

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
