### PR TITLE
Convert context.DeadlineExceed to Offline disk in DiskInfo()

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
When a network DiskInfo() calls exceed a deadline, the state of the disk will be 'unknown'. Convert that to 'offline'.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :x: [more...](#0ab153a5-18a3-4fcc-972e-3019aa5a502c) |
| mint-fs.sh | :x: [more...](#b8deb31a-5614-4d6c-acaf-b3e2168e9366) |
| mint-gateway-s3.sh | :x: [more...](#5309552a-f668-42d5-ae20-f18c45914a8c) |
| mint-erasure.sh | :x: [more...](#2bb274e6-30e5-433f-a3d5-97c385c94be0) |
| mint-dist-erasure.sh | :x: [more...](#47d1a6aa-d774-40a8-b49c-96e229032b76) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#b7237696-d599-4e4c-880d-7de92ceb70e2) |
| mint-pools.sh | :x: [more...](#2673b2fa-7a83-4a3e-81f2-aa9c5ec7ceaa) |
<a name="0ab153a5-18a3-4fcc-972e-3019aa5a502c"></a>
### 15869-98d5bde/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:31978
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 5084c5397849:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... FAILED in 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-annd6cykxnc493on",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "viwqxpdw0pr49w0c0u5q4vcupuxuxr",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2458,
  "error": "want yXTVFQ==, got Ac5tPw==",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 36 seconds
(9/14) Running minio-js tests ... done in 52 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 57 seconds
(11/14) Running s3cmd tests ... done in 18 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 13 out of 14 tests successfully.
```
<a name="47d1a6aa-d774-40a8-b49c-96e229032b76"></a>
### 15869-98d5bde/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.2:30596
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 3996f941972c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... FAILED in 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-ksf1fmxxfomowepj",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "obut2yzn1tmszpda9srqckcr6d2wpa",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2686,
  "error": "want yXTVFQ==, got Ac5tPw==",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 31 seconds
(9/14) Running minio-js tests ... done in 51 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 52 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
<a name="b7237696-d599-4e4c-880d-7de92ceb70e2"></a>
### 15869-98d5bde/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.22:30273
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 06a7e362c05b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... FAILED in 7 seconds
{
  "args": {
    "bucketName": "minio-go-test-xtnenhihlltyw2c5",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "0khvap10utxvpxb5kd91spie2ygzbj",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2165,
  "error": "want yXTVFQ==, got Ac5tPw==",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 32 seconds
(9/14) Running minio-js tests ... done in 51 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 44 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
<a name="5309552a-f668-42d5-ae20-f18c45914a8c"></a>
### 15869-98d5bde/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.23:32553
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 12caa0d51510:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... FAILED in 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-uy1jfb0ptmea0tfw",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "4x1siht1psq9h20nyy2qplbgk3es9b",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 4000,
  "error": "want yXTVFQ==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 38 seconds
(9/14) Running minio-js tests ... done in 37 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 17 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 2 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
<a name="b8deb31a-5614-4d6c-acaf-b3e2168e9366"></a>
### 15869-98d5bde/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.4:30422
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp e343d6b2642d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 12 seconds
(8/14) Running minio-go tests ... FAILED in 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-cxci0oydler00rdq",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "54zv0prcggvbaxz6pno5gboek5hngz",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2563,
  "error": "want yXTVFQ==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 16 seconds
(9/14) Running minio-js tests ... done in 42 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 3 seconds
(11/14) Running s3cmd tests ... done in 13 seconds
(12/14) Running s3select tests ... done in 1 seconds
(13/14) Running versioning tests ... done in 1 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
<a name="2bb274e6-30e5-433f-a3d5-97c385c94be0"></a>
### 15869-98d5bde/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:30294
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 4fc70636899b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... FAILED in 6 seconds
{
  "args": {
    "bucketName": "minio-go-test-4mq9vkbqb1dz1vmi",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "4cq5qk4ycyaj46gyhpa0bvsra222j3",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2899,
  "error": "want yXTVFQ==, got Ac5tPw==",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 17 seconds
(9/14) Running minio-js tests ... done in 46 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 7 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="2673b2fa-7a83-4a3e-81f2-aa9c5ec7ceaa"></a>
### 15869-98d5bde/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.22:31548
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp f9db4ba9b81a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-go tests ... FAILED in 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-bhtstdrw9e3yjvwc",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "jro9s2uplc0grtn9iubrs9i1ox9nb6",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2751,
  "error": "want yXTVFQ==, got Ac5tPw==",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 41 seconds
(9/14) Running minio-js tests ... done in 55 seconds
(10/14) Running minio-py tests ... done in 2 minutes and 4 seconds
(11/14) Running s3cmd tests ... done in 18 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 7 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#b8342c6c-38b3-40d7-a22e-64144cf65875) |
| mint-gateway-s3.sh | :x: [more...](#1086da5b-63fa-49bf-bd3a-816dee0f0303) |
<a name="1086da5b-63fa-49bf-bd3a-816dee0f0303"></a>
### 15869-538f852/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.23:32674
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 23e8e233f5e7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... FAILED in 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-rs2d0i4yz0dpn36m",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "4rc502qc41ybc5ecterkhl0uabj3ga",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 4092,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 38 seconds
(9/14) Running minio-js tests ... done in 37 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 17 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 6 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
<a name="b8342c6c-38b3-40d7-a22e-64144cf65875"></a>
### 15869-538f852/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.4:30782
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp b63d20ec1cf5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 12 seconds
(8/14) Running minio-go tests ... FAILED in 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-jhnanyas3manbdtb",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "21lluryldfvasfez3y52kuajvgwejj",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2689,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 15 seconds
(9/14) Running minio-js tests ... done in 42 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 4 seconds
(11/14) Running s3cmd tests ... done in 12 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
I am reverting this change - there are some sporadic failures with pooled setup with mint.

**Comment by vadmeste** [comment]
> I am reverting this change - there are some sporadic failures with pooled setup with mint.

Are you sure this is still true ? because it is weird but I am also not able to reproduce with latest minio/mint:edge

**Comment by harshavardhana** [comment]
> > I am reverting this change - there are some sporadic failures with pooled setup with mint.
> 
> Are you sure this is still true ? because it is weird but I am also not able to reproduce with latest minio/mint:edge

It is not true you can resend it.

**Pull request merged**
