### PR TITLE
Remove gateway implementations for manta, sia and b2

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Remove gateway implementations for manta, sia and b2

## Motivation and Context
These implementations are no longer maintained.

## Regression
No

## How Has This Been Tested?
```
COMMANDS:
  azure  Microsoft Azure Blob Storage.
  gcs    Google Cloud Storage
  nas    Network-attached storage (NAS)
  oss    Alibaba Cloud (Aliyun) Object Storage Service (OSS)
  s3     Amazon Simple Storage Service (S3)
```
No mention of these gateways anymore

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kannappanr** [comment]
@harshavardhana We should also remove the corresponding vendorized packages.

**Comment by harshavardhana** [comment]
> @harshavardhana We should also remove the corresponding vendorized packages.

oh yes done! @kannappanr

**Review by nitisht — APPROVED** [review]
LGTM & Tested

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by richardkiene** [comment]
Hey @harshavardhana, @nitisht, and @kannappanr,

The Manta Minio gateway is actually still maintained. I work for Joyent and I'm actively working on a fork of minio which adds support for multi-part upload, updates the vendored triton-go library, and fixes a number of bugs. Sorry I didn't see this sooner. Is there any way that we can add that support back? I was in a pretty serious accident and unable to work for a month, which is why it has taken me a while to open a PR.

For reference here is the fork and branch I'm working off of: https://github.com/richardkiene/minio/tree/the_real_mpu

Thanks!

**Comment by harshavardhana** [comment]
> Hey @harshavardhana, @nitisht, and @kannappanr,
> 
> The Manta Minio gateway is actually still maintained. I work for Joyent and I'm actively working on a fork of minio which adds support for multi-part upload, updates the vendored triton-go library, and fixes a number of bugs. Sorry I didn't see this sooner. Is there any way that we can add that support back? I was in a pretty serious accident and unable to work for a month, which is why it has taken me a while to open a PR.
> 
> For reference here is the fork and branch I'm working off of: https://github.com/richardkiene/minio/tree/the_real_mpu
> 
> Thanks!

@richardkiene feel free to send a PR to add it back or if necessary simply keep a fork.

**Comment by Smithx10** [comment]
@harshavardhana   Was a new PR ever put in?  I've just deployed @richardkiene 's branch and it seems to be working well.  I'd love to not have to compile all of this from source and have it in the main code base.

**Comment by harshavardhana** [comment]
@Smithx10 we never saw any PR come in from @richardkiene . If the Manta gateway can be maintained fully we will be happy to take it into the main codebase.

**Comment by Smithx10** [comment]
@harshavardhana  Thats great news,  I've reached out to Joyent Support to hopefully get some traction on this.  Thanks for the cool tooling!!

**Pull request merged**
