### PR TITLE
madmin: Add SetTimeout API for admin http requests

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Add new SetTimeout API

## Motivation and Context
We didn't have this API before, though we need it to configure a http request timeout 

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
why this type of an API? @vadmeste what is useful is SetCustomTransport which is already there.. Can you elaborate on the use case for this?

**Comment by vadmeste** [comment]
> why this type of an API? @vadmeste what is useful is SetCustomTransport which is already there.. Can you elaborate on the use case for this?

As I found, Transport doesn't help to set real timeout (there is only Idle timeout and Header timeout), http.Client's timeout is more generic and covers more cases.

**Comment by harshavardhana** [comment]
> As I found, Transport doesn't help to set real timeout (there is only Idle timeout and Header timeout), http.Client's timeout is more generic and covers more cases.

But why do we need any other timeout other than idle or header? i am not sure we need other timeouts.

**Comment by vadmeste** [comment]
For now, the user can set timeout for header response which is enough to cover most of real world cases, closing this PR.

**Pull request closed without merging**
