### PR TITLE
fix: convert storage class into azure tiers

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: convert storage class into azure tiers

## Motivation and Context
we have now storage class tests which needs
to pass on azure gateway

## How to test this PR?
add tests to ensure that our tests pass on azure gateway

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#0654ec1a-4193-4d96-9479-0789fe5402c3) |
| mint-gateway-nas.sh | :x: [more...](#b38174ee-ef43-4205-9a74-2672790b3eb1) |
<a name="0654ec1a-4193-4d96-9479-0789fe5402c3"></a>
### 9381-caca376/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32507
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 17ab5976ccdc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5e996c5a9b7a0",
    "Object": "obj1"
  },
  "duration": "907",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://minio-dev4.minio.io:32507/aws-sdk-php-5e996c5a9b7a0/obj1-copy-0\"; AWS HTTP error: Client error: `PUT http://minio-dev4.minio.io:32507/aws-sdk-php-5e996c5a9b7a0/obj1-copy-0` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.< (truncated...)\n InvalidBucketName (client): The specified bucket is not valid. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5e996c5a9b7a0</BucketName><Resource>/aws-sdk-php-5e996c5a9b7a0/obj1-copy-0</Resource><RequestId>16068EE97242725C</RequestId><HostId>0d61c2cc-6dd9-4098-8806-0aca19c8612d</HostId></Error>"
}

Executed 2 out of 15 tests successfully.
```
<a name="b38174ee-ef43-4205-9a74-2672790b3eb1"></a>
### 9381-caca376/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32260
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d3a990269c1f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 9 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 23 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... FAILED in 38 seconds
{}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#d1c393d1-5a46-4cf6-b8ae-cbb4a4dc4d5b) |
| mint-gateway-nas.sh | :x: [more...](#3b459aa7-b262-4c4b-9fe5-cf94e0b0bf7c) |
<a name="3b459aa7-b262-4c4b-9fe5-cf94e0b0bf7c"></a>
### 9381-510d109/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31920
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ae548b65ac20:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 7 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 11 seconds
(8/15) Running minio-dotnet tests ... done in 27 seconds
(9/15) Running minio-go tests ... FAILED in 11 seconds
{}

Executed 8 out of 15 tests successfully.
```
<a name="d1c393d1-5a46-4cf6-b8ae-cbb4a4dc4d5b"></a>
### 9381-510d109/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32571
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a4e9b5d2765:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5e99f38d462d5",
    "Object": "obj1"
  },
  "duration": "784",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://minio-dev6.minio.io:32571/aws-sdk-php-5e99f38d462d5/obj1-copy-0\"; AWS HTTP error: Client error: `PUT http://minio-dev6.minio.io:32571/aws-sdk-php-5e99f38d462d5/obj1-copy-0` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.< (truncated...)\n InvalidBucketName (client): The specified bucket is not valid. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5e99f38d462d5</BucketName><Resource>/aws-sdk-php-5e99f38d462d5/obj1-copy-0</Resource><RequestId>1606AE63E4593F15</RequestId><HostId>1abac19d-6596-434d-a96e-f325b4c97b7a</HostId></Error>"
}

Executed 2 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#6ddedf7c-d053-4eb5-80b1-cbe2e00958ad) |
| mint-gateway-nas.sh | :x: [more...](#0fff993b-ebdc-42d7-8bb2-39fb904d96d4) |
<a name="6ddedf7c-d053-4eb5-80b1-cbe2e00958ad"></a>
### 9381-3a9ad68/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30794
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fe5fb669fbe5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5e9a5870a6730",
    "Object": "obj1"
  },
  "duration": "800",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://minio-dev4.minio.io:30794/aws-sdk-php-5e9a5870a6730/obj1-copy-0\"; AWS HTTP error: Client error: `PUT http://minio-dev4.minio.io:30794/aws-sdk-php-5e9a5870a6730/obj1-copy-0` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.< (truncated...)\n InvalidBucketName (client): The specified bucket is not valid. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5e9a5870a6730</BucketName><Resource>/aws-sdk-php-5e9a5870a6730/obj1-copy-0</Resource><RequestId>1606C5E148AD72F2</RequestId><HostId>96e68cb9-53f9-4c4b-a601-c686081c2db5</HostId></Error>"
}

Executed 2 out of 15 tests successfully.
```
<a name="0fff993b-ebdc-42d7-8bb2-39fb904d96d4"></a>
### 9381-3a9ad68/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:30422
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 623d36bdbda0:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 34 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 39 seconds
{}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ef1cc434-9854-4d81-b219-e0691884f054) |
| mint-gateway-azure.sh | :x: [more...](#c22f58ff-ef50-4b67-8163-16a2c18f9cc6) |
| mint-gateway-nas.sh | :x: [more...](#c46cf896-a920-467a-9c25-dab6c181ae5c) |
<a name="c46cf896-a920-467a-9c25-dab6c181ae5c"></a>
### 9381-7826f2d/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31392
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3d5970249361:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 18 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... FAILED in 19 seconds
{}

Executed 8 out of 15 tests successfully.
```
<a name="ef1cc434-9854-4d81-b219-e0691884f054"></a>
### 9381-7826f2d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32586
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d7d231c4ecd4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-so33mfyr5mnub2",
    "objectName": "oqt1iruh29depvdzjnmwitnwqcw3gv"
  },
  "duration": 577,
  "error": "RequestError: send request failed\ncaused by: Put http://minio-c3.minio.io:32586/aws-sdk-go-test-so33mfyr5mnub2/oqt1iruh29depvdzjnmwitnwqcw3gv?tagging=: EOF",
  "function": "testObjectTagging",
  "message": "AWS SDK Go PUTObjectTagging expected to success but got RequestError",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 15 tests successfully.
```
<a name="c22f58ff-ef50-4b67-8163-16a2c18f9cc6"></a>
### 9381-7826f2d/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32202
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c432be8366e6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 5 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... FAILED in 52 seconds
{
  "name": "awscli",
  "duration": 4656,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:32202 s3api head-object --bucket awscli-mint-test-bucket-20603 --key datafile-1-kB-copy\n",
  "status": "FAIL",
  "error": "StorageClass was not applied"
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#e3b13d69-8ac5-425e-951d-5dd28fcba667) |
| mint-gateway-nas.sh | :x: [more...](#9d3f52bd-3b57-48c4-8872-b8f4963813ab) |
<a name="e3b13d69-8ac5-425e-951d-5dd28fcba667"></a>
### 9381-630fa85/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31949
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 37c415c34315:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 6 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... FAILED in 54 seconds
{
  "name": "awscli",
  "duration": 4821,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31949 s3api head-object --bucket awscli-mint-test-bucket-1536 --key datafile-1-kB-copy\n",
  "status": "FAIL",
  "error": "StorageClass was not applied"
}

Executed 4 out of 15 tests successfully.
```
<a name="9d3f52bd-3b57-48c4-8872-b8f4963813ab"></a>
### 9381-630fa85/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:30341
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 59ec2ee9b248:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 31 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... FAILED in 54 seconds
{}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Fixed our storage account used in CI/CD doesn't support Tier's and it requires a premium account that we do not have. So right now we reply back `NotImplemented` which is ignored in the tests.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#7452122a-84d7-4677-b247-0dc622d00d70) |
| mint-gateway-nas.sh | :x: [more...](#ace647a0-7556-4299-b156-f54cc93c6f6d) |
<a name="ace647a0-7556-4299-b156-f54cc93c6f6d"></a>
### 9381-bae7e96/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31923
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 63818dc6c2cd:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 27 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... FAILED in 31 seconds
{}

Executed 8 out of 15 tests successfully.
```
<a name="7452122a-84d7-4677-b247-0dc622d00d70"></a>
### 9381-bae7e96/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32336
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7e052b1edc5f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 5 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... FAILED in 52 seconds
{
  "name": "awscli",
  "duration": 4041,
  "function": "aws --endpoint-url http://minio-dev3.minio.io:32336 s3api copy-object --bucket awscli-mint-test-bucket-10706 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-10706/datafile-1-kB\n",
  "status": "FAIL",
  "error": ""
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#c8e49abc-d658-4378-8dfb-764e7e1ad7f6) |
| mint-gateway-nas.sh | :x: [more...](#9b30bdde-e57f-4799-aae3-bdbf65ddccfc) |
<a name="c8e49abc-d658-4378-8dfb-764e7e1ad7f6"></a>
### 9381-d2849c9/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:31138
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5ff4726dc6b6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... FAILED in 55 seconds
{
  "name": "awscli",
  "duration": 3999,
  "function": "aws --endpoint-url http://minio-c4.minio.io:31138 s3api copy-object --bucket awscli-mint-test-bucket-15067 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-15067/datafile-1-kB\n",
  "status": "FAIL",
  "error": ""
}

Executed 4 out of 15 tests successfully.
```
<a name="9b30bdde-e57f-4799-aae3-bdbf65ddccfc"></a>
### 9381-d2849c9/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:31841
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e9448d4210dc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 7 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 28 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 43 seconds
{}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#ec06b463-8eeb-4e4a-aa80-4df0e432e258) |
| mint-gateway-nas.sh | :x: [more...](#34cd8010-5124-4976-a1c1-cfee60de3d30) |
<a name="ec06b463-8eeb-4e4a-aa80-4df0e432e258"></a>
### 9381-a052b16/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:31309
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e6648cd7f79b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 5 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... FAILED in 54 seconds
{
  "name": "awscli",
  "duration": 4013,
  "function": "aws --endpoint-url http://minio-c4.minio.io:31309 s3api copy-object --bucket awscli-mint-test-bucket-2116 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-2116/datafile-1-kB\n",
  "status": "FAIL",
  "error": ""
}

Executed 4 out of 15 tests successfully.
```
<a name="34cd8010-5124-4976-a1c1-cfee60de3d30"></a>
### 9381-a052b16/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30685
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58f2ed74c148:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 27 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 38 seconds
{}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#11a6380f-4a2c-41e2-91df-2793fe9d6999) |
| mint-gateway-nas.sh | :x: [more...](#b6435857-ad4c-43cf-b63c-c503f0d521f9) |
<a name="11a6380f-4a2c-41e2-91df-2793fe9d6999"></a>
### 9381-9a23a1b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31315
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d2ed40c156f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... FAILED in 54 seconds
{
  "name": "awscli",
  "duration": 4215,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:31315 s3api copy-object --bucket awscli-mint-test-bucket-22488 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-22488/datafile-1-kB\n",
  "status": "FAIL",
  "error": ""
}

Executed 4 out of 15 tests successfully.
```
<a name="b6435857-ad4c-43cf-b63c-c503f0d521f9"></a>
### 9381-9a23a1b/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31492
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1e1a33dab8ff:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 28 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... FAILED in 29 seconds
{}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by Praveenrajmani — APPROVED** [review]

**Pull request merged**
