### PR TITLE
fix: extract array type for policy claim if present

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: extract array type for policy claim if present

## Motivation and Context
Add missing claims extraction to support `arrays` as well.

## How to test this PR?
You need `dex` installed and tested which supports custom claims of `groups` only as arrays.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d984f590-5674-42db-bd08-c2bf30949f10) |
| mint-large-bucket.sh | :x: [more...](#6a86af10-2da4-4844-915c-1a9281785a26) |
| mint-dist-xl.sh | :x: [more...](#b361dc85-a3a5-4492-bf8b-e9c01b2ca5a4) |
| mint-zoned.sh | :x: [more...](#55b29fd4-0768-4766-a1c8-950688d21ac3) |
<a name="6a86af10-2da4-4844-915c-1a9281785a26"></a>
### 10014-59f28da/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31159
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 19373359d577:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 16 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 49 seconds
(4/15) Running aws-sdk-ruby tests ... done in 9 seconds
(5/15) Running awscli tests ... done in 2 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 42 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 29 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 46 seconds
{
  "args": {
    "bucketName": "minio-go-test-211eea9jbh54mvuz",
    "objectName": "bqcplutkiix43kajjj1c9ol093nb4b",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 6594,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 4 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 5 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 8 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 13 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="55b29fd4-0768-4766-a1c8-950688d21ac3"></a>
### 10014-59f28da/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30755
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c726103e4848:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 20 seconds
(2/15) Running aws-sdk-java tests ... done in 4 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... done in 2 minutes and 26 seconds
(6/15) Running healthcheck tests ... done in 2 seconds
(7/15) Running mc tests ... done in 2 minutes and 13 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 17 seconds
(9/15) Running minio-go tests ... FAILED in 3 minutes and 19 seconds
{
  "args": {
    "bucketName": "minio-go-test-6sk5fyk6kkyk909c",
    "objectName": "0z9totp15f0ivolzpe55ym2rpo6kzs",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 7281,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 7 minutes and 10 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 2 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 22 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 9 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="d984f590-5674-42db-bd08-c2bf30949f10"></a>
### 10014-59f28da/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30762
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 506b0901355b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 31 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 51 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 52 seconds
{
  "args": {
    "bucketName": "minio-go-test-hkelm1rcyr1t6z9r",
    "objectName": "aye0uxcd94ov15n2s9jt5i39zhbax9",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3257,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 3 minutes and 1 seconds
(10/15) Running minio-js tests ... done in 58 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 43 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="b361dc85-a3a5-4492-bf8b-e9c01b2ca5a4"></a>
### 10014-59f28da/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30168
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d1f4dbf0011f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 16 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 49 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 2 minutes and 36 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 55 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 6 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 36 seconds
{
  "args": {
    "bucketName": "minio-go-test-haxarzk2afcmc4hy",
    "objectName": "01wmzdgchooj9wexwat40i6xw2tx1g",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5856,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 49 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 2 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 18 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 22 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by poornas — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by dnoelb** [comment]
Is it possible in the same way to use the jwt:groups array as a condition in a policy like this: "Condition": {"StringLike": {"s3:prefix" : "${jwt:groups}"}}. I could not get it to work and i am not sure if it is possible right now or if i should open a feature request for it..

**Pull request merged**
