### PR TITLE
Increase context timeout for bandwidth throttled reader

### LINKED ISSUE #12812: Replication doesn't complete for big files
When upload big file ~13GB replication does not completes and multipart folder grows until takes all disk space (up to five times size of a size of the file)

When upload smaller files (750Mb , 2.5GB ) replication works as expected without any issue.

## Expected Behavior

I expect file to be replicated with the same size as on master node

## Current Behavior

/mnt/minio/data0/.minio.sys/multipart on a replica node grows in size until the free disk space is finished. Replication in a Pending status

## Possible Solution
none

## Steps to Reproduce (for bugs)

1. Upload big file to master node
2. Watch the size of the folders on a replica
3.
4.

## Your Environment

* Version used (`minio --version`): "RELEASE.2021-07-22T05-23-32Z"
* Server setup and configuration: 
Two nodes . Five disks on each node

  /mnt/minio/data0
 /mnt/minio/data1
 /mnt/minio/data2
 /mnt/minio/data3
 /mnt/minio/data4

erasure coding
* Operating System and version (`uname -a`):
centos 8

### PR DESCRIPTION
**Pull request by poornas**
Fixes #12812

## Motivation and Context
Current timeout was at 10 minutes, increasing to an hour 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Lint failures 

```
golang.org/x/tools/cmd/stringer
Running lint check
internal/bucket/bandwidth/monitor.go:183:1: exported: exported method Monitor.IsThrottled should have comment or be unexported (revive)
func (m *Monitor) IsThrottled(bucket string) bool {
	m.tlock.RLock()
	defer m.tlock.RUnlock()
	_, ok := m.bucketThrottle[bucket]
	return ok
}
make: *** [Makefile:35: lint] Error 1
Error: Process completed with exit code 2.
```

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :x: [more...](#db476e9b-496b-4d67-b8af-6e71cb54f0a1) |
<a name="db476e9b-496b-4d67-b8af-6e71cb54f0a1"></a>
### 12820-7f6422e/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:32543
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 2 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 46 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 2 minutes and 2 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 26 seconds
(8/16) Running minio-dotnet tests ... done in 55 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 29 seconds
(10/16) Running minio-java tests ... FAILED in 6 minutes and 25 seconds
(10/16) Running minio-js tests ... done in 51 seconds
(11/16) Running minio-py tests ... done in 2 minutes and 14 seconds
(12/16) Running s3cmd tests ... done in 25 seconds
(13/16) Running s3select tests ... done in 6 seconds
(14/16) Running security tests ... done in 0 seconds
(15/16) Running versioning tests ... done in 3 minutes and 7 seconds

Executed 15 out of 16 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Pull request merged**
