### PR TITLE
root user is now part of IAM allowing it to be disabled

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
root user is now part of IAM allowing it to be disabled

## Motivation and Context
root user exists now as a special user that does not
carry any policy associated with it, however allows
it to be disabled via another admin.
    
This admin can also enable root if needed in the future,
this allows for completely disabled root credentials.

## How to test this PR?
```
minio server ~/test

mc alias set myminio/ http://localhost:9000 minioadmin minioadmin
mc admin user add myminio/ testuser testuser123

mc admin policy attach myminio/ consoleAdmin --user=testuser

mc alias set testuser-adm/ http://localhost:9000 testuser testuser123
mc admin user disable testuser-adm/ minioadmin

mc ls myminio/
mc: <ERROR> Unable to list folder. Your account is disabled; please contact your administrator.
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :x: [more...](#b3f294e1-7329-4634-b98b-2bc890a24391) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#2c96f7c0-48f1-4c34-9e87-199dd43b012c) |
| mint-pools.sh | :x: [more...](#48e3a5dc-c23c-4991-b578-b22ab44b2c7c) |
<a name="b3f294e1-7329-4634-b98b-2bc890a24391"></a>
### 16806-3ad8d85/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:31964
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp d18c0f6cf280:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 23 seconds
{
  "name": "mc",
  "duration": "11092",
  "function": "test_find",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-13359 --quiet --no-color rb --force myminio/mc-test-bucket-18131  >>> \nmc: <ERROR> Unable to validate target `myminio/mc-test-bucket-18131`. Get \"http://15.15.15.7:31964/mc-test-bucket-18131/?location=\": dial tcp 15.15.15.7:31964: i/o timeout"
}
(7/14) Running minio-go tests ... done in 1 minutes and 3 seconds
(8/14) Running minio-java tests ... done in 18 seconds
(9/14) Running minio-js tests ... done in 46 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 25 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 25 seconds

Executed 13 out of 14 tests successfully.
```
<a name="48e3a5dc-c23c-4991-b578-b22ab44b2c7c"></a>
### 16806-3ad8d85/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:31052
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 16c265451539:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 9 seconds
(5/14) Running awscli tests ... done in 1 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 16 seconds
{
  "name": "mc",
  "duration": "10327",
  "function": "test_get_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-10939 --quiet --no-color cp myminio/mc-test-bucket-6519/mc-test-object-28235 mc-test-object-28235.downloaded  >>> \nmc: <ERROR> Unable to validate source `myminio/mc-test-bucket-6519/mc-test-object-28235`."
}
(7/14) Running minio-go tests ... done in 1 minutes and 31 seconds
(8/14) Running minio-java tests ... done in 37 seconds
(9/14) Running minio-js tests ... done in 52 seconds
(10/14) Running minio-py tests ... done in 4 minutes and 13 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 19 seconds

Executed 13 out of 14 tests successfully.
```
<a name="2c96f7c0-48f1-4c34-9e87-199dd43b012c"></a>
### 16806-3ad8d85/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:31945
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 21394b36ef4a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 9 seconds
(5/14) Running awscli tests ... done in 1 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 2 seconds
{
  "name": "mc",
  "duration": "53213",
  "function": "test_presigned_put_object",
  "status": "FAIL",
  "error": "unable to upload /mint/data/datafile-1-MB presigned put object url"
}
(7/14) Running minio-go tests ... done in 54 seconds
(8/14) Running minio-java tests ... done in 29 seconds
(9/14) Running minio-js tests ... done in 49 seconds
(10/14) Running minio-py tests ... done in 3 minutes and 55 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 18 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :x: [more...](#d4cf1877-414a-4b51-8b1a-8fa9b3468c34) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#47967321-14d0-4188-a03c-96728b2e0c26) |
| mint-pools.sh | :x: [more...](#f712c01a-69b0-4760-b1b4-f9104a2611a0) |
<a name="47967321-14d0-4188-a03c-96728b2e0c26"></a>
### 16806-9972715/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:30136
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 2017d96de1fc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 10 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 49 seconds
(9/14) Running minio-java tests ... done in 29 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 49 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 64295,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(10/14) Running minio-py tests ... done in 2 minutes and 7 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 31 seconds

Executed 13 out of 14 tests successfully.
```
<a name="f712c01a-69b0-4760-b1b4-f9104a2611a0"></a>
### 16806-9972715/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:32563
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp c0d3763def70:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 10 seconds
(5/14) Running awscli tests ... done in 1 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-go tests ... done in 59 seconds
(9/14) Running minio-java tests ... done in 38 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 20 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-b85250a4-55c7-4464-8dae-8480e4bd8be9, events: s3:ObjectCreated:*",
  "duration": 36794,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 2 minutes and 17 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 32 seconds

Executed 13 out of 14 tests successfully.
```
<a name="d4cf1877-414a-4b51-8b1a-8fa9b3468c34"></a>
### 16806-9972715/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:30759
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 2ee4a1bc1cd0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 34 seconds
(9/14) Running minio-java tests ... done in 18 seconds
(10/14) Running minio-js tests ... done in 46 seconds
(11/14) Running minio-py tests ... FAILED in 1 minutes and 16 seconds
{
  "name": "minio-py:test_stat_object",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-e76cdec3-f10a-44b3-a648-a27b567912ea",
    "object_name": "c24b43cb-53c0-4c00-aebd-8532ecc64a86-metadata",
    "length": 11534336,
    "data": "LimitedRandomReader(11 * MB)",
    "metadata": {
      "X-Amz-Meta-Testing": "value"
    },
    "content_type": "application/octet-stream"
  },
  "message": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 820, in test_stat_object\n    _test_stat_object(log_entry, sse)\n  File \"/mint/run/core/minio-py/tests.py\", line 794, in _test_stat_object\n    result = _CLIENT.put_object(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1766, in put_object\n    raise exc\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1725, in put_object\n    upload_id = self._create_multipart_upload(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1565, in _create_multipart_upload\n    response = self._execute(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 403, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 266, in _url_open\n    response = self._http.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n",
  "duration": 60443
}
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
@ravindk89 ^^ upcoming feature.

**Review by vadmeste — CHANGES_REQUESTED** [review]
Setting root admin as disabled does not seem to be persisted as per my testing. I think it is okay to have a special object in the disks when disabling the root credentials and instead of the env variable, the user can remove that object manually frmo the disks

**Comment by ravindk89** [comment]
Thanks for the heads-up - one question. Should we not add an `admin:DisableRootAccess` or similar permission to help gate this feature? Otherwise any user w/ user management perms could disable root. I guess this is still an issue as `consoleAdmin` policy will do `admin:*` but it's still some level of gate.

**Comment by harshavardhana** [comment]
> Setting root admin as disabled does not seem to be persisted as per my testing. I think it is okay to have a special object in the disks when disabling the root credentials and instead of the env variable, the user can remove that object manually frmo the disks

It is persisted @vadmeste can you show me how you tested it?

**Comment by harshavardhana** [comment]
> Thanks for the heads-up - one question. Should we not add an `admin:DisableRootAccess` or similar permission to help gate this feature? Otherwise any user w/ user management perms could disable root. I guess this is still an issue as `consoleAdmin` policy will do `admin:*` but it's still some level of gate.

Only user with admin permissions can disable it @ravindk89 we don't need additional perms for this.

It is expected that an admin can disable other admins, root is nothing special.

**Comment by vadmeste** [comment]
> It is persisted @vadmeste can you show me how you tested it?

Just restart the cluster @harshavardhana

**Comment by harshavardhana** [comment]
> > It is persisted @vadmeste can you show me how you tested it?
> 
> Just restart the cluster @harshavardhana

I did @vadmeste it seems to be persisted, are you sure that you are testing this PR?

**Comment by harshavardhana** [comment]
PTAL @donatello @vadmeste @krisis @poornas

**Comment by poornas** [comment]
with site replicated setup, this could easily lead to a state where admin user of peer site can disable the admin of the first site, e.g.
```
 mc admin user add sitea testuser testuser123
 mc admin user add siteb testuserb testuser123

 mc alias set testuser-adm/ http://localhost:9002 testuser testuser123

 mc alias set testuser-admb/ http://localhost:9004 testuserb testuser123

 mc admin policy attach sitea consoleAdmin --user=testuser
 mc admin policy attach siteb consoleAdmin --user=testuserb

 mc admin replicate add testuser-adm testuser-admb

 mc admin user disable testuser-adm/ minio
 mc admin user disable testuser-admb/ testuser
```
Now no admin privileges for any user in sitea after site replication syncs above. Also re-enabling `testuser` on siteb has no effect on sitea since all admin API operations will be rejected. Perhaps, site replication should never replicate admin users, which was easier earlier with root user and derived service accounts not replicating.

**Comment by harshavardhana** [comment]
> with site replicated setup, this could easily lead to a state where admin user of peer site can disable the admin of the first site, e.g.
> 
> ```
>  mc admin user add sitea testuser testuser123
>  mc admin user add siteb testuserb testuser123
> 
>  mc alias set testuser-adm/ http://localhost:9002 testuser testuser123
> 
>  mc alias set testuser-admb/ http://localhost:9004 testuserb testuser123
> 
>  mc admin policy attach sitea consoleAdmin --user=testuser
>  mc admin policy attach siteb consoleAdmin --user=testuserb
> 
>  mc admin replicate add testuser-adm testuser-admb
> 
>  mc admin user disable testuser-adm/ minio
>  mc admin user disable testuser-admb/ testuser
> ```
> 
> Now no admin privileges for any user in sitea after site replication syncs above. Also re-enabling `testuser` on siteb has no effect on sitea since all admin API operations will be rejected. Perhaps, site replication should never replicate admin users, which was easier earlier with root user and derived service accounts not replicating.

Yeah this is good find will talk to @abperiasamy about this further on how to simplify it.

**Comment by harshavardhana** [comment]
@poornas this PR is updated to avoid root change propagation so root must be disabled per site.

**Comment by harshavardhana** [comment]
PTAL @donatello @vadmeste @poornas @krisis

**Review by poornas — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
Will be resubmitted with new changes.

**Pull request closed without merging**
