### PR TITLE
browser: Component attr names should not clash with redux state keys.

### PR DESCRIPTION
**Pull request by krishnasrinivas**
fixes #270

## Description

showAbout and showSettings attr values were being over ridden by redux state values.

## Motivation and Context

Fixes https://github.com/minio/miniobrowser/issues/270

## How Has This Been Tested?

manual

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
@krishnasrinivas can we fix the commit message to be 80 column only right now it has exceeded github's UI and wrapped to description. 

As practice we can keep the 80 column limit and rest can go to description/body of the commit.

**Comment by krishnasrinivas** [comment]
@harshavardhana right now the commit message is 74 chars:

```
krishna@escape:~$ wc
browser: Component attr names should not clash with redux state key names.      0      12      74
```

So github UI must be having an even lower limit.

**Comment by harshavardhana** [comment]
> So github UI must be having an even lower limit.

Yes we can keep 60 - i usually try to be 50-60.

**Comment by krishnasrinivas** [comment]
github subject limit is 72:
```
krishna@escape:~$ wc
browser: Component attr names should not clash with redux state key n…      0      12      72
```

I have amended the commit message

**Pull request merged**
