### PR TITLE
Add Vault support for custom CAs directory

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add Vault support for custom CAs directory

## Motivation and Context
Specifying custom CAs to avoid SSL client trust issues

## Regression
No

## How Has This Been Tested?
Setup Vault in accordance with the `doc/kms/` along with public CAs trusted in `certs/CAs` 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aead** [comment]
@harshavardhana IMO CA path should also be a config file option (additionally to ENV. var)
Therefore we should also upgrade config file... See #6523

**Comment by harshavardhana** [comment]
> @harshavardhana IMO CA path should also be a config file option (additionally to ENV. var)
> Therefore we should also upgrade config file... See #6523

Won't be doing config upgrade @aead just made it an ENV only requirement. We are moving away from the migration concept, for now, it's not needed to be saved.

**Review by poornas — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
ping @aead

**Review by aead — APPROVED** [review]

**Pull request merged**
