### PR TITLE
Adding a fix to check for bucket existence before upload

### PR DESCRIPTION
**Pull request by zveinn**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Currently the SFTP server does not prevent file uploads to buckets that do not exist. This PR adds a simple check for bucket existence before accepting the upload.

## BEFORE
image

## AFTER
image

## Types of changes
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
> Currently the SFTP server does not prevent file uploads to buckets that do not exist. This PR adds a simple check for bucket existence before accepting the upload.

It does upload however, an error is returned at the end @zveinn that buckets do not exist. It is better to return those errors back to the sftp client as well. Right now its just returning "failure"

**Comment by zveinn** [comment]
@harshavardhana yes. We want a proper error message, but more importantly I wanted to stop the file from being uploaded if it's not going to be saved in minio. This way we waste less resources.

**Comment by harshavardhana** [comment]
> @harshavardhana yes. We want a proper error message, but more importantly I wanted to stop the file from being uploaded if it's not going to be saved in minio. This way we waste less resources.

yeah that is good @zveinn

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by jiuker — APPROVED** [review]

**Pull request merged**
