### PR TITLE
Fixes a regression with node level bucket heal

### PR DESCRIPTION
**Pull request by shtripat**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
If not a dangling bucket, make sure remove flag is not set for removal.

## Motivation and Context
Issue: https://github.com/minio/minio/issues/18809

## How to test this PR?
Follow the issue: https://github.com/minio/minio/issues/18809
And also test the scenarios listed at https://github.com/minio/minio/pull/18504

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by harshavardhana** [comment]
This is still wrong @shtripat HealBucket() is costly operation with 1000+s of drives.

**Comment by shtripat** [comment]
> This is still wrong @shtripat HealBucket() is costly operation with 1000+s of drives.

oh ok. I thought this way I am avoiding removal of an empty volume which has presence on more than half the disks of pool, as its not a dangling one. Please help me with proper approach.

**Comment by shtripat** [comment]
Closing as https://github.com/minio/minio/pull/18815 sent for the same.

**Comment by harshavardhana** [comment]
> h ok. I thought this way I am avoiding removal of an empty volume which has presence on more than half the disks of pool, as its not a dangling one. Please help me with proper approach.


You can see why it is simple in the PR and how it still solves the expected requirement.

**Pull request closed without merging**
