### PR TITLE
Browser: Make input number types readonly in share objects modal

### PR DESCRIPTION
**Pull request by rushenn**
## Description
Make input number types readonly and allow inputs through only 'steps' in order to prevent invalid entries.

## Motivation and Context
https://github.com/minio/minio/issues/4269

## How Has This Been Tested?
Manually (Localhost)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by poornas — COMMENTED** [review]
Wouldn't allowing manual editing of number types and validating be less cumbersome from user's perspective? Tested current changes locally, and they work.

**Comment by harshavardhana** [comment]
> Wouldn't allowing manual editing of number types and validating be less cumbersome from user's perspective? Tested current changes locally, and they work.

Can you elaborate more with more detailed comment?. are you approving this PR's approach or no?

**Comment by rushenn** [comment]
@poornas Allowing only the spinners (steps) to make inputs prevents invalid numeric entries as well as other string characters without any further validation codes. Since we do not have a proper form validation system at the moment, I think this fix is good to go.

**Review by poornas — APPROVED** [review]
@rushenn, agreed - this is a quick fix around the validation issue, but for the future it would be good to add form validation. Approving current PR - it was tested locally.

**Review by krishnasrinivas — APPROVED** [review]

**Comment by krishnasrinivas** [comment]
> @rushenn, agreed - this is a quick fix around the validation issue, but for the future it would be good to add form validation. Approving current PR - it was tested locally.

:+1:

**Pull request merged**
