### PR TITLE
fix: headobject will not save meta into cache when not found

### LINKED ISSUE #19925: with mincache enabled `HEAD` request returns different `Content-Length` then matching `GET` on a KMS setup
I have enabled server-side encryption on my bucket and uploaded `Audi cabriolet 01.jpg` of 2,971,514 bytes to the `test` bucket. When I try to copy the file using `mc`, then I got the following error: `Input reader closed pre-maturely. Expected '2972986' bytes, but only received '2971514' bytes.`

I ran the `mc` command using the `--debug` flag and noticed that the `HEAD` request returns a different length then the `GET` request. This is the `HEAD` request:
```
HEAD /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 __debug_bin2996553503/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240612/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240612T160723Z
```
`HEAD` response:
```
HTTP/1.1 200 OK
Content-Length: 2972986
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Wed, 12 Jun 2024 16:07:23 GMT
Etag: "efd738945e94f4dbb8588b788b2ea7c1"
Last-Modified: Wed, 12 Jun 2024 15:21:24 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D84D79C009F04A
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```
Then it performs the actual `GET` and that request looks like:
```
GET /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 __debug_bin2996553503/DEVELOPMENT.GOGET
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240612/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240612T160904Z
```
And the response is:
```
HTTP/1.1 200 OK
Content-Length: 2971514
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Wed, 12 Jun 2024 16:09:04 GMT
Etag: "efd738945e94f4dbb8588b788b2ea7c1"
Last-Modified: Wed, 12 Jun 2024 15:21:24 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D84D916E7CC820
X-Amz-Server-Side-Encryption: aws:kms
X-Amz-Server-Side-Encryption-Aws-Kms-Key-Id: arn:aws:kms:tenant-rdk-key
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```
This seems to be a bug in Minio, because both the `HEAD` and `GET` requests should return the same content length. I never have seen this issue without encryption.

### PR DESCRIPTION
**Pull request by jiuker**
fix: headobject will not save meta into cache when not found

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

fix: headobject will not save meta into cache when not found

```shell
mc cp 4mobject minio9000/mytest/object
mc stat minio9000/mytest/object   <----------here save metadata 4mb
mc cp 3mobject minio9000/mytest/object    <------------here can't save
mc cp minio9000/mytest/object object  <------- read as 4mb, but it should be 3mb
mc: <ERROR> Failed to copy `http://:9000/mytest/object`. Input reader closed pre-maturely. Expected `aaaaaaa` bytes, but only received `bbbbbb` bytes.
```

## Types of changes
- [x] Bug fix #19925
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
The main motivation here is that metadata on the cache is not useful, and it was a bit excessive in the current code. 

The caching will populate when both metadata and data are available such as GET and PUT.

**Review by shtripat — APPROVED** [review]
lgtm

**Comment by ramondeklein** [comment]
I have recreated my cluster using KMS and caching enabled (also on the bucket), but I can't reproduce the issue anymore. It should be the same configuration as yesterday, so I'm not sure what has changed. Because I cannot reproduce the issue with an older Minio release, I cannot confirm that this release will fix it.

**Comment by jiuker** [comment]
> I have recreated my cluster using KMS and caching enabled (also on the bucket), but I can't reproduce the issue anymore. It should be the same configuration as yesterday, so I'm not sure what has changed. Because I cannot reproduce the issue with an older Minio release, I cannot confirm that this release will fix it.

I have posted my steps. You can follow them @ramondeklein

**Comment by klauspost** [comment]
@harshavardhana Shouldn't cache just be completely removed from HeadObject?

It seems counterproductive to fetch up to a 1MB data (or whatever the limit is) just to serve Metadata header.

**Comment by harshavardhana** [comment]
> @harshavardhana Shouldn't cache just be completely removed from HeadObject?
> 

HEAD is cached to save on reading xl.meta for metadata such as if-match, if-modified calls. However what was wrong was HEAD updating the cache without data.

> It seems counterproductive to fetch up to a 1MB data (or whatever the limit is) just to serve Metadata header.

This needs fix at mincache not at MinIO.

**Comment by klauspost** [comment]
@harshavardhana So HEAD is saved in a separate cache from GET requests?

Just wondering if it returns data as well, or is everything split on the server.

**Comment by ramondeklein** [comment]
I have been able to reproduce the issue with this PR, so it doesn't seem to be fixed. When I restart the pods using this image it all seems to work fine:
```
mc: <DEBUG> GET /test/?location= HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 mc/DEVELOPMENT.GOGET
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240613/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20240613T114107Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Type: application/xml
Date: Thu, 13 Jun 2024 11:41:07 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D88D86CB930FC3
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Expires: 2025-06-12 09:16:34 +0000 UTC
mc: <DEBUG> Response Time: 5.295233ms

mc: <DEBUG> HEAD /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240613/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240613T114107Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2971514
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Thu, 13 Jun 2024 11:41:07 GMT
Etag: "bf8b56ed8f68b800536335ad4c6fa7e8"
Last-Modified: Thu, 13 Jun 2024 11:37:10 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D88D86CBB15A37
X-Amz-Server-Side-Encryption: aws:kms
X-Amz-Server-Side-Encryption-Aws-Kms-Key-Id: arn:aws:kms:tenant-rdk-key
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Expires: 2025-06-12 09:16:34 +0000 UTC
mc: <DEBUG> Response Time: 3.414829ms

mc: <DEBUG> HEAD /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 mc/DEVELOPMENT.GOGET
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240613/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240613T114107Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2971514
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Thu, 13 Jun 2024 11:41:07 GMT
Etag: "bf8b56ed8f68b800536335ad4c6fa7e8"
Last-Modified: Thu, 13 Jun 2024 11:37:10 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D88D86CBF60060
X-Amz-Server-Side-Encryption: aws:kms
X-Amz-Server-Side-Encryption-Aws-Kms-Key-Id: arn:aws:kms:tenant-rdk-key
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Expires: 2025-06-12 09:16:34 +0000 UTC
mc: <DEBUG> Response Time: 2.936505ms

mc: <DEBUG> GET /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 mc/DEVELOPMENT.GOGET
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240613/us-east-1/s3/aws4_request, SignedHeaders=host;if-match;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
If-Match: "bf8b56ed8f68b800536335ad4c6fa7e8"
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240613T114107Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2971514
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Thu, 13 Jun 2024 11:41:07 GMT
Etag: "bf8b56ed8f68b800536335ad4c6fa7e8"
Last-Modified: Thu, 13 Jun 2024 11:37:10 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D88D86CC3F66D6
X-Amz-Server-Side-Encryption: aws:kms
X-Amz-Server-Side-Encryption-Aws-Kms-Key-Id: arn:aws:kms:tenant-rdk-key
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Expires: 2025-06-12 09:16:34 +0000 UTC
mc: <DEBUG> Response Time: 4.672123ms
```
When I copy the data to the `test` bucket again, then the copy operation succeeds. But fetching the data fails with the following logging:
```
mc: <DEBUG> GET /test/?location= HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 mc/DEVELOPMENT.GOGET
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240613/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20240613T114115Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Type: application/xml
Date: Thu, 13 Jun 2024 11:41:15 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D88D888E65F5DB
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Expires: 2025-06-12 09:16:34 +0000 UTC
mc: <DEBUG> Response Time: 5.764119ms

mc: <DEBUG> HEAD /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240613/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240613T114115Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2972986
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Thu, 13 Jun 2024 11:41:15 GMT
Etag: "cf286d3bb78192dc30574ae716b671a7"
Last-Modified: Thu, 13 Jun 2024 11:41:12 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D88D888E83DED2
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Expires: 2025-06-12 09:16:34 +0000 UTC
mc: <DEBUG> Response Time: 1.841403ms

mc: <DEBUG> HEAD /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 mc/DEVELOPMENT.GOGET
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240613/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240613T114115Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2972986
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Thu, 13 Jun 2024 11:41:15 GMT
Etag: "cf286d3bb78192dc30574ae716b671a7"
Last-Modified: Thu, 13 Jun 2024 11:41:12 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D88D888EAFA7B8
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Expires: 2025-06-12 09:16:34 +0000 UTC
mc: <DEBUG> Response Time: 1.460432ms

mc: <DEBUG> GET /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 mc/DEVELOPMENT.GOGET
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240613/us-east-1/s3/aws4_request, SignedHeaders=host;if-match;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
If-Match: "cf286d3bb78192dc30574ae716b671a7"
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240613T114115Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2971514
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Thu, 13 Jun 2024 11:41:15 GMT
Etag: "cf286d3bb78192dc30574ae716b671a7"
Last-Modified: Thu, 13 Jun 2024 11:41:12 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D88D888EE0966D
X-Amz-Server-Side-Encryption: aws:kms
X-Amz-Server-Side-Encryption-Aws-Kms-Key-Id: arn:aws:kms:tenant-rdk-key
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Expires: 2025-06-12 09:16:34 +0000 UTC
mc: <DEBUG> Response Time: 14.091496ms

mc: <ERROR> Failed to copy `https://tenant-rdk-hl.tenant-rdk:9000/test/audi/Audi cabriolet 01.jpg`. Input reader closed pre-maturely. Expected `2972986` bytes, but only received `2971514` bytes.
 (3) cp-main.go:478 cmd.doCopySession(..) Tags: [https://tenant-rdk-hl.tenant-rdk:9000/test/audi/Audi cabriolet 01.jpg]
 (2) common-methods.go:508 cmd.uploadSourceToTargetURL(..) Tags: [https://tenant-rdk-hl.tenant-rdk:9000/test/audi/Audi cabriolet 01.jpg]
 (1) common-methods.go:212 cmd.putTargetStream(..) Tags: [, /mnt/c/temp/Audi cabriolet 01.jpg]
 (0) client-fs.go:355 cmd.(*fsClient).put(..)
 Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:RDK-PREC7560 | OS:linux | Arch:amd64 | Lang:go1.22.3 | Mem:5.7 MiB/18 MiB | Heap:5.7 MiB/11 MiB
```
After a restart of the pods, everything works again. I can copy the files multiple times to my local disk without any issues. Only when I copy the files from my local disk to the bucket again, then it starts to fail. I double-checked, but I build my Docker image using branch `jiuker:fix-headobject-will-not-save-meta-into-cache-when-not-found` and my `/usr/bin/minio` file is only a few minutes old, so I'm pretty confident that I'm using the proper image.

**Comment by ramondeklein** [comment]
I think there might be a problem that `mincache` updates its local cache during the `PutObject` operation. To test if `mincache` is the issue, I did the following:
1. Copy the files to the bucket and fetch one of the files. This failed with the issue that it couldn't read enough data.
2. Shell into the `mincache` side-containers of both pods and issue `kill 1` to kill the `mincache`.
3. Wait until both pods spinned up a `mincache` side-container again.
4. Fetch one of the files and this now works.

> This needs fix at mincache not at MinIO.

@harshavardhana I guess my test indicates the same.

**Comment by ramondeklein** [comment]
Steps to reproduce:
1. Spin up a Minio container that uses server-side encryption.
2. Create a bucket named `test` and enable SSE on the bucket.
3. Ensure that `mincache` is used and make sure `mincache` also caches the `test` bucket.
4. Copy a file to the `test` bucket using `mc`.
5. Copy the file from the `test` bucket using `mc`.

After restarting `mincache` copying the file works fine, until it's written again.

**Comment by harshavardhana** [comment]
This PR is an independent fix where it avoids discrepancy on HEAD, so not really fixing the original issue.

**Review by harshavardhana — APPROVED** [review]

**Comment by jiuker** [comment]
> Steps to reproduce:
> 
> 1. Spin up a Minio container that uses server-side encryption.
> 2. Create a bucket named `test` and enable SSE on the bucket.
> 3. Ensure that `mincache` is used and make sure `mincache` also caches the `test` bucket.
> 4. Copy a file to the `test` bucket using `mc`.
> 5. Copy the file from the `test` bucket using `mc`.
> 
> After restarting `mincache` copying the file works fine, until it's written again.

```shell
root@DESKTOP-QPDA04R:/mnt/c/workspace/go/src/minkms/dist# mc cp shell.sh minio9000/mytest/shell.sh
mc stat minio9000/mytest/shell.sh
mc cp minio9000/mytest/shell.sh shell.sh
.../src/minkms/dist/shell.sh: 307 B / 307 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 3.65 KiB/s 0sName      : shell.sh
Date      : 2024-06-14 09:29:50 CST
Size      : 307 B
ETag      : 37ac95accdbcf49bab25e5e1da3bf1e6
Type      : file
Encryption: SSE-KMS (arn:aws:kms:default-key)
Metadata  :
  Content-Type: application/x-sh

....2.6:9000/mytest/shell.sh: 307 B / 307 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 3.83 KiB/s 0sroot@DESKTOP-QPDA04R:/mnt/c/workspace/go/src/minkms/dist#

```

**Pull request merged**
