### PR TITLE
Add a snapcraft build badge.

### PR DESCRIPTION
**Pull request by evandandrea**
Congrats on the snap! This branch adds a badge for the latest build status.

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
LGTM but this is blocked until we merge #4806

**Comment by harshavardhana** [comment]
Would you mind rebasing the PR the latest commit @evandandrea ? - Thanks.

**Review by harshavardhana — APPROVED** [review]

**Comment by evandandrea** [comment]
Hi! Can we land this now that #4806 has landed?

**Review by krishnasrinivas — APPROVED** [review]

**Comment by deekoder** [comment]
done and thank you @evandandrea

**Pull request merged**
