### PR TITLE
Do not cleanup range files in SaveMetadata if incHitsOnly is false

### PR DESCRIPTION
**Pull request by kaloyan-raev**
## Description

`diskCache.SaveMetadata` takes an `HTTPRangeSpec` param. Some calls to this method pass `nil` instead of the HTTPRangeSpec that the callers have in hand. In such a case, the SaveMetadata method cleans up existing range files.

This change makes sure that the SaveMetadata method won't cleanup range files if `incHitsOnly` is `false`.

## Motivation and Context

While testing the caching of large files in our gateway backend implementation, we found that the `cacheObjects.updateMetadataIfChanged` method has a case where it passes `nil` as the HTTPRangeSpec to SaveMetadata.

This erroneously causes the `diskCache.saveMetadata` method to assume it is saving the metadata for an entire object, thus deleting all cached ranges:
https://github.com/minio/minio/blob/5cc23ae0526d28874f25b100c1477b476ec39e26/cmd/disk-cache-backend.go#L544
As a result, some of the cached ranges are lost for larger files, making the cache inefficient.

## How to test this PR?

Use AWS CLI to download a larger file (tens or hundreds of MB) several times. Watch if the cache works as expected.

Cache settings:
```
MINIO_CACHE=on
MINIO_CACHE_DRIVES=/var/cache/storj
MINIO_CACHE_EXPIRY=180
MINIO_CACHE_QUOTA=80
MINIO_CACHE_WATERMARK_LOW=80
MINIO_CACHE_WATERMARK_HIGH=95
MINIO_CACHE_AFTER=0
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#f9a41b77-3f87-4aaa-ab33-7098cc40fa13) |
<a name="f9a41b77-3f87-4aaa-ab33-7098cc40fa13"></a>
### 10728-b348dc0/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30498
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f23045526e43:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 11 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 40 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 52 seconds
{
  "args": {
    "bucketName": "minio-go-test-b09q5it1wdbsoal3",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1087,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 11 minutes and 2 seconds
(10/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 58 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 19 seconds
(12/15) Running s3select tests ... done in 39 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by poornas** [comment]
@kaloyan-raev , range requests are filled in the cache by [putRange](https://github.com/minio/minio/blob/master/cmd/disk-cache-backend.go#L727) - you may see nil *HttpRangeSpec passed wherever it is not a GET request with range specified. 

This PR will essentially not solve the issue you are facing. As mentioned in the other PR, please provide additional info on your cache settings to root cause better.

**Comment by kaloyan-raev** [comment]
@poornas I added my cache setting to the PR description, in the section for testing.

You are right that the cache is filled by in `putCache`, but this is not the only place where an update to the cache metadata is triggered.

Below is the stack trace of the gourtine that is causing the issue for us:

```
goroutine 118 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa1
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/minio/minio/cmd.removeAll(0xc0006f01c0, 0x70, 0x0, 0x0)
	/home/kaloyan/git/minio/cmd/os-reliable.go:30 +0x2e
github.com/minio/minio/cmd.(*diskCache).saveMetadata(0xc000bfa140, 0x2b4e880, 0xc0007407e0, 0xc000771561, 0xb, 0xc00075a080, 0x40, 0xc0002c5050, 0xac9be79, 0x0, ...)
	/home/kaloyan/git/minio/cmd/disk-cache-backend.go:541 +0xaad
github.com/minio/minio/cmd.(*diskCache).SaveMetadata(0xc000bfa140, 0x2b4e880, 0xc0007407e0, 0xc000771561, 0xb, 0xc00075a080, 0x40, 0xc0002c5050, 0xac9be79, 0x0, ...)
	/home/kaloyan/git/minio/cmd/disk-cache-backend.go:506 +0x25f
github.com/minio/minio/cmd.(*cacheObjects).updateMetadataIfChanged(0xc00019a400, 0x2b4e880, 0xc0007407e0, 0xc000bfa140, 0xc000771561, 0xb, 0xc00075a080, 0x40, 0xc000771561, 0xb, ...)
	/home/kaloyan/git/minio/cmd/disk-cache.go:117 +0x6fa
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc00019a400, 0x2b4e880, 0xc0007407e0, 0xc000771561, 0xb, 0xc00075a080, 0x40, 0xc00074a5c0, 0xc000740450, 0x1, ...)
	/home/kaloyan/git/minio/cmd/disk-cache.go:275 +0x185d
github.com/minio/minio/cmd.objectAPIHandlers.GetObjectHandler(0x26cc748, 0x26cc738, 0xc000b683a0, 0xc000b683c0, 0x2b3e3c0, 0xc00074e3c0, 0xc000206900)
	/home/kaloyan/git/minio/cmd/object-handlers.go:407 +0x149b
net/http.HandlerFunc.ServeHTTP(0xc000960330, 0x2b3e3c0, 0xc00074e3c0, 0xc000206900)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x2b3e3c0, 0xc00074e3c0, 0xc000206900)
	/home/kaloyan/git/minio/cmd/handler-utils.go:355 +0x195
net/http.HandlerFunc.ServeHTTP(0xc000b27820, 0x2b3e3c0, 0xc00074e3c0, 0xc000206900)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/minio/minio/cmd.collectAPIStats.func1(0x2b3e3c0, 0xc00074e320, 0xc000206900)
	/home/kaloyan/git/minio/cmd/handler-utils.go:370 +0x156
net/http.HandlerFunc.ServeHTTP(0xc000b32ca0, 0x2b3e3c0, 0xc00074e320, 0xc000206900)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/minio/minio/cmd.maxClients.func1(0x2b3e3c0, 0xc00074e320, 0xc000206900)
	/home/kaloyan/git/minio/cmd/handler-api.go:89 +0x42f
net/http.HandlerFunc.ServeHTTP(0xc000b27840, 0x2b3e3c0, 0xc00074e320, 0xc000206900)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x2b1dda0, 0xc000b27840, 0x2b3e380, 0xc000b6e4c0, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:725 +0x119
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x2b1caa0, 0xc000b74130, 0x2b3e380, 0xc000b6e4c0, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:740 +0xe0
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc000740540, 0x2b1cc00, 0xc000b74140, 0x2b3e380, 0xc000b6e4c0, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:598 +0x120
github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x2b1ca00, 0xc000b6e460, 0x2b3e380, 0xc000b6e4c0, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:582 +0x60d
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x2b1cba0, 0xc000b74160, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:510 +0x1ae
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x2b1cac0, 0xc000b74170, 0x50004000000, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:67 +0xe3
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x2b1cb80, 0xc000b6e480, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:92 +0x1b0
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x2b1cb60, 0xc000b74180, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/crossdomain-xml-handler.go:51 +0x228
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x2b1ca80, 0xc000b74190, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:250 +0x115
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x2b1cb40, 0xc000b741a0, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:318 +0x96
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x2b1cb00, 0xc000b741b0, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:277 +0x24d
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x2b1ca20, 0xc000b741c0, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:388 +0x447
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x2b1cc40, 0xc000b741d0, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:490 +0x3e9
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x2b1cbe0, 0xc000b741e0, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/auth-handler.go:463 +0xa5
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x2b1c9e0, 0xc000b741f0, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:776 +0x2fc
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x2b1cc20, 0xc000b74200, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:138 +0x1b0
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00024ab40, 0x2b43f40, 0xc000760000, 0xc000206900)
	/home/kaloyan/go/pkg/mod/github.com/gorilla/mux@v1.7.5-0.20200711200521-98cb6bf42e08/mux.go:210 +0x1e6
github.com/rs/cors.(*Cors).Handler.func1(0x2b43f40, 0xc000760000, 0xc0006bed00)
	/home/kaloyan/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x35f
net/http.HandlerFunc.ServeHTTP(0xc000b41f80, 0x2b43f40, 0xc000760000, 0xc0006bed00)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x2b1dda0, 0xc000b41f80, 0x2b43f40, 0xc000760000, 0xc0006bed00)
	/home/kaloyan/git/minio/cmd/generic-handlers.go:758 +0xc1
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x2b43f40, 0xc000760000, 0xc0006bed00)
	/home/kaloyan/git/minio/cmd/http/server.go:100 +0x2b9
net/http.HandlerFunc.ServeHTTP(0xc000b54060, 0x2b43f40, 0xc000760000, 0xc0006bed00)
	/usr/local/go/src/net/http/server.go:2012 +0x44
net/http.serverHandler.ServeHTTP(0xc000239440, 0x2b43f40, 0xc000760000, 0xc0006bed00)
	/usr/local/go/src/net/http/server.go:2807 +0x20f
net/http.(*conn).serve(0xc000a308c0, 0x2b4e7c0, 0xc00098df00)
	/usr/local/go/src/net/http/server.go:1895 +0x1716
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x931
```

Is there any legit reason for ignoring the HTTPRangeSpec in the cases touched by this PR?

**Comment by kaloyan-raev** [comment]
@poornas Thanks for approving and merging #10724

The suggested change in https://github.com/minio/minio/compare/master...poornas:fxcache2?expand=1#diff-baf18047d48284503b27c0e3f7e6701cc6a09d5f33a7a0fa747987b4c6dce215R542-R548 also seems to work for us.

Should I update this PR to use that change instead of the one suggested here?

**Comment by poornas** [comment]
> @poornas Thanks for approving and merging #10724
> 
> The suggested change in https://github.com/minio/minio/compare/master...poornas:fxcache2?expand=1#diff-baf18047d48284503b27c0e3f7e6701cc6a09d5f33a7a0fa747987b4c6dce215R542-R548 also seems to work for us.
> 
> Should I update this PR to use that change instead of the one suggested here?

@kaloyan-raev , yes - that would be great.

**Comment by kaloyan-raev** [comment]
@poornas The PR is updated. I updated also the title and the description.

**Review by poornas — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
