### PR TITLE
do not log client canceled events

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
do not log client-canceled events

## Motivation and Context
avoid logging context canceled/timeout errors 
as audit miss events since they are not.

## How to test this PR?
Nothing special a canceled client conn leads

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by vadmeste — COMMENTED** [review]
I really think it is better if we ignore logs from the upper level, I can send a PR for that

**Comment by harshavardhana** [comment]
> I really think it is better if we ignore logs from the upper level, I can send a PR for that

yes but we can't return errors for valid context canceled ones since the audit is invalid as the request didn't complete.

**Comment by harshavardhana** [comment]
PTAL @vadmeste @krisis

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by krisis — APPROVED** [review]

**Pull request merged**
