### PR TITLE
remove the unused code for decrypting `io.Writer`

### PR DESCRIPTION
**Pull request by aead**
## Description
This commit removes unused code for decrypting
`io.Writer` since the actual implementation only
decrypts `io.Reader`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0bcabf95-73a1-451f-99e1-9e5771462a3f) |
| mint-compression-fs.sh | :x: [more...](#a4110941-693e-4492-9f05-3835bdb2db7a) |
<a name="0bcabf95-73a1-451f-99e1-9e5771462a3f"></a>
### 8277-c1ed0a8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30632
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c489422816ac:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 minutes and 3 seconds
(2/14) Running aws-sdk-java tests ... done in 3 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 5 minutes and 7 seconds
{
  "name": "aws-sdk-php",
  "function": "getObject ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5d84022a21d57",
    "Object": "obj1"
  },
  "duration": "27",
  "status": "FAIL",
  "error": "Error executing \"PutObject\" on \"http://72.28.97.58:30632/aws-sdk-php-5d84022a21d57/obj1\"; AWS HTTP error: Client error: `PUT http://72.28.97.58:30632/aws-sdk-php-5d84022a21d57/obj1` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of byte (truncated...)\n IncompleteBody (client): You did not provide the number of bytes specified by the Content-Length HTTP header. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of bytes specified by the Content-Length HTTP header.</Message><Key>obj1</Key><BucketName>aws-sdk-php-5d84022a21d57</BucketName><Resource>/aws-sdk-php-5d84022a21d57/obj1</Resource><RequestId>15C5F7FAAB1B83BC</RequestId><HostId>53d29dff-8a05-450b-bfa2-60eb17fe20b1</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="a4110941-693e-4492-9f05-3835bdb2db7a"></a>
### 8277-c1ed0a8/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31052
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 39fb1fb02c1d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 54 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 51 seconds
(10/14) Running minio-java tests ... done in 52 seconds
(11/14) Running minio-js tests ... done in 45 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 29 seconds
{
  "status": "FAIL",
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "object_name": "707e3d2c-43dd-4dea-b58f-59467063c3ae",
    "bucket_name": "minio-py-test-5d51dbb3-28cb-4de4-9759-fc469e3a4087",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-19T22-15-15Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C5F7E86E25767D\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Thu, 19 Sep 2019 22:37:02 GMT\"]}}",
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>707e3d2c-43dd-4dea-b58f-59467063c3ae</Key><BucketName>minio-py-test-5d51dbb3-28cb-4de4-9759-fc469e3a4087</BucketName><Resource>/minio-py-test-5d51dbb3-28cb-4de4-9759-fc469e3a4087/707e3d2c-43dd-4dea-b58f-59467063c3ae</Resource><RequestId>15C5F7E86E25767D</RequestId><HostId>a70204ce-58d4-4262-843a-b9688e0e8f3d</HostId></Error>",
    "presigned_get_object_url": "http://72.28.97.52:31052/minio-py-test-5d51dbb3-28cb-4de4-9759-fc469e3a4087/707e3d2c-43dd-4dea-b58f-59467063c3ae?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190919%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190919T223657Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=ba9b39f4ce812892d8c6d1e1ab357120f3d9f2680d0df63438b78a1a448320af",
    "response.status": 403
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 49
}

Executed 11 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#db1f43b7-3647-4a44-96ee-db239a67cd17) |
| mint-compression-dist-xl.sh | :x: [more...](#25a97fda-bb24-420b-a50c-3554aa9e9b89) |
<a name="25a97fda-bb24-420b-a50c-3554aa9e9b89"></a>
### 8277-509cdb3/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32269
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 056ac3d1460b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 14 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 15 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 43 seconds
(11/14) Running minio-js tests ... done in 51 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 13 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "status": "FAIL",
  "args": {
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>2bb77a4c-1c9c-416d-b799-b2a91b5a965b</Key><BucketName>minio-py-test-5970fbdd-1269-4f28-9f91-0a71333efd0e</BucketName><Resource>/minio-py-test-5970fbdd-1269-4f28-9f91-0a71333efd0e/2bb77a4c-1c9c-416d-b799-b2a91b5a965b</Resource><RequestId>15C5F98C94B1A364</RequestId><HostId>ffa922ba-3cb3-4884-b6d5-b7e5fca5a0ff</HostId></Error>",
    "presigned_get_object_url": "http://72.28.97.53:32269/minio-py-test-5970fbdd-1269-4f28-9f91-0a71333efd0e/2bb77a4c-1c9c-416d-b799-b2a91b5a965b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190919%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190919T230702Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=bdfff3e166856d45556c40d0d36196cbe82199fad0bbc23fa46b63e4cfb38a8e",
    "object_name": "2bb77a4c-1c9c-416d-b799-b2a91b5a965b",
    "response.reason": "Forbidden",
    "bucket_name": "minio-py-test-5970fbdd-1269-4f28-9f91-0a71333efd0e",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-19T22-42-26Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C5F98C94B1A364\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Thu, 19 Sep 2019 23:07:07 GMT\"]}}",
    "response.status": 403
  },
  "duration": 120,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "name": "minio-py:test_presigned_get_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```
<a name="db1f43b7-3647-4a44-96ee-db239a67cd17"></a>
### 8277-509cdb3/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30465
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp abd364dbc42d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 1 minutes and 33 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 38 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 51 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 59 seconds
{
  "args": {},
  "duration": 87072,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
Build test failure 

```
# github.com/minio/minio/cmd
vet: cmd/encryption-v1_test.go:176:29: undeclared name: SSESealAlgorithmDareSha256
make: *** [vet] Error 2
```

@aead

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#598410ab-2fde-4b89-ab04-0b5848f994de) |
| mint-large-bucket.sh | :x: [more...](#f94673e2-b6fd-4322-9b26-c1b6b204624d) |
<a name="f94673e2-b6fd-4322-9b26-c1b6b204624d"></a>
### 8277-d158f3d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31151
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0ee5182d16b5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 47 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5d8413a2e971e"
  },
  "duration": "40654",
  "status": "FAIL",
  "error": "Error executing \"CreateBucket\" on \"http://72.28.97.52:31151/aws-sdk-php-5d8413a2e971e\"; AWS HTTP error: Client error: `PUT http://72.28.97.52:31151/aws-sdk-php-5d8413a2e971e` resulted in a `409 Conflict` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>BucketAlreadyOwnedByYou</Code><Message>Your previous request to crea (truncated...)\n BucketAlreadyOwnedByYou (client): Your previous request to create the named bucket succeeded and you already own it. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>BucketAlreadyOwnedByYou</Code><Message>Your previous request to create the named bucket succeeded and you already own it.</Message><BucketName>aws-sdk-php-5d8413a2e971e</BucketName><Resource>/aws-sdk-php-5d8413a2e971e</Resource><RequestId>15C5FBCF7A8F9558</RequestId><HostId>47f5b4d5-f64c-4dc0-9d3f-7b05bfdfa26d</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="598410ab-2fde-4b89-ab04-0b5848f994de"></a>
### 8277-d158f3d/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31641
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d6d9dce04d81:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-04uvith2g4xlk0",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 366393,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C5FC190FD82E4C, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f4277c41-7f96-4f40-a0d2-1b33f2f9620d) |
| mint-gateway-nas.sh | :x: [more...](#384e6e3b-092f-41a7-98c1-b3702d031e45) |
<a name="f4277c41-7f96-4f40-a0d2-1b33f2f9620d"></a>
### 8277-ec39f92/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30532
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1c8a2899e375:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 5 minutes and 49 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5d8419c2180f2"
  },
  "duration": "41125",
  "status": "FAIL",
  "error": "Error executing \"PutObject\" on \"http://72.28.97.55:30532/aws-sdk-php-5d8419c2180f2/test-anon\"; AWS HTTP error: Client error: `PUT http://72.28.97.55:30532/aws-sdk-php-5d8419c2180f2/test-anon` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of byte (truncated...)\n IncompleteBody (client): You did not provide the number of bytes specified by the Content-Length HTTP header. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of bytes specified by the Content-Length HTTP header.</Message><Key>test-anon</Key><BucketName>aws-sdk-php-5d8419c2180f2</BucketName><Resource>/aws-sdk-php-5d8419c2180f2/test-anon</Resource><RequestId>15C5FD82B7DCDBC4</RequestId><HostId>6131c4d4-7944-4d44-ba78-c77decac979c</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="384e6e3b-092f-41a7-98c1-b3702d031e45"></a>
### 8277-ec39f92/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30959
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a033b0646bab:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 44 seconds
(8/14) Running minio-dotnet tests ... done in 30 seconds
(9/14) Running minio-go tests ... done in 40 seconds
(10/14) Running minio-java tests ... done in 59 seconds
(11/14) Running minio-js tests ... done in 37 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 28 seconds
{
  "args": {
    "bucket_name": "minio-py-test-1d205b0a-51bd-4c9c-aed3-5813c938e03b",
    "object_name": "8b263a67-f6e1-4cc9-9c6a-7ebc3331654a",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"404\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-20T00-01-00Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C5FDAA4C602836\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 20 Sep 2019 00:22:33 GMT\"]}}",
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>8b263a67-f6e1-4cc9-9c6a-7ebc3331654a</Key><BucketName>minio-py-test-1d205b0a-51bd-4c9c-aed3-5813c938e03b</BucketName><Resource>/minio-py-test-1d205b0a-51bd-4c9c-aed3-5813c938e03b/8b263a67-f6e1-4cc9-9c6a-7ebc3331654a</Resource><RequestId>15C5FDAA4C602836</RequestId><HostId></HostId></Error>",
    "presigned_get_object_url": "http://72.28.97.54:30959/minio-py-test-1d205b0a-51bd-4c9c-aed3-5813c938e03b/8b263a67-f6e1-4cc9-9c6a-7ebc3331654a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190920%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190920T002227Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=dac565980fa8437336cf3f140bca5217544d4b6b5b6931f4b38f44a7d7674645",
    "response.status": 403
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "duration": 53,
  "status": "FAIL",
  "message": "AccessDenied: message: Access Denied",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by harshavardhana — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
