### PR TITLE
admin: new API for creating KMS master keys

### PR DESCRIPTION
**Pull request by aead**
## Description

This commit adds a new admin API for creating master keys.
An admin client can send a POST request to:
```
/minio/admin/v3/kms/key/create?key-id=<keyID>
```

The name / ID of the new key is specified as request
query parameter `key-id=<ID>`.

Creating new master keys requires KES - it does not work with
the native Vault KMS (deprecated) nor with a static master key
(deprecated).

Further, this commit removes the `UpdateKey` method from the `KMS`
interface. This method is not needed and not used anymore.

## Motivation and Context
KMS, KES, SSE-KMS

## How to test this PR?

 - Follow https://github.com/minio/minio/tree/master/docs/kms#quick-start for a MinIO-KMS setup.
 - Checkout minio/mc#3287
 - Add the `replace github.com/minio/minio => <your-minio/minio-dir>` directive to the go.md file
 - Use `mc admin kms key create <alias> <key-ID>`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#9903935e-3daf-442b-abb1-21599c213832) |
| mint-large-bucket.sh | :x: [more...](#8b6ed0ae-e9c6-4fae-851b-28db9ba57473) |
| mint-dist-xl.sh | :x: [more...](#47628a2c-410e-40b4-83ac-8d06ac2c61d9) |
| mint-gateway-azure.sh | :x: [more...](#18febe86-1e80-43ab-a8f4-835157e8c622) |
| mint-zoned.sh | :x: [more...](#0b5f3fb6-192b-42d5-88c3-480374669b6b) |
<a name="9903935e-3daf-442b-abb1-21599c213832"></a>
### 9982-59de1e2/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31886
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dfef9b692bc5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 47 seconds
(8/15) Running minio-dotnet tests ... done in 58 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 11 seconds
{
  "args": {
    "bucketName": "minio-go-test-mf42xxfvwrlxttr0",
    "objectName": "6ofpni2pt3ftjl6fsnloy9gpz9yjhm",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 2859,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 1 minutes and 55 seconds
(10/15) Running minio-js tests ... done in 56 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 23 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="18febe86-1e80-43ab-a8f4-835157e8c622"></a>
### 9982-59de1e2/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30745
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3934634a7345:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 59 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 2 minutes and 45 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 4 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 36 seconds
(10/15) Running minio-java tests ... FAILED in 5 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1293,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 41 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 56 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 30 seconds
(13/15) Running s3select tests ... done in 1 minutes and 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="0b5f3fb6-192b-42d5-88c3-480374669b6b"></a>
### 9982-59de1e2/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32078
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dae4cfc35e7c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 18 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... done in 1 minutes and 26 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 25 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 36 seconds
(9/15) Running minio-go tests ... FAILED in 3 minutes and 3 seconds
{
  "args": {
    "bucketName": "minio-go-test-kn4wp2gdvspym4ai",
    "objectName": "phgd6slf9bn1fbvpt3u6oavolym9qw",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4436,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 42 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 8 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 43 seconds
(12/15) Running s3cmd tests ... done in 28 seconds
(13/15) Running s3select tests ... done in 15 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="47628a2c-410e-40b4-83ac-8d06ac2c61d9"></a>
### 9982-59de1e2/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30264
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 123d54de5769:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 12 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 2 minutes and 24 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 26 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 51 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 12 seconds
{
  "args": {
    "bucketName": "minio-go-test-2ai1x0jo39zagz3g",
    "objectName": "w69xm06lymlodkkscashpv56jeg1es",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4521,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 3 minutes and 37 seconds
(10/15) Running minio-js tests ... done in 53 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 14 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 15 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="8b6ed0ae-e9c6-4fae-851b-28db9ba57473"></a>
### 9982-59de1e2/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30245
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b0c4f117f5b5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 11 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 49 seconds
(4/15) Running aws-sdk-ruby tests ... done in 10 seconds
(5/15) Running awscli tests ... done in 2 minutes and 23 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 12 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 41 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 4 seconds
{
  "args": {
    "bucketName": "minio-go-test-0nwxjf9urnbi0g1o",
    "objectName": "ohcsp9id4ld46j0qmz9em2vf5mj4r1",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3683,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 3 minutes and 47 seconds
(10/15) Running minio-js tests ... done in 54 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 51 seconds
(12/15) Running s3cmd tests ... done in 28 seconds
(13/15) Running s3select tests ... done in 14 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#da45d17a-e5fb-486d-ad18-38e2f1beed88) |
| mint-large-bucket.sh | :x: [more...](#fab3088a-2ae5-48d9-9b2b-73fc87444b32) |
| mint-dist-xl.sh | :x: [more...](#e238ddc7-976d-4f24-ae35-554330ffe2ec) |
| mint-gateway-azure.sh | :x: [more...](#a5c03135-ce2a-4c48-95a5-d97d5070ee5f) |
| mint-zoned.sh | :x: [more...](#ee7af469-22f8-4552-8b4e-572f092496f5) |
<a name="a5c03135-ce2a-4c48-95a5-d97d5070ee5f"></a>
### 9982-d9ab87f/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30156
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 09f9e5df3145:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 2 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 2 minutes and 45 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 18 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 32 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 36 seconds
(10/15) Running minio-java tests ... FAILED in 5 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1285,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 35 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 42 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 22 seconds
(13/15) Running s3select tests ... done in 1 minutes and 1 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="e238ddc7-976d-4f24-ae35-554330ffe2ec"></a>
### 9982-d9ab87f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32358
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp da152738ab39:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 16 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 8 seconds
(5/15) Running awscli tests ... done in 2 minutes and 29 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 52 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 18 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 54 seconds
{
  "args": {
    "bucketName": "minio-go-test-opb0qldhkwmd3edz",
    "objectName": "ylx6b324fi41yoshq3e1ttr25lo9u4",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4634,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 42 seconds
(10/15) Running minio-js tests ... done in 59 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 0 seconds
(12/15) Running s3cmd tests ... done in 26 seconds
(13/15) Running s3select tests ... done in 25 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="fab3088a-2ae5-48d9-9b2b-73fc87444b32"></a>
### 9982-d9ab87f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30017
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6472afb62b19:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 17 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 49 seconds
(4/15) Running aws-sdk-ruby tests ... done in 10 seconds
(5/15) Running awscli tests ... done in 2 minutes and 49 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 46 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 14 seconds
(9/15) Running minio-go tests ... FAILED in 3 minutes and 6 seconds
{
  "args": {
    "bucketName": "minio-go-test-sarde6xfsvjv3fvt",
    "objectName": "sr6yjuxllxzqim9y2hkk3dmno4lopm",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 8619,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 13 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 2 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 16 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 13 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="da45d17a-e5fb-486d-ad18-38e2f1beed88"></a>
### 9982-d9ab87f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31949
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1de8689b8fc8:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 41 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 49 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 29 seconds
{
  "args": {
    "bucketName": "minio-go-test-qjlwa6hm1wlayq9c",
    "objectName": "c4ktbgxkt3cl9ye0nrqguzalhflf59",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3231,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 3 minutes and 33 seconds
(10/15) Running minio-js tests ... done in 53 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 59 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 11 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="ee7af469-22f8-4552-8b4e-572f092496f5"></a>
### 9982-d9ab87f/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31784
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d7d0e8d3cc37:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 20 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... done in 2 minutes and 49 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 2 minutes and 1 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 32 seconds
(9/15) Running minio-go tests ... FAILED in 3 minutes and 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-ss2wgkthwparlyu0",
    "objectName": "h3azqrd3l3dss0sl4hoxhb0j06ilgw",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5747,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 8 minutes and 9 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 3 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 27 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 9 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]
LGTM. Should we also add an example and where should this API be documented?

**Comment by harshavardhana** [comment]
> LGTM. Should we also add an example and where should this API be documented?

We don't need documentation @kannappanr it is meant for `mc` to be used. Users will use `mc` to create keys.

**Pull request merged**
