### PR TITLE
Add simple metadata commandline printer

### PR DESCRIPTION
**Pull request by klauspost**
## Motivation and Context

Easy inspection of metadata files.

Example output:

```
{
  "Versions": [
    {
      "Type": 1,
      "V2Obj": {
        "ID": [
          92,
          83,
          215,
          15,
          143,
          30,
          70,
          162,
          175,
          226,
          124,
          241,
          132,
          243,
          132,
          29
        ],
        "DDir": [
          198,
          1,
          80,
          121,
          203,
          80,
          68,
          145,
          139,
          93,
          199,
          244,
          87,
          245,
          200,
          117
        ],
        "EcAlgo": 1,
        "EcM": 2,
        "EcN": 2,
        "EcBSize": 10485760,
        "EcIndex": 3,
        "EcDist": "AgMEAQ==",
        "CSumAlgo": 1,
        "PartNums": [
          1
        ],
        "PartETags": [
          ""
        ],
        "PartSizes": [
          10490880
        ],
        "PartASizes": [
          10485760
        ],
        "Size": 10490880,
        "MTime": 1592831201921364300,
        "MetaSys": {
          "X-Minio-Internal-Server-Side-Encryption-Iv": "MHd0UlZPdEdYUUlKK2NVWE5mNFRlU3F3SExyOWI0dkZRZkV0dnlGQUIvTT0=",
          "X-Minio-Internal-Server-Side-Encryption-S3-Kms-Key-Id": "bXktbWluaW8ta2V5",
          "X-Minio-Internal-Server-Side-Encryption-S3-Kms-Sealed-Key": "SUFBZkFJaERINW9aVStTMXF5YS9xRDlhNERVZ3BUR1kyM1hzWm4yZ0dha2YzeUxIbU9KL0x3R2lqaEVCVTROSnk1NDZYVlNHUFl4Tm82K1grMTZsenc9PQ==",
          "X-Minio-Internal-Server-Side-Encryption-S3-Sealed-Key": "SUFBZkFLVEdOV0hENFJmeDNNQk1MU1ZlWlhRWER5THZQaWdFOThHRnVCMGl2LzFTL2RjWk1JYXdSeEhXaVIrR1o3WTBTdFh3SUJLbU54cXc5cmFTK1E9PQ==",
          "X-Minio-Internal-Server-Side-Encryption-Seal-Algorithm": "REFSRXYyLUhNQUMtU0hBMjU2"
        },
        "MetaUsr": {
          "content-type": "application/octet-stream",
          "etag": "20000f00f172acf19c8a6b28bb8017cdfd5b20e9a99ddd849203e35be58a0ab28c1de4f7aa7d9bcb9f2c814ba5dfa5c4"
        }
      }
    },
    {
      "Type": 2,
      "DelObj": {
        "ID": [
          226,
          214,
          3,
          167,
          12,
          16,
          74,
          68,
          130,
          255,
          150,
          10,
          170,
          43,
          19,
          247
        ],
        "MTime": 1592831202665027200
      }
    }
  ]
}
```

Error messages also a bit more informational.

## How to test this PR?

* Go into `github.com/minio/cmd/read-meta`.
* Execute `go install read-meta-v2.go`
* Run on any file `read-meta-v2 xl.meta`
* Output is printed to stdout.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by harshavardhana** [comment]
@klauspost can you not improve `xl-meta-to-json.go` ?

**Comment by klauspost** [comment]
@harshavardhana You mean make it look nicer?

**Comment by harshavardhana** [comment]
> @harshavardhana You mean make it look nicer?

I meant either have you change or remove this file or borrow changes from it.

**Comment by klauspost** [comment]
@harshavardhana Ah. Hadn't seen that file. Sure.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#5a6ac770-0202-4a91-85b8-c1e04803e12d) |
| mint-large-bucket.sh | :x: [more...](#10be339d-0803-47d8-a573-35cfd379e090) |
| mint-dist-xl.sh | :x: [more...](#b866b419-808a-4343-850d-53bad5b8a9d2) |
<a name="5a6ac770-0202-4a91-85b8-c1e04803e12d"></a>
### 9896-eedeca8/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30757
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4f294cada23f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 31 seconds
(8/15) Running minio-dotnet tests ... done in 43 seconds
(9/15) Running minio-go tests ... FAILED in 54 seconds
{
  "args": {
    "bucketName": "minio-go-test-pddp60hj9m93c9mf",
    "objectName": "bujfqcvkj5psfh0qo9k1wvbdpacq3e",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4412,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 1 minutes and 45 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 203,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-qf42p1, objectName = null, resource = /minio-java-test-qf42p1, requestId = 161AE8F79C6A0969, hostId = 2753a2f2-1d6f-4256-8671-1f10bd25832e)\nrequest={method=DELETE, url=http://minio-c3.minio.io:30757/minio-java-test-qf42p1, headers=Host: minio-c3.minio.io:30757\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200622T155928Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200622/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-22T15-46-40Z\nVary: Origin\nX-Amz-Request-Id: 161AE8F79C6A0969\nX-Xss-Protection: 1; mode=block\nDate: Mon, 22 Jun 2020 15:59:28 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 55 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 23 seconds
(11/15) Running s3cmd tests ... done in 22 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="10be339d-0803-47d8-a573-35cfd379e090"></a>
### 9896-eedeca8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32396
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 10bd57184eed:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 28 seconds
(2/15) Running aws-sdk-java tests ... done in 5 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 11 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 minutes and 29 seconds
(5/15) Running awscli tests ... done in 3 minutes and 9 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 16 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 59 seconds
(9/15) Running minio-go tests ... FAILED in 4 minutes and 54 seconds
{
  "args": {
    "bucketName": "minio-go-test-wgluvpc4kqeo149h",
    "objectName": "41a1ekfipxixvxhpgspocwpp49ip3p",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 6863,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 9 minutes and 38 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 4474,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-m0hhlg, objectName = null, resource = /minio-java-test-m0hhlg, requestId = 161AEA04FFF59F8E, hostId = af4e9aa3-0bd2-458b-9116-3d837d7de589)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:32396/minio-java-test-m0hhlg, headers=Host: minio-dev6.minio.io:32396\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200622T161845Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200622/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-22T15-46-40Z\nVary: Origin\nX-Amz-Request-Id: 161AEA04FFF59F8E\nX-Xss-Protection: 1; mode=block\nDate: Mon, 22 Jun 2020 16:18:45 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 15 seconds
(10/15) Running minio-py tests ... done in 13 minutes and 40 seconds
(11/15) Running s3cmd tests ... done in 41 seconds
(12/15) Running s3select tests ... done in 52 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="b866b419-808a-4343-850d-53bad5b8a9d2"></a>
### 9896-eedeca8/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31892
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 795a31cc9386:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 6 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 3 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 5 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 50 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 53 seconds
{
  "args": {
    "bucketName": "minio-go-test-tenza60pvfr1alvp",
    "objectName": "c61c1eyszw2mfrob3pka46e1bwxtow",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3971,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 3 minutes and 38 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 276,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3r04k9n, objectName = null, resource = /minio-java-test-3r04k9n, requestId = 161AE94597132263, hostId = f9254d49-cd84-4760-a55a-01d0f5293910)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:31892/minio-java-test-3r04k9n, headers=Host: minio-dev4.minio.io:31892\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200622T160503Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200622/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-22T15-46-40Z\nVary: Origin\nX-Amz-Request-Id: 161AE94597132263\nX-Xss-Protection: 1; mode=block\nDate: Mon, 22 Jun 2020 16:05:03 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 50 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 42 seconds
(11/15) Running s3cmd tests ... done in 22 seconds
(12/15) Running s3select tests ... done in 7 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request closed without merging**
