### PR TITLE
Add object parity in listing V2M and listing versions M

### PR DESCRIPTION
**Pull request by vadmeste**
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by vadmeste** [comment]
@klauspost currently parity information are in UserMetadata, thinking to move them outside

```
 <Contents>
    <Key>go.mod</Key>
    <LastModified>2023-05-16T16:24:19.989Z</LastModified>
    <ETag>"7be5e22578783218f2eda8dbe29a4daf"</ETag>
    <Size>681</Size>
    <Owner>
      <ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID>
      <DisplayName>minio</DisplayName>
    </Owner>
    <StorageClass>STANDARD</StorageClass>
    <UserMetadata>
      <K>3</K>
      <M>1</M>
      <content-type>application/octet-stream</content-type>
      <X-Amz-Meta-A>B</X-Amz-Meta-A>
    </UserMetadata>
  </Contents>
```

**Comment by klauspost** [comment]
Oh, there was special marshal code. I thought the format was how it was returned.

Yes, move it outside in an `<Erasure>` tag.

**Comment by vadmeste** [comment]
> Yes, move it outside in an <Erasure> tag.

I think `<Internal></Internal>` is better here, we may have to add something there in the future

**Review by klauspost — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
