### PR TITLE
completed sample config and fix wrong json format

### PR DESCRIPTION
**Pull request by wksw**
missing worm configuration and wrong json format

## Description

add worm configuration and fix the json format

## Motivation and Context

make sure get a complete and right config from here

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#eacb2e48-2c03-45c1-a34b-903f51c9698a) |
<a name="eacb2e48-2c03-45c1-a34b-903f51c9698a"></a>
### 6096-47f3ac2/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32648
ACCESS_KEY:           minioazure1
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9571cccf121d:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 8460,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the CreateBucket operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```

**Comment by nitisht** [comment]
Thanks for the PR @wksw but https://github.com/minio/minio/pull/6088/files is already addressing the problem in a detailed manner.

**Comment by harshavardhana** [comment]
> Thanks for the PR @wksw but https://github.com/minio/minio/pull/6088/files is already addressing the problem in a detailed manner.

Perhaps we can take this PR and PR #6088 can rebase on top - this PR in itself is independent, looks like PR #6088 is piggybacking these fixes as well.

**Comment by nitisht** [comment]
> this PR in itself is independent, looks like PR #6088 is piggybacking these fixes as well.

fair enough.

**Review by nitisht — APPROVED** [review]

**Pull request merged**
