### PR TITLE
Avoid race in accessing internal reader

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Avoid race in accessing internal reader

## Motivation and Context
Fixes a race reported by windows CI

```
Read at 0x00c000239410 by goroutine 402:
  github.com/minio/minio/cmd.(*streamingBitrotReader).Close()
      C:/Users/travis/gopath/src/github.com/minio/minio/cmd/bitrot-streaming.go:109 +0x4e
  github.com/minio/minio/cmd.closeBitrotReaders()
      C:/Users/travis/gopath/src/github.com/minio/minio/cmd/bitrot.go:137 +0xab
  github.com/minio/minio/cmd.TestErasureDecode()
      C:/Users/travis/gopath/src/github.com/minio/minio/cmd/erasure-decode_test.go:185 +0x16e7
  testing.tRunner()
      C:/Users/travis/.gimme/versions/go1.11.4.windows.amd64/src/testing/testing.go:827 +0x169
Previous write at 0x00c000239410 by goroutine 389:
  github.com/minio/minio/cmd.(*streamingBitrotReader).ReadAt()
      C:/Users/travis/gopath/src/github.com/minio/minio/cmd/bitrot-streaming.go:126 +0x9ac
  github.com/minio/minio/cmd.(*parallelReader).Read.func1()
      C:/Users/travis/gopath/src/github.com/minio/minio/cmd/erasure-decode.go:80 +0x301
```

## Regression
No

## How Has This Been Tested?
Using windows CI on travis

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by krishnasrinivas** [comment]
@harshavardhana https://github.com/minio/minio/pull/7109 fixes the cause

**Comment by harshavardhana** [comment]
Cool, closing.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#8a1a3435-13b6-4f94-b80e-20b1007594b1) |
| mint-xl.sh | :x: [more...](#60e9b3e4-3cc7-4310-8ed4-80222103f44f) |
| mint-large-bucket.sh | :x: [more...](#407b17f5-e77b-4b7f-af20-88b8b328f925) |
| mint-dist-xl.sh | :x: [more...](#7af05efb-c903-4af8-9d6f-e64a284f3442) |
<a name="7af05efb-c903-4af8-9d6f-e64a284f3442"></a>
### 7107-8b47ed5/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30444
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0782a91e442f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 28 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 6 seconds
(4/13) Running aws-sdk-php tests ... done in 46 seconds
(5/13) Running aws-sdk-ruby tests ... done in 12 seconds
(6/13) Running mc tests ... FAILED in 1 days 8 hours 14 minutes and 33 seconds
{
  "name": "mc",
  "duration": "116066189",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-1306 --quiet --no-color cp myminio/mc-test-bucket-5828/mc-test-object-26520 mc-test-object-26520.downloaded  >>> \n`myminio/mc-test-bucket-5828/mc-test-object-26520` -> `mc-test-object-26520.downloaded`\nmc: <ERROR> Failed to copy `http://minikube:30444/mc-test-bucket-5828/mc-test-object-26520`. Input reader closed pre-maturely. Expected `68157440` bytes, but only received `20971520` bytes.\nmc: <ERROR> Session safely terminated. To resume session `mc session resume NokWbQhl`"
}

Executed 5 out of 13 tests successfully.
```
<a name="60e9b3e4-3cc7-4310-8ed4-80222103f44f"></a>
### 7107-8b47ed5/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30113
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ca5a00696d82:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 4 minutes and 1 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 7 seconds
(4/13) Running aws-sdk-php tests ... done in 42 seconds
(5/13) Running aws-sdk-ruby tests ... done in 5 seconds
(6/13) Running mc tests ... FAILED in 1 days 8 hours 18 minutes and 48 seconds
{
  "name": "mc",
  "duration": "116322924",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-24969 --quiet --no-color cp myminio/mc-test-bucket-22981/mc-test-object-24653 mc-test-object-24653.downloaded  >>> \n`myminio/mc-test-bucket-22981/mc-test-object-24653` -> `mc-test-object-24653.downloaded`\nmc: <ERROR> Failed to copy `http://minikube:30113/mc-test-bucket-22981/mc-test-object-24653`. Input reader closed pre-maturely. Expected `68157440` bytes, but only received `20971520` bytes.\nmc: <ERROR> Session safely terminated. To resume session `mc session resume pbgMlWDq`"
}

Executed 5 out of 13 tests successfully.
```
<a name="407b17f5-e77b-4b7f-af20-88b8b328f925"></a>
### 7107-8b47ed5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30954
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1aa26e9fe0a9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 54 seconds
(2/13) Running aws-sdk-go tests ... done in 3 seconds
(3/13) Running aws-sdk-java tests ... done in 6 seconds
(4/13) Running aws-sdk-php tests ... done in 1 minutes and 2 seconds
(5/13) Running aws-sdk-ruby tests ... done in 25 seconds
(6/13) Running mc tests ... FAILED in 1 days 8 hours 12 minutes and 57 seconds
{
  "name": "mc",
  "duration": "115967392",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28393 --quiet --no-color cp myminio/mc-test-bucket-23457/mc-test-object-28447 mc-test-object-28447.downloaded  >>> \n`myminio/mc-test-bucket-23457/mc-test-object-28447` -> `mc-test-object-28447.downloaded`\nmc: <ERROR> Failed to copy `http://minikube:30954/mc-test-bucket-23457/mc-test-object-28447`. Input reader closed pre-maturely. Expected `68157440` bytes, but only received `20971520` bytes.\nmc: <ERROR> Session safely terminated. To resume session `mc session resume LvyKxCmZ`"
}

Executed 5 out of 13 tests successfully.
```
<a name="8a1a3435-13b6-4f94-b80e-20b1007594b1"></a>
### 7107-8b47ed5/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31482
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9d3f55e016e7:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 48 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 9 seconds
(4/13) Running aws-sdk-php tests ... done in 42 seconds
(5/13) Running aws-sdk-ruby tests ... done in 5 seconds
(6/13) Running mc tests ... FAILED in 1 days 8 hours 19 minutes and 7 seconds
{
  "name": "mc",
  "duration": "116343242",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28014 --quiet --no-color cp myminio/mc-test-bucket-24980/mc-test-object-30089 mc-test-object-30089.downloaded  >>> \n`myminio/mc-test-bucket-24980/mc-test-object-30089` -> `mc-test-object-30089.downloaded`\nmc: <ERROR> Failed to copy `http://minikube:31482/mc-test-bucket-24980/mc-test-object-30089`. Input reader closed pre-maturely. Expected `68157440` bytes, but only received `20938752` bytes.\nmc: <ERROR> Session safely terminated. To resume session `mc session resume xHLMFFnh`"
}

Executed 5 out of 13 tests successfully.
```

**Pull request closed without merging**
