### PR TITLE
fix: an odd crash when deleting `null` DEL markers

### LINKED ISSUE #18724: Panic Error: slice bounds out of range, in DeleteVersion
Hello MinIO Community, 

I experience a potential bug/missed error handling in the Way Versions are handled/deleted. 

After upgrading to Version 2023-12-23T07:19:11Z from 2023-11-20T22:40:07Z, my cluster crashes every 1-2 minutes, as soon as some specific versioned Files are to be deleted. The Error Message is: 

```
panic: runtime error: slice bounds out of range [3:1]
goroutine 57207 [running]:
github.com/minio/minio/cmd.(*xlMetaV2).DeleteVersion(_, {{0x0, 0x0}, {0xc0137d0000, 0x3a}, {0x0, 0x0}, 0x0, 0x0, {0x0, ...}, ...})
#011github.com/minio/minio/cmd/xl-storage-format-v2.go:1414 +0x2e30
github.com/minio/minio/cmd.(*xlStorage).DeleteVersion(_, {_, _}, {_, _}, {_, _}, {{0x0, 0x0}, {0xc0137d0000, ...}, ...}, ...)
#011github.com/minio/minio/cmd/xl-storage.go:1212 +0x768
github.com/minio/minio/cmd.(*xlStorageDiskIDCheck).DeleteVersion.func1()
#011github.com/minio/minio/cmd/xl-storage-disk-id-check.go:593 +0x66
github.com/minio/minio/internal/ioutil.(*DeadlineWorker).Run.func1()
#011github.com/minio/minio/internal/ioutil/ioutil.go:141 +0x22
created by github.com/minio/minio/internal/ioutil.(*DeadlineWorker).Run in goroutine 57256
#011github.com/minio/minio/internal/ioutil/ioutil.go:140 +0xbe

panic: runtime error: slice bounds out of range [2:1]
goroutine 4223965 [running]:
github.com/minio/minio/cmd.(*xlMetaV2).DeleteVersion(_, {{0x0, 0x0}, {0xc019e5e280, 0x45}, {0x0, 0x0}, 0x0, 0x0, {0x0, ...}, ...})
#011github.com/minio/minio/cmd/xl-storage-format-v2.go:1414 +0x2e30
github.com/minio/minio/cmd.(*xlStorage).DeleteVersion(_, {_, _}, {_, _}, {_, _}, {{0x0, 0x0}, {0xc019e5e280, ...}, ...}, ...)
#011github.com/minio/minio/cmd/xl-storage.go:1212 +0x768
github.com/minio/minio/cmd.(*xlStorageDiskIDCheck).DeleteVersion.func1()
#011github.com/minio/minio/cmd/xl-storage-disk-id-check.go:593 +0x66
github.com/minio/minio/internal/ioutil.(*DeadlineWorker).Run.func1()
#011github.com/minio/minio/internal/ioutil/ioutil.go:141 +0x22
created by github.com/minio/minio/internal/ioutil.(*DeadlineWorker).Run in goroutine 4226206
#011github.com/minio/minio/internal/ioutil/ioutil.go:140 +0xbe
```
 
A specific File for Example looks like this: 
```
mc ls minio/loki-chunks/index/loki_index_19343/loki-write-0-1671277734359685422-1671317692.gz --versions
[2023-12-25 17:02:15 CET]     0B STANDARD null v1 DEL loki-write-0-1671277734359685422-1671317692.gz
```
 
If I try to delete it: 
```
mc rm minio/loki-chunks/index/loki_index_19343/loki-write-0-1671277734359685422-1671317692.gz --versions --force
Removed `minio/loki-chunks/index/loki_index_19343/loki-write-0-1671277734359685422-1671317692.gz` (versionId=null).
```
the file is still there after Server crashed and restarted.
the Trace for this request end up failing:
```
mc admin trace -v minio --path loki-chunks/index                                                                
mc: <ERROR> Unable to listen to http trace: unexpected EOF.
```
 
This happens buckets that have been versioned for quite some time. 

## Expected Behavior
A version of a file, the file itself etc. Is deleted. 

## Current Behavior
When trying to delete the file it is suggested by cli that it is working, but the server is crashing with a panic error. After the Crash, the Cluster keeps restarting for a few minutes repeatedly trying to delete the dangling files. 

## Possible Solution
Just give an error message, delete the file that is broken instead of panic error. 
Even better would be, if such orphanage files would be removed automatically. 

## Steps to Reproduce (for bugs)
No steps to reproduce on a new system possible as it requires older files. 

## Context
Old Versions need to be pruned from Buckets. 

## Regression
There are multiple Issues that had the context of Old Files making Problems, but i cannot name a Version specific

## Your Environment
* Version used (`minio --version`):
```
mc admin info minio-hq
●  minio-1.example.org:9000
   Uptime: 17 minutes 
   Version: 2023-12-23T07:19:11Z
   Network: 4/4 OK 
   Drives: 8/8 OK 
   Pool: 1

●  minio-2.example.org:9000
   Uptime: 17 minutes 
   Version: 2023-12-23T07:19:11Z
   Network: 4/4 OK 
   Drives: 8/8 OK 
   Pool: 1

●  minio-3.example.org:9000
   Uptime: 17 minutes 
   Version: 2023-12-23T07:19:11Z
   Network: 4/4 OK 
   Drives: 8/8 OK 
   Pool: 1

●  minio-4.example.org:9000
   Uptime: 17 minutes 
   Version: 2023-12-23T07:19:11Z
   Network: 4/4 OK 
   Drives: 8/8 OK 
   Pool: 1

Pools:
   1st, Erasure sets: 2, Drives per erasure set: 16

3.6 TiB Used, 44 Buckets, 402,534 Objects, 494,349 Versions, 89,961 Delete Markers
32 drives online, 0 drives offline
```

* Server setup and configuration:
4 baremetal Linux Server
- 8 Drives each 
- filesystem: xfs
- HBA mode
* Operating System and version (`uname -a`):
```
uname -a
Linux minio-3 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by harshavardhana**
This PR should address both scenarios.

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix: an odd crash when deleting `null` DEL markers

## Motivation and Context
fixes #18724

A regression was introduced in #18547, that attempted
to file adding a missing `null` marker however we
should not skip returning based on versionID instead
it must be based on if we are being asked to create
a DEL marker or not.

The PR also has a side-affect for replicating `null`
marker permanent delete, as it may end up adding a
`null` marker while removing one.

This PR should address both scenarios.

## How to test this PR?
Requires a special set of files that can reproduce this, we need to
have many `null` DEL markers on the same object. This is not possible any
MinIO versions since some time, as we do not allow new DEL markers to be
created on the namesapce anymore.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by klauspost** [comment]
```
--- FAIL: TestHealingDanglingObject (0.09s)
    erasure-healing_test.go:693: Expected versions 1, got 2
FAIL
```

**Review by jiuker — APPROVED** [review]
Fix the pipeline plz

**Comment by vadmeste** [comment]
@harshavardhana do you have a handy reproducer for the issue ?

**Comment by harshavardhana** [comment]
> @harshavardhana do you have a handy reproducer for the issue ?

Yeah its in the issue @vadmeste it requires a strange situation that has not happened since some time now. 

you need two or more DEL markers with `null` vid on the same object.

**Comment by harshavardhana** [comment]
Done the tests must be fixed, checking if mint tests pass or not.

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
