### PR TITLE
Tier metrics prometheus

### PR DESCRIPTION
**Pull request by krisis**
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 13413-2aca3fc/gopath/src/github.com/minio
+ git -C 13413-2aca3fc/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 13413-2aca3fc/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 13413-2aca3fc/gopath/src/github.com/minio/minio fetch --quiet minio pull/13413/head:pr13413
+ git -C 13413-2aca3fc/gopath/src/github.com/minio/minio checkout --quiet pr13413
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/13413-2aca3fc/gopath
+ make -C 13413-2aca3fc/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13413-2aca3fc/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13413-2aca3fc/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13413-2aca3fc/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading github.com/minio/pkg v1.1.4
go: downloading github.com/minio/minio-go/v7 v7.0.15-0.20210928020726-a58653d41dd8
go: downloading github.com/json-iterator/go v1.1.11
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading google.golang.org/api v0.31.0
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/rs/dnscache v0.0.0-20210201191234-295bba877686
go: downloading github.com/golang-jwt/jwt v3.2.1+incompatible
go: downloading github.com/fatih/color v1.12.0
go: downloading golang.org/x/sys v0.0.0-20210819135213-f52c844e1c1c
go: downloading golang.org/x/crypto v0.0.0-20210616213533-5ff15b29337e
go: downloading github.com/minio/kes v0.14.0
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/klauspost/compress v1.13.5
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/go-openapi/loads v0.20.2
go: downloading github.com/bits-and-blooms/bloom/v3 v3.0.1
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/klauspost/reedsolomon v1.9.13
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/minio/console v0.10.3
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/minio/zipindex v0.2.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/pierrec/lz4 v2.6.0+incompatible
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/shirou/gopsutil/v3 v3.21.7
go: downloading github.com/tinylib/msgp v1.1.6-0.20210521143832-0becd170c402
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/yargevad/filepathx v1.0.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.0-beta.4
go: downloading go.etcd.io/etcd/client/v3 v3.5.0-beta.4
go: downloading go.uber.org/atomic v1.7.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading go.uber.org/zap v1.16.1-0.20210329175301-c23abee72d19
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/elastic/go-elasticsearch/v7 v7.12.0
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/nats-io/nats.go v1.11.1-0.20210623165838-4b75fc59ae30
go: downloading github.com/nats-io/stan.go v0.8.3
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/klauspost/cpuid/v2 v2.0.6
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/minio/parquet-go v1.0.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading go.opencensus.io v0.22.5
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13413-2aca3fc/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
make: *** [build] Error 1

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
