### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by darkdragon-001**
## Description
Follow up on the great work of @harshavardhana in #9633.

### Success

npm audit
- `npm install --save-dev css-loader@3.5.3`
- `npm install --save-dev url-loader@4.1.0`
- `npm install --save-dev copy-webpack-plugin@6.0.1`
  - constructor changed (fixed in `webpack*.config.js`)
  - dependency `move-file@2.0.0` requires node >=10.17 (changed in `Dockerfile.simpleci`)

npm outdated
- general dependencies
  - `npm install --save-dev async@3.2.0 esformatter-jsx@8.0.1`
  - `npm install --save expect@26.0.1 moment@2.26.0 redux@4.0.5 reselect@4.0.0 superagent@5.2.2`
- webpack dependencies
  - `npm install --save-dev html-webpack-plugin@4.3.0 purgecss-webpack-plugin@2.2.0`
- style dependencies
  - `npm install --save-dev style-loader@1.2.1 less-loader@6.1.0`
- react dependencies
  - `npm install --save react-addons-test-utils@15.6.2 react-router-dom@5.2.0`
- testing (jest) dependencies
  - `npm install --save-dev babel-jest@23.6.0 jest@23.6.0 jest-enzyme@7.1.2`

## Motivation and Context
Fix security vulnerabilities, use new features.

## How to test this PR?
Test suite, browser.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by darkdragon-001** [comment]
Below you can find some notes for further updates which I did not perform. I hope this helps limiting the time needed to fix these as well...

### Update fails (-> not included in this PR)

react
- #`npm install --save bootstrap@4.5.0 react-bootstrap@1.0.1` -> problems _not found_ when running "npm run dev"
- #`npm install --save react-redux@7.2.0` -> 2 tests fail
- #`npm install --save react-dropzone@11.0.1` -> done in #9627

jest
- #`npm install --save-dev babel-jest@26.0.1 jest@26.0.1` -> needs fixes in tests
- #`npm install --save-dev babel-loader@8.1.0` -> problems running `npm run dev`
- #warning: `babel-preset-es2015@6.24.1`: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!

### Browser console warnings (existed before PR)

- [React unsafe component lifecycles](https://fb.me/react-unsafe-component-lifecycles)

> Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.

**Comment by harshavardhana** [comment]
@darkdragon-001 updating ui-assets.go is a controlled process we ask you not to add that as part of your commit. It is updated by maintainers only.

**Comment by darkdragon-001** [comment]
@harshavardhana I removed the ui-assets.go commit.

**Comment by kanagarajkm** [comment]
@darkdragon-001 could you fix the conflict?

**Comment by darkdragon-001** [comment]
@kanagarajkm done.

**Review by kanagarajkm — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#2022ad4a-f0e4-4f4c-82a5-b2bfb18995ac) |
<a name="2022ad4a-f0e4-4f4c-82a5-b2bfb18995ac"></a>
### 9673-c6656f6/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30475
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0642ba8b85c8:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 9 seconds
(8/15) Running minio-dotnet tests ... done in 26 seconds
(9/15) Running minio-go tests ... done in 10 seconds
(10/15) Running minio-java tests ... done in 19 seconds
(11/15) Running minio-js tests ... FAILED in 6 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-0536226b-6398-4da9-8842-124b8b3d0b13",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 51 seconds
(12/15) Running s3cmd tests ... done in 12 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#98f0999c-621b-41f5-983a-a7170c5e1a2e) |
<a name="98f0999c-621b-41f5-983a-a7170c5e1a2e"></a>
### 9673-c69accf/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31982
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 229ed054a79e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 9 seconds
(8/15) Running minio-dotnet tests ... done in 27 seconds
(9/15) Running minio-go tests ... done in 11 seconds
(10/15) Running minio-java tests ... done in 18 seconds
(11/15) Running minio-js tests ... FAILED in 8 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-d05689bd-f202-4008-a3c3-24e4c1a63235",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 50 seconds
(12/15) Running s3cmd tests ... done in 12 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kaankabalak — APPROVED** [review]

**Pull request merged**
