### PR TITLE
Hotfix/image preview

### PR DESCRIPTION
**Pull request by tweigel-dev**
### Hotfix:
upload of ui-assets.go for feature image-preview
[PR](https://github.com/minio/minio/pull/9239) 
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 9329-492ee29/gopath/src/github.com/minio
+ git -C 9329-492ee29/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9329-492ee29/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9329-492ee29/gopath/src/github.com/minio/minio fetch --quiet minio pull/9329/head:pr9329
+ git -C 9329-492ee29/gopath/src/github.com/minio/minio checkout --quiet pr9329
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/9329-492ee29/gopath
+ make -C 9329-492ee29/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/minio/minio-go/v6 v6.0.52
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/json-iterator/go v1.1.9
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading github.com/Shopify/sarama v1.24.1
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/beevik/ntp v0.2.0
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/minio/lsync v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/cheggaaa/pb v1.0.28
go: downloading github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/kurin/blazer v0.5.4-0.20200327014341-8f90a40f8af7
go: downloading gopkg.in/ini.v1 v1.48.0
go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading github.com/nats-io/stan.go v0.4.5
go: downloading github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/tinylib/msgp v1.1.1
go: downloading github.com/miekg/dns v1.1.8
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/nats-io/nats.go v1.9.1
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: downloading google.golang.org/grpc v1.22.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading github.com/minio/sio v0.2.0
go: downloading github.com/gorilla/handlers v1.4.0
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading go.opencensus.io v0.21.0
go: downloading github.com/fatih/color v1.7.0
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading github.com/prometheus/common v0.2.0
go: downloading github.com/nats-io/nkeys v0.1.3
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading go.uber.org/atomic v1.3.2
go: downloading github.com/philhofer/fwd v1.0.0
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: downloading github.com/klauspost/compress v1.10.3
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/klauspost/cpuid v1.2.2
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/gorilla/mux v1.7.0
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/lib/pq v1.1.1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading github.com/rs/cors v1.6.0
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading gopkg.in/yaml.v2 v2.2.4
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading github.com/minio/simdjson-go v0.1.5-0.20200303142138-b17fe061ea37
go: downloading github.com/djherbis/atime v1.0.0
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/klauspost/pgzip v1.2.1
go: downloading github.com/minio/parquet-go v0.0.0-20200125064549-a1e49702e174
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/tidwall/pretty v1.0.0
go: downloading github.com/tidwall/match v1.0.1
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/ryanuber/go-glob v1.0.0
# github.com/minio/minio/browser
browser/ui-assets.go:78:1: syntax error: unexpected <<, expecting }
browser/ui-assets.go:99:1: syntax error: unexpected <<, expecting }
browser/ui-assets.go:120:1: syntax error: unexpected <<, expecting }
browser/ui-assets.go:141:1: syntax error: unexpected <<, expecting }
browser/ui-assets.go:162:1: syntax error: unexpected <<, expecting }
browser/ui-assets.go:247:1: syntax error: unexpected <<, expecting }
browser/ui-assets.go:259:57: syntax error: unexpected !, expecting comma or )
browser/ui-assets.go:259: invalid character U+003F '?'
browser/ui-assets.go:260:1: syntax error: non-declaration statement outside function body
browser/ui-assets.go:271:32: syntax error: unexpected {, expecting expression
browser/ui-assets.go:271:32: too many errors
make: *** [build] Error 2

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#e9d997bb-9d10-4dc9-961a-c887f0d655de) |
<a name="e9d997bb-9d10-4dc9-961a-c887f0d655de"></a>
### 9329-4164231/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32208
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fda8fbf69847:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 7 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... done in 3 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 25 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 29 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 19 seconds
(10/15) Running minio-java tests ... done in 27 minutes and 21 seconds
(11/15) Running minio-js tests ... FAILED in 3 minutes and 52 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-f91fbd10-a769-42db-bdd1-0031b90f01d2, recursive:true",
  "duration": 206,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 10 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
We have already updated the UI assets @tweigel-dev I don't see any change in the code. We don't accept asset building from external community. 

Thanks for the PR, will close it.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#bdcc041f-fb71-4403-92b1-bd92261f2beb) |
<a name="bdcc041f-fb71-4403-92b1-bd92261f2beb"></a>
### 9329-402f691/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30665
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 367dbc488d90:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 8 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... done in 2 minutes and 33 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 9 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 32 seconds
(9/15) Running minio-go tests ... done in 19 minutes and 7 seconds
(10/15) Running minio-java tests ... done in 27 minutes and 51 seconds
(11/15) Running minio-js tests ... FAILED in 3 minutes and 51 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-61786470-c4cd-462a-811c-85f3d7e734d2, recursive:true",
  "duration": 212,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 10 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request closed without merging**
