### PR TITLE
[security] Disable redirect of HTTP request to a HTTPS Minio server

### LINKED ISSUE #4452: [security] Disable HTTP to HTTPS redirection in Minio server
Detailed context about the issue is here - https://github.com/minio/minio/pull/4445#issuecomment-305020726

If the server redirects HTTP to HTTPS, the client never realizes that the initial request is being sent out on the internet in the clear. In this case, there is a silent leaking of data. Parts of the initial request including headers may be sent in the clear.

After further discussion with @abperiasamy it is decided to return an error (in plain text HTTP) to the client - this will force the client to fix the misconfiguration thus limiting the amount of potentially compromised data.

### PR DESCRIPTION
**Pull request by donatello**
Fixes #4452

## Description

Return error to user that the server cannot respond to a plaintext request from a TLS server.

## Motivation and Context

#4452 

## How Has This Been Tested?

Updated test.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — COMMENTED** [review]
Overall looks good. Will validate with mc and browser.

**Comment by deekoder** [comment]
code coverage is going down with this pr can this be addressed @donatello

**Comment by donatello** [comment]
> code coverage is going down with this pr can this be addressed @donatello

It is fixed by itself after all tests completed. @deekoder

**Review by balamurugana — APPROVED** [review]
Not tested

**Review by harshavardhana — APPROVED** [review]
Tested and validated with `mc` and browser.

**Pull request merged**
