### PR TITLE
[security] rpc: Do not transfer access/secret key.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This is an improvement upon existing implementation
by avoiding transfer of access and secret keys over
the network. This change only exchanges JWT tokens
generated by an rpc client. Even if the JWT can be
traced over the network on a non-TLS connection, this
change makes sure that we never really expose the
secret key over the network.

## Motivation and Context
Securing network transfer.

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Browser changes are still pending.. will move this to WIP

**Comment by harshavardhana** [comment]
> Browser changes are still pending.. will move this to WIP

Not going to do browser related changes in this PR, will send a PR for that to `newux` branch instead.

**Comment by harshavardhana** [comment]
This PR is ready for review.. carries only RPC related changes.

**Review by aead — APPROVED** [review]
Change itself LGTM. As far as I can see this cannot be used with the current browser?! So is merging bocked until this is fixed?

**Comment by harshavardhana** [comment]
As I explained before ..browser changes will happen in it's new branch. This just for internal rpc communication.

**Comment by aead** [comment]
Oh, yes - overlooked comment, sry...

**Comment by harshavardhana** [comment]
ping @donatello waiting on your review.

**Review by donatello — APPROVED** [review]

**Pull request merged**
