### PR TITLE
Multitenant/CustomRoot minio browser support

### PR DESCRIPTION
**Pull request by ghost**
## Description
Allow custom application path for hosting web ui. This in turn could allow to start multiple instances for different tenants behind single reverse proxy.

## Motivation and Context

The application root context paths were hardcoded in multiple places, so, there was no easy way to produce customized builds for the web ui part. 

The idea was to have ability to run minio storage web ui using port and hostname sharind scenarios and paths like:
* http://myhost/**miniobrowser**/tenant1/**minio**/
* http://myhost/**miniobrowser**/tenant2/**minio**/
with actual servers being proxied at:
* http://myhost/**minio**/tenant1/minio/
* http://myhost/**minio**/tenant1/minio/

\* Parts enclosed in ** could be configured using constants during build or reverse proxy configuration.

Positive side effect would be complete removal of hardcoded path elements within code. The full backward compatibility should be achieved by providing default values to content. Special case was to inject those constants also to html file (using templates), but now only use them inside javascript code (required update to browser build scripts).

Future improvement could be to add option to set custom application context root also in go code. (I'm not sure if this should be mixed to the same pull request, because the frontend part is pretty isolated if the backend stays compatible).

## How Has This Been Tested?

There were no changes to backend part, so those were testing running the actual build result with reverse proxy enabled. Running **yarn test** detected no issues, but the windows machine was used, so, this was not the most representative result probably.

Configuration during manual tests:
* vanilla build of minio running on localhost:9000
* nginx reverse proxy with the following configuration:

        location ~ ^/miniobrowser/tenant1/minio/[a-zA-Z0-9-_]+$ {
            alias    miniobrowser;
            try_files $uri $uri/ /miniobrowser/tenant1/minio/index.html;
        }

        location ~ ^/miniobrowser/tenant1/minio/.+[^.].+/$ {
            alias    miniobrowser;
            try_files $uri $uri/ /miniobrowser/tenant1/minio/index.html;
        }

        location /miniobrowser/tenant1/minio {
            alias    miniobrowser;
        }

        location /minio/tenant1/ {
            proxy_set_header    Host $http_host;
            proxy_pass          http://127.0.0.1:9000/;
            proxy_redirect      /minio/ /minio/tenant1/minio/;
        }

Constants.json file with content during build:

        {
            "browserRoot":"miniobrowser/tenant1/minio",
            "serverRoot":"minio/tenant1/minio"
        }

What was checked:
* login/logout;
* navigation;
* creation of buckets;
* upload/download;
* share link functionality.

Code style was validated in the way, that the changes were made is way like being inline, but not providing huge blocks of new code.

Probably this change could require some additional changes for documentation or at least readme parts.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Thanks for the PR @a-rix-mkii 

Have you looked at the following documentation
https://github.com/krishnasrinivas/cookbook/blob/68b6dab51f557ed437449104970abcf3bacf4b7b/docs/multi-tenancy-in-minio.md

**Comment by ghost** [comment]
@harshavardhana thank you for the quick reply.

Yes, this was my starting point, but didn't work for my demo setup. Splitting tenant per hostname is a bit different from using application path. Still if there is already a hostname based possible solution, it might be a good idea to not make things over complicated.

What is your opinion about cleaning up hardcoded path values around the code?

**Comment by harshavardhana** [comment]
> What is your opinion about cleaning up hardcoded path values around the code?

@a-rix-mkii hardcoded paths are generally okay since browser is embedded into the server and pretty much part of servers core. So making this configurable is not necessary. 

Now regarding the usage of Host based routing for multi-tenant access, we will discuss this internally and get back to you.

**Comment by harshavardhana** [comment]
> Now regarding the usage of Host based routing for multi-tenant access, we will discuss this internally and get back to you.

We haven't had time to discuss this yet, we will get back to you soon.  // cc @krishnasrinivas @deekoder @abperiasamy

**Comment by krishnasrinivas** [comment]
@a-rix-mkii there is a simpler solution to this. What needs to be done is remove hard coding of this:
```
constants.js:export const minioBrowserPrefix = '/minio'
```

and it should be initialised in index.js before calling `new Web()`

The value to which it should be initialised can be figured out by looking at `window.location.pathname`

There are other places where `/minio` is hardcoded which should be fixed:
```
krishna@escape:~/gocode/src/github.com/minio/minio/browser/app/js$ grep '\/minio' * -r
actions.js:    const uploadUrl = `${window.location.origin}/minio/upload/${currentBucket}/${objectName}`
components/Browse.js:          let url = `${window.location.origin}/minio/download/${currentBucket}/${encPrefix}?token=${res.token}`
components/Browse.js:        let requestUrl = location.origin + "/minio/zip?token=" + res.token
components/Browse.js:      loginButton = <a className='btn btn-danger' href='/minio/login'>Login</a>
components/Browse.js:                  <a href="https://minio.io" target="_blank"><img className="maii-logo" src={ logo } alt="" /></a>
components/BrowserDropdown.js:            <a target="_blank" href="https://github.com/minio/minio">Github <i className="fa fa-github"></i></a>
constants.js:export const minioBrowserPrefix = '/minio'
krishna@escape:~/gocode/src/github.com/minio/minio/browser/app/js$ 
```

Would you like to fix this?

I have opened an issue to track this: https://github.com/minio/minio/issues/5040

**Comment by harshavardhana** [comment]
@krishnasrinivas has submitted a new PR at #5040 @a-rix-mkii would you mind validating the PR and let us know if it works for you? - Feel free to close this PR.

**Comment by deekoder** [comment]
@a-rix-mkii  we will go ahead and close this PR. Please join us at https://github.com/minio/minio/issues/5040 to discuss further. Also we would love to send you some swag for this amazing pr. Let us know how we can reach you.

**Comment by deekoder** [comment]
ping @a-rix-mkii . Closing this PR. Please ping @belvid  we want to get in touch with you if possible.

**Comment by belvid** [comment]
@a-rix-mkii You can find me on twitter as @belvid or you can send me a private message on https://minio.slack.com/ 

Thanks for the amazing work!

**Pull request closed without merging**
