### PR TITLE
Decrypt ETag before precondition check for Copy

### PR DESCRIPTION
**Pull request by poornas**
operation

## Description

For copy with SSE encryption, the source ETag needs to be decrypted before doing a source ETag match. 
## Motivation and Context

Correctness
## Regression
 Maybe

## How Has This Been Tested?

1. Turn auto encryption on by setting MINIO_SSE_MASTER_KEY and MINIO_SSE_AUTO_ENCRYPTION. Start minio server in fs/dist mode.
2. mc cp /etc/issue myminio/testbucket/src
3. use minio-go to do a copy from testbucket/src to testbucket/dst and set the ETag match condition to src ETag. Copy should succeed.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
There is no lot more that needs to be fixed @poornas

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
More problems fixed in #7000

**Comment by poornas** [comment]
closing this, #7000 has a better fix

**Pull request closed without merging**
