### PR TITLE
Fixes misleading assume role error msgs

### LINKED ISSUE #9290: Misleading error when incorrect credentials are used with assume role
This appears to be a minio server bug rather than a client bug. I've tested against aws as well as minio. The short version is boto at least is reporting a `MalformedPolicyDocumentException` to a assume role request (that doesn't even have a policy), when the issue should be with the credentials.

## Expected Behavior

Using boto with the default AWS endpoint a `ClientError` is raised:

`botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.`

## Current Behavior

Running the same test with a local Minio deployment, boto raises a very different and misleading error message:

`botocore.errorfactory.MalformedPolicyDocumentException: An error occurred (MalformedPolicyDocument) when calling the AssumeRole operation: The request was rejected because the policy document was malformed.`

## Steps to Reproduce

1. Launch Minio locally - serving on port 9000. 
2. Run this with `python -m pytest`:

```python

import boto3

class TestAssumeRole:

    def test_create_temp_credentials_with_boto(self):
        session = boto3.Session(
            aws_access_key_id='newuser',
            aws_secret_access_key='newuser123',
            region_name='us-east-1'
        )
        sts_client = session.client('sts', endpoint_url="http://minio:9000")

        response = sts_client.assume_role(
            RoleArn="arn:xxx:xxx:xxx:xxxx",
            RoleSessionName="anything",
            # note not providing a Policy
            DurationSeconds=3000,
        )

```
3. Observe the exception.

## Context

I'm adding support for assume role to the minio-py client and I wanted to check that the minio server  behaves similar to AWS sts service. I was running tests with the boto client when I ran into this inconsistency. I actually had a `Policy` and believed the error message thinking I must have inadvertently modified my test policy, when I investigated it was actually the credentials were no longer valid.

## Regression
Not as far as I know.

## Environment

* Version used (`minio version`): Docker image was `minio/minio:RELEASE.2020-04-04T05-39-31Z`
* Environment name and version: local tests using docker compose.
* Link to your project: [wip gist for minio-py](https://gist.github.com/hardbyte/8d6261154b5c840a0f29e6d34cb181c9)

### PR DESCRIPTION
**Pull request by ebozduman**
Fixes #9290
Having invalid access key causes a misleading error message about policy during assume-role api.
S3 error message for both cases, when access key is bad and when the secret access key is bad, is the same vague error message:
```
An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.
```
In our implementation, there are 2 different error messages and it is much more clearer than the S3 message above.
If the access key is bad, the error message is :
```
An error occurred (InvalidAccessKeyId) when calling the AssumeRole operation: The access key ID you provided does not exist in our records.
```
If the secret access key is bad, the error message is :
```
An error occurred (SignatureDoesNotMatch) when calling the AssumeRole operation: The request signature we calculated does not match the signature you provided. Check your Secret Access key and signing method.
```

## Motivation and Context
To replace the misleading error message with the correct and clear version.

## How to test this PR?
Use the following  python script as it is also explained in issue #9290.

```
import boto3

class TestAssumeRole:
    def test_create_temp_credentials_with_boto(self):
        session = boto3.Session(
            # aws_access_key_id='user1',
            aws_access_key_id='newuser',
            aws_secret_access_key='mino123',
            region_name='us-east-1'
        )
        sts_client = session.client(
            'sts', endpoint_url="http://localhost:9000")
        # 'sts', endpoint_url="https://sts.amazonaws.com")
        response = sts_client.assume_role(
            RoleArn="arn:xxx:xxx:xxx:xxxx",
            RoleSessionName="anything",
            # note not providing a Policy
            # DurationSeconds=3000,
        )

t = TestAssumeRole()
t.test_create_temp_credentials_with_boto()
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b9bc60a7-4189-4a41-979b-eee0df860447) |
<a name="b9bc60a7-4189-4a41-979b-eee0df860447"></a>
### 9642-02e81c2/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32554
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 91c39d61944a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 28 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 3 seconds
(8/15) Running minio-dotnet tests ... done in 43 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 46 seconds
(10/15) Running minio-java tests ... FAILED in 6 minutes and 4 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 1409,
  "status": "FAIL",
  "error": "java.io.EOFException >>> [okio.RealBufferedSink.write(RealBufferedSink.java:115), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:78), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264), okhttp3.RealCall.execute(RealCall.java:93), io.minio.MinioClient.execute(MinioClient.java:1097), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.uploadPart(MinioClient.java:5492), io.minio.MinioClient.putObject(MinioClient.java:3740), io.minio.MinioClient.putObject(MinioClient.java:3870), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1835), FunctionalTest.runTests(FunctionalTest.java:4053), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(10/15) Running minio-js tests ... done in 51 seconds
(11/15) Running minio-py tests ... done in 4 minutes and 8 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 9 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by kannappanr** [comment]
PTAL build failure

**Comment by harshavardhana** [comment]
@ebozduman we cannot change the message in the error response, only make it compatible with error strings.

**Comment by ebozduman** [comment]
@kannappanr ,
I am looking  into the build failure.

@harshavardhana ,
Ok. I'll make the change to exactly match S3 error message in the above 2 scenarios.
I created the PR this way, because if I remember correctly, long time back when we had a conversation about S3 compatibility with @abperiasamy , he said we should definitely match S3 behavior, or if we can do, do it better than S3. Our current error messages are much better and to the point when compared to the S3 message, which just says `... invalid security token..`.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by poornas — APPROVED** [review]
LGTM

**Comment by ebozduman** [comment]
@harshavardhana 
Actually, I tested the s3 side with some other simple command, and the error message is different than I reported previously.
The correct error messages on s3 side for the simple (list objects in a bucket) command are as follows.

When the access key is bad:
```
An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
```
When the access key is bad:
```
An error occurred (SignatureDoesNotMatch) when calling the ListObjects operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```
I modified and matched the error messages on our side as above.

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#d4393343-78f3-4215-a23f-3bb5d765793e) |
<a name="d4393343-78f3-4215-a23f-3bb5d765793e"></a>
### 9642-8c43446/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31582
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cdefeaeeb6f6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 25 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 45 seconds
(8/15) Running minio-dotnet tests ... done in 42 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 2 seconds
(10/15) Running minio-java tests ... done in 2 minutes and 41 seconds
(11/15) Running minio-js tests ... FAILED in 15 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, metaData)",
  "args": "bucketName:minio-js-test-ac5ad8ba-e478-4a1e-872d-66643aa00f22, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 1113,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)"
}
(11/15) Running minio-py tests ... done in 1 minutes and 36 seconds
(12/15) Running s3cmd tests ... done in 26 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by kannappanr** [comment]
@poornas @harshavardhana Can you please review and re-approve the PR as code has been force pushed after approvals?

**Review by harshavardhana — APPROVED** [review]

**Review by poornas — APPROVED** [review]

**Pull request merged**
