### PR TITLE
Moved csvparser fuzzer to new directory

### PR DESCRIPTION
**Pull request by AdamKorcz**
## Description
This PR moves over the fuzzer for the csvparser to the `/fuzzing` directory.

Furthermore a few optimizations have been made to the fuzzer. These are:
- Removed log statements.
- Removed panics from the fuzzer.

The motivations for the two changes above are described below.

## Motivation and Context
Motivation for moving the fuzzer:
I am currently setting up continuous fuzzing on oss-fuzz's infrasctructure as per https://github.com/minio/minio/issues/10689. Go modules is causing some problems, and I have managed to get it working by moving it to `/fuzzing`. 

There are obviously trade offs with this move. The cons for doing this could be related to style, organization and structure of the project which is something I don't have a strong opinion about. Instead let me lay down some pros for having the fuzzer in `/fuzzing`:

- Looking forward, there is more data that could be added to the fuzzing efforts of minio, some of which are: 1) Documentation on running the fuzzers locally, 2) Directories with seed corpus files, 3) More fuzzers. Having all these files in a unified directory in terms of organization is an argument for the move proposed in this pr.
- At the time of writing, the integration with oss-fuzz works without any "hacky" solutions, and maintenance will be easy moving forward.

The motivation for the optimizations of the fuzzer:
Log statements will slow down the fuzzer. Considering it sends thousands of pseudo-random test inputs to the target function every second, spending resources on log statements is a waste.
Panics should not be in the the fuzzer. Instead we should either return 0 or -1.

## How to test this PR?
No tests have been provided. But I can setup the integration with oss-fuzz and use the fuzzer from this pr. If their Travis tests pass, then everything works as expected.

## Types of changes
- [x] Restructuring of files.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Comment by AdamKorcz** [comment]
Tagging @klauspost and @harshavardhana as you were part of this pr: https://github.com/minio/minio/pull/8927

**Comment by klauspost** [comment]
> Panics should not be in the the fuzzer. Instead we should either return 0 or -1.

This doesn't make sense to me. You are returning 0 which AFAIK just means the data provided isn't interesting. So in these failure cases nothing is reported unless I am mistaking. Do you have any links to documentation for this?

**Comment by AdamKorcz** [comment]
You are correct that returning 0 is to indicate to go-fuzz that the input is not interesting.

This can be found in [go-fuzz's README](https://github.com/dvyukov/go-fuzz):

> Data is a random input generated by go-fuzz, note that in most cases it is invalid. The function must return 1 if the fuzzer should increase priority of the given input during subsequent fuzzing (for example, the input is lexically correct and was parsed successfully); -1 if the input must not be added to corpus even if gives new coverage; and 0 otherwise; other values are reserved for future use.

However, the README also clearly states that throwing panics in the fuzzer is completely fine. However, the panics in the csvparser fuzzer will cause the fuzzer to stop when an invalid input is generated. This is not want we would like the fuzzer to do. Rather: We would like to tell the fuzzer that this particular input data is invalid. At some point the fuzzer will start creating valid input data if we give it enough time and give it the correct return values.

I just tested the fuzzer with the panics, and it stops after 1-2 seconds from an artificial panic (from the panics), and it would not reach the target application and test for bugs.

@klauspost Please see: I made a change from the first version of this post.

To be clear, I am not judging the hard work of anyone here. I am merely explaining the rationale for my amendments to the fuzzer.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#0a30069d-993f-4587-ae9c-a11eeb2637fe) |
<a name="0a30069d-993f-4587-ae9c-a11eeb2637fe"></a>
### 10694-75f0111/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30179
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 23fd33225d87:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 37 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 46 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 28 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 37 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 41 seconds
{
  "args": {
    "bucketName": "minio-go-test-ksbnlvx26vpgir0g",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1086,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 10 minutes and 16 seconds
(10/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 78,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 1 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 13 seconds
(12/15) Running s3select tests ... done in 37 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by klauspost** [comment]
Honestly I had forgotten about this and I don't think it was meant as a candidate for actual fuzz testing. So I think it should rather be removed since I am unsure if it provides anything valuable - most likely not something worth burning cycles on.

Sorry if it wasted your time.

**Comment by AdamKorcz** [comment]
Not a problem. 

In all honesty, I can see potential for this fuzzer to be useful. I will be happy to rewrite it, if this is desirable.

Edit: The current changes make the fuzzer run as desired, but I will be happy to optimize it as well.

**Pull request closed without merging**
