### PR TITLE
Return ETag for 0-byte object prefixes

### LINKED ISSUE #7290: Always return ETag for get object
## Expected Behavior
An ETag should always be returned when performing a get object. A lack of an ETag causes issues with 3rd-party libraries such as Stow.

## Current Behavior
No ETag is returned for 0-byte objects

### AWS S3 Behavior
```
$ touch empty

$ aws s3api put-object --bucket minio-test --key "test1/" --body empty
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\""
}

$ aws s3api get-object --bucket minio-test --key "test1/" tmp
{
    "AcceptRanges": "bytes",
    "ContentType": "binary/octet-stream",
    "LastModified": "Mon, 25 Feb 2019 22:02:32 GMT",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "Metadata": {}
}
```

### Minio Behavior
```
$ touch empty

$ aws s3api --endpoint ${AWS_ENDPOINT} put-object --bucket minio-test --key "test1/" --body empty
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\""
}

$ aws --endpoint ${AWS_ENDPOINT} s3api get-object --bucket minio-test --key "test1/" tmp
{
    "AcceptRanges": "bytes",
    "LastModified": "Mon, 01 Jan 0001 00:00:00 GMT",
    "ContentLength": 0,
    "Metadata": {}
}
```

Here are the raw headers from Minio:
```
{'Content-Length': '0', 'X-Xss-Protection': '1; mode=block', 'X-Minio-Deployment-Id': 'f13016da-356d-4da9-8c1d-71cacb96ee44', 'Content-Security-Policy': 'block-all-mixed-content', 'Accept-Ranges': 'bytes', 'Vary': 'Origin', 'Server': 'Minio/RELEASE.2019-02-12T21-58-47Z', 'Last-Modified': 'Mon, 01 Jan 0001 00:00:00 GMT', 'X-Amz-Request-Id': '1586BAB99E962434', 'Date': 'Mon, 25 Feb 2019 22:07:08 GMT'}
```
## Your Environment
* Version used (`minio version`): 2019-02-12T21:58:47Z

### PR DESCRIPTION
**Pull request by poornas**
Fixes: #7290

## Regression
 No

## How Has This Been Tested?

the issue lists repro steps
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by ntolia** [comment]
Thank you for the quick fix. I verified that this does address the underlying issue.

**Review by donatello — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
