### PR TITLE
Fix ListObjectsV2 for gateway encryption mode

### LINKED ISSUE #7468: [encryption] aws-sdk-php mint test goes into infinite loop with minio gateway s3
## Expected Behavior
No infinite loop

## Current Behavior
Start `minio server` with encryption on and also `minio gateway s3` also to inherit these variables.

```
MINIO_SSE_MASTER_KEY=my-minio-key:6a201e6c403a699aed709a81b3075cb972149836f7656255ee588bc8de3d38a2
MINIO_SECRET_KEY=minio123
MINIO_ACCESS_KEY=minio
minio server ~/test
```

```
MINIO_SSE_AUTO_ENCRYPTION=on
MINIO_SSE_MASTER_KEY=my-minio-key:6a201e6c403a699aed709a81b3075cb972149836f7656255ee588bc8de3d38a2
MINIO_SECRET_KEY=minio123
MINIO_ACCESS_KEY=minio
minio gateway --address ":9001" s3 http://localhost:9000
```

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Just run mint tests with above configuration pointing to gateway

```
~ docker run --rm --net=host -e SERVER_ENDPOINT=localhost:9001 -e ACCESS_KEY=minio -e SECRET_KEY=minio123 -e ENABLE_HTTPS=0 -e MINT_MODE=full minio/mint:edge aws-sdk-php
```

You will see a CPU spike and high usage.

## Context
Double encryption bug

## Regression
Perhaps not sure.

## Your Environment
master branch

### PR DESCRIPTION
**Pull request by poornas**
Fixes #7468 by setting NextContinuationToken only if list is
truncated

## Description

NextContinuationToken was being set even when the end of list is reached. When end of list is reached IsTruncated should be false and NextContinuationToken ""
## Motivation and Context

Most clients decide whether to continue listing based on IsTruncated returning true. aws-sdk-php seems to be using the NextContinuationToken to decide whether to send ListObjectsV2 call for continuing to iterate through the list. This results in a infinite loop on Mint for aws-sdk-php when gateway double encryption mode is on.
## Regression
 No ( incorrectly implemented)

## How Has This Been Tested?

See issue description - rerun Mint for aws-sdk-php with this fix. Also, generic `mc ls` tests to ensure there are no side-effects
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — DISMISSED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#df5accfa-7b17-4098-8577-60535e4c0c81) |
| mint-compression-dist-xl.sh | :x: [more...](#169b2722-7d24-482f-a5be-bda6d782366e) |
| mint-dist-xl.sh | :x: [more...](#92922690-8aa0-45ec-a2fc-71ca677609ac) |
<a name="169b2722-7d24-482f-a5be-bda6d782366e"></a>
### 7491-7663926/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32615
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ab5eeec279ac:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-u1r4mfcobztsgg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120179,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1592A7F6118A4FF6, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="df5accfa-7b17-4098-8577-60535e4c0c81"></a>
### 7491-7663926/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30258
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1c725959ab6e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 42 seconds
{
  "name": "mc",
  "duration": "100108",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-22212 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-5487/mc-test-object-22458  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-5487/mc-test-object-22458`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Session safely terminated. To resume session `mc session resume zfDfEUKE`"
}

Executed 6 out of 14 tests successfully.
```
<a name="92922690-8aa0-45ec-a2fc-71ca677609ac"></a>
### 7491-7663926/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30169
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6a0c853e0650:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 17 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 2 minutes and 4 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 minutes and 15 seconds
(5/14) Running awscli tests ... done in 11 minutes and 33 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 2 minutes and 22 seconds
(8/14) Running minio-dotnet tests ... done in 4 minutes and 56 seconds
(9/14) Running minio-go tests ... done in 6 minutes and 21 seconds
(10/14) Running minio-java tests ... FAILED in 10 minutes and 4 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 554276,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=XMinioWriteQuorum, message=Multiple disks failures, unable to write data., bucketName=minio-java-test-3njhvlh, objectName=minio-java-test-2v81b19, resource=/minio-java-test-3njhvlh/minio-java-test-2v81b19, requestId=1592A9E905B504BC, hostId=6ced79a6-5704-4c01-b4ee-697b0ead7f76)\nrequest={method=PUT, url=http://72.28.97.54:30169/minio-java-test-3njhvlh/minio-java-test-2v81b19, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.54:30169\nUser-Agent: Minio (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20190405T191359Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190405/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: Minio/DEVELOPMENT.2019-04-05T18-23-30Z\nVary: Origin\nX-Amz-Request-Id: 1592A9E905B504BC\nX-Minio-Deployment-Id: 6ced79a6-5704-4c01-b4ee-697b0ead7f76\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Apr 2019 19:16:10 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1190), io.minio.MinioClient.execute(MinioClient.java:1056), io.minio.MinioClient.executePut(MinioClient.java:1391), io.minio.MinioClient.executePut(MinioClient.java:1413), io.minio.MinioClient.putObject(MinioClient.java:3986), io.minio.MinioClient.putObject(MinioClient.java:4029), io.minio.MinioClient.putObject(MinioClient.java:3570), FunctionalTest.listObject_test5(FunctionalTest.java:1462), FunctionalTest.runTests(FunctionalTest.java:2985), FunctionalTest.main(FunctionalTest.java:3121)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by poornas** [comment]
pushed again for travis failure

**Review by harshavardhana — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]

**Comment by kannappanr** [comment]
@poornas Can you please fix Travis failure?

**Comment by poornas** [comment]
@kannappanr, CI build passed

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
