### PR TITLE
pre-allocate memory by default

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request, I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
enable pre-allocate by default

## Motivation and Context
EC memory can be enabled by default

## How to test this PR?
Nothing special CI/CD should test everything

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by jiuker — APPROVED** [review]

**Review by shtripat — APPROVED** [review]
lgtm

**Review by Praveenrajmani — APPROVED** [review]

**Review by klauspost — COMMENTED** [review]
Why is this even an option?

**Comment by harshavardhana** [comment]
> Why is this even an option?

To turn-it off in-case its necessary? @klauspost

**Comment by klauspost** [comment]
@harshavardhana Yeah, but if they can't handle it at startup they risk crashing under load.

**Comment by harshavardhana** [comment]
> @harshavardhana Yeah, but if they can't handle it at startup they risk crashing under load.

the option is removed @klauspost

**Review by shtripat — APPROVED** [review]

**Pull request merged**
