### PR TITLE
Remove delayIsLeaf requirement simplify ListObjects further

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Remove delayIsLeaf requirement simplify ListObjects further

## Motivation and Context
Simplification before bringing performance changes

## Regression
No

## How Has This Been Tested?
This PR changes a behavior about not listing empty directories

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#f3771a9b-0815-42c5-a4c3-588c5598b7b9) |
| mint-large-bucket.sh | :x: [more...](#3300c071-7add-4601-aaf7-24acfd25661c) |
| mint-compression-dist-xl.sh | :x: [more...](#3b2fa3b3-b7ec-4da4-8546-9830cb12486e) |
<a name="3b2fa3b3-b7ec-4da4-8546-9830cb12486e"></a>
### 7593-9b51108/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32729
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b4b69cdc33dd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cc4fc546f858",
    "Object": "obj1"
  },
  "duration": "344",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.61:32729/aws-sdk-php-5cc4fc546f858/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.61:32729/aws-sdk-php-5cc4fc546f858/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cc4fc546f858</BucketName><Resource>/aws-sdk-php-5cc4fc546f858/obj1-copy-0</Resource><RequestId>15997DDAC8F6C08B</RequestId><HostId>ac3b0c8c-d10d-455d-becc-828494b1754a</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="f3771a9b-0815-42c5-a4c3-588c5598b7b9"></a>
### 7593-9b51108/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30938
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 79d9c3ec28dd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ujie0fxcvty43j",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 326,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30938/aws-sdk-go-test-ujie0fxcvty43j: dial tcp 72.28.97.60:30938: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="3300c071-7add-4601-aaf7-24acfd25661c"></a>
### 7593-9b51108/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30974
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cf0b584806d1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-sf22wsq2a4zgq9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360016,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15997E31BEAB6FFE, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#d0082013-c7a1-4d6e-8e1b-f3cfa5405ab4) |
| mint-large-bucket.sh | :x: [more...](#e4604869-b2be-4926-aff9-e28d32b2a438) |
| mint-compression-dist-xl.sh | :x: [more...](#f1a1647f-8bee-4b59-b112-f52dcacf3d2a) |
| mint-dist-xl.sh | :x: [more...](#ae30e813-93da-48c2-933e-4c395547d7de) |
<a name="ae30e813-93da-48c2-933e-4c395547d7de"></a>
### 7593-b10a267/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30483
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b1763c7ffa51:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 33 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 33 seconds
(8/14) Running minio-dotnet tests ... done in 45 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 49 seconds
(10/14) Running minio-java tests ... done in 3 minutes and 22 seconds
(11/14) Running minio-js tests ... done in 45 seconds
(12/14) Running minio-py tests ... FAILED in 12 minutes and 9 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "bucket_name": "minio-py-test-5fbfaddc-b83a-4dab-9e28-c3d2bf14b041",
    "object_name": "9856c0d9-daad-4687-ac9c-33d526c6ddf3"
  },
  "duration": 255,
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "name": "minio-py:test_presigned_get_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```
<a name="d0082013-c7a1-4d6e-8e1b-f3cfa5405ab4"></a>
### 7593-b10a267/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32278
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a53fd0bfea7b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-uvw4b6iw4fht39",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 322,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:32278/aws-sdk-go-test-uvw4b6iw4fht39: dial tcp 72.28.97.53:32278: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="e4604869-b2be-4926-aff9-e28d32b2a438"></a>
### 7593-b10a267/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30879
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 59db63fee9d6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-l6s323yabpl2jx",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159982D28FF235E5, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f1a1647f-8bee-4b59-b112-f52dcacf3d2a"></a>
### 7593-b10a267/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30493
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d797386a6706:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cc5103589674",
    "Object": "obj1"
  },
  "duration": "671",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.61:30493/aws-sdk-php-5cc5103589674/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.61:30493/aws-sdk-php-5cc5103589674/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cc5103589674</BucketName><Resource>/aws-sdk-php-5cc5103589674/obj1-copy-0</Resource><RequestId>1599827BC485F304</RequestId><HostId>a63edf16-586c-440f-858a-a48ee7220dda</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_exclamation_mark: [more...](#639cb271-820f-4c6b-9e69-b1178f6e4afa) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#a65b0e69-8e75-4065-8318-3703355c62fb) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#c1e42299-74fa-4021-97c4-c8885f00d053) |
| mint-compression-dist-xl.sh | :heavy_exclamation_mark: [more...](#62398625-b159-43ed-b573-908f5454e8d1) |
| mint-compression-fs.sh | :heavy_exclamation_mark: [more...](#6c37fd30-570e-47a5-8a9b-f32a42af8f14) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#caba2de4-b3ee-415e-a7bc-a2fec20e06e9) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#9e715177-f194-463b-b577-be2e3b3d1d0e) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#80275720-8f51-44ef-be69-8675f31e43b4) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#0ac581f4-3467-4e5e-8d4e-a4763ad12211) |
<a name="6c37fd30-570e-47a5-8a9b-f32a42af8f14"></a>
### 7593-9de29e9/mint-compression-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="80275720-8f51-44ef-be69-8675f31e43b4"></a>
### 7593-9de29e9/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="c1e42299-74fa-4021-97c4-c8885f00d053"></a>
### 7593-9de29e9/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="caba2de4-b3ee-415e-a7bc-a2fec20e06e9"></a>
### 7593-9de29e9/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="62398625-b159-43ed-b573-908f5454e8d1"></a>
### 7593-9de29e9/mint-compression-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="9e715177-f194-463b-b577-be2e3b3d1d0e"></a>
### 7593-9de29e9/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0ac581f4-3467-4e5e-8d4e-a4763ad12211"></a>
### 7593-9de29e9/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a65b0e69-8e75-4065-8318-3703355c62fb"></a>
### 7593-9de29e9/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="639cb271-820f-4c6b-9e69-b1178f6e4afa"></a>
### 7593-9de29e9/mint-compression-xl.sh.xtrace:
```
DISABLED TIME BEING
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_exclamation_mark: [more...](#9d93772a-277a-409f-9754-6fcceb294ae0) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#bd4075f5-6f75-435a-8551-fb36ae81c482) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#a19d7383-43df-45f0-90e9-f76da9c1157b) |
| mint-compression-dist-xl.sh | :heavy_exclamation_mark: [more...](#189ea9ad-5eca-4f1c-bbc6-4b56dc818d5a) |
| mint-compression-fs.sh | :heavy_exclamation_mark: [more...](#4e1cc80f-c33d-41b8-81a4-19cb412175f7) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#fdbb59c7-54ae-40fe-87c9-fb2981871021) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#3651af77-3709-4c84-bdc8-28c87c6252a8) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#4f56d0e9-ca72-4197-8f81-f0cacef7ba12) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#5677e5d7-e7c8-4db0-85cc-74673b9d6585) |
<a name="9d93772a-277a-409f-9754-6fcceb294ae0"></a>
### 7593-be5c688/mint-compression-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="fdbb59c7-54ae-40fe-87c9-fb2981871021"></a>
### 7593-be5c688/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="5677e5d7-e7c8-4db0-85cc-74673b9d6585"></a>
### 7593-be5c688/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="4f56d0e9-ca72-4197-8f81-f0cacef7ba12"></a>
### 7593-be5c688/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="189ea9ad-5eca-4f1c-bbc6-4b56dc818d5a"></a>
### 7593-be5c688/mint-compression-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a19d7383-43df-45f0-90e9-f76da9c1157b"></a>
### 7593-be5c688/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="bd4075f5-6f75-435a-8551-fb36ae81c482"></a>
### 7593-be5c688/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="3651af77-3709-4c84-bdc8-28c87c6252a8"></a>
### 7593-be5c688/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="4e1cc80f-c33d-41b8-81a4-19cb412175f7"></a>
### 7593-be5c688/mint-compression-fs.sh.xtrace:
```
DISABLED TIME BEING
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Can this be reviewed ? This PR blocks my listing refactor

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#484683cf-526d-4cce-aa01-1166c28f7594) |
<a name="484683cf-526d-4cce-aa01-1166c28f7594"></a>
### 7593-b44c3aa/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30211
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e1bb953641f9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-g2nqet3yiu0elt",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360015,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159AB640D77CFE8E, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by kannappanr — APPROVED** [review]
LGTM.

**Review by krishnasrinivas — APPROVED** [review]

**Pull request merged**
