### PR TITLE
fix: load certs on windows from the registry

### LINKED ISSUE #11007: Azure gateway mode is broken on v2020-11-19T23:48:16Z
Steps to reproduce
1. Get connection string for existing azure storage (for example, mystorage/my_key).
2. Download current mino release from https://dl.min.io/server/minio/release/windows-amd64/minio.exe
3. In command line, powershell:
```ps
$env:MINIO_ACCESS_KEY="mystorage" 
$env:MINIO_SECRET_KEY="my_key"
 .\minio.exe gateway azure --address :9008
```
4. open in browser http://localhost:9008
5. Use credentials from above to login, attempt to make a bucket
-or- (C# minio client)
4, 5:
```
	client = new MinioClient(
		options.Endpoint, options.AccessKey,
		options.SecretKey, options.SessionToken);
	if (!await client.BucketExistsAsync(BucketName))
		await client.MakeBucketAsync(BucketName);
```
6. Bucket creation fails, minio server output:
```
API: WebListBuckets()
Time: 15:51:41 MSK 12/01/2020
DeploymentID: c149d95a-7aea-4d13-a6bf-33508eb715c0
RemoteHost: 127.0.0.1
Host: localhost:9008
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
Error: Get "https://mystorage.blob.core.windows.net?comp=list&timeout=1501": x509: certificate signed by unknown authority (*url.Error)
       5: cmd\api-errors.go:1995:cmd.toAPIErrorCode()
       4: cmd\api-errors.go:2020:cmd.toAPIError()
       3: cmd\web-handlers.go:2279:cmd.toWebAPIError()
       2: cmd\web-handlers.go:2147:cmd.toJSONError()
       1: cmd\web-handlers.go:359:cmd.(*webAPIHandlers).ListBuckets()

```
-or-
```
API: GetBucketLocation(bucket=my-bucket
Time: 15:39:36 MSK 12/01/2020
DeploymentID: 4a3ec9a7-473e-4a14-bc2e-7685e7ab693c
RequestID: 164C980701F7152C
RemoteHost: 127.0.0.1
Host: localhost:9008
UserAgent: MinIO (Microsoft Windows 10.0.19041;X64) minio-dotnet/1.0.9
Error: Get "https://mystorage.blob.core.windows.net?comp=list&prefix=my-bucket&timeout=1501": x509: certificate signed by unknown authority (*url.Error)
       4: cmd\api-errors.go:1995:cmd.toAPIErrorCode()
       3: cmd\api-errors.go:2020:cmd.toAPIError()
       2: cmd\bucket-handlers.go:179:cmd.objectAPIHandlers.GetBucketLocationHandler()
       1: net\http\server.go:2042:http.HandlerFunc.ServeHTTP()
```

minio version:
```
VERSION
2020-11-19T23:48:16Z
PLATFORM
Host: IgorPC | OS: windows | Arch: amd64
RUNTIME
Version: go1.15.5 | CPUs: 12
```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: load certs on windows from the registry

## Motivation and Context
fixes #11007

## How to test this PR?
As per #11007 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Comment by klauspost** [comment]
```
-->    darwin/amd64:github.com/minio/minio
# github.com/minio/minio/pkg/certs
pkg/certs/ca-certs.go:29:16: undefined: loadSystemRoots
```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#067653c3-02b8-477f-a4f5-ae7e41901a4d) |
| mint-erasure.sh | :x: [more...](#a93e6d31-6cd2-48cd-bd93-34dc8b7a6f7d) |
<a name="067653c3-02b8-477f-a4f5-ae7e41901a4d"></a>
### 11016-0cf74f7/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32244
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp afc8e1b695c0:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 36 seconds
(4/15) Running aws-sdk-ruby tests ... done in 22 seconds
(5/15) Running awscli tests ... done in 2 minutes and 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 48 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 53 seconds
(9/15) Running minio-go tests ... done in 7 minutes and 0 seconds
(10/15) Running minio-java tests ... FAILED in 9 minutes and 4 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 175,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:bf193891-f01e-00a1-5287-c82375000000\nTime:2020-12-02T08:47:51.7994414Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'obdFmLA09xS2bAzM6kKdofr+eS5WNjrwhiPsiXBPSA8=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:db5f8704-54c5-47b9-76b2-73378a5a71b2\nx-ms-date:Wed, 02 Dec 2020 08:47:51 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-54q976/minio-java-test-q63rb6\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-54q976/minio-java-test-q63rb6?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-02T08:15:10Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [db5f8704-54c5-47b9-76b2-73378a5a71b2]\n   X-Ms-Date: [Wed, 02 Dec 2020 08:47:51 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1090]\n   Content-Type: [application/xml]\n   Date: [Wed, 02 Dec 2020 08:47:51 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [bf193891-f01e-00a1-5287-c82375000000]\n\n\n, bucketName = minio-java-test-54q976, objectName = minio-java-test-q63rb6, resource = /minio-java-test-54q976/minio-java-test-q63rb6, requestId = 164CDA0294A91649, hostId = be3f50c3-8ce0-4732-9f06-1ff1ad01ffaf)\nrequest={method=PUT, url=http://minio-dev8.minio.io:32244/minio-java-test-54q976/minio-java-test-q63rb6, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev8.minio.io:32244\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201202T084751Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201202/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3078\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164CDA0294A91649\nX-Xss-Protection: 1; mode=block\nDate: Wed, 02 Dec 2020 08:47:51 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 41 seconds
(11/15) Running minio-py tests ... done in 19 minutes and 14 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 18 seconds
(13/15) Running s3select tests ... done in 58 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="a93e6d31-6cd2-48cd-bd93-34dc8b7a6f7d"></a>
### 11016-0cf74f7/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30827
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a45dba33d2c9:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 6 seconds
{
  "name": "awscli",
  "duration": 62502,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30827 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-10359/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-10359/datafile-0-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-10359/datafile-1-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-10359/datafile-100-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-10359/datafile-1-bupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-10359/datafile-33-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-10359/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-10359/datafile-1.03-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-10359/datafile-5-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-10359/datafile-6-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-10359/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-10359/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-10359/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-10359/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-10359/datafile-129-MBupload failed: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-10359/datafile-10-kB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 50 seconds
(7/15) Running minio-dotnet tests ... done in 56 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 34 seconds
(9/15) Running minio-java tests ... done in 47 seconds
(10/15) Running minio-js tests ... done in 47 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 10 seconds
(12/15) Running s3cmd tests ... done in 17 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by klauspost — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#e1e61022-3232-4c35-a458-95fce9bc9753) |
<a name="e1e61022-3232-4c35-a458-95fce9bc9753"></a>
### 11016-5fde735/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32174
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6afdc6a961a5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 37 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 3 minutes and 13 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 39 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 55 seconds
(9/15) Running minio-go tests ... FAILED in 5 minutes and 16 seconds
{
  "args": {
    "bucketName": "minio-go-test-zmxafeu6ir12try3",
    "objectName": "94aw6vssaewkdtbtrbqpyem5r1xxrj"
  },
  "duration": 919,
  "error": "EOF",
  "function": "GetObject(bucketName, objectName)",
  "message": "ReadAt failed",
  "name": "minio-go: testGetObjectReadAtFunctional",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 9 minutes and 8 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 175,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:16036e03-401e-00de-7291-c8bd47000000\nTime:2020-12-02T10:00:17.9204585Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request '5mUoIUd/+mNJdGSARNEUHr2QBHfxdJwro1UmJngqVqo=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:93cc886e-aad4-4799-5a19-6ab06826a36b\nx-ms-date:Wed, 02 Dec 2020 10:00:17 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-2c0f4q8/minio-java-test-lbnkt3\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-2c0f4q8/minio-java-test-lbnkt3?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-02T09:29:05Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [93cc886e-aad4-4799-5a19-6ab06826a36b]\n   X-Ms-Date: [Wed, 02 Dec 2020 10:00:17 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Wed, 02 Dec 2020 10:00:17 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [16036e03-401e-00de-7291-c8bd47000000]\n\n\n, bucketName = minio-java-test-2c0f4q8, objectName = minio-java-test-lbnkt3, resource = /minio-java-test-2c0f4q8/minio-java-test-lbnkt3, requestId = 164CDDF67C64328A, hostId = 31a08512-0824-4ce4-8586-3519d400a955)\nrequest={method=PUT, url=http://minio-dev7.minio.io:32174/minio-java-test-2c0f4q8/minio-java-test-lbnkt3, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev7.minio.io:32174\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201202T100017Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201202/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164CDDF67C64328A\nX-Xss-Protection: 1; mode=block\nDate: Wed, 02 Dec 2020 10:00:17 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 2 minutes and 39 seconds
(10/15) Running minio-py tests ... done in 18 minutes and 39 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 24 seconds
(12/15) Running s3select tests ... done in 1 minutes and 0 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
