### PR TITLE
Fix Gateway startup sequence to populate etcd with bucket info

### PR DESCRIPTION
**Pull request by nitisht**
## Description
Fix Gateway startup sequence to populate etcd with bucket info

## Motivation and Context
When a existing gateway deployment starts up in Federated mode, it needs to 
import existing buckets to the etcd server.

## Regression
No

## How Has This Been Tested?
- Start MinIO Gateway mode
- Create multiple buckets
- Enable etcd and start a federated setup 
- You should be able to see the old buckets created before federated setup

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#79132168-bc35-4b0a-85ca-2981a5128530) |
| mint-large-bucket.sh | :x: [more...](#1868995f-e19d-44c1-b4ae-1711ce0e7811) |
<a name="79132168-bc35-4b0a-85ca-2981a5128530"></a>
### 7686-46259ff/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31363
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9417b3dbcee0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ni4vroyea50rk3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360010,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A15250EBD0E13F, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="1868995f-e19d-44c1-b4ae-1711ce0e7811"></a>
### 7686-46259ff/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31870
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4cf65fa794bd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 4 seconds
(4/14) Running aws-sdk-ruby tests ... done in 19 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 30 seconds
{
  "name": "mc",
  "duration": "79261",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-3044 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-7282  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-7282/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-7282/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-7282/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-7282/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-7282/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-7282/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-7282/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-7282/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-7282/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-7282/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-7282/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-7282/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-7282/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-7282/datafile-5-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 278.99 MiB, Speed: 3.52 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Review by poornas — APPROVED** [review]
LGTM

**Comment by kannappanr** [comment]
@nitisht Can you check why 
```
(7/14) Running mc tests ... FAILED in 2 minutes and 30 seconds
{
  "name": "mc",
  "duration": "79261",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-3044 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-7282  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-7282/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-7282/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-7282/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-7282/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-7282/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-7282/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-7282/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-7282/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-7282/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-7282/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-7282/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-7282/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-7282/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-7282/datafile-5-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 278.99 MiB, Speed: 3.52 MiB/s"
}

```
this error occurs?

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by nitisht** [comment]
@kannappanr it passed this time. can we merge the fix?

**Pull request merged**
