### PR TITLE
skip lookup the location when put object and enable worm.

### PR DESCRIPTION
**Pull request by taozix**
## Description
skip lookup the location when put object and enable worm.

## Types of changes
- make put object more effective after cluster expanding when worm enabled

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
This is an incorrect approach @taozix you are willfully allowing duplicate objects to be created when the worm is enabled - this is not the correct approach.

Before sending a PR for intricate code paths, please open a GitHub issue or talk to us at https://slack.min.io

**Comment by taozix** [comment]
WORM not allowed to create duplicate objects, so it's no need to check whether New object already exists in previous zones after expanding.

**Comment by harshavardhana** [comment]
> WORM not allowed to create duplicate objects, so it's no need to check whether New object already exists in previous zones after expanding.

Such optimizations need to cater for retention, legal-hold / object -lock as well not just Global WORM.  We don't need to make such optimizations without a comprehensive fix @taozix

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6862e3ea-4458-4852-86ca-a696dac5a6d5) |
| mint-gateway-azure.sh | :x: [more...](#281781b7-562e-4a14-8f5b-78f8c4a4dd10) |
<a name="281781b7-562e-4a14-8f5b-78f8c4a4dd10"></a>
### 9043-039a2a1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32450
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3f4e2ab2eb90:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 9 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 23 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 22 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/14) Running minio-go tests ... FAILED in 15 minutes and 59 seconds
{
  "args": {
    "bucketName": "minio-go-test-m2jjk5hg3qwrspza",
    "objectName": "y40yo0uq9eyxekh9vhzh1uj2sp4r41"
  },
  "duration": 99652,
  "error": "Get http://72.28.97.58:32450/minio-go-test-m2jjk5hg3qwrspza/y40yo0uq9eyxekh9vhzh1uj2sp4r41: Connection closed by foreign host http://72.28.97.58:32450/minio-go-test-m2jjk5hg3qwrspza/y40yo0uq9eyxekh9vhzh1uj2sp4r41. Retry again.",
  "function": "GetObject(bucketName, objectName)",
  "message": "ReadAt failed",
  "name": "minio-go: testGetObjectReadAtWhenEOFWasReached",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="6862e3ea-4458-4852-86ca-a696dac5a6d5"></a>
### 9043-039a2a1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32727
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5c5729d7534c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qpnad3jovqp0lm",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120305,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32727/aws-sdk-go-test-qpnad3jovqp0lm: dial tcp 72.28.97.55:32727: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request closed without merging**
