### PR TITLE
ilm: Fix x-amz-expiration header evaluation

### PR DESCRIPTION
**Pull request by krisis**
## Description
SetPredictionHeaders doesn't set x-amz-expiration headers for upcoming expiration/transition lifecycle events. This was a regression introduced in https://github.com/minio/minio/pull/15812.

## How to test this PR?
1. Make bucket and import the following lifecycle policy document
```
{
  "Rules": [
    {
      "ID": "expire-date-subfolders",
      "Status": "Enabled",
      "Expiration": {
        "Days": 1
      },
      "Filter": {
        "Prefix": "prefix1"
      }
    }
  ]
}

```
2. Upload an object onto the prefix which has an Expiration action rule enabled.
3. `mc stat ALIAS/bucket/prefix1/object-name` should have `Expiration` set to the corresponding date of expiry.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here) PR #15812 
- [x] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Does this affect how the expiration happens? @krisis

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by krisis** [comment]
> Does this affect how the expiration happens? @krisis

No, this only affects the x-amz-expiration header set during HeadObject.

**Pull request merged**
