### PR TITLE
add disk.Close() in healFreshDisk to indicate idiomatic flow of code

### PR DESCRIPTION
**Pull request by jiuker**
cmd/background-newdisks-heal-ops.go:395
```go
	for {
		select {
		case <-ctx.Done():
			return
		case <-diskCheckTimer.C:
			healDisks := globalBackgroundHealState.getHealLocalDiskEndpoints()
			if len(healDisks) == 0 {
				// Reset for next interval.
				diskCheckTimer.Reset(defaultMonitorNewDiskInterval)
				continue
			}

			// Reformat disks immediately
			_, err := z.HealFormat(context.Background(), false)
			if err != nil && !errors.Is(err, errNoHealRequired) {
				logger.LogIf(ctx, err)
				// Reset for next interval.
				diskCheckTimer.Reset(defaultMonitorNewDiskInterval)
				continue
			}

			for _, disk := range healDisks {
				go func(disk Endpoint) {
					globalBackgroundHealState.markDiskForHealing(disk)
					err := healFreshDisk(ctx, z, disk)
					if err != nil {
						printEndpointError(disk, err, false)
						return
					}
					// Only upon success pop the healed disk.
					globalBackgroundHealState.popHealLocalDisks(disk)
				}(disk)
			}

			// Reset for next interval.
			diskCheckTimer.Reset(defaultMonitorNewDiskInterval)
		}
	}
```
cmd/erasure-sets.go:119
```go
// Initializes a new StorageAPI from the endpoint argument, returns
// StorageAPI and also `format` which exists on the disk.
func connectEndpoint(endpoint Endpoint) (StorageAPI, *formatErasureV3, error) {
	disk, err := newStorageAPI(endpoint, false)
	if err != nil {
		return nil, nil, err
	}

	format, err := loadFormatErasure(disk)
	if err != nil {
		if errors.Is(err, errUnformattedDisk) {
			info, derr := disk.DiskInfo(context.TODO())
			if derr != nil && info.RootDisk {
				return nil, nil, fmt.Errorf("Drive: %s is a root drive", disk)
			}
		}
		return nil, nil, fmt.Errorf("Drive: %s returned %w", disk, err) // make sure to '%w' to wrap the error
	}

	return disk, format, nil
}
```
When every `healFreshDisk()` call, client will be new every time.But no where to Close()

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]

**Comment by harshavardhana** [comment]
This doesn't really fix anything other than simply calling restClient.Close() which is simply updating atomic value to closed. Mostly this is just a cosmetic change

**Comment by jiuker** [comment]
> This doesn't really fix anything other than simply calling restClient.Close() which is simply updating atomic value to closed. Mostly this is just a cosmetic change

@harshavardhana Yes,it is.But when we add more struct field which need to be closed(etc,os.File).It's useful.

**Comment by harshavardhana** [comment]
> @harshavardhana Yes,it is.But when we add more struct field which need to be closed(etc,os.File).It's useful.

yeah that will never happen @jiuker this is not what the Close() is meant for, the PR itself is harmless though.

**Comment by harshavardhana** [comment]
updated the PR title to make it more relevant.

**Pull request merged**
