### PR TITLE
add windows port allot by "netsh dynamicport"

### PR DESCRIPTION
**Pull request by yanggangtony**
## How to test this PR?
Fixes [#](https://github.com/minio/minio/issues/15888)15888

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [✔️] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :x: [more...](#6707829e-1c1d-41ee-b312-4134ca011e00) |
<a name="6707829e-1c1d-41ee-b312-4134ca011e00"></a>
### 15986-bc2eb24/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.21:32453
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 5917b9ffa8fc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 58 seconds
(9/14) Running minio-java tests ... FAILED in 32 seconds
{
  "name": "minio-java",
  "function": "getObjectRetention()",
  "duration": 81,
  "status": "FAIL",
  "error": "java.time.format.DateTimeParseException: Text '2022-11-02T11:33:39.4Z' could not be parsed at index 19 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioAsyncClient.lambda$getObjectRetention$35(MinioAsyncClient.java:1738), java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642), java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506), java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073), io.minio.S3Base$1.onResponse(S3Base.java:559), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 53 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 52 seconds
(11/14) Running s3cmd tests ... done in 18 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by vadmeste** [comment]
@yanggangtony I think it is better if you add this to '.github/workflows/go-lint.yml'. I will fix 'go-lint.yml' name later.

**Comment by klauspost** [comment]
CI reports:
```
2022-11-01T11:50:17.6170914Z === RUN   TestHTTPListenerAddr
2022-11-01T11:50:17.6171167Z windows run 'netsh int ipv4 set dynamicport tcp'  Error:  exit status 1
2022-11-01T11:50:17.6171362Z --- FAIL: TestHTTPListenerAddr (1.59s)
```

**Comment by yanggangtony** [comment]
> @yanggangtony I think it is better if you add this to '.github/workflows/go-lint.yml'. I will fix 'go-lint.yml' name later.
@klauspost 

thanks , I will update it. and test CI

**Comment by yanggangtony** [comment]
@klauspost @vadmeste 
Hi , Could you tell me how to trigger the CI? 
I just push --force the code , but the ci have not any feedback..

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by vadmeste** [comment]
@yanggangtony 'Linters and Tests' is already retriggered when you updated your PR and is passed. There are other issues out of the scope of this PR. We will merge this PR when all tests succeed

**Comment by yanggangtony** [comment]
>

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by yanggangtony** [comment]
> @yanggangtony 'Linters and Tests' is already retriggered when you updated your PR and is passed. There are other issues out of the scope of this PR. We will merge this PR when all tests succeed

OK,thanks to explain it.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
