### PR TITLE
STS call should be rejected for missing policies

### LINKED ISSUE #12055: MinIO crashes after AssumeRole if user is using a policy that doesn't exists
## Expected Behavior
MinIO should not crash

## Current Behavior

MinIO is crashing

## Possible Solution

Validate array size when length is 0

## Steps to Reproduce (for bugs)

1. create a user
2. assign policy to that user
3. delete the policy
4. Try to generate STS credentials via AssumeRole, ie:

```
			opts := credentials.STSAssumeRoleOptions{
				AccessKey:       accessKey,
				SecretKey:       secretKey,
				Location:        location,
			}
			stsAssumeRole := &credentials.STSAssumeRole{
				STSEndpoint: MinioEndpoint,
				Options:     opts,
			}
			consoleSTSWrapper := consoleSTSAssumeRole{stsAssumeRole: stsAssumeRole}
			return credentials.New(consoleSTSWrapper), nil
```

You will see:

```
2021-04-14 17:37:33.079027 I | http: panic serving [::1]:53845: runtime error: index out of range [0] with length 0
goroutine 842 [running]:
net/http.(*conn).serve.func1(0xc000e11360)
        net/http/server.go:1824 +0x153
panic(0x2a11440, 0xc001108570)
        runtime/panic.go:971 +0x499
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0xc009e84400, 0x33ec3b0, 0xc0004420e0)
        github.com/minio/minio/cmd/generic-handlers.go:597 +0x1cc
panic(0x2a11440, 0xc001108570)
        runtime/panic.go:965 +0x1b9
github.com/minio/minio/cmd.(*IAMSys).SetTempUser(0xc000097140, 0xc001108558, 0x14, 0xc001108558, 0x14, 0xc008b85fb0, 0x28, 0x0, 0xed8098f32, 0x0, ...)
        github.com/minio/minio/cmd/iam.go:861 +0xbba
github.com/minio/minio/cmd.(*stsAPIHandlers).AssumeRole(0x40cfba0, 0x33e9920, 0xc000e114a0, 0xc009e84600)
        github.com/minio/minio/cmd/sts-handlers.go:238 +0x918
net/http.HandlerFunc.ServeHTTP(...)
        net/http/server.go:2069
github.com/minio/minio/cmd.httpTraceAll.func1(0x33e9920, 0xc000e114a0, 0xc009e84600)
        github.com/minio/minio/cmd/handler-utils.go:368 +0x70
net/http.HandlerFunc.ServeHTTP(0xc00107e970, 0x33e9920, 0xc000e114a0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRedirectHandler.func1(0x33e9920, 0xc000e114a0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:137 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc0005bd008, 0x33e9920, 0xc000e114a0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addCustomHeaders.func1(0x33e98f0, 0xc0005bd188, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:572 +0x174
net/http.HandlerFunc.ServeHTTP(0xc0005bd020, 0x33e98f0, 0xc0005bd188, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addSecurityHeaders.func1(0x33e98f0, 0xc0005bd188, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:581 +0x1ea
net/http.HandlerFunc.ServeHTTP(0xc0005bd038, 0x33e98f0, 0xc0005bd188, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBucketForwardingHandler.func1(0x33e98f0, 0xc0005bd188, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:455 +0xad
net/http.HandlerFunc.ServeHTTP(0xc0005bd050, 0x33e98f0, 0xc0005bd188, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestValidityHandler.func1(0x33e98f0, 0xc0005bd188, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:443 +0x493
net/http.HandlerFunc.ServeHTTP(0xc0005bd068, 0x33e98f0, 0xc0005bd188, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setHTTPStatsHandler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:374 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc0005bd080, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:50 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc0005bd098, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:70 +0x202
net/http.HandlerFunc.ServeHTTP(0xc0005bd0b0, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x33c6640, 0xc0005bd0b0, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x82
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:163 +0x74
net/http.HandlerFunc.ServeHTTP(0xc0005bd0c8, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setReservedBucketHandler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:295 +0x278
net/http.HandlerFunc.ServeHTTP(0xc0005bd0e0, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBrowserCacheControlHandler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:264 +0x1ce
net/http.HandlerFunc.ServeHTTP(0xc0005bd0f8, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setTimeValidityHandler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:361 +0x42c
net/http.HandlerFunc.ServeHTTP(0xc0005bd110, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setAuthHandler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/auth-handler.go:490 +0x3a3
net/http.HandlerFunc.ServeHTTP(0xc0005bd128, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setSSETLSHandler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:615 +0x74
net/http.HandlerFunc.ServeHTTP(0xc0005bd140, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.filterReservedMetadata.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        github.com/minio/minio/cmd/generic-handlers.go:110 +0x1e8
net/http.HandlerFunc.ServeHTTP(0xc0005bd158, 0x33ec3b0, 0xc0004420e0, 0xc009e84600)
        net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000346600, 0x33ec3b0, 0xc0004420e0, 0xc009e84400)
        github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rs/cors.(*Cors).Handler.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84400)
        github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc002cf4da0, 0x33ec3b0, 0xc0004420e0, 0xc009e84400)
        net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x33c6640, 0xc002cf4da0, 0x33ec3b0, 0xc0004420e0, 0xc009e84400)
        github.com/minio/minio/cmd/generic-handlers.go:600 +0x85
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x33ec3b0, 0xc0004420e0, 0xc009e84400)
        github.com/minio/minio/cmd/http/server.go:102 +0x258
net/http.HandlerFunc.ServeHTTP(0xc0007984e0, 0x33ec3b0, 0xc0004420e0, 0xc009e84400)
        net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0007bec60, 0x33ec3b0, 0xc0004420e0, 0xc009e84400)
        net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000e11360, 0x33f5e68, 0xc00052b040)
        net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        net/http/server.go:3013 +0x39b
```

## Your Environment

* Version used (`minio --version`): `master`
* Server setup and configuration:
* Operating System and version (`uname -a`):

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
STS call should be rejected for missing policies

## Motivation and Context
fixes #12055

## How to test this PR?
As per #12055 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#3228dbb9-b70d-4a39-b73c-6007ac56f317) |
<a name="3228dbb9-b70d-4a39-b73c-6007ac56f317"></a>
### 12056-f6267be/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31204
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a606fabc109a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2483,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:31204 s3api copy-object --bucket awscli-mint-test-bucket-4297 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-4297/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 50 seconds
(7/15) Running minio-dotnet tests ... done in 36 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 4 seconds
{
  "args": {},
  "duration": 391,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 32 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 353,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-20g7eaj, objectName = minio-java-test-2u42n74-copy, resource = /minio-java-test-20g7eaj/minio-java-test-2u42n74-copy, requestId = 1675E546689F0E39, hostId = eaab4503-0556-49e0-b00a-ea57513495fa)\nrequest={method=PUT, url=http://minio-dev4.minio.io:31204/minio-java-test-20g7eaj/minio-java-test-2u42n74-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2vseg19/minio-java-test-2u42n74\nHost: minio-dev4.minio.io:31204\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210415T015531Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210415/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Thu, 15 Apr 2021 01:55:31 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1675E546689F0E39\nX-Xss-Protection: 1; mode=block\nDate: Thu, 15 Apr 2021 01:55:31 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 1 minutes and 5 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 54 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2590",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-9509/s3cmd-test-object-9636 95ec6f1f-6854-41c9-b177-a23f9a3fcb7e\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 95ec6f1f-6854-41c9-b177-a23f9a3fcb7e put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#48ac7ac6-8ff2-4b83-88b8-1d70eee2a515) |
<a name="48ac7ac6-8ff2-4b83-88b8-1d70eee2a515"></a>
### 12056-726cd40/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30503
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dfb12e085aac:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2604,
  "function": "aws --endpoint-url http://minio-c2.minio.io:30503 s3api copy-object --bucket awscli-mint-test-bucket-30159 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-30159/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 48 seconds
(7/15) Running minio-dotnet tests ... done in 41 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 56 seconds
{
  "args": {},
  "duration": 459,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 29 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 274,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-1mdbpu6, objectName = minio-java-test-un9885-copy, resource = /minio-java-test-1mdbpu6/minio-java-test-un9885-copy, requestId = 1675E8EFEDBC63BD, hostId = 3a39ff76-ca30-4e63-be88-bc6aa76d34d5)\nrequest={method=PUT, url=http://minio-c2.minio.io:30503/minio-java-test-1mdbpu6/minio-java-test-un9885-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-1t7fvsl/minio-java-test-un9885\nHost: minio-c2.minio.io:30503\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210415T030238Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210415/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Thu, 15 Apr 2021 03:02:38 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1675E8EFEDBC63BD\nX-Xss-Protection: 1; mode=block\nDate: Thu, 15 Apr 2021 03:02:38 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 52 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 49 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2772",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-12898/s3cmd-test-object-23711 d17908ab-a6cd-441b-8c21-b0ce90747f04\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id d17908ab-a6cd-441b-8c21-b0ce90747f04 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by Alevsk — CHANGES_REQUESTED** [review]
I think the fix is working but im seeing a weird behavior when trying to remove the policy

```
alevsk@tifa  ~  mc admin policy add myminio mcsAdmin  /Users/alevsk/Desktop/admin_policy.json
Added policy `mcsAdmin` successfully.
 alevsk@tifa  ~  mc admin policy set myminio mcsAdmin user="alevsk"
Policy `mcsAdmin` is set on user `alevsk`
 alevsk@tifa  ~  mc admin user list myminio
enabled    alevsk                mcsAdmin
enabled    alevsk2               consoleAdmin
enabled    alice                 rMybucket
 alevsk@tifa  ~  mc admin policy remove myminio mcsAdmin
mc: <ERROR> Unable to remove policy. The specified user does not exist. (Specified user does not exist).
 ✘ alevsk@tifa  ~  mc admin policy list myminio
rMybucket
readonly
readwrite
writeonly
consoleAdmin
diagnostics
```

Removing policy says the operation failed but the policy was removed indeed, also the error message is wrong, logs on minio confirm the authentication failed because of the policy doesnt exists:

```
Error: specified policy mcsAdmin, not found Specified canned policy does not exist (*fmt.wrapError)
       3: cmd/sts-errors.go:57:cmd.writeSTSErrorResponse()
       2: cmd/sts-handlers.go:239:cmd.(*stsAPIHandlers).AssumeRole()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

**Review by Alevsk — APPROVED** [review]
Remove policy issue will be fixed on the next PR, tested, worked fine.

**Pull request merged**
