### PR TITLE
feat:support tags for PostPolicy upload

### LINKED ISSUE #19811: Support Tagging in PostPolicy upload functionality
## NOTE

I'm trying to upload a file using a presigned POST URL and have the file tagged.  The code works on S3 but not Minio.

## Expected Behavior

Object in the bucket should be tagged with the key and value `{"retention": "expire_fast"}`

## Current Behavior

Object was not tagged at all

## Steps to Reproduce (for bugs)

I used this code which uploads the file but doesn't tag:

```python
import datetime

import boto3
import requests
from django.conf import settings

RETENTION = 'retention'
EXPIRE_FAST = 'expire_fast'
TEMP_MARKER = 'temp'

service = 's3'
region = 'us-east-1'
t = datetime.datetime.utcnow()
algorithm = 'AWS4-HMAC-SHA256'
credential_scope = '/'.join([t.strftime('%Y%m%d'), region, service, 'aws4_request'])

key = 'temp-22e063cd-4ed3-437c-87ac-2bc6e6f328d0/my_file.txt'


def get_tag_xml(key, value):
    return f"<Tagging><TagSet><Tag><Key>{key}</Key><Value>{value}</Value></Tag></TagSet></Tagging>"


conditions = [
    {"x-amz-algorithm": algorithm},
    {"x-amz-credential": credential_scope},
    {"x-amz-date": t.isoformat()},
    {"tagging": get_tag_xml(RETENTION, EXPIRE_FAST)},
    {"success_action_status": "201"},
    {"bucket": settings.AWS_STORAGE_BUCKET_NAME},
    ["starts-with", "$key", TEMP_MARKER],
]

fields = {
    "x-amz-algorithm": algorithm,
    "x-amz-credential": credential_scope,
    "x-amz-date": t.isoformat(),
    "tagging": get_tag_xml(RETENTION, EXPIRE_FAST),
    "success_action_status": "201",
}

client = boto3.client(
    service_name='s3',
    aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
    aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
    endpoint_url=settings.AWS_S3_ENDPOINT_URL,  # http://127.0.0.1:6000
)

presigned = client.generate_presigned_post(
    settings.AWS_STORAGE_BUCKET_NAME,
    key,
    Fields=fields,
    Conditions=conditions,
    ExpiresIn=60*60,
)

# Demonstrate how another Python program can use the presigned URL to upload a file
object_name = 'my_file.txt'
with open(object_name, 'rb') as f:
    files = {'file': (object_name, f)}
    http_response = requests.post(presigned['url'], data=presigned['fields'], files=files)
print(f'File upload HTTP status code: {http_response.status_code}')
print(http_response.content)
```

The output of the code is:

```
File upload HTTP status code: 201
b'<?xml version="1.0" encoding="UTF-8"?>\n<PostResponse><Bucket>my-bucket</Bucket><Key>temp-22e063cd-4ed3-437c-87ac-2bc6e6f328d0/my_file.txt</Key><ETag>&#34;14758f1afd44c09b7992073ccf00b43d&#34;</ETag><Location>http://127.0.0.1:6000/my-bucket/temp-22e063cd-4ed3-437c-87ac-2bc6e6f328d0/my_file.txt</Location></PostResponse>'
```

I got this log capture:

```
$  ./mc admin trace --verbose myminio
127.0.0.1:6000 [REQUEST s3.PostPolicyBucket] [2024-05-26T13:23:20.832] [Client IP: 127.0.0.1]
127.0.0.1:6000 POST /my-bucket
127.0.0.1:6000 Proto: HTTP/1.1
127.0.0.1:6000 Host: 127.0.0.1:6000
127.0.0.1:6000 User-Agent: python-requests/2.31.0
127.0.0.1:6000 Accept: */*
127.0.0.1:6000 Accept-Encoding: gzip, deflate
127.0.0.1:6000 Connection: keep-alive
127.0.0.1:6000 Content-Length: 1917
127.0.0.1:6000 Content-Type: multipart/form-data; boundary=e189907d61cb5bf9142c98341cbc85c6
127.0.0.1:6000 <BLOB>
127.0.0.1:6000 [RESPONSE] [2024-05-26T13:23:20.835] [ Duration 3.008ms TTFB 2.989ms ↑ 1.9 KiB  ↓ 319 B ]
127.0.0.1:6000 201 Created
127.0.0.1:6000 X-Amz-Id-2: 726abb4f16358ae8a3c79dbe4408cc087c01b37ec7f880f6f4abad03bc208938
127.0.0.1:6000 X-Amz-Request-Id: 17D32393D6F94138
127.0.0.1:6000 X-Content-Type-Options: nosniff
127.0.0.1:6000 ETag: "14758f1afd44c09b7992073ccf00b43d"
127.0.0.1:6000 Location: http://127.0.0.1:6000/my-bucket/temp-22e063cd-4ed3-437c-87ac-2bc6e6f328d0/my_file.txt
127.0.0.1:6000 Strict-Transport-Security: max-age=31536000; includeSubDomains
127.0.0.1:6000 Vary: Origin,Accept-Encoding
127.0.0.1:6000 X-Xss-Protection: 1; mode=block
127.0.0.1:6000 Accept-Ranges: bytes
127.0.0.1:6000 Content-Length: 319
127.0.0.1:6000 Content-Type: application/xml
127.0.0.1:6000 Server: MinIO
127.0.0.1:6000 <BLOB>
127.0.0.1:6000 
```

## Context

I want to tag the files to use to apply lifecycle rules.

## Your Environment

* Version used (`minio --version`): RELEASE.2024-05-10T01-41-38Z (go1.22.3 darwin/amd64)
* Server setup and configuration: Python 3.10 with boto3
* Operating System and version (`uname -a`): macOS 13.6

### PR DESCRIPTION
**Pull request by jiuker**
feat:support tags for PostPolicy upload

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Test code will depend on this https://github.com/minio/minio-go/pull/1967
```golang
package main

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"mime/multipart"
	"net/http"
	"os"
	"time"

	minio "github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	endpoint := "127.0.0.1:9000"
	accessKeyID := "minioadmin"
	secretAccessKey := "minioadmin"
	useSSL := false

	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		log.Fatalln(err)
	}

	ctx := context.Background()
	policy := minio.NewPostPolicy()
	policy.SetBucket("mytest")

	file, err := os.Open("req")
	if err != nil {
		panic(err)
	}
	fileInfo, err := file.Stat()
	if err != nil {
		panic(err)
	}
	tagging := "<Tagging><TagSet><Tag><Key>abc</Key><Value>efg</Value></Tag></TagSet></Tagging>"
	policy.SetKey(file.Name())
	policy.SetContentType("image/png")
	policy.SetContentLengthRange(fileInfo.Size(), fileInfo.Size())
	policy.SetExpires(time.Now().Add(time.Hour * 6))
	policy.SetUserMetadata("myname", "hahaha")
	policy.SetTagging(tagging)                    <----------------------- here is tagging, depend on this pr https://github.com/minio/minio-go/pull/1967

	postUrl, formData, err := minioClient.PresignedPostPolicy(ctx, policy)
	if err != nil {
		panic(err)
	}

	bodyBuffer := &bytes.Buffer{}
	w := multipart.NewWriter(bodyBuffer)
	for k, v := range formData {
		w.WriteField(k, v)
	}

	w.WriteField("x-amz-ignore-foo", "bar")

	// is ignored
	w.WriteField("foo", "bar")

	fw, err := w.CreateFormFile("file", "test.png")
	if err != nil {
		panic(err)
	}
	_, err = io.Copy(fw, file)
	if err != nil {
		panic(err)
	}
	resp, err := http.Post(postUrl.String(), w.FormDataContentType(), bodyBuffer)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}
	fmt.Println(resp.Status)
	fmt.Println(resp.StatusCode)
	fmt.Println(string(body))
}

```

## How to test this PR?

You need `tagging` for other SDK to test this.
When upload is done. And you will see the tags you set.
## Types of changes
- [x] Bug fix https://github.com/minio/minio/issues/19811
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by shtripat — APPROVED** [review]
lgtm, verified

**Review by ramondeklein — COMMENTED** [review]
~Although the code seems to be fine, I think that object tagging should be done using the `tagging` form field as described [here](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html) (search for `tagging`).~

I was referring to the normal `POST Object` method, but this PR changes the `POST Policy` method. But it looks like it also doesn't support the `x-amz-tagging` header. I can't find it [here](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html#sigv4-PolicyConditions). Or is this a MinIO-specific extension? If so, then we should probably document it.

**Comment by jiuker** [comment]
> ~Although the code seems to be fine, I think that object tagging should be done using the `tagging` form field as described [here](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html) (search for `tagging`).~
> 
> I was referring to the normal `POST Object` method, but this PR changes the `POST Policy` method. But it looks like it also doesn't support the `x-amz-tagging` header. I can't find it [here](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html#sigv4-PolicyConditions). Or is this a MinIO-specific extension? If so, then we should probably document it.

Yes. Thanks for your document that you found. I will change that into `tagging`

**Comment by shtripat** [comment]
For verifying it, we need https://github.com/minio/minio-go/pull/1967, right? You may want to add minio-go dependency as replace in go.mod till that PR gets merged.

**Comment by harshavardhana** [comment]
> For verifying it, we need [minio/minio-go#1967](https://github.com/minio/minio-go/pull/1967), right? You may want to add minio-go dependency as replace in go.mod till that PR gets merged.

that's just for client side support @shtripat we don't need this for merging server PR.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
