### PR TITLE
remove unnecessary code checking for supported features

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
remove unnecessary code checking for supported features

Bonus: optimize markDelete/purgeDelete code for buckets 
replicating in site-replication to use peer calls.

## Motivation and Context
code cleanup

## How to test this PR?
Nothing should change or break, site-replication tests 
already provide coverage for the bucket delete sync
calls.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by vadmeste** [comment]
> remove unnecessary code checking for supported features

This is because gateway and FS modes are removed

**Comment by klauspost** [comment]
We can also do `type ObjectLayer = *erasureServerPools` to remove a bazillion interface checks, since it is the only implementation.

It will also speed up things, since escape analysis can now be done. Got it 50% done yesterday. I can finish when this is merged.

**Review by klauspost — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
