### PR TITLE
fix: Avoid re-reading bucket names from etcd

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: Avoid re-reading bucket names from etcd

## Motivation and Context
This helps improve performance when there are
1000+ bucket entries on etcd, improves the
startup time significantly.

## How to test this PR?
Observed in federated setups with large number of buckets

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#77161455-5158-43bc-85ba-90c11fa880c6) |
| mint-worm.sh | :x: [more...](#85c1490c-3b3c-4f86-b7f1-12cdc754f8a2) |
| mint-dist-xl.sh | :x: [more...](#ee8cf368-1f84-4b92-aeb0-7ea1665fd047) |
| mint-gateway-azure.sh | :x: [more...](#f7a6a603-5fd1-4ce4-9955-c9622058e32c) |
<a name="85c1490c-3b3c-4f86-b7f1-12cdc754f8a2"></a>
### 8924-c7ad79b/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30046
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 386ad6f5e6e0:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-08sn77612y9hrxwqdeq6slcv7rpc386t4391xfimfg3to5kixslwndx",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120289,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30046/bucket-08sn77612y9hrxwqdeq6slcv7rpc386t4391xfimfg3to5kixslwndx: dial tcp 72.28.97.55:30046: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="f7a6a603-5fd1-4ce4-9955-c9622058e32c"></a>
### 8924-c7ad79b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31553
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1a7b0e8daf72:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 58 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 17 seconds
(5/13) Running minio-go tests ... FAILED in 30 minutes and 35 seconds
{
  "args": {
    "bucketName": "minio-go-test-6ti9uypxpq5tg22l",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 237,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="ee8cf368-1f84-4b92-aeb0-7ea1665fd047"></a>
### 8924-c7ad79b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31614
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 93e41e747bd3:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 26 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 4 seconds
(4/13) Running mc tests ... done in 42 seconds
(5/13) Running minio-go tests ... done in 13 minutes and 38 seconds
(6/13) Running minio-js tests ... FAILED in 17 seconds
{
  "name": "minio-js",
  "function": "listObjects(bucketName, prefix, recursive)",
  "args": "bucketName:minio-js-test-b86adaaa-5d6b-45aa-9dbc-f759f103481f, recursive:false",
  "duration": 311,
  "status": "FAIL",
  "error": "Error: done() called multiple times at /mint/run/core/minio-js/node_modules/mocha-steps/lib/step.js:67:11 at /mint/run/core/minio-js/test/functional-tests.js:1161:13 at wrapper (node_modules/minio/node_modules/async/dist/async.js:273:20) at iterateeCallback (node_modules/minio/node_modules/async/dist/async.js:418:21) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:326:20 at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:1846:25 at DestroyableTransform.<anonymous> (node_modules/minio/dist/main/minio.js:514:15) at done (node_modules/readable-stream/lib/_stream_transform.js:192:25) at /mint/run/core/minio-js/node_modules/readable-stream/lib/_stream_transform.js:130:7 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:7) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 5 out of 13 tests successfully.
```
<a name="77161455-5158-43bc-85ba-90c11fa880c6"></a>
### 8924-c7ad79b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30590
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cce259815121:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 23 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 45 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 58 seconds
{
  "args": {},
  "duration": 95913,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
PTAL @poornas @nitisht

**Review by nitisht — APPROVED** [review]
LGTM & Tested Server Startup

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ea7c2251-77d9-4f17-b039-aee74454c58a) |
| mint-fs.sh | :x: [more...](#d5f4b8be-c535-46c0-aff9-3113cdcbce3f) |
| mint-gateway-azure.sh | :x: [more...](#c29c5fca-74e0-4a5c-8479-a108ee38928a) |
<a name="ea7c2251-77d9-4f17-b039-aee74454c58a"></a>
### 8924-6c0444a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31264
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c9629368d766:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 21 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 58 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 42 seconds
{
  "args": {},
  "duration": 81661,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="d5f4b8be-c535-46c0-aff9-3113cdcbce3f"></a>
### 8924-6c0444a/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30342
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 90fe8e2dfb9a:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 310015, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30342/awscli-mint-test-bucket-19342""}

Executed 0 out of 13 tests successfully.
```
<a name="c29c5fca-74e0-4a5c-8479-a108ee38928a"></a>
### 8924-6c0444a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30660
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 34256b4ca395:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 33 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 17 seconds
(4/13) Running mc tests ... done in 7 minutes and 43 seconds
(5/13) Running minio-go tests ... FAILED in 21 minutes and 56 seconds
{
  "args": {
    "bucketName": "minio-go-test-ofqq5zwlhap3lme0",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 233,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by poornas — APPROVED** [review]
LGTM

**Pull request merged**
