### PR TITLE
ship mc along with MinIO container image

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
ship mc along with MinIO container image

## Motivation and Context
this is mainly to facilitate any local pod
or container-level debugging.

## How to test this PR?
Nothing special `mc` is available gzipped

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#a717fdf3-e767-48bd-b3f5-265c1e81e44e) |
<a name="a717fdf3-e767-48bd-b3f5-265c1e81e44e"></a>
### 16156-7eda831/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:31493
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 25c65ead5c4e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 52 seconds
(9/14) Running minio-java tests ... FAILED in 35 seconds
{
  "name": "minio-java",
  "function": "getObjectRetention()",
  "duration": 110,
  "status": "FAIL",
  "error": "java.time.format.DateTimeParseException: Text '2022-12-03T00:42:15.9Z' could not be parsed at index 19 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioAsyncClient.lambda$getObjectRetention$35(MinioAsyncClient.java:1738), java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642), java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506), java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073), io.minio.S3Base$1.onResponse(S3Base.java:559), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 52 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 49 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by krisis — APPROVED** [review]

**Comment by levrik** [comment]
What is the reason for having `mc` only available gzipped? I wanted to use the `minio` container for integration testing with Testcontainers and was surprised by it not being included until I discovered that it is but gzipped which needs to be decompressed first.

**Comment by olizilla** [comment]
Same here? I was going to do a quick `container.exec(['mc', 'mb', 'test-bucket'])` from a test container, but mc turned out to be gzip'd which started to make it a faff. It'd be rad if I could use `mc` out of the box in the docker container.

**Comment by levrik** [comment]
@olizilla This is my workaround to make `mc` work with Testcontainers. It simply decompresses it, makes it executable and also configures the local MinIO instance with `mc`. It's implemented in Python but the idea should be easy to port to other Testcontainers implementations.

```python
class MinioContainer(testcontainers.minio.MinioContainer):
    def __init__(
        self,
        image: str = "minio/minio:latest",
        port_to_expose: int = 9000,
        access_key: str = "minioadmin",
        secret_key: str = "minioadmin",
        **kwargs,
    ):
        super().__init__(image, port_to_expose, access_key, secret_key, **kwargs)

    def _prepare_mc(self):
        cmd = ";".join(
            [
                # Decompress the MinIO Client included with the image
                "gzip -d /opt/bin/mc.gz",
                # Make the MinIO Client executable
                "chmod +x /opt/bin/mc",
                # Configure local MinIO instance in client
                f"mc config host add local http://localhost:{self.port_to_expose} {self.access_key} {self.secret_key}",
            ]
        )
        res = self.exec(f"/bin/sh -c '{cmd}'")
        if res.exit_code != 0:
            raise RuntimeError(f"MinIO Client prepare failure: {res.output}")

    def start(self):
        super().start()
        self._prepare_mc()
        return self
```

**Comment by olizilla** [comment]
Nice. In JS land I ended up just creating a local s3 client to create the bucket, to make sure it works with non-release minio docker images as well that don't come with `mc.gz`.

**Comment by levrik** [comment]
@olizilla I wanted to use `mc` to recursively import a data fixture for an integration test as this supports it OOTB and doesn't require custom code for recursively uploading everything.

**Pull request merged**
