### PR TITLE
fix: a crash when disk is nil, safe access on erasureDisks

### LINKED ISSUE #11088: After last upgrade memory fault
```



dic 11 22:14:56 ops-object02.domain.de minio[39576]: panic: runtime error: invalid memory address or nil pointer dereference
dic 11 22:14:56 ops-object02.domain.de minio[39576]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x1613fc3]
dic 11 22:14:56 ops-object02.domain.de minio[39576]: goroutine 287823 [running]:
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd.erasureObjects.crawlAndGetDataUsage(0x10, 0xc00898fb20, 0xc00898fb40, 0xc00898fb60, 0xc00898f8e0, 0xc00898f900, 0xc008996a20, 0x214cde0, 0xc01e843a80, 0xc005dfaa80, ...)
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd/erasure.go:256 +0x143
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd.(*erasureServerPools).CrawlAndGetDataUsage.func1(0xc01e8376a0, 0xc01e837698, 0xc01ec0b1e0, 0xc01e839e50, 0xc005dfaa80, 0x24, 0x43, 0xc0012206d0, 0xc01e839e70, 0xc01e839e60, ...)
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd/erasure-server-sets.go:352 +0x1a5
dic 11 22:14:56 ops-object02.domain.de minio[39576]: created by github.com/minio/minio/cmd.(*erasureServerPools).CrawlAndGetDataUsage
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd/erasure-server-sets.go:339 +0x2a7
dic 11 22:14:56 ops-object02.domain.de systemd[1]: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
dic 11 22:14:56 ops-object02.domain.de systemd[1]: Unit minio.service entered failed state.
dic 11 22:14:56 ops-object02.domain.de systemd[1]: minio.service failed.
dic 11 22:14:56 ops-object02.domain.de systemd[1]: minio.service holdoff time over, scheduling restart.
dic 11 22:14:56 ops-object02.domain.de systemd[1]: Stopped MinIO.
dic 11 22:14:56 ops-object02.domain.de systemd[1]: Starting MinIO...
dic 11 22:14:56 ops-object02.domain.de systemd[1]: Started MinIO.

```

## Expected Behavior
working as usual 

## Current Behavior
after upgrading it, there is one node restarting constantly

## Steps to Reproduce (for bugs)

1. Upgrade to RELEASE.2020-12-10T01-54-29Z

## Regression
Yes

## Your Environment

* Version used (`minio --version`): RELEASE.2020-12-10T01-54-29Z
* Server setup and configuration: CentOS 7, systemd, 2 nodes cluster with 96 disks each
* Operating System and version (`uname -a`): 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: a crash when disk is nil, safe access on erasureDisks

## Motivation and Context
fixes #11088

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 11089-9e62cb4/gopath/src/github.com/minio
+ git -C 11089-9e62cb4/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 11089-9e62cb4/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 11089-9e62cb4/gopath/src/github.com/minio/minio fetch --quiet minio pull/11089/head:pr11089
+ git -C 11089-9e62cb4/gopath/src/github.com/minio/minio checkout --quiet pr11089
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/11089-9e62cb4/gopath
+ make -C 11089-9e62cb4/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/colinmarc/hdfs/v2 v2.1.1
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/minio/minio-go/v7 v7.0.6
go: downloading github.com/shirou/gopsutil v3.20.11+incompatible
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.3.0
go: downloading github.com/klauspost/compress v1.11.3
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading golang.org/x/crypto v0.0.0-20201124201722-c8d3bf9c5392
go: downloading github.com/minio/sio v0.2.1
go: downloading github.com/prometheus/client_golang v1.0.0
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/ncw/directio v1.0.5
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading github.com/lib/pq v1.8.0
go: downloading github.com/nats-io/stan.go v0.7.0
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/klauspost/reedsolomon v1.9.9
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/prometheus/procfs v0.2.0
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading golang.org/x/sys v0.0.0-20201101102859-da207088b7d1
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: downloading github.com/willf/bitset v1.1.11
go: downloading go.etcd.io/etcd v0.0.0-20201125193152-8a03d2e9614b
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/beorn7/perks v1.0.0
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/tinylib/msgp v1.1.3
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/prometheus/common v0.4.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/olivere/elastic/v7 v7.0.22
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/dswarbrick/smart v0.0.0-20190505152634-909a45200d6d
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/fatih/color v1.9.0
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/golang/protobuf v1.4.0
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading github.com/gorilla/handlers v1.4.2
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading google.golang.org/grpc v1.26.0
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/minio/simdjson-go v0.1.5
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/Shopify/sarama v1.24.1
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading google.golang.org/protobuf v1.22.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/mattn/go-isatty v0.0.11
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading github.com/nats-io/nkeys v0.2.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading go.uber.org/zap v1.10.0
go: downloading github.com/nats-io/jwt v1.1.0
go: downloading go.opencensus.io v0.22.5
go: downloading go.uber.org/multierr v1.1.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/minio/md5-simd v1.1.0
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/mailru/easyjson v0.7.6
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
go: downloading github.com/eapache/queue v1.1.0
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading go.uber.org/atomic v1.3.2
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/eapache/go-resiliency v1.1.0
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/tidwall/match v1.0.1
go: downloading github.com/tidwall/pretty v1.0.0
# github.com/minio/minio/cmd
cmd/erasure.go:255:6: i declared but not used
make: *** [build] Error 2

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#33ce12b1-a3e6-4150-93cd-052480eebff7) |
<a name="33ce12b1-a3e6-4150-93cd-052480eebff7"></a>
### 11089-e9714a1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32488
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7773749c4e9e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 27 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 57 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 43 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 37 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 40 seconds
(10/15) Running minio-java tests ... FAILED in 9 minutes and 6 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 188,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:658d30cf-b01e-00ad-620f-d0cd84000000\nTime:2020-12-11T22:46:30.1028188Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'Vyl/TNvrmIVGNLOc5vvoA9LE4hEhf7bk1zaB1hDKt28=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:024208f4-825f-4739-4b7b-5696b5ddbda3\nx-ms-date:Fri, 11 Dec 2020 22:46:30 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-110k22b/minio-java-test-296sq11\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-110k22b/minio-java-test-296sq11?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-11T22:13:24Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [024208f4-825f-4739-4b7b-5696b5ddbda3]\n   X-Ms-Date: [Fri, 11 Dec 2020 22:46:30 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Fri, 11 Dec 2020 22:46:29 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [658d30cf-b01e-00ad-620f-d0cd84000000]\n\n\n, bucketName = minio-java-test-110k22b, objectName = minio-java-test-296sq11, resource = /minio-java-test-110k22b/minio-java-test-296sq11, requestId = 164FCAFF549FA56C, hostId = 2cd1e7ae-022f-4bca-9cba-44ff69ebf87f)\nrequest={method=PUT, url=http://minio-dev4.minio.io:32488/minio-java-test-110k22b/minio-java-test-296sq11, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev4.minio.io:32488\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201211T224629Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201211/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164FCAFF549FA56C\nX-Xss-Protection: 1; mode=block\nDate: Fri, 11 Dec 2020 22:46:30 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 40 seconds
(11/15) Running minio-py tests ... done in 19 minutes and 55 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 21 seconds
(13/15) Running s3select tests ... done in 59 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by poornas — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
