### PR TITLE
Allow OIDC user to query user info if policies permit

### PR DESCRIPTION
**Pull request by donatello**
## Motivation and Context

Bug reported by @Alevsk - console gets a 403 error. Fixed here.

## How to test this PR?

Login via OIDC and try to get user info by clicking on users in console. Browser networks requests shows 403 error, UI does not show the expected enabled status for enabled accounts.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [x] Unit tests added/updated

### CODE REVIEW

**Comment by donatello** [comment]
Please merge https://github.com/minio/minio/pull/13881 before this one.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Looks like there is a bug in this PR @donatello upgrade tests are not proceeding .

**Review by Alevsk — APPROVED** [review]
Tested, works fine

**Comment by harshavardhana** [comment]
> Looks like there is a bug in this PR @donatello upgrade tests are not proceeding .

False alarm some other issue on the docker layer in CI/CD - will monitor.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
