### PR TITLE
Optimize string processing in select

### PR DESCRIPTION
**Pull request by donatello**
## Description

Reduce allocations during string concatenation and simplify some
processing code.

## Motivation and Context

Using `strings.Join` is much faster appending to the same variable in a loop.

## Regression

No

## How Has This Been Tested?

Manually - 

```
$ mc cat myminio/test/2.csv
Name,Count
A,3
B,4
C,1
D,0

mc select --query "select * from S3Object" myminio/test/2.csv
mc select --query "select s._1 from S3Object" myminio/test/2.csv
mc select --query "select s._2 from S3Object" myminio/test/2.csv
mc select --query "select sum(s._2) from S3Object" myminio/test/2.csv
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Enhancement

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
@donatello some changes are already done in @sinhaashish PR can you coordinate with him to avoid any duplicated effort?

**Comment by donatello** [comment]
> @donatello some changes are already done in @sinhaashish PR can you coordinate with him to avoid any duplicated effort?

@harshavardhana None of my changes are already in @sinhaashish's PR at this time. The main change this PR is focused on is avoiding string appending loops like:

```
row := "something"
for <something> {
     row = row + delimiter + <something>
}
```

This can be done efficiently strings.Join.

This is 3x faster when appending 10 1-length strings, and 5x faster when appending 20 1-length strings. Indeed there is a 30% improvement when appending 3 1-length strings! [[Source](https://gist.github.com/donatello/6260986989c7d19a369e231e2d86dbd6)]

**Comment by harshavardhana** [comment]
> @harshavardhana None of my changes are already in @sinhaashish's PR at this time. The main change this PR is focused on is avoiding string appending loops like:

@donatello I thought there was a PR review by you to add strings.Join() , didn't @sinhaashish made that change already in his PR?

**Comment by donatello** [comment]
> @donatello I thought there was a PR review by you to add strings.Join() , didn't @sinhaashish made that change already in his PR?

Ah yes, that was in https://github.com/minio/minio/pull/6515 which was closed by @sinhaashish in favour of https://github.com/minio/minio/pull/6564 at which point I thought maybe my feedback was not understood - and additionally, the change should be implemented throughout the row assembling code in select processing. This is what this PR does.

**Comment by harshavardhana** [comment]
> Ah yes, that was in #6515 which was closed by @sinhaashish in favour of #6564 at which point I thought maybe my feedback was not understood - and additionally, the change should be implemented throughout the row assembling code in select processing. This is what this PR does.

I see now I understood

**Comment by donatello** [comment]
Not sure why travis is not reporting on this change - looks like it passed according to https://travis-ci.org/minio/minio/pull_requests but the status was not reported here - @harshavardhana any idea to fix this?

**Comment by harshavardhana** [comment]
resubmit again, usually a transient issue.

**Review by harshavardhana — DISMISSED** [review]
LGTM changes are working fine for common CSVs

**Comment by donatello** [comment]
This time looks like appveyor has some other unrelated build failure - will resubmit this once hoping for the best @harshavardhana :dagger:

**Review by sinhaashish — APPROVED** [review]
Tested for `select  _1, _2 from S3Object AS s `
`select * from S3Object AS s `
`select   count(*) from S3Object  s ` 
`select   sum(s.height) from S3Object  s`
`select  * from S3Object AS s  where last_name  = 'Acy'  `
and it is works fine.

**Review by harshavardhana — APPROVED** [review]
LGTM

**Pull request merged**
