### PR TITLE
Fix Audit kafka configuration loading

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Currently, the server totally misses loading the audit kafka configuration
after a code refactor. This commit fixes the behavior to make it properly work.

## Motivation and Context
Fix kafka audit loading

## How to test this PR?

1. 
https://developer.confluent.io/quickstart/kafka-docker/ to quickly setup kafka and listen for new events

2.
```
export MINIO_AUDIT_KAFKA_ENABLE=on
export MINIO_AUDIT_KAFKA_BROKERS=localhost:9092
export MINIO_AUDIT_KAFKA_TOPIC=quickstart

./minio server /tmp/fs/
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by harshavardhana** [comment]
When was this regression added ?

**Comment by vadmeste** [comment]
> When was this regression added ?

https://github.com/minio/minio/pull/14269

We do not have integration tests for audit and notification subsystems yet

**Comment by harshavardhana** [comment]
> We do not have integration tests for audit and notification subsystems yet

So almost a year it has been broken @vadmeste

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by klauspost — APPROVED** [review]

**Review by anjalshireesh — APPROVED** [review]
LGTM, tested

**Pull request merged**
