### PR TITLE
Changed the metric name as `minio_bucket_replication_failed_objects`

### PR DESCRIPTION
**Pull request by shtripat**
## Description
This is required as descripton of metric doesn't get set properly as old prometheus API end point `/minio/prometheus/metrics` as well consists a metric with same name.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by harshavardhana** [comment]
> This is required as descripton of metric doesn't get set properly as old prometheus API end point `/minio/prometheus/metrics` as well consists a metric with same name.

We shouldn't carry anything from old.

**Comment by shtripat** [comment]
> > This is required as descripton of metric doesn't get set properly as old prometheus API end point `/minio/prometheus/metrics` as well consists a metric with same name.
> 
> We shouldn't carry anything from old.

@harshavardhana the old end point `/minio/prometheus/metrics` stills seems to be active and returns metrics which contains `minio_bucket_replication_failed_count`. Should we rename the old one or good with this new name?

**Comment by harshavardhana** [comment]
> > > This is required as descripton of metric doesn't get set properly as old prometheus API end point `/minio/prometheus/metrics` as well consists a metric with same name.
> > 
> > 
> > We shouldn't carry anything from old.
> 
> @harshavardhana the old end point `/minio/prometheus/metrics` stills seems to be active and returns metrics which contains `minio_bucket_replication_failed_count`. Should we rename the old one or good with this new name?

Old one should not be touched, no one should be using old endpoint anymore.

**Comment by shtripat** [comment]
> > > > This is required as descripton of metric doesn't get set properly as old prometheus API end point `/minio/prometheus/metrics` as well consists a metric with same name.
> > > 
> > > 
> > > We shouldn't carry anything from old.
> > 
> > 
> > @harshavardhana the old end point `/minio/prometheus/metrics` stills seems to be active and returns metrics which contains `minio_bucket_replication_failed_count`. Should we rename the old one or good with this new name?
> 
> Old one should not be touched, no one should be using old endpoint anymore.

Ok, so new metric name should be a different one as old endpoint still remains active.

**Comment by harshavardhana** [comment]
@shtripat why are we changing this ?

**Comment by shtripat** [comment]
> @shtripat why are we changing this ?

As the name are same in two endpoints the description and type for the metric remains blank as below in prometheus console
image (1)

**Comment by poornas** [comment]
@shtripat , Since the metric is visible in grafana as well as expressions browser , it doesn't appear necessary to rename this metric - closing this PR for now.

**Pull request closed without merging**
