### PR TITLE
Helm s3 gateway support

### PR DESCRIPTION
**Pull request by Broom94**
## Description

* These changes have been migrated from the previous chart: https://github.com/helm/charts/tree/master/stable/minio
* Added s3 support for gateway mode.
* Added new s3 block under the gateway key to house the s3 specific variable serviceEndpoint.

## Motivation and Context

* The current chart does not enable gateway mode to be set as s3. We need the ability to deploy minio as a s3 gateway via helm.

## How to test this PR?

**create IAM principal with at least the privileges listed on the page https://docs.min.io/docs/minio-gateway-for-s3.html**

`cd helm/minio/`

**create new override values file called gateway-s3.yaml containing:**
```
mode: gateway 

rootUser: "AWS_ACCESS_KEY"
rootPassword: "AWS_SECRET_KEY"

gateway:
  type: "s3"

persistence:
  enabled: false
```

**debug install as dry-run to check entrypoint is configured correctly**

`helm install miniogateways3 ./ -f ./gateway-s3.yaml --dry-run`

**test chart install**

`helm install miniogateways3 ./ -f ./gateway-s3.yaml`

follow instructions in terminal to connect to s3 using mc client. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ /] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ /] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by Broom94** [comment]
https://github.com/minio/minio/pull/14418 will need updated after this is merged

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Pull request closed without merging**
