### PR TITLE
re-order the top-level config keys for priority

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
re-order the top-level config keys for priority

## Motivation and Context
update relevant docs with new keys

## How to test this PR?
check via `mc admin config set alias/` the keys must be ordered
in priority - we should keep `subnet/callhome` at the top 
and the rest of the other dynamic systems, then the rest.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [x] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#a5e18d8c-ecc9-4300-9796-bd42d08f890e) |
<a name="a5e18d8c-ecc9-4300-9796-bd42d08f890e"></a>
### 16150-384a23a/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:30518
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 233c1f726640:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-voumxrxjyumxa4",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 370,
  "error": "InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 172C97544D0A6539, host id: ",
  "function": "testListObjects",
  "message": "AWS SDK Go listobjects expected to success but got InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 172C97544D0A6539, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/14) Running aws-sdk-java tests ... done in 1 seconds
(2/14) Running aws-sdk-php tests ... done in 43 seconds
(3/14) Running aws-sdk-ruby tests ... FAILED in 7 seconds
{
  "name": "aws-sdk-ruby",
  "function": "removeObjects(bucket_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-c0fca5fe884f"
  },
  "duration": 2324.64,
  "error": "Failed to clean-up bucket 'aws-sdk-ruby-bucket-c0fca5fe884f', File name: '', We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)",
  "status": "FAIL"
}
(3/14) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 10576,
  "function": "aws --endpoint-url http://15.15.15.1:30518 s3api list-objects-v2 --bucket awscli-mint-test-bucket-21013 --prefix datafile-1-kB\n",
  "status": "FAIL",
  "error": ""
}
(3/14) Running healthcheck tests ... done in 0 seconds
(4/14) Running mc tests ... FAILED in 34 seconds
{
  "name": "mc",
  "duration": "5616",
  "function": "test_find",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(4/14) Running minio-go tests ... FAILED in 33 seconds
{
  "args": {
    "bucketName": "minio-go-test-6fext4qkgnfxuwjw",
    "region": "eu-central-1"
  },
  "duration": 4381,
  "error": "We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)",
  "function": "MakeBucket(bucketName, region)",
  "message": "CleanupBucket failed",
  "name": "minio-go: testMakeBucketRegions",
  "status": "FAIL"
}
(4/14) Running minio-java tests ... done in 38 seconds
(5/14) Running minio-js tests ... done in 52 seconds
(6/14) Running minio-py tests ... done in 1 minutes and 49 seconds
(7/14) Running s3cmd tests ... done in 16 seconds
(8/14) Running s3select tests ... done in 4 seconds
(9/14) Running versioning tests ... done in 3 minutes and 8 seconds

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by anjalshireesh — APPROVED** [review]
LGTM

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by klauspost — APPROVED** [review]
LGTM

**Pull request merged**
