### PR TITLE
lc: Return expiration header only when version id is unspecified

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Follow S3 specification to return Expiration header in HEAD/GET call
only when version-id is not passed in the request.

## Motivation and Context
Follow S3 spec

## How to test this PR?
1. Create a versioned bucket and upload a file twice
2. mc ilm add --expiry-days 1 --noncurrentversion-expiration-days 1 alias/bucket/
3. aws --endpoint-url http://locahost s3api head-object --bucket bucket --key key
4. aws --endpoint-url http://locahost s3api head-object --bucket bucket --key key --version-id version-id  
5. Retry 3 and 4 with aws s3api get-object 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#bbd0258a-9c45-4314-a77d-66c730ae7f36) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#1799d4f5-11bd-4201-a883-bad83bdaf80d) |
<a name="bbd0258a-9c45-4314-a77d-66c730ae7f36"></a>
### 11718-c667e7a/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32708
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dc839b637d30:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 53 seconds
{
  "name": "awscli",
  "duration": 62905,
  "function": "aws --endpoint-url http://minio-c2.minio.io:32708 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-23115/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-23115/datafile-0-bupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-23115/datafile-1-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-23115/datafile-10-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-23115/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-23115/datafile-100-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-23115/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-23115/datafile-1.03-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-23115/datafile-5243880-bupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-23115/datafile-5-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-23115/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-23115/datafile-11-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-23115/datafile-6-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-23115/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-23115/datafile-129-MBupload failed: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-23115/datafile-1-kB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 27 seconds
(7/15) Running minio-dotnet tests ... done in 31 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 1 seconds
(9/15) Running minio-java tests ... done in 13 seconds
(10/15) Running minio-js tests ... done in 44 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 6 seconds
(12/15) Running s3cmd tests ... done in 16 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1799d4f5-11bd-4201-a883-bad83bdaf80d"></a>
### 11718-c667e7a/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30946
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d0fb32091e59:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2876,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30946 s3api copy-object --bucket awscli-mint-test-bucket-10169 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-10169/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 50 seconds
(7/15) Running minio-dotnet tests ... done in 52 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 20 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-r96cc0y4liok6ilu",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-r96cc0y4liok6ilu",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 4858,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 41 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 244,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-1pudo1d, objectName = minio-java-test-gotud-copy, resource = /minio-java-test-1pudo1d/minio-java-test-gotud-copy, requestId = 1669927BF3D88D62, hostId = 8a8ac141-38b5-4a47-9dc0-6ce5933df0df)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30946/minio-java-test-1pudo1d/minio-java-test-gotud-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-8ie37g/minio-java-test-gotud\nHost: minio-dev4.minio.io:30946\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210305T222322Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210305/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 414\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 05 Mar 2021 22:23:22 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1669927BF3D88D62\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Mar 2021 22:23:22 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 55 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 20 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2929",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-25429/s3cmd-test-object-10733 1237f034-0df0-499b-a5fa-d737a5412698\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 1237f034-0df0-499b-a5fa-d737a5412698 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#de2a6c34-a111-4b8c-a456-fa9bde328d6f) |
| mint-gateway-nas.sh | :x: [more...](#6f824bbb-1bf7-4b8a-9514-b20b55735935) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#f8c02473-9adf-4739-9a8e-511810296591) |
<a name="f8c02473-9adf-4739-9a8e-511810296591"></a>
### 11718-b181021/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32375
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp da15f29d0e83:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 34 seconds
{
  "name": "awscli",
  "duration": 2594,
  "function": "aws --endpoint-url http://minio-c2.minio.io:32375 s3api copy-object --bucket awscli-mint-test-bucket-15767 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-15767/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 45 seconds
(7/15) Running minio-dotnet tests ... done in 40 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 55 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-zq3gyyn1liktxnae",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-zq3gyyn1liktxnae",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 5572,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 3 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 153,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-213ik2n, objectName = minio-java-test-27k54bf-copy, resource = /minio-java-test-213ik2n/minio-java-test-27k54bf-copy, requestId = 166995801C327FF2, hostId = 95659ecd-adb1-42ad-9621-59f2879b2759)\nrequest={method=PUT, url=http://minio-c2.minio.io:32375/minio-java-test-213ik2n/minio-java-test-27k54bf-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-hv9log/minio-java-test-27k54bf\nHost: minio-c2.minio.io:32375\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210305T231838Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210305/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 05 Mar 2021 23:18:38 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166995801C327FF2\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Mar 2021 23:18:38 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 51 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 11 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3010",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-4227/s3cmd-test-object-7339 93a59c2c-b821-43f5-88dc-08895f4621f4\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 93a59c2c-b821-43f5-88dc-08895f4621f4 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="de2a6c34-a111-4b8c-a456-fa9bde328d6f"></a>
### 11718-b181021/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31880
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6f7e060bd442:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 4 minutes and 16 seconds
{
  "name": "awscli",
  "duration": 124891,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "remove_bucket failed: s3://awscli-mint-test-bucket-5985 An error occurred (NoSuchBucket) when calling the DeleteBucket operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 42 seconds
(7/15) Running minio-dotnet tests ... done in 40 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 28 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 3 seconds
(10/15) Running minio-js tests ... done in 49 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 58 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="6f824bbb-1bf7-4b8a-9514-b20b55735935"></a>
### 11718-b181021/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31028
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 942fcce432d0:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 3 seconds
{
  "name": "awscli",
  "duration": 72979,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:31028 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-13163/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-13163/datafile-0-bupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-13163/datafile-1-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-13163/datafile-10-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-13163/datafile-33-kBupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-13163/datafile-1-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-13163/datafile-100-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-13163/datafile-1-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-13163/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-13163/datafile-5243880-bupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-13163/datafile-6-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-13163/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-13163/datafile-11-MBupload failed: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-13163/datafile-1.03-MB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not existupload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-13163/datafile-65-MB An error occurred (NoSuchBucket) when calling the UploadPart operation: The specified bucket does not existupload failed: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-13163/datafile-129-MB An error occurred (NoSuchBucket) when calling the UploadPart operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 42 seconds
(7/15) Running minio-dotnet tests ... done in 34 seconds
(8/15) Running minio-go tests ... done in 47 seconds
(9/15) Running minio-java tests ... done in 19 seconds
(10/15) Running minio-js tests ... done in 32 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 9 seconds
(12/15) Running s3cmd tests ... done in 12 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#9ad24c3e-cd9f-4e7d-967a-ce569cdaae22) |
<a name="9ad24c3e-cd9f-4e7d-967a-ce569cdaae22"></a>
### 11718-b6a6a5b/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31363
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4fde27d87070:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2739,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31363 s3api copy-object --bucket awscli-mint-test-bucket-30714 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-30714/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 49 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 48 seconds
{
  "args": {},
  "duration": 1339,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 8 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 165,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-3983la2, objectName = minio-java-test-3sljrbv-copy, resource = /minio-java-test-3983la2/minio-java-test-3sljrbv-copy, requestId = 166A9E92CEB86A41, hostId = a25e715a-2fea-4f06-b02b-8f92509f5286)\nrequest={method=PUT, url=http://minio-c3.minio.io:31363/minio-java-test-3983la2/minio-java-test-3sljrbv-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-27sla70/minio-java-test-3sljrbv\nHost: minio-c3.minio.io:31363\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210309T081607Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210309/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 09 Mar 2021 08:16:09 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166A9E92CEB86A41\nX-Xss-Protection: 1; mode=block\nDate: Tue, 09 Mar 2021 08:16:09 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 52 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 29 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2600",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-18918/s3cmd-test-object-14388 033f8c6b-ab5c-4cec-8e8d-edb07d2effae\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 033f8c6b-ab5c-4cec-8e8d-edb07d2effae put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
