### PR TITLE
Enable go1.10.1 version

### LINKED ISSUE #5644: [toolchain]: Update go version to latest stable version 1.10
This is a request for updating our CI, docker files and other configuration files to the latest Go version `1.10`. At the moment we require Go `1.9.4`.
Further some of our config files contain out-dated Go versions like: [snap](https://github.com/minio/minio/blob/52e382b697eab615ca114df431ea741e60bb4879/snap/snapcraft.yaml#L31)

## Context
Tooling
Also related: #5566 

## Your Environment
master

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Enable travis on go1.10.1 version

## Motivation and Context
Fixes https://github.com/minio/minio/issues/5644

## How Has This Been Tested?
Manually and using `go test`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5666-d8c1371/gopath/src/github.com/minio
+ git -C 5666-d8c1371/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5666-d8c1371/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5666-d8c1371/gopath/src/github.com/minio/minio fetch --quiet minio pull/5666/head:pr5666
+ git -C 5666-d8c1371/gopath/src/github.com/minio/minio checkout --quiet pr5666
+ GOPATH=/home/bala/mintauto/5666-d8c1371/gopath
+ make -C 5666-d8c1371/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5666-6842020/gopath/src/github.com/minio
+ git -C 5666-6842020/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5666-6842020/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5666-6842020/gopath/src/github.com/minio/minio fetch --quiet minio pull/5666/head:pr5666
+ git -C 5666-6842020/gopath/src/github.com/minio/minio checkout --quiet pr5666
+ GOPATH=/home/bala/mintauto/5666-6842020/gopath
+ make -C 5666-6842020/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5666-70a7e06/gopath/src/github.com/minio
+ git -C 5666-70a7e06/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5666-70a7e06/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5666-70a7e06/gopath/src/github.com/minio/minio fetch --quiet minio pull/5666/head:pr5666
+ git -C 5666-70a7e06/gopath/src/github.com/minio/minio checkout --quiet pr5666
+ GOPATH=/home/bala/mintauto/5666-70a7e06/gopath
+ make -C 5666-70a7e06/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Comment by vadmeste** [comment]
@harshavardhana can you update the commit message? it is not only about travis anymore

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5666-9611f70/gopath/src/github.com/minio
+ git -C 5666-9611f70/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5666-9611f70/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5666-9611f70/gopath/src/github.com/minio/minio fetch --quiet minio pull/5666/head:pr5666
+ git -C 5666-9611f70/gopath/src/github.com/minio/minio checkout --quiet pr5666
+ GOPATH=/home/bala/mintauto/5666-9611f70/gopath
+ make -C 5666-9611f70/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Review by nitisht — DISMISSED** [review]
LGTM

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5666-f206ae0/gopath/src/github.com/minio
+ git -C 5666-f206ae0/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5666-f206ae0/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5666-f206ae0/gopath/src/github.com/minio/minio fetch --quiet minio pull/5666/head:pr5666
+ git -C 5666-f206ae0/gopath/src/github.com/minio/minio checkout --quiet pr5666
+ GOPATH=/home/bala/mintauto/5666-f206ae0/gopath
+ make -C 5666-f206ae0/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5666-c3dc294/gopath/src/github.com/minio
+ git -C 5666-c3dc294/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5666-c3dc294/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5666-c3dc294/gopath/src/github.com/minio/minio fetch --quiet minio pull/5666/head:pr5666
+ git -C 5666-c3dc294/gopath/src/github.com/minio/minio checkout --quiet pr5666
+ GOPATH=/home/bala/mintauto/5666-c3dc294/gopath
+ make -C 5666-c3dc294/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Review by vadmeste — DISMISSED** [review]
LGTM

**Review by nitisht — DISMISSED** [review]

**Comment by harshavardhana** [comment]
Let's not merge this yet. Before I confirm with @abperiasamy about this.

**Comment by vadmeste** [comment]
We need this PR for error logging. GOROOT is correctly calculated only since go 1.10. (If GOROOT is not set, GOROOT is deduced from the go binary path). Otherwise the log can contain some long path prefixes in the stack trace.

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5666-37a8b2d/gopath/src/github.com/minio
+ git -C 5666-37a8b2d/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5666-37a8b2d/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5666-37a8b2d/gopath/src/github.com/minio/minio fetch --quiet minio pull/5666/head:pr5666
+ git -C 5666-37a8b2d/gopath/src/github.com/minio/minio checkout --quiet pr5666
+ GOPATH=/home/bala/mintauto/5666-37a8b2d/gopath
+ make -C 5666-37a8b2d/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Comment by deekoder** [comment]
I don't think there's anything blocking this move.

**Comment by deekoder** [comment]
we need to update the doc "how to install golang" for updated new version. If we can remove the version number we don't have to keep updating this doc I suppose.

**Comment by harshavardhana** [comment]
> we need to update the doc "how to install golang" for updated new version. If we can remove the version number we don't have to keep updating this doc I suppose.

https://github.com/minio/cookbook/blob/master/docs/how-to-install-golang.md yeah that's in cookbook

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5666-36713bb/gopath/src/github.com/minio
+ git -C 5666-36713bb/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5666-36713bb/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5666-36713bb/gopath/src/github.com/minio/minio fetch --quiet minio pull/5666/head:pr5666
+ git -C 5666-36713bb/gopath/src/github.com/minio/minio checkout --quiet pr5666
+ GOPATH=/home/bala/mintauto/5666-36713bb/gopath
+ make -C 5666-36713bb/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5666-3d2439b/gopath/src/github.com/minio
+ git -C 5666-3d2439b/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5666-3d2439b/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5666-3d2439b/gopath/src/github.com/minio/minio fetch --quiet minio pull/5666/head:pr5666
+ git -C 5666-3d2439b/gopath/src/github.com/minio/minio checkout --quiet pr5666
+ GOPATH=/home/bala/mintauto/5666-3d2439b/gopath
+ make -C 5666-3d2439b/gopath/src/github.com/minio/minio --quiet
make: *** [checks] Error 1

```

**Comment by harshavardhana** [comment]
Moved to go1.10.1

**Comment by deekoder** [comment]
ping @vadmeste  and @nitisht.

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by nitisht — APPROVED** [review]

**Pull request merged**
