### PR TITLE
Updated version of klauspost/reedsolomon with NEON support for ARM

### PR DESCRIPTION
**Pull request by fwessels**
Add NEON support for ARM for reed solomon coding. It speeds up erasure coding on ARM by up to a factor 10x.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by aead — APPROVED** [review]
LGTM - I don't know why Codecov reports decreasing coverage - As far as I can see: patch is not related; I think this is fine.

**Comment by harshavardhana** [comment]
> LGTM - I don't know why Codecov reports decreasing coverage - As far as I can see: patch is not related; I think this is fine.

This is possibly fixed by #4864

**Review by harshavardhana — APPROVED** [review]

**Comment by vielmetti** [comment]
Thanks for this. Is there a simple set of benchmark results that shows the performance speedup directly?

**Comment by harshavardhana** [comment]
@vielmetti https://github.com/klauspost/reedsolomon#performance-on-arm64-neon

**Pull request merged**
