### PR TITLE
fix: a regression with audit log sending

### PR DESCRIPTION
**Pull request by shtripat**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by klauspost — COMMENTED** [review]
What is the regression here?

It seems reasonable to me that invalid configuration would take it offline.

Is it that a success takes it online again? If so, just remove that part.

**Comment by shtripat** [comment]
> What is the regression here?
> 
> It seems reasonable to me that invalid configuration would take it offline.
> 
> Is it that a success takes it online again? If so, just remove that part.

None of the audit logs were being sent. @klauspost you mean to remove below additional line?
```
if err != nil {
	atomic.StoreInt32(&h.status, statusOffline)  <=========
	return fmt.Errorf("%s returned '%w', please check your endpoint configuration", h.Endpoint(), err)
}
```

**Comment by klauspost** [comment]
@shtripat Sorry for my ignorance, but I fail to see how this could fix such an issue?

**Comment by klauspost** [comment]
@shtripat You are replacing a check on the returned error (that may take it online if ok) to something that will in rarer cases take it offline.

Looking at the places where errors could be returned it seems to be with invalid configuration or server responds with an error. I don't see why it is a mistake to mark it offline in that situation.

It seems more like the problem must be how it is taken *online* - and not actually in any of the code modified. I did not dig deeper, but I don't see how this change fixes what you are seeing. Or it is working around the problem in another way by never taking it offline even when there are errors - and it just keeps trying.

Either way I am not sure this is the fix.

**Comment by shtripat** [comment]
> @shtripat You are replacing a check on the returned error (that may take it online if ok) to something that will in rarer cases take it offline.
> 
> Looking at the places where errors could be returned it seems to be with invalid configuration or server responds with an error. I don't see why it is a mistake to mark it offline in that situation.
> 
> It seems more like the problem must be how it is taken _online_ - and not actually in any of the code modified. I did not dig deeper, but I don't see how this change fixes what you are seeing. Or it is working around the problem in another way by never taking it offline even when there are errors - and it just keeps trying.
> 
> Either way I am not sure this is the fix.

Ok, I get the point. Let me debug more and see.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
