### PR TITLE
tests: Enable previously disabled UNC tests on CI.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Enable previously disabled UNC tests on CI.

## Motivation and Context
Windows CI had a bug which has been fixed, re-enable
those commented tests.

## How Has This Been Tested?
Manually on windows. and go test.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by donatello** [comment]
Seems to have died pretty messily in one of the travis builds.

**Comment by harshavardhana** [comment]
> Seems to have died pretty messily in one of the travis builds.

Restarted this is related to the TLSListenAndServe.

**Comment by harshavardhana** [comment]
is there anything that is needed here ? @balamurugana @donatello

**Review by donatello — APPROVED** [review]

**Review by balamurugana — APPROVED** [review]
Not tested.

**Pull request merged**
