### PR TITLE
Add Docker development workflow for browser

### PR DESCRIPTION
**Pull request by darkdragon-001**
## Description
Add docker development workflow for frontend / browser component.

## Motivation and Context
Helps for onboarding new contributors.

## How to test this PR?
Read the documentation changes and try the described steps.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
> Depends on #9663.

why does this depend on #9663 that file is removed now @darkdragon-001

**Comment by darkdragon-001** [comment]
@harshavardhana Check the last added section in the README about running tests. I think it would be a good idea to advise the user on how to run tests. Should I change it to running `npm run test` instead?

**Comment by harshavardhana** [comment]
> @harshavardhana Check the last added section in the README about running tests. I think it would be a good idea to advise the user on how to run tests. Should I change it to running `npm run test` instead?

Yes that would be better.

**Comment by darkdragon-001** [comment]
@harshavardhana done.

**Review by harshavardhana — APPROVED** [review]

**Review by kanagarajkm — APPROVED** [review]

**Pull request merged**
