### PR TITLE
[S3 Select] Eliminate message metadata overhead in SQL Select responses

### PR DESCRIPTION
**Pull request by donatello**
## Description

This change collects SQL query result records into a buffer (1MiB) and then sends out the data as a single message in the response. This greatly reduces the number of bytes transferred for queries that return small records.

Previously we were sending 1 record per message in the response. Each message has 16 bytes of metadata overhead. This change sends as many (whole) records as needed to fill a 1MiB buffer in a single message.

## Motivation and Context

The performance gain is dramatic for queries that return small records - take `mys3/sqlselectapi/big.csv.gz` that contains looks like:

```shell
$ mc cat mys3/sqlselectapi/big.csv.gz | head
Id,FirstName,LastName,Rating
1,James,Cruz,3.553518234841988
2,James,Karev,4.500141413056121
3,Alice,Merkel,0.7988159563374936
4,Alice,Karev,1.3823139588325635
5,Angela,Ford,1.4022646931870353
6,Alice,Cruz,3.8760075447547266
7,Joe,Jones,1.0697657081273237
8,Joe,Jones,4.0405880522258455
9,Joe,Merkel,0.1369984718177114
```

It contains 1 million such short rows.

With this file, the following queries were run using mc and measurements made (mc and minio are running on a laptop in this micro-benchmark):

|Query|Master|This PR|
|:------|:------|:-----|
| `select * from s3object` | 15s | 3s |
| `select s.Id from s3object s` | 21s | 4s |
| `select  s.LastName, s.FirstName, s.Rating, s.Id from s3object s ` | 37s | 9s |

All measurements are a fastest of 5 runs rounded to a whole seconds.

Improvements here are 4-5X!

## Regression

No

## How Has This Been Tested?

The results with master and this PR on the above queries were compared for byte-to-byte exactness by hashing the mc output with md5sum.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Performance enhancement

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by donatello** [comment]
Please note that this PR depends on https://github.com/minio/minio/pull/7102 and can only be merged after that PR so marking it as blocked.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by balamurugana — DISMISSED** [review]
Approving this PR is pre-refactoring as https://github.com/minio/minio/pull/7102 is already approved.

**Comment by donatello** [comment]
> Approving this PR is pre-refactoring as #7102 is already approved.

@balamurugana Could you re-approve #7102 as it got updated.

**Comment by donatello** [comment]
This is unblocked for merge now

**Review by harshavardhana — APPROVED** [review]

**Review by balamurugana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Pull request merged**
