### PR TITLE
Fix unicode delimiters not working with s3select

### PR DESCRIPTION
**Pull request by kanagarajkm**
When unicode character is used as a delimiter, for example `╦`,
XML parsing is failed. This is now fixed.

## Motivation and Context
Unicode characters should be supported as delimiters in select.

## How to test this PR?
1. Create a data.csv file with `╦` as the field delimiter
2. Upload it to minio, `mc cp data.csv local/bucket/data.csv`
3. Run this command `mc sql --csv-input "rd=\n,fh=IGNORE,fd=╦"  --query "select s._1 from S3Object s" local/bucket/data.csv`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [x] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#beec110d-a358-425b-8f30-16373088f289) |
<a name="beec110d-a358-425b-8f30-16373088f289"></a>
### 7931-ca1ca9f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32705
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 108caf3133f1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 6 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 58 seconds
(10/14) Running minio-java tests ... FAILED in 36 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName, Integer expires)",
  "duration": 29,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.59:32705/minio-java-test-38bu059/minio-java-test-2ou4pug?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190715%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190715T140539Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=dc49922aecc5167153331d9d7bae8868aee7ac21211c07bdf83916a7474c53e3}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-2ou4pug</Key><BucketName>minio-java-test-38bu059</BucketName><Resource>/minio-java-test-38bu059/minio-java-test-2ou4pug</Resource><RequestId>15B199B2E0BAA0B4</RequestId><HostId>a7e5a9eb-4ea2-484e-805c-65fee9338f52</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test2(FunctionalTest.java:1803), FunctionalTest.runTests(FunctionalTest.java:2995), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a168b9bc-930b-4677-af3f-9085310e47ea) |
| mint-dist-xl.sh | :x: [more...](#d72adf41-7150-480d-afd6-587cc7aa2f31) |
<a name="a168b9bc-930b-4677-af3f-9085310e47ea"></a>
### 7931-13f8163/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31552
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1f3b08fb4169:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yksqlvusgkkx39",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12502,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31552/aws-sdk-go-test-yksqlvusgkkx39: dial tcp 72.28.97.57:31552: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d72adf41-7150-480d-afd6-587cc7aa2f31"></a>
### 7931-13f8163/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30135
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 063f0901fbfe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 8 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 4 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 2 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 724,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3gri9j5, objectName=minio-java-test-uuenhg, resource=/minio-java-test-3gri9j5/minio-java-test-uuenhg, requestId=15B1D743FDBDA54A, hostId=482c0fdc-7fa5-48ac-9589-4eaf17da8c83)\nrequest={method=DELETE, url=http://72.28.97.59:30135/minio-java-test-3gri9j5/minio-java-test-uuenhg?uploadId=454c9c9a-d10f-4747-a43c-791c1cb5a5c5, headers=Host: 72.28.97.59:30135\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190716T085352Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190716/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-16T08-33-42Z\nVary: Origin\nX-Amz-Request-Id: 15B1D743FDBDA54A\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jul 2019 08:53:52 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#5bb48785-976f-48c3-9e70-71a08168e468) |
| mint-large-bucket.sh | :x: [more...](#5120e696-301e-479b-8237-d31b3927da42) |
| mint-dist-xl.sh | :x: [more...](#04ff0410-cff2-49f7-b19e-ea45b2c4a59a) |
<a name="5bb48785-976f-48c3-9e70-71a08168e468"></a>
### 7931-796f143/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30513
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6276abb21611:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-kaq4bzwbvn4ow5",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12278,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30513/aws-sdk-go-test-kaq4bzwbvn4ow5: dial tcp 72.28.97.57:30513: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5120e696-301e-479b-8237-d31b3927da42"></a>
### 7931-796f143/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31441
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0cd27b212e24:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 3 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 35 seconds
{
  "name": "mc",
  "duration": "122747",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-26897 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-30675  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-30675/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-30675/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-30675/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-30675/datafile-1-b`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-30675/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-30675/datafile-10-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-30675/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-30675/datafile-10-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-30675/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-30675/datafile-5-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-30675/datafile-11-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-30675/datafile-65-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-30675/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-30675/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-30675/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 472.80 MiB, Speed: 3.85 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="04ff0410-cff2-49f7-b19e-ea45b2c4a59a"></a>
### 7931-796f143/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30572
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bafe0063c831:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-w9gzfywalse1xx",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12121,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30572/aws-sdk-go-test-w9gzfywalse1xx: dial tcp 72.28.97.57:30572: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a4e18629-2659-41b6-8541-701b2b9c999a) |
| mint-compression-fs.sh | :x: [more...](#3eb79c6f-717d-420f-b8d1-e2ecfb9bca31) |
| mint-dist-xl.sh | :x: [more...](#0a270484-8e0c-4f89-bee7-2a9595ebf8a2) |
<a name="3eb79c6f-717d-420f-b8d1-e2ecfb9bca31"></a>
### 7931-cb1858f/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31498
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d904cd53a05:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-g2gxrw5esjaw6w",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12588,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31498/aws-sdk-go-test-g2gxrw5esjaw6w: dial tcp 72.28.97.57:31498: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="a4e18629-2659-41b6-8541-701b2b9c999a"></a>
### 7931-cb1858f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32498
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 857d0b8a88e7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... FAILED in 57 seconds
{
  "name": "awscli",
  "duration": 1157,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 14 tests successfully.
```
<a name="0a270484-8e0c-4f89-bee7-2a9595ebf8a2"></a>
### 7931-cb1858f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31450
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 111b5f383081:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 0 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 17 seconds
(10/14) Running minio-java tests ... FAILED in 49 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 242,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-35e3pr4, objectName=minio-java-test-25d3rh4, resource=/minio-java-test-35e3pr4/minio-java-test-25d3rh4, requestId=15B1DEBE25851CF3, hostId=a9bb9484-b637-4b74-9a0f-302197e2cd0c)\nrequest={method=DELETE, url=http://72.28.97.51:31450/minio-java-test-35e3pr4/minio-java-test-25d3rh4?uploadId=84fad322-126f-4d21-9fee-d819d9782716, headers=Host: 72.28.97.51:31450\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190716T111053Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190716/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-16T10-51-09Z\nVary: Origin\nX-Amz-Request-Id: 15B1DEBE25851CF3\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jul 2019 11:10:53 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Review by donatello — APPROVED** [review]

**Comment by harshavardhana** [comment]
Looks like this fix is causing Gateway failure. @kanagarajkm

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#dba41c8a-f88e-4d21-a951-f53a30e88489) |
| mint-compression-dist-xl.sh | :x: [more...](#99fed034-71bf-457b-9e79-9c80d23bfdc2) |
| mint-dist-xl.sh | :x: [more...](#cd9ea556-921d-4375-87f7-0cd781b18861) |
<a name="dba41c8a-f88e-4d21-a951-f53a30e88489"></a>
### 7931-e6d5ea1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30238
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 087601644b21:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 27 seconds
{
  "name": "mc",
  "duration": "111216",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7826 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-7249  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-7249/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-7249/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-7249/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-7249/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-7249/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-7249/datafile-100-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-7249/datafile-1.03-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-7249/datafile-129-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-7249/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-7249/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-7249/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-7249/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-7249/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-7249/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-7249/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 480.49 MiB, Speed: 4.32 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="cd9ea556-921d-4375-87f7-0cd781b18861"></a>
### 7931-e6d5ea1/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30294
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cb7506a0714e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 52 seconds
(10/14) Running minio-java tests ... FAILED in 30 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 1042,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3cht722, objectName=minio-java-test-34p2391, resource=/minio-java-test-3cht722/minio-java-test-34p2391, requestId=15B21AB3F0E9B450, hostId=a90d6357-0ff0-47ae-a334-03c245a14326)\nrequest={method=DELETE, url=http://72.28.97.52:30294/minio-java-test-3cht722/minio-java-test-34p2391?uploadId=ff7a6866-3c1c-4e4c-b5ee-a436033ff575, headers=Host: 72.28.97.52:30294\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190717T052940Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190717/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-17T05-10-57Z\nVary: Origin\nX-Amz-Request-Id: 15B21AB3F0E9B450\nX-Xss-Protection: 1; mode=block\nDate: Wed, 17 Jul 2019 05:29:41 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="99fed034-71bf-457b-9e79-9c80d23bfdc2"></a>
### 7931-e6d5ea1/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32183
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2fd3881a5ee6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0mevxcyjsxs665",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12489,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32183/aws-sdk-go-test-0mevxcyjsxs665: dial tcp 72.28.97.57:32183: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by kanagarajkm** [comment]
@harshavardhana gateway tests failure is fixed

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
