### PR TITLE
fix: validate deployment id when adding peer clusters

### LINKED ISSUE #15573: runtime error: index out of range when site repication configuration
## NOTE

Created 3 Minio single node helm installs with **MinIO VERSION  2022-08-13T21:54:44Z**

when creating site replication from the only minio with a bucket created I got this error in minio logs(the one I trigered add replication from console UI

```
panic: "PUT /minio/admin/v3/site-replication/add": runtime error: index out of range [-1]                                                          │
│ goroutine 272884 [running]:                                                                                                                        │
│ runtime/debug.Stack()                                                                                                                              │
│     runtime/debug/stack.go:24 +0x65                                                                                                                │
│ github.com/minio/minio/cmd.setCriticalErrorHandler.func1.1()                                                                                       │
│     github.com/minio/minio/cmd/generic-handlers.go:578 +0x8e                                                                                       │
│ panic({0x2621420, 0xc0137327f8})                                                                                                                   │
│     runtime/panic.go:838 +0x207                                                                                                                    │
│ github.com/minio/minio/cmd.(*SiteReplicationSys).AddPeerClusters(0x4d9cde0?, {0x4d9cde0, 0xc002245c50}, {0xc0005f7a00?, 0x2281840?, 0xc000e767f8?} │
│     github.com/minio/minio/cmd/site-replication.go:414 +0x1850                                                                                     │
│ github.com/minio/minio/cmd.adminAPIHandlers.SiteReplicationAdd({}, {0x4d99080, 0xc002f16be0}, 0xc0005f7900)                                        │
│     github.com/minio/minio/cmd/admin-handlers-site-replication.go:55 +0x2fc                                                                        ││ net/http.HandlerFunc.ServeHTTP(...)                                                                                                                ││     net/http/server.go:2084                                                                                                                        ││ github.com/minio/minio/cmd.httpTrace.func1({0x4d99080, 0xc002f16be0}, 0xc0005f7900)                                                                ││     github.com/minio/minio/cmd/http-tracer.go:238 +0x1af                                                                                           ││ net/http.HandlerFunc.ServeHTTP(0x2313780?, {0x4d99080?, 0xc002f16be0?}, 0x4?)                                                                      │
│     net/http/server.go:2084 +0x2f                                                                                                                  │
│ github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x4d99080, 0xc002f16be0}, 0xc00102ae00?)                                                  ││     github.com/klauspost/compress@v1.15.9/gzhttp/compress.go:391 +0x347                                                                            ││ net/http.HandlerFunc.ServeHTTP(0x7fe59d4d4200?, {0x4d99080?, 0xc002f16be0?}, 0x417aeb?)                                                            ││     net/http/server.go:2084 +0x2f                                                                                                                  ││ github.com/minio/minio/cmd.setBucketForwardingHandler.func1({0x4d99080, 0xc002f16be0}, 0xc0005f7900)                                               ││     github.com/minio/minio/cmd/generic-handlers.go:486 +0x22d                                                                                      ││ net/http.HandlerFunc.ServeHTTP(0x4d99020?, {0x4d99080?, 0xc002f16be0?}, 0x10?)                                                                     ││     net/http/server.go:2084 +0x2f                                                                                                                  ││ github.com/minio/minio/cmd.addCustomHeaders.func1({0x4d99020, 0xc000e766c0}, 0xc01576edc0?)                                                        ││     github.com/minio/minio/cmd/generic-handlers.go:561 +0x3c2                                                                                      ││ net/http.HandlerFunc.ServeHTTP(0x26b7340?, {0x4d99020?, 0xc000e766c0?}, 0x39?)                                                                     ││     net/http/server.go:2084 +0x2f
```

Site replication config
image

### PR DESCRIPTION
**Pull request by poornas**
Fixes: #15573

## Motivation and Context
Guard against panic

## How to test this PR?
Can't happen unless drive replacement caused format.json to be recreated

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#a3cc54b4-a2ab-428e-b884-ea3eb2645f3b) |
| mint-dist-erasure.sh | :x: [more...](#6499ffd5-0fc8-464c-96ef-d477054a826c) |
<a name="6499ffd5-0fc8-464c-96ef-d477054a826c"></a>
### 15591-bf5d8cf/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:32642
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 29 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(9/14) Running minio-java tests ... done in 31 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 36 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 2,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 21 seconds
(11/14) Running s3cmd tests ... done in 25 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 13 out of 14 tests successfully.
```
<a name="a3cc54b4-a2ab-428e-b884-ea3eb2645f3b"></a>
### 15591-bf5d8cf/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:30971
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 24 seconds
(8/14) Running minio-go tests ... done in 43 seconds
(9/14) Running minio-java tests ... done in 31 seconds
(10/14) Running minio-js tests ... 
Aborting Mint...
Running with
SERVER_ENDPOINT:      minio-k8s4:30971
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... FAILED in 42 seconds
{"name": "awscli", "duration": 1458, "function": "aws --endpoint-url http://minio-k8s4:30971 s3api put-bucket-lifecycle-configuration --bucket awscli-mint-test-bucket-31232 --lifecycle-configuration file:///tmp/lifecycle.json\n", "status": "FAIL", "error": "Error parsing parameter '--lifecycle-configuration': Invalid JSON: Extra data: line 2 column 1 (char 129)JSON received: { "Rules": [ { "Expiration": { "Days": 365 },"ID": "Bucketlifecycle test", "Filter": { "Prefix": "" }, "Status": "Enabled" } ] }{ "Rules": [ { "Expiration": { "Days": 365 },"ID": "Bucketlifecycle test", "Filter": { "Prefix": "" }, "Status": "Enabled" } ] }"}
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... done in 25 seconds
(7/14) Running minio-go tests ... done in 40 seconds
(8/14) Running minio-java tests ... done in 31 seconds
FAILED in 16 minutes and 46 seconds
(9/14) Running minio-py tests ... done in 1 minutes and 1 seconds
(10/14) Running s3cmd tests ... done in 1 minutes and 6 seconds
(11/14) Running s3select tests ... done in 3 seconds
(12/14) Running versioning tests ... done in 0 seconds

Executed 12 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by segator** [comment]
How can I actually test this, is not yet released I guess

**Comment by harshavardhana** [comment]
> How can I actually test this, is not yet released I guess

Compile from source @segator

**Comment by segator** [comment]
@harshavardhana  is this PR released?

**Comment by vadmeste** [comment]
> @harshavardhana is this PR released?

Yes

**Pull request merged**
