### PR TITLE
Add node address information to logs

### PR DESCRIPTION
**Pull request by krisis**
## Description
Adds node address to MinIO console/http logs

## Motivation and Context
The ability to identify the node logging the error message would help in debugging issues, especially in distributed MinIO deployments.

## How to test this PR?
1. Start a MinIO server
2. Try to delete a bucket that has objects in it
3. Verify that the log message on console or http target contains
    node address information

E.g
```
API: webDeleteBucket(bucket=test)
Time: 14:48:34 PDT 07/17/2019
DeploymentID: 96f39533-866e-431a-8724-0004e9485729
RemoteHost: 127.0.0.1
Host: localhost:9000
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Error: Bucket not empty: test
       3: cmd/web-handlers.go:2013:cmd.toWebAPIError()
       2: cmd/web-handlers.go:1893:cmd.toJSONError()
       1: cmd/web-handlers.go:265:cmd.(*webAPIHandlers).DeleteBucket()
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#762f18e2-ae7c-4930-a1e0-c5625d593f88) |
| mint-fs.sh | :x: [more...](#9b311439-8202-46cb-86f8-214101e8323d) |
| mint-dist-xl.sh | :x: [more...](#78b5ca56-4e44-46f3-ab82-f78158a13f4b) |
<a name="9b311439-8202-46cb-86f8-214101e8323d"></a>
### 7941-189d7af/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32618
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1be2dfdff327:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 40 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 4 seconds
(10/14) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, String filename)",
  "args": "filename: 6MB",
  "duration": 437,
  "status": "FAIL",
  "error": "java.io.EOFException >>> [okio.RealBufferedSink.write(RealBufferedSink.java:115), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:77), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264), okhttp3.RealCall.execute(RealCall.java:93), io.minio.MinioClient.executeReq(MinioClient.java:1111), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executePut(MinioClient.java:1405), io.minio.MinioClient.executePut(MinioClient.java:1427), io.minio.MinioClient.putObject(MinioClient.java:4216), io.minio.MinioClient.putObject(MinioClient.java:4328), io.minio.MinioClient.putObject(MinioClient.java:3591), FunctionalTest.putObject_test2(FunctionalTest.java:440), FunctionalTest.runTests(FunctionalTest.java:2957), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="78b5ca56-4e44-46f3-ab82-f78158a13f4b"></a>
### 7941-189d7af/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32054
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2c155b3c5c38:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 48 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 15 seconds
(10/14) Running minio-java tests ... FAILED in 43 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 826,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1902r9v, objectName=minio-java-test-15k7mp0, resource=/minio-java-test-1902r9v/minio-java-test-15k7mp0, requestId=15B25306421E283D, hostId=c4cfdefb-2e83-4f30-aeeb-f700b062d9c4)\nrequest={method=DELETE, url=http://72.28.97.51:32054/minio-java-test-1902r9v/minio-java-test-15k7mp0?uploadId=8cd4984a-0f82-49f1-b5f9-1da567f0cc19, headers=Host: 72.28.97.51:32054\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190717T224146Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190717/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-17T22-23-17Z\nVary: Origin\nX-Amz-Request-Id: 15B25306421E283D\nX-Xss-Protection: 1; mode=block\nDate: Wed, 17 Jul 2019 22:41:47 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="762f18e2-ae7c-4930-a1e0-c5625d593f88"></a>
### 7941-189d7af/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32564
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 08915b732d69:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 34 seconds
{
  "name": "mc",
  "duration": "115240",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-18175 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-17424  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-17424/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-17424/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-17424/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-17424/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-17424/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-17424/datafile-100-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-17424/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-17424/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-17424/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-17424/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-17424/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-17424/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-17424/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-17424/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-17424/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 518.77 MiB, Speed: 4.50 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Review by kannappanr — APPROVED** [review]
LGTM.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9acc4bfc-dbe8-495f-9e68-b30284bf2b11) |
| mint-dist-xl.sh | :x: [more...](#a9138f02-4d45-4005-a5e7-9bf4035f3b52) |
<a name="9acc4bfc-dbe8-495f-9e68-b30284bf2b11"></a>
### 7941-a790a02/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30885
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f9fcb8cae9f6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 33 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 42 seconds
{
  "name": "mc",
  "duration": "120743",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-20652 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-26580  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-26580/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-26580/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-26580/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-26580/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-26580/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-26580/datafile-10-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-26580/datafile-33-kB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-26580/datafile-1-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-26580/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-26580/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-26580/datafile-5-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-26580/datafile-100-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-26580/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-26580/datafile-65-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-26580/datafile-5243880-b`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 486.58 MiB, Speed: 4.03 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="a9138f02-4d45-4005-a5e7-9bf4035f3b52"></a>
### 7941-a790a02/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32250
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 20b002b760d6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 19 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName)",
  "duration": 1031,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-25npg1e, objectName=minio-java-test-7uikbq, resource=/minio-java-test-25npg1e/minio-java-test-7uikbq, requestId=15B257879BFBECBB, hostId=12fab91a-0ec8-4e97-94ef-a60b209afac9)\nrequest={method=DELETE, url=http://72.28.97.54:32250/minio-java-test-25npg1e/minio-java-test-7uikbq?uploadId=e2b8e90a-336b-4b79-9ba9-26a40cda8edf, headers=Host: 72.28.97.54:32250\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190718T000420Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190718/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-17T23-44-30Z\nVary: Origin\nX-Amz-Request-Id: 15B257879BFBECBB\nX-Xss-Protection: 1; mode=block\nDate: Thu, 18 Jul 2019 00:04:21 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test1(FunctionalTest.java:1601), FunctionalTest.runTests(FunctionalTest.java:2988), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Review by poornas — APPROVED** [review]
LGTM

**Pull request merged**
