### PR TITLE
cache DiskInfo() metrics call separately

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
cache DiskInfo() metrics call separately

## Motivation and Context
caching variables is not a good idea,
introduce another cache for metrics
DiskInfo() alone.

## How to test this PR?
Just a bug-fix nothing should change.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by klauspost** [comment]
I have rewritten this for websockets.

Since we are fetching it only every second, I just always fetch metrics remotely.

**Comment by harshavardhana** [comment]
> I have rewritten this for websockets.
> 
> Since we are fetching it only every second, I just always fetch metrics remotely.

No, we don't need to @klauspost we shouldn't send it when it's not needed. a DiskInfo() is used without this information for the most part. The metrics itself is a large information that we should avoid over the network IMO.

**Comment by klauspost** [comment]
@harshavardhana Sure, if it is that slow. I will integrate it.

**Comment by klauspost** [comment]
@harshavardhana Added here: https://github.com/minio/minio/pull/18263/commits/773630603b01598a771194534cde07076272a3a4 (set a 10 second timeout)

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
