### PR TITLE
only allow decryption of etag for only sse-s3

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
only allow decryption of etag for only sse-s3

## Motivation and Context
replaces #17304

## How to test this PR?
minio-go functional tests and `mc` tests. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by klauspost** [comment]
Yeah, I think this is the solution we are looking for instead of the other way around. I will test. 👍🏼

**Comment by harshavardhana** [comment]
Seems like the tests pass properly now. @klauspost

**Comment by klauspost** [comment]
@harshavardhana Similar to the other issue, I am a bit worried if we return the decrypted hash incorrectly.... I would like @aead to review it.

**Comment by harshavardhana** [comment]
> @harshavardhana Similar to the other issue, I am a bit worried if we return the decrypted hash incorrectly.... I would like @aead to review it.

Sure, but we are not returning any decryption for anything other than SSE-S3 @klauspost 

Just matching what is returned in PutObjectPart() v/s what is verified in CompleteMultipart

**Review by aead — APPROVED** [review]
👍

**Comment by harshavardhana** [comment]
PTAL @poornas @vadmeste

**Review by poornas — APPROVED** [review]

**Pull request merged**
