### PR TITLE
Update go-sql-driver/mysql package

### PR DESCRIPTION
**Pull request by krisis**
## Description

This change updates the go-sql-driver/mysql package we vendorize to its latest version to include support MySQL 8.x configuration.

## Motivation and Context

The version of mysql driver package we have vendorized to support bucket notifications to MySQL doesn't support configurations supported by MySQL 8.x. See #6999 for more information

## Regression
 No

## How Has This Been Tested?

Waiting for user to provide sample configuration to test with.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Is this still a WIP if not can you fix the title @krisis ?

**Comment by krisis** [comment]
@harshavardhana, I haven't tested this with the configuration the reporter opened this issue for. That's why I have marked this WIP.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by krisis** [comment]
I am inclined to taking this PR once the travis-ci build passes. Removing WIP

**Review by harshavardhana — APPROVED** [review]
LGTM

**Review by nitisht — APPROVED** [review]

**Pull request merged**
