### PR TITLE
make the crypto error type a native go time

### PR DESCRIPTION
**Pull request by aead**
## Description
This commit makes the `crypto.Error` type a native go (string)
type. That allows us to define error values as constants instead
of variables.

For reference see:
 - https://twitter.com/_aead_/status/1118170258215514115?s=20
 - https://dave.cheney.net/2016/04/07/constant-errors

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
based on this can we add code such that when we see crypto.Error in toAPIError() we can write a proper S3 error? 

we can use 
```
var cerr = crypto.Error{}
if errors.As(err, &cerr) {
    return string(cerr)
}
```

We can also have `crypto.Error{Code, Message, StatusCode}` for a more concrete type here.

**Review by klauspost — APPROVED** [review]
Good change 👍

**Review by krisis — APPROVED** [review]

**Comment by aead** [comment]
@harshavardhana In general yes. We already have [ÈrrObjectTampered](https://github.com/minio/minio/blob/master/cmd/api-errors.go#L1680) - However, we can improve at this front to. We had a couple of error translation issues in the past (500 Internal Error) and I want to clean up some crypto. related code...

**Comment by harshavardhana** [comment]
> @harshavardhana In general yes. We already have [ÈrrObjectTampered](https://github.com/minio/minio/blob/master/cmd/api-errors.go#L1680) - However, we can improve at this front to. We had a couple of error translation issues in the past (500 Internal Error) and I want to clean up some crypto. related code...

Yes, that was my idea, we can stick to even what is there in this PR just that it is nice for users to see a better error Message: 

My idea is this 

```diff
diff --git a/cmd/api-errors.go b/cmd/api-errors.go
index cd0deaa96..ae3167d6d 100644
--- a/cmd/api-errors.go
+++ b/cmd/api-errors.go
@@ -1723,6 +1723,12 @@ func toAPIError(ctx context.Context, err error) APIError {
                // their internal error types. This code is only
                // useful with gateway implementations.
                switch e := err.(type) {
+               case crypto.Error:
+                       apiErr = APIError{
+                               Code:           "XVaultInternalError",
+                               Description:    string(e),
+                               HTTPStatusCode: http.StatusBadRequest,
+                       }
```

We can improve this over time. But this is super helpful for our users such that the clients don't retry for vault errors - when it's not possible. This PR can have this change.

**Review by harshavardhana — APPROVED** [review]

**Comment by kannappanr** [comment]
Waiting for Mint Auto to finish before merging

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e9ed21bb-23dc-4da8-b322-dda270079d65) |
| mint-gateway-nas.sh | :x: [more...](#9a8e5085-7a8b-4f06-b254-7660aad0f72d) |
<a name="e9ed21bb-23dc-4da8-b322-dda270079d65"></a>
### 8267-b658650/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31430
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5cc2832cb59b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 55 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 26 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 50 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 4 seconds
{
  "args": {},
  "duration": 83494,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="9a8e5085-7a8b-4f06-b254-7660aad0f72d"></a>
### 8267-b658650/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31871
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3f44e8eea3a7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 56 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 11 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 15 seconds
(11/14) Running minio-js tests ... done in 33 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 34 seconds
{
  "args": {
    "response.status": 403,
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>2889cd2e-8cfc-4302-a778-be7b6b78aaf0</Key><BucketName>minio-py-test-5f168fd3-307e-4b17-ad4d-983c45d0d09b</BucketName><Resource>/minio-py-test-5f168fd3-307e-4b17-ad4d-983c45d0d09b/2889cd2e-8cfc-4302-a778-be7b6b78aaf0</Resource><RequestId>15C63A24A22DB03F</RequestId><HostId></HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"404\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-20T18-28-25Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C63A24A22DB03F\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 20 Sep 2019 18:50:49 GMT\"]}}",
    "response.reason": "Forbidden",
    "object_name": "2889cd2e-8cfc-4302-a778-be7b6b78aaf0",
    "bucket_name": "minio-py-test-5f168fd3-307e-4b17-ad4d-983c45d0d09b",
    "presigned_get_object_url": "http://72.28.97.54:31871/minio-py-test-5f168fd3-307e-4b17-ad4d-983c45d0d09b/2889cd2e-8cfc-4302-a778-be7b6b78aaf0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190920%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190920T185043Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=ef3452574a24f5c0a2d7ca57c7d14928aeefed462c02e7ebf384cbbf8332b288"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 58,
  "message": "AccessDenied: message: Access Denied",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```

**Pull request merged**
