### PR TITLE
gcs: check error on object writer close

### LINKED ISSUE #7605: GCS gateway: PutObject sometimes errors with NoSuchKey
## Expected Behavior

We upload ~10,000 files per day from 3 Python services to a pair of minio GCS gateways on GKS (Kubernetes). File sizes range from 1kb to 2GB; median is perhaps 100kb. We use `boto3` to upload them (a single TransferManager with long-living connections), but previously we've used `minio-py` as well.

We expect all `PutObject` calls to succeed -- or to _report the correct error message_ if they don't.

## Current Behavior

Once or twice per week, PutObject fails with: `botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the PutObject operation: The specified key does not exist.`

This is certainly the wrong error message. (Nothing differentiates the keys that fail from the keys that upload correctly.)

This happens with `botocore`, and it happened with `minio-py` previously.

After this error, the file exists in Google Storage. I don't know whether it's truncated.

## Possible Solution

I can't reproduce this outside of production. (Perhaps because it's so rare?) But I can suggest why the error message is wrong.

[gateway-gcs.go:PutObject()](https://github.com/minio/minio/blob/c113d4e49c621dd45b1cbc2947c51069255808a1/cmd/gateway/gcs/gateway-gcs.go#L917-L926) seems to ignore error reports from GCS storage writers.

The code looks like this:

```go
	// Close the object writer upon success.
	w.Close()

	attrs, err := object.Attrs(ctx)
	if err != nil {
		logger.LogIf(ctx, err)
		return minio.ObjectInfo{}, gcsToObjectError(err, bucket, key)
	}
```

This ignores an error from [writer.Close()](https://godoc.org/cloud.google.com/go/storage#Writer.Close). Also, it makes an [unnecessary HTTP request](https://godoc.org/cloud.google.com/go/storage#ObjectHandle.Attrs) (`object.Attrs(ctx)`) -- if my reading of the [Writer docs](https://godoc.org/cloud.google.com/go/storage#Writer.Attrs) is correct, `attrs := w.Attrs()` ought to suffice. That extra HTTP request can (and does) throw nonsense exceptions like `NoSuchKey`.

Shouldn't the code be:

```go
	// Close the object writer upon success.
	err = w.Close()
        if err != nil {
		logger.LogIf(ctx, err)
		return minio.ObjectInfo{}, gcsToObjectError(err, bucket, key)
	}

        attrs := w.Attrs()
```

(Ditto for `PutObjectPart()`.)

I'm no expert in Go, S3, Google Storage or minio; but I'd expect this to at least report the correct error message?

## Steps to Reproduce (for bugs)

Unfortunately, I can't reproduce this bug on demand. We just keep running our service, and if the bug doesn't occur for a month I'd assume it's fixed.

## Context

Retry can circumvent the problem. But I'm loath to retry blindly -- I want to see the correct error message first.

## Regression

Is this issue a regression? No.

## Your Environment

* Version used: `minio/minio:RELEASE.2019-04-18T21-44-59Z`
* Environment name and version: `GKS 1.11.8-gke.6`
* Link to your project: https://github.com/CJWorkbench/cjworkbench (`server/minio.py`)

### PR DESCRIPTION
**Pull request by poornas**
Fixes #7605. Object metadata should be written to storage
only when the object was written successfully

## Motivation and Context

As mentioned in referenced issue, updating metadata attributes when backend has not saved object would give a misleading error message. PutObject() can also get the metadata from object writer on successful Close() instead of making another call to storage backend to get the object attrs. 
## Regression
 No (implementation bug)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by krisis — APPROVED** [review]

**Comment by kannappanr** [comment]
ping @vadmeste

**Comment by vadmeste** [comment]
@poornas can I privately get a GCS account to test this PR ?

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Pull request merged**
