### PR TITLE
update rulesguard with new rules

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
update rulesguard with new rules

## Motivation and Context
fix issues after updating rulesguard with new rules

## How to test this PR?
Nothing special all functionality should remain the same

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [x] Unit tests needed

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#3cffce61-5981-4f32-b6b7-d2787d983a2b) |
| mint-gateway-azure.sh | :x: [more...](#b2504790-8e89-47da-9148-a1feaca916ee) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#f6536fab-b590-40d3-b5d9-bf8137a5643d) |
<a name="b2504790-8e89-47da-9148-a1feaca916ee"></a>
### 10392-5934d93/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30207
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3c2afb3efe17:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 25 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 43 seconds
{
  "name": "awscli",
  "duration": 3795,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:30207 s3api copy-object --bucket awscli-mint-test-bucket-11116 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-11116/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected ae9a3f1d83c6d5c7e2f1abff06064890, got 0x8D84E1043FD4E64-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 7 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 38 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 50 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 42 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 44 seconds
(11/15) Running minio-py tests ... done in 13 minutes and 6 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 13 seconds
(13/15) Running s3select tests ... done in 54 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="f6536fab-b590-40d3-b5d9-bf8137a5643d"></a>
### 10392-5934d93/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="3cffce61-5981-4f32-b6b7-d2787d983a2b"></a>
### 10392-5934d93/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a4659e5b-d4e1-47f9-9af6-b3b91f7d805b) |
| mint-gateway-s3.sh | :x: [more...](#88ca9db3-7bd1-48c3-9961-0f6f73f49e54) |
| mint-gateway-azure.sh | :x: [more...](#23f75dcc-db44-4317-92e1-677122d3a44c) |
<a name="23f75dcc-db44-4317-92e1-677122d3a44c"></a>
### 10392-80d173d/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31431
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a4121881c334:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 58 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 44 seconds
{
  "name": "awscli",
  "duration": 3712,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:31431 s3api copy-object --bucket awscli-mint-test-bucket-10881 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-10881/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected ae9a3f1d83c6d5c7e2f1abff06064890, got 0x8D84E512919EA8B-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 15 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 32 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 42 seconds
{
  "args": {
    "bucketName": "minio-go-test-1cyj6z3z0djdo4o4",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 682,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 7 minutes and 11 seconds
(9/15) Running minio-js tests ... FAILED in 48 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 12 minutes and 38 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 8 seconds
(11/15) Running s3select tests ... done in 34 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="88ca9db3-7bd1-48c3-9961-0f6f73f49e54"></a>
### 10392-80d173d/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31912
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3236015c5738:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 16 minutes and 1 seconds
{
  "name": "mc",
  "duration": "941660",
  "function": "test_find",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... done in 28 seconds
(9/15) Running minio-java tests ... done in 16 seconds
(10/15) Running minio-js tests ... done in 30 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 9 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 0 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="a4659e5b-d4e1-47f9-9af6-b3b91f7d805b"></a>
### 10392-80d173d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31319
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 106b9ece04f6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 17 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 58 seconds
(8/15) Running minio-dotnet tests ... done in 48 seconds
(9/15) Running minio-go tests ... FAILED in 16 minutes and 49 seconds
{
  "args": {
    "bucketName": "minio-go-test-hk09kuas6qm1jhqz",
    "fileName": "/mint/data/datafile-129-MB",
    "location": "us-east-1",
    "objectName": "minio-go-test-hk09kuas6qm1jhqzFPutObject-GTar",
    "opts": {
      "UserMetadata": null,
      "UserTags": null,
      "Progress": null,
      "ContentType": "",
      "ContentEncoding": "",
      "ContentDisposition": "",
      "ContentLanguage": "",
      "CacheControl": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "ServerSideEncryption": null,
      "NumThreads": 0,
      "StorageClass": "",
      "WebsiteRedirectLocation": "",
      "PartSize": 0,
      "LegalHold": "",
      "SendContentMd5": false,
      "DisableMultipart": false,
      "ReplicationVersionID": "",
      "ReplicationETag": "",
      "ReplicationStatus": "",
      "ReplicationMTime": "0001-01-01T00:00:00Z"
    }
  },
  "duration": 961921,
  "error": "Put \"http://minio-dev7.minio.io:31319/minio-go-test-hk09kuas6qm1jhqz/minio-go-test-hk09kuas6qm1jhqzFPutObject-GTar?partNumber=2&uploadId=7045e330-e48a-48ac-a05f-e5a4bd91bd88\": net/http: timeout awaiting response headers",
  "function": "FPutObject(bucketName, objectName, fileName, opts)",
  "message": "FPutObject failed",
  "name": "minio-go: testFPutObject",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 1 minutes and 15 seconds
(10/15) Running minio-js tests ... done in 48 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 8 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10392-80d173d

**Review by nitisht — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#7be43814-deff-407e-a3c1-1ef96b041395) |
| mint-zoned.sh | :x: [more...](#02267b1e-49ec-417f-9d66-bbfb6fa1ace5) |
| mint-gateway-nas.sh | :x: [more...](#fdb5c15e-8388-4e78-afd5-5bc91f5c56e6) |
<a name="02267b1e-49ec-417f-9d66-bbfb6fa1ace5"></a>
### 10392-498b87e/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30817
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 71ab3e55ca6e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 21 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 40 seconds
(8/15) Running minio-dotnet tests ... done in 47 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 17 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 19 seconds
(11/15) Running minio-js tests ... done in 52 seconds
(12/15) Running minio-py tests ... done in 3 minutes and 38 seconds
(13/15) Running s3cmd tests ... FAILED in 23 seconds
{
  "name": "s3cmd",
  "duration": "12874",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="fdb5c15e-8388-4e78-afd5-5bc91f5c56e6"></a>
### 10392-498b87e/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32394
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4ddb0461f283:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 16 minutes and 0 seconds
{
  "name": "mc",
  "duration": "946782",
  "function": "test_mirror_list_objects",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... done in 29 seconds
(9/15) Running minio-java tests ... done in 16 seconds
(10/15) Running minio-js tests ... done in 30 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 3 seconds
(12/15) Running s3cmd tests ... done in 13 seconds
(13/15) Running s3select tests ... done in 1 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="7be43814-deff-407e-a3c1-1ef96b041395"></a>
### 10392-498b87e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31646
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 60a9b255c6cd:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 20 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 55 seconds
{
  "name": "awscli",
  "duration": 3952,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31646 s3api copy-object --bucket awscli-mint-test-bucket-11435 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-11435/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected ae9a3f1d83c6d5c7e2f1abff06064890, got 0x8D84E975CD5E41E-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 47 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 37 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 42 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 36 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 39 seconds
(11/15) Running minio-py tests ... done in 12 minutes and 57 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 13 seconds
(13/15) Running s3select tests ... done in 52 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10392-498b87e

**Review by Praveenrajmani — APPROVED** [review]

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 10392-7d2af06/gopath/src/github.com/minio
+ git -C 10392-7d2af06/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 10392-7d2af06/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 10392-7d2af06/gopath/src/github.com/minio/minio fetch --quiet minio pull/10392/head:pr10392
+ git -C 10392-7d2af06/gopath/src/github.com/minio/minio checkout --quiet pr10392
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/10392-7d2af06/gopath
+ make -C 10392-7d2af06/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/minio/minio-go/v7 v7.0.5-0.20200811211821-14ed05478889
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: downloading go.etcd.io/etcd/v3 v3.3.0-rc.0.0.20200707003333-58bb8ae09f8e
go: downloading github.com/miekg/dns v1.1.8
go: downloading github.com/minio/sio v0.2.0
go: downloading github.com/minio/simdjson-go v0.1.5
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/tinylib/msgp v1.1.2
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/google/uuid v1.1.1
go: downloading golang.org/x/crypto v0.0.0-20200709230013-948cd5f35899
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/klauspost/compress v1.10.3
go: downloading google.golang.org/api v0.5.0
go: downloading golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae
go: downloading github.com/cheggaaa/pb v1.0.28
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.3.0
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/prometheus/client_golang v1.0.0
go: downloading github.com/colinmarc/hdfs/v2 v2.1.1
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/coredns/coredns v1.4.0
go: downloading golang.org/x/net v0.0.0-20200707034311-ab3426394381
go: downloading github.com/gorilla/handlers v1.4.2
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading google.golang.org/grpc v1.26.0
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading github.com/golang/protobuf v1.4.0
go: downloading github.com/prometheus/procfs v0.0.8
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/mattn/go-runewidth v0.0.2
go: downloading github.com/philhofer/fwd v1.0.0
go: downloading github.com/beorn7/perks v1.0.0
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/willf/bitset v1.1.11
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/mattn/go-isatty v0.0.8
go: downloading github.com/prometheus/common v0.4.1
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading go.uber.org/zap v1.14.1
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/klauspost/reedsolomon v1.9.9
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/klauspost/pgzip v1.2.1
go: downloading github.com/minio/md5-simd v1.1.0
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading google.golang.org/protobuf v1.22.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/coreos/go-systemd/v22 v22.0.0
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/rs/xid v1.2.1
go: downloading go.uber.org/multierr v1.5.0
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading go.opencensus.io v0.22.3
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading github.com/beevik/ntp v0.2.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading go.uber.org/atomic v1.6.0
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading github.com/tidwall/match v1.0.1
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/Shopify/sarama v1.24.1
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading github.com/tidwall/pretty v1.0.0
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/nats-io/nkeys v0.1.4
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading gopkg.in/olivere/elastic.v5 v5.0.86
go: downloading github.com/eapache/go-resiliency v1.1.0
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/nats-io/stan.go v0.7.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a
go: downloading github.com/lib/pq v1.7.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/mailru/easyjson v0.7.1
+ docker build --quiet --tag minio/minio:10392-7d2af06 --file 10392-7d2af06/gopath/src/github.com/minio/minio/Dockerfile.dev 10392-7d2af06/gopath/src/github.com/minio/minio
+ docker push minio/minio:10392-7d2af06

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#12cd87f2-3615-4995-8254-4a94c6ec572a) |
<a name="12cd87f2-3615-4995-8254-4a94c6ec572a"></a>
### 10392-3c4494e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30479
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1fc5a9f882e3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 12 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 24 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 47 seconds
{
  "name": "awscli",
  "duration": 3867,
  "function": "aws --endpoint-url http://minio-c2.minio.io:30479 s3api copy-object --bucket awscli-mint-test-bucket-14950 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-14950/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected ae9a3f1d83c6d5c7e2f1abff06064890, got 0x8D84EC3B0FA95FD-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 5 minutes and 13 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 37 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 39 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 29 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 39 seconds
(11/15) Running minio-py tests ... done in 13 minutes and 3 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 17 seconds
(13/15) Running s3select tests ... done in 54 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10392-3c4494e

**Pull request merged**
