### PR TITLE
update-notifier.go: misleading version age message

### PR DESCRIPTION
**Pull request by shoce**
## Description

The message says "released 3 days ago" but it actually means "released 3 days before the latest release"

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by shtripat — APPROVED** [review]
lgtm

**Review by klauspost — APPROVED** [review]

**Comment by harshavardhana** [comment]
Please fix the tests @shoce

**Comment by klauspost** [comment]
```
2023-07-31T06:56:53.1867632Z --- PASS: TestEncodeDecodeTierConfigMgr (0.00s)
2023-07-31T06:56:53.1867777Z === RUN   TestPrepareUpdateMessage
2023-07-31T06:56:53.1868104Z     update-notifier_test.go:88: Testcase 1: output '
2023-07-31T06:56:53.1868551Z          You are running an older version of MinIO released 3 days before the latest release 
2023-07-31T06:56:53.1868891Z          Update: my_download_url 
2023-07-31T06:56:53.1869046Z         
2023-07-31T06:56:53.1869652Z         ' did not contain line 1: 'You are running an older version of MinIO released 3 days ago'
2023-07-31T06:56:53.1869962Z     update-notifier_test.go:88: Testcase 2: output '
2023-07-31T06:56:53.1870424Z          You are running an older version of MinIO released 3 hours before the latest release 
2023-07-31T06:56:53.1871157Z          Update: https://my_download_url_is_huge/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
2023-07-31T06:56:53.1871268Z         
2023-07-31T06:56:53.1872149Z         ' did not contain line 1: 'You are running an older version of MinIO released 3 hours ago'
2023-07-31T06:56:53.1872481Z     update-notifier_test.go:88: Testcase 7: output '
2023-07-31T06:56:53.1872933Z          You are running an older version of MinIO released 1 second before the latest release 
2023-07-31T06:56:53.1873125Z          Update: my_download_url 
2023-07-31T06:56:53.1873200Z         
2023-07-31T06:56:53.1873738Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 second ago'
2023-07-31T06:56:53.1874045Z     update-notifier_test.go:88: Testcase 8: output '
2023-07-31T06:56:53.1874714Z          You are running an older version of MinIO released 37 seconds before the latest release 
2023-07-31T06:56:53.1875097Z          Update: my_download_url 
2023-07-31T06:56:53.1875190Z         
2023-07-31T06:56:53.1876151Z         ' did not contain line 1: 'You are running an older version of MinIO released 37 seconds ago'
2023-07-31T06:56:53.1876560Z     update-notifier_test.go:88: Testcase 9: output '
2023-07-31T06:56:53.1876994Z          You are running an older version of MinIO released 1 minute before the latest release 
2023-07-31T06:56:53.1877188Z          Update: my_download_url 
2023-07-31T06:56:53.1877280Z         
2023-07-31T06:56:53.1878013Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 minute ago'
2023-07-31T06:56:53.1878433Z     update-notifier_test.go:88: Testcase 10: output '
2023-07-31T06:56:53.1878881Z          You are running an older version of MinIO released 1 minute before the latest release 
2023-07-31T06:56:53.1879075Z          Update: my_download_url 
2023-07-31T06:56:53.1879165Z         
2023-07-31T06:56:53.1879699Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 minute ago'
2023-07-31T06:56:53.1880009Z     update-notifier_test.go:88: Testcase 11: output '
2023-07-31T06:56:53.1880472Z          You are running an older version of MinIO released 37 minutes before the latest release 
2023-07-31T06:56:53.1880663Z          Update: my_download_url 
2023-07-31T06:56:53.1880777Z         
2023-07-31T06:56:53.1881645Z         ' did not contain line 1: 'You are running an older version of MinIO released 37 minutes ago'
2023-07-31T06:56:53.1882167Z     update-notifier_test.go:88: Testcase 12: output '
2023-07-31T06:56:53.1882597Z          You are running an older version of MinIO released 1 hour before the latest release 
2023-07-31T06:56:53.1882942Z          Update: my_download_url 
2023-07-31T06:56:53.1883075Z         
2023-07-31T06:56:53.1883658Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 hour ago'
2023-07-31T06:56:53.1883996Z     update-notifier_test.go:88: Testcase 13: output '
2023-07-31T06:56:53.1884437Z          You are running an older version of MinIO released 1 hour before the latest release 
2023-07-31T06:56:53.1884628Z          Update: my_download_url 
2023-07-31T06:56:53.1884714Z         
2023-07-31T06:56:53.1885539Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 hour ago'
2023-07-31T06:56:53.1885891Z     update-notifier_test.go:88: Testcase 14: output '
2023-07-31T06:56:53.1886339Z          You are running an older version of MinIO released 2 hours before the latest release 
2023-07-31T06:56:53.1886646Z          Update: my_download_url 
2023-07-31T06:56:53.1886741Z         
2023-07-31T06:56:53.1887271Z         ' did not contain line 1: 'You are running an older version of MinIO released 2 hours ago'
2023-07-31T06:56:53.1887578Z     update-notifier_test.go:88: Testcase 15: output '
2023-07-31T06:56:53.1888027Z          You are running an older version of MinIO released 1 day before the latest release 
2023-07-31T06:56:53.1888202Z          Update: my_download_url 
2023-07-31T06:56:53.1888293Z         
2023-07-31T06:56:53.1889038Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 day ago'
2023-07-31T06:56:53.1889617Z     update-notifier_test.go:88: Testcase 16: output '
2023-07-31T06:56:53.1890375Z          You are running an older version of MinIO released 1 day before the latest release 
2023-07-31T06:56:53.1890609Z          Update: my_download_url 
2023-07-31T06:56:53.1890698Z         
2023-07-31T06:56:53.1891268Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 day ago'
2023-07-31T06:56:53.1891596Z     update-notifier_test.go:88: Testcase 17: output '
2023-07-31T06:56:53.1892228Z          You are running an older version of MinIO released 2 days before the latest release 
2023-07-31T06:56:53.1892443Z          Update: my_download_url 
2023-07-31T06:56:53.1892683Z         
2023-07-31T06:56:53.1893282Z         ' did not contain line 1: 'You are running an older version of MinIO released 2 days ago'
2023-07-31T06:56:53.1893609Z     update-notifier_test.go:88: Testcase 18: output '
2023-07-31T06:56:53.1894055Z          You are running an older version of MinIO released 1 week before the latest release 
2023-07-31T06:56:53.1894231Z          Update: my_download_url 
2023-07-31T06:56:53.1894321Z         
2023-07-31T06:56:53.1894878Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 week ago'
2023-07-31T06:56:53.1895210Z     update-notifier_test.go:88: Testcase 19: output '
2023-07-31T06:56:53.1895994Z          You are running an older version of MinIO released 1 week before the latest release 
2023-07-31T06:56:53.1896257Z          Update: my_download_url 
2023-07-31T06:56:53.1896349Z         
2023-07-31T06:56:53.1896961Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 week ago'
2023-07-31T06:56:53.1897465Z     update-notifier_test.go:88: Testcase 20: output '
2023-07-31T06:56:53.1897927Z          You are running an older version of MinIO released 2 weeks before the latest release 
2023-07-31T06:56:53.1898116Z          Update: my_download_url 
2023-07-31T06:56:53.1898205Z         
2023-07-31T06:56:53.1898787Z         ' did not contain line 1: 'You are running an older version of MinIO released 2 weeks ago'
2023-07-31T06:56:53.1899282Z     update-notifier_test.go:88: Testcase 21: output '
2023-07-31T06:56:53.1899747Z          You are running an older version of MinIO released 1 month before the latest release 
2023-07-31T06:56:53.1899943Z          Update: my_download_url 
2023-07-31T06:56:53.1900019Z         
2023-07-31T06:56:53.1900611Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 month ago'
2023-07-31T06:56:53.1901051Z     update-notifier_test.go:88: Testcase 22: output '
2023-07-31T06:56:53.1901509Z          You are running an older version of MinIO released 1 month before the latest release 
2023-07-31T06:56:53.1901699Z          Update: my_download_url 
2023-07-31T06:56:53.1901786Z         
2023-07-31T06:56:53.1902309Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 month ago'
2023-07-31T06:56:53.1902813Z     update-notifier_test.go:88: Testcase 23: output '
2023-07-31T06:56:53.1903303Z          You are running an older version of MinIO released 2 months before the latest release 
2023-07-31T06:56:53.1903499Z          Update: my_download_url 
2023-07-31T06:56:53.1903588Z         
2023-07-31T06:56:53.1904547Z         ' did not contain line 1: 'You are running an older version of MinIO released 2 months ago'
2023-07-31T06:56:53.1904946Z     update-notifier_test.go:88: Testcase 24: output '
2023-07-31T06:56:53.1905387Z          You are running an older version of MinIO released 1 year before the latest release 
2023-07-31T06:56:53.1905579Z          Update: my_download_url 
2023-07-31T06:56:53.1905665Z         
2023-07-31T06:56:53.1906376Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 year ago'
2023-07-31T06:56:53.1906781Z     update-notifier_test.go:88: Testcase 25: output '
2023-07-31T06:56:53.1907990Z          You are running an older version of MinIO released 1 year before the latest release 
2023-07-31T06:56:53.1908193Z          Update: my_download_url 
2023-07-31T06:56:53.1908284Z         
2023-07-31T06:56:53.1908818Z         ' did not contain line 1: 'You are running an older version of MinIO released 1 year ago'
2023-07-31T06:56:53.1909143Z     update-notifier_test.go:88: Testcase 26: output '
2023-07-31T06:56:53.1909939Z          You are running an older version of MinIO released 2 years before the latest release 
2023-07-31T06:56:53.1910208Z          Update: my_download_url 
2023-07-31T06:56:53.1910300Z         
2023-07-31T06:56:53.1910909Z         ' did not contain line 1: 'You are running an older version of MinIO released 2 years ago'
2023-07-31T06:56:53.1911641Z --- FAIL: TestPrepareUpdateMessage (0.00s)
```

**Comment by shoce** [comment]
> Please fix the tests @shoce

done

**Pull request merged**
