### PR TITLE
Remove references to MINIO_ENDPOINTS

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Remove references to MINIO_ENDPOINTS

## Motivation and Context
MINIO_ENDPOINTS is a special case scenario
we don't need to document it for now.

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ebozduman — COMMENTED** [review]
Do we want to hide it or completely remove it from our code?
If we want to hide it, but still have support for it, this change is fine. Otherwise, we also need to cleanup references to `MINIO_ENDPOINTS` in the following lines:
. Line# 130
. Line# 154

**Comment by harshavardhana** [comment]
> Do we want to hide it or completely remove it from our code?
> If we want to hide it, but still have support for it, this change is fine. Otherwise, we also need to cleanup references to MINIO_ENDPOINTS in the following lines:
> . Line# 130
> . Line# 154

We only want to hide it. @ebozduman

**Review by ebozduman — APPROVED** [review]
LGTM

**Review by poornas — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Pull request merged**
