### PR TITLE
docs: Fix dead link of HighwayHash

### PR DESCRIPTION
**Pull request by iliul**
## Description

Fix dead link of HighwayHash introduction

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#9ac85608-28ae-475a-8453-39254dab76da) |
| mint-dist-xl.sh | :x: [more...](#9e2fdc59-cd4a-42b9-b972-c33e87a18de6) |
<a name="9e2fdc59-cd4a-42b9-b972-c33e87a18de6"></a>
### 7847-6bd0f3d/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31331
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cd53fbd3e757:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 40 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 16 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 26 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 527,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-fudblg, objectName=minio-java-test-1d3ntbb, resource=/minio-java-test-fudblg/minio-java-test-1d3ntbb, requestId=15AC3EDE7CE3D4A2, hostId=41ba59e9-239d-4dfd-b1a9-32bfad615fdf)\nrequest={method=DELETE, url=http://72.28.97.61:31331/minio-java-test-fudblg/minio-java-test-1d3ntbb?uploadId=da4ae77f-d42b-4cac-b0ba-5409fdb3122a, headers=Host: 72.28.97.61:31331\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190628T032456Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190628/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-28T03-06-08Z\nVary: Origin\nX-Amz-Request-Id: 15AC3EDE7CE3D4A2\nX-Minio-Deployment-Id: 41ba59e9-239d-4dfd-b1a9-32bfad615fdf\nX-Xss-Protection: 1; mode=block\nDate: Fri, 28 Jun 2019 03:24:56 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="9ac85608-28ae-475a-8453-39254dab76da"></a>
### 7847-6bd0f3d/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31653
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b0c407adb648:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-hthwf16bu4bifd",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3063,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31653/aws-sdk-go-test-hthwf16bu4bifd: dial tcp 72.28.97.57:31653: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by iliul** [comment]
update chinese doc

@eco-minio @ebozduman Ping ?

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#71ad18d5-0e02-450c-8342-2ebb523065f4) |
| mint-large-bucket.sh | :x: [more...](#1a14c53b-d78a-40dc-8b28-c7f95c1fdef8) |
| mint-dist-xl.sh | :x: [more...](#533e84a2-1407-4aaa-a3bc-caf6523b3326) |
<a name="71ad18d5-0e02-450c-8342-2ebb523065f4"></a>
### 7847-4356439/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32502
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0552049d1d8a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-du9bxdk2g6lar4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3068,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32502/aws-sdk-go-test-du9bxdk2g6lar4: dial tcp 72.28.97.57:32502: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="533e84a2-1407-4aaa-a3bc-caf6523b3326"></a>
### 7847-4356439/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30037
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f57cdc693c56:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 41 seconds
(9/14) Running minio-go tests ... done in 54 seconds
(10/14) Running minio-java tests ... FAILED in 47 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 620,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-22m511t, objectName=minio-java-test-48b3ke, resource=/minio-java-test-22m511t/minio-java-test-48b3ke, requestId=15AC5014D5327151, hostId=aa6af552-14ae-4239-82d1-0e1bc4e1039f)\nrequest={method=DELETE, url=http://72.28.97.61:30037/minio-java-test-22m511t/minio-java-test-48b3ke?uploadId=83e81c5a-9636-4105-bd26-4c0b978432d7, headers=Host: 72.28.97.61:30037\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190628T084021Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190628/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-28T08-21-23Z\nVary: Origin\nX-Amz-Request-Id: 15AC5014D5327151\nX-Minio-Deployment-Id: aa6af552-14ae-4239-82d1-0e1bc4e1039f\nX-Xss-Protection: 1; mode=block\nDate: Fri, 28 Jun 2019 08:40:21 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="1a14c53b-d78a-40dc-8b28-c7f95c1fdef8"></a>
### 7847-4356439/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30964
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d01b1eb96d3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 13 seconds
{
  "name": "mc",
  "duration": "93036",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-4726 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-97  >>> \n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-97/datafile-0-b`\n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-97/datafile-1-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-97/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-97/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-97/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-97/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-97/datafile-10-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-97/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-97/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-97/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-97/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-97/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-97/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-97/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-97/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 578.08 MiB, Speed: 6.22 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Review by ebozduman — APPROVED** [review]
LGTM

**Comment by iliul** [comment]
@eco-minio  Ping

**Review by eco-minio — APPROVED** [review]
LGTM

**Pull request merged**
