### PR TITLE
config: Support kafka brokers to be specified dynamically.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Currently the brokers have a strict []string requirement. To
make it easier for users to consume it is easier to allow this
field to be dynamic.

This PR adds support for following styles

  - "addr:port" as a single broker address.
  - [ "addr1:port1", "addr2:port2"... ] as a list of brokers.
  - "addr1:port1, addr2:port2, ..." as a comma separated list of brokers.

## Motivation and Context
Ease of usability for user.

## How Has This Been Tested?
Manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]

**Comment by balamurugana** [comment]
@harshavardhana 

> "addr1:port1, addr2:port2, ..." as a comma separated list of brokers.

Why do we need one more representation of array?  As per JSON, its non-standard. Many options will lead to confusion.

**Comment by harshavardhana** [comment]
> Why do we need one more representation of array? As per JSON, its non-standard. Many options will lead to confusion.

The reason is that brokers are usually provided as comma separated.

**Comment by balamurugana** [comment]
> The reason is that brokers are usually provided as comma separated.

Where is it specified like this?

**Comment by balamurugana** [comment]
@harshavardhana basically its not a good idea to have dynamic JSON in config.  If we need one more values, I would prefer array ie
```json
{ "value": ["one"] }
```
or
```json
{ "value": ["one", "two"] }
```

**Comment by harshavardhana** [comment]
> Where is it specified like this?

It is usually how kafka clients take broker list for example here https://github.com/Shopify/sarama/blob/master/examples/http_server/http_server.go#L21 - this is the library we use.

**Comment by balamurugana** [comment]
> It is usually how kafka clients take broker list for example here https://github.com/Shopify/sarama/blob/master/examples/http_server/http_server.go#L21 - this is the library we use.

As its an example code reading from values from env or command line argument, it may deal that style.  However as a JSON configuration file, I won't recommend dynamic JSON.

**Comment by harshavardhana** [comment]
> As its an example code reading from values from env or command line argument, it may deal that style. However as a JSON configuration file, I won't recommend dynamic JSON.

I agree, it is more of a proposal to see if we indeed need to support. I know the typed is more preferred than typeless.

**Comment by harshavardhana** [comment]
Closing this.. as this is not needed for the time being.

**Pull request closed without merging**
