### PR TITLE
Check local address in healthcheck script to ensure correct MinIO port

### LINKED ISSUE #7780: Healthcheck fails when using a docker network.
I'm running minio using a docker network with traefik in front of it.

## Expected Behavior
healthcheck returns 0

## Current Behavior
healthcheck returns 1
2019/06/12 23:27:48 Get http://127.0.0.11:38673/minio/health/live: EOF

## Possible Solution
root@tohru:/srv/traefik# docker exec services_minio_1 healthcheck
2019/06/12 23:27:48 Get http://127.0.0.11:38673/minio/health/live: EOF
root@tohru:/srv/traefik# docker exec services_minio_1 netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:38673        0.0.0.0:*               LISTEN      -
tcp        0      0 :::9000                 :::*                    LISTEN      -

I believe the healthcheck script should be looking by port what something is listening on from the environment variables passed in by the user or the default port.

https://github.com/minio/minio/blob/b4ab778cb2e6b5a2425f226e4ac1febde334ab51/dockerscripts/healthcheck.go#L79-L101 

## Steps to Reproduce (for bugs)
Create a docker network
Create a minio instance attached to that network
Eventually the healthcheck will start to fail after the grace period.

## Context
root@tohru:/srv# docker exec services_minio_1 healthcheck
2019/06/12 23:27:48 Get http://127.0.0.11:38673/minio/health/live: EOF
root@tohru:/srv# docker exec services_minio_1 netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:38673        0.0.0.0:*               LISTEN      -
tcp        0      0 :::9000                 :::*                    LISTEN      -

## Your Environment

* minio/minio:RELEASE.2019-06-11T00-44-33Z
* Docker 18.09.6
* Ubuntu 18.04
* Linux tohru 5.0.0-16-generic #17~18.04.1-Ubuntu SMP Mon May 20 14:00:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by nitisht**
## Description
Fix Docker Healhcheck script to consider only `tcp` process listening on `:::<port>`
as MinIO server.

## Motivation and Context
Fixes #7780

## Regression
Probably yes caused by https://github.com/minio/minio/pull/7569

## How Has This Been Tested?
Deploy MinIO using Docker Compose setup here: https://docs.min.io/docs/deploy-minio-on-docker-compose.html
Observe healthcheck status after grace period of 5 mins. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#a70dcf11-0b01-4639-bd82-f37b266bd783) |
| mint-large-bucket.sh | :x: [more...](#40664a56-ed82-4260-8d86-e4fe8d5c8682) |
| mint-dist-xl.sh | :x: [more...](#9a0bde3f-4cb6-4eda-a032-2d21748bba5a) |
<a name="40664a56-ed82-4260-8d86-e4fe8d5c8682"></a>
### 7787-4ace539/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31457
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c2552d80bd92:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 35 seconds
{
  "name": "mc",
  "duration": "128112",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-6701 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-21162  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-21162/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-21162/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-21162/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-21162/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-21162/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-21162/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-21162/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-21162/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-21162/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-21162/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-21162/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-21162/datafile-33-kB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-21162/datafile-65-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-21162/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-21162/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 552.55 MiB, Speed: 4.32 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="9a0bde3f-4cb6-4eda-a032-2d21748bba5a"></a>
### 7787-4ace539/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32223
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 65fdeeb7309d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 46 seconds
{
  "name": "mc",
  "duration": "11450",
  "function": "test_find_empty",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-3443 --quiet --no-color rb --force myminio/mc-test-bucket-7395  >>> \nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-7395`. The bucket you tried to delete is not empty."
}

Executed 6 out of 14 tests successfully.
```
<a name="a70dcf11-0b01-4639-bd82-f37b266bd783"></a>
### 7787-4ace539/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30322
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0185d86303ac:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yd45yzhceanpk9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360014,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A80C58DB64AC87, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#66fb9dfd-2129-45c6-81da-7f010e2757af) |
| mint-dist-xl.sh | :x: [more...](#72fb860b-dc98-44ae-b0d2-a8e4b80ce1ca) |
<a name="72fb860b-dc98-44ae-b0d2-a8e4b80ce1ca"></a>
### 7787-83e306d/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32453
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8d1739779122:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 5 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 28 seconds
(10/14) Running minio-java tests ... FAILED in 4 minutes and 10 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 5722,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-219p142, objectName=minio-java-test-2fen7t7, resource=/minio-java-test-219p142/minio-java-test-2fen7t7, requestId=15A85DBC0A3B7644, hostId=76317ed4-fafb-47ff-ac8c-514daa6441a9)\nrequest={method=DELETE, url=http://72.28.97.58:32453/minio-java-test-219p142/minio-java-test-2fen7t7?uploadId=eec3c385-f22f-4304-b719-6fc8ff2f057b, headers=Host: 72.28.97.58:32453\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190615T120533Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190615/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-15T11-42-15Z\nVary: Origin\nX-Amz-Request-Id: 15A85DBC0A3B7644\nX-Minio-Deployment-Id: 76317ed4-fafb-47ff-ac8c-514daa6441a9\nX-Xss-Protection: 1; mode=block\nDate: Sat, 15 Jun 2019 12:05:33 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="66fb9dfd-2129-45c6-81da-7f010e2757af"></a>
### 7787-83e306d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32305
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ed12c09c6369:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 32 seconds
{
  "name": "mc",
  "duration": "110290",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-25807 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-827  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-827/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-827/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-827/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-827/datafile-1-b`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-827/datafile-10-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-827/datafile-100-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-827/datafile-10-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-827/datafile-5-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-827/datafile-11-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-827/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-827/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-827/datafile-6-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-827/datafile-1.03-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-827/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-827/datafile-129-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 601.61 MiB, Speed: 5.46 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by nitisht** [comment]
ping @kannappanr

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
