### PR TITLE
fix: honor token based authentication in NATS streaming

### LINKED ISSUE #9148: Can not connect to the NATS Streaming server
NATS streaming server is running as part of the Fission.IO deployment.
When setting up MINIO NATS Streaming notification using the following command:
```bash
 mc admin config set minio/ notify_nats:1 address="<nats-streaming-NodePort>:4222" subject=minio username= password= token=defaultFissionAuthToken tls=off tls_skip_verify=off cert_authority= client_cert= client_key= ping_interval=0 streaming=on streaming_async=on streaming_max_pub_acks_in_flight=0 streaming_cluster_id=fissionMQTrigger queue_dir= queue_limit=0
```
Get the error back :
```
 nats: Authorization Violation.
```
NATS container shows the following authentication attempt
```
[1] 2020/03/10 21:18:36.052109 [INF] STREAM: Starting nats-streaming-server[fissionMQTrigger] version 0.17.0
[1] 2020/03/10 21:18:36.052224 [INF] STREAM: ServerID: pawpJo4MpmEidEhVO4a9nn
[1] 2020/03/10 21:18:36.052227 [INF] STREAM: Go version: go1.13.7
[1] 2020/03/10 21:18:36.052230 [INF] STREAM: Git commit: [f4b7190]
[1] 2020/03/10 21:18:36.061561 [INF] Starting nats-server version 2.1.4
[1] 2020/03/10 21:18:36.061580 [INF] Git commit [fb009af]
[1] 2020/03/10 21:18:36.061751 [INF] Starting http monitor on 0.0.0.0:4223
[1] 2020/03/10 21:18:36.061789 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2020/03/10 21:18:36.061794 [INF] Server id is NDXSP3KLEZTDSPRGIH5JSLPIVXDX7D55V4REMU7U2TATPPZLNOKNLX2C
[1] 2020/03/10 21:18:36.061797 [INF] Server is ready
[1] 2020/03/10 21:18:36.124023 [INF] STREAM: Recovering the state...
[1] 2020/03/10 21:18:36.124041 [INF] STREAM: No recovered state
[1] 2020/03/10 21:18:36.396948 [INF] STREAM: Message store is MEMORY
[1] 2020/03/10 21:18:36.397000 [INF] STREAM: ---------- Store Limits ----------
[1] 2020/03/10 21:18:36.397003 [INF] STREAM: Channels:            unlimited
[1] 2020/03/10 21:18:36.397006 [INF] STREAM: --------- Channels Limits --------
[1] 2020/03/10 21:18:36.397008 [INF] STREAM:   Subscriptions:          1000 *
[1] 2020/03/10 21:18:36.397010 [INF] STREAM:   Messages     :       1000000 *
[1] 2020/03/10 21:18:36.397012 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2020/03/10 21:18:36.397014 [INF] STREAM:   Age          :     unlimited *
[1] 2020/03/10 21:18:36.397017 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2020/03/10 21:18:36.397019 [INF] STREAM: ----------------------------------
[1] 2020/03/10 21:18:36.397022 [INF] STREAM: Streaming Server is ready
[1] 2020/03/10 21:19:25.707195 [INF] STREAM: Channel "minio" has been created
[1] 2020/03/14 21:48:05.276106 [ERR] 172.17.0.22:51272 - cid:84 - authentication error

```
## Expected Behavior
MINIO notify_nats should successfully connect with provided parameter

## Possible Solution
It's might belong to the following line construction in https://github.com/minio/minio/blob/master/pkg/event/target/nats.go
```go 
171 addressURL := scheme + "://" + n.Username + ":" + n.Password + "@" + n.Address.String()
```
where in case of missing username and password the `addressURL` will looks like 
`nats://:@<address>` but should looks like `nats://<token>@<address>`

## Your Environment
Mikikube: 1.7.3 (--vm-driver=none)
Kubectl: 1.17.3
Docker: 18.0.9
MINIO 3.0.12

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
Currently we aren't supporting token auth in NatsURL while connecting to Streaming Nats

## Motivation and Context
Fixes #9148

## How to test this PR?
- Start nats-streaming server with token auth enabled -  `nats-streaming-server --auth mytoken`
- Try to set the token in the config 
```
./mc admin config set myminio/ notify_nats:1 address="0.0.0.0:4222" subject=minio username= password= token= tls=off tls_skip_verify=off cert_authority= client_cert= client_key= ping_interval=0 streaming=on streaming_async=on streaming_cluster_id=test-cluster streaming_max_pub_acks_in_flight=0 queue_dir= queue_limit=0
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#bcb29021-d4ef-4e37-97f4-064c1cf02892) |
<a name="bcb29021-d4ef-4e37-97f4-064c1cf02892"></a>
### 9296-f4542e5/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32339
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8164d0db71f9:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 8 minutes and 56 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... FAILED in 17 seconds
{
  "name": "awscli",
  "duration": 1470,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#310e8110-4a72-4782-a85e-a0ef16d5afe6) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#7bcde02e-4322-4ace-8848-d5d089049c4a) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#f30bd0a4-c2c8-4fb6-8a42-15510b37ecc9) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#fd9308f1-1b0b-4fa7-a335-1a827094a8cd) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#8974758b-27a6-4829-9a70-0278f2c8a91b) |
| mint-gateway-azure.sh | :heavy_exclamation_mark: [more...](#e0421196-6f16-427f-815b-d0df1048bc52) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#36fabb59-c9ee-4308-a7d8-b65e42fa4798) |
<a name="fd9308f1-1b0b-4fa7-a335-1a827094a8cd"></a>
### 9296-a07cb16/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="36fabb59-c9ee-4308-a7d8-b65e42fa4798"></a>
### 9296-a07cb16/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="e0421196-6f16-427f-815b-d0df1048bc52"></a>
### 9296-a07cb16/mint-gateway-azure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="310e8110-4a72-4782-a85e-a0ef16d5afe6"></a>
### 9296-a07cb16/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="7bcde02e-4322-4ace-8848-d5d089049c4a"></a>
### 9296-a07cb16/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="8974758b-27a6-4829-9a70-0278f2c8a91b"></a>
### 9296-a07cb16/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="f30bd0a4-c2c8-4fb6-8a42-15510b37ecc9"></a>
### 9296-a07cb16/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#7c1d51bb-b843-45f7-a08d-3f32fcb06958) |
| mint-gateway-azure.sh | :x: [more...](#743ee702-8a44-4ba8-ae8c-a877883844af) |
<a name="7c1d51bb-b843-45f7-a08d-3f32fcb06958"></a>
### 9296-49bfb86/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32195
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aba590d83ade:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 32 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... done in 11 minutes and 49 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 46 seconds
(11/15) Running minio-js tests ... done in 48 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 34 seconds
(13/15) Running s3cmd tests ... done in 21 seconds
(14/15) Running s3select tests ... done in 1 seconds
(15/15) Running security tests ... done in 0 seconds

All tests ran successfully
```
<a name="743ee702-8a44-4ba8-ae8c-a877883844af"></a>
### 9296-49bfb86/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32089
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 211141aa06c1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 9 minutes and 32 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 19 seconds
{
  "name": "awscli",
  "duration": 1472,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
