### PR TITLE
cleanup ignored static analysis

### PR DESCRIPTION
**Pull request by ferhatelmas**
## Description
Drop ignored static analysis checks as much as possible.

## Motivation and Context
https://github.com/minio/minio/pull/16736#discussion_r1124286148

## How to test this PR?
CI ensures everything is fine.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
Awesome stuff 👍🏼

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by klauspost** [comment]
Ah, you found it. Was just writing it down for you. Rerunning tests.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by ferhatelmas** [comment]
seems good to go 🚀

**Pull request merged**
