### PR TITLE
Listen for PolicyDB events from etcd in IAM and fix etcd watch handling

### LINKED ISSUE #7991: gateway with etcd: STS token is returned before it's usable by minio cluster
Sometimes a minio server will return STS credentials ... but when we make a request using that STS token, the client receives `InvalidAccessKeyId: The access key ID you provided does not exist in our records`.

## Expected Behavior

I expect minio to only return STS credentials that are valid on all servers in the minio cluster.

## Current Behavior

We're operating two minio servers in GCS gateway mode, configured by a 3-node etcd cluster.

We're using etcd+STS to supply temporary credentials to our JS-client users. I suspect we're hitting a race:

1. our server's minio client creates an STS user on minio server "minio1"
2. minio1 writes the STS credentials to etcd
3. minio1 tells server the STS credentials (after the token is written)
4. server tells JS client credentials
5. JS client connects to minio2, our redundant minio server
6. minio2 responds, InvalidAccessKeyId
7. [OOPS THIS IS TOO LATE] etcd tells minio2 about the STS credentials

## Possible Solution

Brainstorming, with little knowledge of etcd:

* When authenticating, query etcd instead of using a cache.
* If STS credentials aren't in the minio cache, then query etcd as a fallback.

## Steps to Reproduce (for bugs)

```
docker network create minio-test
# Launch etcd (and make it slow)
docker run --network minio-test --name minio-test-etcd -it --cpus=0.5 --rm gcr.io/etcd-development/etcd:v3.3.12 etcd --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://minio-test-etcd:2379

# Launch minio servers 1-4 on localhost:9001-4 (and make them slow)
for i in `seq 1 4`; do docker run -d --network minio-test --name minio-test-minio-$i --cpus=0.5 --env MINIO_ETCD_ENDPOINTS=http://minio-test-etcd:2379 --env MINIO_ACCESS_KEY=root --env MINIO_SECRET_KEY=rootroot -p 900$i:9000 minio/minio:RELEASE.2019-07-24T02-02-23Z server http://minio-test-minio-1/data http://minio-test-minio-2/data http://minio-test-minio-3/data http://minio-test-minio-4/data; done

# Create user with accessKeyId "guest",secretAccessKey "guestguest"
docker run -it --rm --network minio-test --entrypoint sh minio/mc:RELEASE.2019-07-24T02-55-56Z -c 'mc config host add main http://minio-test-minio-1:9000 root rootroot && mc admin user add main guest guestguest readwrite'

python
```

And in Python:

```
import boto3
sts_client = boto3.session.Session(aws_access_key_id='guest', aws_secret_access_key='guestguest', region_name='us-east-1').client('sts', endpoint_url='http://localhost:9001')
def attempt():
    credentials = sts_client.assume_role(RoleArn='notusednotusednotused', RoleSessionName='notused')['Credentials']
    print('Trying with access key ' + credentials['AccessKeyId'])
    # S3 request goes to a different minio server
    s3_client = boto3.session.Session(aws_access_key_id=credentials['AccessKeyId'], aws_secret_access_key=credentials['SecretAccessKey'], aws_session_token=credentials['SessionToken'], region_name='us-east-1').client('s3', endpoint_url='http://localhost:9004')
    s3_client.list_buckets()  # Should not error with InvalidAccessKeyId

for i in range(100): attempt()
```

On my machine, instead of 100 printed lines, I see:

```
Trying with access key PIWBLMYJIY72KETCKH5D
Trying with access key GKEOQW46OF5NLY2A4LRD
Trying with access key 146ECUS9QQHY90469GFC
Trying with access key O79KZ0Q49B02TWZBP8VC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in attempt
  File "/home/adam/.local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/adam/.local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The access key ID you provided does not exist in our records.
```

To clean up after testing:

```
docker rm -f minio-test-etcd minio-test-minio-{1,2,3,4}
docker network rm minio-test
```

## Context

This is nearly a deal-breaker with STS. In production, we need to delay at least 1s and hope that was long enough for the setting to wend its way through our etcd cluster and back to minio clients.

## Regression

No

## Your Environment

* Version used (`minio version`): RELEASE.2019-07-24T02-02-23Z
* Environment name and version (e.g. nginx 1.9.1): GKE (GCS gateway) and Docker+Python3 on Linux (reduction)
* Server type and version:
* Operating System and version (`uname -a`): Linux
* Link to your project: https://github.com/CJWorkbench/cjworkbench

### PR DESCRIPTION
**Pull request by donatello**
## Description

Fix a bug related to erroneous etcd watch response handling

## Motivation and Context

Fix https://github.com/minio/minio/issues/7991

## How to test this PR?

See https://github.com/minio/minio/issues/7991

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]
LGTM tested this locally using the reproducer from the issue #7991

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#bca7c51b-9521-420f-8622-06a973b3190e) |
| mint-large-bucket.sh | :x: [more...](#6263403c-1202-481a-9c34-8e71e709a6b4) |
| mint-compression-dist-xl.sh | :x: [more...](#0c12b5be-4606-48a2-bf84-b2b19e308ec1) |
| mint-compression-fs.sh | :x: [more...](#0df69cd1-f1d6-457a-9caa-92c3d4ff6044) |
| mint-dist-xl.sh | :x: [more...](#e24eeb41-3006-4301-83f2-2ffbacb28732) |
<a name="0c12b5be-4606-48a2-bf84-b2b19e308ec1"></a>
### 7992-326e0f1/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31879
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1ff7f923a636:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 19 seconds
{
  "name": "mc",
  "duration": "631",
  "function": "test_presigned_put_object",
  "status": "FAIL",
  "error": "unable to upload /mint/data/datafile-1-MB presigned put object url"
}

Executed 6 out of 14 tests successfully.
```
<a name="6263403c-1202-481a-9c34-8e71e709a6b4"></a>
### 7992-326e0f1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32652
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4ceadfba1777:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 39 seconds
{
  "name": "mc",
  "duration": "128888",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-4480 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-11394  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-11394/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-11394/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-11394/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-11394/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-11394/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-11394/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-11394/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-11394/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-11394/datafile-129-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-11394/datafile-100-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-11394/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-11394/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-11394/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-11394/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-11394/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 480.99 MiB, Speed: 3.73 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="e24eeb41-3006-4301-83f2-2ffbacb28732"></a>
### 7992-326e0f1/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32588
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2064577e2488:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 39 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 52 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 14 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName)",
  "duration": 63,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.55:32588/minio-java-test-39lpg10/minio-java-test-hukn2r?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190729%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190729T212744Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=1beeab51682e778c2cb306e1a29073a120df2ae1edfca0e53a86a5fd1472f547}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-hukn2r</Key><BucketName>minio-java-test-39lpg10</BucketName><Resource>/minio-java-test-39lpg10/minio-java-test-hukn2r</Resource><RequestId>15B5FDF2D3E52637</RequestId><HostId>2a53f058-01dd-4891-ba41-24f7518fb5cb</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test1(FunctionalTest.java:1767), FunctionalTest.runTests(FunctionalTest.java:2994), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="0df69cd1-f1d6-457a-9caa-92c3d4ff6044"></a>
### 7992-326e0f1/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31384
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 61cf5589be00:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-r6nq1xuxyqshow",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12510,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31384/aws-sdk-go-test-r6nq1xuxyqshow: dial tcp 72.28.97.57:31384: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="bca7c51b-9521-420f-8622-06a973b3190e"></a>
### 7992-326e0f1/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32080
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6efdbb8b0e96:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-e0k9ysc30w0wqg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360010,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B5FDEFB4A7C246, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d5c9db55-0003-4d29-a2f5-4e4781016099) |
<a name="d5c9db55-0003-4d29-a2f5-4e4781016099"></a>
### 7992-d446b7b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32436
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8a137d39e6c5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 21 seconds
{
  "name": "mc",
  "duration": "100647",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7150 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-23018  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-23018/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-23018/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-23018/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-23018/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-23018/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-23018/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-23018/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-23018/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-23018/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-23018/datafile-33-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-23018/datafile-11-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-23018/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-23018/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-23018/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-23018/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 513.81 MiB, Speed: 5.11 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#fb8c079b-9299-451e-adc0-b3f91ac20147) |
| mint-large-bucket.sh | :x: [more...](#f4f4940c-67b3-4920-8cc1-64e49ae7b548) |
| mint-worm.sh | :x: [more...](#b9bebaba-075c-4cac-aa8a-7ebe95d1d646) |
<a name="fb8c079b-9299-451e-adc0-b3f91ac20147"></a>
### 7992-a3b6c55/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30398
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0413eeda872c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fcbh51p4rmpflc",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12284,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30398/aws-sdk-go-test-fcbh51p4rmpflc: dial tcp 72.28.97.57:30398: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f4f4940c-67b3-4920-8cc1-64e49ae7b548"></a>
### 7992-a3b6c55/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31874
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 13b0f169c60a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 22 seconds
{
  "name": "mc",
  "duration": "111146",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-17447 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-24341  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-24341/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-24341/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-24341/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-24341/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-24341/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-24341/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-24341/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-24341/datafile-129-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-24341/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-24341/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-24341/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-24341/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-24341/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-24341/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-24341/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 490.99 MiB, Speed: 4.42 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="b9bebaba-075c-4cac-aa8a-7ebe95d1d646"></a>
### 7992-a3b6c55/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32424
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b890ce84f3be:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-lz3tgjpamrtocrbbo1js1xx8ziuj8yn08f00wip16fafzsk8ex5g4zt",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 11930,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32424/bucket-lz3tgjpamrtocrbbo1js1xx8ziuj8yn08f00wip16fafzsk8ex5g4zt: dial tcp 72.28.97.57:32424: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```

**Review by poornas — APPROVED** [review]
LGTM

**Pull request merged**
