### PR TITLE
Cross compile openbsd/amd64 as well

### PR DESCRIPTION
**Pull request by danieljakots**
As discussed in https://github.com/minio/mc/pull/3732

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#e253ced1-259e-4858-a6a0-500e618ebf47) |
<a name="e253ced1-259e-4858-a6a0-500e618ebf47"></a>
### 12417-51beeca/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31103
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7ca9721ecce0:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 13 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 3 seconds
(8/15) Running minio-dotnet tests ... done in 48 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 53 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 24 seconds
{
  "name": "minio-java",
  "function": "composeObject()",
  "args": "[single source with offset]",
  "duration": 35,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Range specified is not valid for source object, bucketName = minio-java-test-30uc0on, objectName = minio-java-test-3mua4be, resource = /minio-java-test-30uc0on/minio-java-test-3mua4be, requestId = 1684893169975A6D, hostId = 830e8104-99d1-4172-ae1f-69a92f84e50d)\nrequest={method=PUT, url=http://minio-c3.minio.io:31103/minio-java-test-30uc0on/minio-java-test-3mua4be?uploadId=97ea8d49-2da4-44aa-b871-e469a1f3b6be&partNumber=1, headers=x-amz-copy-source: /minio-java-test-30uc0on/minio-java-test-1rpfkuf\nx-amz-copy-source-range: bytes=2048-1048575\nx-amz-copy-source-if-match: cb92d17a904ccec2e6e23b8bb66245fb\nHost: minio-c3.minio.io:31103\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210601T183651Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210601/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-copy-source-range;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 390\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1684893169975A6D\nX-Xss-Protection: 1; mode=block\nDate: Tue, 01 Jun 2021 18:36:51 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.uploadPartCopy(MinioClient.java:4804), io.minio.MinioClient.composeObject(MinioClient.java:1431), FunctionalTest.testComposeObject(FunctionalTest.java:2120), FunctionalTest.composeObjectTests(FunctionalTest.java:2145), FunctionalTest.composeObject(FunctionalTest.java:2300), FunctionalTest.runObjectTests(FunctionalTest.java:3758), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 53 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 53 seconds
(12/15) Running s3cmd tests ... done in 17 seconds
(13/15) Running s3select tests ... done in 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Looks like `gopsutil` doesn't support OpenBSD

```
# github.com/shirou/gopsutil/v3/process
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:163:15: undefined: pidsWithContext
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:171:9: undefined: ProcessesWithContext
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:209:14: p.ForegroundWithContext undefined (type *Process has no field or method ForegroundWithContext)
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:223:20: p.TimesWithContext undefined (type *Process has no field or method TimesWithContext)
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:235:20: p.TimesWithContext undefined (type *Process has no field or method TimesWithContext)
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:287:22: p.createTimeWithContext undefined (type *Process has no field or method createTimeWithContext, but does have CreateTimeWithContext)
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:313:25: p.MemoryInfoWithContext undefined (type *Process has no field or method MemoryInfoWithContext)
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:328:20: p.createTimeWithContext undefined (type *Process has no field or method createTimeWithContext, but does have CreateTimeWithContext)
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:333:16: p.TimesWithContext undefined (type *Process has no field or method TimesWithContext)
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:349:10: p.GroupsWithContext undefined (type *Process has no field or method GroupsWithContext)
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.4/process/process.go:349:10: too many errors
make: *** [Makefile:24: crosscompile] Error 2
Error: Process completed with exit code 2.
```

**Comment by danieljakots** [comment]
gopsutil supports OpenBSD but with CGO. On an OpenBSD machine:
`$ go build -tags kqueue -o /dev/null` succeed.
`$ CGO_ENABLED=0 go build -tags kqueue -o /dev/null` shows the problem.

I'll check with gopsutil since the README says `All works are implemented without cgo by porting c struct to golang struct.`.

Cf. https://github.com/shirou/gopsutil/pull/965

**Comment by harshavardhana** [comment]
> gopsutil supports OpenBSD but with CGO. On an OpenBSD machine:
> `$ go build -tags kqueue -o /dev/null` succeed.
> `$ CGO_ENABLED=0 go build -tags kqueue -o /dev/null` shows the problem.
> 
> I'll check with gopsutil since the README says `All works are implemented without cgo by porting c struct to golang struct.`.
> 
> Cf. [shirou/gopsutil#965](https://github.com/shirou/gopsutil/pull/965)

Yeah, we need to do without CGO, we can't have 'C' deps in MinIO.

**Comment by danieljakots** [comment]
Yeah I totally understand. I'm closing the PR for now.

**Pull request closed without merging**
