### PR TITLE
Add canned `diagnostics` policy for admin users

### PR DESCRIPTION
**Pull request by poornas**
## Motivation and Context
Create a canned policy called `diagnostics` for access to admin trace, console logs, profiling and server info for user convenience

## How to test this PR?
Start minio with this patch, `mc admin policy list myminio` should show the new policy and you should be able to set this policy on a user.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#13535e06-18a7-45f9-9541-26dbf7eec0f1) |
| mint-large-bucket.sh | :x: [more...](#1a0c56f5-935a-4fd4-bbaf-4eab049f6479) |
| mint-gateway-azure.sh | :x: [more...](#02af5a53-1231-4f82-9bcf-82d736fee5e0) |
<a name="1a0c56f5-935a-4fd4-bbaf-4eab049f6479"></a>
### 8937-359add6/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32676
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 21ec28e8583b:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 54 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 26 seconds
{
  "args": {},
  "duration": 76975,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="02af5a53-1231-4f82-9bcf-82d736fee5e0"></a>
### 8937-359add6/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32275
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3c278de5357c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 28 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 17 seconds
(4/13) Running mc tests ... done in 6 minutes and 14 seconds
(5/13) Running minio-go tests ... FAILED in 20 minutes and 24 seconds
{
  "args": {
    "bucketName": "minio-go-test-ox3sbnkidwtvujmb",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 234,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="13535e06-18a7-45f9-9541-26dbf7eec0f1"></a>
### 8937-359add6/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32594
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 674b771dc573:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 309454, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32594/awscli-mint-test-bucket-14884""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#0d09ff32-1f52-491f-ab17-a40e429afda4) |
| mint-large-bucket.sh | :x: [more...](#f0cc7ac1-9c86-4c57-a2a5-990dee3c0d84) |
| mint-worm.sh | :x: [more...](#7571fa1e-74d3-4510-a226-452507914146) |
| mint-gateway-azure.sh | :x: [more...](#258f6e17-91d4-4549-b3b8-693de1c3ad32) |
| mint-gateway-nas.sh | :x: [more...](#f9d3cede-0348-49c7-8b18-00c0a072a2ad) |
<a name="258f6e17-91d4-4549-b3b8-693de1c3ad32"></a>
### 8937-91edb55/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32193
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 750fda6481e4:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 10 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 17 seconds
(4/13) Running mc tests ... done in 6 minutes and 15 seconds
(5/13) Running minio-go tests ... FAILED in 21 minutes and 10 seconds
{
  "args": {
    "bucketName": "minio-go-test-l63315uet1jqwwie",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 237,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="0d09ff32-1f52-491f-ab17-a40e429afda4"></a>
### 8937-91edb55/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30843
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7a082d927215:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 309648, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30843/awscli-mint-test-bucket-5001""}

Executed 0 out of 13 tests successfully.
```
<a name="f9d3cede-0348-49c7-8b18-00c0a072a2ad"></a>
### 8937-91edb55/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31214
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 49ebfa824c45:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 11 seconds
{"name": "awscli", "duration": 308686, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31214/awscli-mint-test-bucket-19349""}

Executed 0 out of 13 tests successfully.
```
<a name="7571fa1e-74d3-4510-a226-452507914146"></a>
### 8937-91edb55/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32395
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 47abb6d9c06c:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-8oyjv79nscmczmjb6jnh1hmlrvqd1kzd1inc9hsc107zi8mpj59esus",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120244,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32395/bucket-8oyjv79nscmczmjb6jnh1hmlrvqd1kzd1inc9hsc107zi8mpj59esus: dial tcp 72.28.97.55:32395: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="f0cc7ac1-9c86-4c57-a2a5-990dee3c0d84"></a>
### 8937-91edb55/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31800
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7b367e43c2c1:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 21 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 49 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 35 seconds
{
  "args": {},
  "duration": 94603,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by kannappanr** [comment]
@poornas Please check build failure

**Comment by kannappanr** [comment]
Tested. LGTM

**Review by donatello — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#1785120d-8bfa-4aa6-b562-5b1b05d0313b) |
| mint-large-bucket.sh | :x: [more...](#cddfb59c-f387-4588-8636-afaf183b6c12) |
| mint-worm.sh | :x: [more...](#87efa04a-6a56-408f-81f8-31a5836d6585) |
| mint-fs.sh | :x: [more...](#63e6dc05-579f-4989-a0fc-117eeb43bcf4) |
| mint-dist-xl.sh | :x: [more...](#10f9e263-9a5c-44b8-a75c-9b8aac3c42eb) |
| mint-gateway-azure.sh | :x: [more...](#4cb1a6e8-4999-4b39-b8cd-96d44e321e62) |
<a name="cddfb59c-f387-4588-8636-afaf183b6c12"></a>
### 8937-e8e0a89/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30161
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9691e126a458:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 19 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 41 seconds
(5/13) Running minio-go tests ... FAILED in 11 minutes and 38 seconds
{
  "args": {},
  "duration": 96285,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="63e6dc05-579f-4989-a0fc-117eeb43bcf4"></a>
### 8937-e8e0a89/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30748
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a0a827984d9a:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 13 seconds
{"name": "awscli", "duration": 310545, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30748/awscli-mint-test-bucket-10987""}

Executed 0 out of 13 tests successfully.
```
<a name="4cb1a6e8-4999-4b39-b8cd-96d44e321e62"></a>
### 8937-e8e0a89/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31908
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5f5b4a5a5d54:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 17 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 40 seconds
(5/13) Running minio-go tests ... FAILED in 20 minutes and 34 seconds
{
  "args": {
    "bucketName": "minio-go-test-aevoly50v1zih0go",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 239,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="10f9e263-9a5c-44b8-a75c-9b8aac3c42eb"></a>
### 8937-e8e0a89/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31828
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 08f9d9621326:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 15 seconds
{"name": "awscli", "duration": 312676, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31828/awscli-mint-test-bucket-3504""}

Executed 0 out of 13 tests successfully.
```
<a name="1785120d-8bfa-4aa6-b562-5b1b05d0313b"></a>
### 8937-e8e0a89/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32383
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 88860afaf514:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 16 seconds
{
  "name": "awscli",
  "duration": 14148,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="87efa04a-6a56-408f-81f8-31a5836d6585"></a>
### 8937-e8e0a89/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31968
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ea5fd1a55e7b:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-684o1srz6k2wdaa2b9g0njs828wy4u6cq9v25k8tn7hw2qnwo20crsj",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120321,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31968/bucket-684o1srz6k2wdaa2b9g0njs828wy4u6cq9v25k8tn7hw2qnwo20crsj: dial tcp 72.28.97.55:31968: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
