### PR TITLE
Add a lock on format.json when healing a bucket or object

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
This commit adds locking on format.json when healing an object
or a bucket, to avoid write data on disks during the format
process.

This commit also uses a write lock in heal object since the
object will be modified.

## Motivation and Context
Adding missing lock on formatting disks

## How to test this PR?
Hard to test to reproduce the issue

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#82e1b5ca-88df-410b-930d-627a1f8ed51f) |
| mint-compression-dist-xl.sh | :x: [more...](#930dc7b5-fe06-4494-8b80-2ec8190230f0) |
<a name="82e1b5ca-88df-410b-930d-627a1f8ed51f"></a>
### 8370-bcb860d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30842
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 060da9f5c137:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 55 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 17 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 43 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 28 seconds
{
  "args": {},
  "duration": 83776,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="930dc7b5-fe06-4494-8b80-2ec8190230f0"></a>
### 8370-bcb860d/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30793
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b8d0a4b27a83:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 48 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 11 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 4 seconds
(11/14) Running minio-js tests ... done in 53 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 56 seconds
{
  "duration": 100,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "args": {
    "presigned_get_object_url": "http://72.28.97.54:30793/minio-py-test-ea6b6ac6-d205-4143-a35e-a02b6ad31fae/d18114c9-9bf6-450f-8ed2-7f1d0d115208?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191008%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191008T174817Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=2030b6fa2d5ca0ce24e5f2d3bf8fb56ddd8d601a7e80d5fc63a2b830de11cadf",
    "object_name": "d18114c9-9bf6-450f-8ed2-7f1d0d115208",
    "bucket_name": "minio-py-test-ea6b6ac6-d205-4143-a35e-a02b6ad31fae"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "'content-language'",
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_response_headers"
}

Executed 11 out of 14 tests successfully.
```
Error: No such image: minio/minio:8370-bcb860d

**Comment by kannappanr** [comment]
@vadmeste `make verify` fails on Travis, PTAL

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#5f879c82-d854-4ce2-91de-0b3cb5686ee9) |
| mint-compression-dist-xl.sh | :x: [more...](#a3df42f5-5a93-44ab-bf02-c4b8fb0a72e4) |
| mint-dist-xl.sh | :x: [more...](#7e4c7eea-2713-4b56-b2c9-a43919831c70) |
<a name="5f879c82-d854-4ce2-91de-0b3cb5686ee9"></a>
### 8370-a6c435a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30015
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8a71427b894f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 59 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 32 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 25 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 33 seconds
{
  "args": {},
  "duration": 125008,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="7e4c7eea-2713-4b56-b2c9-a43919831c70"></a>
### 8370-a6c435a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31778
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f0e75f6d9ad5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 56 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 18 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 49 seconds
(11/14) Running minio-js tests ... done in 56 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 43 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "duration": 333,
  "args": {
    "object_name": "00ad456b-01d3-4504-8500-5adaa00285b8",
    "presigned_get_object_url": "http://72.28.97.52:31778/minio-py-test-6e91743b-ca05-4203-afcb-642d35dde7ec/00ad456b-01d3-4504-8500-5adaa00285b8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191008%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191008T200824Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=66ce7c513e545a3f5e318baabbf632cc752b5da598c58dd288531d94f6f7f6a0",
    "bucket_name": "minio-py-test-6e91743b-ca05-4203-afcb-642d35dde7ec"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "message": "'content-language'",
  "name": "minio-py:test_presigned_get_object_response_headers"
}

Executed 11 out of 14 tests successfully.
```
<a name="a3df42f5-5a93-44ab-bf02-c4b8fb0a72e4"></a>
### 8370-a6c435a/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32671
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 61af14b41712:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 44 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 8 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 59 seconds
(11/14) Running minio-js tests ... done in 52 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 35 seconds
{
  "name": "minio-py:test_presigned_get_object_response_headers",
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "args": {
    "object_name": "47ee0190-4b35-475f-8f48-0a17925cba2b",
    "bucket_name": "minio-py-test-3d51ce92-950b-4d2a-a4b2-2764b39c13cc",
    "presigned_get_object_url": "http://72.28.97.52:32671/minio-py-test-3d51ce92-950b-4d2a-a4b2-2764b39c13cc/47ee0190-4b35-475f-8f48-0a17925cba2b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191008%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191008T200824Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=60bed48f7b05e5b917d07e6fa9d2f180ea8fe2682fd7c0f1f4021d9a605aaadd"
  },
  "duration": 94,
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "'content-language'"
}

Executed 11 out of 14 tests successfully.
```
Error: No such image: minio/minio:8370-a6c435a

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#1adeb8f8-bd90-4f00-bfe4-a533b51fc41a) |
| mint-large-bucket.sh | :x: [more...](#9cfa11f6-8d87-4877-bf2d-2e0bb7342e8f) |
| mint-compression-fs.sh | :x: [more...](#168684f2-d3e4-4e03-ae85-4b321fb5e32e) |
<a name="1adeb8f8-bd90-4f00-bfe4-a533b51fc41a"></a>
### 8370-5c74d30/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30685
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 77dff828d8bf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mxlu66xgwkgn2w",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365535,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15CBE8106F70257E, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="168684f2-d3e4-4e03-ae85-4b321fb5e32e"></a>
### 8370-5c74d30/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30499
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e082ec1a4051:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 19 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 47 seconds
(10/14) Running minio-java tests ... done in 52 seconds
(11/14) Running minio-js tests ... done in 48 seconds
(12/14) Running minio-py tests ... FAILED in 1 minutes and 59 seconds
{
  "duration": 51,
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "object_name": "7cdb9e68-3914-4687-8c70-9359adc4963e",
    "response.status": 403,
    "bucket_name": "minio-py-test-eb221057-dbe2-4b6c-839e-c451282156c7",
    "response.reason": "Forbidden",
    "presigned_get_object_url": "http://72.28.97.56:30499/minio-py-test-eb221057-dbe2-4b6c-839e-c451282156c7/7cdb9e68-3914-4687-8c70-9359adc4963e?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191009%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191009T065448Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=afce1b08587cc7d8d05486abd8d940a3e50f0ece67cbfb069077be853ac4711c",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>7cdb9e68-3914-4687-8c70-9359adc4963e</Key><BucketName>minio-py-test-eb221057-dbe2-4b6c-839e-c451282156c7</BucketName><Resource>/minio-py-test-eb221057-dbe2-4b6c-839e-c451282156c7/7cdb9e68-3914-4687-8c70-9359adc4963e</Resource><RequestId>15CBE81AF47334C6</RequestId><HostId>20a4b5f3-b664-4d95-a272-7b247dfadea4</HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-09T06-28-52Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CBE81AF47334C6\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Wed, 09 Oct 2019 06:54:57 GMT\"]}}"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="9cfa11f6-8d87-4877-bf2d-2e0bb7342e8f"></a>
### 8370-5c74d30/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31696
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1bcd5cd616b2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 22 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 57 seconds
{
  "args": {},
  "duration": 111852,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8370-5c74d30

**Review by harshavardhana — APPROVED** [review]

**Comment by vadmeste** [comment]
ping @krishnasrinivas @donatello

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Now that I thought more about this - I am not sure will this ever happen. Since `format.json` written to new disks don't come online automatically even if they did it is well protected by the xl.getDisks() implementation which would make sure that the obtained disks are the correct ones with correct format.json positions. so any slice of disks currently under use by either a HealObject or HealBucket is the correct one at that time. 

So taking another lock on the `format.json` doesn't look like its needed. What is the issue that you are trying to fix here @vadmeste?

Perhaps the concerns here are also being properly fixed in #8408

**Review by krishnasrinivas — COMMENTED** [review]
@vadmeste heal of format.json and heal of object are independent ... can you explain the problem in more detail on how things can go wrong? (assuming https://github.com/minio/minio/pull/8408 PR is taken in)

**Comment by kannappanr** [comment]
ping @vadmeste

**Comment by vadmeste** [comment]
@harshavardhana @krishnasrinivas yes, this PR is not needed after modifying posix to write only in formatted disks, getDisks() will return only formatted disks but even something wrong happen in the middle of healing, posix will still forbid to write on disks, so this PR is not needed anymore

**Pull request closed without merging**
