### PR TITLE
Allow querying a single target in config get API

### PR DESCRIPTION
**Pull request by donatello**
## Motivation and Context

Restores previous behavior when a single target could be queried. Also allow querying the default target alone with trailing `:`.

No `mc` changes are required.

## How to test this PR?

It should work like this now:

```
$ mc admin config get myminio logger_webhook
logger_webhook enable=off endpoint= auth_token= client_cert= client_key= queue_size=100000 
logger_webhook:1 endpoint=http://localhost:8080/ auth_token= client_cert= client_key= queue_size=100000 
$ mc admin config get myminio logger_webhook:1
logger_webhook:1 endpoint=http://localhost:8080/ auth_token= client_cert= client_key= queue_size=100000 
$ mc admin config get myminio logger_webhook:
logger_webhook enable=off endpoint= auth_token= client_cert= client_key= queue_size=100000 
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (introduced in 21831b3fe29a6ae4d81c4e16132460b879fa872e)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#6bbf2df4-3e5b-4c65-9546-d5fbf553a1fd) |
<a name="6bbf2df4-3e5b-4c65-9546-d5fbf553a1fd"></a>
### 15587-02a684b/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:30280
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 54 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-go tests ... done in 42 seconds
(9/14) Running minio-java tests ... done in 33 seconds
(10/14) Running minio-js tests ... 
Aborting Mint...
Running with
SERVER_ENDPOINT:      minio-k8s6:30280
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... FAILED in 41 seconds
{"name": "awscli", "duration": 1397, "function": "aws --endpoint-url http://minio-k8s6:30280 s3api put-bucket-lifecycle-configuration --bucket awscli-mint-test-bucket-10786 --lifecycle-configuration file:///tmp/lifecycle.json\n", "status": "FAIL", "error": "Error parsing parameter '--lifecycle-configuration': Invalid JSON: Extra data: line 2 column 1 (char 129)JSON received: { "Rules": [ { "Expiration": { "Days": 365 },"ID": "Bucketlifecycle test", "Filter": { "Prefix": "" }, "Status": "Enabled" } ] }{ "Rules": [ { "Expiration": { "Days": 365 },"ID": "Bucketlifecycle test", "Filter": { "Prefix": "" }, "Status": "Enabled" } ] }"}
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... done in 25 seconds
(7/14) Running minio-go tests ... done in 39 seconds
(8/14) Running minio-java tests ... done in 32 seconds
(9/14) Running minio-js tests ... FAILED in 31 minutes and 13 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 6860,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(9/14) Running minio-py tests ... done in 57 seconds
(10/14) Running s3cmd tests ... done in 1 minutes and 6 seconds
(11/14) Running s3select tests ... done in 2 seconds
(12/14) Running versioning tests ... done in 0 seconds

Executed 12 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by anjalshireesh — APPROVED** [review]
LGTM, tested

**Comment by harshavardhana** [comment]
> mint-gateway-s3.sh	 [more...](#6bbf2df4-3e5b-4c65-9546-d5fbf553a1fd)
> ### 15587-02a684b/mint-gateway-s3.sh.log:
> ```
> Running with
> SERVER_ENDPOINT:      minio-k8s6:30280
> ACCESS_KEY:           minio
> SECRET_KEY:           ***REDACTED***
> ENABLE_HTTPS:         0
> SERVER_REGION:        us-east-1
> MINT_DATA_DIR:        /mint/data
> MINT_MODE:            full
> ENABLE_VIRTUAL_STYLE: 0
> RUN_ON_FAIL:          0
> 
> To get logs, run 'docker cp :/mint/log /tmp/mint-logs'
> 
> (1/14) Running aws-sdk-go tests ... done in 0 seconds
> (2/14) Running aws-sdk-java tests ... done in 1 seconds
> (3/14) Running aws-sdk-php tests ... done in 43 seconds
> (4/14) Running aws-sdk-ruby tests ... done in 5 seconds
> (5/14) Running awscli tests ... done in 54 seconds
> (6/14) Running healthcheck tests ... done in 0 seconds
> (7/14) Running mc tests ... done in 26 seconds
> (8/14) Running minio-go tests ... done in 42 seconds
> (9/14) Running minio-java tests ... done in 33 seconds
> (10/14) Running minio-js tests ... 
> Aborting Mint...
> Running with
> SERVER_ENDPOINT:      minio-k8s6:30280
> ACCESS_KEY:           minio
> SECRET_KEY:           ***REDACTED***
> ENABLE_HTTPS:         0
> SERVER_REGION:        us-east-1
> MINT_DATA_DIR:        /mint/data
> MINT_MODE:            full
> ENABLE_VIRTUAL_STYLE: 0
> RUN_ON_FAIL:          0
> 
> To get logs, run 'docker cp :/mint/log /tmp/mint-logs'
> 
> (1/14) Running aws-sdk-go tests ... done in 1 seconds
> (2/14) Running aws-sdk-java tests ... done in 1 seconds
> (3/14) Running aws-sdk-php tests ... done in 43 seconds
> (4/14) Running aws-sdk-ruby tests ... done in 4 seconds
> (5/14) Running awscli tests ... FAILED in 41 seconds
> {"name": "awscli", "duration": 1397, "function": "aws --endpoint-url http://minio-k8s6:30280 s3api put-bucket-lifecycle-configuration --bucket awscli-mint-test-bucket-10786 --lifecycle-configuration file:///tmp/lifecycle.json\n", "status": "FAIL", "error": "Error parsing parameter '--lifecycle-configuration': Invalid JSON: Extra data: line 2 column 1 (char 129)JSON received: { "Rules": [ { "Expiration": { "Days": 365 },"ID": "Bucketlifecycle test", "Filter": { "Prefix": "" }, "Status": "Enabled" } ] }{ "Rules": [ { "Expiration": { "Days": 365 },"ID": "Bucketlifecycle test", "Filter": { "Prefix": "" }, "Status": "Enabled" } ] }"}
> (5/14) Running healthcheck tests ... done in 0 seconds
> (6/14) Running mc tests ... done in 25 seconds
> (7/14) Running minio-go tests ... done in 39 seconds
> (8/14) Running minio-java tests ... done in 32 seconds
> (9/14) Running minio-js tests ... FAILED in 31 minutes and 13 seconds
> {
>   "name": "minio-js",
>   "function": "\"after all\" hook in \"functional tests\"",
>   "duration": 6860,
>   "status": "FAIL",
>   "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
> }
> (9/14) Running minio-py tests ... done in 57 seconds
> (10/14) Running s3cmd tests ... done in 1 minutes and 6 seconds
> (11/14) Running s3select tests ... done in 2 seconds
> (12/14) Running versioning tests ... done in 0 seconds
> 
> Executed 12 out of 14 tests successfully.
> ```

@prakashsvmx I have been observing that minio-js tests hang with S3 gateway sporadically and do not proceed further. Would you be able to test it out on your end? 

This is after rebuilding mint with the latest `minio-js` release.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#2fb008ac-de49-4499-9937-dd01015006f0) |
<a name="2fb008ac-de49-4499-9937-dd01015006f0"></a>
### 15587-2a63a2a/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:31121
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 24 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(9/14) Running minio-java tests ... done in 31 seconds
(10/14) Running minio-js tests ... 
Aborting Mint...
Running with
SERVER_ENDPOINT:      minio-k8s1:31121
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... FAILED in 40 seconds
{"name": "awscli", "duration": 1235, "function": "aws --endpoint-url http://minio-k8s1:31121 s3api put-bucket-lifecycle-configuration --bucket awscli-mint-test-bucket-13644 --lifecycle-configuration file:///tmp/lifecycle.json\n", "status": "FAIL", "error": "Error parsing parameter '--lifecycle-configuration': Invalid JSON: Extra data: line 2 column 1 (char 129)JSON received: { "Rules": [ { "Expiration": { "Days": 365 },"ID": "Bucketlifecycle test", "Filter": { "Prefix": "" }, "Status": "Enabled" } ] }{ "Rules": [ { "Expiration": { "Days": 365 },"ID": "Bucketlifecycle test", "Filter": { "Prefix": "" }, "Status": "Enabled" } ] }"}
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... done in 25 seconds
(7/14) Running minio-go tests ... done in 42 seconds
(8/14) Running minio-java tests ... done in 34 seconds
FAILED in 15 minutes and 11 seconds
(9/14) Running minio-py tests ... done in 1 minutes and 1 seconds
(10/14) Running s3cmd tests ... done in 1 minutes and 6 seconds
(11/14) Running s3select tests ... done in 2 seconds
(12/14) Running versioning tests ... done in 1 seconds

Executed 12 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
