### PR TITLE
Browser: fix UI related issues on object lists, alerts and dialogs

### PR DESCRIPTION
**Pull request by rushenn**
## Description
- Add correct information icons for confirmation dialogs
- Highlight the object lists which are selected by adding a background color
- Remove unnecessary style properties

## How Has This Been Tested?
Tested manually 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Can you fix formatting error @rushenn ?

**Comment by rushenn** [comment]
@harshavardhana Fixed the formatting. Please check now.

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Looks like there are more issues 


```
/home/travis/gopath/src/github.com/minio/minio/browser/app/js/browser/ConfirmModal.js
  29:7  error  Delete `,`  prettier/prettier
/home/travis/gopath/src/github.com/minio/minio/browser/app/js/components/BrowserUpdate.js
  48:43  error  Delete `,`  prettier/prettier
/home/travis/gopath/src/github.com/minio/minio/browser/app/js/objects/ObjectItem.js
  32:10  error  Delete `,`  prettier/prettier
  39:78  error  Delete `,`  prettier/prettier
  79:63  error  Delete `,`  prettier/prettier
  86:65  error  Delete `,`  prettier/prettier
/home/travis/gopath/src/github.com/minio/minio/browser/app/js/uploads/UploadModal.js
  80:44  error  Delete `,`  prettier/prettier
  86:68  error  Delete `,`  prettier/prettier
✖ 8 problems (8 errors, 0 warnings)
  8 errors, 0 warnings potentially fixable with the `--fix` option.
```

**Comment by kmkanagaraj** [comment]
@rushenn you can run `yarn format` to fix the formatting errors.

**Comment by rushenn** [comment]
@kmkanagaraj @harshavardhana Please check now

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by harshavardhana — APPROVED** [review]

**Comment by deekoder** [comment]
I think @rushenn  you may have to send this to newux branch again

**Comment by harshavardhana** [comment]
I changed the base to `newux` branch no more conflicts.

**Pull request merged**
