### PR TITLE
Support TLS auth for Kafka notification target

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Support TLS auth for Kafka notification target

## Motivation and Context
Based off from https://github.com/minio/minio/pull/8593#issuecomment-562072349 

## How to test this PR?
As mentioned in the PR https://github.com/minio/minio/pull/8593#issuecomment-562072349

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by harshavardhana** [comment]
@rzrbld here is the working copy of your PR

**Comment by rzrbld** [comment]
@harshavardhana thank you, but i already created a new one - https://github.com/minio/minio/pull/8609 it pass all the checks and my tests

**Comment by harshavardhana** [comment]
Ah cool 👍 closing

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#58fab835-570d-409f-afc6-e24765eb8295) |
| mint-large-bucket.sh | :x: [more...](#816434ca-827c-4413-adeb-0f20ff36fa09) |
| mint-compression-dist-xl.sh | :x: [more...](#19db0da3-1e3e-4ed8-9236-742ac9d179fb) |
| mint-dist-xl.sh | :x: [more...](#bd78dc04-d3e6-4e56-b03b-35c719fceab1) |
<a name="bd78dc04-d3e6-4e56-b03b-35c719fceab1"></a>
### 8611-f65a17d/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31444
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dc2bf53bf4b3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 16 seconds
(10/14) Running minio-java tests ... FAILED in 4 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream body, long size, String contentType)",
  "args": "contentType: application/javascript",
  "duration": 1971,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3p4qss9, objectName=minio-java-test-1m2qc4i, resource=/minio-java-test-3p4qss9/minio-java-test-1m2qc4i, requestId=15DD966F0EE6DEA6, hostId=9d3dcfe8-9570-4a46-b3e3-d025167a2615)\nrequest={method=POST, url=http://72.28.97.53:31444/minio-java-test-3p4qss9/minio-java-test-1m2qc4i?uploadId=1ff583f1-e828-4dbd-9b6c-03f4da7fe829, headers=Host: 72.28.97.53:31444\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: 21efaa0f9a08b1fa769dbd4b204c7b579633e9f5fda203bd43c26b67b1c68f61\nx-amz-date: 20191205T212048Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191205/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-05T20-56-03Z\nVary: Origin\nX-Amz-Request-Id: 15DD966F0EE6DEA6\nX-Xss-Protection: 1; mode=block\nDate: Thu, 05 Dec 2019 21:20:48 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePost(MinioClient.java:1393), io.minio.MinioClient.completeMultipart(MinioClient.java:5269), io.minio.MinioClient.putObject(MinioClient.java:4613), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.testPutObjectUnknownStreamSize(FunctionalTest.java:548), FunctionalTest.putObject_test8(FunctionalTest.java:576), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="816434ca-827c-4413-adeb-0f20ff36fa09"></a>
### 8611-f65a17d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32533
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d087bec86548:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 54 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 19 seconds
(8/14) Running minio-dotnet tests ... done in 54 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 31 seconds
{
  "args": {},
  "duration": 87797,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="19db0da3-1e3e-4ed8-9236-742ac9d179fb"></a>
### 8611-f65a17d/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30943
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c855d4dbef9b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 3 seconds
(10/14) Running minio-java tests ... FAILED in 36 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 32053,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3k1eudv, objectName=minio-java-test-2acd3uc, resource=/minio-java-test-3k1eudv/minio-java-test-2acd3uc, requestId=15DD966CE893539D, hostId=27fe6747-c280-40b8-8b80-c6081a908194)\nrequest={method=PUT, url=http://72.28.97.54:30943/minio-java-test-3k1eudv/minio-java-test-2acd3uc, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.54:30943\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191205T212039Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191205/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-05T20-56-03Z\nVary: Origin\nX-Amz-Request-Id: 15DD966CE893539D\nX-Xss-Protection: 1; mode=block\nDate: Thu, 05 Dec 2019 21:20:39 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="58fab835-570d-409f-afc6-e24765eb8295"></a>
### 8611-f65a17d/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30380
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4d503ad7e0ea:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dscrsv4uak2wq9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364430,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15DD9671620850C6, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Error: No such image: minio/minio:8611-f65a17d

**Pull request closed without merging**
