### PR TITLE
GCS ListMultipartUploads: return all uploadids

### LINKED ISSUE #7011: GCS: minio-py Mint test 'test_remove_incomplete_upload' fails
minio-py Mint test failure during remove_incomplete_upload test when minio server runs in gateway GCS mode.

Here are the failure console messages:
```
(1/1) Running minio-py tests ... FAILED in 22 minutes and 54 seconds
{
  "duration": 4327,
  "status": "FAIL",
  "name": "minio-py:test_remove_incomplete_upload",
  "function": "remove_incomplete_upload(bucket_name, object_name)",
  "args": {
    "bucket_name": "minio-py-test-c5bce381-daae-48af-b41f-2d7f69116d89",
    "object_name": "f8fd5a8e-2989-47eb-82d9-07e82bbe55d8"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1146, in test_remove_incomplete_upload\n    raise ValueError(\"There are still upload ids not removed\")\nValueError: There are still upload ids not removed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1876, in main\n    test_remove_incomplete_upload(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1148, in test_remove_incomplete_upload\n    raise Exception(err)\nException: There are still upload ids not removed\n",
  "message": "There are still upload ids not removed"
```
## Steps to Reproduce (for bugs)
1. run minio-py mint tests or the following script:
```
from minio import Minio
from minio.error import ResponseError

client = Minio('localhost:9000',
               access_key='minio',
               secret_key='minio123',
    	       secure=False)

# Helper method for test_list_incomplete_uploads
# and test_remove_incomplete_uploads tests
def create_upload_ids(client, b_name, o_name, n):
    # Create 'n' many incomplete upload ids and
    # return the list of created upload ids
    upload_ids_created = []
    for i in range(n):
        upload_id = client._new_multipart_upload(b_name, o_name, {})
        upload_ids_created.append(upload_id)
    return upload_ids_created

# Helper method for test_list_incomplete_uploads
# and test_remove_incomplete_uploads tests
def collect_incomplete_upload_ids(client, b_name, o_name):
    # Collect the upload ids from 'list_incomplete_uploads'
    # command, and return the list of created upload ids
    upload_ids_listed = []
    for obj in client.list_incomplete_uploads(b_name, o_name, False):
        upload_ids_listed.append(obj.upload_id)
    return upload_ids_listed

# Start testing by creating a new bucket
bucket_name = "bucket44"
object_name = "object44"
try:
    client.make_bucket(bucket_name)
    no_of_upload_ids = 3
    # Create 'no_of_upload_ids' many incomplete upload ids
    create_upload_ids(client, bucket_name, object_name, no_of_upload_ids)
    # Remove all of the created upload ids
    client.remove_incomplete_upload(bucket_name, object_name)
    # Get the list of incomplete upload ids for object_name
    # using 'list_incomplete_uploads' command
    upload_ids_listed = collect_incomplete_upload_ids(client,
                                                      bucket_name,
                                                      object_name)
    # Verify listed/returned upload id list
    if upload_ids_listed:
        # The list is not empty
        raise ValueError("There are still upload ids not removed")
except Exception as err:
    raise Exception(err)
finally:
    try:
        client.remove_bucket(bucket_name)
    except Exception as err:
        raise Exception(err)
```
## Regression
It looks like a regression, since this test passed before.

## Your Environment
$ ./minio version
Version: 2018-12-19T22:36:33Z
Release-Tag: DEVELOPMENT.2018-12-19T22-36-33Z
Commit-ID: 7881791a913dacef9562e7a33a8186503d7967bf

The logs in docker container were all empty. If I find more information about the issue, I'll add them.

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
Currently, ListMultipartUploads code returns only the first uploadid.
Modified the code to return all the uploadids returned by gcs to the gateway 

Fixes #7011

## Motivation and Context
Issue #7011

## Regression
No

## How Has This Been Tested?
Using the instructions and sample code provided in #7011

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by krisis** [comment]
@kannappanr It was a conscious decision to have the current behaviour, see https://github.com/minio/minio/pull/6377#pullrequestreview-151189701
/cc @krishnasrinivas

**Comment by harshavardhana** [comment]
@krisis is right, we should making more changes to GCS . The implementation is not complete unless we end up providing uploadId marker if we return all uploadIds

**Comment by ebozduman** [comment]
@krisis,

So, do we expect the end-user to take care of the cleanup by iterating through all the incomplete upload ids and removing them one by one in a loop in his/her script?

If so, then we need to modify our test script accordingly.

**Comment by krisis** [comment]
@ebozduman The way ListMultipartUploads is implemented in GCS gateway, we can't remove incomplete uploads recursively by giving `/` as prefix argument. ListMultipartUploads returns the first upload that matches with bucket and object name. So, to clean up completely, you need to list with prefix=objectName and remove the returned upload. Repeat this until then list is empty.

**Comment by kannappanr** [comment]
> @ebozduman The way ListMultipartUploads is implemented in GCS gateway, we can't remove incomplete uploads recursively by giving `/` as prefix argument. ListMultipartUploads returns the first upload that matches with bucket and object name. So, to clean up completely, you need to list with prefix=objectName and remove the returned upload. Repeat this until then list is empty.

@krisis If you look at the documentation of `remove_incomplete_upload` (https://docs.minio.io/docs/python-client-api-reference.html#remove_incomplete_upload), it is supposed to remove all the incomplete uploads. 

If we have to satisfy what the api promises, then we will have to  enumerate inside `minio-py's` `remove_incomplete_upload` api and remove all the upload ids one by one. We can also talk about combination of fixes in both minio server and SDKs.

**Comment by krisis** [comment]
> If we have to satisfy what the api promises, then we will have to enumerate inside minio-py's remove_incomplete_upload api and remove all the upload ids one by one. We can also talk about combination of fixes in both minio server and SDKs.

@kannappanr I agree. @krishnasrinivas had mentioned that the GCS gateway backend format is not suited for listing all incomplete upload ids. We need to see how to support ListMultipartUploads as client SDKs expect and yet have reasonable performance characteristics.

**Comment by krishnasrinivas** [comment]
@krisis GCS gateway backend format is not suitable recursive listing of incomplete uploads. But it can support listing of all upload ids given an object name. (You can see that this PR is just one line change) On the other hand, in addition to the change in this PR if we also need support uploaidID marker - then it might not be worth the extra code we have to write. Hence we could just take this PR in (one-line change) as it does not complicate existing code and also take care of https://github.com/minio/minio/issues/7011

**Review by krisis — APPROVED** [review]

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
