### PR TITLE
Add a graceful msg when CTRL+C is pressed.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add a graceful msg when CTRL+C is pressed.

## Motivation and Context
Useful to show we have captured interrupt. 

## How Has This Been Tested?
Manually using CTRL-C. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by krisis — APPROVED** [review]
LGTM, verified the PR locally.

**Comment by harshavardhana** [comment]
Release made.. unblocking.

**Comment by deekoder** [comment]
some tests are still failing.

**Comment by harshavardhana** [comment]
No tests are failing @deekoder

**Review by deekoder — APPROVED** [review]

**Pull request merged**
