### PR TITLE
Add tagging support in bucket policy condition

### LINKED ISSUE #10265: Minio does not support ExistingObjectTag policies
Object tagging is common practice and AWS S3 supports the key `ExistingObjectTag` in policies since version `2012-10-17` but it seems unsupported in Minio.

## Expected Behavior
The following policy should work:
```
                    {
                        "Effect": "Deny",
                        "Action": "s3:GetObject",
                        "Resource": "arn:aws:s3:::mybucket/*",
                        "Condition": {
                            "StringNotEquals": {
                                "s3:ExistingObjectTag/status": "DONE"
                            }
                        }
                    }
```

## Current Behavior
Minio will fail to parse the policy.

## Possible Solution
Add support for the missing condition documented here: https://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html

## Steps to Reproduce (for bugs)

1. Create a bucket
2. Add the above policy
3. Notice the error that the condition is not supported and cannot be parsed.

## Context
Having some post processing on files that tag them when complete and blocking downloads of those files until the post processing is done is not possible without this condition.
This is also common practice with bucket antivirus solutions: https://github.com/upsidetravel/bucket-antivirus-function

## Your Environment
* Version used (`minio --version`): Any
* Server setup and configuration: Any
* Operating System and version (`uname -a`): Any

### PR DESCRIPTION
**Pull request by balamurugana**
Fixes #10265

Signed-off-by: Bala.FA <bala.gluster@gmail.com>

Depends on https://github.com/minio/minio/pull/12232

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 12280-b5d5edc/gopath/src/github.com/minio
+ git -C 12280-b5d5edc/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 12280-b5d5edc/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 12280-b5d5edc/gopath/src/github.com/minio/minio fetch --quiet minio pull/12280/head:pr12280
+ git -C 12280-b5d5edc/gopath/src/github.com/minio/minio checkout --quiet pr12280
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/12280-b5d5edc/gopath
+ make -C 12280-b5d5edc/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading cloud.google.com/go v0.65.0
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading github.com/json-iterator/go v1.1.11
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/minio-go/v7 v7.0.11-0.20210302210017-6ae69c73ce78
go: downloading github.com/minio/madmin-go v1.0.2
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading google.golang.org/api v0.31.0
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading golang.org/x/sys v0.0.0-20210510120138-977fb7262007
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading golang.org/x/crypto v0.0.0-20210421170649-83a5a9bb288b
go: downloading github.com/minio/kes v0.14.0
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/google/uuid v1.1.2
go: downloading go.etcd.io/etcd v0.0.0-20201125193152-8a03d2e9614b
go: downloading github.com/klauspost/compress v1.12.2
go: downloading github.com/klauspost/reedsolomon v1.9.11
go: downloading github.com/coredns/coredns v1.4.0
go: downloading go.uber.org/zap v1.14.1
go: downloading github.com/go-ldap/ldap v3.0.2+incompatible
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/gorilla/handlers v1.5.1
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/minio/rpc v1.0.0
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/pierrec/lz4 v2.6.0+incompatible
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.6.0
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/shirou/gopsutil/v3 v3.21.3
go: downloading github.com/tinylib/msgp v1.1.3
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/fatih/structs v1.1.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/dswarbrick/smart v0.0.0-20190505152634-909a45200d6d
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/elastic/go-elasticsearch/v7 v7.12.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading github.com/nats-io/stan.go v0.8.3
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/olivere/elastic/v7 v7.0.22
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/minio/parquet-go v1.0.0
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/willf/bitset v1.1.11
go: downloading golang.org/x/net v0.0.0-20210421230115-4e50805a0758
go: downloading github.com/felixge/httpsnoop v1.0.1
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.7
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/golang/snappy v0.0.3
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading google.golang.org/grpc v1.29.1
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/tidwall/sjson v1.1.6
go: downloading github.com/tidwall/gjson v1.7.5
go: downloading golang.org/x/text v0.3.6
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.1
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20200615164410-66371956d46c
go: downloading github.com/nats-io/jwt v1.1.0
go: downloading github.com/nats-io/nkeys v0.2.0
go: downloading github.com/tidwall/pretty v1.1.0
go: downloading github.com/tidwall/match v1.0.3
go: downloading github.com/prometheus/common v0.14.0
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading go.uber.org/multierr v1.5.0
go: downloading go.uber.org/atomic v1.6.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/tklauser/go-sysconf v0.3.4
go: downloading github.com/jcmturner/dnsutils/v2 v2.0.0
go: downloading github.com/jcmturner/gofork v1.0.0
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading github.com/jcmturner/aescts/v2 v2.0.0
go: downloading github.com/jcmturner/rpc/v2 v2.0.3
go: downloading github.com/minio/argon2 v1.0.0
go: downloading google.golang.org/protobuf v1.25.0
go: downloading google.golang.org/genproto v0.0.0-20200901141002-b3bf27a9dbd1
go: downloading github.com/tklauser/numcpus v0.2.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.5.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20200313005456-10cdbea86bc0
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/minio/md5-simd v1.1.1
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/klauspost/cpuid/v2 v2.0.4
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading go.opencensus.io v0.22.5
go: downloading github.com/jcmturner/goidentity/v6 v6.0.1
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading github.com/mailru/easyjson v0.7.6
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: downloading github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
# github.com/minio/minio/pkg/bucket/policy
pkg/bucket/policy/action.go:315:49: cannot use condition.CommonKeys (type []condition.KeyName) as type []condition.Key in argument to condition.NewKeySet
pkg/bucket/policy/action.go:317:41: cannot use condition.CommonKeys (type []condition.KeyName) as type []condition.Key in argument to condition.NewKeySet
pkg/bucket/policy/action.go:319:41: cannot use condition.CommonKeys (type []condition.KeyName) as type []condition.Key in argument to condition.NewKeySet
pkg/bucket/policy/action.go:321:46: cannot use condition.CommonKeys (type []condition.KeyName) as type []condition.Key in argument to condition.NewKeySet
pkg/bucket/policy/action.go:323:50: cannot use condition.CommonKeys (type []condition.KeyName) as type []condition.Key in argument to condition.NewKeySet
pkg/bucket/policy/action.go:326:9: cannot use condition.CommonKeys (type []condition.KeyName) as type []condition.Key in append
pkg/bucket/policy/action.go:327:13: cannot use condition.S3XAmzServerSideEncryption (type condition.KeyName) as type condition.Key in slice literal
pkg/bucket/policy/action.go:328:13: cannot use condition.S3XAmzServerSideEncryptionCustomerAlgorithm (type condition.KeyName) as type condition.Key in slice literal
pkg/bucket/policy/action.go:331:39: cannot use condition.CommonKeys (type []condition.KeyName) as type []condition.Key in argument to condition.NewKeySet
pkg/bucket/policy/action.go:333:45: cannot use condition.CommonKeys (type []condition.KeyName) as type []condition.Key in argument to condition.NewKeySet
pkg/bucket/policy/action.go:333:45: too many errors
make: *** [build] Error 2

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#3e2ddb15-e19e-4ca9-b8fd-b8fe8a90c314) |
<a name="3e2ddb15-e19e-4ca9-b8fd-b8fe8a90c314"></a>
### 12280-5447635/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31284
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f740ef92639d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2632,
  "function": "aws --endpoint-url http://minio-c2.minio.io:31284 s3api copy-object --bucket awscli-mint-test-bucket-24028 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-24028/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 46 seconds
(7/15) Running minio-dotnet tests ... done in 38 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 3 seconds
{
  "args": {},
  "duration": 434,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 11 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 140,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-d8hgtg, objectName = minio-java-test-2pkk70r-copy, resource = /minio-java-test-d8hgtg/minio-java-test-2pkk70r-copy, requestId = 167E6143E2668203, hostId = 3a0cc7e2-117c-48eb-91e6-394b02d3c5d8)\nrequest={method=PUT, url=http://minio-c2.minio.io:31284/minio-java-test-d8hgtg/minio-java-test-2pkk70r-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-147aq01/minio-java-test-2pkk70r\nHost: minio-c2.minio.io:31284\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210512T171740Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210512/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 12 May 2021 17:17:40 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167E6143E2668203\nX-Xss-Protection: 1; mode=block\nDate: Wed, 12 May 2021 17:17:40 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 48 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 42 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2648",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-18646/s3cmd-test-object-3431 ddd307f8-8c9c-48c4-8bea-f965644d52b6\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id ddd307f8-8c9c-48c4-8bea-f965644d52b6 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#82a04229-3417-47fa-8625-7730bdef6cf9) |
<a name="82a04229-3417-47fa-8625-7730bdef6cf9"></a>
### 12280-ccdbdcd/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30763
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a13164b03430:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2771,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30763 s3api copy-object --bucket awscli-mint-test-bucket-28763 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-28763/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 49 seconds
(7/15) Running minio-dotnet tests ... done in 40 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 19 seconds
{
  "args": {},
  "duration": 305,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 7 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 129,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-3fr1cur, objectName = minio-java-test-181ige7-copy, resource = /minio-java-test-3fr1cur/minio-java-test-181ige7-copy, requestId = 167E67591A9279F6, hostId = 3b039362-afd8-461f-919c-18831f7924b9)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30763/minio-java-test-3fr1cur/minio-java-test-181ige7-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-14969io/minio-java-test-181ige7\nHost: minio-dev4.minio.io:30763\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210512T190908Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210512/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 12 May 2021 19:09:08 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167E67591A9279F6\nX-Xss-Protection: 1; mode=block\nDate: Wed, 12 May 2021 19:09:08 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 47 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 39 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2604",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-10457/s3cmd-test-object-10625 fecb3ebd-3358-444f-9dc6-051fc1d1346f\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id fecb3ebd-3358-444f-9dc6-051fc1d1346f put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Now that the set qualifier is added and server is now using the latest `minio/pkg` - can you rebase this PR? @balamurugana

**Comment by balamurugana** [comment]
Moved to https://github.com/minio/pkg/pull/4

**Pull request closed without merging**
