### PR TITLE
Filter Expires header from user metadata

### LINKED ISSUE #2690: Error when attempting to transfer from GCP to S3
I am attempting to transfer a GCP storage bucket to S3 using the following command with the Windows CLI exe:
`mc.exe cp -r gcs/takeout-export-123/ s3/my-bucket/`

It seems to start transferring but then throws this error:

`mc.exe: <ERROR> Failed to copy https://storage.googleapis.com/takeout-export-123/20190215T172254Z/Resource-456/takeout-20190215T172258Z-001.zip. Expires unsupported user defined metadata name`

## Your Environment
Version: 2019-02-13T19:48:27Z
Release-tag: RELEASE.2019-02-13T19-48-27Z
Commit-id: bc1a108e5c8f3c2a9e25ed34ff221985987b3fed
Windows 10 Pro 64-bit

### PR DESCRIPTION
**Pull request by poornas**
instead save it as a struct field in ObjectInfo as it is a standard HTTP header

## Motivation and Context

Fixes https://github.com/minio/mc/issues/2690. 

## Regression
 No

## How Has This Been Tested?

See https://github.com/minio/minio-go/pull/1076 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :x: [more...](#3c794e27-d630-43b5-bad3-934fe13dad49) |
<a name="3c794e27-d630-43b5-bad3-934fe13dad49"></a>
### 7269-a09da04/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30232
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7bb5dd366b53:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 31 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 43 seconds
(4/13) Running aws-sdk-ruby tests ... done in 19 seconds
(5/13) Running awscli tests ... FAILED in 19 minutes and 53 seconds
{
  "name": "awscli",
  "duration": 193173,
  "function": "aws --endpoint-url http://72.28.97.60:30232 s3 presign s3://awscli-mint-test-bucket-28977/datafile-1-MB\n",
  "status": "FAIL",
  "error": "Checksum verification failed for downloaded object"
}

Executed 4 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#1a8485d9-c503-4a66-b3de-baa753e74576) |
<a name="1a8485d9-c503-4a66-b3de-baa753e74576"></a>
### 7269-b548c79/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30966
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dbe52a46f5df:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 30 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 2 minutes and 57 seconds
(4/13) Running aws-sdk-ruby tests ... done in 4 seconds
(5/13) Running awscli tests ... done in 35 minutes and 17 seconds
(6/13) Running mc tests ... FAILED in 1 minutes and 30 seconds
{
  "name": "mc",
  "duration": "60196",
  "function": "test_put_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21481 --quiet --no-color rm myminio/mc-test-bucket-24852/mc-test-object-22425  >>> \nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-24852/mc-test-object-22425`. Get http://72.28.97.60:30966/mc-test-bucket-24852/?location=: dial tcp 72.28.97.60:30966: i/o timeout"
}

Executed 5 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2699ff35-ab6c-46ea-94cc-01b4b046abb9) |
| mint-compression-dist-xl.sh | :x: [more...](#744c154a-57db-4bb4-b4fe-32620e041a5f) |
| mint-dist-xl.sh | :x: [more...](#f70ad04f-5785-4bcc-b045-6b39863008f9) |
<a name="f70ad04f-5785-4bcc-b045-6b39863008f9"></a>
### 7269-1d03a22/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32590
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 83565c7dbab2:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-w3ewppxlyyvk3d",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360016,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1586FD00A5EEA58A, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="744c154a-57db-4bb4-b4fe-32620e041a5f"></a>
### 7269-1d03a22/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30367
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d1db0b7756ac:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-m4cg4l4mbktevr",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360016,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1586FD012389019A, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="2699ff35-ab6c-46ea-94cc-01b4b046abb9"></a>
### 7269-1d03a22/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32628
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 905f90065e3d:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 5 minutes and 10 seconds
(2/13) Running aws-sdk-java tests ... done in 34 seconds
(3/13) Running aws-sdk-php tests ... done in 4 minutes and 42 seconds
(4/13) Running aws-sdk-ruby tests ... done in 13 seconds
(5/13) Running awscli tests ... FAILED in 18 seconds
{
  "name": "awscli",
  "duration": 11009,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 4 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#32aa6c6f-f62a-4b8c-864a-1fda033ea579) |
| mint-compression-dist-xl.sh | :x: [more...](#2eb8b7c4-7a80-43f6-b69f-b04f581ed680) |
| mint-dist-xl.sh | :x: [more...](#dad6c310-1785-4e70-9aba-8dc052eba016) |
<a name="32aa6c6f-f62a-4b8c-864a-1fda033ea579"></a>
### 7269-31a163f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32685
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 27a4a9b4becb:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qclpxwzwe6ztu3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 337,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:32685/aws-sdk-go-test-qclpxwzwe6ztu3: dial tcp 72.28.97.60:32685: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="2eb8b7c4-7a80-43f6-b69f-b04f581ed680"></a>
### 7269-31a163f/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30129
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f58cc2375d8f:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-u1gg3s0oxp5hmw",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360023,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1586FDE9A089FC66, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="dad6c310-1785-4e70-9aba-8dc052eba016"></a>
### 7269-31a163f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32710
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a0fa9726c7cf:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-3wr3gaw3wx9xow",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360018,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1586FDE999D32338, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```

**Review by donatello — CHANGES_REQUESTED** [review]
Code looks good, but we probably need to vendor this in the usual way - i.e. merge the change in minio-go first and then just vendor here. The reasoning is that vendor packages are expected to be at the same version as in the vendor.json file.

**Comment by poornas** [comment]
> Code looks good, but we probably need to vendor this in the usual way - i.e. merge the change in minio-go first and then just vendor here. The reasoning is that vendor packages are expected to be at the same version as in the vendor.json file.

That's true, waiting for the minio-go PR to be merged before vendorizing properly

**Comment by poornas** [comment]
vendorized minio-go

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by Praveenrajmani — APPROVED** [review]
LGTM

**Review by donatello — APPROVED** [review]

**Pull request merged**
