### PR TITLE
skip speedtest bucket from site-replication

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
skip speedtest bucket from site-replication

## Motivation and Context
just skip versioning to skip replication

## How to test this PR?
Setup site replication and observe 
`mc support perf object` does not perform replication

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
LGTM

**Comment by shtripat** [comment]
I created two sites `m1` and `m2` and setup site replication using `mc admin replicate add m1 m2`.
After this while running `mc support perf object m1 --airgap --dev` I see that `mc ls m1` hangs till support command running  and `mc ls m2` shows a bucket with name `minio-perf-test-tmp-bucket/` which later after completion of support command gets cleared.
Also I see below errors in second MinIO instance's log
```
API: SYSTEM()
Time: 16:12:46 UTC 11/06/2023
DeploymentID: 10f25440-ebe1-4d02-8c2a-001ca734eb15
Error: m2: ConfigureReplication: Site replication error(s): 
'ConfigureReplication' on site m1 (257836d8-ea07-4bd9-bfe5-4c6a1a96bceb): failed(m2->m1: Bucket target creation error: Remote already exists for this bucket: minio-perf-test-tmp-bucket) (*fmt.wrapError)
       4: internal/logger/logger.go:258:logger.LogIf()
       3: cmd/site-replication.go:4621:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
       2: cmd/site-replication.go:3944:cmd.(*SiteReplicationSys).healBuckets()
       1: cmd/site-replication.go:3830:cmd.(*SiteReplicationSys).startHealRoutine()
```
The error is seen after support completes. Is it expected?

**Review by poornas — APPROVED** [review]

**Comment by harshavardhana** [comment]
yes that is expected @shtripat since `support perf` tests block S3 API traffic.

**Comment by harshavardhana** [comment]
yes all of this is async so it is expected that it happens @shtripat

**Review by shtripat — APPROVED** [review]
lgtm

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
