### PR TITLE
fix: Use correct replication status in replication healing

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
In case of replication healing, we always store completed status in the
object metadata, which is wrong because replication could fail in the
further retries.

## Motivation and Context
Fix replication status in some cases

## How to test this PR?
Setup replication & stop destination server then check for the status of the source object
when replication fails

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by vadmeste** [comment]
@poornas @krisis could you review this ?

**Review by poornas — APPROVED** [review]
LGTM

**Review by krisis — APPROVED** [review]

**Comment by krisis** [comment]
@vadmeste nice catch!

**Pull request merged**
