### PR TITLE
Simplify putObject by not breaking the stream into parts

### PR DESCRIPTION
**Pull request by krishnasrinivas**
Needs careful review (for encryption and compression's special needs on sizes)

## Description

We broke into parts previously as we had checksum for the entire file
to tax less on memory and to have better TTFB. We dont need to now
after the streaming-bitrot change.

## Motivation and Context

Code simplification

## Regression

No

## How Has This Been Tested?

By creating the objects and making sure that the backend format for the object is as expected

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
why do we need to go back? @krishnasrinivas - we shouldn't change an existing code without any bugs. Even now with smaller parts, it's better because allows for smaller parts rather than using large single files. It is generally helpful on XFS to create a bunch of 64MiB files rather than a full single 5Gig file.

**Review by harshavardhana — CHANGES_REQUESTED** [review]
I don't see a good reason for this change at this point in time.

**Comment by krishnasrinivas** [comment]
> we shouldn't change an existing code without any bugs.

We have always advocated towards simplifying/refactoring code even if there are no bugs.

> it's better because allows for smaller parts rather than using large single files. It is generally helpful on XFS to create a bunch of 64MiB files rather than a full single 5Gig file.

what are the advantages of lot of small part files? One advantage I can see is if there is a bitrot error and we have to heal a part, we will have to heal a smaller part. But ofcourse our current code heals all the parts even if one part has bitrot error (to have the healing code simple) So this advantage also not there.

Advantages of having having a just one part:
1) Simpler code
2) smaller xl.json
3) less inodes usage (5G file will use 2 inodes instead of 80)
4) less chattiness during putobject because you don't have to create and write a lot of different files
5) less chattiness during getobject because you don't have to open and read a lot of files

**Comment by harshavardhana** [comment]
> what are the advantages of lot of small part files? One advantage I can see is if there is a bitrot error and we have to heal a part, we will have to heal a smaller part. But ofcourse our current code heals all the parts even if one part has bitrot error (to have the healing code simple) So this advantage also not there.

are you saying that for multipart we heal all parts even if one part has the issue? then that is a bug in our code - we shouldn't do that and we should only heal which requires healing. Healing all parts would tax the entire cluster using up all the bandwidth. 

> * Simpler code
> * smaller xl.json
> * less inodes usage (5G file will use 2 inodes instead of 80)
> * less chattiness during putobject because you don't have to create and write a lot of different files
> * less chattiness during getobject because you don't have to open and read a lot of files

Most of our objects either fall under

- < 64MiB for single PUT 
- Multipart > 64MiB (most clients already do multipart)

So practically IMO all of the above arguments are not valid.  For chattiness problems, I would like some **benchmarking** results to see greater benefits. 

**NOTE: For single PUT object we already support a single stream of 5TiB object size, not just 5GiB we don't restrict it so you will have users who have uploaded > 5GiB already** 

Another problem is that this change is going to introduce another type of backend behavior for objects

- Streaming bitrot single PUT multiple parts (already released)
- Old bitrot single PUT multiple parts (already released)
- Streaming bitrot single PUT single part (TBD in this PR)

I am not denying we shouldn't simplify the code but the cost of this change is not justifying itself. We need to show this has practical benefits with some proven results starting with *benchmarking* - because just reducing the number of lines of code is not sufficient enough evidence.

**Comment by krishnasrinivas** [comment]
@harshavardhana I discussed with AB about this PR, he says we should take this change in.

**Comment by harshavardhana** [comment]
My concerns still hold, the change is not the issue. Simplification is always great. 

But since we shouldn't do a theoretical guess here that this change has benefits without getting some numbers.

**Comment by krishnasrinivas** [comment]
let's discuss about this @harshavardhana

**Comment by harshavardhana** [comment]
Can you rebase this ?

**Comment by krishnasrinivas** [comment]
will do @harshavardhana

**Comment by harshavardhana** [comment]
@krishnasrinivas can you rebase this PR?

**Comment by harshavardhana** [comment]
@abperiasamy suggested this should be taken in as well as part of perf improvements..@deekoder added high priority label.

@krishnasrinivas please rebase this PR with master.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Travis is failing @krishnasrinivas PTAL

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#e09e24cb-930e-4f2c-9586-e2fc9956fc26) |
<a name="e09e24cb-930e-4f2c-9586-e2fc9956fc26"></a>
### 7199-9725409/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31834
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a67d0553ecb2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ty40hl2jutsj0i",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360011,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159E7780F224A927, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by kannappanr** [comment]
ping @vadmeste @aead

**Review by harshavardhana — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM and tested

**Pull request merged**
