### PR TITLE
Require go 1.7.1 to build Minio server

### LINKED ISSUE #2674: [distributed] : Move to Go 1.7.x as default for distributed build.
- With GC benefits being very clear from the load tests here https://github.com/minio/minio/issues/2445 , enforce go 1.7.x for builds.

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #2674

### CODE REVIEW

**Comment by vadmeste** [comment]
This is also strange. Increase of 1% in code coverage. What's going on ? (codecov.io is changing its algorithm?)

**Comment by harshavardhana** [comment]
> This is also strange. Increase of 1% in code coverage. What's going on ? (codecov.io is changing its algorithm?)

This is related to go1.7 behavior perhaps

**Comment by harshavardhana** [comment]
> This is also strange. Increase of 1% in code coverage. What's going on ? (codecov.io is changing its algorithm?)
> This is related to go1.7 behavior perhaps

Now its fixed.

**Comment by vadmeste** [comment]
Should be fine.

**Comment by harshavardhana** [comment]
Ping @hackintoshrao would you confirm that we move to go1.7?

**Comment by hackintoshrao** [comment]
@harshavardhana : Will test it and confirm.

**Comment by hackintoshrao** [comment]
LGTM 👍 Not able to run the binary when built with Go 1.6 and Go 1.7, works when built with Go 1.7.1 .

**Comment by rmb938** [comment]
This broke the minio:edge docker image. Running it now gives this error

```
+ exec app server /export
app: <ERROR> Please recompile Minio with Golang version >= 1.7.1.
```

**Comment by vadmeste** [comment]
@rmb938, thanks for reporting. Will fix it right now.

**Pull request merged**
