### PR TITLE
Remove unusued Set/GetConfigKeys API

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Remove unused Set/GetConfigKeys API

## Motivation and Context
Remove unused Set/GetConfigKeys API

## How to test this PR?
Part of the #7463 PR but sending them separately for faster merges.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#791cb0c3-6e02-4286-8c49-ed75a9587bc0) |
<a name="791cb0c3-6e02-4286-8c49-ed75a9587bc0"></a>
### 8235-cd3b89d/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32733
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 94b9ea7cf722:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 49 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 33 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 39 seconds
(10/14) Running minio-java tests ... done in 11 seconds
(11/14) Running minio-js tests ... FAILED in 10 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-962146c3-8a67-49c8-ad20-e849686004be, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 2807,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TCP.onread (net.js:580:26)"
}

Executed 10 out of 14 tests successfully.
```

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by kannappanr** [comment]
Should there be a corresponding mc PR after this?

**Comment by harshavardhana** [comment]
> Should there be a corresponding mc PR after this?

mc doesn't use these APIs there is no one using this API right now, that's why it's unused` and being removed.

**Review by poornas — APPROVED** [review]
LGTM

**Pull request merged**
