### PR TITLE
Deprecate auto detection of container user

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Deprecate auto detection of container user

## Motivation and Context
There is no reliable way to handle fallbacks for
MinIO deployments, due to the various command line
options and multiple locations which require
access inside the container.

Parsing command line options is tricky to figure
out which is the backend disk etc, we did try
to fix this in implementations of check-user.go
but it wasn't complete and introduced more bugs.

This PR simplifies the entire approach to rather
than running Docker container as non-root by default
always, it allows users to opt-in. Such that they
are aware that that is what they are planning to do.

In fact, there are other ways docker containers can
be run as regular users, without modifying our
internal behavior and adding more complexities.

## How to test this PR?
`TAG=y4m4/minio:dev make docker`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9012ec14-4c97-4915-8918-68a17c88700b) |
| mint-dist-xl.sh | :x: [more...](#deea4d3f-9225-49bc-960a-ea6f91b44bac) |
<a name="9012ec14-4c97-4915-8918-68a17c88700b"></a>
### 7930-918dc35/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30694
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e6252df1ec0a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 59 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 38 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 34 seconds
{
  "name": "mc",
  "duration": "109539",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-2735 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-9319  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-9319/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-9319/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-9319/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-9319/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-9319/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-9319/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-9319/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-9319/datafile-129-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-9319/datafile-100-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-9319/datafile-33-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-9319/datafile-11-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-9319/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-9319/datafile-65-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-9319/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-9319/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 439.80 MiB, Speed: 4.02 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="deea4d3f-9225-49bc-960a-ea6f91b44bac"></a>
### 7930-918dc35/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32108
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 51879a0527db:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... FAILED in 51 seconds
{
  "name": "awscli",
  "duration": 9989,
  "function": "aws --endpoint-url http://72.28.97.59:32108 s3 rb s3://awscli-mint-test-bucket-14921/\n",
  "status": "FAIL",
  "error": "remove_bucket failed: s3://awscli-mint-test-bucket-14921/ An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 4 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
This is a high priority PR - this is affecting all our docker ecosystem deployments. PTAL @krisis @nitisht

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#613357f4-3e15-425b-baff-4a4b445139bd) |
| mint-large-bucket.sh | :x: [more...](#434572aa-23df-4311-ae64-85f4ba653061) |
| mint-dist-xl.sh | :x: [more...](#35fe54f6-acca-4336-8cbc-e7e80ae576f8) |
<a name="613357f4-3e15-425b-baff-4a4b445139bd"></a>
### 7930-38d8cf0/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30252
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 80cd3716bd98:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 22 seconds
(8/14) Running minio-dotnet tests ... done in 21 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/14) Running minio-java tests ... done in 21 seconds
(11/14) Running minio-js tests ... done in 37 seconds
(12/14) Running minio-py tests ... done in 1 minutes and 14 seconds
(13/14) Running s3cmd tests ... FAILED in 7 seconds
{
  "name": "s3cmd",
  "duration": "2515",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  following lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nInvoked as: /usr/local/bin/s3cmd --config /tmp/.s3cmd-25611/s3cfg get s3://s3cmd-test-bucket-1547/s3cmd-test-object-28163 s3cmd-test-object-28163.downloaded\nProblem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer\nS3cmd:   2.0.2\npython:   3.5.2 (default, Nov 12 2018, 13:43:14) \n[GCC 5.4.0 20160609]\nenvironment LANG=C.UTF-8\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 3092, in <module>\n    rc = main()\n  File \"/usr/local/bin/s3cmd\", line 3001, in main\n    rc = cmd_func(args)\n  File \"/usr/local/bin/s3cmd\", line 590, in cmd_object_get\n    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 716, in object_get\n    response = self.recv_file(request, stream, labels, start_position)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 1742, in recv_file\n    data = http_response.read(this_chunk)\n  File \"/usr/lib/python3.5/http/client.py\", line 448, in read\n    n = self.readinto(b)\n  File \"/usr/lib/python3.5/http/client.py\", line 488, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  above lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
}

Executed 12 out of 14 tests successfully.
```
<a name="35fe54f6-acca-4336-8cbc-e7e80ae576f8"></a>
### 7930-38d8cf0/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32105
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1e72477882ac:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 15 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 50 seconds
(10/14) Running minio-java tests ... FAILED in 47 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 473,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2qh7801, objectName=minio-java-test-291lah9, resource=/minio-java-test-2qh7801/minio-java-test-291lah9, requestId=15B200C62ACCB0C4, hostId=dec54049-56a5-4650-96b2-12e4b84efb55)\nrequest={method=DELETE, url=http://72.28.97.55:32105/minio-java-test-2qh7801/minio-java-test-291lah9?uploadId=b8e3b49f-9660-4793-9cdf-5dfb40e8200c, headers=Host: 72.28.97.55:32105\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190716T213431Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190716/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-16T21-15-23Z\nVary: Origin\nX-Amz-Request-Id: 15B200C62ACCB0C4\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jul 2019 21:34:32 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="434572aa-23df-4311-ae64-85f4ba653061"></a>
### 7930-38d8cf0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31394
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 40a2cd25b2b3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 19 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 18 seconds
{
  "name": "mc",
  "duration": "96334",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-29038 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-26528  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-26528/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-26528/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-26528/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-26528/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-26528/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-26528/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-26528/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-26528/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-26528/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-26528/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-26528/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-26528/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-26528/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-26528/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-26528/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 447.11 MiB, Speed: 4.65 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Review by krisis — APPROVED** [review]

**Review by nitisht — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#efc79bbc-092e-47a9-89e1-4931398a80b8) |
| mint-dist-xl.sh | :x: [more...](#30f9425b-c7c7-444b-a28e-0b5583e38a35) |
<a name="30f9425b-c7c7-444b-a28e-0b5583e38a35"></a>
### 7930-0632e59/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31169
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 196d848e81fa:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 56 seconds
(8/14) Running minio-dotnet tests ... done in 48 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 15 seconds
(10/14) Running minio-java tests ... FAILED in 43 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName)",
  "duration": 35,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.52:31169/minio-java-test-2oidikk/minio-java-test-3gtc2qk?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190717%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190717T175459Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=c48a46e559fd6dc66764eec6bb14a184675c2be4a734b1ebd94fea14032e4dd2}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-3gtc2qk</Key><BucketName>minio-java-test-2oidikk</BucketName><Resource>/minio-java-test-2oidikk/minio-java-test-3gtc2qk</Resource><RequestId>15B2435FD23A3F3A</RequestId><HostId>c3cb06cf-59c6-4c2a-9edd-f09d4c96dfef</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test1(FunctionalTest.java:1767), FunctionalTest.runTests(FunctionalTest.java:2994), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="efc79bbc-092e-47a9-89e1-4931398a80b8"></a>
### 7930-0632e59/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32381
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 19f9d91f723c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 3 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 58 seconds
{
  "name": "mc",
  "duration": "141755",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-27826 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-22310  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-22310/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-22310/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-22310/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-22310/datafile-1-b`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-22310/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-22310/datafile-11-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-22310/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-22310/datafile-100-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-22310/datafile-10-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-22310/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-22310/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-22310/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-22310/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-22310/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-22310/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 473.43 MiB, Speed: 3.34 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#35891135-9f50-4e82-9d0c-989a35c7cf09) |
| mint-compression-fs.sh | :x: [more...](#2d687887-dfe3-4986-9c8f-664b1fa3ccaa) |
| mint-worm.sh | :x: [more...](#809888db-20d7-42df-a9d6-f06725c750f4) |
| mint-dist-xl.sh | :x: [more...](#3f9909df-13aa-48f0-ba50-8e4c3879cb80) |
<a name="2d687887-dfe3-4986-9c8f-664b1fa3ccaa"></a>
### 7930-015736e/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32492
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7e4e731783a4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 19 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gl1ldbain2kp9i",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 18154,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32492/aws-sdk-go-test-gl1ldbain2kp9i: dial tcp 72.28.97.57:32492: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="35891135-9f50-4e82-9d0c-989a35c7cf09"></a>
### 7930-015736e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32723
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 35ca709ed2b6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 18 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-m4zl1mzeav5pqp",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 17863,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32723/aws-sdk-go-test-m4zl1mzeav5pqp: dial tcp 72.28.97.57:32723: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="809888db-20d7-42df-a9d6-f06725c750f4"></a>
### 7930-015736e/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30828
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e58b0c290991:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-caicq7rv76wmqesws8p9zlfx1ap5fndry4j2gs1mrddugz4huwtwkmr",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 12280,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30828/bucket-caicq7rv76wmqesws8p9zlfx1ap5fndry4j2gs1mrddugz4huwtwkmr: dial tcp 72.28.97.57:30828: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="3f9909df-13aa-48f0-ba50-8e4c3879cb80"></a>
### 7930-015736e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31507
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a52fffdc5e96:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 25 seconds
(10/14) Running minio-java tests ... FAILED in 42 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 713,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-5preon, objectName=minio-java-test-ui9n2t, resource=/minio-java-test-5preon/minio-java-test-ui9n2t, requestId=15B244B60BB3F4CA, hostId=0647c670-1d11-471e-ae93-f5d7f859dfa6)\nrequest={method=DELETE, url=http://72.28.97.59:31507/minio-java-test-5preon/minio-java-test-ui9n2t?uploadId=e26dab27-e9a2-4909-aedd-ad61a9d43021, headers=Host: 72.28.97.59:31507\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190717T181929Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190717/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 359\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-17T18-01-31Z\nVary: Origin\nX-Amz-Request-Id: 15B244B60BB3F4CA\nX-Xss-Protection: 1; mode=block\nDate: Wed, 17 Jul 2019 18:19:29 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Pull request merged**
