### PR TITLE
Update Minio version in docs and example yaml files

### PR DESCRIPTION
**Pull request by nitisht**
## Description
Update the Minio version in docs and yaml files 

## Motivation and Context
After Minio release `RELEASE.2017-09-29T19-16-56Z` docs and yaml files need to be updated.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by vadmeste** [comment]
@nitisht, why we don't use minio/minio:latest instead of putting a specific Minio image version ?

**Comment by harshavardhana** [comment]
> @nitisht, why we don't use minio/minio:latest instead of putting a specific Minio image version ?

AFAIK - It is generally considered bad practice in prod deployments to use "latest" directly.  It also disallows accidental updates to the image if the stack is being restarted etc.

**Comment by vadmeste** [comment]
> AFAIK - It is generally considered bad practice in prod deployments to use "latest" directly. It also disallows accidental updates to the image if the stack is being restarted etc.

yes, that makes sense.. but we need to keep this documentation always updated, we had one user complaining about a bug which was already fixed in the last _release_.

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by nitisht** [comment]
> why we don't use minio/minio:latest instead of putting a specific Minio image version

@vadmeste here is more detailed explanation of the problem with `latest` tag : http://container-solutions.com/docker-latest-confusion/

I agree we should keep these docs always updated, probably we can do it as a part of build automation. Let me add a point there.

**Pull request merged**
