### PR TITLE
Allow folders inside buckets to be opened in a new tab

### LINKED ISSUE #7836: MinIO Browser - Cannot open a folder in a new Tab
It is not possible in chrome to open a folder in a new tab. Its Always open the new tab in the bucket overview.

Steps to Reproduce (for bugs)
Right click on a folder in the bucket overview an choose open in new tab.

Your Environment
Version used (minio version): 2019-06-13T01:41:13Z
Nuget packages: MinIO v3.0.11, AWSSDK.S3 v3.3.102.12
Operating System and version (uname -a): Windows 10 Pro Version 1803

### PR DESCRIPTION
**Pull request by kaankabalak**
## Description

Check if a list item is a folder and if so change `href` attribute inside the `a` tag to lead to inside the folder.

## Motivation and Context

Fixes #7836

## Regression

No

## How Has This Been Tested?

1. Create folders inside buckets and inside folders to test the scenarios
2. Right click on a folder and verify that it can be opened on a new tab
3. Click on a folder and verify that it is opened
4. Try clicking on list items that aren't folders to verify that the previous behavior is unchanged

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#5f5a2a7e-6e2b-4809-9e46-45230a8c9b2d) |
| mint-dist-xl.sh | :x: [more...](#f51b4ab5-f6f1-4e1d-a9bf-562a7878d8f7) |
<a name="f51b4ab5-f6f1-4e1d-a9bf-562a7878d8f7"></a>
### 7840-bdcbd16/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31405
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eac386f97584:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 54 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 52 seconds
(10/14) Running minio-java tests ... done in 44 seconds
(11/14) Running minio-js tests ... FAILED in 1 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 19,
  "status": "FAIL",
  "error": "S3Error: Please reduce your request at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```
<a name="5f5a2a7e-6e2b-4809-9e46-45230a8c9b2d"></a>
### 7840-bdcbd16/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31197
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 721c392e033e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dkf5skybuqnyym",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360016,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15ABE58B6B254747, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by kanagarajkm — DISMISSED** [review]
Verified.

**Review by harshavardhana — DISMISSED** [review]

**Comment by harshavardhana** [comment]
@kaankabalak can you update the browser assets

**Comment by kaankabalak** [comment]
Updating now...

**Comment by kaankabalak** [comment]
I have updated the ui-assets.go file, I would appreciate if you could take another look @kanagarajkm @harshavardhana

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3e367ddc-bb2f-457d-83c3-e3d7c80ed97a) |
| mint-compression-fs.sh | :x: [more...](#3004055b-a73c-46a0-997e-18d20a6e6f8a) |
| mint-dist-xl.sh | :x: [more...](#decd598d-0514-40fd-9391-6b022fabd355) |
<a name="3e367ddc-bb2f-457d-83c3-e3d7c80ed97a"></a>
### 7840-2a620b5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31639
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0dc0c195fa8a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 44 seconds
{
  "name": "mc",
  "duration": "16628",
  "function": "test_mirror_list_objects",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-26948 --quiet --no-color rb --force myminio/mc-test-bucket-31674  >>> \nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-31674`. The bucket you tried to delete is not empty."
}

Executed 6 out of 14 tests successfully.
```
<a name="3004055b-a73c-46a0-997e-18d20a6e6f8a"></a>
### 7840-2a620b5/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32683
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f516f8f88fa9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2qswbf6bjmzb4e",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3052,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32683/aws-sdk-go-test-2qswbf6bjmzb4e: dial tcp 72.28.97.57:32683: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="decd598d-0514-40fd-9391-6b022fabd355"></a>
### 7840-2a620b5/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31032
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0e0d91cf1425:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 7 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 52 seconds
(10/14) Running minio-java tests ... FAILED in 38 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 445,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1ve2s7h, objectName=minio-java-test-10u365, resource=/minio-java-test-1ve2s7h/minio-java-test-10u365, requestId=15ADB26C1AF197C2, hostId=59929b6c-9969-4be2-a543-2df4b9b3004c)\nrequest={method=DELETE, url=http://72.28.97.61:31032/minio-java-test-1ve2s7h/minio-java-test-10u365?uploadId=188a3993-4125-4f30-ac1f-9decb095bcb6, headers=Host: 72.28.97.61:31032\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190702T205343Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190702/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-02T20-34-39Z\nVary: Origin\nX-Amz-Request-Id: 15ADB26C1AF197C2\nX-Xss-Protection: 1; mode=block\nDate: Tue, 02 Jul 2019 20:53:43 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Pull request merged**
