### PR TITLE
Validate prefixes on all sets

### LINKED ISSUE #6293: Some directories invisible after upload on EC-based server instance
I have an EC-based server instance with 32 disks and try to upload this directory strucuture:
```
$ find 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/
6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/
6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30
6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml
6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/Arial.ttf
```

## Expected Behavior
When I upload this directory, I expect to be able to list it.

## Current Behavior
The API doesn't return the second level directory, only if i list the bucket recursively.
This affects minio, s3cmd, and s3fs. None of these client implementations is able to list the second level directory withnout recursive list (which is not supported on s3fs, therefore renders the directory invisible).

## Steps to Reproduce (for bugs)
```
$ minio server data/disk{1..32}
..
$ mc mb local/test
[success]
$ mc cp -r 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b local/test
[success]
$ mc ls local/test
**[nothing]**
$ mc ls -r local/test
{"status":"success","type":"file","lastModified":"2018-08-16T15:19:58.618+02:00","size":367112,"key":"6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/Arial.ttf","etag":"5995c725ca5a13be62d3dc75c2fc59fc"}
{"status":"success","type":"file","lastModified":"2018-08-16T15:19:58.626+02:00","size":2846,"key":"6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml","etag":"90949995bb143b946f124c5f716a6065"}
```

## Your Environment
```
$ minio version
Version: 2018-08-02T23:11:36Z
Release-Tag: RELEASE.2018-08-02T23-11-36Z
Commit-ID: a091b1a3eefbaea07499bef9a5462280ec9d2a7a
```
```
$ mc version
Version: 2018-08-02T17:39:44Z
Release-tag: RELEASE.2018-08-02T17-39-44Z
Commit-id: 9998e077dfd70a0c1189f1a9b5d7ab25a6e01b79
```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This PR fixes a regression introduced in 8eb838bf91bf7d98aa2ba9eac976e78c9530225e
where hashing technique was used on prefixes to get the right set
to perform the operation, this is not correct since prefixes and
their corresponding keys might hash to a different value depending
on the key length.

For prefixes/directories we should look everywhere to support proper
quorum based listing.

## Motivation and Context
Fixes #6293

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by deekoder** [comment]
Fixes regression. Please review asap.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by poornas — APPROVED** [review]
tested locally. LGTM

**Review by kannappanr — APPROVED** [review]
Tested. LGTM

**Pull request merged**
