### PR TITLE
fix: validate partNumber in queryParam as part of preConditions

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: validate partNumber in queryParam as part of preConditions

## Motivation and Context
Add additional checks to validate incoming partNumber

## How to test this PR?
You would need aws-cli to test this PR

```
~ aws s3api head-object --part-number
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 9386-0aa7802/gopath/src/github.com/minio
+ git -C 9386-0aa7802/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9386-0aa7802/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9386-0aa7802/gopath/src/github.com/minio/minio fetch --quiet minio pull/9386/head:pr9386
+ git -C 9386-0aa7802/gopath/src/github.com/minio/minio checkout --quiet pr9386
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/9386-0aa7802/gopath
+ make -C 9386-0aa7802/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/minio-go/v6 v6.0.53
go: downloading github.com/gorilla/mux v1.7.0
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/klauspost/compress v1.10.3
go: downloading github.com/kurin/blazer v0.5.4-0.20200327014341-8f90a40f8af7
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/rs/cors v1.6.0
go: downloading github.com/json-iterator/go v1.1.9
go: downloading github.com/miekg/dns v1.1.8
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/prometheus/common v0.2.0
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/cheggaaa/pb v1.0.28
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/minio/lsync v1.0.1
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading gopkg.in/ini.v1 v1.48.0
go: downloading google.golang.org/grpc v1.22.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/fatih/color v1.7.0
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/minio/sio v0.2.0
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/nats-io/nats.go v1.9.1
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: downloading github.com/golang/protobuf v1.3.2
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/tinylib/msgp v1.1.1
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/Shopify/sarama v1.24.1
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading github.com/klauspost/pgzip v1.2.1
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading go.uber.org/atomic v1.3.2
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/nats-io/nkeys v0.1.3
go: downloading github.com/gorilla/handlers v1.4.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: downloading github.com/minio/simdjson-go v0.1.5-0.20200303142138-b17fe061ea37
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading gopkg.in/yaml.v2 v2.2.4
go: downloading github.com/lib/pq v1.1.1
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading github.com/minio/parquet-go v0.0.0-20200414234858-838cfa8aae61
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/klauspost/cpuid v1.2.2
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading go.opencensus.io v0.21.0
go: downloading github.com/philhofer/fwd v1.0.0
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/nats-io/stan.go v0.4.5
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/tidwall/match v1.0.1
go: downloading github.com/tidwall/pretty v1.0.0
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/beevik/ntp v0.2.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
# github.com/minio/minio/cmd/gateway/oss
cmd/gateway/oss/gateway-oss.go:557:61: cannot use opts.CheckCopyPrecondFn (type "github.com/minio/minio/cmd".CheckCopyPreconditionFn) as type "github.com/minio/minio/cmd".ObjectOptions in argument to "github.com/minio/minio/cmd".NewGetObjectReaderFromReader
# github.com/minio/minio/cmd/gateway/b2
cmd/gateway/b2/gateway-b2.go:481:61: cannot use opts.CheckCopyPrecondFn (type "github.com/minio/minio/cmd".CheckCopyPreconditionFn) as type "github.com/minio/minio/cmd".ObjectOptions in argument to "github.com/minio/minio/cmd".NewGetObjectReaderFromReader
# github.com/minio/minio/cmd/gateway/hdfs
cmd/gateway/hdfs/gateway-hdfs.go:469:61: cannot use opts.CheckCopyPrecondFn (type "github.com/minio/minio/cmd".CheckCopyPreconditionFn) as type "github.com/minio/minio/cmd".ObjectOptions in argument to "github.com/minio/minio/cmd".NewGetObjectReaderFromReader
# github.com/minio/minio/cmd/gateway/s3
cmd/gateway/s3/gateway-s3-sse.go:318:65: cannot use o.CheckCopyPrecondFn (type "github.com/minio/minio/cmd".CheckCopyPreconditionFn) as type "github.com/minio/minio/cmd".ObjectOptions in argument to "github.com/minio/minio/cmd".NewGetObjectReader
cmd/gateway/s3/gateway-s3.go:404:61: cannot use opts.CheckCopyPrecondFn (type "github.com/minio/minio/cmd".CheckCopyPreconditionFn) as type "github.com/minio/minio/cmd".ObjectOptions in argument to "github.com/minio/minio/cmd".NewGetObjectReaderFromReader
# github.com/minio/minio/cmd/gateway/azure
cmd/gateway/azure/gateway-azure.go:721:61: cannot use opts.CheckCopyPrecondFn (type "github.com/minio/minio/cmd".CheckCopyPreconditionFn) as type "github.com/minio/minio/cmd".ObjectOptions in argument to "github.com/minio/minio/cmd".NewGetObjectReaderFromReader
# github.com/minio/minio/cmd/gateway/gcs
cmd/gateway/gcs/gateway-gcs.go:757:61: cannot use opts.CheckCopyPrecondFn (type "github.com/minio/minio/cmd".CheckCopyPreconditionFn) as type "github.com/minio/minio/cmd".ObjectOptions in argument to "github.com/minio/minio/cmd".NewGetObjectReaderFromReader
make: *** [build] Error 2

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#79a43337-9611-4ce8-927c-a0dd3da8508d) |
| mint-gateway-azure.sh | :x: [more...](#8b782a15-58f7-41e4-8472-cc7fe6f95fc6) |
| mint-gateway-nas.sh | :x: [more...](#c24aa037-3458-4a92-b13f-0ffae2d7054d) |
<a name="79a43337-9611-4ce8-927c-a0dd3da8508d"></a>
### 9386-233e7f8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:32476
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ea45b4007b26:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 6 minutes and 7 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-bwcmyemawioc9v",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 366944,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 16070E79E01BBBFD, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 15 tests successfully.
```
<a name="c24aa037-3458-4a92-b13f-0ffae2d7054d"></a>
### 9386-233e7f8/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32389
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2adf793bccb7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 34 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... FAILED in 29 seconds
{}

Executed 8 out of 15 tests successfully.
```
<a name="8b782a15-58f7-41e4-8472-cc7fe6f95fc6"></a>
### 9386-233e7f8/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:32441
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d18c1b47f573:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... FAILED in 55 seconds
{
  "name": "awscli",
  "duration": 4724,
  "function": "aws --endpoint-url http://minio-c4.minio.io:32441 s3api head-object --bucket awscli-mint-test-bucket-6004 --key datafile-1-kB-copy\n",
  "status": "FAIL",
  "error": "StorageClass was not applied"
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#20d676b6-b334-4377-9be4-5fc563447a9e) |
| mint-gateway-nas.sh | :x: [more...](#7eee6ae9-841b-401b-8b61-f472004d1689) |
<a name="7eee6ae9-841b-401b-8b61-f472004d1689"></a>
### 9386-8801cea/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30672
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7239c6519874:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 40 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 43 seconds
{
  "name": "awscli",
  "duration": 1228,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
<a name="20d676b6-b334-4377-9be4-5fc563447a9e"></a>
### 9386-8801cea/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31410
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1e1ec4aa85d9:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 5 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... FAILED in 52 seconds
{
  "name": "awscli",
  "duration": 4675,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31410 s3api head-object --bucket awscli-mint-test-bucket-6773 --key datafile-1-kB-copy\n",
  "status": "FAIL",
  "error": "StorageClass was not applied"
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by Praveenrajmani — COMMENTED** [review]
Can we add a mint test on this @harshavardhana

**Review by Praveenrajmani — APPROVED** [review]
Tested and LGTM

**Comment by Praveenrajmani** [comment]
Can you fix the conflicts? @harshavardhana

**Comment by harshavardhana** [comment]
> Can you fix the conflicts? @harshavardhana

Conflicts fixed @Praveenrajmani

**Comment by Praveenrajmani** [comment]
PTAL @donatello

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#5b6e4fe3-09c0-4b4e-bc28-acc20f8039ee) |
| mint-gateway-nas.sh | :x: [more...](#5c8b1fc1-9c1a-47da-928f-07fdbd441218) |
<a name="5c8b1fc1-9c1a-47da-928f-07fdbd441218"></a>
### 9386-93bd736/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30412
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b0a45c7c3d01:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 9 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 37 seconds
(8/15) Running minio-dotnet tests ... done in 31 seconds
(9/15) Running minio-go tests ... FAILED in 23 seconds
{}

Executed 8 out of 15 tests successfully.
```
<a name="5b6e4fe3-09c0-4b4e-bc28-acc20f8039ee"></a>
### 9386-93bd736/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31152
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3ee10ca66d35:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 5 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... FAILED in 55 seconds
{
  "name": "awscli",
  "duration": 3663,
  "function": "aws --endpoint-url http://minio-dev3.minio.io:31152 s3api copy-object --bucket awscli-mint-test-bucket-11289 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-11289/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#2f6aac92-0e08-47a0-9936-ab122a4f0d7d) |
| mint-gateway-nas.sh | :x: [more...](#89ab9ea6-927a-4015-9f0f-a7e3d0f86f40) |
<a name="89ab9ea6-927a-4015-9f0f-a7e3d0f86f40"></a>
### 9386-7248176/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32713
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 623bf2b7862b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 35 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 20 seconds
{}

Executed 8 out of 15 tests successfully.
```
<a name="2f6aac92-0e08-47a0-9936-ab122a4f0d7d"></a>
### 9386-7248176/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32440
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 683c2c72d893:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... FAILED in 54 seconds
{
  "name": "awscli",
  "duration": 4267,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32440 s3api copy-object --bucket awscli-mint-test-bucket-24415 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-24415/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by donatello — APPROVED** [review]

**Comment by FreeG** [comment]
hello i might have found an issue with this fix:
when executing a head operation with a given part-number on a small zip file via aws cli like `aws --endpoint-url <endpoint> s3api head-object --bucket <bucket> --key <key> --part-number 1`
then i am getting a preCondition failed. When executing the very same command against aws s3 it doesn't fail and returns the meta data. It fails on pngs but it seems like it should be allowed for zip files.
The java aws sdk sets the part-number when geting meta data for zip files. So currently the download for zip files is broken in our software when using RELEASE.2020-04-23T00-58-49Z version of minio.

**Comment by harshavardhana** [comment]
> hello i might have found an issue with this fix:
> when executing a head operation with a given part-number on a small zip file via aws cli like `aws --endpoint-url <endpoint> s3api head-object --bucket <bucket> --key <key> --part-number 1`
> then i am getting a preCondition failed. When executing the very same command against aws s3 it doesn't fail and returns the meta data. It fails on pngs but it seems like it should be allowed for zip files.
> The java aws sdk sets the part-number when geting meta data for zip files. So currently the download for zip files is broken in our software when using RELEASE.2020-04-23T00-58-49Z version of minio.

Did you upload object as multipart @FreeG ?

**Comment by FreeG** [comment]
@harshavardhana ok i double checked. It seems like the file type doesn't change the behaviour. As far as i can tell we are not using AWS S3 Multipart. But you can reproduce this issue when uploading files via cloudberry to s3 and minIO. Amazon accepts head-object requests with and without --part-number. And it seems like some libraries depend on that. It would be great if the behaviour could be changed so it is more consistent with amazon s3.

**Comment by harshavardhana** [comment]
> @harshavardhana ok i double checked. It seems like the file type doesn't change the behaviour. As far as i can tell we are not using AWS S3 Multipart. But you can reproduce this issue when uploading files via cloudberry to s3 and minIO. Amazon accepts head-object requests with and without --part-number. And it seems like some libraries depend on that. It would be great if the behaviour could be changed so it is more consistent with amazon s3.

Issue is not that @FreeG I was asking how were the files uploaded because that dictates if partNumber works or not.

**Comment by FreeG** [comment]
@harshavardhana the file wasn't uploaded as multipart.

**Comment by FreeG** [comment]
@harshavardhana Since Amazon accepts head object requests with part-number=1 even when files were not uploaded as multipart. Is there any chance that this behaviour is adapted in minIO?

**Pull request merged**
