### PR TITLE
ignore configNotFound error in AccountInfo()

### LINKED ISSUE #14081: Error: config file not found
## Expected Behavior

When I start minio in erasure coding mode, there should be no errors

## Current Behavior

An error is as follows, but it doesn't seem to have any effect.
截屏2022-01-11 上午11 16 43

## Possible Solution

Maybe there is no ".usage.json" file before the bucket is created

## Steps to Reproduce (for bugs)

1. Start minio with 4 drives 
2. Log in console
3. Create a bucket
4. Now you can see the error
## Regression

maybe

## Your Environment

* Version used (`minio --version`):latest
* Server setup and configuration:server /Volumes/data{1...4} --console-address :9001
* Operating System and version (`uname -a`):Darwin MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
ignore configNotFound error in AccountInfo()

## Motivation and Context
fixes #14081

## How to test this PR?
Just a fresh setup and login to Console UI

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by klauspost — CHANGES_REQUESTED** [review]
Put it here instead:

https://github.com/minio/minio/blob/001b77e7e1f0ee1eb6c8a0f696ee2d71b6036b20/cmd/data-usage.go#L93

**Review by klauspost — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Pull request merged**
