### PR TITLE
Change query param name to duration in list/clear locks API

### PR DESCRIPTION
**Pull request by krisis**
Following is a sample list lock API request schematic,

  /?lock&bucket=mybucket&prefix=myprefix&duration=holdDuration
  x-minio-operation: list

The response would contain the list of locks held on mybucket matching
myprefix for a duration longer than holdDuration.

## Description

This change is to make the query params intention clear to lock management API consumers.
Previously, ``older-than`` query parameter was used to include locks that were held a duration of ``older-than`` units from current time. With this change, we rename the query parameter to ``duration`` to indicate that list/clear locks API will include locks held for a duration longer than the value specified using the ``duration`` query parameter.

## Motivation and Context

This change intends to simplify the lock management APIs.

## How Has This Been Tested?

unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Can you rebase this patch @krisis ?

**Comment by harshavardhana** [comment]
// cc @vadmeste mc needs to be updated as well

**Comment by vadmeste** [comment]
> // cc @vadmeste mc needs to be updated as well

Shall I also modify the flag --older-than to --duration in mc ?

**Comment by harshavardhana** [comment]
> Shall I also modify the flag --older-than to --duration in mc ?

I think so @vadmeste

**Pull request merged**
