### PR TITLE
Fix: Policy action name for Get/Put BucketLifeCycle

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
S3:GetBucketLifeCycle should be changed to S3:GetLifeCycleConfiguration
S3:PutBucketLifeCycle should be changed to S3:PutLifeCycleConfiguration

## Motivation and Context
Policy provided in https://github.com/minio/minio-java/issues/831 does not work in MinIO.
The policy action name for Get/Put Bucket LifeCycle is wrong in MinIO

https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLifecycle.html
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycle.html

## How to test this PR?
Setting Bucket policy 
```
{
  "Version": "2012-10-17",
  "Statement": [
       {
          "Action": [
              "s3:PutObject",
              "s3:DeleteObject",
              "s3:GetObject"
          ],
          "Effect": "Allow",
          "Principal": {
              "AWS": [
                  "*"
              ]
          },
          "Resource": [
              "arn:aws:s3:::bucket/*"
          ]
      },
      {
          "Action": [
              "s3:DeleteBucket",
              "s3:ListBucket",
              "s3:GetBucketPolicy",
              "s3:PutBucketPolicy",
              "s3:GetLifecycleConfiguration",
              "s3:PutLifecycleConfiguration"
          ],
          "Effect": "Allow",
          "Principal": {
              "AWS": [
                  "*"
              ]
          },
          "Resource": [
              "arn:aws:s3:::bucket"
          ]
      }
  ]
}
```
works in AWS S3, but fails in MinIO
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#dff0fece-b3a8-4891-8da5-a9724253bdfb) |
| mint-large-bucket.sh | :x: [more...](#d1593a14-32b2-4c4e-ae09-bd8342212be9) |
| mint-gateway-nas.sh | :x: [more...](#67f060da-2bcf-4596-a244-250a7e76e5d1) |
<a name="d1593a14-32b2-4c4e-ae09-bd8342212be9"></a>
### 8698-6426bb5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30669
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bd56cb529607:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 6 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 1 minutes and 7 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 28 seconds
{
  "args": {},
  "duration": 85496,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="67f060da-2bcf-4596-a244-250a7e76e5d1"></a>
### 8698-6426bb5/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30542
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5e14a9d9ec15:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{
  "name": "awscli",
  "duration": 309642,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=30542): Max retries exceeded with url: /awscli-mint-test-bucket-10815 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f20b4695748>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="dff0fece-b3a8-4891-8da5-a9724253bdfb"></a>
### 8698-6426bb5/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31097
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4181810f9b72:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 13 seconds
{
  "name": "awscli",
  "duration": 311411,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=31097): Max retries exceeded with url: /awscli-mint-test-bucket-13378 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7ff18fef7160>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a1dbf9cf-b072-4130-bf2c-749e08e1cdf4) |
| mint-compression-fs.sh | :x: [more...](#75a4a509-ed98-4ea2-81a9-84f5e1979a2b) |
| mint-fs.sh | :x: [more...](#fd7c60f2-d98b-451e-894b-9f09c7444672) |
<a name="75a4a509-ed98-4ea2-81a9-84f5e1979a2b"></a>
### 8698-5f570c6/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30746
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4e74391f672f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{
  "name": "awscli",
  "duration": 306705,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=30746): Max retries exceeded with url: /awscli-mint-test-bucket-27368 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7fe432c17048>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="a1dbf9cf-b072-4130-bf2c-749e08e1cdf4"></a>
### 8698-5f570c6/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32029
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 382da4f13232:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 13 seconds
{
  "name": "awscli",
  "duration": 310859,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=32029): Max retries exceeded with url: /awscli-mint-test-bucket-32142 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f3efb4ed0b8>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="fd7c60f2-d98b-451e-894b-9f09c7444672"></a>
### 8698-5f570c6/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30575
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a44a91ac6661:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{
  "name": "awscli",
  "duration": 307057,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "HTTPConnectionPool(host='72.28.97.55', port=30575): Max retries exceeded with url: /awscli-mint-test-bucket-1447 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7feced0500b8>, 'Connection to 72.28.97.55 timed out. (connect timeout=60)'))"
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by vadmeste** [comment]
Simple CI is failing here @kannappanr

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#95c62853-2783-473e-8bc9-7c78d56a579f) |
| mint-xl.sh | :x: [more...](#295c691c-b8bf-499a-958e-cf2ca4b49e3a) |
| mint-large-bucket.sh | :x: [more...](#d2f3e771-3a7b-46c0-a2aa-9072352c2b38) |
| mint-compression-dist-xl.sh | :x: [more...](#e44f3f74-241a-434e-bfd8-8eca1882110e) |
| mint-compression-fs.sh | :x: [more...](#3f707687-14ef-4e0c-997e-b69d23b7b5f1) |
| mint-fs.sh | :x: [more...](#380db545-2b9b-46c1-9035-f4c95e45ab28) |
| mint-dist-xl.sh | :x: [more...](#a6b9b4f1-30b2-44e0-9e0b-9b06c8a62960) |
| mint-gateway-nas.sh | :x: [more...](#adc96c78-75af-478f-9fc8-195885f4dce4) |
<a name="e44f3f74-241a-434e-bfd8-8eca1882110e"></a>
### 8698-6ca1ac3/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30213
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 157763ee5610:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 24 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 3 seconds
(4/13) Running mc tests ... done in 25 seconds
(5/13) Running minio-go tests ... done in 1 minutes and 27 seconds
(6/13) Running minio-js tests ... FAILED in 6 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 12,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="adc96c78-75af-478f-9fc8-195885f4dce4"></a>
### 8698-6ca1ac3/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30252
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5f3eab0fd0da:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 5 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 3 seconds
(4/13) Running mc tests ... done in 46 seconds
(5/13) Running minio-go tests ... done in 1 minutes and 3 seconds
(6/13) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 9,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="a6b9b4f1-30b2-44e0-9e0b-9b06c8a62960"></a>
### 8698-6ca1ac3/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31299
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a9b06f19e080:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 15 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 1 minutes and 8 seconds
(5/13) Running minio-go tests ... done in 1 minutes and 12 seconds
(6/13) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="d2f3e771-3a7b-46c0-a2aa-9072352c2b38"></a>
### 8698-6ca1ac3/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30263
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 967ef641d93e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 1 minutes and 20 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 23 seconds
{
  "args": {},
  "duration": 95240,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="95c62853-2783-473e-8bc9-7c78d56a579f"></a>
### 8698-6ca1ac3/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32463
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 902337feb497:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 5 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 2 seconds
(4/13) Running mc tests ... done in 48 seconds
(5/13) Running minio-go tests ... done in 57 seconds
(6/13) Running minio-js tests ... FAILED in 5 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="3f707687-14ef-4e0c-997e-b69d23b7b5f1"></a>
### 8698-6ca1ac3/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30200
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 31f25ea570c0:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 3 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 2 seconds
(4/13) Running mc tests ... done in 41 seconds
(5/13) Running minio-go tests ... done in 58 seconds
(6/13) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="295c691c-b8bf-499a-958e-cf2ca4b49e3a"></a>
### 8698-6ca1ac3/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30531
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e2d76c45a63c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 6 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 2 seconds
(4/13) Running mc tests ... done in 1 minutes and 1 seconds
(5/13) Running minio-go tests ... done in 1 minutes and 0 seconds
(6/13) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 4,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 5 out of 13 tests successfully.
```
<a name="380db545-2b9b-46c1-9035-f4c95e45ab28"></a>
### 8698-6ca1ac3/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30614
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 091c8957548b:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 309721, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30614/awscli-mint-test-bucket-31290""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#64c5109d-c69f-473f-8be3-ca35349c60a6) |
| mint-large-bucket.sh | :x: [more...](#f3a6cf09-db42-4fc1-9e7c-95eb5b777250) |
<a name="64c5109d-c69f-473f-8be3-ca35349c60a6"></a>
### 8698-a860cf6/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30595
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0c940a27c664:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 306055, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30595/awscli-mint-test-bucket-27301""}

Executed 0 out of 13 tests successfully.
```
<a name="f3a6cf09-db42-4fc1-9e7c-95eb5b777250"></a>
### 8698-a860cf6/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31379
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8fe0ab4273f6:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 32 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 46 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 55 seconds
{
  "args": {},
  "duration": 82812,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
