### PR TITLE
[proposal] Add extended header for checksum verification

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add extended header for checksum verification

## Motivation and Context
This PR brings a special header `x-minio-object-hash`
which specifically captures the object-hash of the
entire object - set by the client for server validation.

The once set server validates the object in its entirety

- PutObject supports this header if set, object hash
  is validated as the stream is being written to the backend.
- CompleteMultipartUpload supports this header if set,
  re-reads and verifies the combined object on the backend.

Additionally, this header is also saved along with other
metadata values in the backend.

## Regression
No

## How Has This Been Tested?
Using the following Java program, follow up cookbook to get started with aws-sdk-java https://docs.minio.io/docs/how-to-use-aws-sdk-for-java-with-minio-server.html
```java
import java.io.BufferedReader;
import java.io.File;
import java.util.Map;
import java.lang.Object;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.ClientConfiguration;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.GetObjectRequest;
import com.amazonaws.services.s3.model.PutObjectRequest;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.S3Object;

public class S3Sample {
    private static String bucketName = "testbucket";
    private static String keyName = "hosts";
    private static String uploadFileName = "/etc/issue";

    public static void main(String[] args) throws IOException {
        AWSCredentials credentials = new BasicAWSCredentials("minio", "minio123");
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");

        AmazonS3 s3Client = AmazonS3ClientBuilder
                .standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:9000", Regions.US_EAST_1.name()))
                .withPathStyleAccessEnabled(true)
                .withClientConfiguration(clientConfiguration)
                .withCredentials(new AWSStaticCredentialsProvider(credentials))
                .build();

        try {
            System.out.println("Uploading a new object to S3 from a file\n");
            // Upload file
            PutObjectRequest request = new PutObjectRequest(bucketName, keyName, new File(uploadFileName));
            ObjectMetadata metadata = new ObjectMetadata();
            metadata.setHeader("x-minio-object-hash", "sha256:8ba8085ad1bb937158eb6db5de263219ff69a7ca87637425e85f3fcf683cd1a3");
            request.setMetadata(metadata);
            s3Client.putObject(request);
            
            // Download file
            GetObjectRequest rangeObjectRequest = new GetObjectRequest(bucketName, keyName);
            S3Object objectPortion = s3Client.getObject(rangeObjectRequest);
            metadata = objectPortion.getObjectMetadata();
            Map<String, Object> m = metadata.getRawMetadata();
            if (!(m.get("x-minio-object-hash").equals("sha256:8ba8085ad1bb937158eb6db5de263219ff69a7ca87637425e85f3fcf683cd1a3"))) {
                System.out.println("Error uploading object");
            }
        } catch(AmazonServiceException e) {
            // The call was transmitted successfully, but Amazon S3 couldn't process 
            // it, so it returned an error response.
            e.printStackTrace();
        }  
    }
}
```  

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#56ad1b79-ad82-418b-8944-feb3ecdbfcef) |
<a name="56ad1b79-ad82-418b-8944-feb3ecdbfcef"></a>
### 6687-ecda05f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30271
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dcd7042188a7:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... FAILED in 3 minutes and 12 seconds
{
  "name": "awscli",
  "duration": 160865,
  "function": "aws --endpoint-url http://minikube:30271 s3 rb s3://awscli-mint-test-bucket-17487/\n",
  "status": "FAIL",
  "error": "remove_bucket failed: s3://awscli-mint-test-bucket-17487/ An error occurred (NoSuchBucket) when calling the DeleteBucket operation: The specified bucket does not exist"
}

Executed 0 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 6687-59c92cc/gopath/src/github.com/minio
+ git clone --quiet https://github.com/minio/minio.git 6687-59c92cc/gopath/src/github.com/minio/minio
++ cd 6687-59c92cc/gopath/src/github.com/minio/minio
++ git remote add minio https://github.com/minio/minio.git
++ cd 6687-59c92cc/gopath/src/github.com/minio/minio
++ git fetch --quiet minio pull/6687/head:pr6687
++ cd 6687-59c92cc/gopath/src/github.com/minio/minio
++ git checkout --quiet pr6687
++ minikube ip
+ minikube_ip=192.168.39.64
++ mkdir -p certs
++ cd certs
++ ./cert -host 192.168.39.64
2018/10/24 13:10:58 wrote public.crt
2018/10/24 13:10:58 wrote private.key
+ GOPATH=/mnt/nvme0n1p1/mint-auto/mint-auto/6687-59c92cc/gopath
+ make -C 6687-59c92cc/gopath/src/github.com/minio/minio --quiet
pkg/hash/algo.go:9:2: cannot find package "golang.org/x/crypto/sha3" in any of:
	/mnt/nvme0n1p1/mint-auto/mint-auto/6687-59c92cc/gopath/src/github.com/minio/minio/vendor/golang.org/x/crypto/sha3 (vendor tree)
	/mnt/nvme0n1p1/mint-auto/.gimme/versions/go1.10.4.linux.amd64/src/golang.org/x/crypto/sha3 (from $GOROOT)
	/mnt/nvme0n1p1/mint-auto/mint-auto/6687-59c92cc/gopath/src/golang.org/x/crypto/sha3 (from $GOPATH)
make: *** [build] Error 1

```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#cb5c924a-ac90-4c97-a1b0-6e16e1ced22f) |
<a name="cb5c924a-ac90-4c97-a1b0-6e16e1ced22f"></a>
### 6687-ffed467/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30016
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5c6a4c953f84:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 9741,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Closing this PR since this is not going to be used as there is a newer proposal.

**Pull request closed without merging**
