### PR TITLE
return underlying error with BackendDown{} error

### PR DESCRIPTION
**Pull request by jiuker**
## Description

Make error messages richer.
It looks like it can make the error reporting information richer.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by jiuker** [comment]
Close it if on purpose.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :x: [more...](#192ada6b-e00a-4bd6-9251-979cee5aa3d1) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#a643b9a2-ea2e-4946-a7b9-4a2bf14c24d0) |
| mint-pools.sh | :x: [more...](#eaf7d8bf-6113-4926-8cfd-72af1d17cf7d) |
<a name="192ada6b-e00a-4bd6-9251-979cee5aa3d1"></a>
### 16738-3066b9b/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:30790
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp fd83ef21f222:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 22 seconds
{
  "name": "mc",
  "duration": "11031",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-29834 --quiet --no-color rb --force myminio/mc-test-bucket-16274  >>> \nmc: <ERROR> Unable to validate target `myminio/mc-test-bucket-16274`. Get \"http://15.15.15.6:30790/mc-test-bucket-16274/?location=\": dial tcp 15.15.15.6:30790: i/o timeout"
}
(7/14) Running minio-go tests ... done in 1 minutes and 10 seconds
(8/14) Running minio-java tests ... done in 18 seconds
(9/14) Running minio-js tests ... done in 46 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 29 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 26 seconds

Executed 13 out of 14 tests successfully.
```
<a name="a643b9a2-ea2e-4946-a7b9-4a2bf14c24d0"></a>
### 16738-3066b9b/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:30073
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 156ba39504f5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 9 seconds
(5/14) Running awscli tests ... done in 1 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 50 seconds
{
  "name": "mc",
  "duration": "40158",
  "function": "test_presigned_get_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-10459 --quiet --no-color cp /mint/data/datafile-1-MB myminio/mc-test-bucket-20306/mc-test-object-30520  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-20306/mc-test-object-30520`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Get \"http://15.15.15.7:30073/mc-test-bucket-20306/?location=\": dial tcp 15.15.15.7:30073: i/o timeout\nTotal: 0 B, Transferred: 0 B, Speed: 0 B/s"
}
(7/14) Running minio-go tests ... done in 55 seconds
(8/14) Running minio-java tests ... done in 31 seconds
(9/14) Running minio-js tests ... done in 52 seconds
(10/14) Running minio-py tests ... done in 7 minutes and 7 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 13 out of 14 tests successfully.
```
<a name="eaf7d8bf-6113-4926-8cfd-72af1d17cf7d"></a>
### 16738-3066b9b/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:30321
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 092f719f9d16:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 10 seconds
(5/14) Running awscli tests ... done in 1 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 48 seconds
{
  "name": "mc",
  "duration": "41761",
  "function": "test_mv_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-8448 --quiet --no-color mv /tmp/tmp.QobmXxzPPd/file myminio/mc-test-bucket-18083/dir-32516-31373/object-1  >>> \n`/tmp/tmp.QobmXxzPPd/file` -> `myminio/mc-test-bucket-18083/dir-32516-31373/object-1`\nmc: <ERROR> Failed to copy `/tmp/tmp.QobmXxzPPd/file`. Get \"http://15.15.15.1:30321/mc-test-bucket-18083/?location=\": dial tcp 15.15.15.1:30321: i/o timeout\nTotal: 0 B, Transferred: 0 B, Speed: 0 B/s"
}
(7/14) Running minio-go tests ... done in 1 minutes and 5 seconds
(8/14) Running minio-java tests ... done in 39 seconds
(9/14) Running minio-js tests ... done in 51 seconds
(10/14) Running minio-py tests ... done in 4 minutes and 13 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 33 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Please fix Go code format.

**Comment by jiuker** [comment]
@harshavardhana review again,plz.Which tool should used for minio code? `go fmt` or `goimport` can't format like the code.I use `goimport` after I move the package down,it seems good.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by klauspost** [comment]
@jiuker `goimport` should arrange stdlib/other separately.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Pull request merged**
