### PR TITLE
Remove erasureSets and erasureObjects from ObjectLayer

### PR DESCRIPTION
**Pull request by klauspost**
## Motivation and Context

erasureSets and erasureObjects are not meant to be used as standalone ObjectLayer.

Remove the stubs that are just there to satisfy the interface and implement shallower interfaces for specific functionality.

This will make the implemented vs. non implemented clear.

Fixes some test cleanups as well.

## How to test this PR?

Should be handled with tests.

## Types of changes
- [x] Cleanup

### CODE REVIEW

**Comment by klauspost** [comment]
Weird. Tests run OOM on my computer. Seems like there is some magic somewhere.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#838558df-bfc7-4210-9a56-fb719aa8191c) |
<a name="838558df-bfc7-4210-9a56-fb719aa8191c"></a>
### 10442-9e12394/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32748
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 190e23efd95f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 44 seconds
{
  "name": "awscli",
  "duration": 3951,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:32748 s3api copy-object --bucket awscli-mint-test-bucket-31798 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-31798/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D854E81DD5FFC7-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 6 minutes and 11 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(8/15) Running minio-go tests ... done in 6 minutes and 56 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 37 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 28 seconds
(11/15) Running minio-py tests ... done in 13 minutes and 25 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 31 seconds
(13/15) Running s3select tests ... done in 1 minutes and 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10442-9e12394

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
> Weird. Tests run OOM on my computer. Seems like there is some magic somewhere.

Is this still happening?

**Comment by klauspost** [comment]
@harshavardhana No. Still a bit unsure what caused it, but cleaning up more seemed to fix it.

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
