### PR TITLE
Update dockerfile go version to 1.9.2

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Update dockerfile go version to 1.9.2

## Motivation and Context
Update dockerfile go version to 1.9.2

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]

**Review by nitisht — APPROVED** [review]

**Comment by J0WI** [comment]
There is already `1.9.3`. Is there a strong reason against using `1.9-alpine3.6` or `1.9-alpine`?

**Comment by harshavardhana** [comment]
> There is already 1.9.3. Is there a strong reason against using 1.9-alpine3.6 or 1.9-alpine?

To avoid bugs that may come up unknowingly @J0WI we would like to stick to a version for a while.

**Comment by J0WI** [comment]
I would expect that Go/Minio are always compatible within a minor releases. If not, automated tests/CI are likely to catch breaking changes.

**Comment by harshavardhana** [comment]
> I would expect that Go/Minio are always compatible within a minor releases. If not, automated tests/CI are likely to catch breaking changes.

Not necessarily, that is not enough @J0WI

**Pull request merged**
