### PR TITLE
Show minio version when building from source file

### PR DESCRIPTION
**Pull request by ruspaul013**
## Description
Showing minio version when building from source file.

## Motivation and Context
If minio is build form tar.gz file, when running `minio --version` will show
```
minio version DEVELOPMENT.GOGET (commit-id=DEVELOPMENT.GOGET)
Runtime: go1.23.0 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-0000 MinIO, Inc.
```
With this commit, minio will show now
```
minio version CUSTOM.2024-08-17T01-24-54Z (commit-id=DEVELOPMENT.GOGET)
Runtime: go1.23.0 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```

## How to test this PR?
Download the tar.gz file, unzip the file and then run `make`, after that run `./minio --version`.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — CHANGES_REQUESTED** [review]
I know this is well intentioned, but we don't want non-official builds to show as releases.

**Comment by ruspaul013** [comment]
@klauspost Thanks for the reply. 
Instead of RELEASE, can be something else like CUSTOM? I know that `MINIO_RELEASE` env will give that value.

**Comment by klauspost** [comment]
`CUSTOM` would work for me.

**Comment by harshavardhana** [comment]
This is beyond the scope of this project, please install via `go install -v github.com/minio/minio@latest` for source compilation. 

keep this change in your fork if needed.

**Comment by ruspaul013** [comment]
Hello @harshavardhana! 
Thank you for the reply! I understand that this is beyond the scope of the project, but I was thinking that this would help other people that make custom builds for minio, so that they can use `MINIO_VERSION` to add the version and not to see `DEVELOPMENT`.

**Comment by harshavardhana** [comment]
> Thank you for the reply! I understand that this is beyond the scope of the project, but I was thinking that this would help other people that make custom builds for minio, so that they can use `MINIO_VERSION` to add the version and not to see `DEVELOPMENT`.

If you are planning to ship your own binaries of minio you can pass in the flags directly via `go build --ldflags` this approach is not needed. We are never going to use MINIO_VERSION so its not needed in our repo.

**Pull request closed without merging**
