### PR TITLE
Fix RPC client data race

### LINKED ISSUE #8811: Race in RPC client error storage
```
==================
WARNING: DATA RACE
Write at 0x00c00039e4e0 by goroutine 321:
  github.com/minio/minio/cmd.(*storageRESTClient).call()
      d:/minio/minio/cmd/storage-rest-client.go:133 +0x22f
  github.com/minio/minio/cmd.(*storageRESTClient).ReadAll()
      d:/minio/minio/cmd/storage-rest-client.go:298 +0x29c
  github.com/minio/minio/cmd.readXLMeta()
      d:/minio/minio/cmd/xl-v1-utils.go:166 +0x103
  github.com/minio/minio/cmd.readAllXLMetadata.func1()
      d:/minio/minio/cmd/xl-v1-utils.go:193 +0x1e6
  github.com/minio/minio/pkg/sync/errgroup.(*Group).Go.func1()
      d:/minio/minio/pkg/sync/errgroup/errgroup.go:55 +0x78

Previous write at 0x00c00039e4e0 by goroutine 141:
  github.com/minio/minio/cmd.(*storageRESTClient).call()
      d:/minio/minio/cmd/storage-rest-client.go:133 +0x22f
  github.com/minio/minio/cmd.(*storageRESTClient).ReadAll()
      d:/minio/minio/cmd/storage-rest-client.go:298 +0x29c
  github.com/minio/minio/cmd.readXLMeta()
      d:/minio/minio/cmd/xl-v1-utils.go:166 +0x103
  github.com/minio/minio/cmd.readAllXLMetadata.func1()
      d:/minio/minio/cmd/xl-v1-utils.go:193 +0x1e6
  github.com/minio/minio/pkg/sync/errgroup.(*Group).Go.func1()
      d:/minio/minio/pkg/sync/errgroup/errgroup.go:55 +0x78

Goroutine 321 (running) created at:
  github.com/minio/minio/pkg/sync/errgroup.(*Group).Go()
      d:/minio/minio/pkg/sync/errgroup/errgroup.go:52 +0x80
  github.com/minio/minio/cmd.readAllXLMetadata()
      d:/minio/minio/cmd/xl-v1-utils.go:189 +0x14d
  github.com/minio/minio/cmd.xlObjects.getObjectInfo()
      d:/minio/minio/cmd/xl-v1-object.go:368 +0xf3
  github.com/minio/minio/cmd.xlObjects.GetObjectInfo()
      d:/minio/minio/cmd/xl-v1-object.go:355 +0x374
  github.com/minio/minio/cmd.(*xlSets).GetObjectInfo()
      d:/minio/minio/cmd/xl-sets.go:670 +0x19b
  github.com/minio/minio/cmd.(*xlZones).GetObjectInfo()
      d:/minio/minio/cmd/xl-zones.go:379 +0x2fa
  github.com/minio/minio/cmd.ObjectLayer.GetObjectInfo-fm()
      d:/minio/minio/cmd/object-api-interface.go:79 +0x11e
  github.com/minio/minio/cmd.checkPutObjectRetentionAllowed()
      d:/minio/minio/cmd/object-lock.go:538 +0x21e
  github.com/minio/minio/cmd.objectAPIHandlers.PutObjectHandler()
      d:/minio/minio/cmd/object-handlers.go:1254 +0x1dcf
  github.com/minio/minio/cmd.objectAPIHandlers.PutObjectHandler-fm()
      d:/minio/minio/cmd/object-handlers.go:1068 +0x81
  github.com/minio/minio/cmd.httpTraceHdrs.func1()
      c:/go/src/net/http/server.go:2007 +0x204
  github.com/minio/minio/cmd.collectAPIStats.func1()
      c:/go/src/net/http/server.go:2007 +0x230
  net/http.HandlerFunc.ServeHTTP()
      c:/go/src/net/http/server.go:2007 +0x58
  github.com/gorilla/mux.(*Router).ServeHTTP()
      e:/gopath/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0x145
  github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:748 +0x19f
  github.com/minio/minio/cmd.(*customHeaderHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:763 +0x250
  github.com/minio/minio/cmd.(*securityHeaderHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:624 +0x1abd
  github.com/minio/minio/cmd.(*bucketForwardingHandler).ServeHTTP()
      <autogenerated>:1 +0xa4
  github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:608 +0xb0e
  github.com/minio/minio/cmd.(*requestValidityHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:544 +0x1ee
  github.com/minio/minio/cmd.(*httpStatsHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:68 +0x18e
  github.com/minio/minio/cmd.(*requestSizeLimitHandler).ServeHTTP()
      <autogenerated>:1 +0xa4
  github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:93 +0x394
  github.com/minio/minio/cmd.(*requestHeaderSizeLimitHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP()
      d:/minio/minio/cmd/crossdomain-xml-handler.go:51 +0xc7
  github.com/minio/minio/cmd.(*crossDomainPolicy).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.redirectHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:247 +0x7c
  github.com/minio/minio/cmd.(*redirectHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:315 +0x99
  github.com/minio/minio/cmd.(*minioReservedBucketHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:274 +0xae
  github.com/minio/minio/cmd.(*cacheControlHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:385 +0x44c
  github.com/minio/minio/cmd.(*timeValidityHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/rs/cors.(*Cors).Handler.func1()
      e:/gopath/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 +0x23d
  net/http.HandlerFunc.ServeHTTP()
      c:/go/src/net/http/server.go:2007 +0x58
  github.com/minio/minio/cmd.resourceHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:524 +0xbf
  github.com/minio/minio/cmd.(*resourceHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.authHandler.ServeHTTP()
      d:/minio/minio/cmd/auth-handler.go:472 +0x4d7
  github.com/minio/minio/cmd.(*authHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:798 +0x6ef
  github.com/minio/minio/cmd.(*sseTLSHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:136 +0x394
  github.com/minio/minio/cmd.(*reservedMetadataHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:780 +0xc0
  github.com/minio/minio/cmd.(*criticalErrorHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd/http.(*Server).Start.func1()
      d:/minio/minio/cmd/http/server.go:100 +0x166
  net/http.HandlerFunc.ServeHTTP()
      c:/go/src/net/http/server.go:2007 +0x58
  net/http.serverHandler.ServeHTTP()
      c:/go/src/net/http/server.go:2802 +0xd5
  net/http.(*conn).serve()
      c:/go/src/net/http/server.go:1890 +0x83e

Goroutine 141 (finished) created at:
  github.com/minio/minio/pkg/sync/errgroup.(*Group).Go()
      d:/minio/minio/pkg/sync/errgroup/errgroup.go:52 +0x80
  github.com/minio/minio/cmd.readAllXLMetadata()
      d:/minio/minio/cmd/xl-v1-utils.go:189 +0x14d
  github.com/minio/minio/cmd.xlObjects.getObjectInfo()
      d:/minio/minio/cmd/xl-v1-object.go:368 +0xf3
  github.com/minio/minio/cmd.xlObjects.GetObjectInfo()
      d:/minio/minio/cmd/xl-v1-object.go:355 +0x374
  github.com/minio/minio/cmd.(*xlSets).GetObjectInfo()
      d:/minio/minio/cmd/xl-sets.go:670 +0x19b
  github.com/minio/minio/cmd.(*xlZones).GetObjectInfo()
      d:/minio/minio/cmd/xl-zones.go:379 +0x2fa
  github.com/minio/minio/cmd.ObjectLayer.GetObjectInfo-fm()
      d:/minio/minio/cmd/object-api-interface.go:79 +0x11e
  github.com/minio/minio/cmd.checkPutObjectRetentionAllowed()
      d:/minio/minio/cmd/object-lock.go:538 +0x21e
  github.com/minio/minio/cmd.objectAPIHandlers.PutObjectHandler()
      d:/minio/minio/cmd/object-handlers.go:1254 +0x1dcf
  github.com/minio/minio/cmd.objectAPIHandlers.PutObjectHandler-fm()
      d:/minio/minio/cmd/object-handlers.go:1068 +0x81
  github.com/minio/minio/cmd.httpTraceHdrs.func1()
      c:/go/src/net/http/server.go:2007 +0x204
  github.com/minio/minio/cmd.collectAPIStats.func1()
      c:/go/src/net/http/server.go:2007 +0x230
  net/http.HandlerFunc.ServeHTTP()
      c:/go/src/net/http/server.go:2007 +0x58
  github.com/gorilla/mux.(*Router).ServeHTTP()
      e:/gopath/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0x145
  github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:748 +0x19f
  github.com/minio/minio/cmd.(*customHeaderHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:763 +0x250
  github.com/minio/minio/cmd.(*securityHeaderHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:624 +0x1abd
  github.com/minio/minio/cmd.(*bucketForwardingHandler).ServeHTTP()
      <autogenerated>:1 +0xa4
  github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:608 +0xb0e
  github.com/minio/minio/cmd.(*requestValidityHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:544 +0x1ee
  github.com/minio/minio/cmd.(*httpStatsHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:68 +0x18e
  github.com/minio/minio/cmd.(*requestSizeLimitHandler).ServeHTTP()
      <autogenerated>:1 +0xa4
  github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:93 +0x394
  github.com/minio/minio/cmd.(*requestHeaderSizeLimitHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP()
      d:/minio/minio/cmd/crossdomain-xml-handler.go:51 +0xc7
  github.com/minio/minio/cmd.(*crossDomainPolicy).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.redirectHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:247 +0x7c
  github.com/minio/minio/cmd.(*redirectHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:315 +0x99
  github.com/minio/minio/cmd.(*minioReservedBucketHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:274 +0xae
  github.com/minio/minio/cmd.(*cacheControlHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:385 +0x44c
  github.com/minio/minio/cmd.(*timeValidityHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/rs/cors.(*Cors).Handler.func1()
      e:/gopath/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 +0x23d
  net/http.HandlerFunc.ServeHTTP()
      c:/go/src/net/http/server.go:2007 +0x58
  github.com/minio/minio/cmd.resourceHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:524 +0xbf
  github.com/minio/minio/cmd.(*resourceHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.authHandler.ServeHTTP()
      d:/minio/minio/cmd/auth-handler.go:472 +0x4d7
  github.com/minio/minio/cmd.(*authHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:798 +0x6ef
  github.com/minio/minio/cmd.(*sseTLSHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:136 +0x394
  github.com/minio/minio/cmd.(*reservedMetadataHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:780 +0xc0
  github.com/minio/minio/cmd.(*criticalErrorHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd/http.(*Server).Start.func1()
      d:/minio/minio/cmd/http/server.go:100 +0x166
  net/http.HandlerFunc.ServeHTTP()
      c:/go/src/net/http/server.go:2007 +0x58
  net/http.serverHandler.ServeHTTP()
      c:/go/src/net/http/server.go:2802 +0xd5
  net/http.(*conn).serve()
      c:/go/src/net/http/server.go:1890 +0x83e
==================
[more....]
````

## Expected Behavior

There should not be a data race.

## Current Behavior

Data race here: https://github.com/minio/minio/blob/37b32199e3ee76f43b0c71e2046fb0ef58cfebc6/cmd/storage-rest-client.go#L133

## Possible Solution

Add a simple mutex. This is done extremely fast so it shouldn't affect anything.

## Steps to Reproduce (for bugs)

1. Build minio with `-race`
2. Run minio in distributed mode.
3. Put load on the server.

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Fixes #8811

See ticket...

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#73f974c3-4f88-4785-bac8-db5abcffe955) |
<a name="73f974c3-4f88-4785-bac8-db5abcffe955"></a>
### 8812-073920b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30543
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8579ce68816f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 19 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 54 seconds
(5/13) Running minio-go tests ... FAILED in 2 minutes and 44 seconds
{
  "args": {},
  "duration": 62571,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — CHANGES_REQUESTED** [review]
As discussed the PR itself fixes this issue but we should move away from LastError() implementation

**Comment by vadmeste** [comment]
> As discussed the PR itself fixes this issue but we should move away from LastError() implementation

LastError() is needed so we can log disk errors but still we can revisit it

**Comment by harshavardhana** [comment]
> LastError() is needed so we can log disk errors but still we can revisit it

We need to remove that instead of introducing mutexes @vadmeste

**Comment by harshavardhana** [comment]
Feel free to close this @klauspost as this is addressed properly in #8817

**Pull request closed without merging**
