### PR TITLE
Feature - Making the Health-check script value configurable. 

### PR DESCRIPTION
**Pull request by jdelamar**
## Description
In some of our deployment, the hardcoded 120 second wait time on the healthcheck script is not sufficient and triggers minio cluster outage.

## Motivation and Context
In our precise case today starting 2 out of our 4 minio servers took about 3 minutes. However, the 2 healthy containers would be killed after 120 seconds, which would cause the two "slower" containers to fail and restart, forever...

This changes propose extending that delay by default, and making it configurable. On startup, there is no reason to rush killing a starting server that is waiting for the cluster to stabilize. The former 120 second wait time was arbitrary. The proposed 500 second is just as arbitrary, but gives more chance for clusters to stabilize.

You can now use the STARTUP_GRACE_PERIOD_SEC env variable when starting this docker to set the time (in second) to wait before starting to perform actual healthcheck on a local minio server. This will cause docker to wait for at least STARTUP_GRACE_PERIOD_SEC before determining if a minio server is unhealthy.

## Regression

No regression

## How Has This Been Tested?
Shell script changes. We have deployed and confirmed that the new timing is used properly

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_exclamation_mark: [more...](#be3cc364-a136-439a-a79e-635efad27520) |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#a9e2b24b-5f9b-4538-9097-d898d207e772) |
| mint-gateway-azure.sh | :heavy_exclamation_mark: [more...](#76d657ee-b8ca-4363-8dda-dbdb22f86b38) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#19f24daa-2d9f-4a2d-9b7d-cdd420fe20d0) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#886c0553-0a0e-4fce-b7b5-f588b9aa0954) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#5a811752-c913-4f36-8007-f627244ca546) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#d261295b-3179-470f-8009-fc456b5dc4b9) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#a505b1f3-bcff-4e54-ba3e-d903338f70e9) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#eb4d9eb9-ae73-4f40-b1fc-f4a0e29180a5) |
<a name="eb4d9eb9-ae73-4f40-b1fc-f4a0e29180a5"></a>
### 6399-874363a/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="19f24daa-2d9f-4a2d-9b7d-cdd420fe20d0"></a>
### 6399-874363a/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a9e2b24b-5f9b-4538-9097-d898d207e772"></a>
### 6399-874363a/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a505b1f3-bcff-4e54-ba3e-d903338f70e9"></a>
### 6399-874363a/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="5a811752-c913-4f36-8007-f627244ca546"></a>
### 6399-874363a/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="d261295b-3179-470f-8009-fc456b5dc4b9"></a>
### 6399-874363a/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="886c0553-0a0e-4fce-b7b5-f588b9aa0954"></a>
### 6399-874363a/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="76d657ee-b8ca-4363-8dda-dbdb22f86b38"></a>
### 6399-874363a/mint-gateway-azure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="be3cc364-a136-439a-a79e-635efad27520"></a>
### 6399-874363a/mint-tls.sh.xtrace:
```
DISABLED TIME BEING
```

**Review by nitisht — COMMENTED** [review]
@jdelamar we're planning to move from shell to a go implementation of healthcheck script. I suggest this can wait, and we can see how to incorporate this in the go healhcheck..

**Comment by jdelamar** [comment]
Thanks for your reply. 

But it really doesn't hurt to add it now? Little risk. Unless you are planning on the Go implementation shortly? Also, I noticed yesterday that the curl command is not in the Dockerfile and Dockerfile.dev files (only in the Dockerfile.release). Couldn't understand why my services were still killed after a longer time :)

Up to you.

**Review by harshavardhana — CHANGES_REQUESTED** [review]
is there a good reason why the startup is taking around 500 secs?

**Comment by jdelamar** [comment]
In my case it is closer to 300 seconds. I am looking at this. I am suspecting it has to do with the underlying I/O, but I am not sure yet.

**Comment by deekoder** [comment]
@jdelamar any insights into why it may be taking 300 seconds? We welcome any additional details @jdelamar

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Healthcheck is not a script anymore it's a native Go binary @jdelamar can you test the latest release and let us know if you need this configurable still? 

Going to close this PR for now. Feel free to re-open or open an issue stating further the requirements.

**Pull request closed without merging**
