### PR TITLE
Fix CopyObject with Metadata for Azure Gateway

### LINKED ISSUE #4924: [gateway/azure/s3/gcs]: copy object with metadata doesn't set metadata on destination object
While running below minio-java test, azure gateway fails.

```java 
  /**
   * Test: copyObject(String bucketName, String objectName, String destBucketName,
   * CopyConditions copyConditions, Map metadata) replace
   * object metadata.
   */
  public static void copyObject_test8() throws Exception {
    if (!mintEnv) {
      System.out.println("Test: copyObject(String bucketName, String objectName, String destBucketName,"
                        + "CopyConditions copyConditions, Map<String, String> metadata)"
                        + " replace object metadata");
    }

    long startTime = System.currentTimeMillis();
    try {
      String objectName = getRandomName();
      InputStream is = new ContentInputStream(3 * MB);
      client.putObject(bucketName, objectName, is, 3 * MB, "application/octet-stream");
      is.close();

      String destBucketName = getRandomName();
      client.makeBucket(destBucketName);

      CopyConditions copyConditions = new CopyConditions();
      copyConditions.setReplaceMetadataDirective();

      Map<String, String> metadata = new HashMap<>();
      metadata.put("Content-Type", customContentType);

      client.copyObject(bucketName, objectName, destBucketName, objectName, copyConditions, metadata);

      ObjectStat objectStat = client.statObject(destBucketName, objectName);
      if (!customContentType.equals(objectStat.contentType())) {
        throw new Exception("content type differs. expected: " + customContentType + ", got: "
                            + objectStat.contentType());
      }

      client.removeObject(bucketName, objectName);
      client.removeObject(destBucketName, objectName);
      client.removeBucket(destBucketName);
      mintSuccessLog("copyObject(String bucketName, String objectName, String destBucketName, "
                     + "CopyConditions copyConditions, Map<String, String> metadata)",
                     null, startTime);
    } catch (Exception e) {
      mintFailedLog("copyObject(String bucketName, String objectName, String destBucketName, "
                    + "CopyConditions copyConditions, Map<String, String> metadata)",
                    null, startTime, null,
                    e.toString() + " >>> " + Arrays.toString(e.getStackTrace()));
      throw e;
    }
  }
```

### PR DESCRIPTION
**Pull request by donatello**
## Description

Set metadata from Copy-Object request on destination object.

~This PR **SHOULD NOT** be merged directly. It should be merged after the Azure SDK update PR #4985 is merged. I will update the PR to fix conflicts once that is merged.~

## Motivation and Context

Fixes #4924 and https://github.com/minio/minio-java/issues/614 (azure part) - both are referring to the same bug.

## How Has This Been Tested?

Minio-Java Copy-Object functional tests pass.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
Blocked by https://github.com/minio/minio/pull/4985

**Comment by deekoder** [comment]
Removing blocked because the dependent PR is merged.

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Build fix needed.. @donatello  :-1: until then.

**Comment by donatello** [comment]
@harshavardhana Build is fixed.

**Review by harshavardhana — APPROVED** [review]

**Review by balamurugana — APPROVED** [review]
LGTM

**Comment by balamurugana** [comment]
Tested

**Pull request merged**
