### PR TITLE
fix: Avoid closing target in RegisterNotificationTargets

### LINKED ISSUE #8963: Minio service stops when notify_kafka is configured
## Current Behavior

The service crash on  with the following log:

Feb  6 10:16:35 minionode10 minio: panic: send on closed channel
Feb  6 10:16:35 minionode10 minio: goroutine 413 [running]:
Feb  6 10:16:35 minionode10 minio: github.com/Shopify/sarama.(*asyncProducer).shutdown(0xc000301110)
Feb  6 10:16:35 minionode10 minio: /q/.q/sources/gopath/pkg/mod/github.com/!shopify/sarama@v1.24.1/async_producer.go:1017 +0xd9
Feb  6 10:16:35 minionode10 minio: github.com/Shopify/sarama.withRecover(0xc000726560)
Feb  6 10:16:35 minionode10 minio: /q/.q/sources/gopath/pkg/mod/github.com/!shopify/sarama@v1.24.1/utils.go:45 +0x4d
Feb  6 10:16:35 minionode10 minio: created by github.com/Shopify/sarama.(*asyncProducer).AsyncClose
Feb  6 10:16:35 minionode10 minio: /q/.q/sources/gopath/pkg/mod/github.com/!shopify/sarama@v1.24.1/async_producer.go:297 +0x6b
Feb  6 10:16:35 minionode10 systemd: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb  6 10:16:35 minionode10 systemd: Unit minio.service entered failed state.
Feb  6 10:16:35 minionode10 systemd: minio.service failed.

## Steps to Reproduce (for bugs)

1. mc admin config set SERVER notify_kafka:1 enable=on topic=minioevent brokers=SERVER1:6667,SERVER2:6667,SERVER3:6667 sasl_username= sasl_password= client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off queue_limit=0 queue_dir=

2. If minio.service is started again the system work, but as soon as "mc admin info" or other mc admin commands are used the service on the responding servernode fail.  

3. Starting minio.service and resetting the notify_kafka configuration and restarting via "mc admin service restart ---" make the system fully operational again

## Your Environment

Version used: releases 2020-02-07T04:56:50Z, 2020-01-25T02-50-51Z adn 2020-01-16T22-40-29Z
Server type and version: Virtual VMware
Operating System and version: RHEL7
Reproduced on a distributed 4 node cluster and a standalone node

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
This will prevent a double target Close() call when fetchLambdaInfo()
is executed (mc admin info)

This fixes the following crash when mc admin info is called:

```
  panic: send on closed channel
  goroutine 2036 [running]:
  github.com/Shopify/sarama.(*asyncProducer).shutdown(0xc0006dda40)
  /q/.q/sources/gopath/pkg/mod/github.com/!shopify/sarama@v1.24.1/async_producer.go:1017 +0xd9
  github.com/Shopify/sarama.withRecover(0xc0012befd0)
  /q/.q/sources/gopath/pkg/mod/github.com/!shopify/sarama@v1.24.1/utils.go:45 +0x4d
  created by github.com/Shopify/sarama.(*asyncProducer).AsyncClose
  /q/.q/sources/gopath/pkg/mod/github.com/!shopify/sarama@v1.24.1/async_producer.go:297 +0x6b
```

## Motivation and Context
fixes #8963 

## How to test this PR?
- Run the following docker-compose
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

to start a Kafka server

2. Enable kafka in MinIO server
3. mc admin info

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by harshavardhana** [comment]
There is a problem in this fix @vadmeste , we need to close the targets when it's under `test` - the issue seems to be that `admin info` is incorrectly doing a Register unnecessarily.

**Comment by harshavardhana** [comment]
All we need remove is this

```diff
~ git diff
diff --git a/cmd/admin-handlers.go b/cmd/admin-handlers.go
index b76d4e84b..15fe45b23 100644
--- a/cmd/admin-handlers.go
+++ b/cmd/admin-handlers.go
@@ -1538,8 +1538,6 @@ func fetchLambdaInfo(cfg config.Config) []map[string][]madmin.TargetIDStatus {
                list := lambdaMap[targetID.Name]
                list = append(list, targetIDStatus)
                lambdaMap[targetID.Name] = list
-               // Close any leaking connections
-               _ = target.Close()
        }
 
        notify := make([]map[string][]madmin.TargetIDStatus, len(lambdaMap))
```

**Review by Praveenrajmani — APPROVED** [review]
Tested and LGTM

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#49969b25-3bf0-4882-a573-fa50b06f5da2) |
| mint-gateway-nas.sh | :x: [more...](#5905dbf6-6cff-4eb1-8fe8-93d3e05d3f96) |
<a name="49969b25-3bf0-4882-a573-fa50b06f5da2"></a>
### 8966-252953a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32604
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3dc6a4bfc9cc:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 23 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 47 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 23 seconds
{
  "args": {},
  "duration": 68641,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="5905dbf6-6cff-4eb1-8fe8-93d3e05d3f96"></a>
### 8966-252953a/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31006
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 038e32867400:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 306741, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31006/awscli-mint-test-bucket-9879""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d37d96af-e293-4dfc-9143-2d21ea170b49) |
| mint-worm.sh | :x: [more...](#be6c4217-077a-4aa9-a730-3ccd0af40e42) |
| mint-gateway-azure.sh | :x: [more...](#531b951e-e5fd-4c0c-845e-386a0a11d372) |
<a name="531b951e-e5fd-4c0c-845e-386a0a11d372"></a>
### 8966-457e23a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32336
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4dd4f2954b38:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 11 seconds
{"name": "awscli", "duration": 308800, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32336/awscli-mint-test-bucket-21011""}

Executed 0 out of 13 tests successfully.
```
<a name="d37d96af-e293-4dfc-9143-2d21ea170b49"></a>
### 8966-457e23a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30509
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 860a803b1e82:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 34 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 56 seconds
(5/13) Running minio-go tests ... FAILED in 15 minutes and 9 seconds
{
  "args": {},
  "duration": 105459,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="be6c4217-077a-4aa9-a730-3ccd0af40e42"></a>
### 8966-457e23a/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30297
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f49cccdcba7f:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-4pl57s0oxyx80kojd21etrsbiub1340gk3dld2c8qp4wg0mssl6q04n",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120284,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30297/bucket-4pl57s0oxyx80kojd21etrsbiub1340gk3dld2c8qp4wg0mssl6q04n: dial tcp 72.28.97.55:30297: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#36c8ff57-bdef-4e88-ad17-5f4849fe6b38) |
| mint-large-bucket.sh | :x: [more...](#bb2ca245-f08a-434f-80c5-dbbb074f4cf0) |
<a name="36c8ff57-bdef-4e88-ad17-5f4849fe6b38"></a>
### 8966-6cee1bd/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31678
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b77418ac89ce:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 7764,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="bb2ca245-f08a-434f-80c5-dbbb074f4cf0"></a>
### 8966-6cee1bd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31055
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cff12220baf7:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 24 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 46 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 45 seconds
{
  "args": {},
  "duration": 95178,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
