### PR TITLE
fix: Avoid more crashes due to concurrent map usage

### LINKED ISSUE #5897: Rare crash due to a concurrent map writes
## Expected Behavior
No crash

## Current Behavior
Rare crash

```
fatal error: concurrent map writes

goroutine 2505706 [running]:
runtime.throw(0x112243a, 0x15)
        /home/minio/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:616 +0x81 fp=0xc4200f1eb0 sp=0xc4200f1e90 pc=0x42cc61
runtime.mapassign(0xf77fe0, 0xc4260962a0, 0xc4200f1f78, 0x11fb5a0)
        /home/minio/.gimme/versions/go1.10.1.linux.amd64/src/runtime/hashmap.go:607 +0x553 fp=0xc4200f1f40 sp=0xc4200f1eb0 pc=0x409da3
github.com/minio/minio/cmd.(*NotificationSys).DeleteBucket.func1(0xc4245f4f30, 0xc4204e6b48, 0x32, 0xc4260962a0, 0x7ffde2a453ba, 0x9, 0xc42501238f, 0xc42021e330)
        /home/minio/vadmeste/gospace/src/github.com/minio/minio/cmd/notification.go:71 +0xf0 fp=0xc4200f1fa0 sp=0xc4200f1f40 pc=0xc49270
runtime.goexit()
        /home/minio/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200f1fa8 sp=0xc4200f1fa0 pc=0x45a451
created by github.com/minio/minio/cmd.(*NotificationSys).DeleteBucket
        /home/minio/vadmeste/gospace/src/github.com/minio/minio/cmd/notification.go:68 +0x16e
```

## Possible Solution
Do not know yet

## Steps to Reproduce (for bugs)
Running minio-py in full mode multiple times.

```sh
while true; do 
   docker run --net="host" -e SERVER_ENDPOINT=65.xx.xx.xx:9101 -e ACCESS_KEY=minio -e SECRET_KEY=minio123 -e ENABLE_HTTPS=0 -e MINT_MODE=full minio/mint:edge minio-py; 
done
```

## Context
Testing

## Your Environment
All, master

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This PR fixes another situation where a crash occurs
thanks to @krishnasrinivas for reproducing this

## Motivation and Context
Fixes #5897

## How Has This Been Tested?
Manually using the reproducer in #5897 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
NOTE: I have changed the errs from being slice to channels, to avoid double looping by the caller for no error situations.

**Review by krishnasrinivas — APPROVED** [review]
tested.

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#aca55345-8678-49e3-9415-97793af62b91) |
<a name="aca55345-8678-49e3-9415-97793af62b91"></a>
### 5912-d39d226/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30578
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp a35759b357d1:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 18 seconds
(2/13) Running aws-sdk-java tests ... done in 7 seconds
(3/13) Running aws-sdk-php tests ... done in 54 seconds
(4/13) Running aws-sdk-ruby tests ... done in 56 seconds
(5/13) Running awscli tests ... done in 4 minutes and 9 seconds
(6/13) Running mc tests ... done in 3 minutes and 58 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 2 seconds
(8/13) Running minio-go tests ... done in 14 seconds
(9/13) Running minio-java tests ... done in 51 seconds
(10/13) Running minio-js tests ... FAILED in 43 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-81db5a72-3227-49b8-bb7e-1510aa524197, events: s3:ObjectCreated:*",
  "duration": 8479,
  "status": "FAIL",
  "error": "Error: notification not received at client.removeObject.err (test/functional-tests.js:1034:43) at ClientRequest.<anonymous> (node_modules/minio/dist/main/minio.js:420:9) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:478:21) at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23) at Socket.socketOnData (_http_client.js:367:20) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at TCP.onread (net.js:559:20)"
}

Executed 9 out of 13 tests successfully.
```

**Pull request merged**
