### PR TITLE
One click OpenID authorization on Login page

### PR DESCRIPTION
**Pull request by egorkaru**
## Description
Adds new `MINIO_IDENTITY_OPENID_CLIENT_ID` environment variable by definition it on minio start OpenID button on login page starts redirecting to OIDC auth page, instead of sending to minio openid login page.

## Motivation and Context
Simplify log in by OIDC for constant client id

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by ihostage** [comment]
As continuation of [this](https://minio.slack.com/archives/C3NDUB8UA/p1574162338126800) discuss on Slack. 😉

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#32ae8877-1731-498f-99b2-00c67d910eb4) |
| mint-compression-dist-xl.sh | :x: [more...](#4c44b7a8-5122-41b3-8032-34e2d92cb2ab) |
<a name="4c44b7a8-5122-41b3-8032-34e2d92cb2ab"></a>
### 8552-4d4d482/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31945
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 14b4a1567f7f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 41 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 48 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 0 seconds
(11/14) Running minio-js tests ... done in 50 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 12 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1172, in test_list_objects_with_1001_files\n    client.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 417, in remove_bucket\n    self._url_open('DELETE', bucket_name=bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1949, in _url_open\n    object_name).get_exception()\nminio.error.BucketNotEmpty: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2033, in main\n    test_list_objects_with_1001_files(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1174, in test_list_objects_with_1001_files\n    raise Exception(err)\nException: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n",
  "args": {
    "object_name": "d3ee849b-0b5b-41dd-92b4-a586f7c5ff72_0 ~ d3ee849b-0b5b-41dd-92b4-a586f7c5ff72_1000",
    "bucket_name": "minio-py-test-d12e48c0-63b4-4169-a1ea-d9e6508dac60"
  },
  "function": "list_objects(bucket_name, prefix, recursive)",
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "duration": 102684,
  "message": "BucketNotEmpty: message: The bucket you tried to delete is not empty."
}

Executed 11 out of 14 tests successfully.
```
<a name="32ae8877-1731-498f-99b2-00c67d910eb4"></a>
### 8552-4d4d482/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32115
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 69aaf12c9e89:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 minutes and 49 seconds
(2/14) Running aws-sdk-java tests ... done in 29 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 3 minutes and 39 seconds
{
  "name": "aws-sdk-php",
  "function": "listMultipartUploads ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5dd6a1bd41dc0",
    "Object": "obj1"
  },
  "duration": "570",
  "status": "FAIL",
  "error": "Error executing \"CreateMultipartUpload\" on \"http://72.28.97.61:32115/aws-sdk-php-5dd6a1bd41dc0/obj1-copy?uploads\"; AWS HTTP error: Server error: `POST http://72.28.97.61:32115/aws-sdk-php-5dd6a1bd41dc0/obj1-copy?uploads` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>obj (truncated...)\n SlowDown (server): Please reduce your request - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>obj1-copy</Key><BucketName>aws-sdk-php-5dd6a1bd41dc0</BucketName><Resource>/aws-sdk-php-5dd6a1bd41dc0/obj1-copy</Resource><RequestId>15D934A26AE8CF92</RequestId><HostId>d9c578a0-0376-4019-b1ff-691bce8711e8</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
Error: No such image: minio/minio:8552-4d4d482

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#11c318a8-59ae-436d-a012-545f09c21ccf) |
<a name="11c318a8-59ae-436d-a012-545f09c21ccf"></a>
### 8552-94a8692/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32712
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a9289306bc7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 17 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 0 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 51 seconds
{
  "args": {},
  "duration": 94545,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8552-94a8692

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#cb503221-bce4-43e0-af91-2052cb5797fe) |
| mint-compression-dist-xl.sh | :x: [more...](#b21f105e-7b4d-42fd-ab9e-cf3fa766a6d2) |
<a name="cb503221-bce4-43e0-af91-2052cb5797fe"></a>
### 8552-9893bf4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32310
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 57a4ac893ad3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 10 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 2 minutes and 28 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 0 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 1 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 3 seconds
{
  "args": {},
  "duration": 104893,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="b21f105e-7b4d-42fd-ab9e-cf3fa766a6d2"></a>
### 8552-9893bf4/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31410
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e5df7063ad0b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 16 seconds
(11/14) Running minio-js tests ... done in 48 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 16 seconds
{
  "function": "list_objects(bucket_name, prefix, recursive)",
  "name": "minio-py:test_list_objects_with_1001_files",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1172, in test_list_objects_with_1001_files\n    client.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 417, in remove_bucket\n    self._url_open('DELETE', bucket_name=bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1949, in _url_open\n    object_name).get_exception()\nminio.error.BucketNotEmpty: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2033, in main\n    test_list_objects_with_1001_files(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1174, in test_list_objects_with_1001_files\n    raise Exception(err)\nException: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n",
  "duration": 166421,
  "args": {
    "bucket_name": "minio-py-test-a7414814-5d21-4e54-bcd2-bbd30fe8829c",
    "object_name": "2423bb91-dc4b-4dba-bbcb-13df9d0f932c_0 ~ 2423bb91-dc4b-4dba-bbcb-13df9d0f932c_1000"
  },
  "message": "BucketNotEmpty: message: The bucket you tried to delete is not empty.",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
Error: No such image: minio/minio:8552-9893bf4

**Comment by harshavardhana** [comment]
This PR is not complete, in lieu of time will send another PR with the original commit and working off this branch. Closing this PR for now.

**Pull request closed without merging**
