### PR TITLE
Minio start permission issue

### LINKED ISSUE #9746: [resolved] Unable to initialize backend: Insufficient permissions to access path
## Expected Behavior
minIO should start normally using provided folder as its backend

## Current Behavior
minIO fails to start when provided backend is `/media/pi/Toshiba/minIO.data/` which is a mounted USB HDD. See error message in Title.

## Possible Solution
Literally no idea what's happening. minIO should have the same rights as the user executing the binary but it feels like minIO is ran by a user with less permissions

## Steps to Reproduce (for bugs)
See below in `Your Environment`

## Context
I'm trying to start minIO on a Raspberry PI 4 device under Raspbian.

## Regression
No (?)

## Your Environment
  * RPI 4 + Raspbian
  * No docker
  * Just compiled minio binary from source

```bash
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

pi@raspberrypi:~ $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 135.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

minio@raspberrypi:~ $ cat /proc/mounts | grep sda
/dev/sda /media/pi/Toshiba ext4 rw,relatime 0 0
/dev/sda /mnt/Toshiba ext4 rw,relatime 0 0

minio@raspberrypi:~ $ namei -l /media/pi/Toshiba/minIO.data/
f: /media/pi/Toshiba/minIO.data/
drwxr-xr-x root root  /
drwxr-xr-x root root  media
drwxr-xr-x pi   pi    pi
drwxrwxr-x pi   minio Toshiba
drwxrwxr-x pi   minio minIO.data

minio@raspberrypi:~ $ id && group
uid=1001(minio) gid=1002(minio) groups=1002(minio)
bash: group: command not found

minio@raspberrypi:~ $ /usr/local/bin/minio --version
minio version DEVELOPMENT.GOGET

minio@raspberrypi:~ $ (cd /usr/local/src/minio/ && git log --format="%H" -n 1)
8befedef14d7968e0f1ecf8e788bdcdf4e1e2a7f

minio@raspberrypi:~ $ touch /media/pi/Toshiba/minIO.data/newTestFile

minio@raspberrypi:~ $ /usr/local/bin/minio server --address :9000 /media/pi/Toshiba/minIO.data
ERROR Unable to initialize backend: Insufficient permissions to access path
      > Please ensure the specified path can be accessed

minio@raspberrypi:~ $
```

Surprisingly, if I specifcy a different non-user location, it does work as expected:
```bash
minio@raspberrypi:/mnt/Toshiba $ namei -l /opt/minioDATA/
f: /opt/minioDATA/
drwxr-xr-x root  root /
drwxr-xr-x root  root opt
drwxrwxr-x minio root minioDATA
minio@raspberrypi:/mnt/Toshiba $ /usr/local/bin/minio server --address :9000 /opt/minioDATA/
# ...
# OK
```

Am I overseeing something or is this intentional behaviour?
The `minio` user can read/write/access the specified location (no permission error returned by `touch` in my example.

Thanks!

### PR DESCRIPTION
**Pull request by ebozduman**
Fixes #9746
When there is an ownership problem with the data directory or endpoint during minio server start time, the provided HINT in the error message was not applied to the internal `.minio.sys` directory and its content since "-R" option was not included in the suggestion.

## Motivation and Context
To give user the correct HINT that works

## How to test this PR?
- Start minio server with a simple data directory, like `/tmp/dir/` as user "user1"
- Change user and be "user2" and run the same command to start minio server at the same data directory
- You'll hit the error message with the HINT. Run the proposed first command in the error message to fix the error conditon and make sure the same command can start the minio server 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#7435ba87-f914-4488-9c20-48afa8e06f4e) |
| mint-large-bucket.sh | :x: [more...](#0572001b-8ec0-4eb4-bd73-4e87d223d4d4) |
| mint-dist-xl.sh | :x: [more...](#d12cadd1-066e-4f98-bebf-4c38ad2b7a9c) |
<a name="7435ba87-f914-4488-9c20-48afa8e06f4e"></a>
### 9844-bd68b19/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32306
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c409d8c42d5d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 17 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 47 seconds
(8/15) Running minio-dotnet tests ... done in 35 seconds
(9/15) Running minio-go tests ... FAILED in 52 seconds
{
  "args": {
    "bucketName": "minio-go-test-h2vp3m2zctk2wcbg",
    "objectName": "rll09f4xdacbj1apjcwhjb0fl00rvm",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4331,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 1 minutes and 1 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 119,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-lhu4qh, objectName = null, resource = /minio-java-test-lhu4qh, requestId = 1618F68D9307D414, hostId = b98d8559-43aa-479c-bac0-9f7d798332a7)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:32306/minio-java-test-lhu4qh, headers=Host: minio-dev3.minio.io:32306\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T074556Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T07-33-42Z\nVary: Origin\nX-Amz-Request-Id: 1618F68D9307D414\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 07:45:56 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 59 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 15 seconds
(11/15) Running s3cmd tests ... done in 18 seconds
(12/15) Running s3select tests ... done in 3 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="0572001b-8ec0-4eb4-bd73-4e87d223d4d4"></a>
### 9844-bd68b19/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30905
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a2d750f2f93a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 6 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 9 seconds
(5/15) Running awscli tests ... done in 2 minutes and 41 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 0 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 32 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 10 seconds
{
  "args": {
    "bucketName": "minio-go-test-s6n0w6zrg1n1hcl9",
    "objectName": "5yjdipapvmhdnvijndu4pqsceghucn",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3892,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 6 minutes and 41 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 942,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-v5naid, objectName = null, resource = /minio-java-test-v5naid, requestId = 1618F7095C54C7B9, hostId = 6d8ddc57-b668-4d13-a201-27490dfbccb5)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:30905/minio-java-test-v5naid, headers=Host: minio-dev6.minio.io:30905\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T075447Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T07-33-42Z\nVary: Origin\nX-Amz-Request-Id: 1618F7095C54C7B9\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 07:54:47 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 55 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 38 seconds
(11/15) Running s3cmd tests ... done in 26 seconds
(12/15) Running s3select tests ... done in 15 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="d12cadd1-066e-4f98-bebf-4c38ad2b7a9c"></a>
### 9844-bd68b19/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30295
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ae0e36331e6d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 4 seconds
(8/15) Running minio-dotnet tests ... done in 57 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 39 seconds
{
  "args": {
    "bucketName": "minio-go-test-g509fw2gn3zg5ysp",
    "objectName": "pbrv2wrt1khaktwu39roastmkvxzlg",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5435,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 15 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 256,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-1rkiu6g, objectName = null, resource = /minio-java-test-1rkiu6g, requestId = 1618F6B4DEBA1F89, hostId = a2d12a0a-4d24-43b4-acca-0e1e20a6daca)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:30295/minio-java-test-1rkiu6g, headers=Host: minio-dev4.minio.io:30295\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T074844Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T07-33-42Z\nVary: Origin\nX-Amz-Request-Id: 1618F6B4DEBA1F89\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 07:48:44 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 50 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 57 seconds
(11/15) Running s3cmd tests ... done in 22 seconds
(12/15) Running s3select tests ... done in 6 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by ebozduman** [comment]
I am working on cleaning up the other commits that came along somehow.

**Comment by ebozduman** [comment]
Closing this PR as its target is set to `minio:release` by mistake. Default setting was not `master` somehow and I did not notice it when I created the PR.

**Comment by klauspost** [comment]
@ebozduman You should be able to point it at release here. Click `Edit` by the title field.

**Pull request closed without merging**
