### PR TITLE
Enable event persistence in kafka

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
Kafka events will be persisted in a queue dir if configured, else persisted in memory.

## Motivation and Context
To provide offline backup/persistence for events, so that no events are lost.

## Regression
Its a feature

## How Has This Been Tested?

- Start MinIO without an active kafka broker with the following config
```
{
        "enable": true,
        "brokers": ["localhost:9092", "localhost:9093", "localhost:9094"],
        "topic": "bucketevents",
        "queueDir": "/tmp/kafka",
        "queueLimit": 1000,
        "tls": {
            "enable": false,
            "skipVerify": false,
            "clientAuth": 0
        },
        "sasl": {
            "enable": false,
            "username": "",
            "password": ""
        }
}
```
- Enable bucket notification using mc
- Start sending events
- The events will persist in `/tmp/kafka` and gets replayed when the broker is turned on. (/tmp/kafka - will be empty if all the events are successfully sent - atleast leader is online)
- Set up a multi-node kafka cluster
- For an event to be successfully sent, the leader must be online. You can see the leader node by - `bin/kafka-topics.sh --describe --bootstrap-server localhost:9092 --topic bucketevents` 
- The events will be replayed from the store. which can be monitored by - `kafkacat -b localhost:9092 -t bucketevents`
- Bring the leader node up/down to eventually test the persistence and replay.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by nitisht** [comment]
blocked till #7658 is merged

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#cf755888-189d-4491-a6e6-befc7b305a0f) |
<a name="cf755888-189d-4491-a6e6-befc7b305a0f"></a>
### 7633-851ee3c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30219
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f82f51d14109:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 1 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 3 seconds
{
  "name": "mc",
  "duration": "101910",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-18769 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-24405  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-24405/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-24405/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-24405/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-24405/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-24405/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-24405/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-24405/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-24405/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-24405/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-24405/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-24405/datafile-5243880-b`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-24405/datafile-100-kB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-24405/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-24405/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 358.55 MiB, Speed: 3.52 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#b74a3193-1890-4556-811e-ae011cd4b623) |
<a name="b74a3193-1890-4556-811e-ae011cd4b623"></a>
### 7633-de25728/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31117
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 444f9f5d50e4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qii906egocas6m",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360011,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A146F6E7F8350F, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by nitisht — APPROVED** [review]
LGTM & Tested

**Review by sinhaashish — APPROVED** [review]
LGTM

**Comment by kannappanr** [comment]
@Praveenrajmani Can you PTAL at SimpleCI failure?

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#65fd8ec0-4eeb-4c4b-b204-8d6dfa21f5bb) |
<a name="65fd8ec0-4eeb-4c4b-b204-8d6dfa21f5bb"></a>
### 7633-60e835e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30455
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 100a5d8b662e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 57 seconds
{
  "name": "mc",
  "duration": "97637",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-13216 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-24069  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-24069/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-24069/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-24069/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-24069/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-24069/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-24069/datafile-1.03-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-24069/datafile-33-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-24069/datafile-10-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-24069/datafile-5-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-24069/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-24069/datafile-100-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-24069/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-24069/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-24069/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 288.80 MiB, Speed: 2.96 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Pull request merged**
