### PR TITLE
add cross-build linux/amd64

### PR DESCRIPTION
**Pull request by yanggangtony**
## How to test this PR?
make crosscompile

when i compile the code in macos , i want to test if it can build ok in linux/amd64.

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#38852e4b-eb86-4de6-ace9-e35139d61608) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#573c8fd8-fe79-4f3f-8d03-2c7e20314365) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#a4c5b5b4-f087-48b8-8276-d19fa15e8817) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#bdd456fa-6ffb-4e63-8ab7-1c61f8fe9694) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#37456d98-ac44-47ad-ae50-2f88c358821e) |
| mint-pools.sh | :heavy_exclamation_mark: [more...](#a4dbf0d3-a14d-4548-9666-c8052682851d) |
<a name="bdd456fa-6ffb-4e63-8ab7-1c61f8fe9694"></a>
### 15949-f3447de/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a4c5b5b4-f087-48b8-8276-d19fa15e8817"></a>
### 15949-f3447de/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="38852e4b-eb86-4de6-ace9-e35139d61608"></a>
### 15949-f3447de/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a4dbf0d3-a14d-4548-9666-c8052682851d"></a>
### 15949-f3447de/mint-pools.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="573c8fd8-fe79-4f3f-8d03-2c7e20314365"></a>
### 15949-f3447de/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="37456d98-ac44-47ad-ae50-2f88c358821e"></a>
### 15949-f3447de/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#3ec28339-29f7-4248-b807-1668eb20bb7f) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#98ef9c25-52ab-46ba-964c-0e39b12b5598) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#4e208158-d182-4464-8a3a-ab76e9d1cac1) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#2a3ae1f9-071f-4690-b042-ec0dabe15d40) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#82fcc35f-c440-4ddf-a74b-e3cd6b390056) |
| mint-pools.sh | :heavy_exclamation_mark: [more...](#bb0c0512-5448-4df7-af00-c926d6e5e05a) |
<a name="3ec28339-29f7-4248-b807-1668eb20bb7f"></a>
### 15949-25eb766/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="4e208158-d182-4464-8a3a-ab76e9d1cac1"></a>
### 15949-25eb766/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="98ef9c25-52ab-46ba-964c-0e39b12b5598"></a>
### 15949-25eb766/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="bb0c0512-5448-4df7-af00-c926d6e5e05a"></a>
### 15949-25eb766/mint-pools.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="2a3ae1f9-071f-4690-b042-ec0dabe15d40"></a>
### 15949-25eb766/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="82fcc35f-c440-4ddf-a74b-e3cd6b390056"></a>
### 15949-25eb766/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

**Comment by yanggangtony** [comment]
/cc @harshavardhana @vadmeste
could you please take a look?

**Review by klauspost — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Pull request merged**
