### PR TITLE
Cleanup Kubernetes documentation

### PR DESCRIPTION
**Pull request by nitisht**
## Description
Removed Minikube and Helm specific documentation and consolidate yaml based examples. 

## Motivation and Context
- Helm chart is documented well in its own repository. We can point to that document instead of keeping a duplicate document in our repo. 
- Minikube now supports dynamic PV creation, so our sample yaml files will run on Minikube without any additional hacks. So, Minikube specific documentation is removed.

## Regression
No

## How Has This Been Tested?
Ran the sample yaml files on local Minikube.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Can you check any links are affected elsewhere in our docs or website for this change ?

**Comment by nitisht** [comment]
> Can you check any links are affected elsewhere in our docs or website for this change ?

Checked README with https://github.com/tcort/markdown-link-check . Links seem to be okay

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Btw @nitisht we can add this lint check when running our CI ?

**Comment by nitisht** [comment]
> we can add this lint check when running our CI ?

Sure, how about this ? https://github.com/minio/awesome-minio/blob/master/.travis.yml#L10

**Comment by harshavardhana** [comment]
> Sure, how about this ? https://github.com/minio/awesome-minio/blob/master/.travis.yml#L10

Awesome bot is fine but I think markdown-lint-check is nice as well

**Comment by nitisht** [comment]
> Awesome bot is fine but I think markdown-lint-check is nice as well

Okay, will send a PR

**Comment by harshavardhana** [comment]
@Praveenrajmani ping

**Review by Praveenrajmani — APPROVED** [review]

**Pull request merged**
