### PR TITLE
Add a script to filter goroutines waiting for a given number of minutes

### PR DESCRIPTION
**Pull request by vadmeste**
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Linter issues, please address @vadmeste

@anjalshireesh we can use this to look for relevancy in our subnet goroutines viewer?. We can enhance it to optionally show the ones that are waiting, avoids all the other clutter.

**Review by anjalshireesh — APPROVED** [review]
LGTM, tested

**Review by klauspost — APPROVED** [review]

**Comment by vadmeste** [comment]
I am thinking to add this simple feature:

- Simple file that contains of the stack trace that we want to ignore
OR
- Add some specific comments to the existing code, something like a comment
   //minio:pprof
and this tool will ignore printing all the correspnding stack trace

the problem of the second it will only be useful after many months.

**Comment by klauspost** [comment]
@vadmeste I am not sure I completely understand.

If you want something better, an interactive tool that accumulates time spent on traces.

Take this example:

```
goroutine 401 [IO wait, 21474 minutes]:
internal/poll.runtime_pollWait(0x7fffd09e5ba8, 0x72)
	runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc002e1c000?, 0x29ed74e?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc002e1c000)
	internal/poll/fd_unix.go:614 +0x234
net.(*netFD).accept(0xc002e1c000)
	net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc002e1e000)
	net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).AcceptTCP(0xc002e1e000)
	net/tcpsock.go:275 +0x3d
github.com/minio/minio/internal/http.(*httpListener).start.func2(0x0, 0xc00077c360?)
	github.com/minio/minio/internal/http/listener.go:59 +0x97
created by github.com/minio/minio/internal/http.(*httpListener).start
	github.com/minio/minio/internal/http/listener.go:69 +0xb7
```

Here a goroutine waited 21474 minutes. 

Step 1) clean backtrace by removing parameters since they vary and combine function and line info.

```
internal/poll.runtime_pollWait	runtime/netpoll.go:305
internal/poll.(*pollDesc).wait	internal/poll/fd_poll_runtime.go:84
...
```
This makes each line of the backtrace a key.

We start by accumulating all with first line, ie all that start with `internal/poll.runtime_pollWait	runtime/netpoll.go:305 +0x89`

This is the top level. We simply provide these sorted by accumulated time, descending.

In your fancy (text mode) UI you can then select this line. This will display the next line until there is a divergenge in the path.

Let's say there are 3 paths that leads to this, we show the top 5 callers with the percentage of the calls coming from this.
```
> internal/poll.runtime_pollWait	runtime/netpoll.go:305 (25 days, 4h)
...
github.com/minio/minio/internal/http.(*httpListener).start.func2	github.com/minio/minio/internal/http/listener.go:59 (50%)
github.com/minio/minio/internal/http.(*httpListener).start.func3	github.com/minio/minio/internal/http/listener.go:69 (30%)
github.com/minio/minio/internal/http.(*httpListener).start.func3	github.com/minio/minio/internal/http/listener.go:79 (20%)
...
```
This can be selected. If there are no sub-branches it just shows the backtrace.

**Pull request merged**
