### PR TITLE
[s3select] Support for column names with spaces inbetween 

### LINKED ISSUE #6589: s3 select should parse column names with spaces
There can be spaces in column names which should be honored.

## Expected Behavior
The expression `select s."JURISDICTION NAME" from S3Object s` should work with minio's s3select

## Current Behavior
We get ```botocore.exceptions.ClientError: An error occurred (LexerInvalidChar) when calling the SelectObjectContent operation: The SQL expression contains an invalid character.```
for such queries

## Possible Solution
The surrounding " " and ' '  can be replaced with back ticks as per [https://github.com/xwb1989/sqlparser/issues/39#issuecomment-397118463](url)

## Steps to Reproduce (for bugs)

```
import boto3
from botocore.client import Config
import os
s3 = boto3.resource('s3',
                    endpoint_url='http://192.168.86.155:9000',
                    aws_access_key_id='minio',
                    aws_secret_access_key='minio123',
                    config=Config(signature_version='s3v4'),
                    region_name='us-east-1')
s3_client = s3.meta.client
#Expression = "SELECT A_1, A_2 FROM S3OBJECT AS A",
r = s3_client.select_object_content(
        Bucket='testselect',
        Key='spacecsv.csv',
        ExpressionType='SQL',
        Expression = 'select s."JURISDICTION NAME" from S3Object s',
        InputSerialization = {'CSV': {"RecordDelimiter": "\n", "FieldDelimiter": ",","FileHeaderInfo":"USE"}},
        OutputSerialization = {'CSV': {}},
    )

event_stream = r['Payload']
end_event_received = False
with open('output', 'wb') as f:
    # Iterate over events in the event stream as they come
    for event in event_stream:
        # If we received a records event, write the data to a file
        if 'Records' in event:
            data = event['Records']['Payload']
            f.write(data)
        # If we received a progress event, print the details
        elif 'Progress' in event:
            print(event['Progress']['Details'])
        # End event indicates that the request finished successfully
        elif 'End' in event:
            print('Result is complete')
            end_event_received = True
if not end_event_received:
    raise Exception("End event not received, request incomplete.")
```

## Context
s3Select

## Regression
No

## Your Environment
master's version

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
The double/single quotes should be replaced with back ticks (`) and the headers should be matching such compliant names.

## Motivation and Context
s3select for such column names should be honored
Fixes #6589

## Regression
No

## How Has This Been Tested?
```
import boto3
from botocore.client import Config
import os
s3 = boto3.resource('s3',
                    endpoint_url='http://192.168.86.155:9000',
                    aws_access_key_id='minio',
                    aws_secret_access_key='minio123',
                    config=Config(signature_version='s3v4'),
                    region_name='us-east-1')
s3_client = s3.meta.client
#Expression = "select s."JURISDICTION NAME" from S3Object s",
r = s3_client.select_object_content(
        Bucket='testselect',
        Key='spacecsv.csv',
        ExpressionType='SQL',
        Expression = "select s.'JURISDICTION NAME ' from S3Object s",
        InputSerialization = {'CSV': {"RecordDelimiter": "\n", "FieldDelimiter": ",","FileHeaderInfo":"USE"}},
        OutputSerialization = {'CSV': {}},
    )

event_stream = r['Payload']
end_event_received = False
with open('output', 'wb') as f:
    # Iterate over events in the event stream as they come
    for event in event_stream:
        # If we received a records event, write the data to a file
        if 'Records' in event:
            data = event['Records']['Payload']
            f.write(data)
        # If we received a progress event, print the details
        elif 'Progress' in event:
            print(event['Progress']['Details'])
        # End event indicates that the request finished successfully
        elif 'End' in event:
            print('Result is complete')
            end_event_received = True
if not end_event_received:
    raise Exception("End event not received, request incomplete.")
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
We should re-implement the SQL parser lexer to support this instead of doing query transformation in this manner. The expression is not going to be the same always and it is not a correct way to do it. 

The best way is strip down the sqlparser and move to a more smaller SQL parser.

**Comment by Praveenrajmani** [comment]
Can this PR be closed? Since the new sqlparser can cover this? @donatello

**Comment by harshavardhana** [comment]
For now we can take this while we are writing a new parser.

**Comment by harshavardhana** [comment]
We should close this PR @Praveenrajmani

**Review by harshavardhana — APPROVED** [review]

**Review by donatello — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Pull request merged**
