### PR TITLE
[draft] allow versions to spread across pools without pool locality

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
allow versions to spread across pools without pool locality

## Motivation and Context
This PR adds a new change where versions for "an" object 
to be spread across pools, this allows for versions to be 
now spread across pools to provide

- better space management when each version can be bigger
- create newer versions on newer pools to avail better 
  responsiveness
- and allows for lesser data movement when older pools 
  need to be decommissioned

This PR additionally also optimizes reading xl.meta for 
multipart uploads, to avoid multiple lock requests to 
read the same content. This should essentially increase 
overall performance for multipart requests in multi-pooled 
setup.

## How to test this PR?
Nothing should change the existing functionality, 

Tested following functionalities 

- decommission
- rebalance

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#abcd93fa-41d5-47af-9a83-1cb29a8b2e5e) |
<a name="abcd93fa-41d5-47af-9a83-1cb29a8b2e5e"></a>
### 16049-9a66abe/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:31353
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 42c24335ddc9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-9tncnhwkztr0rj",
    "objectName": "adqc6tnkzmkycjr23ck4firn4ikhsy"
  },
  "duration": 477,
  "error": "NoSuchUpload: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.\n\tstatus code: 404, request id: 172672FCD4C03A99, host id: ",
  "function": "testListMultipartUploads",
  "message": "AWS SDK Go CompleteMultipartUpload is expected to fail with EntityTooSmall",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/14) Running aws-sdk-java tests ... done in 1 seconds
(2/14) Running aws-sdk-php tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-php",
  "function": "uploadPart ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-636de7c7da46c",
    "Object": "obj1"
  },
  "duration": "336",
  "status": "FAIL",
  "error": "Error executing \"CompleteMultipartUpload\" on \"http://15.15.15.7:31353/aws-sdk-php-636de7c7da46c/obj1?uploadId=ZGNhMzcwNDMtZDAwZS00OTRjLWFkYTAtNTA3ZjVjYzUxNjVhLjEyNGJmYmU1LWUyY2YtNDU2YS1iNTE3LTA1NzNjNDliOWQ2MA\"; AWS HTTP error: Client error: `POST http://15.15.15.7:31353/aws-sdk-php-636de7c7da46c/obj1?uploadId=ZGNhMzcwNDMtZDAwZS00OTRjLWFkYTAtNTA3ZjVjYzUxNjVhLjEyNGJmYmU1LWUyY2YtNDU2YS1iNTE3LTA1NzNjNDliOWQ2MA` resulted in a `404 Not Found` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not  (truncated...)\n NoSuchUpload (client): The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.</Message><Key>obj1</Key><BucketName>aws-sdk-php-636de7c7da46c</BucketName><Resource>/aws-sdk-php-636de7c7da46c/obj1</Resource><RequestId>172672FDAB6E902A</RequestId><HostId>dca37043-d00e-494c-ada0-507f5cc5165a</HostId></Error>"
}
(2/14) Running aws-sdk-ruby tests ... done in 7 seconds
(3/14) Running awscli tests ... done in 1 minutes and 1 seconds
(4/14) Running healthcheck tests ... done in 0 seconds
(5/14) Running mc tests ... done in 16 seconds
(6/14) Running minio-go tests ... FAILED in 19 seconds
{
  "args": {
    "bucketName": "minio-go-test-6hy3fa1wpu4wcium",
    "objectName": "l6p96209y0x9r2y2su9mk9n3g34wvb"
  },
  "duration": 687,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "GetObject()",
  "message": "CleanupBucket failed",
  "name": "minio-go: testPutObjectWithVersioning",
  "status": "FAIL"
}
(6/14) Running minio-java tests ... FAILED in 8 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, versions]",
  "duration": 312,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-39urgvn, objectName = null, resource = /minio-java-test-39urgvn, requestId = 172673177C3CA9F7, hostId = dca37043-d00e-494c-ada0-507f5cc5165a)\nrequest={method=DELETE, url=http://15.15.15.7:31353/minio-java-test-39urgvn, headers=Host: 15.15.15.7:31353\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.5\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20221111T061416Z\nAuthorization: ██\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Request-Id: 172673177C3CA9F7\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Fri, 11 Nov 2022 06:14:16 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(6/14) Running minio-js tests ... FAILED in 45 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook for \"removeObject(bucketName, objectName, removeOpts)",
  "args": "bucketName:minio-js-test-version-listbdefeed3-7750-44a7-8476-3a2de7852932",
  "duration": 7,
  "alert": "Remove 5 objects\"",
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty. You must delete all versions in the bucket. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(6/14) Running minio-py tests ... done in 1 minutes and 50 seconds
(7/14) Running s3cmd tests ... done in 16 seconds
(8/14) Running s3select tests ... done in 4 seconds
(9/14) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-kljj0gfqacit1q",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 253,
  "error": "NoSuchVersion: The specified version does not exist.\n\tstatus code: 404, request id: 172673406AFA1D0E, host id: ",
  "function": "/mint/build/versioning/put.go:256: main.testPutObjectWithTaggingAndMetadata",
  "message": "GET Object tagging expected to succeed but got NoSuchVersion: The specified version does not exist.\n\tstatus code: 404, request id: 172673406AFA1D0E, host id: ",
  "name": "versioning",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Will fix the mint tests

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#525c698e-1e32-4d29-80ac-854ce095763e) |
<a name="525c698e-1e32-4d29-80ac-854ce095763e"></a>
### 16049-7dc1b9f/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.5:32724
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp b4987f52b4f9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-go tests ... FAILED in 56 seconds
{
  "args": {
    "bucketName": "minio-go-test-waaqu14wh1pugqhh",
    "objectName": "4s3r6lfcaws3whbqvrk3ulivocfb3l",
    "prefix": "",
    "recursive": ""
  },
  "duration": 198,
  "function": "ListObjectVersions(bucketName, prefix, recursive)",
  "message": "Unexpected IsLatest field in listing objects",
  "name": "minio-go: testListObjectVersions",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 39 seconds
(9/14) Running minio-js tests ... done in 53 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 48 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-5d3h5pkob3a5mp",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 223,
  "function": "/mint/build/versioning/get.go:165: main.testGetObject",
  "message": "GetObject(2) unexpected body content",
  "name": "versioning",
  "status": "FAIL"
}

Executed 12 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Will move this PR to draft as there are some other areas that need to be fixed.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
Closing this for now as there is no clean solution for ILM.

**Pull request closed without merging**
