### PR TITLE
lock: Clear a contented lock not recognized by its owner

### PR DESCRIPTION
**Pull request by vadmeste**
When the owner of a lock unlocks this latter, the unlock in the local memory always succeed, but the network peers can still miss receiving the unlock call for any reason. The current mechanism is Refresh that will clear locks not acclaimed by its owner but it can take some time to expire. A faster way is during (R)Lock itself, so we can clear when the lock is found to be held in quorum nodes but not in the lock owner itself.

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by tdsn0007** [comment]
Hi, I think this pull will help us with one problem.

API: SYSTEM.transition
Time: 06:29:21 UTC 09/15/2024
DeploymentID: eac3dde4-5efc-4ade-a692-c1533574ac22
RequestID: 
RemoteHost: 
UserAgent: 
Error: Storage resources are insufficient for the write operation s3sp0-warm-vbr/f58e54cc82f27b54/1e/8a/1e8af457-5b65-4ebd-aee1-b5fde9b62430 (cmd.InsufficientWriteQuorum)

Backtrace: 
0: internal/logger/logger.go:268:logger.LogIf()
1: cmd/logging.go:120:cmd.transitionLogIf()
2: cmd/bucket-lifecycle.go:345:cmd.(*expiryState).Worker()


In the second pool zero errors, nothing in the logs. This is from the tier 1 pool logs.
Latest minio version in all the pools. Network is fine (zero errors) and nothing in the logs in the second pools as said before.

When this you be delivered to be tested by us.

**Comment by harshavardhana** [comment]
> Hi, I think this pull will help us with one problem.
> 
> API: SYSTEM.transition Time: 06:29:21 UTC 09/15/2024 DeploymentID: eac3dde4-5efc-4ade-a692-c1533574ac22 RequestID: RemoteHost: UserAgent: Error: Storage resources are insufficient for the write operation s3sp0-warm-vbr/f58e54cc82f27b54/1e/8a/1e8af457-5b65-4ebd-aee1-b5fde9b62430 (cmd.InsufficientWriteQuorum)
> 
> Backtrace: 0: internal/logger/logger.go:268:logger.LogIf() 1: cmd/logging.go:120:cmd.transitionLogIf() 2: cmd/bucket-lifecycle.go:345:cmd.(*expiryState).Worker()
> 
> In the second pool zero errors, nothing in the logs. This is from the tier 1 pool logs. Latest minio version in all the pools. Network is fine (zero errors) and nothing in the logs in the second pools as said before.
> 
> When this you be delivered to be tested by us.

This PR has nothing do with your logs. The PR is available as is take the patch build it yourself and use it but it won't do anything to fix your log.

**Comment by klauspost** [comment]
Without more explanation it seems like a very marginal potential improvement at the cost of a lot of complexity. Also the fact that it has "inverse scaling" (meaning more nodes will make it less effective), it doesn't seem worth it in the big picture.

I may however be misunderstanding how it works.

**Comment by harshavardhana** [comment]
> Without more explanation it seems like a very marginal potential improvement at the cost of a lot of complexity. Also the fact that it has "inverse scaling" (meaning more nodes will make it less effective), it doesn't seem worth it in the big picture.
> 
> I may however be misunderstanding how it works.

@vadmeste ^^

**Comment by vadmeste** [comment]
Closing after agreeing the complexity outweighs the benefits..

**Pull request closed without merging**
