### PR TITLE
claim exp should be integer

### PR DESCRIPTION
**Pull request by m-pavel**
## Description
Updated expiration claim should be numeric as per https://openid.net/specs/openid-connect-core-1_0.html#IDToken.

## Motivation and Context
Currently it's not possible to login to console with Oauth. Console unable to parse generated STS token since 'exp' claim encoded as string and it treated as expired.

## How to test this PR?
Try to login with Oauth

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
@m-pavel this doesn't make sense you are changing the type here.

Can you provide code which shows this information?

**Comment by harshavardhana** [comment]
A JSON number is not an integer

```
exp
REQUIRED. Expiration time on or after which the ID Token MUST NOT be accepted for processing. The processing of this parameter requires that the current date/time MUST be before the expiration date/time listed in the value. Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time. See RFC 3339 [RFC3339] for details regarding date/times in general and UTC in particular.
```

This can be a string as well, since the unmarshal attempt is based on the type of the struct being used it is not necessary to have this change.

Not sure why this is needed.

**Review by harshavardhana — APPROVED** [review]

**Comment by m-pavel** [comment]
> Not sure why this is needed.

When this kind of token comes back to minio server for validation it validated with https://github.com/golang-jwt/jwt/blob/main/map_claims.go#L37. String value is not expected there so token treated as expired.

**Comment by harshavardhana** [comment]
> > Not sure why this is needed.
> 
> When this kind of token comes back to minio server for validation it validated with https://github.com/golang-jwt/jwt/blob/main/map_claims.go#L37. String value is not expected there so token treated as expired.

It seems like they broke the promise in their API fixing the CVE.

**Comment by harshavardhana** [comment]
> > > Not sure why this is needed.
> > 
> > 
> > When this kind of token comes back to minio server for validation it validated with https://github.com/golang-jwt/jwt/blob/main/map_claims.go#L37. String value is not expected there so token treated as expired.
> 
> It seems like they broke the promise in their API fixing the CVE.

https://github.com/golang-jwt/jwt/commit/8e9d9ebf6f4a43a4ae610493f1cc0c05f5630350 here is the fix that broke this.

**Review by donatello — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Pull request merged**
