### PR TITLE
Remove unusued functions and constants

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add unusued functions and constants

## Motivation and Context
Cleanup

## How Has This Been Tested?
`make test`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by nitisht — COMMENTED** [review]
LGTM, but `s/Add unusued functions and constants/Remove unused functions and constants`

**Review by poornas — APPROVED** [review]
PR title ^^

**Comment by harshavardhana** [comment]
Done changed the title @nitisht @poornas

**Comment by nitisht** [comment]
commit message needs update as well

**Comment by harshavardhana** [comment]
> commit message needs update as well

Please fix it as you merge...

**Pull request merged**
