### PR TITLE
Per-bucket access keys

### PR DESCRIPTION
**Pull request by evangreen**
This change enables support for having a separate access key/secret per bucket.

## Motivation
Minio is quite useful, but it's challenging to properly manage bucket access when there is only a single root-level API access key. Handing out the all-access-pass master key to users is risky, as it invites abuse or mistakes from any actor using the service. Users have also been asking for such a feature, as in #5199, #5305, #4186, #2998, #811, and #2751. Responses to these requests have usually been a "no" with responses such as "this feature doesn't fit in the microservices architecture", "it's in the federated service", or "spin up multiple instances instead". I believe that with only minor changes to the overall architecture it's possible to add support for multiple keys, in a way that doesn't bloat the code or ruin the microservice flavor of minio.

## Architecture
 * The primary set of master credentials is still used for administrative backend tasks, RPCs, and as an all-access key to all buckets.
 * In addition, a single key/secret can be set for each bucket. This key can be used on the web, in v2 and v4 requests, and with the streaming API. The per-bucket keys cannot enumerate the contents or existence of other buckets. The per-bucket key is currently stored in the main config.json file. 
 * The per-bucket key cannot be used to delete the bucket or change the key.
 * For the purposes of ListBuckets, if the same API key is set for multiple buckets, then ListBuckets shows all buckets that correspond to the key used.

While this might not satisfy every possible use case, I believe it will be useful for a large population of users asking for this feature. Or at least me :)

## Outstanding issues
 * Currently only one key per bucket can be stored. This could probably be expanded with a little more effort, and some UI changes.
 * I've hijacked the password change web UI since I'm no expert in web stuff. The password change UI now controls the per-bucket key, leaving no way to change the master key/secret. This could probably be tweaked with a minimal UI change (eg a switch saying "Change per-bucket key", or maybe two buttons instead of one for "Update Bucket Key" and "Update Master Key").
 * No unit tests.
 * No documentation.

## How Has This Been Tested?
I've tested this on my local machine manually, with the web UI and the "mc" tool.

## Types of changes
- New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
> While this might not satisfy every possible use case, I believe it will be useful for a large population of users asking for this feature. Or at least me :)

@evangreen thanks for the commendable effort really appreciate the time you spent implementing this feature. To start with let me explain a few things here for more clarity

- Our implementation is going to diverge from per bucket level access keys. Minio is designed on purpose for a single tenant model i.e single access/secret key and this PR conflicts with our design model.
- We are planning to bring external identity providers like OpenID, SAML etc this would provide temporary credentials (Amazon STS) for each user but such a user conceptually doesn't exist on Minio and Minio doesn't manager users. Access keys are simply temporary and expire.  (this still keeps Minio in line with our single tenant model)

We will take this PR into consideration discuss this with the team and see how we can fit this into our design model. But for now, multiple keys per bucket is going to complicate our simple behavior.

**Comment by krishnasrinivas** [comment]
@evangreen :1st_place_medal: for the effort

**Comment by evangreen** [comment]
Thanks for taking a look at this PR. I'll be sure to check out your external identity provider hookups once they're up on Github. Sounds like this is a no for now, which is admittedly disappointing. If you do decide to take some or all of this later, I'll be around. Thanks again for making minio!

**Comment by guanzo** [comment]
@harshavardhana Any idea when the identity feature will be released?

**Comment by pruiz** [comment]
It is a shame this pull-req has been rejected, as on somewhat large deployments (with many nodes, using erasure, etc.), it is not easy to spin multiple instances on each cluster-node w/o a bit of deployment & maintenance hell.

Being able to have a single minio deployment with per-bucket keys would benefit allot in those cases.. :(

**Comment by harshavardhana** [comment]
It has not been rejected it is being discussed,  what was stated above are design challenges. We will keep everyone posted.

**Comment by harshavardhana** [comment]
@evangreen I have been trying to reach out to you regarding this PR. Would you be able to spend some time on https://slack.minio.io to discuss this? . Feel free to ping me at 'y4m4'.

**Comment by evangreen** [comment]
Whoops, I'm sorry. I was travelling when I received your last message, and lost of track of it. I've connected now on LinkedIn, so I'm happy to talk here or there.

**Comment by krishnasrinivas** [comment]
We are going to support multi access/secret keys supporting Client-Credentials-Flow of OpenID. Here is the rough idea on how it will work https://github.com/aarushiarya/minio-idp/blob/master/README.md

Implementation is underway.

**Comment by evangreen** [comment]
Will I be able to specify a simple text file of keys and buckets, without having to set up additional services? One of the things I love about minio is that it's got everything out of the box in a single binary.

**Comment by krishnasrinivas** [comment]
Not sure how it will look in the end.

Different implementation options for us without any additional IDP services:
1) `minio server --iam-policy policy.json /mnt/export`

policy.json might look like this:
```
{
  "version": 1,
  "users": [
    {
      "accessKey": "user1",
      "secretKey": "secret1",
      "policy": {
	"Version": "2012-10-17",
	"Statement": [
	  {
	    "Sid": "Stmt1530559274230",
	    "Action": [
              "s3:CreateBucket",
              "s3:DeleteBucket",
              "s3:DeleteObject",
              "s3:GetObject",
              "s3:PutObject"
	    ],
	    "Effect": "Allow",
	    "Resource": "arn:aws:s3:::user1bucket"
	  }
	]
      }
    },
    {
      "accessKey": "user2",
      "secretKey": "secret2",
      "policy": {
	"Version": "2012-10-17",
	"Statement": [
	  {
	    "Sid": "Stmt1530559274231",
	    "Action": [
              "s3:CreateBucket",
              "s3:DeleteBucket",
              "s3:DeleteObject",
              "s3:GetObject",
              "s3:PutObject"
	    ],
	    "Effect": "Allow",
	    "Resource": "arn:aws:s3:::user2bucket"
	  },
	  {
	    "Sid": "Stmt1530559274232",
	    "Action": [
              "s3:GetObject"
	    ],
	    "Effect": "Allow",
	    "Resource": "arn:aws:s3:::user1bucket"  <-- user2 can do GetObject on user1's bucket
	  },
	]
      }
    }
  ]
}
```

the individual policies here were generated by https://awspolicygen.s3.amazonaws.com/policygen.html Choose "IAM Policy" from the dropdown there.

2) the policy.json above can be embedded in config.json itself (downside is every time a user is added deleted we have to touch config.json)

3) We might have an "~/.minio/iam/" directory containing a number of user policy files. One policy file per user.

**Comment by harshavardhana** [comment]
Closing this PR we have first draft of the changes in - there is still more work that needs to be done but everyone can follow the PR here https://github.com/minio/minio/pull/6176

**Pull request closed without merging**
