### PR TITLE
Allow specifying the local server with env variable _MINIO_SERVER_LOCAL

### PR DESCRIPTION
**Pull request by allanrogerr**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
For containerized systems where the hostname cannot be resolved to local IP, this PR introduces a change allowing the specifying of the local server with env variable `_MINIO_SERVER_LOCAL`

## Motivation and Context
In this sort of containerized system, e.g. a kubernetes cluster within which minio pods is running on nodes on different networks, the internal IP address of the pod is not resolvable from any hostname, accessible externally. Therefore minio is not able to recognize itself within the pool of hosts as no endpoint can be resolved to it's own IP address.

A workaround would be to perform the resolution manually by editing `/etc/hosts/` and assigning a consecutive host resolving to the pod ip address. e.g.
`<ip of k8s pod>     <hostname>.<domain>`
e.g.
`10.42.0.11     minio-18825-1.lab.min.dev`

## How to test this PR?
See example here: https://github.com/allanrogerr/public/wiki/minio%E2%80%9018825
1.- Pull and compile http://github.com/allanrogerr/minio.git on several k8s pods
2.- Run minio on all pods e.g.
```
CI=on \
_MINIO_SERVER_LOCAL=minio-18825-1.lab.min.dev:9000 \
~/github/minio/minio server https://minio-18825-{0...1}.lab.min.dev:9000/tmp/data{1...2} --address :9000 --console-address :9090 --certs-dir ~/.minio/certs
```
3.- Observe the minio cluster online

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by allanrogerr** [comment]
Fixes https://github.com/minio/minio/issues/18825

**Review by zveinn — APPROVED** [review]

**Comment by klauspost** [comment]
This seems like a can of worms. AFAICT you can really f up an install with this.

> For systems where the hostname cannot be resolved to local IP

It sounds to me like this is the actual issue. It sounds like a nasty workaround to have to push individual (unmatching) env vars to a deployment.  I am by no means an expert on this, but it is a red flag for me.

**Comment by zveinn** [comment]
> This seems like a can of worms. AFAICT you can really f up an install with this.
> 
> > For systems where the hostname cannot be resolved to local IP
> 
> It sounds to me like this is the actual issue. It sounds like a nasty workaround to have to push individual (unmatching) env vars to a deployment. I am by no means an expert on this, but it is a red flag for me.

He's just letting the local be defined right ? .. I mean, sure.. if you're running re-deployments and hostnames change, you're install has a good chance of getting messed up. But I think that applies to many other things too ? 

But I will agree with Klaus on one thing, the original issue seems to be that the local hostname is not resolvable. even within kubernetes the pod/container hostnames should be resolvable ? at least that how I remember it. 

Maybe we're missing more context ?

**Comment by klauspost** [comment]
@zveinn Yeah. Without context it seems like many other things could fail - and per sever env vars just seems like a recipe for misconfiguration.

**Comment by allanrogerr** [comment]
The internal k8s network has its own way of resolving its own hostnames. Within that internal network a pod can know that hostname - so host 10-42-0-10.minio-ns.pod.cluster.local is resolvable locally, but cannot be resolved externally. If we use the the external hostname e.g. node1.min.dev, the dns resolution works for each pod, but each pod cannot determine which of these external hostnames is itself.

I will make this code explicitly work only for containerised solutions. This should minimise any mixups.
Note that the only other workaround is modifying /etc/hosts or perhaps /etc/resolv.conf

**Comment by harshavardhana** [comment]
This issue is about being able to run a cluster where the local for an endpoint cannot be determined by regular means where a DNS resolves to an IP which is not local to you but more elastic in nature.

This applies to many situations however this environment value is just a hack to circumvent that requirement that's why it's an experimental flag.

It's useful only for situations where above is trust and none of the normal deployments would need it.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
And on top of that it's even more self constrained to be honored only for k8s/docker environments which have this problem.

- docker swarm + docker stack deployment face this issue
- k8s multi-cluster deployments

**Pull request merged**
