### PR TITLE
Add new extended list of JWT keys from OpenID group

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add the new extended list of JWT keys from OpenID group

## Motivation and Context
https://www.iana.org/assignments/jwt/jwt.xhtml#claims

## How to test this PR?
Claims which match the supported list as part of the IAM policies

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0f8c626a-9b68-4976-b9a8-436d288bbb28) |
| mint-worm.sh | :x: [more...](#e85fdfd7-60d7-4533-9116-be81a9d88716) |
| mint-gateway-azure.sh | :x: [more...](#4b49def7-fdbd-48e4-8d59-0e3372c21b1a) |
<a name="e85fdfd7-60d7-4533-9116-be81a9d88716"></a>
### 9087-1f3b792/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31617
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bc20709bb697:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-v0rk9uhkvndx0xkmjncfei49j43u3vg5nlezog8s58ddfy25luo9jos",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120296,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31617/bucket-v0rk9uhkvndx0xkmjncfei49j43u3vg5nlezog8s58ddfy25luo9jos: dial tcp 72.28.97.55:31617: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="4b49def7-fdbd-48e4-8d59-0e3372c21b1a"></a>
### 9087-1f3b792/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32456
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ee6c3708d9e8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 35 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... FAILED in 3 minutes and 27 seconds
{
  "name": "awscli",
  "duration": 1534,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 14 tests successfully.
```
<a name="0f8c626a-9b68-4976-b9a8-436d288bbb28"></a>
### 9087-1f3b792/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32531
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4f5413d952a7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 9 seconds
(5/14) Running awscli tests ... done in 2 minutes and 23 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... FAILED in 12 minutes and 39 seconds
{
  "args": {},
  "duration": 89382,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#03426024-52ab-4407-996c-0fc31f46707b) |
| mint-worm.sh | :x: [more...](#ad0cf0bd-5f17-47bc-8343-e3e6aae9ae34) |
| mint-gateway-azure.sh | :x: [more...](#9262bf37-cd1a-460f-b8c5-96eb49c404f5) |
<a name="ad0cf0bd-5f17-47bc-8343-e3e6aae9ae34"></a>
### 9087-9f34716/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30470
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8938955e395a:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-i0onxcrn9w35vwossootrfq4ikcdrrxrr156242eiziq6ilxap40tmg",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120276,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30470/bucket-i0onxcrn9w35vwossootrfq4ikcdrrxrr156242eiziq6ilxap40tmg: dial tcp 72.28.97.55:30470: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="03426024-52ab-4407-996c-0fc31f46707b"></a>
### 9087-9f34716/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30111
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5d15454d19fe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 23 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... FAILED in 13 minutes and 20 seconds
{
  "args": {},
  "duration": 76189,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="9262bf37-cd1a-460f-b8c5-96eb49c404f5"></a>
### 9087-9f34716/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32596
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ba6d9da6d171:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 19 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 42 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/14) Running minio-go tests ... done in 21 minutes and 31 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 29 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11929,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3gpkf3j, objectName=minio-java-test-1345d8a, resource=/minio-java-test-3gpkf3j/minio-java-test-1345d8a, requestId=15F948A4C83C9502, hostId=50ff3711-7602-47e8-8aa8-32a654375b51)\nrequest={method=PUT, url=http://72.28.97.56:32596/minio-java-test-3gpkf3j/minio-java-test-1345d8a?uploadId=36fdb5aa9f94d2a0&partNumber=1, headers=x-amz-copy-source-if-match: db63d3403a4b78f590bda7cea751c8f6-2\nx-amz-copy-source: minio-java-test-3gpkf3j/minio-java-test-6vegvb\nAccept-Encoding: identity\nHost: 72.28.97.56:32596\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200305T025016Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200305/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-05T01-44-17Z\nVary: Origin\nX-Amz-Request-Id: 15F948A4C83C9502\nX-Xss-Protection: 1; mode=block\nDate: Thu, 05 Mar 2020 02:50:16 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#5db0241b-0571-43f6-8ab5-4dd5784f4448) |
| mint-gateway-azure.sh | :x: [more...](#6bbc7803-d924-4581-9142-dbf535ce92ef) |
| mint-gateway-nas.sh | :x: [more...](#8d35ab69-58f3-42e7-89c8-cd78396e9bd3) |
<a name="6bbc7803-d924-4581-9142-dbf535ce92ef"></a>
### 9087-594de32/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30997
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f32e373b9cc9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 32 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 3 minutes and 33 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 25 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/14) Running minio-go tests ... done in 19 minutes and 46 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 14 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11424,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-21dhdca, objectName=minio-java-test-51epio, resource=/minio-java-test-21dhdca/minio-java-test-51epio, requestId=15F94CD4F4BAEEE9, hostId=740584f3-f8cc-4075-b6e1-d3347efe757b)\nrequest={method=PUT, url=http://72.28.97.53:30997/minio-java-test-21dhdca/minio-java-test-51epio?uploadId=74482fb2dcfee63d&partNumber=1, headers=x-amz-copy-source-if-match: a6fa4612863bcb5976cfc187551b9cb2-2\nx-amz-copy-source: minio-java-test-21dhdca/minio-java-test-2chtdjh\nAccept-Encoding: identity\nHost: 72.28.97.53:30997\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200305T040701Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200305/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-05T03-02-47Z\nVary: Origin\nX-Amz-Request-Id: 15F94CD4F4BAEEE9\nX-Xss-Protection: 1; mode=block\nDate: Thu, 05 Mar 2020 04:07:01 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="5db0241b-0571-43f6-8ab5-4dd5784f4448"></a>
### 9087-594de32/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30692
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3a3e3902bbf9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 42 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... FAILED in 14 minutes and 36 seconds
{
  "args": {},
  "duration": 110198,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="8d35ab69-58f3-42e7-89c8-cd78396e9bd3"></a>
### 9087-594de32/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31080
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3f3ad4f2b7b8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yjniphgwjyt6jg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120381,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31080/aws-sdk-go-test-yjniphgwjyt6jg: dial tcp 72.28.97.55:31080: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by aead — APPROVED** [review]

**Pull request merged**
