### PR TITLE
Honor and support bucket policies for all gateway backends.

### LINKED ISSUE #4763: gateway: Bucket policies set from webUI are not honored on Browser
All gateway backends honor the minimum requirement of atleast read-only policy, if a user tries to the reach the URL directly from the browser for any gateway backend should work. i.e it should listObjects and objects should be downloadable. 

This should work for Azure, S3 backend properly. GCS currently doesn't work properly due to bucket policy implementation issue.

## Expected Behavior
Works properly like FS and Erasure mode minio server. 

## Current Behavior
Does not work and returns error by throwing the login page. 

## Possible Solution
Implement bucket policies properly for gateway layer.

## Steps to Reproduce (for bugs)
Set a policy using Minio browser to read-only with prefix as `*` and then access such a bucket from Minio browser.

## Context
Gateway testing.

## Your Environment
Current master branch and all gateway releases.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Currently we did not have proper bucket policies
supported on all gateway backends due to the
fact that globalBucketPolicies object was
never initialized.

## Motivation and Context
Fixes #4763

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ckuetbach** [comment]
This PR made my Tests for #4763 in C# go green, without any new errors.

**Comment by harshavardhana** [comment]
Can you guys review @krishnasrinivas @krisis this PR?

**Review by krishnasrinivas — COMMENTED** [review]
Discussed with @harshavardhana this needs further discussion on the implementation because if there are multiple gateway instances, then set/delete bucket policy don't get updated to the peers.

**Comment by harshavardhana** [comment]
Closing this. as this requires a full change in the backend structure.

**Pull request closed without merging**
