### PR TITLE
Add docker release files.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
We used to release by building directly on the docker
hub auto build process, which is sufficient for edge
but it is not a good idea to do it for stable releases.

## Motivation and Context
Do not build docker release binaries again, but instead
use the released binaries themselves which are signed
and validated.

## How Has This Been Tested?
Manually and using `docker build` 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
This PR is on hold until we decide to make a release cut, the changes presented in this PR are only applicable with the upcoming release.  The `Dockerfile` present in this PR cannot be used directly with existing released binaries since they are not fully statically compiled so cannot be used directly in alpine linux.

**Comment by vadmeste** [comment]
It looks like there is an error somewhere.

This is how I built the docker image:
```
$ docker build -t localminiorelease -f Dockerfile.release .
```
But when I try to test the image:
```
$ docker run localminiorelease version
/usr/bin/docker-entrypoint.sh: exec: line 81: minio: not found
```

Though with the last released image, it works normally:
```
$ docker run minio/minio version
Version: 2017-05-05T01:14:51Z
Release-Tag: RELEASE.2017-05-05T01-14-51Z
Commit-ID: 40985cc4e3eec06b7ea82dc34c8d907fd2e7aa12
```

**Comment by harshavardhana** [comment]
> $ docker run localminiorelease version
> /usr/bin/docker-entrypoint.sh: exec: line 81: minio: not found

@vadmeste as i explained in my previous comment it won't work with current release.

**Comment by vadmeste** [comment]
> @vadmeste as i explained in my previous comment it won't work with current release.

yes I understand the issue now. `minio: not found` error is confusing.

**Comment by harshavardhana** [comment]
> yes I understand the issue now. minio: not found error is confusing.

Unfortunately yes,  if you don't have the `ld-linux` then this is the error you get on your Linux.

**Review by nitisht — APPROVED** [review]
Tried locally with statically built binary. LGTM

**Review by vadmeste — APPROVED** [review]
LGTM and tested

**Pull request merged**
