### PR TITLE
Add endpoint option for FTP mode

### PR DESCRIPTION
**Pull request by pablo-ruth**
## Description

This PR add an option to configure the endpoint used to call Minio when using FTP/SFTP mode.

```
minio server http://server{1...4}/disk{1...4} \
--ftp="address=:8021" \
--ftp="passive-port-range=30000-40000" \
--ftp="endpoint=minio.mycorp.org:9000"
```

## Motivation and Context

PR #16952 added support of FTP/SFTP protocols, but the endpoint used to do Minio HTTP call is hardcoded to 127.0.0.1 [code](https://github.com/minio/minio/blob/dd9ed85e22b6f0668c2c079eb0b56ef12e47f941/cmd/ftp-server-driver.go#L48). It can cause an issue when using Minio over HTTPS if the TLS certificate doesn't have an IP SAN for the localhost IP (this is the case when using a certificate from a public CA).

```
Command:	MLSD
Response:	550 Get "https://127.0.0.1:9000/": tls: failed to verify certificate: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

So using this endpoint option, we can use the public name of the Minio instance and the certificate can be validated.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
There is a better way to do this, will send a PR without adding a new option here.

**Comment by pablo-ruth** [comment]
ok @harshavardhana, what's the better way ?

**Comment by pablo-ruth** [comment]
Hello @harshavardhana @klauspost,

Any news? I can propose a new PR if you explain what's the better way.

Thanks

**Pull request closed without merging**
