### PR TITLE
Checking for access denied in web browser request.

### LINKED ISSUE #9485: Browser: "not enough permission" error is  masked with "internal error"
When a browser user, who does not have object delete permit/policy, attempts to delete an object, the attempted delete action ends up with a very generic error message, which does not give any clue to the user about what really went wrong. 

Selection_006

Here are the console error messages we actually captured at the backend:
API: WebRemoveObject(bucket=bucket)
Time: 01:36:47 PDT 04/29/2020
DeploymentID: 4c2e1c3d-fcab-414a-8414-0a164015471d
RemoteHost: ::1
Host: localhost:9000
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
**Error: Do not have enough permissions to access this resource**
       3: github.com/minio/minio@/cmd/web-handlers.go:2250:cmd.toWebAPIError()
       2: github.com/minio/minio@/cmd/web-handlers.go:2121:cmd.toJSONError()
       1: github.com/minio/minio@/cmd/web-handlers.go:744:cmd.(*webAPIHandlers).RemoveObject()

API: WebRemoveObject(bucket=bucket)
Time: 01:36:47 PDT 04/29/2020
DeploymentID: 4c2e1c3d-fcab-414a-8414-0a164015471d
RemoteHost: ::1
Host: localhost:9000
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
**Error: Do not have enough permissions to access this resource**
       5: github.com/minio/minio@/cmd/api-errors.go:1824:cmd.toAPIErrorCode()
       4: github.com/minio/minio@/cmd/api-errors.go:1849:cmd.toAPIError()
       3: github.com/minio/minio@/cmd/web-handlers.go:2251:cmd.toWebAPIError()
       2: github.com/minio/minio@/cmd/web-handlers.go:2121:cmd.toJSONError()
       1: github.com/minio/minio@/cmd/web-handlers.go:744:cmd.(*webAPIHandlers).RemoveObject()

Better error messaging would eliminate `Subnet` queries and waste of engineering time.

## Expected Behavior
The captured internal error message should not be masked and passed to the browser to be displayed to the end-user.

## Current Behavior
The error message captured at the back-end, `"Error: Do not have enough permissions to access this resource"`, is masked with `"We encountered an internal error. Please try again."`. This basically means no information or clue for the end-user.

## Possible Solution
Pass the captured error message to the browser unit so that a meaningful error message can be displayed at the browser.

## Steps to Reproduce (for bugs)
Have a user with no delete permit/policy delete an object an see the displayed error message.
Or have any user try to delete an object with retention defined as `Compliance` mode.

## Regression
No

## Your Environment
MinIO server, FS, build from top of the master

### PR DESCRIPTION
**Pull request by BigUstad**
Fixes #9485

## How to test this PR?
One possible/easy way to test: Create/Put/Copy objects to a bucket that can be locked and is locked. Try to delete the object(s) copied in browser. Instead of seeing 'We encountered an internal error. Please try again.' you should see a more appropriate message.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#2f70817a-af89-43f8-b7e5-9aeeb3a2d2f4) |
| mint-gateway-azure.sh | :x: [more...](#98eed32b-b68f-475f-ba29-96434b45db87) |
| mint-gateway-nas.sh | :x: [more...](#aac3926b-a021-495e-9b1a-36cde38789ee) |
<a name="aac3926b-a021-495e-9b1a-36cde38789ee"></a>
### 9523-72da610/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32131
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fb8770f5d5bb:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 3 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 9 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... FAILED in 11 seconds
{}
(9/15) Running minio-java tests ... FAILED in 19 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 31,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-2u8dblm, objectName = minio-java-test-206qnbr, resource = /minio-java-test-2u8dblm/minio-java-test-206qnbr, requestId = 160C38364C174232, hostId = 509d2121-9c68-4060-a3f8-343a5c0f2ff3)\nrequest={method=PUT, url=http://minio-dev7.minio.io:32131/minio-java-test-2u8dblm/minio-java-test-206qnbr?legal-hold=, headers=Host: minio-dev7.minio.io:32131\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200505T192254Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200505/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160C38364C174232\nX-Xss-Protection: 1; mode=block\nDate: Tue, 05 May 2020 19:22:54 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 28 seconds
(10/15) Running minio-py tests ... done in 51 seconds
(11/15) Running s3cmd tests ... done in 13 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="2f70817a-af89-43f8-b7e5-9aeeb3a2d2f4"></a>
### 9523-72da610/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31076
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 56d73896ef1d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 3 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 10 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... FAILED in 13 seconds
{}
(9/15) Running minio-java tests ... FAILED in 33 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 50,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-1u8ap7n, objectName = minio-java-test-1r9ab15, resource = /minio-java-test-1u8ap7n/minio-java-test-1r9ab15, requestId = 160C384813DD58A7, hostId = 7b2c1cd8-9ad3-4cd9-8f67-f49660c3010c)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31076/minio-java-test-1u8ap7n/minio-java-test-1r9ab15?legal-hold=, headers=Host: minio-dev7.minio.io:31076\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200505T192410Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200505/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160C384813DD58A7\nX-Xss-Protection: 1; mode=block\nDate: Tue, 05 May 2020 19:24:10 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 29 seconds
(10/15) Running minio-py tests ... done in 56 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 0 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="98eed32b-b68f-475f-ba29-96434b45db87"></a>
### 9523-72da610/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32656
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp de1c82e8784e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 9 minutes and 50 seconds
(4/15) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 4 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 242595.07,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}
(4/15) Running awscli tests ... FAILED in 49 seconds
{
  "name": "awscli",
  "duration": 3720,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32656 s3api copy-object --bucket awscli-mint-test-bucket-10340 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-10340/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(4/15) Running healthcheck tests ... done in 0 seconds
(5/15) Running mc tests ... done in 3 minutes and 37 seconds
(6/15) Running minio-dotnet tests ... done in 3 minutes and 7 seconds
(7/15) Running minio-go tests ... FAILED in 5 minutes and 21 seconds
{}
(7/15) Running minio-java tests ... FAILED in 28 minutes and 5 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1739,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-3r42sfv, objectName = minio-java-test-32bju1d, resource = /minio-java-test-3r42sfv/minio-java-test-32bju1d, requestId = 160C3B0E32681492, hostId = a0b253e4-f60b-46c3-a95a-22dcae97a3f8)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32656/minio-java-test-3r42sfv/minio-java-test-32bju1d?legal-hold=, headers=Host: minio-dev6.minio.io:32656\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200505T201500Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200505/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160C3B0E32681492\nX-Xss-Protection: 1; mode=block\nDate: Tue, 05 May 2020 20:15:00 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(7/15) Running minio-js tests ... FAILED in 7 minutes and 39 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-69db0bb0-1904-4b19-a03d-9b18ace3e4b9, recursive:true",
  "duration": 210,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(7/15) Running minio-py tests ... done in 12 minutes and 30 seconds
(8/15) Running s3cmd tests ... FAILED in 44 seconds
{
  "name": "s3cmd",
  "duration": "1726",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(8/15) Running s3select tests ... done in 22 seconds
(9/15) Running security tests ... done in 0 seconds

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by ebozduman — APPROVED** [review]
Reviewed and tested the fix.
It works.
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
Please rebase the PR with master @BigUstad

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#9ca7f1fb-4902-41ed-ad81-ffb503e27af9) |
| mint-gateway-azure.sh | :x: [more...](#9c2b433a-fae7-400b-bb36-e3ba73b47eb4) |
| mint-gateway-nas.sh | :x: [more...](#9c0c5478-c383-4172-82c1-9796aa2dd854) |
<a name="9c0c5478-c383-4172-82c1-9796aa2dd854"></a>
### 9523-8525818/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32519
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ba72bd4d626a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 25 seconds
(8/15) Running minio-dotnet tests ... done in 35 seconds
(9/15) Running minio-go tests ... FAILED in 39 seconds
{}
(9/15) Running minio-java tests ... FAILED in 23 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 28,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-3rvcq2g, objectName = minio-java-test-1ju2r1f, resource = /minio-java-test-3rvcq2g/minio-java-test-1ju2r1f, requestId = 160C960912C77744, hostId = 022989b4-e67b-4762-8857-245ed4b897bb)\nrequest={method=PUT, url=http://minio-c3.minio.io:32519/minio-java-test-3rvcq2g/minio-java-test-1ju2r1f?legal-hold=, headers=Host: minio-c3.minio.io:32519\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T000214Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160C960912C77744\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 00:02:14 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 30 seconds
(10/15) Running minio-py tests ... done in 55 seconds
(11/15) Running s3cmd tests ... done in 17 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="9c2b433a-fae7-400b-bb36-e3ba73b47eb4"></a>
### 9523-8525818/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31701
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d6fa9f996f3a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 11 minutes and 16 seconds
(4/15) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 3 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 242338.94,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}
(4/15) Running awscli tests ... FAILED in 49 seconds
{
  "name": "awscli",
  "duration": 4061,
  "function": "aws --endpoint-url http://minio-dev3.minio.io:31701 s3api copy-object --bucket awscli-mint-test-bucket-27697 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-27697/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(4/15) Running healthcheck tests ... done in 1 seconds
(5/15) Running mc tests ... done in 3 minutes and 35 seconds
(6/15) Running minio-dotnet tests ... done in 3 minutes and 8 seconds
(7/15) Running minio-go tests ... FAILED in 4 minutes and 24 seconds
{}
(7/15) Running minio-java tests ... FAILED in 29 minutes and 53 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 2075,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-4i552v, objectName = minio-java-test-2gr19v0, resource = /minio-java-test-4i552v/minio-java-test-2gr19v0, requestId = 160C98E614F115ED, hostId = 8bac89c7-b61a-4413-8f83-d63ed45e6169)\nrequest={method=PUT, url=http://minio-dev3.minio.io:31701/minio-java-test-4i552v/minio-java-test-2gr19v0?legal-hold=, headers=Host: minio-dev3.minio.io:31701\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T005442Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160C98E614F115ED\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 00:54:42 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(7/15) Running minio-js tests ... FAILED in 8 minutes and 16 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-c0a831b6-5175-4260-9e61-41716682de71, recursive:true",
  "duration": 207,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(7/15) Running minio-py tests ... done in 13 minutes and 6 seconds
(8/15) Running s3cmd tests ... FAILED in 42 seconds
{
  "name": "s3cmd",
  "duration": "1653",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(8/15) Running s3select tests ... done in 22 seconds
(9/15) Running security tests ... done in 0 seconds

Executed 9 out of 15 tests successfully.
```
<a name="9ca7f1fb-4902-41ed-ad81-ffb503e27af9"></a>
### 9523-8525818/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30654
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3483b2c2e8c8:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 20 seconds
{
  "name": "awscli",
  "duration": 4443,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30654 s3api get-object --bucket awscli-mint-test-bucket-1793 --key awscli-mint-test-bucket-1793-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "Etag mismatch for multipart 0 byte object"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 16 seconds
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... FAILED in 30 seconds
{}
(8/15) Running minio-java tests ... FAILED in 26 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 33,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-gs58e8, objectName = minio-java-test-q4ju9e, resource = /minio-java-test-gs58e8/minio-java-test-q4ju9e, requestId = 160C95EC0E6BFCA8, hostId = 45134bdc-5921-4ce4-af27-7697b4e3b54c)\nrequest={method=PUT, url=http://minio-c3.minio.io:30654/minio-java-test-gs58e8/minio-java-test-q4ju9e?legal-hold=, headers=Host: minio-c3.minio.io:30654\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T000009Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 380\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160C95EC0E6BFCA8\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 00:00:09 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... done in 33 seconds
(9/15) Running minio-py tests ... done in 1 minutes and 2 seconds
(10/15) Running s3cmd tests ... done in 1 minutes and 2 seconds
(11/15) Running s3select tests ... done in 1 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Pull request merged**
